### ISSUE TITLE
Table组件

### ISSUE THREAD

**Issue by linrencai** [vbenjs/vue-vben-admin#1030]
问题：切换tab页时，表格滚动条位置会重置回到最顶部
建议：是否有现成的解决办法？或者增加此项需求

**Comment by wlc11070108** [comment]
同问

**Comment by linrencai** [comment]
`<template> <BasicTable  ref="scrollRef"/> </template>
<script lang="ts">
  import { useEventListener } from '/@/hooks/event/useEventListener';
const scrollRef = ref<HTMLDivElement | null>(null);
      const offsetTop = ref(0);
 function onScroll() {
        const wrapEl: any = unref(scrollRef);
        if (!wrapEl) {
          return;
        }
        offsetTop.value = wrapEl.$el.querySelector('.ant-table-body').scrollTop;
      }
 onMounted(async () => {
        nextTick(() => {
          const wrapEl: any = unref(scrollRef);
          if (!wrapEl) {
            return;
          }
          useEventListener({
            el: wrapEl.$el.querySelector('.ant-table-body'),
            name: 'scroll',
            listener: onScroll,
            wait: 100,
          });
        });
      });
onActivated(() => {
        nextTick(() => {
          if (offsetTop.value) {
            const wrapEl: any = unref(scrollRef);
            if (!wrapEl) {
              return;
            }
            wrapEl.$el.querySelector('.ant-table-body').scrollTo({
              top: offsetTop.value,
              left: 0,
              behavior: 'smooth',
            });
          }
        });
      });
return{  scrollRef,
      };
</script>
`


希望各位大佬有改进的回复下~~
