### ISSUE TITLE
table中的checkbox点击响应非常慢

### ISSUE THREAD

**Issue by luger1990** [vbenjs/vue-vben-admin#1084]
table组件中的checkbox `rowSelection: { type: 'checkbox', onChange: onSelectChange },` 点击复选中响应非常慢。性能差的电脑上要等很久才有响应。

**Comment by kunimitsu2** [comment]
【系统管理】/【账号管理】，展开收缩表格也很慢

**Comment by cnhuye** [comment]
遇到同样的问题。不太清楚是不是 antv 本身的问题。
测试发现 checkbox 点击后，整个表格包括 pagination 都会 re-render ，导致点一下 checkbox 可能需要 600+ms 才能执行完。

**Comment by luger1990** [comment]
> 遇到同样的问题。不太清楚是不是 antv 本身的问题。
> 
> 测试发现 checkbox 点击后，整个表格包括 pagination 都会 re-render ，导致 checkbox click 可能需要 600+ms 才能执行完。
> 
> 尝试删除 `pagination/actionColumn/ rowSelection 中的 { selectedRowKeys:checkedKeys } ` 部分，再点击 checkbox 才能较快的反馈，click 过程大概150ms。

应该不是antdv的问题。我试了试antdv里面的table  checbox没问题。我是个后端server研发~ 想解决这个问题有点困难，所以提了个问题。

**Comment by luger1990** [comment]
除了点击这个checkbox响应慢，如果table设置了filters 点击筛选也会很慢。

**Comment by mynetfan** [comment]
> > 遇到同样的问题。不太清楚是不是 antv 本身的问题。
> > 
> > 测试发现 checkbox 点击后，整个表格包括 pagination 都会 re-render ，导致 checkbox click 可能需要 600+ms 才能执行完。
> > 
> > 尝试删除 `pagination/actionColumn/ rowSelection 中的 { selectedRowKeys:checkedKeys } ` 部分，再点击 checkbox 才能较快的反馈，click 过程大概150ms。
> 
> 应该不是antdv的问题。我试了试antdv里面的table  checbox没问题。我是个后端server研发~ 想解决这个问题有点困难，所以提了个问题。

你要测试antdv的话也需要设置rowSelection中的selectedRowKeys才有可比性。这个问题跟树形表格的展开收缩卡顿问题一样，使用了受控属性来管理选中状态和展开状态时就会有这种问题。

**Comment by mynetfan** [comment]
这几个类似问题稍候统一跟踪一下看看应该怎么处理

**Comment by luger1990** [comment]
> > > 遇到同样的问题。不太清楚是不是 antv 本身的问题。
> > > 测试发现 checkbox 点击后，整个表格包括 pagination 都会 re-render ，导致 checkbox click 可能需要 600+ms 才能执行完。
> > > 尝试删除 `pagination/actionColumn/ rowSelection 中的 { selectedRowKeys:checkedKeys } ` 部分，再点击 checkbox 才能较快的反馈，click 过程大概150ms。
> > 
> > 
> > 应该不是antdv的问题。我试了试antdv里面的table  checbox没问题。我是个后端server研发~ 想解决这个问题有点困难，所以提了个问题。
> 
> 你要测试antdv的话也需要设置rowSelection中的selectedRowKeys才有可比性。这个问题跟树形表格的展开收缩卡顿问题一样，使用了受控属性来管理选中状态和展开状态时就会有这种问题。

哈哈哈 不好意思 我是服务端研发，对vue了解的还是不透彻。期待大神修复这个问题。

**Comment by sicun-github** [comment]
所以这个问题解决了吗 今天看一样有

**Comment by playadmin** [comment]
同样的问题，响应非常慢

**Comment by Weilence** [comment]
我也碰到了这个问题，尝试升级到最新版2.7.2，但是目前2.7.2的hmr有问题:joy:

**Comment by DreamBuddy** [comment]
@Weilence 我现在3.2.33 依然卡顿

**Comment by wangjue666** [comment]
在vben的`2.10.1` 版本下不会有响应慢的问题了
