### ISSUE TITLE
希望集成动态表单设计

### ISSUE THREAD

**Issue by Garens** [vbenjs/vue-vben-admin#1088]
希望集成类似https://form.nutflow.vip/
这样的表单设计，现在没有一个好点的替代产品。

**Comment by andyqier88** [comment]
个人理解，楼主给的nutflow动态生成表单，类似表单的低代码平台了。
使用vben以来，在vban里目前动态生成表单可借助useForm 里的appendSchemaByField，表单数据以json方式存在后端，前端拿到数据通过appendSchemaByField循环出来表单

**Comment by Garens** [comment]
拖动排序的插件，哪一个比较好用呢？

**Comment by Garens** [comment]
> 个人理解，楼主给的nutflow动态生成表单，类似表单的低代码平台了。
> 使用vben以来，在vban里目前动态生成表单可借助useForm 里的appendSchemaByField，表单数据以json方式存在后端，前端拿到数据通过appendSchemaByField循环出来表单

拖动排序的插件，哪一个比较好用呢？

**Comment by kongsiyu** [comment]
框架已经实现了配置化生产form，你只需要实现设计器的表单json转换城FormSchema配置就可以了，另外要改一改你那个表单设计器的设计字段去配置绑定字段和数据源

**Comment by datasre** [comment]
有表单生成器没？
