### ISSUE TITLE
Table 表格无法固定选择列

### ISSUE THREAD

**Issue by mcguire-w** [vbenjs/vue-vben-admin#1089]
![image](https://user-images.githubusercontent.com/48664370/129694820-8fed6184-2140-4b0a-8d6f-c9e6c24edda7.png)

https://user-images.githubusercontent.com/48664370/129694733-f721cd77-2bca-46b9-9533-3cfef34efdf0.mp4

**Comment by mynetfan** [comment]
Ant design vue的table的BUG，等待更新
