### ISSUE TITLE
目前完整版demo系统管理-菜单管理，表格的展开和收缩很卡

### ISSUE THREAD

**Issue by MilkSunshine** [vbenjs/vue-vben-admin#1100]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

系统管理-菜单管理，点击表格展开与收缩

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统: macos big sur 11.2.3
- Node 版本: 12.16.2
- 包管理器 (npm/yarn/pnpm) 及其版本: npm 7.15.1

**Comment by guxin-org** [comment]
同问,在对接后端接口后,增加了展开收缩操作,发现触发时有明显卡顿,且无loading加载

操作系统:win10 专业版 64位
浏览器:Google Chrome 92.0.4515.159（正式版本）（64 位）
Node 版本:  @v12.22.1

**Comment by AndroidMilk** [comment]
目前定位到的问题应该是表格默认展开全部以后会出现卡顿情况，应该是expandAll方法有问题，还有一个bug，就是antd的表格属性defaultExpandAllRows无法起到效果！

**Comment by AndroidMilk** [comment]
> 同问,在对接后端接口后,增加了展开收缩操作,发现触发时有明显卡顿,且无loading加载
> 
> 操作系统:win10 专业版 64位
> 浏览器:Google Chrome 92.0.4515.159（正式版本）（64 位）
> Node 版本: @v12.22.1

目前解决办法暂时不让树形表格全部展开，默认收缩

**Comment by mynetfan** [comment]
> 目前定位到的问题应该是表格默认展开全部以后会出现卡顿情况，应该是expandAll方法有问题，还有一个bug，就是antd的表格属性defaultExpandAllRows无法起到效果！

defaultExpandAllRows 不会起作用在文档中已有说明。

**Comment by mynetfan** [comment]
不是expandAll有问题，是使用受控展开属性时会慢。如果你不需要basicTable提供的expandAll功能，可以直接将isTreeTable设为false，由table自己管理展开状态，这样就会快很多

**Comment by AndroidMilk** [comment]
> 不是expandAll有问题，是使用受控展开属性时会慢。如果你不需要basicTable提供的expandAll功能，可以直接将isTreeTable设为false，由table自己管理展开状态，这样就会快很多

👌，好的

**Comment by cuteCloud** [comment]
你有发现稍微复杂点的表格 点击查询后到loading效果出现要延迟一会儿吗

**Comment by AndroidMilk** [comment]
复杂点的表格，有demo吗

**Comment by cuteCloud** [comment]
> 复杂点的表格，有demo吗

release下载2.7.1 版本包 菜单管理页面 本地dev开发环境下，点击查询按钮会过几秒才出现loading

**Comment by ljw-codeking** [comment]
> > 复杂点的表格，有demo吗
> 
> release下载2.7.1 版本包 菜单管理页面 本地dev开发环境下，点击查询按钮会过几秒才出现loading

>> 确实是的，我这里也是一样
