### ISSUE TITLE
打包时出现警告

### ISSUE THREAD

**Issue by wl19** [vbenjs/vue-vben-admin#1130]
![image](https://user-images.githubusercontent.com/51466251/130922289-c0167832-285a-4cec-8679-f82fa52b8446.png)
拉取最新代码进行打包

**Comment by waney** [comment]
![1 (2)](https://user-images.githubusercontent.com/69211/131204311-abae22a0-922b-4206-b5e1-ac4d33d426d8.png)

更新后情况并没有改变。 @mynetfan

**Comment by waney** [comment]
![12312](https://user-images.githubusercontent.com/69211/131204481-a019f80d-c252-49a7-b57a-025f186a5629.png)
这是刚刚全新拉下来的 build 截图。
