### ISSUE TITLE
精简版: VITE_LEGACY = true 打包后, 文件hash错误: 例如index-legacy.6ba8da47.js

### ISSUE THREAD

**Issue by Lance-Hu** [vbenjs/vue-vben-admin#1163]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [√ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [√ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [√ ] 已在 Issues 中搜索了相关的关键词
- [√ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

启用VITE_LEGACY=true,运行脚本preview;在Chrome浏览器v55.0.2883.87 访问网页, 会发现部分文件的hash错误, 导致资源访问不到.
而尝试用vue3的命令行创建一个新的vite项目, 同样也使用了@vitejs/plugin-legacy插件.但没有上述问题.

### 复现 Bug

使用精简版最新的代码可以复现该问题
## 系统信息

- 操作系统: win10(x64)
- Node 版本: v14.17.3
- 包管理器 (npm/yarn/pnpm) 及其版本: yarn1.22.10
![1630638859(1)](https://user-images.githubusercontent.com/41471252/131945300-b4285a63-9a18-48c2-810d-aa1bb1a0f04f.jpg)

**Comment by Dengyc** [comment]
请问解决了吗？我也遇到这个问题了，不知道怎么解决。

**Comment by meteor199** [comment]
补充信息：打包后在 不支持module的浏览器出现404，支持module的浏览器正常显示。

可能legacy 插件影响的。这些找不到的js文件都是 ant-design-vue中按需加载的样式文件。可能是rollup将要生成这些js文件时，被什么给拦截了，导致最终未生成这些js文件。

我目前的解决方案是 不用按需加载...

rollup的chunk信息:
```
{
  "id": "assets/index-legacy.0070e3e3.js",
  "files": [
    "C:/xxx/vue-vben-admin-main/node_modules/ant-design-vue/es/grid/style/index.less"
  ]
}

```

**Comment by webzhouyan** [comment]
同样问题
