### ISSUE TITLE
打包前后样式不一致，字体出现差异

### ISSUE THREAD

**Issue by chenmaolan** [vbenjs/vue-vben-admin#1171]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:
![image](https://user-images.githubusercontent.com/40062515/132327584-50c0dc6f-3297-4fb1-b2bd-5fcfc6585337.png)
![1631009460(1)](https://user-images.githubusercontent.com/40062515/132327603-de4e4e37-065e-426f-962a-2addb5236951.jpg)

**Comment by zuihou** [comment]
+1

**Comment by cnguu** [comment]
@anncwb 这个bug有办法解决吗？2.8.0版本仍然有这个问题

**Comment by vinoMamba** [comment]
I have the same problem  T-T
