### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by anncwb** [vbenjs/vue-vben-admin#12]
为了方便交流，提供了QQ群：569291866

Discord Url: https://discord.gg/8GuAdwDhj6

**Comment by flybyhorse** [comment]
TypeError: str.matchAll is not a function
      at Object.extractor (H:\vue-vben-admin-main\node_modules\@purge-icons\core\dist\index.js:146:27)
      at Extract (H:\vue-vben-admin-main\node_modules\@purge-icons\core\dist\index.js:173:54)

**Comment by AlvinMi** [comment]
有微信群嘛

**Comment by anncwb** [comment]
没有建微信群

**Comment by bhabgs** [comment]
我现在有一个问题代码如下: 
* `vite.config.ts`
```
import type { UserConfig } from 'vite';
export default {
  optimizeDeps: {
    include: ['raf', '@ant-design/icons-vue'],
  },
} as UserConfig;
```
![image](https://user-images.githubusercontent.com/19221378/103337840-7b1e8380-4ab7-11eb-9bf6-1f4ae73fee58.png)
![image](https://user-images.githubusercontent.com/19221378/103337862-870a4580-4ab7-11eb-82af-e11aeeba51f3.png)

> 我在我的vite + vue3.0 + tsx项目中使用 `antv` 时终端会提示很多 @ant-design/icons-vue 的警告，并且会在浏览器的 `console` 会提示非es包的问题，即使我在vite.config.ts中加入了相关配置也会有此问题。fork 您的项目下来发现运行起来并没有相关问题。不知道我应该在哪一步来处理这个问题呢？

**Comment by bhabgs** [comment]
> 我现在有一个问题代码如下:
> 
> * `vite.config.ts`
> 
> ```
> import type { UserConfig } from 'vite';
> export default {
>   optimizeDeps: {
>     include: ['raf', '@ant-design/icons-vue'],
>   },
> } as UserConfig;
> ```
> 
> ![image](https://user-images.githubusercontent.com/19221378/103337840-7b1e8380-4ab7-11eb-9bf6-1f4ae73fee58.png)
> ![image](https://user-images.githubusercontent.com/19221378/103337862-870a4580-4ab7-11eb-82af-e11aeeba51f3.png)
> 
> > 我在我的vite + vue3.0 + tsx项目中使用 `antv` 时终端会提示很多 @ant-design/icons-vue 的警告，并且会在浏览器的 `console` 会提示非es包的问题，即使我在vite.config.ts中加入了相关配置也会有此问题。fork 您的项目下来发现运行起来并没有相关问题。不知道我应该在哪一步来处理这个问题呢？

ant-design-vue 在安装的时候 `yarn add ** -S` 千万不要 -D

**Comment by JC-Yang1997** [comment]
ant-design-vue2.0.0-rc.5 select标签在选择过后键盘enter的时候会有bug。

**Comment by leixuesong** [comment]
qq群已满，请求加入

**Comment by yeyuchen198** [comment]
我用手机Tim搜不到这个QQ群，要是有tg群就好了
