### ISSUE TITLE
打包后部份 ant 组件样式会不见

### ISSUE THREAD

**Issue by mypeng1985** [vbenjs/vue-vben-admin#1205]
-
![5f06d2d8f274f94e832c490bce7ff6e](https://user-images.githubusercontent.com/22997469/133357738-a914139f-8459-466d-a4de-08cadf8c2dc1.png)
![9988d49dc963ae3c5fac90c31bb9ed8](https://user-images.githubusercontent.com/22997469/133357743-9a8ed7ff-d6e6-4c5c-bbd7-ede2c1c701e0.png)
![46851462eb69fddee98b92624796ac4](https://user-images.githubusercontent.com/22997469/133357745-8225d893-786d-4f39-aa5a-73a725d3aa37.png)
![decd4af77c75ccc2df8fd853778a7c6](https://user-images.githubusercontent.com/22997469/133357746-9fbb6869-7f7a-4a22-87ff-b19219d594ef.png)

请问下这个应该怎么处理。

**Comment by mynetfan** [comment]
无效的Issue。演示站点也是打包后的产物，但没有出现类似问题。如果你的项目出现了这种问题，而Demo中却没有，我们无法重现问题就排不了错。

**Comment by xunnasu** [comment]
我的也是出现了这种错误 怎么处理

**Comment by AYang518989** [comment]
我的是打包后，自己写的样式不见了，怎么处理呀

**Comment by xunnasu** [comment]
> 我的是打包后，自己写的样式不见了，怎么处理呀

在main.js里面， 又一处判断了环境，把判断环境去掉，就可以， 不行的话就再看下antd 有没有按需加载或者全局加载

**Comment by AYang518989** [comment]
> > 我的是打包后，自己写的样式不见了，怎么处理呀
> 
> 在main.js里面， 又一处判断了环境，把判断环境去掉，就可以， 不行的话就再看下antd 有没有按需加载或者全局加载

判断环境那块好像没看见呀
