### ISSUE TITLE
jest单元格测试报错

### ISSUE THREAD

**Issue by lgf196** [vbenjs/vue-vben-admin#1229]
我这边执行单元格报了如下的错误：
![image](https://user-images.githubusercontent.com/29600558/134300494-f3adb489-d28c-4004-94c7-391007cd1eed.png)

**Comment by mynetfan** [comment]
此文件当前代码并无这种用法。你是自己添加的代码吗？

**Comment by lgf196** [comment]
我的是这样的
![image](https://user-images.githubusercontent.com/29600558/134301350-debe47b1-945e-413d-b846-9e8066a7f59c.png)
![image](https://user-images.githubusercontent.com/29600558/134301376-0863fbeb-e27a-458e-9ecf-9bccdcb1c798.png)


> 此文件当前代码并无这种用法。你是自己添加的代码吗？

**Comment by lgf196** [comment]
> 此文件当前代码并无这种用法。你是自己添加的代码吗？

.env.preprod文件里面的代码是这样的：
NODE_ENV=production
VITE_APP_ANT=preprod
其它的环境类似

**Comment by mynetfan** [comment]
说的是你的src/utils/index.ts第六行

**Comment by lgf196** [comment]
> 说的是你的src/utils/index.ts第六行

![image](https://user-images.githubusercontent.com/29600558/134301744-b70a5e3c-28ab-40ce-98c8-11cfd654e948.png)
这个就是我的until/index里面的代码，没问题哈，启动没问题，jest就报错

**Comment by mynetfan** [comment]
问题就出在第六行，这种写法没有通过测试，错误提示已经说得很明白了

**Comment by lgf196** [comment]
> 问题就出在第六行，这种写法没有通过测试，错误提示已经说得很明白了

我知道是这种写法的问题，但是我们获取环境变量不就是通过：import.meta.env.xx来的吧，是jest不支持import.meta，还是什么原因呢

**Comment by mynetfan** [comment]
https://github.com/vitejs/vite/issues/1955

**Comment by lgf196** [comment]
> [vitejs/vite#1955](https://github.com/vitejs/vite/issues/1955)

这篇文章看了的，说是jest暂时不支持，不过还是感谢你

**Comment by Free-Qi** [comment]
能问下，这个框架的jest如何使用么
