### ISSUE TITLE
ApiSelect为多选时，每次点击选项都会执行一次接口请求

### ISSUE THREAD

**Issue by xiyanglove** [vbenjs/vue-vben-admin#1255]
### 描述 Bug

ApiSelect为多选时，每次点击选项都会执行一次接口请求，watch在拦截数据变化时，是否需要判断数据有变化的时候才再次执行fetch方法，多选时点击选项会触发watch

## 系统信息

- 操作系统:win11
- Node 版本:v16.4.2
- 包管理器 (npm/yarn/pnpm) 及其版本:yarn

**Comment by linrencai** [comment]
也有遇到过这个问题，好像是带了请求参数的原因。把componentsProps 写成函数返回一个对象可以解决

**Comment by webzhouyan** [comment]
同一个问题

**Comment by acegank** [comment]
`watch(
        () => props.params,
        (n, o) => {
          !unref(isFirstLoad) && !isEqual(n, o) && fetch();
        },
        { deep: true }
      );`
这样处理下

**Comment by lcffind** [comment]
我的问题是只有一个表单中有一个apiSelect, 其他的输入框输入也会调这个api，用上上面的代码没有作用

**Comment by linrencai** [comment]
> 我的问题是只有一个表单中有一个apiSelect, 其他的输入框输入也会调这个api，用上上面的代码没有作用

`<ApiSelect
          :api="getCustomerDicApi"
          :params="searchParams"
          showSearch
          allowClear
          v-model:value="model[field]"
          optionFilterProp="label"
          resultField="data"
          labelField="key"
          valueField="value"
          :immediate="false"
        />
const orgId = getOrgId();
      const searchParams = computed<Recordable>(() => {
        return { orgId: orgId };
      });
`

**Comment by linrencai** [comment]
> 我的问题是只有一个表单中有一个apiSelect, 其他的输入框输入也会调这个api，用上上面的代码没有作用

`<ApiSelect
          :api="getCustomerDicApi"
          :params="searchParams"
          showSearch
          allowClear
          v-model:value="model[field]"
          optionFilterProp="label"
          resultField="data"
          labelField="key"
          valueField="value"
          :immediate="false"
        />
const orgId = getOrgId();
      const searchParams = computed<Recordable>(() => {
        return { orgId: orgId };
      });
`
