### ISSUE TITLE
使用@antv/g6的情况下，build版本运行报错TypeError: Cannot read properties of undefined (reading 'Graph')

### ISSUE THREAD

**Issue by jwxue** [vbenjs/vue-vben-admin#1289]
如题，问题描述如下：
使用@antv/g6的情况下，build版本运行报错TypeError: Cannot read properties of undefined (reading 'Graph')

环境：
基于当前main分支，安装antv g6
yarn add @antv/g6

依赖如下：
"dependencies": {
    "@antv/g6": "^4.3.11",
    ...
  },

在首页页面代码中添加如下内容：
import G6, { IGroup, IShape, ModelConfig } from '@antv/g6';

`
G6.registerEdge('fund-polyline', {

    itemType: 'edge',
    draw: function draw(cfg: ModelConfig, group: IGroup) {

      const startPoint: {
        x: number;
        y: number;
      } = cfg.startPoint;

      const endPoint: {
        x: number;
        y: number;
      } = cfg.endPoint;

      const diffX: number = endPoint.x - startPoint.x;

      const offset: {
        x: number;
      } = {
        x: diffX / 2,
      };

      const line1EndPoint: {
        x: number;
        y: number;
      } = {
        x: startPoint.x + offset.x,
        y: startPoint.y,
      };
      const line2EndPoint: {
        x: number;
        y: number;
      } = {
        x: line1EndPoint.x,
        y: endPoint.y,
      };

      let startOffsetX = 20;
      const path = [
        ['M', startPoint.x + startOffsetX, startPoint.y],
        ['L', line1EndPoint.x, line1EndPoint.y],
        ['Q', line1EndPoint.x, line1EndPoint.y, line2EndPoint.x, line2EndPoint.y],
        ['L', endPoint.x, endPoint.y],
      ];

      const line: IShape = group.addShape('path', {
        attrs: {
          path,
          stroke: '#9EA7B4',
          lineWidth: 1,
          // endArrow,
        },
        name: 'path-shape',
      });
      return line;
    },
  });
`

yarn build

部署dist内容，比如用http-server启动web服务

访问上述页面后，就会出现该错误
![image](https://user-images.githubusercontent.com/8721518/137479571-48d071da-89e1-40d6-8a4a-ed4cae7ac970.png)

**Comment by aladdin-add** [comment]
使用 vite v2.9.9，也遇到了这个问题，是什么原因导致的，有思路么？ @jwxue
