### ISSUE TITLE
版本：2.7.2 - F5页面刷新左侧菜单无法加载的问题

### ISSUE THREAD

**Issue by zhangWeiZhuang** [vbenjs/vue-vben-admin#1303]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

版本 2.7.2 下 将系统内权限模式改为 ROLE 模式，左侧菜单是根据后台接口返回数据动态生成的。
第一次登录时，左侧菜单可以正常加载没任何问题。当用户F5刷新页面后左侧菜单即加载不出来了，随之访问的路由也是404（访问的页面不存在）！！！
我这边大致看了一眼， permission.ts 里面根据方法（getBackMenuList）获取菜单时这里返回的结果数组是空的
![image](https://user-images.githubusercontent.com/44084004/138101428-56217250-8ea7-4c1b-9103-a0e4827a7a31.png)
不知道为什么这个集合的数据丢掉了，登录时我console看到是记录数据的。

如果有其他同学遇到这种问题麻请告知下解决方案，谢谢了！！！！！

另外：我在之前版本：2.6.1 是没遇过这种问题的

### 复现 Bug
图一：第一次登录
![image](https://user-images.githubusercontent.com/44084004/138102186-309ef8e3-7765-4807-828f-1bcf259c4dec.png)

图二：F5刷新后效果
![image](https://user-images.githubusercontent.com/44084004/138102113-2dd7bfbc-73f5-4fa5-80b5-83143a47e2b3.png)

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- window 10
- Node 版本:
- v16.6.0
- 包管理器 (npm/yarn/pnpm) 及其版本:
yarn 版本：v1.22.3

**Comment by taoyiyang1** [comment]
> 我的用户登录界面也加载了这个问题，看到了路由和菜单重温的时候是重新读取的，我是因为更改了登录的逻辑，信息在直接获取的时候获取了，获取信息的删除了，在重新加载菜单的时候有一个读取用户信息的操作然后报错了，但是vben在代码里面直接catch了，没有抛出来，具体的代码在router/guard/permissionGuard.ts里面，你可以看看一下

![image](https://user-images.githubusercontent.com/53025630/160956044-5a3acab3-c271-4ba7-a655-26ab36db3d84.png)
我也是把获取用户信息删除了 , 在

> router/guard/permissionGuard.ts

删除这段代码后F5刷新就不会404了

**Comment by imruxin** [comment]
> > 我的用户登录界面也加载了这个问题，看到了路由和菜单重温的时候是重新读取的，我是因为更改了登录的逻辑，信息在直接获取的时候获取了，获取信息的删除了，在重新加载菜单的时候有一个读取用户信息的操作然后报错了，但是vben在代码里面直接catch了，没有抛出来，具体的代码在router/guard/permissionGuard.ts里面，你可以看看一下
> 
> ![image](https://user-images.githubusercontent.com/53025630/160956044-5a3acab3-c271-4ba7-a655-26ab36db3d84.png) 我也是把获取用户信息删除了 , 在
> 
> > router/guard/permissionGuard.ts
> 
> 删除这段代码后F5刷新就不会404了

删除后404问题可以搞定，但是菜单没了，尴尬
