### ISSUE TITLE
这种复杂的表单如何实现？

### ISSUE THREAD

**Issue by vssir** [vbenjs/vue-vben-admin#1308]
![image](https://user-images.githubusercontent.com/10388068/138391808-6f609e1a-f452-4a35-a4a0-c65b8a74c77d.png)
架构学习成本有点高，太折腾了

**Comment by vssir** [comment]
按原组件 FormSchema 布局没办法实现

**Comment by ldw4033** [comment]
弄明白了，求指点

**Comment by vssir** [comment]
**问题解决，用插槽方式进行自定义排版：**
  
FormSchema 设置
`{
    field: 'standby_staff',
    label: '备用员工',
    component: 'Input',
    required: true,
    slot: 'abcSlot',
  },`

表单
`<template>
        <template #abcSlot="{ model, field }">  这里按自己的排版  </template>
</template >`
