### ISSUE TITLE
请问怎么Jquery引入？ ReferenceError: $ is not defined？

### ISSUE THREAD

**Issue by cqllzp** [vbenjs/vue-vben-admin#1324]
我使用命令引入
![JM)JSX0953Z` `(B6M8JASM](https://user-images.githubusercontent.com/3725186/139275515-edb07f97-d89e-4004-887e-554204f0a93e.png)
但还是报错！
ReferenceError: $ is not defined？

**Comment by cqllzp** [comment]
我已经引入了谢谢，主要是以前的代码不想去转换了。

**Comment by lszai90** [comment]
> 我已经引入了谢谢，主要是以前的代码不想去转换了。
你好 请问一下你是怎么引用的
