### ISSUE TITLE
富文本编辑器的下拉选项经常错位

### ISSUE THREAD

**Issue by yangyanju** [vbenjs/vue-vben-admin#1328]
### 描述 Bug
富文本编辑器的下拉选项经常错位

请清晰地描述此 Bug 的具体表现。如图：

![微信图片_20211029183107](https://user-images.githubusercontent.com/7056767/139420668-7cb05265-77d6-4bc2-baf4-5bc9501be8ce.png)

图片来自https://vvbin.cn/next/#/comp/editor/tinymce/index 截图

**Comment by Miboweixin** [comment]
html,
body {
width: auto;
height: auto;
}

**Comment by yangyanju** [comment]
这是自动回复，已收到您的邮件，我将尽快给您回复。

**Comment by Miboweixin** [comment]
我也是刚刚解决这个问题，html添加即可，解决项目问题

**Comment by GodZhuJunTao** [comment]
> 我也是刚刚解决这个问题，html添加，解决项目

会不会有啥影响

**Comment by yangyanju** [comment]
这是自动回复，已收到您的邮件，我将尽快给您回复。

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！

**Comment by yangyanju** [comment]
这是自动回复，已收到您的邮件，我将尽快给您回复。
