### ISSUE TITLE
希望增加一個彈框關閉後銷毀彈框內部數據的解決方案

### ISSUE THREAD

**Issue by 604587986** [vbenjs/vue-vben-admin#1337]
### 描述

彈框內經常會用到一些內部數據，這些數據有時不僅僅跟form相關，無法用resetFields一次解決，vue3的內部數據又分散在組件內，一不小心就忘記重置了

### 問題

我目前自己寫了個包裹容器，用於監聽關閉後動態渲染，將內容重置

### Expected behaviour

以前都是通過v-if 希望官方也出一個方案

**Comment by obamin** [comment]
希望支持, 这个很需要

**Comment by wangjue666** [comment]
给 `modal `设置属性 [`destroyOnClose `](https://www.antdv.com/components/modal-cn#api)
