### ISSUE TITLE
【兼容性问题】华为手机自带浏览器菜单颜色异常

### ISSUE THREAD

**Issue by sjlei** [vbenjs/vue-vben-admin#1344]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

华为手机自带浏览器菜单颜色异常，目前已知 华为手机mate30 rs 鸿蒙系统存在下图问题
![139643978-7f629e00-d023-4811-af75-319cd6287d08 jpg_08_202454](https://user-images.githubusercontent.com/34293221/140741979-e90badab-e383-4576-92dc-56274934b4dd.png)

### 复现 Bug

使用华为手机自带的浏览器访问演示环境

## 系统信息

- 操作系统: mate30 rs 鸿蒙系统
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by liuhang-cn** [comment]
新版本已经正常了，但不知道是改的哪儿，找出来的可以共享一下。

**Comment by hdtopku** [comment]
同样的问题，不知道问题出在哪
