### ISSUE TITLE
出一个自定义组件，封装的教程吧。

### ISSUE THREAD

**Issue by Angle-bo** [vbenjs/vue-vben-admin#1351]
类似于BasicUpload 组件这样的。Vben官方组件不够用的情况，基于 Ant Design Vue的组件库，组件自己封装到vben组件库。

 自己要用的话，想按照BasicUpload 组件的封装方式使用。要怎么弄？

**Comment by glorydreamtop** [comment]
照着vben-admin现有的组件封装就行了呀。。。

**Comment by Angle-bo** [comment]
没搞明白，数据双向绑定，传参，还是事件，怎么写。
