### ISSUE TITLE
Upload 上传组件，上传的文件名字过长时，表格变形，能否固定宽度？

### ISSUE THREAD

**Issue by zuihou** [vbenjs/vue-vben-admin#1355]
![image](https://user-images.githubusercontent.com/8500410/141149731-06f8c4ef-cfc2-4bff-b2b9-42f24576ab34.png)

**Comment by yonghui666** [comment]
请问大佬；这个upload组件；后端需要返回什么样的格式数据呢？？虽然我上次成功了；但是回调函数拿不到后端返回的参数；

**Comment by zyz954489346** [comment]
同样的问题，暂时是通过修改组件样式解决的
