### ISSUE TITLE
打包发布后，切换系统主题 不生效。

### ISSUE THREAD

**Issue by zuihou** [vbenjs/vue-vben-admin#1360]
![image](https://user-images.githubusercontent.com/8500410/141455219-a8803e38-4480-419a-b6fe-7adef8babd14.png)

打包发布后，切换 系统主题 不生效。

本地生效。

**Comment by LestreZhao** [comment]
遇到同样问题,演示环境也是一样,无法切换主题 请问解决了么

**Comment by webzhouyan** [comment]
@LestreZhao @zuihou     使用 2.7.1 版本，没有问题，我是2.7.1版本升级vite版本到最新，出现一样问题，改成vite版本2.5.1没有问题，所以还是使用vben2.7.1版本稳定一些，最新的bug较多

**Comment by LestreZhao** [comment]
@webzhouyan vite最新版本到2.7.1了么 我看是beta版本
