### ISSUE TITLE
官网完整版示例QQ浏览器转圈进不了。

### ISSUE THREAD

**Issue by qq2814659909** [vbenjs/vue-vben-admin#1363]
官网完整版示例QQ浏览器转圈进不了。

**Comment by 1sm23** [comment]
QQ浏览器的chrome版本太低了，还不支持 [globalThis](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/globalThis)

**Comment by qq2814659909** [comment]
老师，应该考虑一下支持QQ浏览器，因为这个浏览器用户群体多。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "anncwb/vue-vben-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月15日(星期一) 中午11:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [anncwb/vue-vben-admin] 官网完整版示例QQ浏览器转圈进不了。 (Issue #1363)





 
QQ浏览器的chrome版本太低了，还不支持 globalThis
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by M69W** [comment]
内核低不支持，
除非 QQ 浏览器更新内核

**Comment by mymbrooks** [comment]
做开发的用 QQ 浏览器简直是搞笑的，支持屏蔽各种国产垃圾套壳浏览器

**Comment by PineSongCN** [comment]
> 做开发的用 QQ 浏览器简直是搞笑的，支持屏蔽各种国产垃圾套壳浏览器

弱智。

**Comment by PineSongCN** [comment]
> QQ浏览器的chrome版本太低了，还不支持 [globalThis](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/globalThis)

加个polyfill的事情

**Comment by xuke19991002** [comment]
通过查找 github vite的 issues 解决了，可以加入如下改动：
```
// vite.config.js
{
  // ......

  build: {
    // target: 'es2015',
    target: 'chrome63',
  }

  // ......
}
```

```
// build/vite/plugin/index.ts

VITE_LEGACY &&
  isBuild &&
    vitePlugins.push(
      legacy({
        // 新增
        targets: ['Chrome 63'],
        modernPolyfills: true,
      }),
    );
```

**Comment by core-admin** [comment]
通过查找 github vite的 issues 解决了，可以加入如下改动：
```
// vite.config.js
{
  // ......

  build: {
    // target: 'es2015',
    target: 'chrome63',
  }

  // ......
}
```

```
// build/vite/plugin/index.ts

VITE_LEGACY &&
  isBuild &&
    vitePlugins.push(
      legacy({
        // 新增
        targets: ['Chrome 63'],
        modernPolyfills: true,
      }),
    );
```

issuse对应地址：https://github.com/vitejs/vite/issues/5952
