### ISSUE TITLE
打包后，360浏览器弹窗弹不出问题

### ISSUE THREAD

**Issue by dingshaohua-cn** [vbenjs/vue-vben-admin#1381]
### 描述 Bug
打包后360浏览器弹窗弹不出问题   
官网演示环境或者基于最新模板创建的项目，打包后在360浏览器下无法弹窗，   
甚至使用antd原生组件也无法弹出问题。   
经过排查是vben内部依赖问题。   
使用老版本的yarn.lock即可: 比如2021/11/10号的版本就行，如果没有 可以问我要，我有备份

### 复现 Bug
官网演示环境或者基于最新模板创建的项目，打包后在360浏览器下无法弹窗，甚至使用antd原生组件也无法弹出问题。

## 系统信息
- Node 版本: v16.x or v14.x

**Comment by liuhang-cn** [comment]
是top:0;bottom:0;left0:right:0;被替换成了inset，低版本内核的浏览器不支持inset。不知道怎么禁止这个转换。

**Comment by dshvv** [comment]
> 是top:0;bottom:0;left0:right:0;被替换成了inset，低版本内核的浏览器不支持inset。不知道怎么禁止这个转换。

其实已经不低了，内核86，vben不应该对浏览器要求如此之高

**Comment by liuhang-cn** [comment]
86是不支持inset的最后一个版本。vben最新版本的已经改过了，你可以试试。

**Comment by MochiFairyhood** [comment]
我是通过引入外部css样式，临时解决，如果知道怎么禁用这个转化，望告知，学习下。。
![b4edc27a7f682efe27be076d06788ba](https://user-images.githubusercontent.com/37924380/145210951-6154c327-f397-448a-ae8e-7b19779df6cb.png)
![image](https://user-images.githubusercontent.com/37924380/145211374-b0397ba6-c64a-4708-a5e3-5687ffe327fc.png)
