### ISSUE TITLE
文档推荐的 Vetur 插件不支持 setup 语法，打开 vue 文件报错

### ISSUE THREAD

**Issue by SilenceAdam** [vbenjs/vue-vben-admin#1387]
### 文档推荐的 Vetur 插件不支持setup语法，打开 vue 文件报错

看官方文档推荐 VSCode 使用 vue 开发必备的 Vetur 插件，但是Vetur不支持 setup 语法，会报“ 'xxx' is declared but its value is never ”。

### 问题

其实官网文档有提到也可以选择 Volar 插件，但是给人的感觉这个插件优先级不高，用 Vetur是最好的选择，但实际上打开使用了 setup语法糖的 vue 页面几乎都会报错。对于新手使用这个项目不太友好，还以为是自己哪里的问题导致的页面报错。

### 预期

希望在文档里专门增加对Vetur 插件不支持 setup 的解决方案，比如说换用 Volar 插件，或者其他更好的方式。

### 备选方案（不推荐）

在设置 -> 扩展 -> Vetur 中去掉对 template、script 的验证。
> 不推荐这种做法，放弃了验证会给开发效率带来很大的影响。

![image](https://user-images.githubusercontent.com/14231871/142414480-7a9a6e9e-764d-4fb7-b74d-0cfc57ed1204.png)

**Comment by glorydreamtop** [comment]
很明显换volar就行

**Comment by SilenceAdam** [comment]
@glorydreamtop  请看官方文档截图：
![image](https://user-images.githubusercontent.com/14231871/142625649-2c308da7-d066-408d-9b97-992a26ac9261.png)

当你对插件的支持情况不了解时，难道不是有限考虑安装 Vetur么？

**Comment by xujunweb** [comment]
.eslintrc.js配置里加这个试下

**Comment by core-admin** [comment]
用 Volar吧，基本写vue3都不用vetur了

**Comment by bryant0623** [comment]
使用 Volar 格式化后，格式化规则和 prettier 不一致怎么解决
