### ISSUE TITLE
面包屑导航bug 

### ISSUE THREAD

**Issue by a67622531** [vbenjs/vue-vben-admin#1405]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

菜单栏已经隐藏子菜单，但是面包屑导航还是会显示子菜单

### 复现 Bug
 {
  path: '/check-task',
  name: 'CheckTask',
  component: LAYOUT,
  redirect: '/check-task/list',
  meta: {
    hideChildrenInMenu: true,
    icon: 'ic:sharp-inventory',
    title: '盘点管理',
    orderNo: 2,
  },
  children: [
    {
      path: 'list',
      name: 'CheckTaskList',
      component: () => import('/@/views/check-task/index.vue'),
      meta: {
        title: '盘点列表',
        icon: 'ic:sharp-inventory',
        hideMenu: true,
      },
    },
  ],
};
![微信截图_20211124141320](https://user-images.githubusercontent.com/40052127/143184640-c2543d4c-4015-4fca-99aa-1d053c63b09a.png)

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by liujians** [comment]
我也遇到了这个问题
I have the same problem.
version：2.8.0

**Comment by liujians** [comment]
可能是vue-vben-admin和vue-admin-thin-next两个版本的breadcrumb代码不一致的问题，项目中用的vue-admin-thin-next。现在临时的解决方案就是用vue-vben-admin的breadcrumb代码来替换一下。
