### ISSUE TITLE
最新版 Table ColumnProps 已经不存在了

### ISSUE THREAD

**Issue by HaceraI** [vbenjs/vue-vben-admin#1408]
`\src\components\Table\src\types\table.ts` 这个文件里面 `ColumnProps` 已经找不到了，导致很多引用了 Table 的地方都爆红了.

![image](https://user-images.githubusercontent.com/48341368/143399746-c5f83a2d-33ed-4563-bd20-9d099bfd7fbb.png)
![image](https://user-images.githubusercontent.com/48341368/143399776-c084dd83-0d37-499d-ae91-07a2f7428c97.png)
![image](https://user-images.githubusercontent.com/48341368/143399807-9b915c23-ef54-4bae-bba4-ae3f2b4a823b.png)

**Comment by ldw4033** [comment]
+1

**Comment by renhhh** [comment]
![image](https://user-images.githubusercontent.com/49031260/145778409-c85452a0-24c7-44f7-a013-adb5613e5975.png)

**Comment by phoenixor** [comment]
个人维护的项目就是乱改api，作者为什么不用elementPlus呢

**Comment by anncwb** [comment]
这个项目开始的时候elementPlus 还没出来啊，再等等吧，可以先还原2.8，通过git记录还原
