### ISSUE TITLE
严重BUG： 打包后，弹出框现在不显示，或者样式错误

### ISSUE THREAD

**Issue by gaocheng001** [vbenjs/vue-vben-admin#1422]
### 描述 Bug

弹出框现在不显示，或者样式错误

### 复现 Bug

![image](https://user-images.githubusercontent.com/40415260/143801498-53244f9d-cddd-4b5e-a5d2-ab40c0867729.png)
升级到antd3,弹出框不显示了，或者有问题

![5ZQ3DY6DQI$LW`L3( GH5$C](https://user-images.githubusercontent.com/40415260/143801745-d2f3aa79-a1e6-4830-a835-863fe649eff2.png)
这是本地开发

![4}B)R8CH(_{O59XG%8J(IN2](https://user-images.githubusercontent.com/40415260/143801746-cf067ca7-e8af-46ea-ae51-d48d1bcf49de.jpg)

这是打包编译后的css

查了node_modules/antd的less文件，一切是正常的

**Comment by dshvv** [comment]
我提过这个问题 有人解答
