### ISSUE TITLE
useTable()模式下table设置无法取消勾选 且点击后页面卡死

### ISSUE THREAD

**Issue by chuangyi110** [vbenjs/vue-vben-admin#1439]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

组件-》Table》开始搜索区域 页面内 setting表单里的勾选项 无法取消选项并且点击后报错 页面卡死
只出现在下载代码内 （无修改）

预览网站无此问题

### 复现 Bug

![1638431107(1)](https://user-images.githubusercontent.com/33341823/144379181-54271690-0337-4ef3-b2b0-2fa5d61fd0f6.jpg)

## 系统信息

- 操作系统:  windows10
- Node 版本:  14.15.4
- 包管理器 (npm/yarn/pnpm) 及其版本: 6.20.2

**Comment by hhw2444** [comment]
我也碰到，具体处理   #1327

**Comment by chuangyi110** [comment]
#

> 我也碰到，具体处理 #1327

我看了一下这个处理办法 这种会导致再次选中时无法获取选中列。感觉根本问题在于onchange事件无法监听到

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
