### ISSUE TITLE
vben 2.8版本打包后 app-theme-style.css文件打包没有内容，导致主题切换没有效果  

### ISSUE THREAD

**Issue by webzhouyan** [vbenjs/vue-vben-admin#1445]
### 描述 Bug

vben 2.8版本打包后 app-theme-style.css文件打包没有内容，导致主题切换没有效果，2.7版本打包正常  
![image](https://user-images.githubusercontent.com/18736886/144705396-133c0607-4c28-4065-abcc-69bf9d78d47c.png)

### 复现 Bug

2.8版本直接打包

## 系统信息

- 操作系统:
- Node 版本: v16.13.0
- 包管理器 (npm/yarn/pnpm) 及其版本: 8.1.0

**Comment by xietongjian** [comment]
我之前也遇到过，是因为项目中有使用空的<style lang="less" scoped></style>导致的
![image](https://user-images.githubusercontent.com/16096832/144750004-66719078-c8e1-42d8-95c9-6fe9c883cc5e.png)

项目中全局搜索一下，去掉这个就行了。

**Comment by 156704883** [comment]
> 我之前也遇到过，是因为项目中有使用空的<style lang="less" scoped></style>导致的 ![image](https://user-images.githubusercontent.com/16096832/144750004-66719078-c8e1-42d8-95c9-6fe9c883cc5e.png)
> 
> 项目中全局搜索一下，去掉这个就行了。

不行

**Comment by webzhouyan** [comment]
> 
确实不行

**Comment by xietongjian** [comment]
感谢您的来信，您的来信我会及时回复
有事请致电13510419502 或QQ583110978联系
姓名：谢桐健 
联系方式：手机13510419502  QQ583110978 
中级软件工程师，系统架构师，网站网页设计工程师
有意者请致电话或QQ联系

**Comment by webzhouyan** [comment]
> 我之前也遇到过，是因为项目中有使用空的<style lang="less" scoped></style>导致的 ![image](https://user-images.githubusercontent.com/16096832/144750004-66719078-c8e1-42d8-95c9-6fe9c883cc5e.png)
> 
> 项目中全局搜索一下，去掉这个就行了。

确实不行

**Comment by dievdy** [comment]
同问，打包完后，这个文件没有数据，修改主题色不生效，请问有什么解决办法吗

**Comment by xiaoxia1314** [comment]
同问

**Comment by cuizhanshan** [comment]
我把vite版本降到v2.5.10之后可以了

**Comment by 156704883** [comment]
> 我把vite版本降到v2.5.10之后可以了

果然可以了

**Comment by adleader** [comment]
这个问题解决有两个办法。打包需要使用vbenjs/vite-plugin-theme，V大写这个插件在低版本的vite中没有问题。高版本的vite针对下方代码
```
async transform(code, id) {
        if (!cssLangRE.test(id)) {
          return null;
        }
        const getResult = (content: string) => {
          return {
            map: needSourcemap ? this.getCombinedSourcemap() : null,
            code: content,
          };
        };

        const clientCode = isServer
          ? await getClientStyleString(code)
          : code.replace('export default', '').replace('"', '');

        // Used to extract the relevant color configuration in css, you can pass in the function to override
        const extractCssCodeTemplate =
          typeof customerExtractVariable === 'function'
            ? customerExtractVariable(clientCode)
            : extractVariable(clientCode, colorVariables, resolveSelectorFn);

        debug('extractCssCodeTemplate:', id, extractCssCodeTemplate);

        if (!extractCssCodeTemplate) {
          return null;
        }

        // dev-server
        if (isServer) {
          const retCode = [
            `import { addCssToQueue } from ${clientPath}`,
            `const themeCssId = ${JSON.stringify(id)}`,
            `const themeCssStr = ${JSON.stringify(formatCss(extractCssCodeTemplate))}`,
            `addCssToQueue(themeCssId, themeCssStr)`,
            code,
          ];

          return getResult(retCode.join('\n'));
        } else {
          if (!styleMap.has(id)) {
            extCssSet.add(extractCssCodeTemplate);
          }
          styleMap.set(id, extractCssCodeTemplate);
        }

        return null;
      },
```
主要vite最新版本因为enforce: "post"导致async transform(code, id) 的code没有正确获取。
第一种就是修改V大的vite-plugin-theme插件。

第二种修改打包主题的插件“/build/vite/plugin/theme.ts”
对viteThemePlugin中的'vite:theme'进行delete item.enforce
代码如下，可能和最新版本的有部分不一致，原理是一样的。

```
export function configThemePlugin(isBuild: boolean): Plugin[] {
  const colors = generateColors({
    mixDarken,
    mixLighten,
    tinycolor,
  });
  // 抽取出viteThemePlugin插件，下方会根据不同环境设置enforce
  let vite_theme_plugin = viteThemePlugin({
    resolveSelector: (s) => {
      s = s.trim();
      switch (s) {
        case '.ant-steps-item-process .ant-steps-item-icon > .ant-steps-icon':
          return '.ant-steps-item-icon > .ant-steps-icon';
        case '.ant-radio-button-wrapper-checked:not(.ant-radio-button-wrapper-disabled)':
        case '.ant-radio-button-wrapper-checked:not(.ant-radio-button-wrapper-disabled):hover':
        case '.ant-radio-button-wrapper-checked:not(.ant-radio-button-wrapper-disabled):active':
          return s;
        case '.ant-steps-item-icon > .ant-steps-icon':
          return s;
        case '.ant-select-item-option-selected:not(.ant-select-item-option-disabled)':
          return s;
        default:
          if (s.indexOf('.ant-btn') >= -1) {
            // 按钮被重新定制过，需要过滤掉class防止覆盖
            return s;
          }
      }
      return s.startsWith('[data-theme') ? s : `[data-theme] ${s}`;
    },
    colorVariables: [...getThemeColors(), ...colors],
  });
  //console.log('vite_theme_plugin:'+JSON.stringify(vite_theme_plugin));
  vite_theme_plugin.forEach(function (item) {
    //对vite:theme插件特殊配置
    if ('vite:theme' === item.name) {
      //console.log(item);
      // 打包时去除enforce: "post"，vite 2.6.x适配，否则生成app-theme-style为空，因为async transform(code, id) {的code没有正确获取
      if (isBuild) {
        delete item.enforce;
      }
      //console.log(item);
    }
  });
  //console.log('vite_theme_plugin后:'+JSON.stringify(vite_theme_plugin));
  const plugin = [
    vite_theme_plugin,
    // 黑暗模式，颜色层穿透bug较多
    antdDarkThemePlugin({
      preloadFiles: [
        path.resolve(process.cwd(), 'node_modules/ant-design-vue/dist/antd.less'),
        path.resolve(process.cwd(), 'gxqtvue3-base/assets/gxqtcss/index.less'),
      ],
      filter: (id) => (isBuild ? !id.endsWith('antd.less') : true),
      // extractCss: false,
      darkModifyVars: {
        ...generateModifyVars(true),
        'text-color': '#c9d1d9',
        'primary-1': 'rgb(255 255 255 / 8%)',
        'text-color-base': '#c9d1d9',
        'component-background': '#151515',
        'heading-color': 'rgb(255 255 255 / 65%)',
        // black: '#0e1117',
        // #8b949e
        'text-color-secondary': '#8b949e',
        'border-color-base': '#303030',
        // 'border-color-split': '#30363d',
        'item-active-bg': '#111b26',
        'app-content-background': '#1e1e1e',
        'tree-node-selected-bg': '#11263c',

        'alert-success-border-color': '#274916',
        'alert-success-bg-color': '#162312',
        'alert-success-icon-color': '#49aa19',
        'alert-info-border-color': '#153450',
        'alert-info-bg-color': '#111b26',
        'alert-info-icon-color': '#177ddc',
        'alert-warning-border-color': '#594214',
        'alert-warning-bg-color': '#2b2111',
        'alert-warning-icon-color': '#d89614',
        'alert-error-border-color': '#58181c',
        'alert-error-bg-color': '#2a1215',
        'alert-error-icon-color': '#a61d24',
      },
    }),
  ];
  
  return plugin as unknown as Plugin[];
}
```

**Comment by zuihou** [comment]
> enforce

亲测有效

**Comment by zuihou** [comment]
> 这个问题解决有两个办法。打包需要使用vbenjs/vite-plugin-theme，V大写这个插件在低版本的vite中没有问题。高版本的vite针对下方代码
> 
> ```
> async transform(code, id) {
>         if (!cssLangRE.test(id)) {
>           return null;
>         }
>         const getResult = (content: string) => {
>           return {
>             map: needSourcemap ? this.getCombinedSourcemap() : null,
>             code: content,
>           };
>         };
> 
>         const clientCode = isServer
>           ? await getClientStyleString(code)
>           : code.replace('export default', '').replace('"', '');
> 
>         // Used to extract the relevant color configuration in css, you can pass in the function to override
>         const extractCssCodeTemplate =
>           typeof customerExtractVariable === 'function'
>             ? customerExtractVariable(clientCode)
>             : extractVariable(clientCode, colorVariables, resolveSelectorFn);
> 
>         debug('extractCssCodeTemplate:', id, extractCssCodeTemplate);
> 
>         if (!extractCssCodeTemplate) {
>           return null;
>         }
> 
>         // dev-server
>         if (isServer) {
>           const retCode = [
>             `import { addCssToQueue } from ${clientPath}`,
>             `const themeCssId = ${JSON.stringify(id)}`,
>             `const themeCssStr = ${JSON.stringify(formatCss(extractCssCodeTemplate))}`,
>             `addCssToQueue(themeCssId, themeCssStr)`,
>             code,
>           ];
> 
>           return getResult(retCode.join('\n'));
>         } else {
>           if (!styleMap.has(id)) {
>             extCssSet.add(extractCssCodeTemplate);
>           }
>           styleMap.set(id, extractCssCodeTemplate);
>         }
> 
>         return null;
>       },
> ```
> 
> 主要vite最新版本因为enforce: "post"导致async transform(code, id) 的code没有正确获取。 第一种就是修改V大的vite-plugin-theme插件。
> 
> 第二种修改打包主题的插件“/build/vite/plugin/theme.ts” 对viteThemePlugin中的'vite:theme'进行delete item.enforce 代码如下，可能和最新版本的有部分不一致，原理是一样的。
> 
> ```
> export function configThemePlugin(isBuild: boolean): Plugin[] {
>   const colors = generateColors({
>     mixDarken,
>     mixLighten,
>     tinycolor,
>   });
>   // 抽取出viteThemePlugin插件，下方会根据不同环境设置enforce
>   let vite_theme_plugin = viteThemePlugin({
>     resolveSelector: (s) => {
>       s = s.trim();
>       switch (s) {
>         case '.ant-steps-item-process .ant-steps-item-icon > .ant-steps-icon':
>           return '.ant-steps-item-icon > .ant-steps-icon';
>         case '.ant-radio-button-wrapper-checked:not(.ant-radio-button-wrapper-disabled)':
>         case '.ant-radio-button-wrapper-checked:not(.ant-radio-button-wrapper-disabled):hover':
>         case '.ant-radio-button-wrapper-checked:not(.ant-radio-button-wrapper-disabled):active':
>           return s;
>         case '.ant-steps-item-icon > .ant-steps-icon':
>           return s;
>         case '.ant-select-item-option-selected:not(.ant-select-item-option-disabled)':
>           return s;
>         default:
>           if (s.indexOf('.ant-btn') >= -1) {
>             // 按钮被重新定制过，需要过滤掉class防止覆盖
>             return s;
>           }
>       }
>       return s.startsWith('[data-theme') ? s : `[data-theme] ${s}`;
>     },
>     colorVariables: [...getThemeColors(), ...colors],
>   });
>   //console.log('vite_theme_plugin:'+JSON.stringify(vite_theme_plugin));
>   vite_theme_plugin.forEach(function (item) {
>     //对vite:theme插件特殊配置
>     if ('vite:theme' === item.name) {
>       //console.log(item);
>       // 打包时去除enforce: "post"，vite 2.6.x适配，否则生成app-theme-style为空，因为async transform(code, id) {的code没有正确获取
>       if (isBuild) {
>         delete item.enforce;
>       }
>       //console.log(item);
>     }
>   });
>   //console.log('vite_theme_plugin后:'+JSON.stringify(vite_theme_plugin));
>   const plugin = [
>     vite_theme_plugin,
>     // 黑暗模式，颜色层穿透bug较多
>     antdDarkThemePlugin({
>       preloadFiles: [
>         path.resolve(process.cwd(), 'node_modules/ant-design-vue/dist/antd.less'),
>         path.resolve(process.cwd(), 'gxqtvue3-base/assets/gxqtcss/index.less'),
>       ],
>       filter: (id) => (isBuild ? !id.endsWith('antd.less') : true),
>       // extractCss: false,
>       darkModifyVars: {
>         ...generateModifyVars(true),
>         'text-color': '#c9d1d9',
>         'primary-1': 'rgb(255 255 255 / 8%)',
>         'text-color-base': '#c9d1d9',
>         'component-background': '#151515',
>         'heading-color': 'rgb(255 255 255 / 65%)',
>         // black: '#0e1117',
>         // #8b949e
>         'text-color-secondary': '#8b949e',
>         'border-color-base': '#303030',
>         // 'border-color-split': '#30363d',
>         'item-active-bg': '#111b26',
>         'app-content-background': '#1e1e1e',
>         'tree-node-selected-bg': '#11263c',
> 
>         'alert-success-border-color': '#274916',
>         'alert-success-bg-color': '#162312',
>         'alert-success-icon-color': '#49aa19',
>         'alert-info-border-color': '#153450',
>         'alert-info-bg-color': '#111b26',
>         'alert-info-icon-color': '#177ddc',
>         'alert-warning-border-color': '#594214',
>         'alert-warning-bg-color': '#2b2111',
>         'alert-warning-icon-color': '#d89614',
>         'alert-error-border-color': '#58181c',
>         'alert-error-bg-color': '#2a1215',
>         'alert-error-icon-color': '#a61d24',
>       },
>     }),
>   ];
>   
>   return plugin as unknown as Plugin[];
> }
> ```


亲测有效

**Comment by zuihou** [comment]
> 这个问题解决有两个办法。打包需要使用vbenjs/vite-plugin-theme，V大写这个插件在低版本的vite中没有问题。高版本的vite针对下方代码
> 
> ```
> async transform(code, id) {
>         if (!cssLangRE.test(id)) {
>           return null;
>         }
>         const getResult = (content: string) => {
>           return {
>             map: needSourcemap ? this.getCombinedSourcemap() : null,
>             code: content,
>           };
>         };
> 
>         const clientCode = isServer
>           ? await getClientStyleString(code)
>           : code.replace('export default', '').replace('"', '');
> 
>         // Used to extract the relevant color configuration in css, you can pass in the function to override
>         const extractCssCodeTemplate =
>           typeof customerExtractVariable === 'function'
>             ? customerExtractVariable(clientCode)
>             : extractVariable(clientCode, colorVariables, resolveSelectorFn);
> 
>         debug('extractCssCodeTemplate:', id, extractCssCodeTemplate);
> 
>         if (!extractCssCodeTemplate) {
>           return null;
>         }
> 
>         // dev-server
>         if (isServer) {
>           const retCode = [
>             `import { addCssToQueue } from ${clientPath}`,
>             `const themeCssId = ${JSON.stringify(id)}`,
>             `const themeCssStr = ${JSON.stringify(formatCss(extractCssCodeTemplate))}`,
>             `addCssToQueue(themeCssId, themeCssStr)`,
>             code,
>           ];
> 
>           return getResult(retCode.join('\n'));
>         } else {
>           if (!styleMap.has(id)) {
>             extCssSet.add(extractCssCodeTemplate);
>           }
>           styleMap.set(id, extractCssCodeTemplate);
>         }
> 
>         return null;
>       },
> ```
> 
> 主要vite最新版本因为enforce: "post"导致async transform(code, id) 的code没有正确获取。 第一种就是修改V大的vite-plugin-theme插件。
> 
> 第二种修改打包主题的插件“/build/vite/plugin/theme.ts” 对viteThemePlugin中的'vite:theme'进行delete item.enforce 代码如下，可能和最新版本的有部分不一致，原理是一样的。
> 
> ```
> export function configThemePlugin(isBuild: boolean): Plugin[] {
>   const colors = generateColors({
>     mixDarken,
>     mixLighten,
>     tinycolor,
>   });
>   // 抽取出viteThemePlugin插件，下方会根据不同环境设置enforce
>   let vite_theme_plugin = viteThemePlugin({
>     resolveSelector: (s) => {
>       s = s.trim();
>       switch (s) {
>         case '.ant-steps-item-process .ant-steps-item-icon > .ant-steps-icon':
>           return '.ant-steps-item-icon > .ant-steps-icon';
>         case '.ant-radio-button-wrapper-checked:not(.ant-radio-button-wrapper-disabled)':
>         case '.ant-radio-button-wrapper-checked:not(.ant-radio-button-wrapper-disabled):hover':
>         case '.ant-radio-button-wrapper-checked:not(.ant-radio-button-wrapper-disabled):active':
>           return s;
>         case '.ant-steps-item-icon > .ant-steps-icon':
>           return s;
>         case '.ant-select-item-option-selected:not(.ant-select-item-option-disabled)':
>           return s;
>         default:
>           if (s.indexOf('.ant-btn') >= -1) {
>             // 按钮被重新定制过，需要过滤掉class防止覆盖
>             return s;
>           }
>       }
>       return s.startsWith('[data-theme') ? s : `[data-theme] ${s}`;
>     },
>     colorVariables: [...getThemeColors(), ...colors],
>   });
>   //console.log('vite_theme_plugin:'+JSON.stringify(vite_theme_plugin));
>   vite_theme_plugin.forEach(function (item) {
>     //对vite:theme插件特殊配置
>     if ('vite:theme' === item.name) {
>       //console.log(item);
>       // 打包时去除enforce: "post"，vite 2.6.x适配，否则生成app-theme-style为空，因为async transform(code, id) {的code没有正确获取
>       if (isBuild) {
>         delete item.enforce;
>       }
>       //console.log(item);
>     }
>   });
>   //console.log('vite_theme_plugin后:'+JSON.stringify(vite_theme_plugin));
>   const plugin = [
>     vite_theme_plugin,
>     // 黑暗模式，颜色层穿透bug较多
>     antdDarkThemePlugin({
>       preloadFiles: [
>         path.resolve(process.cwd(), 'node_modules/ant-design-vue/dist/antd.less'),
>         path.resolve(process.cwd(), 'gxqtvue3-base/assets/gxqtcss/index.less'),
>       ],
>       filter: (id) => (isBuild ? !id.endsWith('antd.less') : true),
>       // extractCss: false,
>       darkModifyVars: {
>         ...generateModifyVars(true),
>         'text-color': '#c9d1d9',
>         'primary-1': 'rgb(255 255 255 / 8%)',
>         'text-color-base': '#c9d1d9',
>         'component-background': '#151515',
>         'heading-color': 'rgb(255 255 255 / 65%)',
>         // black: '#0e1117',
>         // #8b949e
>         'text-color-secondary': '#8b949e',
>         'border-color-base': '#303030',
>         // 'border-color-split': '#30363d',
>         'item-active-bg': '#111b26',
>         'app-content-background': '#1e1e1e',
>         'tree-node-selected-bg': '#11263c',
> 
>         'alert-success-border-color': '#274916',
>         'alert-success-bg-color': '#162312',
>         'alert-success-icon-color': '#49aa19',
>         'alert-info-border-color': '#153450',
>         'alert-info-bg-color': '#111b26',
>         'alert-info-icon-color': '#177ddc',
>         'alert-warning-border-color': '#594214',
>         'alert-warning-bg-color': '#2b2111',
>         'alert-warning-icon-color': '#d89614',
>         'alert-error-border-color': '#58181c',
>         'alert-error-bg-color': '#2a1215',
>         'alert-error-icon-color': '#a61d24',
>       },
>     }),
>   ];
>   
>   return plugin as unknown as Plugin[];
> }
> ```

mac 上有效，window 下执行pnpm serve 会报 找不到 gxqtvue3-base/assets/gxqtcss/index.less

**Comment by pzheng2010** [comment]
同上
gxqtvue3-base/assets/gxqtcss/index.less 找不到
而且在dark theme 下 还是不能改变theme color

**Comment by Jamboy** [comment]
2.8打包后样式出现问题，按照第二种方法解决，谢谢大佬。
