### ISSUE TITLE
Add webpack support

### ISSUE THREAD

**Issue by kimmy-wang** [vbenjs/vue-vben-admin#1450]
### Subject of the feature

希望新增加一个分支，用来支持webpack而非vite

**Comment by dearmark** [comment]
Vue3生态都会追随Vite脚步，你想要只能自己维护了。

**Comment by realkimmy** [comment]
> Vue3生态都会追随Vite脚步，你想要只能自己维护了。

生产环境还没有迁移到vite，个人以为一段时间内vite达不到webpack的影响力，更多的是一个噱头而已

**Comment by dearmark** [comment]
你认为Vite是噱头，那你去[Vue3](https://github.com/vuejs/vue-next)下留言啊，说达不到`webpack的影响力`，让他们弃用；去[Vite](https://github.com/vitejs/vite)下留言，督促他们如何达到`webpack的影响力`或者叫他们放弃项目，在这儿说没用。

**Comment by realkimmy** [comment]
你吃枪药了你，爱支持不支持，大不了不用，好心提个建议，什么态度？

**Comment by dearmark** [comment]
其实我是在开玩笑，我只是路人甲。
