### ISSUE TITLE
win7 搜狗浏览器（最新版本） 弹窗 BasicModal无法 弹出。ad 的弹窗可以弹出。已测试

### ISSUE THREAD

**Issue by yundou147** [vbenjs/vue-vben-admin#1454]
### 描述 Bug

win7 搜狗浏览器（最新版本） 弹窗 BasicModal无法 弹出。ad 的弹窗可以弹出

### 复现 Bug

官方模版，无法打开

## 系统信息
win7 
搜狗浏览器（最新版本）

**Comment by yundou147** [comment]
搜狗浏览器版本 11  用内测的搜狗浏览器12版本 可以

**Comment by dearmark** [comment]
https://github.com/anncwb/vue-vben-admin/issues/1381#issuecomment-988789014
vite.config.ts 添加 cssTarget: 'chrome86',
