### ISSUE TITLE
编译后，系统主题配色设置失效！

### ISSUE THREAD

**Issue by think-gem** [vbenjs/vue-vben-admin#1471]
### 描述 Bug

开发环境正常，build后，生产环境出现，主题配色不生效问题，如下图：

![image](https://user-images.githubusercontent.com/4160972/145849120-38910f4c-c57f-4e54-8a1c-2903b0fae62a.png)

### 复现 Bug

上图官网演示也如此：https://vvbin.cn/next/#/permission/front/page

## 系统信息

- 操作系统: chrome

**Comment by 18613740987** [comment]
我也是，编译后t1环境系统主题设置不生效

**Comment by codingSir** [comment]
解决了吗？我这边也是

**Comment by think-gem** [comment]
还未解决，暂时还没抽出时间研究，如果已经解决希望可以发上来解决方案  @dievdy   @codingSir  @anncwb

**Comment by smallyaohailu** [comment]
路过。。。

**Comment by think-gem** [comment]
已解决：https://gitee.com/thinkgem/jeesite-vue/commit/8cddc3e006cf5992db9aaf2cdfeae9d62a13b708
