### ISSUE TITLE
pnpm下peer依赖报错，麻烦升级一下包

### ISSUE THREAD

**Issue by pincman** [vbenjs/vue-vben-admin#1491]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ √] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ √] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ √] 已在 Issues 中搜索了相关的关键词
- [ √] 不是 ant design vue 组件库的 Bug

### 描述 Bug

pnpm最新版会对peer进行检测,不正确则出现警告，作者这边有两个vite插件出现问题，如下，请把这两个包内部的依赖弄一下，谢谢

### 复现 Bug

```shell
 WARN  Issues with peer dependencies found
.
├─┬ vite-plugin-mock
│ └─┬ @rollup/plugin-node-resolve
│   ├── ✕ missing peer rollup@^2.42.0
│   └─┬ @rollup/pluginutils
│     └── ✕ missing peer rollup@^1.20.0||^2.0.0
└─┬ vite-plugin-svg-icons
  └─┬ svg-baker
    └─┬ postcss-prefix-selector
      └── ✕ unmet peer postcss@"7.x || 8.x": found 5.2.18
```
## 临时解决方案
package.json 
```json
 "pnpm": {
        "overrides": {
            "postcss": "^8.4.5"
        }
    }
```
and `pnpm add rollup -D`

## 系统信息

- 操作系统: macos
- Node 版本: 17
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 6.24.1

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
