### ISSUE TITLE
table 搜索表单配置 确认按钮 onClick 配置报警

### ISSUE THREAD

**Issue by lhf6623** [vbenjs/vue-vben-admin#1528]
vben版本 "version": "2.8.0"

    formConfig: {
      submitButtonOptions: {
      
         // 这个配置报警
        onClick: () => {
        },
      },
    },

报警提示：Invalid prop: type check failed for prop "onClick". Expected Function, got Array
![image](https://user-images.githubusercontent.com/29174474/147306455-519e18a1-ef4e-4321-b2df-f7489adb10eb.png)

**Comment by lhf6623** [comment]
官方例子配置也报警
![image](https://user-images.githubusercontent.com/29174474/147306862-7b87c3ac-0636-4e4b-913c-cc2d3e582af9.png)

**Comment by lhf6623** [comment]
formConfig: {
      labelWidth: 120,
      schemas: searchFormSchema,
      autoSubmitOnEnter: true,
      submitFunc: async () => {

        await reload();
      },
    },

解决了这样用

**Comment by likui628** [comment]
因为多了一个没用的onClick导致的
