### ISSUE TITLE
请问表格的reload方法该如何使用，reload里该传什么参数进去

### ISSUE THREAD

**Issue by SmallDryad** [vbenjs/vue-vben-admin#1529]
我在使用editRow参数的时候出现了重复渲染的问题，导致跟表格数据展示有关的变动变得特别卡。这个问题在我去掉rowKey以后解决了。
但新的问题出现了，没有rowKey表格就无法实时响应dataSource的数据变动，我必须刷新界面才能看到表格数据的变化。
之后我看到了reload方法可以刷新表格，我想着是否能给我的部分事件用上这个方法。但是我不理解说明文档中的使用方法，也不知道该传什么参数进去。我尝试过不传参数，这个方法不起作用。
请问我该如何使用这个方法，reload里该传什么参数。

**Comment by wangxiaoer5200** [comment]
去useDataSource.ts文件看看几个方法定义就知道了。
  
  async function reload(opt?: FetchParams) {
    return await fetch(opt);
  }
  相当于重新请求fetch的接口，可以传请求参数。

不知道你具体场景 也许你使用updateTableData改变具体某个单元或者使用updateTableDataRecord去改变某一行这两方法更加合适你。

**Comment by wangxiaoer5200** [comment]
去useDataSource.ts文件看看几个方法定义就知道了。
  
  async function reload(opt?: FetchParams) {
    return await fetch(opt);
  }
  相当于重新请求fetch的接口，可以传请求参数。

不知道你具体场景 也许你使用updateTableData改变具体某个单元或者使用updateTableDataRecord去改变某一行这两方法更加合适你。
