### ISSUE TITLE
table组件报错

### ISSUE THREAD

**Issue by flylhb** [vbenjs/vue-vben-admin#1554]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

Warning: [ant-design-vue: Table] `column.slots` is deprecated. Please use `v-slot:headerCell` `v-slot:bodyCell` instead.

### 复现 Bug
打开/#/comp/table/basic页面

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by flylhb** [comment]
table组件报错

**Comment by MssText** [comment]
Maybe [#1562](https://github.com/vbenjs/vue-vben-admin/pull/1563)  can fix this problem

**Comment by wangxiaoer5200** [comment]
![image](https://user-images.githubusercontent.com/38752239/148001684-d349fa9f-d3bc-4b8a-9d7f-537a1fa5e6b1.png)
