### ISSUE TITLE
CollapseContainer 组件的BUG

### ISSUE THREAD

**Issue by vssir** [vbenjs/vue-vben-admin#1555]
### 描述 Bug
canExpan 属于与  #action 插槽冲突？当 canExpan=false 时，#action 插槽放置的按扭消息了，当 canExpan=true 时则显示

### 复现 Bug
实例 CollapseContainer，:canExpan="false"，然后添加添加 #action 插槽
`
<CollapseContainer title="这是测试"  :canExpan="false">
      <template #action>
             <a-button>test</a-button>
      </template>
</CollapseContainer>
`
按扭不能显示，:canExpan="true" 才能显示。
vue-vben-admin 旧版本是可以的，是最近更新的版本出现的问题

## 系统信息

- 操作系统: win11
- Node 版本: v16.13.1
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 6.24.4

**Comment by wangxiaoer5200** [comment]
可以复现，受pr#1525影响
