### ISSUE TITLE
在Form组件的componentMap中加入自定义组件，在一些页面报错

### ISSUE THREAD

**Issue by Walk4Muscle** [vbenjs/vue-vben-admin#1558]
我希望在Form组件中加入自定义的表单组件，我们基于框架的ApiSelect组件，封装了一个ApiSelectWrap组件，注册在`componentMap.ts`文件中，但是在某些页面初始化的时候，系统会报如下错误：
```
componentMap.ts:80 Uncaught ReferenceError: Cannot access 'ApiSelectWrap' before initialization
```

我的注册方式:
```
//Agenthub Custom
import  ApiSelectWrap  from '/@/components/Agenthub/ApiSelectWrap.vue';
//...
//default components
//...
componentMap.set('ApiSelectWrap', ApiSelectWrap);
```

希望得到帮助，应该如何正确地初始化组定义组件。

**Comment by wangxiaoer5200** [comment]
在使用页面引入注册你的ApiSelectWrap组件 然后用render。

     render: ({ model, field }) => {
        return h(ApiSelectWrap, ComponentProps);
      },
      model值集合对象，field，ComponentProps你组件的props对象

**Comment by Walk4Muscle** [comment]
发现问题的原因了，因为我自定义的组件是直接引用了`ApiSelect`，所以在页面上import的时候，一定要放在`'/@/components/Table'`之后才行。
