### ISSUE TITLE
3.0版本打开页脚后分页内容显示不全

### ISSUE THREAD

**Issue by zxuanhong** [vbenjs/vue-vben-admin#1562]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ✅] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

3.0版本打开页脚后分页显示不全
<img width="1714" alt="iShot2022-01-03 09 57 14" src="https://user-images.githubusercontent.com/62740686/147895249-f35397ea-8d06-4cad-8e70-1707bf978015.png">

## System Info

- Operating System: mac
- Node version: v17.0.1
- Package manager (npm/yarn/pnpm) and version: pnpm 6.24.4

**Comment by MssText** [comment]
Maybe [#1562](https://github.com/vbenjs/vue-vben-admin/pull/1563)  can fix this problem

**Comment by flyjin** [comment]
都出到3.0了？

**Comment by Mr-LiuDC** [comment]
> Maybe [#1563](https://github.com/vbenjs/vue-vben-admin/pull/1563) can fix this problem

#1563 并不能解决这个问题，另外还有个开启脚页后部门界面和账号界面的高度不对等，如下图。

![1680822522951](https://user-images.githubusercontent.com/18117854/230510847-9b23e8ef-fe57-4d55-a98d-3f9b85b67407.png)

**Comment by zxuanhong** [comment]
vben is no longer in use, so I closed this issue
