### ISSUE TITLE
编译后，系统主题设置失效

### ISSUE THREAD

**Issue by codingSir** [vbenjs/vue-vben-admin#1568]
环境正常，编译后线上主题失效，版本2.8.0

**Comment by lzdjack** [comment]
官方项目编译后是否出现同样的问题？

**Comment by iporer** [comment]
> 

官方项目一样的，主题失效

**Comment by cuizhanshan** [comment]
#1445

**Comment by Jamboy** [comment]
[https://github.com/vbenjs/vue-vben-admin/issues/1445](url) 按照这个，修改/build/vite/plugin/theme.ts可以

**Comment by Jamboy** [comment]
我这边是打包后样式有问题，按钮下面添加了黑色下划线等，按照这个修改theme.ts后解决 #1445
