### ISSUE TITLE
本地开发环境常常遇到 net::ERR_ABORTED 408 (Request Timeout)

### ISSUE THREAD

**Issue by waney** [vbenjs/vue-vben-admin#1572]
### 描述 Bug

vue-router.esm-bundler.js:3295 TypeError: Failed to fetch dynamically imported module: http://172.27.128.1:3100/src/views/article/add.vue
triggerError @ vue-router.esm-bundler.js:3295
(anonymous) @ vue-router.esm-bundler.js:3030
Promise.catch (async)
pushWithRedirect @ vue-router.esm-bundler.js:3027
push @ vue-router.esm-bundler.js:2962
go @ usePage.ts:28
_createVNode.onClick._cache.<computed>._cache.<computed> @ list.vue?import&t=1641436171680:21
callWithErrorHandling @ runtime-core.esm-bundler.js:6737
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6746
emit$1 @ runtime-core.esm-bundler.js:289
(anonymous) @ runtime-core.esm-bundler.js:6522
handleClick2 @ button.js:119
callWithErrorHandling @ runtime-core.esm-bundler.js:6737
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6746
invoker @ runtime-dom.esm-bundler.js:357
usePage.ts:13 TypeError: Failed to fetch dynamically imported module: http://172.27.128.1:3100/src/views/article/add.vue
handleError @ usePage.ts:13
Promise.catch (async)
go @ usePage.ts:28
_createVNode.onClick._cache.<computed>._cache.<computed> @ list.vue?import&t=1641436171680:21
callWithErrorHandling @ runtime-core.esm-bundler.js:6737
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6746
emit$1 @ runtime-core.esm-bundler.js:289
(anonymous) @ runtime-core.esm-bundler.js:6522
handleClick2 @ button.js:119
callWithErrorHandling @ runtime-core.esm-bundler.js:6737
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6746
invoker @ runtime-dom.esm-bundler.js:357
Editor.vue:6 GET http://172.27.128.1:3100/node_modules/.vite/tinymce_plugins_autolink.js?v=4a313da4 net::ERR_ABORTED 408 (Request Timeout)
Editor.vue:7 GET http://172.27.128.1:3100/node_modules/.vite/tinymce_plugins_autosave.js?v=4a313da4 net::ERR_ABORTED 408 (Request Timeout)
Editor.vue:8 GET http://172.27.128.1:3100/node_modules/.vite/tinymce_plugins_code.js?v=4a313da4 net::ERR_ABORTED 408 (Request Timeout)
Editor.vue:13 GET http://172.27.128.1:3100/node_modules/.vite/tinymce_plugins_insertdatetime.js?v=4a313da4 net::ERR_ABORTED 408 (Request Timeout)

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息
"version": "2.8.0",

$ node -v
v17.1.0

$ pnpm -v
6.23.2

**Comment by DoubleRayWang** [comment]
超时时间改长一点试试， 默认的好像是10s
