### ISSUE TITLE
tree树形异步懒加载,点击两次才能关闭

### ISSUE THREAD

**Issue by lydat** [vbenjs/vue-vben-admin#1588]
![image](https://user-images.githubusercontent.com/36094163/149448078-59a01f41-1005-4e77-93ab-882e62cd104f.png)
![image](https://user-images.githubusercontent.com/36094163/149448871-e799becc-8e7f-4057-afc7-f3914ec4e78f.png)

测试官方项目时,异步加载数据,当展开之后，需要点击两次才会关闭

**Comment by iconFehu** [comment]
现在貌似点不开了

**Comment by iconFehu** [comment]
![image](https://user-images.githubusercontent.com/46149128/169234724-75eb4c81-3f12-4d14-aa42-49be59b30b28.png)

**Comment by iconFehu** [comment]
#1935
