### ISSUE TITLE
基础表单懒加载远程下拉rule验证错误

### ISSUE THREAD

**Issue by sinceseason** [vbenjs/vue-vben-admin#1589]
Version 2.8.0
基础表单--懒加载远程下拉框
当我点击input框的 x 号去除默认值，然后选择一项，表单下方会提示错误，但是此时是有值的，如下图：
![image](https://user-images.githubusercontent.com/14029440/149469396-81733453-d91a-4ec7-a139-1acbad1803fd.png)

但是再次选择后不会出现错误提示

**Comment by lzdjack** [comment]
看pr 有修复

**Comment by vurtnr** [comment]
拉取了最新的pr，问题好像依然存在，大佬。
![image](https://user-images.githubusercontent.com/8241528/160046449-c6eb260b-d080-4e1b-8be2-3abc84403580.png)
点击这个删除按钮，然后重新选择下拉项
![image](https://user-images.githubusercontent.com/8241528/160046497-8e120b7f-98b7-45b2-ba04-e3acb69b892d.png)
依然会有错误信息出现
