### ISSUE TITLE
开发正常，打包部署以后报错，报错信息 Uncaught TypeError: qt[e].default is not iterable

### ISSUE THREAD

**Issue by redbule2** [vbenjs/vue-vben-admin#1590]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
开发正常，打包部署以后报错，报错信息 Uncaught TypeError: qt[e].default is not iterable
![QQ图片20220114220956](https://user-images.githubusercontent.com/97743446/149528511-4f5a3467-309c-4e77-b7a7-e05132c8dd77.png)

### 复现 Bug
``

## 系统信息

- 操作系统:win10
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm

**Comment by redbule2** [comment]
![image](https://user-images.githubusercontent.com/97743446/149538604-3738bb55-0e46-470e-b05d-8b9473563cb8.png)

**Comment by Qingchen9** [comment]
请问解决了...

**Comment by bboyHan** [comment]
解决了吗？ 怎么解决的

**Comment by datasre** [comment]
请问解决了么，我目前也遇到了这个问题

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
