### ISSUE TITLE
Warning: [ant-design-vue: Table] `column.slots` is deprecated. Please use `v-slot:headerCell` `v-slot:bodyCell` instead.

### ISSUE THREAD

**Issue by GlenLee0402** [vbenjs/vue-vben-admin#1604]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

table表格
### 复现 Bug
table表格
## 系统信息

- 操作系统:Mac
- Node 版本:14.18.2
- 包管理器 (npm/yarn/pnpm) 及其版本:yarn

**Comment by CoroLee** [comment]
1

**Comment by Galen-xiaogao** [comment]
请问这个问题什么时候修复下呢

**Comment by cuifuan** [comment]
https://next.antdv.com/components/table-cn#components-table-demo-fixed-columns

**Comment by cuifuan** [comment]
参考下述链接修改后
https://github.com/vbenjs/vue-vben-admin/commit/a23020b76d4fd69871d7a782efe6a9f13eeca6c1
参照官方文档写，例如
```html
      <template #bodyCell="{ column, record }">
        <template v-if="column.key === 'houseId'">
          <a-button type="link" @click="openHouseDetailDrawer(record)">
            {{ record.houseId }}
          </a-button>
        </template>
      </template>
```
