### ISSUE TITLE
Modal  组件错误，按钮无法点击

### ISSUE THREAD

**Issue by skyzfdance** [vbenjs/vue-vben-admin#1609]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

当前BUG，非 Vben 问题。出在  ant design vue 3.0.0-beta.7 错误，它会导致，Model 出现 `TypeError: 'set' on proxy: trap returned falsish for property 'getContainer'`，升级至 beta.8 或者是 降级即可。

### 复现 Bug

当前 2.8.0 版本 测试站点即可复现

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
