### ISSUE TITLE
组件菜单下的弹窗组件打不开，打开了的也没法关闭

### ISSUE THREAD

**Issue by fxzer** [vbenjs/vue-vben-admin#1612]
组件菜单下的弹窗组件好好几个都打不开，而且有些打开了，但是没法关闭，只有刷新才能关闭，希望作者可以修复

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
