### ISSUE TITLE
是否有计划适配naive-ui组件库，扩展vben的生态圈？

### ISSUE THREAD

**Issue by 551685830** [vbenjs/vue-vben-admin#1621]
是否有计划适配naive-ui组件库，扩展vben的生态圈？

**Comment by qingmang** [comment]
支持

**Comment by 551685830** [comment]
> 圈

是否有计划时间表？还是已经在开发或beta中了？

**Comment by 531431988** [comment]
一个个都不赞助作者哪有精力开发维护那么多？天天写代码女朋友都没时间摸了，快生锈了！！
虽然我也很想有，市面上有很多naive-ui的但都收费……还是这个作者更像雷锋赞一个

**Comment by honghuangdc** [comment]
基于naiveUI的免费中后台 https://github.com/honghuangdc/soybean-admin
