### ISSUE TITLE
build报错

### ISSUE THREAD

**Issue by Dog12306** [vbenjs/vue-vben-admin#1622]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

npm run build 打包至最后报错，没有生成appConfig文件 

### 复现 Bug

![1643161675(1)](https://user-images.githubusercontent.com/48237249/151089972-e5708262-1b80-4b1a-88d9-84af09725f32.png)

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:
- 
![1643161940(1)](https://user-images.githubusercontent.com/48237249/151090055-aa93cba2-9903-4892-a6af-7ba4974a7b7a.png)

**Comment by dzvane** [comment]
我也报错了~~

**Comment by guitao** [comment]
我的也是。

**Comment by wangxiaoer5200** [comment]
node升级为16+ 然后试试看

**Comment by sunxy** [comment]
升级vite-plugin-imagemin到0.6.1

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
