### ISSUE TITLE
克隆代码到本地启动，浏览器报错：可选链操作符 语法错误 Uncaught SyntaxError: Unexpected token . 

### ISSUE THREAD

**Issue by liuwang66** [vbenjs/vue-vben-admin#1627]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

请大佬指教一下：克隆代码到本地启动，浏览器报错：可选链操作符 语法错误 Uncaught SyntaxError: Unexpected token . ，
感谢感谢！

### 复现 Bug

1. 克隆代码到本地，yarn insall 后，执行 yarn serve 启动项目
2. 打开浏览器，F12 console 报错 Uncaught SyntaxError: Unexpected token . ;

## 系统信息

- 操作系统: window
- Node 版本: 16.9.0
- 包管理器 (npm/yarn/pnpm) 及其版本: 7.xx.xx

**Comment by zuihou** [comment]
用正版谷歌

**Comment by Frank11223** [comment]
使用最新版谷歌

**Comment by xietongjian** [comment]
我也遇到这个问题了。Uncaught SyntaxError: Unexpected token '...'

**Comment by cnhuye** [comment]
> 我也遇到这个问题了，本地打包后用Nginx代理运行。Uncaught SyntaxError: Unexpected token '...' ![image](https://user-images.githubusercontent.com/16096832/163117217-3a52bcf3-9ceb-4fcc-a263-60b17f0ce8ad.png)

Hi,  怎么样，解决了吗，我也遇到同样的问题。原因是引用了 v-viewer。编译后启动就出这个错误了。

**Comment by xietongjian** [comment]
感谢您的来信，您的来信我会及时回复
有事请致电13510419502 或QQ583110978联系
姓名：谢桐健 
联系方式：手机13510419502  QQ583110978 
中级软件工程师，系统架构师，网站网页设计工程师
有意者请致电话或QQ联系

**Comment by shijunti19** [comment]
@Frank11223 和浏览器无关
怎么解决啊
