### ISSUE TITLE
package install error[404 ]

### ISSUE THREAD

**Issue by bujidao** [vbenjs/vue-vben-admin#1639]
- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

when i clone this rpo and then install with pnpm,it appear "ERR_PNPM_FETCH_404"

### 复现 Bug

1. git clone https://github.com/anncwb/vue-vben-admin.git
2. cd vue-vben-admin
3. pnpm install

......
Relinking E:\workbench\coding\int\vue-vben-admin\node_modules\.pnpm\cssom@0.4.4\node_modules\cssom from the store
Relinking E:\workbench\coding\int\vue-vben-admin\node_modules\.pnpm\cssom@0.3.8\node_modules\cssom from the store
Relinking E:\workbench\coding\int\vue-vben-admin\node_modules\.pnpm\data-urls@2.0.0\node_modules\data-urls from the store
ERR_PNPM_FETCH_404  GET https://registry.npm.taobao.org/filelist/-/filelist-1.0.2.tgz: Not Found - 404

No authorization header was set for the request.
Progress: resolved 1560, reused 757, downloaded 57, added 811
......

## 系统信息

- 操作系统: win10
- Node 版本:v17.4.0
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm 6.30.0

**Comment by wangxiaoer5200** [comment]
去掉package.json中的"bin-wrapper": "npm:bin-wrapper-china"，(这句话是用于npm和yarn防止生成乱码的解决方法)
然后再重新安装试试。

**Comment by zhuoshengjie** [comment]
同样的问题

**Comment by zongpengz** [comment]
和你一样的问题，我将node版本从12.18.2切到16.13.2就好了。

**Comment by smallmonke** [comment]
> 去掉package.json中的"bin-wrapper": "npm:bin-wrapper-china"，(这句话是用于npm和yarn防止生成乱码的解决方法) 然后再重新安装试试。
尝试了 能安装成功部分包
![image](https://user-images.githubusercontent.com/16320122/156145907-4d8585f2-9752-4826-b038-45b1d4a9540d.png)

**Comment by smallmonke** [comment]
> 去掉package.json中的"bin-wrapper": "npm:bin-wrapper-china"，(这句话是用于npm和yarn防止生成乱码的解决方法) 然后再重新安装试试。

尝试了能安装成功部分包
![image](https://user-images.githubusercontent.com/16320122/156146271-f9d97067-d09e-427a-8af7-c68fa8704096.png)

**Comment by smallmonke** [comment]
> 16.13.2

好像也不行 pnpm和vite都试过了
![image](https://user-images.githubusercontent.com/16320122/156149939-8f49f43d-3cea-47aa-acac-6a1275c13d32.png)

**Comment by zongpengz** [comment]
> > 16.13.2
> 
> 好像也不行 pnpm和vite都试过了 ![image](https://user-images.githubusercontent.com/16320122/156149939-8f49f43d-3cea-47aa-acac-6a1275c13d32.png)

把node_modules全删了再试试，还有可以试试npm

**Comment by Mr-xzq** [comment]
切换到 npm 的源试试
![image](https://user-images.githubusercontent.com/53166933/157056077-0b95f802-2d22-49ca-be42-48c0f4e5bd25.png)

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
