### ISSUE TITLE
菜单切换为分割菜单，左侧菜单折叠后无法显示

### ISSUE THREAD

**Issue by caiiansheng** [vbenjs/vue-vben-admin#1644]
### 描述 Bug

菜单切换为分割菜单，左侧菜单折叠后无法显示

### 复现 Bug

![image](https://user-images.githubusercontent.com/26760483/153106726-ba9c61f4-42cd-4ce7-b609-daffccada74c.png)

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by lqxlearn** [comment]
routes 配置上icon 就可以显示了。

**Comment by mynetfan** [comment]
左侧菜单折叠后只显示icon。你没有为菜单配置icon，折叠后就啥也没有。
