### ISSUE TITLE
模块文件过多

### ISSUE THREAD

**Issue by oseaweed** [vbenjs/vue-vben-admin#1652]
打包后基本一个组件一个文件包，网络请求太频繁了，请问会优化这方面性能嘛

**Comment by carl-jin** [comment]
这个属于 vite 的配置优化了，我尝试过把所有文件压缩到一起，也尝试过将输出文件按 dependencies 拆分，但是都不是太理想，最后的最优化方式是将 css 代码合并成一个文件，然后使用 pwa 做预加载，这样既保证用户首屏渲染快，而且在用户登录页面浏览器空闲的时候，还会预加载文件。

你可以折腾折腾，但是折腾来折腾去，如果要想保证首屏的速度，vite 现在默认的打包方式确实是最好的，就看你怎么在 首屏加载速度上，和整体加载速度上做取舍

另外可以在服务区上设置 http2 ，这样会显著提升加载速度，因为 chrome 在 http1 的请求下，同时间只能处理 6 个资源的请求，这就导致如果文件太多的话就会堵塞

**Comment by carl-jin** [comment]
要先把 css 文件合并成一个文件，只需要在 `vite.config.ts -> build.cssCodeSplit` 改为 `false` 即可

**Comment by oseaweed** [comment]
> 这个属于 vite 的配置优化了，我尝试过把所有文件压缩到一起，也尝试过将输出文件按 dependencies 拆分，但是都不是太理想，最后的最优化方式是将 css 代码合并成一个文件，然后使用 pwa 做预加载，这样既保证用户首屏渲染快，而且在用户登录页面浏览器空闲的时候，还会预加载文件。
> 
> 你可以折腾折腾，但是折腾来折腾去，如果要想保证首屏的速度，vite 现在默认的打包方式确实是最好的，就看你怎么在 首屏加载速度上，和整体加载速度上做取舍
> 
> 另外可以在服务器上开启 http2 ，这样会显著提升加载速度，因为 chrome 在 http1 的请求下，同时间只能处理 6 个资源的请求，这就导致如果文件太多的话就会堵塞

和首屏加载以及整体加载不冲突吧 我指的是一个模块如果组件拆分的很细 能不能合并成一个文件

**Comment by carl-jin** [comment]
> > 这个属于 vite 的配置优化了，我尝试过把所有文件压缩到一起，也尝试过将输出文件按 dependencies 拆分，但是都不是太理想，最后的最优化方式是将 css 代码合并成一个文件，然后使用 pwa 做预加载，这样既保证用户首屏渲染快，而且在用户登录页面浏览器空闲的时候，还会预加载文件。
> > 你可以折腾折腾，但是折腾来折腾去，如果要想保证首屏的速度，vite 现在默认的打包方式确实是最好的，就看你怎么在 首屏加载速度上，和整体加载速度上做取舍
> > 另外可以在服务器上开启 http2 ，这样会显著提升加载速度，因为 chrome 在 http1 的请求下，同时间只能处理 6 个资源的请求，这就导致如果文件太多的话就会堵塞
> 
> 和首屏加载以及整体加载不冲突吧 我指的是一个模块如果组件拆分的很细 能不能合并成一个文件

用 rollup 的这个 [manualchunks](https://rollupjs.org/guide/en/#outputmanualchunks) 就行了。

举个🌰  假设你的模块是按页面划分了
```typescript
// vite.config.js

export default {
  build: {
    rollupOptions: {
      output: {
        //    这个方法每个文件的引用都会执行一次
        manualChunks(id) {
          //  id 就是模块的路径， 比如 /Users/name/Desktop/project/src/views/home/index.vue 这样
          let res = id.match(/\/src\/views\/(\w+)\//);
          if (res) {
            //    这里的 moduleName 就是 home
            let [_, moduleName] = res;

            //  如果 manualChunks 返回的有值，他就会将其打包成对应的文件
            //  比如这里就会打包成 home.hash.js
            //  假如你的 home/ 下面有很多文件被引用，他都会打包成到 home.hash.js
            return moduleName;
          }

          //  如果啥也没返回就按默认的模块处理
        },
      },
    },
  },
};
```

这样配置你可以最大程度的控制模块的拆封。

**Comment by oseaweed** [comment]
> > > 这个属于 vite 的配置优化了，我尝试过把所有文件压缩到一起，也尝试过将输出文件按 dependencies 拆分，但是都不是太理想，最后的最优化方式是将 css 代码合并成一个文件，然后使用 pwa 做预加载，这样既保证用户首屏渲染快，而且在用户登录页面浏览器空闲的时候，还会预加载文件。
> > > 你可以折腾折腾，但是折腾来折腾去，如果要想保证首屏的速度，vite 现在默认的打包方式确实是最好的，就看你怎么在 首屏加载速度上，和整体加载速度上做取舍
> > > 另外可以在服务器上开启 http2 ，这样会显著提升加载速度，因为 chrome 在 http1 的请求下，同时间只能处理 6 个资源的请求，这就导致如果文件太多的话就会堵塞
> > 
> > 
> > 和首屏加载以及整体加载不冲突吧 我指的是一个模块如果组件拆分的很细 能不能合并成一个文件
> 
> 用 rollup 的这个 [manualchunks](https://rollupjs.org/guide/en/#outputmanualchunks) 就行了。
> 
> 举个🌰 假设你的模块是按页面划分了
> 
> ```ts
> // vite.config.js
> 
> export default {
>   build: {
>     rollupOptions: {
>       output: {
>         //    这个方法每个文件的引用都会执行一次
>         manualChunks(id) {
>           //  id 就是模块的路径， 比如 /Users/name/Desktop/project/src/views/home/index.vue 这样
>           let res = id.match(/\/src\/views\/(\w+)\//);
>           if (res) {
>             //    这里的 moduleName 就是 home
>             let [_, moduleName] = res;
> 
>             //  如果 manualChunks 返回的有值，他就会将其打包成对应的文件
>             //  比如这里就会打包成 home.hash.js
>             //  假如你的 home/ 下面有很多文件被引用，他都会打包成到 home.hash.js
>             return moduleName;
>           }
> 
>           //  如果啥也没返回就按默认的模块处理
>         },
>       },
>     },
>   },
> };
> ```
> 
> 这样配置你可以最大程度的控制模块的拆封。
感谢 找到思路了

**Comment by coolswitch** [comment]
> > > 这个属于 vite 的配置优化了，我尝试过把所有文件压缩到一起，也尝试过将输出文件按 dependencies 拆分，但是都不是太理想，最后的最优化方式是将 css 代码合并成一个文件，然后使用 pwa 做预加载，这样既保证用户首屏渲染快，而且在用户登录页面浏览器空闲的时候，还会预加载文件。
> > > 你可以折腾折腾，但是折腾来折腾去，如果要想保证首屏的速度，vite 现在默认的打包方式确实是最好的，就看你怎么在 首屏加载速度上，和整体加载速度上做取舍
> > > 另外可以在服务器上开启 http2 ，这样会显著提升加载速度，因为 chrome 在 http1 的请求下，同时间只能处理 6 个资源的请求，这就导致如果文件太多的话就会堵塞
> > 
> > 
> > 和首屏加载以及整体加载不冲突吧 我指的是一个模块如果组件拆分的很细 能不能合并成一个文件
> 
> 用 rollup 的这个 [manualchunks](https://rollupjs.org/guide/en/#outputmanualchunks) 就行了。
> 
> 举个🌰 假设你的模块是按页面划分了
> 
> ```ts
> // vite.config.js
> 
> export default {
>   build: {
>     rollupOptions: {
>       output: {
>         //    这个方法每个文件的引用都会执行一次
>         manualChunks(id) {
>           //  id 就是模块的路径， 比如 /Users/name/Desktop/project/src/views/home/index.vue 这样
>           let res = id.match(/\/src\/views\/(\w+)\//);
>           if (res) {
>             //    这里的 moduleName 就是 home
>             let [_, moduleName] = res;
> 
>             //  如果 manualChunks 返回的有值，他就会将其打包成对应的文件
>             //  比如这里就会打包成 home.hash.js
>             //  假如你的 home/ 下面有很多文件被引用，他都会打包成到 home.hash.js
>             return moduleName;
>           }
> 
>           //  如果啥也没返回就按默认的模块处理
>         },
>       },
>     },
>   },
> };
> ```
> 
> 这样配置你可以最大程度的控制模块的拆封。

我尝试了以下拆分方式：
1. 将 node_modules 模块拆分为几个块，以避免超大包
2. 将 views 按模块打包，以减少细碎chunks

但结果并不太好，会加载无用模块，比如登录页面加载了dashboard页面的包，dashboard又顺带加载了echarts

导致首屏渲染还是慢的，请问有什么建议吗？或者我做错了什么？ @carl-jin
