### ISSUE TITLE
演示网站登录报错404

### ISSUE THREAD

**Issue by JiangNaa** [vbenjs/vue-vben-admin#1662]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
演示网站登录报错404 ，https://vvbin.cn/next/#/login?redirect=/dashboard 使用vben 123456登录报错404

**Comment by dearmark** [comment]
![image](https://user-images.githubusercontent.com/3938942/154842208-2808af4f-d953-4cc2-8262-b440b84d8c61.png)
没问题啊？

**Comment by JiangNaa** [comment]
@dearmark 
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/19604643/154874269-6d08ccab-33f1-4095-96db-5b228cbd28ce.png">
我这里不知道为啥这样。。

**Comment by dearmark** [comment]
![image](https://user-images.githubusercontent.com/3938942/154883485-eddb9532-5974-4e1e-a1cc-6cad9f9b6dd1.png)
清空缓存或使用Chrome无痕模式试试

**Comment by a1067111756** [comment]
清除缓存无用，接口https://vvbin.cn/basic-api/login 404

**Comment by andy7076** [comment]
+1 同样的问题
