### ISSUE TITLE
浏览器打开多个窗口,一个退出登录，其他窗口还能正常操作如：查询，新增，切换页面

### ISSUE THREAD

**Issue by centersxy** [vbenjs/vue-vben-admin#1678]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

浏览器打开多个窗口,退出登录，其他窗口还能正常操作如：查询，新增，切换页面

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by passioncsu** [comment]
你可以在退出登录的时候自己把token清除掉...

**Comment by toKnowMore** [comment]
这应该不关他这啥事吧，退出时应该调用退出接口，然后token失效，其他页面继续操作应该报401。你是不是应该问问你们后台退出逻辑是啥样的？
