### ISSUE TITLE
No index signature with a parameter of type 'string' was found on type 'Partial<ViteEnv>'

### ISSUE THREAD

**Issue by eshimischi** [vbenjs/vue-vben-admin#1680]
https://github.com/vbenjs/vue-vben-admin/blob/3c9f394acb2675587ffcd44999a89d15ce5bb42c/admin/config/index.ts#L32

<img width="800" alt="Screenshot 2022-02-27 at 11 42 45" src="https://user-images.githubusercontent.com/983201/155877370-7ed80301-b147-4a81-83b7-00ac2e1853f4.png">

we should do like that `viteEnv[key as keyof ViteEnv] = realName;`

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
