### ISSUE TITLE
在简版上添加一个element-plus 版本就完美了

### ISSUE THREAD

**Issue by taolei1990** [vbenjs/vue-vben-admin#1685]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?
还是比较喜欢用element-plus 可扩展度高

**Comment by shellingfordly** [comment]
可以看下https://github.com/shellingfordly/vele-admin

**Comment by eyon-org** [comment]
期待你的大作，哈哈

**Comment by pany-ang** [comment]
来个自荐https://github.com/un-pany/v3-admin

**Comment by MySecret** [comment]
期待支持一个element-plus版本！！！！

**Comment by GHKevins** [comment]
找到了吗 @MySecret

**Comment by yinqiangw** [comment]
期待 简版上添加一个element-plus 版本就完美了

**Comment by HC-miss** [comment]
最近在学习源码，发现之前想用`element-plus`重写的想法太简单了，项目封装的基础组件可是非常复杂。:rofl:
也很希望能使用`element-plus`版本的Vben Admin。:grin:

**Comment by shellingfordly** [comment]
> 最近在学习源码，发现之前想用`element-plus`重写的想法太简单了，项目封装的基础组件可是非常复杂。🤣 也很希望能使用`element-plus`版本的Vben Admin。😁

可以看下[vele-admin](https://github.com/shellingfordly/vele-admin)，移植了基础工具，和几个基础组件

**Comment by falcon-jin** [comment]
必须要推荐这一个 https://github.com/kailong321200875/vue-element-plus-admin 代码质量超级高
