### ISSUE TITLE
升级报错，多次删除node_modules及lock文件重试都一样

### ISSUE THREAD

**Issue by waney** [vbenjs/vue-vben-admin#1686]
```
鈥塛ARN鈥?deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
省略....
鈥塛ARN鈥?deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
省略....
鈥塛ARN鈥?deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
省略....
鈥塛ARN鈥?deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
鈥塛ARN鈥?deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
鈥塛ARN鈥?deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
省略....

husky - Git hooks installed

鈥塛ARN鈥?Issues with peer dependencies found
.
鈹斺攢鈹?vite-plugin-svg-icons
  鈹斺攢鈹?svg-baker
    鈹斺攢鈹?postcss-prefix-selector
      鈹斺攢鈹€ 鉁?unmet peer postcss@"7.x || 8.x": found 5.2.18 in svg-baker
```

vue-vben-admin: 2.8.0
node: v17.1.0

**Comment by LUDA0831** [comment]
我也是这样的,请问解决了没

**Comment by smallyaohailu** [comment]
我用下面的方式升级，没有遇到类似问题。

如何保证我的代码能更新到最新代码
如果你使用了该项目进行项目开发。开发之中想同步最新的代码。你可以设置多个源的方式

克隆代码
git clone https://github.com/vbenjs/vben-admin-thin-next.git
添加自己的公司 git 源地址
# up 为源名称,可以随意设置
# gitUrl为开源最新代码
git remote add up gitUrl;
提交代码到自己公司 git
# 提交代码到自己公司
# main为分支名 需要自行根据情况修改
git push up main

# 同步公司的代码
# main为分支名 需要自行根据情况修改
git pull up main
如何同步开源最新代码
git pull origin main
TIP

同步代码的时候会出现冲突。只需要把冲突解决即可

**Comment by LUDA0831** [comment]
> 我用下面的方式升级，没有遇到类似问题。
> 
> 如何保证我的代码能更新到最新代码 如果你使用了该项目进行项目开发。开发之中想同步最新的代码。你可以设置多个源的方式
> 
> 克隆代码 git clone https://github.com/vbenjs/vben-admin-thin-next.git 添加自己的公司 git 源地址
> 
> # up 为源名称,可以随意设置
> # gitUrl为开源最新代码
> git remote add up gitUrl; 提交代码到自己公司 git
> 
> # 提交代码到自己公司
> # main为分支名 需要自行根据情况修改
> git push up main
> 
> # 同步公司的代码
> # main为分支名 需要自行根据情况修改
> git pull up main 如何同步开源最新代码 git pull origin main TIP
> 
> 同步代码的时候会出现冲突。只需要把冲突解决即可

谢谢,刚找到解决方法了https://github.com/vbenjs/vue-vben-admin/issues/1491#issue-1082372539
