### ISSUE TITLE
安装证书

### ISSUE THREAD

**Issue by Bi-xia** [vbenjs/vue-vben-admin#1687]
现在为什么要安装证书了呀 这个是干嘛的哦

**Comment by zhouhexiang12** [comment]
截图看看啊

**Comment by yuzhuo25** [comment]
> 截图看看啊

![image](https://user-images.githubusercontent.com/22900776/163955567-55dea7c0-0355-4597-be3f-54628e9f2b53.png)

**Comment by pandavips** [comment]
你好 是如何解决的?

**Comment by ifredom** [comment]
这是为后门做准备

**Comment by ahgaoyong** [comment]
这是vite-plugin-mkcert 遇上 vite.config.ts文件里面的server.https: true时, 没有mkcert https证书所导致的问题,

一些人建议更改vite.config.ts文件里面的server.https值为false, 其实, 更优雅的做法是:

直接在命令行启动参数增加 --https false 即可, 例如:

yarn dev --https false
pnpm dev --https false
cnpm dev --https false
npm dev --https false
或者你修改package.json里面的scripts dev脚本也行

{ 
  "scripts": {
    //其他配置...
    "dev": "vite --https false",
    // 其他配置...
  }
}
