### ISSUE TITLE
权限路由使用BACK，刷新界面一级菜单不会激活，但是使用currentActiveMenu又会导致出现两个相同的面包屑

### ISSUE THREAD

**Issue by longyi-xw** [vbenjs/vue-vben-admin#1690]
![image](https://user-images.githubusercontent.com/54786937/156500552-0f7c65ac-0ca4-4000-b0f4-1a84b5dac31a.png)

![image](https://user-images.githubusercontent.com/54786937/156500517-28d4fede-308b-4755-955b-f9ecc4d30348.png)

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
