### ISSUE TITLE
开发的时候vue文件被编译无法准确定位到文件位置

### ISSUE THREAD

**Issue by Walk4Muscle** [vbenjs/vue-vben-admin#1691]
开发的时候vue文件被编译，格式、行数都乱了
![image](https://user-images.githubusercontent.com/14989270/156711869-5543cedd-a02e-41dd-9ce8-9fcd6f42fa7b.png)
console和debuger定位错乱
![image](https://user-images.githubusercontent.com/14989270/156711964-fb53ce9c-e355-4bc4-b7e5-f8a364b602c7.png)
请问如何解决

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
