### ISSUE TITLE
权限使用了ROLE并在routes中添加了roles后无法正常显示菜单

### ISSUE THREAD

**Issue by GggXp** [vbenjs/vue-vben-admin#1694]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/). 已阅读https://vvbin.cn/doc-next/guide/auth.html#%E5%AE%9E%E7%8E%B0
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词 有 #1214  是类似问题但是未解决即被关闭，并且后文中的解决方案无效
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

将权限模式修改为ROLE并对routes添加roles后无法显示菜单
![image](https://user-images.githubusercontent.com/5029513/157014621-217d86dc-5efd-406e-b14b-1889ae7e1fa8.png)

### 复现 Bug

1. 使用代码版本 af6ab9
![image](https://user-images.githubusercontent.com/5029513/157013961-ea544abc-9c20-43a0-9009-23e1e44685f2.png)

2. 将projectSetting.ts中的permissionMode修改为PermissionModeEnum.ROLE
![image](https://user-images.githubusercontent.com/5029513/157014225-1944c7db-c3be-4e13-9b24-d9010467ae8a.png)

3. routes中添加roles
![image](https://user-images.githubusercontent.com/5029513/157014417-704973e2-0222-43de-9cd0-ef2c71fbd057.png)

4. 无其他改动
![image](https://user-images.githubusercontent.com/5029513/157014498-ff19539f-3504-46ff-a944-4c9eb377aba2.png)

5. 运行yarn serve，无法正常显示菜单
![image](https://user-images.githubusercontent.com/5029513/157014621-217d86dc-5efd-406e-b14b-1889ae7e1fa8.png)

## 系统信息

- 操作系统: Windows 10 21H1
- Node 版本: v16.13.0
- 包管理器 (npm/yarn/pnpm) 及其版本:  npm 8.4.1 yarn 1.22.5
- 浏览器 Microsoft Edge 版本 99.0.1150.30 (官方内部版本) (64 位)

**Comment by GggXp** [comment]
ROLE模式权限要求菜单放到src/router/menus/modules下而不是src/router/routes/modules下……

**Comment by Adaptables** [comment]
请问大佬，可以看看权限这里你写的代码吗

**Comment by sugar258596** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/84883966/8e183823-d700-4b56-8855-76ee7fd636db)
这里的  const { menu } = menuModule; 都没有menu 属性，那么又是怎么进行写呢
