### ISSUE TITLE
vben3.0（next分支）打包报错（测试环境运行正常，但无法打包）

### ISSUE THREAD

**Issue by 1455668754** [vbenjs/vue-vben-admin#1697]
vben3.0打包报错（测试环境运行正常，但无法打包）
![image](https://user-images.githubusercontent.com/88491446/157157777-6f2ff870-dabf-4ae5-a2b3-75d800216450.png)

**Comment by anncwb** [comment]
该分支还在调试，暂不使用

**Comment by 1455668754** [comment]
已收，尽快给您回复。
