### ISSUE TITLE
网站挂了

### ISSUE THREAD

**Issue by Valar103769** [vbenjs/vue-vben-admin#1703]
登录不了了

**Comment by dearmark** [comment]
![image](https://user-images.githubusercontent.com/3938942/157815433-b8be6e9a-1ec8-4ee7-9e75-dea65b5bb2e9.png)
没问题啊！
![image](https://user-images.githubusercontent.com/3938942/157815552-843b778c-68b1-40dd-b85e-54844451dfb0.png)

**Comment by SuperH-2001-12-30** [comment]
哥们无痕模式开的很六
