### ISSUE TITLE
ApiSelect 数据展示bug

### ISSUE THREAD

**Issue by briefness** [vbenjs/vue-vben-admin#1706]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

如果ApiSelect 接口返回的数据是这个格式[1,2,3,4,5],展示空白

### 复现 Bug

表格的查询表单中，有个异步的select，使用ApiSelect组件进行展示，
{
      field: 'brand_level',
      label: '品牌等级',
      component: 'ApiSelect',
      componentProps: {
        api: brandLevelList, // 这是一个异步调用接口的方法，返回一个promise
        immediate: true,
      },
    },

接口返回的数据格式是【1，2，3，4】这样的一个数组

这种情况，我怎么指定他的label和value

## 系统信息

- 操作系统:Mac
- Node 版本:14.16.0
- 包管理器 (npm/yarn/pnpm) 及其版本: yarn 1.22.10

**Comment by IFnGSiYu** [comment]
自己处理接口数据，或者自行改ApiSelect的getOptions方法就行了

**Comment by TrancyAlois** [comment]
componentProps中可以指定label和value
componentProps: {
      api: getAreaTree,
      labelField: 'name',
      valueField: 'id',
    },
