### ISSUE TITLE
table多选以后选项跨页显示错误

### ISSUE THREAD

**Issue by wangmin0314** [vbenjs/vue-vben-admin#1714]
表格第一页选择了几项以后切换到第二页再选择时不会保留第一页的选择状态。
https://vvbin.cn/next/#/comp/table/formTable
![image](https://user-images.githubusercontent.com/23734878/158166564-b48eb6ed-6f19-4b7d-95de-d717008308d8.png)
![image](https://user-images.githubusercontent.com/23734878/158166629-2df5cc84-d64b-4bf6-b680-12a0314f6688.png)
![image](https://user-images.githubusercontent.com/23734878/158166658-9ba2c803-6c1a-4e1e-b455-2481a028c28d.png)
第三张图是第二页选择以后

**Comment by IFnGSiYu** [comment]
这个问题有解决吗

**Comment by wangmin0314** [comment]
> 这个问题有解决吗

没有解决

**Comment by IFnGSiYu** [comment]
这个问题不是框架的问题，是antd的问题，3.x版本后做了调整，绑定一下rowSelection.preserveSelectedRowKeys==true即可

**Comment by wangmin0314** [comment]
> preserveSelectedRowKeys

**Comment by shuperry** [comment]
在 src\components\Table\src\hooks\useRowSelection.ts 的 useRowSelection 函数的 return  对象中添加 preserveSelectedRowKeys: true 即可解决此问题，亲测好使

**Comment by skywolf627** [comment]
```    
<BasicTable
      @register="registerTable"
      :rowSelection="{
        type: 'checkbox',
        selectedRowKeys: checkedKeys,
        onChange: onSelectChange,
        preserveSelectedRowKeys: true,
      }"
    >
</BasicTable>
````

页面上这样传值就可以了，不需要改hooks里的文件
