### ISSUE TITLE
table 表头都无效了，变成了操作。。。

### ISSUE THREAD

**Issue by smallyaohailu** [vbenjs/vue-vben-admin#1717]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

请清晰地描述此 Bug 的具体表现。

### 复现 Bug
https://vvbin.cn/next/#/system/account
![image](https://user-images.githubusercontent.com/718669/158304636-c3f95464-3a80-442c-9602-77a3832d4f48.png)

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by jinmao88** [comment]
修复了

**Comment by smallyaohailu** [comment]
超级感谢，努力学习该框架中。日后必奉献一份力量。。。谢啦
