### ISSUE TITLE
系统管理——账号管理——新作——选择角色——已经选择角色了，还红色提示

### ISSUE THREAD

**Issue by lixiaolong117** [vbenjs/vue-vben-admin#1718]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

在你们演示环境中按如下顺序操作：
系统管理——账号管理——新作——选择角色——已经选择角色了，还红色提示。
我的项目中使用了这个控件，出现了同样的bug。
另外，你们正式版什么时候出啊
### 复现 Bug

在你们演示环境中按如下顺序操作：
系统管理——账号管理——新作——选择角色——已经选择角色了，还红色提示。

## 系统信息

- 操作系统:Mac
- Node 版本:16
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm

**Comment by zhangjianmei323** [comment]
加这个：itemProps: { validateTrigger: 'blur' },

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
