### ISSUE TITLE
安装的时候这个报错是咋回事啊，win10

### ISSUE THREAD

**Issue by zxh451200** [vbenjs/vue-vben-admin#1727]
npm ERR! code EPERM
npm ERR! syscall unlink
npm ERR! path C:\Users\A8202\Desktop\vue-vben-admin-main\node_modules\.staging\ant-design-vue-ef35fd4f\dist\antd.js
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, unlink 'C:\Users\A8202\Desktop\vue-vben-admin-main\node_modules\.staging\ant-design-vue-ef35fd4f\dist\antd.js'
npm ERR!  [OperationalError: EPERM: operation not permitted, unlink 'C:\Users\A8202\Desktop\vue-vben-admin-main\node_modules\.staging\ant-design-vue-ef35fd4f\dist\antd.js'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, unlink 'C:\Users\A8202\Desktop\vue-vben-admin-main\node_modules\.staging\ant-design-vue-ef35fd4f\dist\antd.js'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'unlink',
npm ERR!     path: 'C:\\Users\\A8202\\Desktop\\vue-vben-admin-main\\node_modules\\.staging\\ant-design-vue-ef35fd4f\\dist\\antd.js'
npm ERR!   },
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'unlink',
npm ERR!   path: 'C:\\Users\\A8202\\Desktop\\vue-vben-admin-main\\node_modules\\.staging\\ant-design-vue-ef35fd4f\\dist\\antd.js',
npm ERR!   parent: 'vue-vben-admin-main'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\A8202\AppData\Roaming\npm-cache\_logs\2022-03-18T02_13_42_723Z-debug.log

**Comment by anncwb** [comment]
用管理员模式去运行
