### ISSUE TITLE
是否可以新建一个  使用 Websocket 全局工具

### ISSUE THREAD

**Issue by oliver225** [vbenjs/vue-vben-admin#1732]

**Comment by oliver225** [comment]
类似这种   的 http://tool.hhyang.cn/doc3/socket/socket.html

**Comment by oliver225** [comment]
类似这种的  https://github.com/SilurianYang/uni-app-tools/blob/master/uni-app-chat/useSocket.js

**Comment by wangjue666** [comment]
可参考demo https://vben.vvbin.cn/#/feat/ws
