### ISSUE TITLE
提取 components 组件

### ISSUE THREAD

**Issue by cn-src** [vbenjs/vue-vben-admin#1739]
### Subject of the feature

能否将 components 组件提取为单独的 npm 组件库。

或者将 components 组件存放到单独的 git 仓库，然后以子仓库的方式引入，这样方便用户单独更新 components 组件。

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by 158710** [comment]
+1

**Comment by jun-luo-changsha** [comment]
+1

**Comment by wangjue666** [comment]
vben2暂无计划，vben3正在做这样的事
