### ISSUE TITLE
iframe中嵌入本地html

### ISSUE THREAD

**Issue by YANGHAOHEHE** [vbenjs/vue-vben-admin#1744]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

各位大佬，我在iframe中嵌入本地的html，如public下直接放一个test.html，无论我是直接用iframe，还是用sys/iframe下的组件，直接在src里用“test.html”或者是“./public/test.html”，访问到的都是项目页面本身，这种情况如何调整可以正常让我访问到本地的html？有的第三方页面实在没办法做成组件
### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- win11
- Node 版本:
- 16
- 包管理器 (npm/yarn/pnpm) 及其版本:
yarn v1.21.1

**Comment by gaoyuan533515** [comment]
俺也一样

**Comment by YANGHAOHEHE** [comment]
> 我去 我也遇到了

兄弟有解决方案吗

**Comment by YANGHAOHEHE** [comment]
> 俺也一样

您好，现在有解决方案吗？我现在只能把静态页面放在后台

**Comment by datasre** [comment]
我也遇到了这个问题，请问解决了么?

**Comment by datasre** [comment]
> 看下下面的评论 是一个插件有问题 注释了就好 html-plugin那个
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年10月13日(星期五) 下午3:29 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [vbenjs/vue-vben-admin] iframe中嵌入本地html (Issue #1744) 我也遇到了这个问题，请问解决了么? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的 确实是这个插件有问题，这个插件注释掉就好了,谢谢

**Comment by datasre** [comment]
不对还是有问题，就是我嵌入的本地html没有展示  我的iframe是嵌在model中在 model弹出来的是空白的，没有得到想要的html页面

**Comment by datasre** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/54182063/7582913b-69cb-48e5-b282-fa685e7fc35b)
model组件的具体是这样的

**Comment by datasre** [comment]
> 你把插件禁用了就好了 不用做别的 而且这个在线上是没问题的 只有线下不行
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年10月13日(星期五) 下午3:42 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [vbenjs/vue-vben-admin] iframe中嵌入本地html (Issue #1744) model组件的具体是这样的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好的 我已经找到问题了，解决了，谢谢解答
