### ISSUE TITLE
使用pageWrapper组件时遇到的问题

### ISSUE THREAD

**Issue by Chopinchan24** [vbenjs/vue-vben-admin#1746]
![image](https://user-images.githubusercontent.com/32224664/160046122-5666da66-9ff2-411c-b004-170929d3e3bc.png)
在页面中引用pageWrapper时会偶现这个bug。
win10、chrome

**Comment by java-lyf** [comment]
+1

**Comment by Luqir** [comment]
+1

**Comment by Zhao-changyuan** [comment]
+100

**Comment by dennislan** [comment]
+1
have same issue. 

OS: Macos
Browser:  Chrome  v100

必定发生：否
发生时机:   有时改完页面，重刷页面时。
如何解决：清除浏览器缓存，重新打开，此问题自动消失了。

**Comment by su-yongjian** [comment]
+1，强行清除浏览器缓存也不能解决，必须重新启动服务才可以

**Comment by webzhouyan** [comment]
+1  必须重启服务

**Comment by chenguang1994** [comment]
+1

**Comment by ap950** [comment]
+1

**Comment by pengjiangyi** [comment]
+1

**Comment by ChanKingBooo** [comment]
+1

**Comment by qifox** [comment]
+1，遇到了一样的问题

**Comment by iconFehu** [comment]
+1，遇到了一样的问题

**Comment by Curitis-TK** [comment]
+1，遇到相同问题

**Comment by rookiePrgrmer** [comment]
+1，遇到同样的问题。

我理解是，PageWrapper.vue 这个组件在 Page/index.ts 里被导入，但是， PageWrapper 在编译阶段又会去到 Page/index.ts 导入 定义在了下面的那个常量，但这个时候那个常量还没初始化，所以就报错了。

比如在 PageWrapper 直接写死那个常量对应的字符串，而不是导入那个常来那个，就不会再报错了。

**Comment by Ls-Bin** [comment]
留意一下引入的组件，不能直接使用.vue那个组件
我用下面这种方式引入就没问题了：
`import {PageWrapper} from '/@/components/Page';`

**Comment by Anima-No** [comment]
> 留意一下引入的组件，不能直接使用.vue那个组件 我用下面这种方式引入就没问题了： `import {PageWrapper} from '/@/components/Page';`

你这个写法有问题吧
