### ISSUE TITLE
初始化安装包pnpm install报错

### ISSUE THREAD

**Issue by yisuo2015** [vbenjs/vue-vben-admin#1749]
报错信息如下：

Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: D:\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1353, reused 1265, downloaded 68, added 163, done
node_modules/.pnpm/core-js@3.21.1/node_modules/core-js: Running postinstall script, done in 90ms
node_modules/.pnpm/cwebp-bin@5.1.0/node_modules/cwebp-bin: Running postinstall script, done in 433ms
node_modules/.pnpm/esbuild@0.11.23/node_modules/esbuild: Running postinstall script...
node_modules/.pnpm/esbuild@0.11.3/node_modules/esbuild: Running postinstall script...
node_modules/.pnpm/gifsicle@5.2.0/node_modules/gifsicle: Running postinstall script, done in 430ms
node_modules/.pnpm/jpegtran-bin@5.0.2/node_modules/jpegtran-bin: Running postinstall script, done in 414ms
node_modules/.pnpm/jpegtran-bin@6.0.1/node_modules/jpegtran-bin: Running postinstall script, failed in 63ms
.../node_modules/jpegtran-bin postinstall$ node lib/install.js
│ D:\Projects\Repos\vue-vben-admin-main\node_modules\.pnpm\jpegtran-bin@6.0.1\node_modules\jpegtran-bin\lib\install.js
│ import process from 'node:process';
│        ^^^^^^^
│ SyntaxError: Unexpected identifier
│     at Module._compile (internal/modules/cjs/loader.js:703:23)
│     at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
│     at Module.load (internal/modules/cjs/loader.js:628:32)
│     at Function.Module._load (internal/modules/cjs/loader.js:555:12)
│     at Function.Module.runMain (internal/modules/cjs/loader.js:824:10)
│     at internal/main/run_main_module.js:17:11
└─ Failed in 63ms
node_modules/.pnpm/mozjpeg@7.1.1/node_modules/mozjpeg: Running postinstall script...
 ELIFECYCLE  Command failed with exit code 1.

**Comment by yisuo2015** [comment]
升级了node 16.14.2解决了

**Comment by yyman001** [comment]
感谢分享, 使用12版本虽然成功安装,但是跑不起来.............果断切换node版本

**Comment by ajcRodrigues** [comment]
Hi,

I fixed it on Ubuntu installing nasm, just did:

```
sudo apt-get install nasm
```
