### ISSUE TITLE
npm install时候 出现下面的报错

### ISSUE THREAD

**Issue by wingjie** [vbenjs/vue-vben-admin#1751]
<!--
抱歉，您遇到了一个错误。感谢您抽出宝贵的时间进行举报！npm install 时候卡在       jpegtran-bin@6.0.1
这里

**Comment by greenhat616** [comment]
![图片](https://user-images.githubusercontent.com/41122242/160388731-1061a643-c15c-4266-b2d6-5a34006f58e5.png)
