### ISSUE TITLE
如何实时获取BasicForm的表单值呢？

### ISSUE THREAD

**Issue by ILikeCoder** [vbenjs/vue-vben-admin#1761]
![image](https://user-images.githubusercontent.com/57169689/160549158-4203b41a-109e-4fa4-8527-1fbf42c806dd.png)

**Comment by ILikeCoder** [comment]
此处应该要怎么写才能正确监听到formModel的变化呢？

**Comment by KtfwyCJ** [comment]
你好，可以参考我的[PR](https://github.com/vbenjs/vue-vben-admin/pull/1801)

**Comment by KtfwyCJ** [comment]
你好，可以参考我的[PR](https://github.com/vbenjs/vue-vben-admin/pull/1801)来解决这个问题。
