### ISSUE TITLE
体验页面-系统管理-角色管理-菜单分配界面问题

### ISSUE THREAD

**Issue by songjiyang** [vbenjs/vue-vben-admin#1763]
![image](https://user-images.githubusercontent.com/19657391/160745042-d0c06b32-bcea-41a1-9a28-a84d1d9411f3.png)
看起来菜单信息没有完全展示，很不友好

**Comment by kevinlau2015** [comment]
我这里是这样的

![image](https://user-images.githubusercontent.com/13088124/162862359-8fd5fb25-d63c-446c-9aca-8568478c326a.png)
