### ISSUE TITLE
树形结构添加拖动

### ISSUE THREAD

**Issue by SwankyTigerYY** [vbenjs/vue-vben-admin#1765]
### Subject of the feature

希望添加树形结构拖动效果。

### Problem

我不能实现这个效果。

### Expected behaviour

我想实现菜单树形结构，拖动节点（如果拖动父级节点，它的子集一起移动），更换位置，点击保存按钮，将新结构数据发送给接口。

### Alternatives

我找了些网上其它项目，基础效果有了，很生硬。

**Comment by wangjue666** [comment]
[`antdv`](https://www.antdv.com/components/tree-cn )现在已支持
