### ISSUE TITLE
form 不能禁用自动填充吗？autocomplete

### ISSUE THREAD

**Issue by kandandiani** [vbenjs/vue-vben-admin#1767]
form 不能禁用自动填充吗？autocomplete

**Comment by WchHxl** [comment]
`{
    field: 'deptId',
    label: '所属部门',
    component: 'TreeSelect',
    componentProps: {
      autocomplete: 'off',
    },
    slot: 'deptId',
    colProps: {
      sm: 12,
      md: 12,
      lg: 8,
      xl: 6,
    },
  },`
只能这样单独设置某条吗？
