### ISSUE TITLE
npm run serve报错

### ISSUE THREAD

**Issue by Hawkinss** [vbenjs/vue-vben-admin#1768]
### 描述 Bug
由于工作需要，需在内网环境调试代码，目前下载代码能在外网电脑上正常运行，将代码及npm-cache一起拷贝到内网电脑，运行npm run serve提示getaddrinfo ENOTFOUND e.coding.net at GetAddrInfoReqWrap.onloopup [as oncomplete] (node:dns:71:26)
hosts文件已修改为 127.0.0.1 localhost
## 系统信息

- 操作系统: 
- 内网电脑 win10-64bit，外网电脑 win11-64bit
- Node 版本:均为16.14.2
- 包管理器 (npm/yarn/pnpm) 及其版本:
  内网npm-8.5.0 外网npm-8.5.5
![图片](https://user-images.githubusercontent.com/51350166/160796263-d9b5ae01-c018-41cc-8d4d-cadcf10760cc.png)

**Comment by CloudnuY** [comment]
mkcert插件导致，可以在vite.config.ts中把server.https设为false

**Comment by Hawkinss** [comment]
> mkcert插件导致，可以在vite.config.ts中把server.https设为false

完美解决问题，谢谢大佬

**Comment by yurenzhen** [comment]
不用改任何代码, 直接在命令行启动参数增加 --https false 即可(你要永久改package.json里面的vite脚本也行), 例如:
yarn dev --https false
pnpm dev --https false
cnpm dev --https false
npm dev --https false
