### ISSUE TITLE
tab页的问题，在一个tab页，弹窗出来编辑，编辑时需要从另外的tab页复制资料，只要点另外的tab页，编辑页就自动关闭了

### ISSUE THREAD

**Issue by sunqintao** [vbenjs/vue-vben-admin#1773]
如题，tab页编辑时不能离开当前页，离开就自动关闭了

**Comment by DreamBuddy** [comment]
需要开启keep-alive
keep-alive 生效的前提是：需要将路由的 name 属性及对应的页面的 name 设置成一样。因为：
include - 字符串或正则表达式，只有名称匹配的组件会被缓存
