### ISSUE TITLE
RadioButtonGroup，赋值有问题

### ISSUE THREAD

**Issue by dzvane** [vbenjs/vue-vben-admin#1774]
Demo里的系统管理-菜单管理-修改  菜单类型赋值有问题了
![微信图片_20220402135658](https://user-images.githubusercontent.com/13115589/161370196-e638ff62-c81a-45e3-ad20-71162009f528.png)

**Comment by lijunfeng** [comment]
https://github.com/vbenjs/vue-vben-admin/pull/1608

**Comment by dzvane** [comment]
> #1608

感谢，updateSchema放前面可以了
