### ISSUE TITLE
怎么禁用form的自动调整

### ISSUE THREAD

**Issue by csm12s** [vbenjs/vue-vben-admin#1780]
选择之后，这个自动跑到右边了
![image](https://user-images.githubusercontent.com/64699457/161668912-a93aa0e2-febc-4b82-ae35-27717664c579.png)

### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by csm12s** [comment]
![image](https://user-images.githubusercontent.com/64699457/161668974-361b5bf1-6210-4e51-9868-8d3a736a02ed.png)

**Comment by csm12s** [comment]
好像设置 inline 就行了

**Comment by wangjue666** [comment]
formschma 有个 col 和 span这样的栅栏配置
