### ISSUE TITLE
表格api获取数据的方式，不支持跨页勾选

### ISSUE THREAD

**Issue by IFnGSiYu** [vbenjs/vue-vben-admin#1781]
可以参考预览的属性表格和开启搜索区域示例，希望大佬能解决下

**Comment by vssir** [comment]
api获取方式，下一页的数据都还没加载进来，怎样钩选？

**Comment by IFnGSiYu** [comment]
> api获取方式，下一页的数据都还没加载进来，怎样钩选？

2.0版本是可以的
