### ISSUE TITLE
富文本编辑器在页面有滚动条的情况下会错位

### ISSUE THREAD

**Issue by sjlei** [vbenjs/vue-vben-admin#1782]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

在页面上使用富文本编辑器，当页面有垂直滚动条时，滚动任意距离，富文本工具条上的下拉都会出现错位的问题。

![image](https://user-images.githubusercontent.com/34293221/162117598-591b903c-0a2b-4762-80ac-79cfda9bbccd.png)
![image](https://user-images.githubusercontent.com/34293221/162117608-7c151246-b20d-4350-82f0-1ae8e3bcb390.png)

### 复现 Bug

https://vvbin.cn/next/#/comp/editor/tinymce/index

## 系统信息

- 操作系统: windows10
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by horizon188** [comment]
html,
body {
  width: auto !important;
  height: auto !important;
}

**Comment by guohaiping521** [comment]
设置了也不行

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！

**Comment by Anima-No** [comment]
> 感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个问题。由于我无法修复该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！

没有修复呀，老哥
