### ISSUE TITLE
打开public下文件时候总会进入vue路由里匹配

### ISSUE THREAD

**Issue by 2016011969sunyifang** [vbenjs/vue-vben-admin#1784]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

在使用windows.open打开public下文件例如XXX.html时候 总会进入vue路由里匹配 然后显示匹配失败而不是加载静态文件

### 复现 Bug

  window.open(`/sss.html`);
  
![image](https://user-images.githubusercontent.com/37146715/162140908-cd59c21b-6962-4840-be46-ccbdcbdeaf66.png)

## 系统信息

- 操作系统:windows
- Node 版本:14.17.1
- 包管理器 (npm/yarn/pnpm) 及其版本:npm6.14.13

**Comment by gaoyuan533515** [comment]
我也遇到这个问题了，通过浏览器地址栏访问public下所有的资源都不能访问

**Comment by 2016011969sunyifang** [comment]
> 我也遇到这个问题了，通过浏览器地址栏访问public下所有的资源都不能访问

请问您是如何解决的
