### ISSUE TITLE
apiCascader 设置defaultValue 界面不回显选择内容

### ISSUE THREAD

**Issue by Hsensor** [vbenjs/vue-vben-admin#1787]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

设置defaultValue 界面不回显选择内容

### 复现 Bug
api cascader 配置如下
`{
  field: 'provinceCityArea',
  component: 'ApiCascader',
  label: '所在省市区',
  defaultValue: ['2','2','18'],
  componentProps: {
    api: standardQuery,
    resultField: 'body',
    labelField: 'name',
    valueField: 'id',
    immediate: true,
    onChange(e: any, selectedOptions: any) {
      console.log(222222, arguments)
    },
    onDefaultChange(e: any, selectedOptions: any) {
      console.log('11111111');
      provinceCityArea.value = selectedOptions.map((item) => {
        return {
          name: item.label,
          id: item.value,
        };
      });
    },
    isLeaf(item) {
      return item.children && item.children.length;
    },
    initFetchParams: {
      method: 'post',
      url: '/management/citys/action/getAddress/',
      params: {},
    },
  },
},`
// 源码位置
`function handleRenderDisplay({ labels, selectedOptions }) {
  console.log('selectedOptions', selectedOptions)
  console.log('unref(emitData)', unref(emitData).length)
  if (unref(emitData).length === selectedOptions.length) {
    return labels.join(' / ');
  }
  if (props.displayRenderArray) {
    return props.displayRenderArray.join(' / ');
  }
  return '';
}`

  //  控制台输出
![image](https://user-images.githubusercontent.com/8132535/162555810-c547b14b-e7b8-4eef-a80a-6f9c229c486f.png)
// 界面显示 cascader options 有默认选中，但是界面没有回显（unref(emitData).length 一直是0）
![image](https://user-images.githubusercontent.com/8132535/162556439-6abf1c56-c42e-46b5-8d18-22eceac66ea4.png)

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by SKT1yang** [comment]
我也遇到了，还以为数据原因

**Comment by TrancyAlois** [comment]
这个问题解决了没，我也遇到这个问题了。接口拿到数据之后，回显不了，但是下拉框的值是已经选中的状态了。
![image](https://user-images.githubusercontent.com/32919573/163975020-63d90d3d-09af-4013-9c63-871f63eb359f.png)

**Comment by TrancyAlois** [comment]
接口拿到数据之后找到一种方法来赋值。
接口查询的时候要把label的值给拿到，然后以数组的形式给update上去
![image](https://user-images.githubusercontent.com/32919573/164183760-d7b5780d-0007-4f35-b3b4-048733ed78ef.png)

**Comment by Hsensor** [comment]
> 接口拿到数据之后找到一种方法来赋值。 接口查询的时候要把label的值给拿到，然后以数组的形式给update上去 ![image](https://user-images.githubusercontent.com/32919573/164183760-d7b5780d-0007-4f35-b3b4-048733ed78ef.png)
用cascader 做吧， apiCascader
