### ISSUE TITLE
本地运行正常但是打包上线后页面打不开

### ISSUE THREAD

**Issue by frankye23** [vbenjs/vue-vben-admin#1804]
### Describe the bug
本地运行正常但是打包上线后页面打不开，页面控制台报错如下
![9176acbeda8c66de752608f9e18ffd0](https://user-images.githubusercontent.com/92201847/163112493-f7cd2d87-a177-40e3-9563-5297e98f627b.png)
jenkins输出如下
![1530082695631225ab16795d220931d](https://user-images.githubusercontent.com/92201847/163112522-31d6ee34-ef3d-4ecc-91f2-295c76f7b869.png)

### Reproduction

不清楚页面不显示的原因是否与这个type=module相关报错有关呢？如果有的话type=module应该写在哪里？我在index.html中的两个script标签内都加入了该语句，仍然不起作用

## System Info

- Operating System: windows
- Node version: 14.18.2
- Package manager (npm/yarn/pnpm) and version: yarn:1.22.17 npm:6.14.15

**Comment by xcxxcxxcxh** [comment]
咋解决的，这可是事故级bug
