### ISSUE TITLE
菜单目录不显示图标

### ISSUE THREAD

**Issue by Hawkinss** [vbenjs/vue-vben-admin#1808]
### 描述 Bug
菜单不显示图标

### 复现 Bug

菜单目录返回数据包括icon，下载图标集也包括该图标，但是菜单不显示图标,安装了包ant-design/icons-vue，因为是内网，不能在线访问图标，怎么直接访问图标

## 系统信息

- 操作系统:
- Node 版本:16.14.2
- 包管理器 (npm/yarn/pnpm) 及其版本:8.5.0
- 
![图片](https://user-images.githubusercontent.com/51350166/163297229-9594ed9a-2916-4dac-86b4-08cb07bf6351.png)
![图片](https://user-images.githubusercontent.com/51350166/163297241-7c7c0fa4-37d5-4c0e-bc56-ffa663e4abf7.png)
![图片](https://user-images.githubusercontent.com/51350166/163300736-b9e1f879-d539-4b24-9cb7-3bcb72a3be4c.png)

**Comment by UserQC** [comment]
兄弟解决了吗,我也遇到这个问题了,我是有的图标能出来有的出不来

**Comment by Hawkinss** [comment]
> 兄弟解决了吗,我也遇到这个问题了,我是有的图标能出来有的出不来
还没有，还在等大佬搭救，你也是内网环境吗

**Comment by UserQC** [comment]
后台传的icon加上 |svg ,例如: "icon": "appraise|svg",然后本地在assets/icon加上同名svg就会调用本地的svg了
![image](https://user-images.githubusercontent.com/45836397/163536723-1dfa239d-e671-402f-8139-6bba3a7dab31.png)

**Comment by ouyanglingyun** [comment]
因为不管选择本地还是在线，图标数据都没有打包

**Comment by JoyNop** [comment]
编译以后为什么不现实
