### ISSUE TITLE
资源加载失败导致项目在浏览器中假死。

### ISSUE THREAD

**Issue by chenNoway** [vbenjs/vue-vben-admin#1810]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

偶尔会出现资源加载失败的问题，然后一直转菊花。需要刷新一下才能恢复
浏览器控制台表现：
![image](https://user-images.githubusercontent.com/39050622/163309003-673309ee-46fe-4888-80ff-59f13f1a9761.png)

### 复现 Bug

尤其qc见的比较多给我i提了优化bug,自己也能偶现

## 系统信息

- 操作系统:windows
- Node 版本:v16.13.2
- 包管理器 (npm/yarn/pnpm) 及其版本:v8.3.1

**Comment by gh852195168** [comment]
@chenNoway 我也出现了，处理了么大佬

**Comment by wangjue666** [comment]
浏览器是不是安装了一些拦截广告之类插件, 关了试试
