### ISSUE TITLE
下拉远程搜索 warn

### ISSUE THREAD

**Issue by liuhaogui** [vbenjs/vue-vben-admin#1814]
### Describe the bug

form -> base  下拉搜索控制台warn提示
每输一个字符就会提示一次warn
```
runtime-core.esm-bundler.js:38 [Vue warn]: Invalid prop: type check failed for prop "onUpdate:value". Expected Function, got Array  
  at <ASelect onDropdownVisibleChange=fn<handleFetch> showSearch="" onUpdate:value= (2) [ƒ, ƒ]  ... > 
  at <ApiSelect api=fn<optionsListApi> showSearch="" value="0"  ... > 
```
## System Info

- Operating System:  mac
- Node version: v14.15.1
- Package manager (npm/yarn/pnpm) and version: npm(6.14.8)

**Comment by dennislan** [comment]
@TengChongChong 可否给个 Sample Code ? 感谢！

**Comment by TengChongChong** [comment]
@dennislan 
<img width="613" alt="image" src="https://user-images.githubusercontent.com/11783658/176620332-10442c3f-677b-4dee-9a36-da97beff87a3.png">

**Comment by dennislan** [comment]
@TengChongChong 感谢， 加上后 warning 除了。

**Comment by TengChongChong** [comment]
@w345599754 需要在handleChange中添加emit
<img width="297" alt="image" src="https://user-images.githubusercontent.com/11783658/182569500-fbdb6c73-c898-4d06-a66b-3f261da784dc.png">

**Comment by mynetfan** [comment]
最新代码已包含修复
