### ISSUE TITLE
Table滑动卡顿

### ISSUE THREAD

**Issue by DreamBuddy** [vbenjs/vue-vben-admin#1816]
### 描述 Bug

测试5000行数据 BasicTable上下滑动会频繁卡顿，但是拖拽滚动条滑动数据不会发生卡顿，在Antd Vue 3.1.0官方Demo中 测试没卡顿

### 复现 Bug

使用Demo中的views/table/Basic.vue修改数据为5000个，设置为不分页一页展示，固定表头，高度任意（500就行），点击一下table中任意行，然后滑动

## 系统信息

- 操作系统:
- Node 版本: 17.7.1
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 6.32.3

**Comment by DreamBuddy** [comment]
经过测试都使用a-table 在Vben Demo中会卡，在Antd Demo中不会卡

**Comment by DreamBuddy** [comment]
https://github.com/vueComponent/ant-design-vue/blob/900464473823277e4b06ace1c1ddc69ab3ef21d9/components/vc-table/Cell/index.tsx
把antd的这个文件里const { onHover, startRow, endRow } = useInjectHover();相关的代码进行了注释，在vben中也不卡顿了，vben和antd对hover存在某种关系？

**Comment by DreamBuddy** [comment]
https://juejin.cn/post/7063332320339099678
果然是rc-table惹的祸，但是在antd demo下没什么卡顿，很奇怪

**Comment by DreamBuddy** [comment]
如果有性能要求的话 推荐使用下边这个table组件
https://github.com/x-extends/vxe-table

**Comment by xishxu** [comment]
> 如果有性能要求的话 推荐使用下边这个table组件 https://github.com/x-extends/vxe-table

请问使用vxe-table有没有遇到高度自适应的问题？目前我使用vxe-grid控件替换掉vben的table控件，但是高度样式不知道怎么设置，能否指导下，谢谢
