### ISSUE TITLE
是否有集成可视化低代码表单设计器的规划？网上找到一个开源的设计器

### ISSUE THREAD

**Issue by smallyaohailu** [vbenjs/vue-vben-admin#1819]
基于 Vue 的可视化低代码表单设计器，赋能企业实现低代码开发模式；帮助开发者从传统枯燥的表单代码中解放出来，更多关注业务，快速提高效率，节省研发成本。

https://github.com/GavinZhuLei/vue-form-making
https://blog.csdn.net/weixin_28965963/article/details/112402609

### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by ljw-codeking** [comment]
你先把项目bug解决完在想这些吧，组件现在都不是很稳定，这个东西作者应该暂时不会考虑的

**Comment by wangjue666** [comment]
https://vben.vvbin.cn/#/form-designer/design 新版本的有集成了

**Comment by NotFound403** [comment]
> https://vben.vvbin.cn/#/form-designer/design 新版本的有集成了

部分组件能否支持动态数据，比如下拉，我可以注入部门接口，成为一个部门下拉组件
