### ISSUE TITLE
通过浏览器地址栏直接访问public资源出错

### ISSUE THREAD

**Issue by gaoyuan533515** [vbenjs/vue-vben-admin#1822]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

通过浏览器地址栏直直接接访问public资源出错

### 复现 Bug

1 下载github里项目的最新版
2 vscode打开项目
3 pnpm install
4 pnpm serve
5 EDGE浏览器访问，首先控制台有报警，地址栏直接访问http://localhost:3100/resource/img/logo.png，访问不了，路由直接跳转到首页了

![image](https://user-images.githubusercontent.com/33167656/163938462-6df811cf-1317-48a7-8560-3f0f119c71c3.png)

## 系统信息

- 操作系统: win10
- Node 版本:v14.17.1
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm v6.32.8

**Comment by Meihai** [comment]
我遇到同样的问题，在开发环境会有这个问题，生产环境没有这个问题

**Comment by xietongjian** [comment]
我遇到同样的问题了，没找到解决方案。

**Comment by 2016011969sunyifang** [comment]
生产环境没有问题

**Comment by iarray** [comment]
救命一样的问题

**Comment by xietongjian** [comment]
感谢您的来信，您的来信我会及时回复
有事请致电13510419502 或QQ583110978联系
姓名：谢桐健 
联系方式：手机13510419502  QQ583110978 
中级软件工程师，系统架构师，网站网页设计工程师
有意者请致电话或QQ联系

**Comment by xietongjian** [comment]
可以参考这个试试：
https://github.com/vbenjs/vue-vben-admin/issues/1872#issuecomment-1161335089

**Comment by iarray** [comment]
> 可以参考这个试试： [#1872 (comment)](https://github.com/vbenjs/vue-vben-admin/issues/1872#issuecomment-1161335089)

这个改了之后，左侧菜单切换不是有问题吗

**Comment by TengChongChong** [comment]
可以fork vite-plugin-html的代码修改下
