### ISSUE TITLE
useCopyToClipboard.ts 存在问题

### ISSUE THREAD

**Issue by zhuichen** [vbenjs/vue-vben-admin#1823]
### Describe the bug
clipboardRef 采用监听的方式进行复制，如果先复制了其他东西到剪切板，再复制，clipboardRef 没有发生变化，无法复制。

### Reproduction
解决办法：业务方在给clipboardRef 赋值时候，后面追加时间戳，然后复制时候再切割掉

**Comment by lonkang** [comment]
能给个解决方法的demo么，谢谢咯

**Comment by ILikeCoder** [comment]
把这个useCopyToClipboard改造一下就可以了，这是最小的改动方式，不用去改业务代码
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/57169689/227416135-dc6a90b4-8a1b-4f53-9a98-335d1b5995b3.png">

**Comment by ILikeCoder** [comment]
@lonkang 解决方法在上面

**Comment by wangjue666** [comment]
的确有这样的问题， `useCopyToClipboard `已移除 可参考 PR https://github.com/vbenjs/vue-vben-admin/pull/3105
