### ISSUE TITLE
BasicTree超出的内容被隐藏了，建议超出时出现滚动条

### ISSUE THREAD

**Issue by xietongjian** [vbenjs/vue-vben-admin#1827]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

BasicTree超出的内容被隐藏了

### 复现 Bug
参考示例
![image](https://user-images.githubusercontent.com/16096832/163943690-324cf8b0-3cf8-4c9b-b7df-925e44d15120.png)

演示环境：https://vvbin.cn/next/#/system/account
## 系统信息

- 操作系统:
- Node 版本: 演示环境的版本
- 包管理器 (npm/yarn/pnpm) 及其版本:演示环境的版本

**Comment by xietongjian** [comment]
是这里加了个loading导致的。

**Comment by Bing-lemon** [comment]
没有loading ，超出的时候 横向也没出滚动条

**Comment by likui628** [comment]
新版本有滚动条出现
![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/935ce845-2ef2-4fd0-8015-99149ce88fdf)
