### ISSUE TITLE
官网TableDemo固定列BUG

### ISSUE THREAD

**Issue by gaoyuan533515** [vbenjs/vue-vben-admin#1828]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
https://vvbin.cn/next/#/comp/table/fixedColumn   固定列里内容都没显示

### 复现 Bug

![image](https://user-images.githubusercontent.com/33167656/163948455-a9a84f59-e125-4ddf-8511-4ab7f2f403cb.png)
## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by Chenggr** [comment]
有个注释要去掉

**Comment by bboyHan** [comment]
哪个注释？@Chenggr
