### ISSUE TITLE
使用ApiSelect，mode:"multiple"现校验问题

### ISSUE THREAD

**Issue by Mjh1231** [vbenjs/vue-vben-admin#1831]
### 描述 Bug

1. 第一次选择必然报校验不通过信息，第二次则正常。虽然选择第一次报校验不通过但是点击保存可正常保存
2. 点击清除按钮把值清了不会提示校验不通过，但点击保存会正常显示。

![image](https://user-images.githubusercontent.com/37246223/164033436-3e12e0d9-0051-470a-a3f5-7dcd7a77f973.png)
![image](https://user-images.githubusercontent.com/37246223/164034239-aa4802c6-2760-4579-b644-3877c2f12c5b.png)

### 复现 Bug

    const schemas: FormSchema[] = [
        {
          field: 'tpl',
          label: '模板',
          component: 'ApiSelect',
          rules: [
            {
              required: true,
              type: 'array',
            },
          ],
          colProps: {
            span: 16,
          },
          componentProps: {
            mode: 'multiple',
            api: ...,
            onChange: (event) => {
              console.log(event);
            },
            resultField: 'items',
            labelField: 'label',
            valueField: 'value',
          },
        },
      ];

**Comment by GodZhuJunTao** [comment]
https://github.com/vbenjs/vue-vben-admin/pull/1587/commits/f0433c4fe9cbabd9052d92e490c8e21923cf624b

**Comment by GodZhuJunTao** [comment]
> ### 描述 Bug
> 1. 第一次选择必然报校验不通过信息，第二次则正常。虽然选择第一次报校验不通过但是点击保存可正常保存
> 2. 点击清除按钮把值清了不会提示校验不通过，但点击保存会正常显示。
> 
> ![image](https://user-images.githubusercontent.com/37246223/164033436-3e12e0d9-0051-470a-a3f5-7dcd7a77f973.png) ![image](https://user-images.githubusercontent.com/37246223/164034239-aa4802c6-2760-4579-b644-3877c2f12c5b.png)
> 
> ### 复现 Bug
> ```
> const schemas: FormSchema[] = [
>     {
>       field: 'tpl',
>       label: '模板',
>       component: 'ApiSelect',
>       rules: [
>         {
>           required: true,
>           type: 'array',
>         },
>       ],
>       colProps: {
>         span: 16,
>       },
>       componentProps: {
>         mode: 'multiple',
>         api: ...,
>         onChange: (event) => {
>           console.log(event);
>         },
>         resultField: 'items',
>         labelField: 'label',
>         valueField: 'value',
>       },
>     },
>   ];
> ```

https://github.com/vbenjs/vue-vben-admin/pull/1587/commits/f0433c4fe9cbabd9052d92e490c8e21923cf624b
