### ISSUE TITLE
ApiTree 无法被校验

### ISSUE THREAD

**Issue by momohmj** [vbenjs/vue-vben-admin#1833]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ✓ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ✓ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ✓ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..
点击查询按钮无法获取ApiTree的值 
### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem
src/components/Form/scr/components/ApiTree.vue
`<template>
  <a-tree v-bind="getAttrs" @change="handleChange">
    <template #[item]="data" v-for="item in Object.keys($slots)">
      <slot :name="item" v-bind="data || {}"></slot>
    </template>
    <template #suffixIcon v-if="loading">
      <LoadingOutlined spin />
    </template>
  </a-tree>
</template>`
修改为
`<template>
  <a-tree v-bind="getAttrs" @check="handleChange">
    <template #[item]="data" v-for="item in Object.keys($slots)">
      <slot :name="item" v-bind="data || {}"></slot>
    </template>
    <template #suffixIcon v-if="loading">
      <LoadingOutlined spin />
    </template>
  </a-tree>
</template>`
可解决
## System Info

- Operating System: windows10
- Node version:16.14.2
- Package manager (npm/yarn/pnpm) and version: pnpm v2.8.0

**Comment by lifei110196** [comment]
thank you

**Comment by M69W** [comment]
一楼的改动
```diff
- @change="handleChange"
+ @check="handleChange"
```
