### ISSUE TITLE
建议增加多选选择页面

### ISSUE THREAD

**Issue by csm12s** [vbenjs/vue-vben-admin#1837]
建议做一个这种选择的界面，或者参考Demo，这种需求很多，特别是在数据量大的时候
1，
![image](https://user-images.githubusercontent.com/64699457/164442897-a7c0c913-d54f-4239-9626-9424a28112c9.png)
2，
![image](https://user-images.githubusercontent.com/64699457/164442974-7430be75-1ccf-415c-9725-e08e7b28b54c.png)
3，
![image](https://user-images.githubusercontent.com/64699457/164443011-58f45e4b-b455-4cf3-8820-b6d45256ff36.png)

可以参考：http://boot3.jeecg.com/system/user
用户追加

**Comment by Wang62646264** [comment]
没错，这个功能很实用，而且很多地方要用到

**Comment by Wang62646264** [comment]
楼主有解决方案了吗

**Comment by wangjue666** [comment]
https://vben.vvbin.cn/#/comp/table/formTable 可以参考这个页面自行改造
