### ISSUE TITLE
自定义的全局组件中如果使用BasicModal， BasicModal的按钮国际化会失效

### ISSUE THREAD

**Issue by fengbindev** [vbenjs/vue-vben-admin#1843]
![image](https://user-images.githubusercontent.com/28595220/164738280-cbf5a852-6f4c-40b5-a704-92c79ac378aa.png)

**Comment by PigTom-c** [comment]
一样的问题  请问你解决了吗

**Comment by fengbindev** [comment]
> 一样的问题 请问你解决了吗

解决了

**Comment by PigTom-c** [comment]
> 
可以请教一下是怎么解决的吗

**Comment by fengbindev** [comment]
> > 
> 
> 可以请教一下是怎么解决的吗

export async function registerGlobComp(app: App) {
  // 解决自定义全局组件国际无法使用问题，import写在外面会vben会先加载组件后加载国际化，所以import写在里面
  const bpmCom = await import('./BpmnProcessDesigner/package/');
  const MyProcessDesigner = bpmCom.MyProcessDesigner;
  const MyProcessPenal = bpmCom.MyProcessPenal;
  console.log(MyProcessDesigner);
  app
    .use(Input)
    .use(Button)
    .use(Layout)
    .use(withInstall(MyProcessDesigner))
    .use(withInstall(MyProcessPenal));
}

**Comment by PigTom-c** [comment]
> > > 
> > 
> > 
> > 可以请教一下是怎么解决的吗
> 
> export async function registerGlobComp(app: App) { // 解决自定义全局组件国际无法使用问题，import写在外面会vben会先加载组件后加载国际化，所以import写在里面 const bpmCom = await import('./BpmnProcessDesigner/package/'); const MyProcessDesigner = bpmCom.MyProcessDesigner; const MyProcessPenal = bpmCom.MyProcessPenal; console.log(MyProcessDesigner); app .use(Input) .use(Button) .use(Layout) .use(withInstall(MyProcessDesigner)) .use(withInstall(MyProcessPenal)); }

好的  感谢大哥

**Comment by lizeze** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/33169073/4b2246e9-6f4e-40e9-ac29-55b538e83ec2)
![image](https://github.com/vbenjs/vue-vben-admin/assets/33169073/65369628-1e9f-413d-bcf6-b8eff12a9fc4)

我的不仅国际化失效，弹出的窗口样式也出问题了，关闭按钮右偏了
