### ISSUE TITLE
打包后颜色点击没反应

### ISSUE THREAD

**Issue by wangxiang4** [vbenjs/vue-vben-admin#1852]
![image](https://user-images.githubusercontent.com/46394426/165271873-663b73ef-811d-4316-a212-815e012330bc.png)

**Comment by KtfwyCJ** [comment]
> ![image](https://user-images.githubusercontent.com/46394426/165271873-663b73ef-811d-4316-a212-815e012330bc.png)

项目配置仅适用于dev环境

**Comment by wangxiang4** [comment]
你们官网也是一样的也有这个问题
![image](https://user-images.githubusercontent.com/46394426/165420056-61e85b7e-dd80-49e7-bd33-809ca400b3fa.png)

**Comment by wangxiang4** [comment]
我还以为,是写的这个vite-plugin-theme插件出来问题呢

**Comment by wangxiang4** [comment]
我还以为是你写的这个vite-plugin-theme插件出了问题呢

**Comment by wangxiang4** [comment]
准备去重构你这个插件,哈哈

**Comment by wangxiang4** [comment]
貌似好像真的是插件的问题,不管我改什么vite-plugin-theme插件的配置app-theme-style.css始终打包出来的都为空,对应的app-antd-dark-theme-style.css就有css样式数据
![image](https://user-images.githubusercontent.com/46394426/165425330-f6eef650-acd8-4695-b12b-38a41b78bdc8.png)
![image](https://user-images.githubusercontent.com/46394426/165425535-6bd12914-8953-4f93-b3e1-0d30b6c9d991.png)

**Comment by wangxiang4** [comment]
vite似乎有HRM加载问题,打包时有些文件获取不到内容显示export default “’‘”,dev环境会显示,dev环境显示的原因是打开浏览器按需加载,打包是没有按需加载的,有些文件的内容拿不到,就设置不了css系统演示样式变量,貌似这个vite官方那边也没有对应的配置,应该是环境不一致,反正就是拿取不到文件内容
![image](https://user-images.githubusercontent.com/46394426/165477940-92cb2227-54e1-40f0-93f4-0c6323d6ac1c.png)

**Comment by wangxiang4** [comment]
目前解决方案只有把dev环境下生成的系统颜色css变量放到app-theme-style.css文件下了,经过测试可以显示,但是也太不友好了吧
![image](https://user-images.githubusercontent.com/46394426/165479551-555c0214-5b6d-4223-9338-6a6edbed9180.png)
![image](https://user-images.githubusercontent.com/46394426/165479657-9146ae0b-d6c4-4f4e-8869-c4bcb86a282a.png)

**Comment by wangxiang4** [comment]
问题可以确定在vite,那边打包环境transform(code, id),code字段拿不到文件内容,导致vite-plugin-theme解析不到css样式

**Comment by wangxiang4** [comment]
这个问题我解决了,到时候我把代码Pull requests一下,不是 @KtfwyCJ 说的（项目配置仅适用于dev环境） 这个问题

**Comment by joeguang** [comment]
> 



> 这个问题我解决了,到时候我把代码Pull requests一下,不是 @KtfwyCJ 说的（项目配置仅适用于dev环境） 这个问题

切换主题后，button hover样式问题解决了没

**Comment by wangxiang4** [comment]
解决了,只要是colorVariables属性中中包含的颜色都能替换调,把 vite 版本换成 2.5.10 就行
![image](https://user-images.githubusercontent.com/46394426/165706414-0e317406-d36b-4160-bb25-dd89a700ca42.png)

**Comment by wangxiang4** [comment]
![image](https://user-images.githubusercontent.com/46394426/165706748-4ce5b778-1421-4b15-bc4f-98addfaf9c4a.png)

**Comment by wangxiang4** [comment]
项目是基于vben进行重构的,所以基础功能都是一样的,我这边可以,vben那边就也可以
