### ISSUE TITLE
antd2升级到antd-3版本的版本兼容问题

### ISSUE THREAD

**Issue by anke117** [vbenjs/vue-vben-admin#1856]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

main分支最新代码中。Table组件的使用中发现对于antd-3版本中的(warning.js:6 Warning: [ant-design-vue: Table] `column.slots` is deprecated. Please use `v-slot:headerCell` `v-slot:bodyCell` instead.)，由于我是从antd2升级到antd3。最新的框架代码还存在这个警告。

### 复现 Bug

在demo里面的Table组件中的可编辑行，可复现此问题。应该是对于Table组件的props中的actionColumn这个参数，还是用了原来的slots，但是antd-3已不支持此方式引入column
![image](https://user-images.githubusercontent.com/33126327/165431753-9b013808-c86b-4ee6-ae9f-b40bfd7956a8.png)

## 系统信息

- 操作系统: macOS
- Node 版本: 16.9.0
- 包管理器 (npm/yarn/pnpm) 及其版本: yarn 1.22

**Comment by mengwuya** [comment]
![image](https://user-images.githubusercontent.com/36690019/165671307-b6d42161-5cc7-48ef-a972-7d879be1030f.png)
当前可用上图方法解决兼容

**Comment by xujunweb** [comment]
如果要兼容之前的写法就改下BasicTable.vue文件吧：
![image](https://user-images.githubusercontent.com/37604013/166874599-d746cc04-833a-4894-ad1a-64dda1ca810c.png)
useColumns.ts对应的改动：
![image](https://user-images.githubusercontent.com/37604013/166874719-1eaa91c5-b827-483c-8cc9-308454c82f4c.png)
加了新属性(customSlots)记得typs里面的类型也要加

**Comment by passioncsu** [comment]
> 如果要兼容之前的写法就改下BasicTable.vue文件吧： ![image](https://user-images.githubusercontent.com/37604013/166874599-d746cc04-833a-4894-ad1a-64dda1ca810c.png) useColumns.ts对应的改动： ![image](https://user-images.githubusercontent.com/37604013/166874719-1eaa91c5-b827-483c-8cc9-308454c82f4c.png) 加了新属性(customSlots)记得typs里面的类型也要加

我擦  哥们你不会贴代码嘛. 我要抄一遍
