### ISSUE TITLE
ApiSelect组件bug

### ISSUE THREAD

**Issue by Suke77** [vbenjs/vue-vben-admin#1859]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

ApiSelect第一次选择时校验不通过，会出现提示语

### 复现 Bug

ApiSelect第一次选择时校验不通过，会出现提示语，再次进行选择时校验就通过了

## 系统信息

- 操作系统:Windows
- Node 版本:16.14.0
- 包管理器 (npm/yarn/pnpm) 及其版本:npm 8.5.0

**Comment by wangmin0314** [comment]
#1764

**Comment by iconFehu** [comment]
#1616
