### ISSUE TITLE
Column 里面的dataIndex 不支持a.b.c 的嵌套写法

### ISSUE THREAD

**Issue by ckbabby** [vbenjs/vue-vben-admin#1873]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

请清晰地描述此 Bug 的具体表现。

### 复现 Bug
<template>
  <div>
    <BasicTable @register="registerTable" />
  </div>
</template>
<script lang="ts">
  import { defineComponent } from 'vue';

  import { BasicTable, useTable } from '/@/components/Table';

  export default defineComponent({
    name: 'DeptManagement',
    components: { BasicTable },
    setup() {
      const [registerTable] = useTable({
        title: '模型管理',
        columns: [
          {
            title: '名称',
            dataIndex: 'name',
            width: 200,
          },
          {
            title: '分类',
            dataIndex: 'parid.name',
            width: 200,
          },
        ],
        dataSource: [
          { name: '测试', parid: { id: 1, name: '分类一' } },
          { name: '测试二', parid: { id: 2, name: '分类二' } },
        ],
        pagination: false,
        striped: false,
        useSearchForm: false,
        showTableSetting: true,
        bordered: true,
        showIndexColumn: false,
        canResize: false,
        actionColumn: {
          width: 150,
          title: '操作',
          dataIndex: 'action',
          slots: { customRender: 'action' },
          fixed: undefined,
        },
      });

      return {
        registerTable,
      };
    },
  });
</script>

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:windows 11
- Node 版本:v16.14.2
- 包管理器 (npm/yarn/pnpm) 及其版本:8.5.0

**Comment by zuihou** [comment]
看 ant-design-vue3 的文档，已经改成 ['parid', 'name'] 的方式了

**Comment by ckbabby** [comment]
> ant-design-vue3

非常感谢，我一直看ant-design-vue2的文档，没留意到，谢谢了
