### ISSUE TITLE
yarn type:check 检查ts语法 报出40多个ts错误

### ISSUE THREAD

**Issue by fuXiangRong** [vbenjs/vue-vben-admin#1882]
Found 35 errors in 27 files.

Errors  Files
     1  src/components/Form/src/components/ApiTree.vue:2
     2  src/components/SimpleMenu/src/SimpleSubMenu.vue:2
     3  src/components/Menu/src/components/BasicSubMenuItem.vue:2
     1  src/components/Menu/src/components/BasicMenuItem.vue:3
     1  src/components/Loading/src/Loading.vue:4
     1  src/views/dashboard/workbench/components/QuickNav.vue:3
     1  src/layouts/default/setting/components/SwitchItem.vue:6
     1  src/views/demo/comp/flow-chart/index.vue:8
     1  src/components/Form/src/components/ApiSelect.vue:7
     1  src/layouts/default/setting/components/SelectItem.vue:7
     1  src/views/dashboard/workbench/components/ProjectCard.vue:7
     1  src/components/Table/src/components/TableFooter.vue:9
     1  src/components/Menu/src/BasicMenu.vue:11
     1  src/views/demo/editor/json/index.vue:6
     1  src/components/Table/src/components/settings/SizeSetting.vue:10
     1  src/components/Button/src/BasicButton.vue:12
     1  src/views/demo/comp/loading/index.vue:12
     1  src/layouts/default/header/components/user-dropdown/index.vue:13
     3  src/components/Table/src/components/settings/ColumnSetting.vue:18
     1  src/components/Tree/src/TreeHeader.vue:22
     1  src/views/demo/feat/ws/index.vue:43
     2  src/components/Time/src/Time.vue:61
     3  src/components/Form/src/BasicForm.vue:92
     1  src/components/Form/src/helper.ts:55
     1  src/components/Table/src/hooks/useColumns.ts:307
     1  src/store/modules/errorLog.ts:34
     1  src/views/sys/login/useLogin.ts:1
error Command failed with exit code 2.

我修复了几个 只剩35个了

**Comment by wangjue666** [comment]
issue https://github.com/vbenjs/vue-vben-admin/issues/2719, 正在陆续处理
