### ISSUE TITLE
是否可以提供一个接口的对接说明文档？

### ISSUE THREAD

**Issue by YahuiWong** [vbenjs/vue-vben-admin#1884]
是否可以提供如 

* 接口列表
* 错误枚举列表

等接口说明文档？

**Comment by yonghui666** [comment]
你找到了吗老哥，我这用上传接口；都不知道后端要返回什么格式才能跟他对接上

**Comment by YahuiWong** [comment]
> 你找到了吗老哥，我这用上传接口；都不知道后端要返回什么格式才能跟他对接上

目前没有找到

**Comment by ITstyle** [comment]
直接返回 url:'xxx.png'

**Comment by QC2168** [comment]
我查了下login的api，是这样子调用的
```typescript

export function loginApi(params: LoginParams, mode: ErrorMessageMode = 'modal') {
  return defHttp.post<LoginResultModel>(
    {
      url: Api.Login,
      params,
    },
    {
      errorMessageMode: mode,
    },
  );
}

```

**Comment by github-ZH-cn** [comment]
![image](https://user-images.githubusercontent.com/67533362/173981026-499da840-45c3-4e9d-a846-2c4f0c0e4ef2.png)
接口调用成功,数据返回undefined,不知道怎么回事

**Comment by M69W** [comment]
关注一下 
https://github.com/vbenjs/vue-vben-admin/blob/main/src/utils/http/axios/index.ts
https://github.com/vbenjs/vue-vben-admin/blob/main/src/utils/http/axios/checkStatus.ts

**Comment by webxmsj** [comment]
似乎是你的接口没有返回token, 导致解构报错
<img width="645" alt="image" src="https://user-images.githubusercontent.com/40289489/174014166-926bfb18-ce4f-4bfa-9529-423ffb3954e5.png">

**Comment by github-ZH-cn** [comment]
非常感谢的回复, 我已经找到问题, vben admin axios全局拦截的字段跟后端的字段返回不一样, 导致返回undefined




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vbenjs/vue-vben-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月16日(星期四) 下午3:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vbenjs/vue-vben-admin] 是否可以提供一个接口的对接说明文档？ (Issue #1884)





 
似乎是你的接口没有返回token, 导致解构报错

**Comment by github-ZH-cn** [comment]
后端返回的菜单,项目怎么使用啊,文档也没有细说


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vbenjs/vue-vben-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月16日(星期四) 下午3:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vbenjs/vue-vben-admin] 是否可以提供一个接口的对接说明文档？ (Issue #1884)





 
似乎是你的接口没有返回token, 导致解构报错

**Comment by M69W** [comment]
其实不出文档，猜测开发者是想由项目具体出发，不一定按照示例照搬。
再说，也给出 解释了 [#L1](https://github.com/vbenjs/vue-vben-admin/blob/main/src/utils/http/axios/index.ts#L1)

**Comment by weiwenqiang** [comment]
我也卡到了这个问题,既然是axios全局拦截与后端返回字段不一样,这里该在哪里修改为和后端返回一样呢?

**Comment by M69W** [comment]
> 其实不出文档，猜测开发者是想由项目具体出发，不一定按照示例照搬。 再说，也给出 解释了 [#L1](https://github.com/vbenjs/vue-vben-admin/blob/main/src/utils/http/axios/index.ts#L1)

@weiwenqiang 看下 最后的链接文件

**Comment by 9iks** [comment]
> 其实不出文档，猜测开发者是想由项目具体出发，不一定按照示例照搬。 再说，也给出 解释了 [#L1](https://github.com/vbenjs/vue-vben-admin/blob/main/src/utils/http/axios/index.ts#L1)

 //  这里 code，result，message为 后台统一的字段，需要在 types.ts内修改为项目自己的接口返回格式
    const { code, result, message } = data
然后types.ts文件里找不到相关的修改项
