### ISSUE TITLE
竖向菜单缩放的建议

### ISSUE THREAD

**Issue by mx4g** [vbenjs/vue-vben-admin#1886]
### Subject of the feature

Describe your issue here.

缩回去之后再显示，展示出来总感觉不跟手，有割裂感觉！显示的效果做得也不细腻！可以参考一下其它UI的效果！

图片网站：https://vvbin.cn/next/#/dashboard/analysis

![image](https://user-images.githubusercontent.com/7499986/167977042-95e5f999-83fe-468c-b0e8-605d568ede19.png)

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

希望能做到像其它UI那样顺滑和显示的效果，可以再细腻一些

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by wangjue666** [comment]
嗯 可能需要你主动调整下这个组件的样式， 也欢迎你的PR
