### ISSUE TITLE
不能支持 node js 12.22.12 的版本

### ISSUE THREAD

**Issue by like-fly** [vbenjs/vue-vben-admin#1891]
### 描述 Bug

执行命令 `yarn install` 时出现以下错误
```
error vscode-jsonrpc@8.0.1: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "12.22.12"
```

## 系统信息

- 操作系统: win10
- Node 版本: v12.22.12
- 包管理器 (npm/yarn/pnpm) 及其版本: 
- npm 版本: 6.14.16
- yarm 版本: 1.22.18

**Comment by KtfwyCJ** [comment]
升级node版本

**Comment by like-fly** [comment]
有使用node 12版本的方法吗，因为某些原因只能使用12的版本，我看文档上对版本的要求是至少使用12的版本

**Comment by watonyweng** [comment]
@like-fly 貌似和`vscode-jsonrpc`有关系

<img width="1220" alt="1652673194435" src="https://user-images.githubusercontent.com/2574065/168517199-8a6deb0e-5cfb-464e-90f0-8b3404938778.png">
