### ISSUE TITLE
权限管理的树形框架显示的问题

### ISSUE THREAD

**Issue by jackcodewu** [vbenjs/vue-vben-admin#1898]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

- [ ]  #您好，我在您的预览版打开权限编辑页面时，菜单的树形框显示不全。

请清晰地描述此 Bug 的具体表现。

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by DCLangX** [comment]
源于这个提交
https://github.com/vbenjs/vue-vben-admin/commit/e4305daf98e30cfd0e87ffa3ae932c90c95af1f3
把表单项默认宽度百分百去掉了，解决方法一是把百分百加回来，二是跟上面提交的示例里一样给表单项设置span为24

**Comment by jack2023-code** [comment]
好的，非常感谢！

爱吃薯片的内存条 ***@***.***> 于2022年5月19日周四 17:53写道：
