### ISSUE TITLE
Tree组件icon插槽无效

### ISSUE THREAD

**Issue by gdisk** [vbenjs/vue-vben-admin#1902]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

Tree组件中，只有title插槽可以使用，其他插槽如icon，switcherIcon等都无法使用

### 复现 Bug

![Uploading image.png…]()

## 系统信息

- 操作系统: win10
- Node 版本:  16.15
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm

**Comment by wangjue666** [comment]
https://github.com/vbenjs/vue-vben-admin/commit/a0b2a9e949dbf1e149da8be757f78fa6b1cebec0
https://github.com/vbenjs/vue-vben-admin/commit/e4bcf8c899a5dc3e76dc9cb9bc0aed253af2f742

修复这个问题了，如果item传递icon了 同时也有icon插槽，优先展示item的icon

**Comment by pengguan06** [comment]
antv官方文档示例中可以根据是否选择树节点改变icon的样式，BasicTree还是做不到
例如：
<BasicTree title="文件夹列表">
  <template #icon="{ selected }">
      <FolderOpenOutlined v-if="selected" />
      <FolderOutlined v-else />
    </template>
</BasicTree>
