### ISSUE TITLE
表单min校验, 提示信息总是英文

### ISSUE THREAD

**Issue by John-Chan** [vbenjs/vue-vben-admin#1903]
#### rule： max 

<img width="445" alt="Snipaste_2022-05-17_14-38-48" src="https://user-images.githubusercontent.com/2360910/168745408-82df704a-c342-445b-917f-d46377309ae0.png">

#### rule：min

<img width="465" alt="Snipaste_2022-05-17_14-38-37" src="https://user-images.githubusercontent.com/2360910/168745416-4d54ff7c-9289-4dcb-a56e-2288a2f5e349.png">

### 重现

修改`src\views\demo\form\RuleForm.vue`测试，可重现

```shell
diff --git a/src/views/demo/form/RuleForm.vue b/src/views/demo/form/RuleForm.vue
index 8124dae7..3e11c1fe 100644
--- a/src/views/demo/form/RuleForm.vue
+++ b/src/views/demo/form/RuleForm.vue
@@ -29,6 +29,7 @@
         span: 8,
       },
       required: true,
+      rules: [{min: 2}, {max: 4}],
     },
     {
       field: 'field2',
```

**Comment by wangjue666** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/1cf5ca71-d075-4caf-8ae5-7a9af4ad39c8)

`2.10.1`测试正常，可能是当时`async-validator`本地化没做好吧
