### ISSUE TITLE
弹窗中插入的是表单，如果修改了表单内容，可以在关闭前提示表单有变动吗？

### ISSUE THREAD

**Issue by SingleDogNo1** [vbenjs/vue-vben-admin#1904]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by vssir** [comment]
定义一个boolean变量，然后用watch来监控表单数据，当有数据更新，修改boolean变量，在关闭弹窗时就可以判断了

**Comment by wangjue666** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/143fd6cc-0454-4254-ad20-5372924d1313)

**basicModal**组件提供了 [closeFunc ](https://doc.vvbin.cn/components/modal.html#props) 钩子函数
