### ISSUE TITLE
官网的演示与这个项目下载下来运行不一样？

### ISSUE THREAD

**Issue by fendo8888** [vbenjs/vue-vben-admin#1905]
官网的演示与这个项目下载下来运行不一样？是哪里设置错了么？

![image](https://user-images.githubusercontent.com/22114481/168984355-6d427155-8470-4b8e-8cf5-4151bf2e6dd3.png)
就这几个页面

**Comment by doraemonxxx** [comment]
When checked out the repo and run it, the demo and preview of the project are the same.

**Comment by fendo8888** [comment]
> 当签出 repo 并运行它时，项目的演示和预览是相同的。

我就是直接下载的main分支？你说的是？

**Comment by Jenky1031** [comment]
> 
是不是点了权限管理-基于后台权限-切换到后台权限？

**Comment by Kento97** [comment]
你用的admin权限吧，改改权限就行了
