### ISSUE TITLE
基础表单页面有 warn提示

### ISSUE THREAD

**Issue by dividez** [vbenjs/vue-vben-admin#1910]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

![image](https://user-images.githubusercontent.com/19829513/169429657-036b3360-c14d-468c-9f4b-3a9b4e1e9165.png)

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统: MacOS
- Node 版本: v16.6.1 
- pnpm : 7.0.0

**Comment by TengChongChong** [comment]
建议参考 [#1974](https://github.com/vbenjs/vue-vben-admin/issues/1974)
