### ISSUE TITLE
基础表单页面 下拉选择，必选项目，选中后 表单校验提示未通过

### ISSUE THREAD

**Issue by dividez** [vbenjs/vue-vben-admin#1911]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

在这个页面 https://vvbin.cn/next/#/comp/form/basic ；
懒加载远程下拉 框，选中后， 依然红色提示 请选择

### 复现 Bug

https://user-images.githubusercontent.com/19829513/169444072-4a627844-1631-4ce0-b4fd-3d508c5d4d35.mp4

## 系统信息

- 操作系统: MacOs
- 谷歌浏览器

**Comment by zhangjianmei323** [comment]
把原本的required: true,删除，需要自己加一个rules规则：
     componentProps: {
      api: getAllRoleList,
      labelField: 'roleName',
      valueField: 'roleValue',
    },
    rules: [
      {
        required: true,
        trigger: 'blur',
      },
    ],

**Comment by kuizuo** [comment]
还可以添加    
itemProps: { validateTrigger: 'blur' },

**Comment by bboyHan** [comment]
添加了不管用 ，两种方法都试了

**Comment by wangjue666** [comment]
https://github.com/vbenjs/vue-vben-admin/pull/3071 该PR已修复

**Comment by guilunmei** [comment]
你是加错地方了吧
itemProps加到外层 和field一级 加到componentProps中无效
