### ISSUE TITLE
多级表头的情况下，record里面没有onEdit方法

### ISSUE THREAD

**Issue by xiaojieajie** [vbenjs/vue-vben-admin#1913]
<img width="446" alt="image" src="https://user-images.githubusercontent.com/39750199/169482219-59c2f869-8811-4b06-a055-c306b667cb4d.png">
如果存在children，就没有onEdit方法
<img width="392" alt="image" src="https://user-images.githubusercontent.com/39750199/169482289-2332d0e1-0c00-4eb7-98fa-e88a4e7f3fcf.png">

没有children就有
<img width="342" alt="image" src="https://user-images.githubusercontent.com/39750199/169482385-4da7ed85-ba68-4874-97eb-63bb7e7fcd6b.png">
<img width="405" alt="image" src="https://user-images.githubusercontent.com/39750199/169482409-63fd23c9-848f-4c8f-9c98-10892b4a08bc.png">

**Comment by xiaojieajie** [comment]
求解答。。

**Comment by zhuxianbin** [comment]
包括 format 在children里 也是失效的

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
