### ISSUE TITLE
有没有qq群呀。想请教问题

### ISSUE THREAD

**Issue by hddlly** [vbenjs/vue-vben-admin#1918]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by wzxinchen** [comment]
我也想问问题，但是作者不提供，所以我提供一个临时的QQ群，刚建的。789415855

**Comment by M69W** [comment]
569291866
Vben Admin

**Comment by M69W** [comment]
> 569291866 Vben Admin

貌似搜索不到，不知为何
