### ISSUE TITLE
项目静置一晚上后（具体多久未知）无法使用，代码报错，需要强制刷新才可以继续使用

### ISSUE THREAD

**Issue by su-yongjian** [vbenjs/vue-vben-admin#1919]
![1653360675(1)](https://user-images.githubusercontent.com/34278832/169940762-947cbfe8-3e59-4453-a5d2-b5bda3865ee7.jpg)

**Comment by su-yongjian** [comment]
这个是因为我推过新代码，重新部署后，静态资源的哈希值就会变化，你本地的html有缓存，静态资源地址指向是旧的资源地址，由于部署了新版，所以旧资源不存在。
这个在开发的项目都有这个问题，需要配置不缓存html
简单的方式就是重新刷新下

**Comment by chenguang1994** [comment]
一样的问题

**Comment by hhw28** [comment]
同问

**Comment by mynetfan** [comment]
demo在有新的commit后会自动重新构建，一些文件名中的hash会发生改变。如果在你打开页面之后的一段时间，demo自动构建了新的版本，你已打开的页面就会出现这种问题。

**Comment by astonishqft** [comment]
> 

问题是为啥需要强制刷新才行呢？有时候只是普通刷新还是不能解决问题，感觉对用户很不友好
