### ISSUE TITLE
setup语法糖中使用useModal提示警告的bug

### ISSUE THREAD

**Issue by Ya2gLu** [vbenjs/vue-vben-admin#1922]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
1.useModal弹窗组件在setup语法糖的写法中提示警告：

[Vue warn]: Component emitted event "register" but it is neither declared in the emits option nor as an "onRegister" prop. 

2.在setup语法糖中父组件在调用useModal实例中的openModal方法时，打开的Modal样式错位。

![image](https://user-images.githubusercontent.com/48912522/170257964-afb58b85-5a59-4409-a666-e8637bbf9fb7.png)

### 复现 Bug
  1. 在父组件中使用setup语法糖调用useModal:
```vue
<template>
  <div>
    <a-button type="primary" @click="handleAdd">创建项目</a-button>
    <ProjectAddModal @register="register1" />
  </div>
</template>

<script lang="ts" setup>
  import { useModal } from "/@/components/Modal";
  import ProjectAddModal from "./modules/ProjectAddModal.vue";
  const [register1, { openModal: openAddModal }] = useModal();
  const handleAdd = (record) => {
    return openAddModal(true, { id: "1" });
  };
</script>
```
  2. 子组件：
```vue
<template>
  <BasicModal v-bind="$attrs" @register="register" @ok="handleSubmit">
    子组件
  </BasicModal>
</template>
<script lang="ts">
import { defineComponent, ref } from "vue";
import { BasicModal, useModalInner } from "/@/components/Modal";

export default defineComponent({
  name: "ProjectAddModal",
  components: {BasicForm, BasicModal},
  props: {},
  setup(props, ctx) {
    const [register, { setModalProps, closeModal }] = useModalInner(async (record) => {
      await resetFields();
      setModalProps({
        title: "创建项目",
        okText: "保存",
        width: 900,
        maskClosable: false,
        keyboard: false,
      });
    });
    return {
      register
    }
  }
})
</script>
```
打开Modal后提示警告：

![image](https://user-images.githubusercontent.com/48912522/170263842-d734368a-0c1e-4c56-9f85-b0e1c2698975.png)

另外，如果在父组件上的`click`事件直接调用`openAddModal `方法后，弹出的modal框也会发生样式错位:

>补充：这种问题在setup语法糖中出现，官方文档的正常语法是没有问题的。

![image](https://user-images.githubusercontent.com/48912522/170265051-ca7bb0b1-b78a-40da-bbdb-d72a0f10f9c5.png)

  

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统: window 10
- Node 版本: v14.16.1
- 包管理器 (npm/yarn/pnpm) 及其版本: npm: v6.14.2

**Comment by xiaojieajie** [comment]
你在emit配置下，register呀。。

**Comment by xiaojieajie** [comment]
子组件
emit: ['register'],

**Comment by jiachenyu1** [comment]
> 子组件 emit: ['register'],

请问为什么要在子组件加这个，加了确实好了，但是没理解原因。
本质上不就是在 register 中抛出了组件实例，并且 expose 出了一些方法，相当于就是封装了一下通过 ref 调用组件内方法的一种实现，不明白为什么要在子组件加这个

**Comment by xiaojieajie** [comment]
> > 子组件 emit: ['register'],
> 
> 请问为什么要在子组件加这个，加了确实好了，但是没理解原因。 本质上不就是在 register 中抛出了组件实例，并且 expose 出了一些方法，相当于就是封装了一下通过 ref 调用组件内方法的一种实现，不明白为什么要在子组件加这个

触发一次 or 双向绑定来着。。

太久没用vue了，有点忘记了
