### ISSUE TITLE
select，多选框清除值清除了，但是值还在

### ISSUE THREAD

**Issue by hasaisd** [vbenjs/vue-vben-admin#1930]
抱歉，我遇到了一个错误。感谢您抽出宝贵的时间进行举报！

{
    field: 'townCode',
    component: 'Select',
    label: '乡镇',
    valueField: 'townCode',
    componentProps: ({ formModel, formActionType }) => {
      return {
        options: townOptions,
        placeholder: '乡镇联动查询',
        onChange: (e: any) => {
          let citiesOptions = villageOptionsData[e];
          if (e === undefined) {
            citiesOptions = [];
          }
          //清空旧数据
          formModel.villageCode = undefined;
          const { updateSchema } = formActionType;
          //重新赋值
          updateSchema({
            field: 'villageCode',
            componentProps: {
              options: citiesOptions,
            },
          });
        },
      };
    },
    colProps: { span: 6 },
  },
  {
    field: 'villageCode',
    component: 'Select',
    label: '行政村',
    valueField: 'villageCode',
    componentProps: {
      options: villageOptions, // defalut []
      placeholder: '乡镇联动查询',
      onChange: (e) => {
      },
    },
    colProps: { span: 6 },
  },
、、、、、、、、、、、、、、、、、、、、、、、、、、、、、
接口请求获取数据
villagePage().then((res) => {
      let towns = [];
      for (let i = 0; i < res.length; i++) {
        if (towns.indexOf(res[i].townCode) != -1) {
        } else {
          townOptions.push({
            label: res[i].townName,
            value: res[i].townCode,
            key: res[i].townCode,
          });
          towns.push(res[i].townCode);
          villageOptionsData[res[i].townCode] = [];
          if (userStore.getDeptCode.length == 9) {
            if (res[i].townCode == userStore.getDeptCode) {
              setTimeout(() => {
                townOrVillage.townCode = userStore.getDeptCode;
                townOrVillage.townName = res[i].townName;
              }, 1000);
            }
          }
        }
        if (userStore.getDeptCode.length == 9) {
          if (res[i].townCode == userStore.getDeptCode) {
            villageOptions.push({
              label: res[i].villageName,
              value: res[i].villageCode,
              key: res[i].villageCode,
            });
          }
        } else if (userStore.getDeptCode.length == 12) {
          if (res[i].villageCode == userStore.getDeptCode) {
            setTimeout(() => {
              townOrVillage.villageName = res[i].villageName;
            }, 1000);
          }
        }

        villageOptionsData[res[i].townCode].push({
          label: res[i].villageName,
          value: res[i].villageCode,
          key: res[i].villageCode,
        });
      }
    });

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
