### ISSUE TITLE
table勾选跨页失效

### ISSUE THREAD

**Issue by weikun321688** [vbenjs/vue-vben-admin#1936]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

跨页勾选不能多条选中

### 复现 Bug

1.第一页勾选一条数据
2.切换到其它页，勾选一条数据
3.切换回第一页，发现第一页勾选信息丢失

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by shuperry** [comment]
是的，我也发现有这个问题

**Comment by odenic** [comment]
设置rowKey为数据源里面的某项唯一值就能解决

**Comment by weikun321688** [comment]
> 



> 设置rowKey为数据源里面的某项唯一值就能解决

已经设置了，不好使

**Comment by 551685830** [comment]
@odenic 
应该不是设置的事，因为代码不做修改，开发和发布环境的效果不一致。应该还是隐式BUG引起的才对。

**Comment by wangmin0314** [comment]
https://github.com/vbenjs/vue-vben-admin/issues/1714

**Comment by weikun321688** [comment]
> #1714

我试了下 还是不好用...

**Comment by shuperry** [comment]
在 src\components\Table\src\hooks\useRowSelection.ts 的 useRowSelection 函数的 return 对象中添加 preserveSelectedRowKeys: true 即可解决此问题，亲测好使
