### ISSUE TITLE
resizable: true with @resize-column="resizeColumn" at BasicTable.vue

### ISSUE THREAD

**Issue by doraemonxxx** [vbenjs/vue-vben-admin#1938]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug
When setting up the resizeable column in the table and when clicking the resizable element, the column will resize its width.
And it is kind of a delay in changing the width when dragging.

Expected result:
should not resize the width when clicking the column resize element.

### Reproduction
**code**
`const columns = [{
    title: 'ID',
    dataIndex: 'id',
    width: 50,
    resizable: true,
 }]`
 
in **BasicTable.vue**

`<Table @resize-column="resizeColumn">`
 ` const resizeColumn = (w, col) => {
        console.log('resizeColumn w', w);
        console.log('resizeColumn col', col);
        setCacheColumnsByField(col.dataIndex, { width: w });
 };`
 
 `return {resizeColumn}`
  
![clean](https://user-images.githubusercontent.com/88119911/171694052-57c51d72-0c19-4bf9-8dbc-4636daec818d.gif)

## System Info
- Operating System: Windows 10
- Node version:  v16.15.0
- Package manager (npm/yarn/pnpm) and version: yarn v1.22.18

Related issues:
#1357 and #1719

**Comment by Baloneo** [comment]
+1
