### ISSUE TITLE
ApiSelect 验证行为异常

### ISSUE THREAD

**Issue by evanzeng** [vbenjs/vue-vben-admin#1939]
在官方在线的基础表单演示中，清除懒加载远程下拉框，没有正确地显示必选错误信息，截图如下：

<img width="681" alt="image" src="https://user-images.githubusercontent.com/872641/171990582-279cfce5-c3bd-4a5d-9cfc-58daccaf4663.png">

这时候再任意选择一个选项，出现必选错误信息，截图如下：

<img width="681" alt="image" src="https://user-images.githubusercontent.com/872641/171990798-29bc0b48-6a6a-4e6f-a185-eb96cea8bfe5.png">

**Comment by jenifly** [comment]
确实...希望早点修复噢

**Comment by iconFehu** [comment]
大佬快来修复这个问题

**Comment by iconFehu** [comment]
#1616

**Comment by TengChongChong** [comment]
可以设置字段校验的时机为`blur`修复
```js
itemProps: { validateTrigger: 'blur' },
```
