### ISSUE TITLE
项目克隆到本地，安装依赖后运行需要系统密码问题

### ISSUE THREAD

**Issue by whidy** [vbenjs/vue-vben-admin#1942]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

macOS Monterey下正常拉取最新的代码（cfbd52bbe7e49dae7a6fd4a4a67c2823d86fd258），按照说明文档安装好依赖（pnpm install），运行程序时提示需要输入sudo密码。

![image](https://user-images.githubusercontent.com/2074757/172100242-32eef8dd-04f0-4826-9140-a23f2736d574.png)

### 复现 Bug

```bash
git clone git@github.com:vbenjs/vue-vben-admin.git
cd vue-vben-admin
pnpm install
pnpm serve
```

然后出现如图提示，需要输入管理员密码。我不确定是否是一个bug。还是系统原因，我记得很早之前也在其他电脑上clone过该项目是没有要密码的，而且前端项目除非是文件目录的权限维护上的问题一般也不需要sudo啊~

## 系统信息

- 操作系统: macOS Monterey 12.3.1 (21E258)
- Node 版本: v16.14.2
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm v7.1.0

---

尝试升级到了node v16.15.1和pnpm v7.1.8，也尝试更换目录，依然无法解决该问题。

千万不要告诉我这个项目运行真的是需要管理员密码的🥺

**Comment by renhhh** [comment]
![image](https://user-images.githubusercontent.com/49031260/172154249-ab25aa96-2108-4cec-96ce-3e6dbcddcb7b.png)
可以看下这个

**Comment by whidy** [comment]
> ![image](https://user-images.githubusercontent.com/49031260/172154249-ab25aa96-2108-4cec-96ce-3e6dbcddcb7b.png) 可以看下这个

我查阅了一下<https://github.com/vbenjs/vue-vben-admin/commit/4e4ce944bcab4aaab677112b7cba9d86501e416c>这个分支。

确实禁用了dev的https相关代码就可以了，谢谢~

顺便帮助其他朋友，说下本地关闭https的方式吧。因为代码变更里面跟当前最新代码还是有点区别。

* 修改文件`vite.config.ts`，将`https: true,`注释掉
* 修改文件`build/vite/plugin/index.ts`，将`import VitePluginCertificate from 'vite-plugin-mkcert';`和
    ```
    VitePluginCertificate({
      source: 'coding',
    }),
    ```
    注释掉。

再启动就好了。

**Comment by lionHua** [comment]
赞

**Comment by ahgaoyong** [comment]
这是vite-plugin-mkcert 遇上 vite.config.ts文件里面的server.https: true时, 没有mkcert https证书所导致的问题,

一些人建议更改vite.config.ts文件里面的server.https值为false, 其实, 更优雅的做法是:

直接在命令行启动参数增加 --https false 即可, 例如:

yarn dev --https false
pnpm dev --https false
cnpm dev --https false
npm dev --https false
或者你修改package.json里面的scripts dev脚本也行

{ 
  "scripts": {
    //其他配置...
    "dev": "vite --https false",
    // 其他配置...
  }
}
