### ISSUE TITLE
页签切换后再返回变成空白页

### ISSUE THREAD

**Issue by zhangying6** [vbenjs/vue-vben-admin#1953]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:
页签切换后再返回变成空白页，只能强制刷新

**Comment by fan-tian-bao** [comment]
使用动画的话每个页面应该只能有一个根节点,应该是这个问题

**Comment by zhangWeiZhuang** [comment]
你好，请问该问题有得到解决吗

**Comment by chenqixian** [comment]
页面只能有一个根节点。例如
`<template>
  <PageWrapper/>
</template>`
不能是
`<template>
  <PageWrapper/>
  <button/>
</template>`
