### ISSUE TITLE
在Modal中增加Table组件

### ISSUE THREAD

**Issue by hyphenliu** [vbenjs/vue-vben-admin#1956]
### Subject of the feature

在使用弹窗模板Modal填写Form表单时会用到 table组件进行数据增删操作。

### Problem
自己在Modal的componentMap.ts中增加antd的table，但是无法实现对该table数据行的删除和编辑操作。使用actionColumn，也没生效。直接使用antd的table action操作也未能实现。

### Expected behaviour

希望弹窗模板Modal填写Form表单时会有 table组件，并可以实现数据行的增删操作。

### Alternatives

没有找到合适的实现方法。

**Comment by mynetfan** [comment]
#/page-demo/form/high
高级表单页有动态表单例子
