### ISSUE TITLE
项目启动报错 - Error: read ECONNRESET

### ISSUE THREAD

**Issue by Zuojiangtao** [vbenjs/vue-vben-admin#1957]
- [X] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [X] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [X] 已在 Issues 中搜索了相关的关键词
- [X] 不是 ant design vue 组件库的 Bug

### 启动项目报错

 ```
ERROR  error when starting dev server:                                                           16:48:41  
    Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)

ELIFECYCLE  Command failed with exit code 1.
```

### 复现 Bug

1. clone代码，`pnpm install`;
2. `pnpm serve`;
3. 终端报错;

## 系统信息

- 操作系统: windows10
- Node 版本: 16.12.0/16.13.0/16.14.0
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm(7.1.9)

**Comment by dearmark** [comment]
修改vite.config.ts的 server 的https为false，关闭HTTPS
``` javascript
 server: {
      https: false,
```

**Comment by Zuojiangtao** [comment]
ok,已解决.

**Comment by zqx-git** [comment]
为什么不能用https呢

**Comment by yudongjun** [comment]
> 

very nice!
