### ISSUE TITLE
顶部菜单混合模式下折叠菜单后变成多选中状态了

### ISSUE THREAD

**Issue by cn-src** [vbenjs/vue-vben-admin#1960]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

顶部菜单混合模式下，折叠菜单后变成多选中状态了。
点击后，其它菜单应该取消选中状态。

<img width="341" alt="image" src="https://user-images.githubusercontent.com/8263180/173193369-b1e4e7e2-ac65-43c7-8534-ec59b76247ae.png">

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by iconFehu** [comment]
设置了相同的path？

**Comment by mynetfan** [comment]
Demo中未能复现
