### ISSUE TITLE
请问使用useform如何设置为每行只显示一个组件？

### ISSUE THREAD

**Issue by ufoozhenghao** [vbenjs/vue-vben-admin#1961]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [√] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [√] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [√] 已在 Issues 中搜索了相关的关键词
- [√] 不是 ant design vue 组件库的 Bug

### 描述 Bug

使用useform如何设置为每行只显示一个组件？类似于ant的 `layout: 'horizontal',` ,目前默认是每行三个组件

## 系统信息

- 操作系统: win11
- Node 版本:  v16.13.1
- 包管理器 (npm/yarn/pnpm) 及其版本: yarn 1.22.15

**Comment by LSvKing** [comment]
@ufoozhenghao 怎么关了啊，找到答案了吗？
