### ISSUE TITLE
超时后卡在登录页面，点刷新没有反应。新开页面可以打开。

### ISSUE THREAD

**Issue by CyrusZhou-CN** [vbenjs/vue-vben-admin#1963]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
![image](https://user-images.githubusercontent.com/4635861/173619923-7c717d52-4273-4540-9b4c-631ccd6336cd.png)

![image](https://user-images.githubusercontent.com/4635861/173572211-c57bef96-b8b4-4821-a302-fc5a40784b35.png)

请清晰地描述此 Bug 的具体表现。
超时后卡在登录页面，点刷新没有反应。新开页面可以打开。
### 复现 Bug
用户登录后，超时退出，重新登录时发生。
加载过程中 F12 无法调出DevTools

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by baiyifengyun** [comment]
我也突然出现这个问题，之前一直运行的挺好的，代码也没有动
