### ISSUE TITLE
删除 pnpm-lock.yaml，重新安装项目依赖，打包部署后会有部分组件空白？按需引入的问题？

### ISSUE THREAD

**Issue by youthug** [vbenjs/vue-vben-admin#1965]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [*] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [*] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [*] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

项目构建部署之后有些组件显示空白

![image](https://user-images.githubusercontent.com/24794392/173854051-f1e584bd-440c-4078-b98a-deb8c0d8402a.png)

### Reproduction

```shell
rm -rf node_modules pnpm-lock.yaml
pnpm i
pnpm preview
```

改成下面这样后能正常显示：

src/views/dashboard/workbench/components/QuickNav.vue
```diff
 <template>
   <Card title="快捷导航" v-bind="$attrs">
     <CardGrid v-for="item in navItems" :key="item">
       <span class="flex flex-col items-center">
         <Icon :icon="item.icon" :color="item.color" size="20" />
         <span class="text-md mt-2">{{ item.title }}</span>
       </span>
     </CardGrid>
   </Card>
 </template>
 <script lang="ts" setup>
-  import { Card } from 'ant-design-vue';
+  import { Card, CardGrid } from 'ant-design-vue';
   import { navItems } from './data';
   import { Icon } from '/@/components/Icon';
-
-  const CardGrid = Card.Grid;
 </script>
```

## System Info

- Operating System: macOS 12.3.1
- Node version: v14.16.1
- Package manager (npm/yarn/pnpm) and version: pnpm v7.2.1

**Comment by webxmsj** [comment]
组件引入补全，未做组件自动导入导致的

**Comment by youthug** [comment]
> 组件引入不全，未做组件自动导入导致的

那这个应该怎么配置？文档好像没写，使用 [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) 自动引入的话会有更多地方有问题
