### ISSUE TITLE
RadioButtonGroup 按钮出错，只显示默认值

### ISSUE THREAD

**Issue by CyrusZhou-CN** [vbenjs/vue-vben-admin#1966]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

请清晰地描述此 Bug 的具体表现。
![image](https://user-images.githubusercontent.com/4635861/173860276-2c35714a-39c4-45e7-96e9-4073cd156124.png)
![image](https://user-images.githubusercontent.com/4635861/173860306-dd77acfe-cc1c-4555-a3ec-6fe920173412.png)
RadioButtonGroup 按钮出错，只显示默认值
### 复现 Bug
https://vvbin.cn/next/#/system/menu
请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by dantes1844** [comment]
请问你解决了这个问题吗？ @CyrusZhou-CN

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
