### ISSUE TITLE
登录接口返回200,打印返回结果是undefined

### ISSUE THREAD

**Issue by github-ZH-cn** [vbenjs/vue-vben-admin#1967]
![image](https://user-images.githubusercontent.com/67533362/173984043-f13e5a64-2473-48da-a2e7-1b2eab6d3afe.png)
![image](https://user-images.githubusercontent.com/67533362/173984076-9647056c-afb6-46e4-982f-5c44ce6da4b3.png)

接口返回200, 打印返回值是undefined, 在全局响应拦截哪里也能打印返回结果, 在登陆接口哪里返回undefined

**Comment by M69W** [comment]
参考一下 vbenjs/vue-vben-admin/issues/1884
