### ISSUE TITLE
后端菜单请求过来, 前端这么创建对应的组件和路由配置啊

### ISSUE THREAD

**Issue by github-ZH-cn** [vbenjs/vue-vben-admin#1969]
后端菜单请求过来, 前端这么创建对应的组件和路由配置啊, 有没有人遇到这个

**Comment by kuizuo** [comment]
在官方文档中有说明 [后台动态获取](https://vvbin.cn/doc-next/guide/auth.html#%E5%90%8E%E5%8F%B0%E5%8A%A8%E6%80%81%E8%8E%B7%E5%8F%96)
后端的mockjs菜单数据为 https://github.com/vbenjs/vue-vben-admin/blob/main/mock/sys/menu.ts

**Comment by kuizuo** [comment]
我这里有一个基于nestjs的后端实例 采用的就是后端菜单获取 https://admin.kuizuo.cn

**Comment by github-ZH-cn** [comment]
谢谢,星期天回去看一下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vbenjs/vue-vben-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月17日(星期五) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vbenjs/vue-vben-admin] 后端菜单请求过来, 前端这么创建对应的组件和路由配置啊 (Issue #1969)





 
我这里有一个基于nestjs的后端实例 采用的就是后端菜单获取 https://admin.kuizuo.cn

**Comment by github-ZH-cn** [comment]
源码能发一下吗,没有源码我看不出来怎么写的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vbenjs/vue-vben-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月17日(星期五) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vbenjs/vue-vben-admin] 后端菜单请求过来, 前端这么创建对应的组件和路由配置啊 (Issue #1969)





 
我这里有一个基于nestjs的后端实例 采用的就是后端菜单获取 https://admin.kuizuo.cn

**Comment by kuizuo** [comment]
> 
https://github.com/kuizuo/kz-vue-admin

**Comment by github-ZH-cn** [comment]
谢谢啊


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vbenjs/vue-vben-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月17日(星期五) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vbenjs/vue-vben-admin] 后端菜单请求过来, 前端这么创建对应的组件和路由配置啊 (Issue #1969)





   
https://github.com/kuizuo/kz-vue-admin
