### ISSUE TITLE
官网项目v2.8.0，ApiSelect在无默认值的情况下，初次选择筛选项，表单校验直接报错

### ISSUE THREAD

**Issue by IceZero-w** [vbenjs/vue-vben-admin#1977]
### 描述 Bug

ApiSelect在无默认值的情况下，初次选择筛选项，表单校验直接报错

### 复现 Bug
官网项目v2.8.0 bug：vue-vben-admin/src/views/demo/system/account/account.data.ts

<img width="269" alt="image" src="https://user-images.githubusercontent.com/29394109/174249316-ba039b9f-33c1-4dfa-8f7c-3e045fa9d12b.png">
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/29394109/174249481-2c9090bc-ec60-4a4d-b2ca-f5eafe44acbd.png">
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/29394109/174249729-6d6c4174-c861-4fcc-91f1-20946f7bb31f.png">

## 系统信息

- 操作系统:macOS
- Node 版本: v16.15.0
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm

debugger了1天，没有发现问题的原因，请求支援（我是在antdV2升级antdV3才复现的问题，结果发现官网项目也有同样的bug）

**Comment by IceZero-w** [comment]
@et2012 help me,my bro

**Comment by fanzihui** [comment]
#1939 itemProps: { validateTrigger: 'blur' },

**Comment by IceZero-w** [comment]
> #1939 可以设置字段校验的时机为blur修复
> 
> itemProps: { validateTrigger: 'blur' }, ![image](https://user-images.githubusercontent.com/8360311/174920831-e20ec1ba-75db-4cb0-ac26-d34831cf0d82.png)

thnak you very much!!
