### ISSUE TITLE
弹出框中的表格在取消弹出框全屏后没有恢复原始宽度 

### ISSUE THREAD

**Issue by shuperry** [vbenjs/vue-vben-admin#1979]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

1、在弹出框中引入表格组件
2、全屏弹出框 -> 表格变宽 -> 取消全屏 -> 表格维持很宽，无法完整展示内容

![IMG20220617162849](https://user-images.githubusercontent.com/12183336/174259246-f7e60f21-79b4-494c-9135-ec7e2d7aaf11.png)

![IMG20220617162907](https://user-images.githubusercontent.com/12183336/174259296-7d401898-58d4-4331-8dad-3127b3d1b8a4.png)

![IMG20220617162923](https://user-images.githubusercontent.com/12183336/174259347-aeb2bdae-02c2-4d80-9287-0258c1d86edb.png)

## 系统信息

- 操作系统:
- Node 版本: v14.19.3
- 包管理器 (npm/yarn/pnpm) 及其版本: yarn 1.22

**Comment by anncwb** [comment]
Hello @shuperry. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.
