### ISSUE TITLE
文件上传报错，本地开发时功能可以使用，更新到服务器时报错，

### ISSUE THREAD

**Issue by RetireWorker** [vbenjs/vue-vben-admin#1985]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

文件上传报错，本地开发时功能可以使用，更新到服务器时报错

### 复现 Bug

以下为服务器部署时报错截图，查看错误信息和官方演示环境一样的错误
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/4509428/174521840-c40c844c-f651-46f9-9701-0b162e5ed300.png">

## 系统信息

- 操作系统: centos7.9    nginx 1.21.6
- Node 版本: 14.18.2
- 包管理器 (npm/yarn/pnpm) 及其版本: 6.14.15

**Comment by xavieryang2011** [comment]
同样的问题，求解答

**Comment by xavieryang2011** [comment]
![image](https://user-images.githubusercontent.com/16483542/175458024-572cc5be-5a9c-4b92-8ce4-b1a8ba857975.png)
把启用mock设置成false就可以了

**Comment by RetireWorker** [comment]
> ![image](https://user-images.githubusercontent.com/16483542/175458024-572cc5be-5a9c-4b92-8ce4-b1a8ba857975.png)
> 把启用mock设置成false就可以了

试了可以！ @xavieryang2011

**Comment by DB-lost** [comment]
确实是这样，问题已解决!!!!

**Comment by wphubs** [comment]
解决了
