### ISSUE TITLE
Support Arabic

### ISSUE THREAD

**Issue by Mosaab-Emam** [vbenjs/vue-vben-admin#1986]
### Subject of the feature

Support Arabic language beside Chinese and English.

### Problem

Not enough i18n for the admin panel.

### Expected behaviour

Should support choosing arabic as a language for the admin panel. With RTL directions.

### Alternatives

Me creating a repo based on this that is Arabic by default (or Arabic only).

**Comment by M69W** [comment]
[document-i18n](https://vvbin.cn/doc-next/dep/i18n.html) maybe help you better.
