### ISSUE TITLE
切换菜单无渲染

### ISSUE THREAD

**Issue by zhangWeiZhuang** [vbenjs/vue-vben-admin#1993]
=====菜单示例======
一级菜单1
     子菜单1-1
     子菜单1-2
     子菜单1-3
=====菜单示例END======
我在路由的module下注册了路由信息，菜单上能正确出现注册的视图，但是浏览器初次刷新时组件能刷出来，同一级子菜单切换了多次以后视图渲染不出来了。如我刷新浏览器，目前是子菜单1-1的视图，当我点击1-2能显示，但是点击1-3就一片空白没有渲染。同理，刷新浏览器是1-3，点击1-2能显示，再点1-1就不能渲染出来了。控制台无报错（Edge浏览器）
![image](https://user-images.githubusercontent.com/44084004/175266269-45893d73-66d6-4814-ac00-908aca93b205.png)

https://user-images.githubusercontent.com/44084004/175266335-45d61737-9918-4de5-b006-0703f1464e09.mp4

**Comment by zhangWeiZhuang** [comment]
![image](https://user-images.githubusercontent.com/44084004/175266713-2018c67f-e04a-4002-b93b-6116601e2ac0.png)

**Comment by chen870370470** [comment]
![image](https://user-images.githubusercontent.com/59992255/175846572-1e7cd75b-d796-4dd7-84fc-ec254f13bd97.png)
