### ISSUE TITLE
有一个需求是收藏网址功能,需要外链,但是我不知道用户收藏那些网站

### ISSUE THREAD

**Issue by github-ZH-cn** [vbenjs/vue-vben-admin#2006]
![image](https://user-images.githubusercontent.com/67533362/175762335-f5d47a09-366a-4f76-91b0-fa6a0ee1442f.png)
我使用window,open 没有用, 这个怎么解决

**Comment by mynetfan** [comment]
合法链接是 http:// 或者 https:// 。你的链接写错了
