### ISSUE TITLE
表格右侧固定列，当没有竖向滚动条的时候，会导致右侧列未对齐（edge浏览器，官方demo也有这个问题。火狐正常）

### ISSUE THREAD

**Issue by skywolf627** [vbenjs/vue-vben-admin#2008]
### 描述 Bug

表格右侧固定列，当没有竖向滚动条的时候，会导致右侧列未对齐（edge浏览器，官方demo也有这个问题。火狐正常）

### 复现 Bug

官方demo  edge浏览器，右侧固定列会显示错位
https://vvbin.cn/next/#/comp/table/fixedColumn
![image](https://user-images.githubusercontent.com/9822661/175816853-9f96d673-eb9f-4455-8c22-6cee21b98001.png)

## 系统信息

- 浏览器: edge
- 操作系统:win11

**Comment by wangjue666** [comment]
https://github.com/vbenjs/vue-vben-admin/issues/3085 这个issue提供了解决方案
