### ISSUE TITLE
能不能去掉国际化，国际化99%的公司都用不上

### ISSUE THREAD

**Issue by ezewu** [vbenjs/vue-vben-admin#2010]
能不能去掉国际化，国际化99%的公司都用不上

**Comment by likui628** [comment]
要是没有国际化我应该不会选vben-admin

**Comment by lemonc2009** [comment]
> 

理由是什么呢？

**Comment by M69W** [comment]
自己去掉即可。

1、项目去掉，肯定又有人说，我需要国际化，请加上？！
2、这是开源项目，理论上国际化可能会更好。

**Comment by M69W** [comment]
说一个例子吧
前几天的 issue https://github.com/vbenjs/vue-vben-admin/issues/1986

**Comment by fanhoucheng** [comment]
笑死人了
