### ISSUE TITLE
table action对齐问题

### ISSUE THREAD

**Issue by kuaileai2022** [vbenjs/vue-vben-admin#2012]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug
<img width="1211" alt="1656326074912" src="https://user-images.githubusercontent.com/101444413/175922529-672d26c0-e3c2-4a6d-ae83-9ad61597e917.png">

### 描述 Bug

BasicTable在使用过程中，右侧会多出来一个scrollbar的位置，官方demo也是这样，麻烦看看怎么解决。

### 复现 Bug

使用BasicTable的action，若数据量少，竖向没有滚动条就会出现该问题。

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by wangjue666** [comment]
https://github.com/vbenjs/vue-vben-admin/issues/3085 这个issue提供了解决方案
