### ISSUE TITLE
Table表格位置错乱BUG，表头的列与数据行的列对不齐错乱问题！！

### ISSUE THREAD

**Issue by zusrsoft** [vbenjs/vue-vben-admin#2016]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

Table表格位置错乱BUG，表头的列与数据行的列对不齐错乱问题！！

### 复现 Bug

![微信图片_20220628120535](https://user-images.githubusercontent.com/26666544/176090370-6fa11d35-6c2c-4c3d-932e-ad5093c85ce9.png)

## 系统信息

- 操作系统: win10
- Node 版本:14.19.3
- 包管理器 (npm/yarn/pnpm) 及其版本: npm 6.14.17
- Chrome\ Edge浏览器  都测试过，还是不行

**Comment by momohmj** [comment]
columns 对象中的fixed设置为 undefined, 如果使用了 actionColumn ,fixed也设置为 undefined

**Comment by iconFehu** [comment]
#2058 解决表头的列与数据行没对齐

**Comment by zusrsoft** [comment]
刚才验证，还是没有解决，你验证过了吗？

**Comment by iconFehu** [comment]
https://github.com/vbenjs/vue-vben-admin/pull/1978

**Comment by iconFehu** [comment]
revert commit

**Comment by zusrsoft** [comment]
到目前这个对齐的bug还是没有解决。但发现一些新的情况

..如下图，110%    150% 页面放大比例，“能对齐”。其他比例表头与数据 都“对不齐”。
![1](https://user-images.githubusercontent.com/26666544/179136289-4bdc6976-a8d4-4d52-95c1-ff4d013cbfd8.png)
![2](https://user-images.githubusercontent.com/26666544/179136349-518191c6-013d-4309-9cb5-24fc494e928a.png)
![3](https://user-images.githubusercontent.com/26666544/179136351-44e93acd-98d5-4a48-916f-3dde6c403b0b.png)
![4](https://user-images.githubusercontent.com/26666544/179136355-58e9fb32-afa9-4efa-83cb-82cac1f3aad0.png)

**Comment by q7486828035** [comment]
https://github.com/vbenjs/vue-vben-admin/pull/1978

去掉他这次提交的内容 即可正常 
`
.ant-table-body {
        overflow: auto !important;
      }
`

**Comment by linrencai** [comment]
给每列设置width属性貌似可以解决

**Comment by wangjue666** [comment]
https://github.com/vbenjs/vue-vben-admin/issues/3085 这个issue提供了解决方案
