### ISSUE TITLE
自定义表单组件使用CodeEditor初次赋值的问题

### ISSUE THREAD

**Issue by 15643701048a** [vbenjs/vue-vben-admin#2019]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

在打开BasicModal中的表单，将CodeEditor作为自定义表单组件使用时，初次使用setFieldsValue赋值时，无法赋值，关闭后再次打开可以赋值，经过测试只有初次赋值时才不能赋值

<template>
  <BasicModal v-bind="$attrs" @register="registerModal" :title="getTitle" @ok="handleSubmit">
    <BasicForm @register="registerForm" />
  </BasicModal>
</template>
<script lang="ts">
  import { defineComponent, ref, computed, unref } from 'vue';
  import { BasicModal, useModalInner } from '/@/components/Modal';
  import { BasicForm, useForm, FormSchema, useComponentRegister } from '/@/components/Form/index';
  // import { accountFormSchema } from './data';

  import { CodeEditor } from '/@/components/CodeEditor';

  import { getDeptList } from '/@/api/demo/system';

  export default defineComponent({
    name: 'AccountModal',
    components: { BasicModal, BasicForm },
    emits: ['success', 'register'],
    setup(_, { emit }) {
      const isUpdate = ref(true);
      const rowId = ref('');
      useComponentRegister('CodeEditor', CodeEditor);

      const accountFormSchema: FormSchema[] = [
        {
          label: '名称',
          field: 'name',
          component: 'Input',
          required: true,
        },
        {
          label: '变量类型',
          field: 'variableType',
          component: 'Select',
          helpMessage: ['ApiSelect组件', '远程数据源本地搜索', '只发起一次请求获取所有选项'],
          componentProps: {
            options: [
              {
                label: '选项1',
                value: '1',
                key: '1',
              },
              {
                label: '选项2',
                value: '2',
                key: '2',
              },
            ],
          },
          required: true,
        },
        {
          label: '数据库',
          field: 'database',
          component: 'Select',
          componentProps: {
            options: [
              {
                label: '选项1',
                value: '1',
                key: '1',
              },
              {
                label: '选项2',
                value: '2',
                key: '2',
              },
            ],
          },
          required: true,
        },
        {
          label: '写入列',
          field: 'code',
          component: 'CodeEditor',
          required: true,
        },
      ];
      const [
        registerForm,
        { setFieldsValue, getFieldsValue, updateSchema, resetFields, validate },
      ] = useForm({
        labelWidth: 100,
        layout: 'horizontal',
        schemas: accountFormSchema,
        showActionButtonGroup: false,
        baseColProps: {
          span: 24,
        },
      });

      const [registerModal, { setModalProps, closeModal }] = useModalInner(async (data) => {
        resetFields();
        setModalProps({ confirmLoading: false });
        isUpdate.value = !!data?.isUpdate;
        rowId.value = data.data.id;
        if (unref(isUpdate)) {
          console.log(data.data);

          setFieldsValue({
            ...data.data,
          });
        }
      });

      const getTitle = computed(() => (!unref(isUpdate) ? '新增账号' : '编辑账号'));

      async function handleSubmit() {
        try {
          await validate();
          setModalProps({ confirmLoading: true });
          // TODO custom api
          const data = getFieldsValue();
          closeModal();
          emit('success', { isUpdate: unref(isUpdate), data: { ...data, id: rowId.value } });
        } finally {
          setModalProps({ confirmLoading: false });
        }
      }

      return { registerModal, registerForm, getTitle, handleSubmit };
    },
  });
</script>

**Comment by lifei110196** [comment]
我也遇到了相同的问题  
解决方法是 resetFields()只在新增的时候调用 更新的时候不调用

**Comment by wangjue666** [comment]
component 不再支持 `CodeEditor`, 使用`slot `来引入这个组件吧

**Comment by auqf** [comment]
> component 不再支持 `CodeEditor`, 使用`slot `来引入这个组件吧

怎么用呢？有没有demo?

**Comment by auqf** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/8895540/0c850b9e-0c57-4c8b-9704-6828e6dcc49b)
![image](https://github.com/vbenjs/vue-vben-admin/assets/8895540/26802e3b-1f98-4739-936f-e6a8c5bfacd5)
![image](https://github.com/vbenjs/vue-vben-admin/assets/8895540/4cd6a8be-0823-4d8c-8c07-cdf54b21c72b)
使用slot做了个测试，这个地方提示不支持CodeEditor这个组件，如何引入呢？
