### ISSUE TITLE
BasicTree获取选中的key都变成["0-0-1","0-0-0-0","0-0-0-1"]

### ISSUE THREAD

**Issue by dzvane** [vbenjs/vue-vben-admin#2029]
BasicTree :replaceFields="{ title: 'title', key: 'id' }" 已经设置了id，获取选中的key都变成["0-0-1","0-0-0-0","0-0-0-1","0-0-0-0-1","0-0-0","0-0"]

**Comment by zdxzqwz** [comment]
replaceFields这个属性在3.0已经废弃，尝试fieldNames
