### ISSUE TITLE
项目配置的重置功能无效(The reset function of the project configuration is invalid)

### ISSUE THREAD

**Issue by lhq2103387078** [vbenjs/vue-vben-admin#2037]
### 描述 Bug
点击【项目配置】的【重置】按钮，功能未生效
(Click the [reset] button of [project configuration], and the function is not effective)

### 复现 Bug
1. 在页面登录成功后，在页面右上角点击齿轮图标【项目配置】;
   (After successful login on the page, click the gear icon [project configuration] in the upper right corner of the page)
2. 点击【项目配置】的底部【重置】按钮；
   (Click the [reset] button at the bottom of the [project configuration])
3. 结果：【项目配置】的内容没有被重置，页面显示也未重置，此功能无效；
   (Result: the content of [project configuration] has not been reset, and the page display has not been reset, so this function is invalid)

### 建议&优化
1. 在项目根目录下，文件路径为【/src/settings/projectSetting.ts】，修改【setting】常量里面的【menuSetting.theme】为【ThemeEnum.LIGHT】，如图：
 (In the project root directory, the file path is /src/settings/projectsetting.ts, and modify [menusetting.theme] in the [setting] constant to [themeenum.light], as shown in the figure:)
![image](https://user-images.githubusercontent.com/35680109/176998054-68cb8389-5e3c-4126-89d1-375f65aeda83.png)
2. 在项目根目录下，文件路径为【/src/utils/index.ts】，添加【深拷贝】公共方法，如图：
  (Under the root directory of the project, the file path is [/src/utils/index.ts]. Add the public method of [deep copy], as shown in the figure:)
![image](https://user-images.githubusercontent.com/35680109/176998206-8ab4282e-0ecc-4b79-871b-5df86f3e2928.png)
3. 在项目根目录下，文件路径为【/src/layouts/default/setting/components/SettingFooter.vue】，引入【更新主题背景色】方法，引入【深拷贝】公共方法，并在点击【重置】按钮后设置其方法，如图：
  (In the root directory of the project, the file path is [/src/layouts/default/setting/components/settingfooter.vue], the method of [update theme background color] is introduced, the public method of [deep copy] is introduced, and the method is set after clicking the [reset] button, as shown in the figure:)
![image](https://user-images.githubusercontent.com/35680109/176998391-222caf69-66e6-45c7-87dc-5b1da83abae3.png)
![image](https://user-images.githubusercontent.com/35680109/176998443-f5897631-f8ad-44a9-9581-9e74edeffd34.png)

## 系统信息
版本	Windows 10 专业版
版本号	21H2
安装日期	‎2022/‎6/‎22
操作系统内部版本	19044.1766
体验	Windows Feature Experience Pack 120.2212.4180.0

- 操作系统:
Windows10 专业版

- Node 版本:
v16.14.2

- 包管理器 (npm/yarn/pnpm) 及其版本:
pnpm 7.1.0

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！

**Comment by lhq2103387078** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我已经收到了你的邮件，我会尽快回复！
