### ISSUE TITLE
debugger代码位置和调式断点位置不一致

### ISSUE THREAD

**Issue by MossLwj** [vbenjs/vue-vben-admin#2044]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
![image](https://user-images.githubusercontent.com/28034235/177478500-b33d4f61-3fa1-42f2-a2df-df51cd521d0f.png)
debugger代码位置和调式断点位置不一致

### 复现 Bug
在登陆方法中增加了debugger，但是在F12打开开发者工具后，进行代码调试的时候发现断点的位置和debugger位置不一致。

## 系统信息

- 操作系统: win10
- Node 版本: 16.15
- 包管理器 (npm/yarn/pnpm) 及其版本: yarn 1.22.11

**Comment by kuizuo** [comment]
同问

**Comment by MossLwj** [comment]
> 1. vben 自己的vite 插件问题，确保你没有使用过 vben setup 给组件命名的规则 可以找到目录
>    build\vite\plugin\index.ts ，禁掉vueSetupExtend 这个插件 重启项目就好了

不好意思，再问下“没有使用过vben setup给组件命名的规则。”这个是什么意思。小白不是很明白。禁用vueSetupExtend插件后断点是可以了

**Comment by adeewu** [comment]
看我这个方法，能够临时对付一下 #2228

**Comment by adoin** [comment]
> > 1. vben 自己的vite 插件问题，确保你没有使用过 vben setup 给组件命名的规则 可以找到目录
> >    build\vite\plugin\index.ts ，禁掉vueSetupExtend 这个插件 重启项目就好了
> 
> 不好意思，再问下“没有使用过vben setup给组件命名的规则。”这个是什么意思。小白不是很明白。禁用vueSetupExtend插件后断点是可以了

禁用后就不能setup上指名了，keepAlive就失效了，或者得再写个script标签指名

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
