### ISSUE TITLE
本地编译没问题，用docker编译不过

### ISSUE THREAD

**Issue by llz199979** [vbenjs/vue-vben-admin#2046]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by tianyuan233** [comment]
至少贴一下日志吧

**Comment by llz199979** [comment]
> 贴一下日记吧

已经解决了，用npm编译不了，换撑pnpm就可以了

**Comment by adoin** [comment]
> > 贴一下日记吧
> 
> 已经解决了，用npm编译不了，换撑pnpm就可以了

不是一样用的vite build 吗？为啥会有区别 我npm也老卡住 试试pnpm看看
