### ISSUE TITLE
table 搜索框中 我想给一个datepicker 设置一个默认值为当前时间向前推12小时到当前时间 请问应该怎么做

### ISSUE THREAD

**Issue by Arelina** [vbenjs/vue-vben-admin#2048]
设置了defaultValue 结果显示的时间是项目加载时间多次进入显示的时间都一样

**Comment by Arelina** [comment]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/42526528/177676412-3ddd20d8-f1b5-4736-9610-6f9cef3f1e04.png">
然后我这样设置的默认值 但是在点击reset按钮以后 时间就会被置空

然后我在resetFunc中更新了form的值 但是还是会被置空

然后我是这么操作的 虽然这样很不好 但是曲线救国
<img width="705" alt="image" src="https://user-images.githubusercontent.com/42526528/177676920-e2989d92-8e12-4e5f-9d11-8bd180a66cde.png">
希望好心人告诉一下有无其他方法

**Comment by lhywell** [comment]
我是用的beforeFetch,给date参数做处理，截取了日期
<img width="595" alt="image" src="https://user-images.githubusercontent.com/1267061/179938080-62aedee6-2fe5-40fd-82e7-e24a63845312.png">
