### ISSUE TITLE
Table 操作列不齐

### ISSUE THREAD

**Issue by aicerain** [vbenjs/vue-vben-admin#2060]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

表格的操作列 表头和数据不齐
![图片](https://user-images.githubusercontent.com/28593083/177957580-04e4ae97-bed6-425c-aec0-7454f38e2976.png)

### 复现 Bug
[见demo页](https://vvbin.cn/next/#/comp/table/fixedColumn)
奇怪的是如果我按下F12 改变了浏览器高度 会变的对齐
![图片](https://user-images.githubusercontent.com/28593083/177958599-1ea06b32-7613-4058-a008-28be7b39508e.png)

## 系统信息

- 操作系统: Windows10
- Node 版本:18.4
- 包管理器 (npm/yarn/pnpm) 及其版本:7.5

**Comment by iconFehu** [comment]
#2058

**Comment by zusrsoft** [comment]
#2058 没有解决问题，请验证。。。。
![1](https://user-images.githubusercontent.com/26666544/179134903-6a615f0d-43e9-4db8-a48e-ab760b605ab3.png)
![2](https://user-images.githubusercontent.com/26666544/179134917-445844e8-d27a-449b-916c-9aef062cb26b.png)
![3](https://user-images.githubusercontent.com/26666544/179134925-50e83185-3a4d-45e7-bf5c-c7f144d74868.png)
![4](https://user-images.githubusercontent.com/26666544/179134934-a5f7d2ad-fceb-45db-afcc-ec7acaa1ebc7.png)

**Comment by zhangxinyong12** [comment]
.ant-table-cell.ant-table-cell-fix-right.ant-table-cell-fix-right-first {
  right: 0 !important;
}
我这样解决的

**Comment by zhangxinyong12** [comment]
> #2058 没有解决问题，请验证。。。。 ![1](https://user-images.githubusercontent.com/26666544/179134903-6a615f0d-43e9-4db8-a48e-ab760b605ab3.png) ![2](https://user-images.githubusercontent.com/26666544/179134917-445844e8-d27a-449b-916c-9aef062cb26b.png) ![3](https://user-images.githubusercontent.com/26666544/179134925-50e83185-3a4d-45e7-bf5c-c7f144d74868.png) ![4](https://user-images.githubusercontent.com/26666544/179134934-a5f7d2ad-fceb-45db-afcc-ec7acaa1ebc7.png)

从来不考虑缩放的问题

**Comment by zhangxinyong12** [comment]
还不对，错位是7px，是右侧滚动条的宽度。我又写了个方法，当数据请求完成后,.我去判断是否出现了滚动条，然后重新设置right是0px还是7px

**Comment by johnshi** [comment]
我也出现了这个问题，有没有正确的解决方案呢？

**Comment by ZengLingJia520** [comment]
> 还不对，错位是7px，是右侧滚动条的宽度。我又写了个方法，当数据请求完成后,.我去判断是否出现了滚动条，然后重新设置right是0px还是7px

你是怎么判断是否出现滚动条的?

**Comment by wangjue666** [comment]
可以详细看下这个PR https://github.com/vbenjs/vue-vben-admin/pull/3087 里面提供了解决方案
