### ISSUE TITLE
debugger断点位置不一致

### ISSUE THREAD

**Issue by wmf1993** [vbenjs/vue-vben-admin#2061]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

在src\router\guard\index.ts文件中，debugger与chrome断点位置不一致
![1657272531479](https://user-images.githubusercontent.com/31245615/177962536-b3ffb233-0e2f-4f6d-abf5-2e3ced8d85bd.png)
原以为是vite-plugin-vue-setup-extend插件问题，但在禁用后问题仍存在
后经过排查发现是ant-design-vue的组件导致的，注释组件的使用后，断点位置正常。重新启用vite-plugin-vue-setup-extend后是同样结果，只要ant-design-vue组件使用就好导致debugger位置不正常

### 复现 Bug

在createMessageGuard的router.beforeEach前添加debugger，刷新页面，断点位置不正常（见上图）
```
export function createMessageGuard(router: Router) {
  const { closeMessageOnSwitch } = projectSetting;
  debugger
  router.beforeEach(async () => {
    try {
      if (closeMessageOnSwitch) {
        Modal.destroyAll();
        notification.destroy();
      }
    } catch (error) {
      warn('message guard error:' + error);
    }
    return true;
  });
}
```
注释`Modal.destroyAll();notification.destroy();`后，断点正常，如下图
![1657273107707](https://user-images.githubusercontent.com/31245615/177964134-ed74d6d1-a235-4472-bc0f-e13ab665860b.png)

## 系统信息

- 操作系统: win10
- Node 版本: v16.15.1
- 包管理器 (npm/yarn/pnpm) 及其版本: 1.22.19

**Comment by adeewu** [comment]
@wmf1993 这个问题找到解决办法了吗？

**Comment by adeewu** [comment]
@wmf1993 看我这个方法，能够临时对付一下 #2228

**Comment by lifei110196** [comment]
@adeewu 非常感谢

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
