### ISSUE TITLE
git commit 提交，执行检查失败，所有提交文件被回滚，且无提交记录。

### ISSUE THREAD

**Issue by hmingv** [vbenjs/vue-vben-admin#2064]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

执行 git commit 提交后，执行检查失败，所有的提交文件都被回滚，且无提交记录。

![image](https://user-images.githubusercontent.com/57735185/178094504-a71f199f-9935-40f6-9387-db3d0366af67.png)

![image](https://user-images.githubusercontent.com/57735185/178094488-97b4769f-7605-4dab-86a2-7f7e023bf646.png)

### 复现 Bug

无法定位是哪个文件导致的问题，部分 commit 无问题。

## 系统信息

- 操作系统: Windows
- Node 版本: 16.15.1
- 包管理器 (npm/yarn/pnpm) 及其版本: 1.22.11

**Comment by Zhengqbbb** [comment]
从报错信息来看是运行 提交文件校验检查命令 超时，能说一下你提交了什么文件吗

**Comment by hmingv** [comment]
我提交了大概30+文件。
把这些文件拆分，每次提交几个文件就不会出现这个问题了（最后用这个方式把所有文件提交到了仓库）。

**Comment by Zhengqbbb** [comment]
嗯嗯，从配置来看会分文件进行检查，如果一次性提交了大量文件，运行命令时不排除在性能不好的时候会超时的可能

https://github.com/vbenjs/vue-vben-admin/blob/6f5711b0889f1e3c0e7a6c3b0701ff21dc9a3742/package.json#L163-L186

**Comment by hmingv** [comment]
哦哦，感谢解释！这样的话倒是能理解报错。

不过这个问题影响的有点严重，它并不是单纯的提示错误，而是把我的所有文件都回滚了，工作全部白干。。。
如果不是编辑器能恢复历史，emmm....，我就得跑了

所以，如果可以的话，还是希望这个项目可以把这个问题修复一下。

**Comment by xingyu4j** [comment]
是不是更新了，新的用czg替换了，具体咋使用还没研究明白，好像和husky有点冲突

**Comment by Zhengqbbb** [comment]
> 是不是更新了，新的用czg替换了，具体咋使用还没研究明白，好像和husky有点冲突

什么意思，`czg`应该没和 husky挂钩呀

**Comment by hmingv** [comment]
> > 哦哦，感谢解释！这样的话倒是能理解报错。
> > 不过这个问题影响的有点严重，它并不是单纯的提示错误，而是把我的所有文件都回滚了，工作全部白干。。。 如果不是编辑器能恢复历史，emmm....，我就得跑了
> > 所以，如果可以的话，还是希望这个项目可以把这个问题修复一下。
> 
> 其实没有回滚, git暂存了, git stash list 查看下有没 然后用 git stash pop 可以恢复

是的，确实可以恢复，但此问题有更好的解决方案吗？

**Comment by Zhengqbbb** [comment]
我查看了 `lint-staged`  的文档
https://github.com/okonet/lint-staged#command-line-flags

可以添加 `--no-stash` options
`--no-stash :                        disable the backup stash, and do not revert in case of errors`
https://github.com/vbenjs/vue-vben-admin/blob/dac9301af485a32583e5b3aa8bc667ead514ae17/.husky/pre-commit#L8

```
npm run lint:lint-staged  --no-stash
```
