### ISSUE TITLE
批量勾选table中数据之后 切换页码之后能否恢复之前的选中状态

### ISSUE THREAD

**Issue by Mr1Sun** [vbenjs/vue-vben-admin#2067]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by wjc112233** [comment]
组件内部没有提供这个功能，可以自己实现

**Comment by skywolf627** [comment]
```
  <BasicTable
      @register="registerTable"
      :rowSelection="{
        type: 'checkbox',
        selectedRowKeys: checkedKeys,
        onChange: onSelectChange,
        preserveSelectedRowKeys: true,
      }"
    >
    </BasicTable>
```
