### ISSUE TITLE
BASE_HOME 更改首页路由 无效

### ISSUE THREAD

**Issue by cnvoa** [vbenjs/vue-vben-admin#2069]
### 修改 BASE_HOME 期望更改首页路由无效

根据文档修改了 src/enums/pageEnum.ts 中 BASE_HOME 的值,  首页路由依然打开的是 /dashboard/analysis

重新从git拉了一份代码

修改BASE_HOME的值后, 也重新 npm run serve 运行过

首页路由依然还是 /dashboard/analysis

![WX20220711-150734](https://user-images.githubusercontent.com/61954852/178209078-279d3802-447b-41b4-b82e-afed329768be.png)

![QQ20220711-151434](https://user-images.githubusercontent.com/61954852/178209101-ae5313be-11e1-42e4-9c88-1be15a080555.png)

- 操作系统:
- Node 版本: v16.14.2
- 包管理器 (npm/yarn/pnpm) 及其版本:8.5.0
- macos 11.5.2

**Comment by neu-yuyang** [comment]
把mock数据中用户的homepath置空即可；
mock/sys/user.ts（homePath: ''）

**Comment by linjiade627** [comment]
> 把mock数据中用户的homepath置空，重新登录即可； mock/sys/user.ts（homePath: ''）

我也正好有这个疑惑，原来是这里的问题，感谢！！！

**Comment by mynetfan** [comment]
接口返回的用户首页配置优先于系统的默认首页
