### ISSUE TITLE
table组件不支持ant design vue3.x的设置 resizable 开启拖动列

### ISSUE THREAD

**Issue by speed-git** [vbenjs/vue-vben-admin#2073]
### 描述 Bug

table组件不支持ant design vue3.x的设置 resizable 开启拖动列，无法使列自由伸缩。ant design vue3.x自身是支持列伸缩的。

### 复现 Bug

table column属性中的resizable设置为true时，无法进行列伸缩。

## 系统信息

- 操作系统:
- Node 版本: 14.19.0
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm

**Comment by wanghao1993** [comment]
> const [registerTable] = useTable({ title: '自定义列内容', titleHelpMessage: '表格中所有头像、图片均为mock生成，仅用于演示图片占位', api: demoListApi, columns: columns, bordered: true, showTableSetting: true, actionColumn: { resizable: true } });
> 
> 添加之后列依然没有伸缩效果呀 , 请问是哪里还需要配置吗

这个项目是用的antv2.x的 当然没用啊 哥
