### ISSUE TITLE
网页放后台一段时间后再切换页面无响应

### ISSUE THREAD

**Issue by mmdjiji** [vbenjs/vue-vben-admin#2075]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

[demo](https://vvbin.cn/next/) 网页在开后台一段时间后（打开网页，浏览器最小化然后去摸会鱼），再切换菜单，就无响应，浏览器 Console 有报错，刷新后一切正常。

具体报错图如下：

![bug](https://s2.loli.net/2022/07/13/WPkNu8QIb6eKhwH.png)

### 复现 Bug

访问 [demo](https://vvbin.cn/next/) 并登录，随便选择一个页面，最小化浏览器，摸会鱼（大概几个小时不去管它就行），得以复现（已多次成功复现）。

## 系统信息

- 操作系统: Windows 10 21H2 19044.1766
- 浏览器: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.49
- Node 版本: -
- 包管理器 (npm/yarn/pnpm) 及其版本: -

**Comment by kangweiming1996** [comment]
@mmdjiji 请问问题解决了吗，我也遇到同样的问题

**Comment by mmdjiji** [comment]
> @mmdjiji 请问问题解决了吗，我也遇到同样的问题

并没有解决

**Comment by M69W** [comment]
报错是 静态文件没了
可能是自动构建后清除了。
![image](https://user-images.githubusercontent.com/15809201/187142271-37d201f4-103e-4be8-963f-fb3c09b5acd5.png)

估计得自己本地测试留意一下。

**Comment by mynetfan** [comment]
demo会在有更新后自动构建，一些文件名中的hash会改变，这样就会导致已打开的页面出错。

**Comment by astonishqft** [comment]
> 

有点不合理的地方在于，重新构建应该是只修改变更后的文件的hash名，而不是全量变更所有文件的hash名，这里应该是有问题的
