### ISSUE TITLE
初始化项目后，登录页样式加载异常

### ISSUE THREAD

**Issue by co-pine** [vbenjs/vue-vben-admin#2076]
![图片](https://user-images.githubusercontent.com/77868200/178883443-93f41ae4-f7af-4e61-ad0c-b5acad490818.png)

**Comment by dearmark** [comment]
你项目文件夹路径中，是不是有中文？

**Comment by 2268143474** [comment]
谢了兄弟，中文倒是没有，有个其它特殊字符导致的
