### ISSUE TITLE
表格组建，点击刷新，如果搜索栏条件比较多的话，更多搜索会跳来跳去

### ISSUE THREAD

**Issue by delaynew** [vbenjs/vue-vben-admin#2078]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

请清晰地描述此 Bug 的具体表现。

### 复现 Bug

表格组建，点击刷新，如果搜索栏条件比较多的话，更多搜索会跳来跳去
## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by skywolf627** [comment]
+1

**Comment by iconFehu** [comment]
![29e94ac4-59e8-48cf-b1bc-98f56a08ca13](https://user-images.githubusercontent.com/46149128/181293006-e1b360f0-eac5-4b45-8405-e0767b584897.gif)
复现下这个趴

**Comment by zhang-jianxun** [comment]
@iconFehu 搜索区域得在收起状态下才会出现。可以看官方例子，组件 -> table -> 开启搜索区域，把搜索区域收起，点击查询、重置、换页会出现

https://user-images.githubusercontent.com/16345344/181397365-acc0c34c-fba6-4e51-bae7-14444ea5a9a5.mov

。

**Comment by iconFehu** [comment]
#2083 perf: 优化BasicForm更新表单时闪烁
![9ffe0edf-d62d-49c3-8571-b69529a31267](https://user-images.githubusercontent.com/46149128/181574607-53a28493-40e8-4862-a72a-bf0a4208542e.gif)

**Comment by JerryJeck** [comment]
pr:https://github.com/vbenjs/vue-vben-admin/pull/2125 ，看到了这个，作者没合并到master 上面
