### ISSUE TITLE
打包部署后主题色theme切换不生效，还是使用初始配置的主题色

### ISSUE THREAD

**Issue by codefarming** [vbenjs/vue-vben-admin#2087]
![image](https://user-images.githubusercontent.com/63433244/179391969-8949b02c-6dea-44c9-b9d2-c20aac77ee95.png)
官方网站中主题色切换也是无效的，看了之前别人提过的issues是因为vite版本2.5.10之后打包时生成app-theme-style.css为空导致的，本人当前使用的vite版本为2.6.13，现在有什么办法可以解决这个问题？

**Comment by dapeng0201** [comment]
同, 我也遇到了这个问题，本地vite运行可以。本地打包preview切换就没效果了

**Comment by dapeng0201** [comment]
解决方案: 
https://gitee.com/thinkgem/jeesite-vue/blob/8cddc3e006cf5992db9aaf2cdfeae9d62a13b708/build/vite/plugin/theme.ts#
这个文件覆盖你项目同路径文件,  我试过了可以实现切换，不用切换vite版本

**Comment by codefarming** [comment]
用你的方法试了，有效果可以正常切换主题色了

**Comment by yeyeye7** [comment]
为什么我的isBuild是false

**Comment by Yuliang-Lee** [comment]
针对 `vite-plugin-theme` 的问题修复发了新的包，使用新的包在初始化 `viteThemePlugin` 时传入 `isProd: true` 即可解决问题
https://www.npmjs.com/package/@xlaoyu/vite-plugin-theme
