### ISSUE TITLE
pnpm install安装错误

### ISSUE THREAD

**Issue by zhengsonglin** [vbenjs/vue-vben-admin#2090]
最新2.8.0版本， pnpm install 安装依赖出错

Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: D:\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1778, reused 246, downloaded 1050, added 1299, done
node_modules/.pnpm/core-js@3.22.1/node_modules/core-js: Running postinstall script...
 WARN  lifecycle The node binary used for scripts is C:\Program Files\nodejs\node.exe but pnpm is using C:\Program Filesnode_modules/.pnpm/core-js@3.22.1/node_modules/core-js: Running postinstall script, done in 579ms node binary pnpm was executed with.
node_modules/.pnpm/cwebp-bin@5.1.0/node_modules/cwebp-bin: Running postinstall script, done in 4.3s
node_modules/.pnpm/esbuild@0.11.23/node_modules/esbuild: Running postinstall script, done in 7.2s
node_modules/.pnpm/esbuild@0.11.3/node_modules/esbuild: Running postinstall script, done in 7s
node_modules/.pnpm/gifsicle@5.2.0/node_modules/gifsicle: Running postinstall script, done in 3.6s
node_modules/.pnpm/jpegtran-bin@5.0.2/node_modules/jpegtran-bin: Running postinstall script, failed in 10.1s
.../node_modules/jpegtran-bin postinstall$ node lib/install.js
│   ‼ Command failed: D:\private\vue-vben-admin\node_modules\.pnpm\jpegtran-bin@5.0.2\node_modules\jpegtran-bin\vendor
│ Not a JPEG file: starts with 0x25 0x54
│   ‼ jpegtran pre-build test failed
│   i compiling from source
│   × Error: Command failed: C:\Windows\system32\cmd.exe /s /c "touch configure.ac aclocal.m4 configure Makefile.am Ma
│ 'touch' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
│ ���������ļ���
│     at D:\private\vue-vben-admin\node_modules\.pnpm\execa@0.7.0\node_modules\execa\index.js:231:11
│     at runMicrotasks (<anonymous>)
│     at processTicksAndRejections (internal/process/task_queues.js:93:5)
│     at async Promise.all (index 0)
└─ Failed in 10.1s
node_modules/.pnpm/jpegtran-bin@6.0.1/node_modules/jpegtran-bin: Running postinstall script...
node_modules/.pnpm/mozjpeg@7.1.1/node_modules/mozjpeg: Running postinstall script, done in 3.6s
node_modules/.pnpm/optipng-bin@7.0.1/node_modules/optipng-bin: Running postinstall script, done in 4s
node_modules/.pnpm/pngquant-bin@6.0.1/node_modules/pngquant-bin: Running postinstall script, done in 4.2s
node_modules/.pnpm/vue-demi@0.12.5_vue@3.2.33/node_modules/vue-demi: Running postinstall script, done in 1.2s
 ELIFECYCLE  Command failed with exit code 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vben-admin@2.8.0 bootstrap: `pnpm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vben-admin@2.8.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\songlin.zheng\AppData\Roaming\npm-cache\_logs\2022-07-18T09_55_06_763Z-debug.log

**Comment by xjdevelop** [comment]
你好，问题解决了吗？

**Comment by liujianchao1995** [comment]
我也是这样

**Comment by lyric-zemin** [comment]
![image](https://user-images.githubusercontent.com/54665054/203678579-43c7f4de-5104-43aa-a24b-1a2b51282f91.png)

**Comment by liujianchao1995** [comment]
我看到官网文档有说明，Linux系统下安装依赖使用imagemin这个包的话会导致安装失败，移除就好了。
http://doc.vvbin.cn/other/faq.html#%E5%9C%A8-linux-%E5%86%85%E4%BE%9D%E8%B5%96%E5%AE%89%E8%A3%85%E5%A4%B1%E8%B4%A5

**Comment by xjdevelop** [comment]
好的，刚看到不好意思，谢谢啦！


 
我看到官网文档有说明，Linux系统下安装依赖使用imagemin这个包的话会导致安装失败，移除就好了。
 http://doc.vvbin.cn/other/faq.html#%E5%9C%A8-linux-%E5%86%85%E4%BE%9D%E8%B5%96%E5%AE%89%E8%A3%85%E5%A4%B1%E8%B4%A5

**Comment by woodsZero** [comment]
> 

我也碰到这个问题了，大佬解决了吗

**Comment by echoyaan** [comment]
同样的问题 貌似和 mozjpeg 以及系统有关; 安装下依赖. 对于我来说有用.
macOS 13.0 (22A380)

brew install autoconf automake libtool nasm make libpng dpkg pkgconfig wget gcc

pnpm install --ignore-scripts
