### ISSUE TITLE
main.ts加载很久

### ISSUE THREAD

**Issue by nathan1217** [vbenjs/vue-vben-admin#2093]
我获取的分支是这个版本vben-admin@2.8.0 dev，但是项目跑起来之后main.ts加载很久。
<img width="949" alt="1658193847508" src="https://user-images.githubusercontent.com/10413074/179643882-bb818ac7-c78f-48f4-8270-b8bd82bc344a.png">

**Comment by yuan2022** [comment]
一样，很慢很慢，项目刚第一次需要几分钟才能响应，第二次就快了很多，希望解决

**Comment by 13250515751** [comment]
太慢了，找不到解决方案，不敢用。。

**Comment by XiaoNode** [comment]
> 一样，很慢很慢，项目刚第一次需要几分钟才能响应，第二次就快了很多，希望解决

同一个问题..
