### ISSUE TITLE
新手请教热更新

### ISSUE THREAD

**Issue by diorslau** [vbenjs/vue-vben-admin#2094]
新手刚接触前端, 想请教一下, 文件修改了以后怎么热更新呢?  现在是每次都要重新build一次  太慢了

**Comment by wjc112233** [comment]
是热更新的啊

**Comment by diorslau** [comment]
> 

默认就是的吗?  那为啥我改了页面以后  刷新并没有生效呢

**Comment by wjc112233** [comment]
![微信图片_20220720105404](https://user-images.githubusercontent.com/45564129/179886562-ebc3bd64-0476-4b68-b81e-c702c2cc0906.png)
![微信图片_20220720105447](https://user-images.githubusercontent.com/45564129/179886576-25d20c69-1adb-4c47-a87b-1a186c292d2c.png)

可以在开发阶段把openKeepAlive设置为false，然后清楚一下缓存，就有热更新了
