### ISSUE TITLE
我把表单的配置项写在ts文件里面了, 但是里面事件不知道怎么发送出来

### ISSUE THREAD

**Issue by github-ZH-cn** [vbenjs/vue-vben-admin#2104]
![_IZ(0FYRA$UXNLX7T0I%2%3(1)](https://user-images.githubusercontent.com/67533362/180162836-9e1c2039-fbb0-4b01-9ca8-6771650c0a2b.png)

sdmxz.vue 如何使用.ts文件 里面的事件

**Comment by wangxiaoer5200** [comment]
![image](https://user-images.githubusercontent.com/38752239/180172287-b38dd29e-bca8-4285-b30c-82ca8db4392b.png)
就正常使用咯

**Comment by github-ZH-cn** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vbenjs/vue-vben-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 下午4:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vbenjs/vue-vben-admin] 我把表单的配置项写在ts文件里面了, 但是里面事件不知道怎么发送出来 (Issue #2104)

这个是事件我想在.vue文件里面触发,不想再.ts里面触发,这个怎么做


 

 就正常使用咯

**Comment by github-ZH-cn** [comment]
我就是在onSearch事件 打开model 弹窗 这个怎么做啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vbenjs/vue-vben-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 下午4:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vbenjs/vue-vben-admin] 我把表单的配置项写在ts文件里面了, 但是里面事件不知道怎么发送出来 (Issue #2104)





 

 就正常使用咯
