### ISSUE TITLE
table 列宽拖拽

### ISSUE THREAD

**Issue by zhuyujie068** [vbenjs/vue-vben-admin#2107]
作者你好，可以为table新增列宽拖拽功能吗？
效果：用户可以根据字段长度，自行拖拽table表头，生成想要的宽度。

**Comment by WitMiao** [comment]
antd vue自带的功能: [可伸缩列](https://www.antdv.com/components/table-cn#components-table-demo-resizable-column)
在想要可伸缩的列columns里加resizable: true属性, 再给table加个@resizeColumn事件就好

**Comment by zhuyujie068** [comment]
你好，[可伸缩列](https://www.antdv.com/components/table-cn#components-table-demo-resizable-column) 它是[Ant Design Vue](https://www.antdv.com/index-cn) 3.x 版本才有的功能，[2.x](https://2x.antdv.com/components/table-cn#components-table-demo-resizable-column)版本好像没有该功能，所以无法使用 可伸缩列 ，请问还有其他方法吗，求指导，谢谢！

**Comment by zhuyujie068** [comment]
> antd v自带的功能：[可](https://www.antdv.com/components/table-cn#components-table-demo-resizable-column) 列缩图想要在可缩略图的列里加resize：true属性，给table加个@resizeColumn事件就好了



> ant v的功能：[可](https://www.antdv.com/components/table-cn#components-table-demo-resizable-column)列缩图自带可 在一个可列里加resize：真实的列里加resize，给table加@reColumn事件就好了

**Comment by zhuyujie068** [comment]
目前该项目用的是 2.7.2 版本，他对应的 Ant Design 2.x

**Comment by speed-git** [comment]
> antd vue自带的功能: [可伸缩列](https://www.antdv.com/components/table-cn#components-table-demo-resizable-column) 在想要可伸缩的列columns里加resizable: true属性, 再给table加个@resizeColumn事件就好

为什么我都安装你的加上了还是不行，大佬有测过吗。可以的话能不能放到线上的table的demo中，让我们看到。

**Comment by Mahailong0522** [comment]
> > antd vue自带的功能: [可伸缩列](https://www.antdv.com/components/table-cn#components-table-demo-resizable-column) 在想要可伸缩的列columns里加resizable: true属性, 再给table加个@resizeColumn事件就好
> 
> 为什么我都安装你的加上了还是不行，大佬有测过吗。可以的话能不能放到线上的table的demo中，让我们看到。

antd vue升级到3.0版本，然后再按照楼上说的去做，可以实现。前几天刚有人提交了pr,解决了这个问题。

**Comment by Mahailong0522** [comment]
[点击这里 ](https://github.com/vbenjs/vue-vben-admin/issues/2073)

**Comment by Mahailong0522** [comment]
看这个提交 [#2073 ](https://github.com/vbenjs/vue-vben-admin/issues/2073)

**Comment by jslthg** [comment]
"ant-design-vue": "^3.2.17",
export function getBasicColumns(): BasicColumn[] {
  return [
    {
      title: 'ID',
      dataIndex: 'id',
      fixed: 'left',
      width: 200,
    },
    {
      title: '地址',
      dataIndex: 'address',
      resizable: true,
    }]
不好用啊，
