### ISSUE TITLE
表格没有数据的时候，为什么不自适应高度了？

### ISSUE THREAD

**Issue by skywolf627** [vbenjs/vue-vben-admin#2123]
有数据的时候可以自适应父级高度，没数据的时候是不是也能适应一下高度
![image](https://user-images.githubusercontent.com/9822661/181406945-cc0b57fa-cf96-4e25-8c69-e38e60f23fa9.png)

**Comment by WatingChen** [comment]
useTable时设置canResize为true

**Comment by lointain** [comment]
测试认为这是bug, 这就很崩溃.
