### ISSUE TITLE
useTable 表单闪现

### ISSUE THREAD

**Issue by lx11573** [vbenjs/vue-vben-admin#2124]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
使用useTable时，使用 useSearchForm后，当收起部分输入框时，点击查询数据按钮，输入框闪现

### 复现 Bug
[官方预览项目](https://vvbin.cn/next/#/comp/table/formTable)
1.点击收起，隐藏部分输入框
2.点击查询，隐藏输入框闪现
## 系统信息

- 操作系统: Mac OS Big Sur
- Node 版本: 16.13
- 包管理器 (npm/yarn/pnpm) 及其版本:
pnpm 7.6

**Comment by iconFehu** [comment]
> **⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**
> 
> * [x]  已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
> * [x]  确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
> * [x]  已在 Issues 中搜索了相关的关键词
> * [x]  不是 ant design vue 组件库的 Bug
> 
> ### 描述 Bug
> 使用useTable时，使用 useSearchForm后，当收起部分输入框时，点击查询数据按钮，输入框闪现
> 
> ### 复现 Bug
> [官方预览项目](https://vvbin.cn/next/#/comp/table/formTable) 1.点击收起，隐藏部分输入框 2.点击查询，隐藏输入框闪现
> 
> ## 系统信息
> * 操作系统: Mac OS Big Sur
> * Node 版本: 16.13
> * 包管理器 (npm/yarn/pnpm) 及其版本:
>   pnpm 7.6

#2083

**Comment by iconFehu** [comment]
https://github.com/vbenjs/vue-vben-admin/pull/2083/commits/7ac400c5c7717ddd2b5f5399c7958c0b1f8ad947?diff=split&w=0

**Comment by duanPeng1** [comment]
请问解决了吗？查询条件的form一直闪现

**Comment by lwz1963785622** [comment]
> [7ac400c](https://github.com/vbenjs/vue-vben-admin/commit/7ac400c5c7717ddd2b5f5399c7958c0b1f8ad947)



> [7ac400c](https://github.com/vbenjs/vue-vben-admin/commit/7ac400c5c7717ddd2b5f5399c7958c0b1f8ad947)

闪烁是没了  input 输不了文字了

**Comment by caelanChan** [comment]
@lwz1963785622  把resetSchema干掉，然后去掉防抖，或者在原来的代码直接去掉防抖，我看这个函数只有更新表单才会触发应该影响不大

**Comment by niuyunlei** [comment]
> @lwz1963785622 重置一下，然后去掉防抖，或者在原来的代码干掉防更新功能，我只要把Schema触发应该会影响到这个

具体怎么做呢

**Comment by JerryJeck** [comment]
pr:https://github.com/vbenjs/vue-vben-admin/pull/2125 ，后面找到了这个，完美修复，不知道为什么作者没合并
