### ISSUE TITLE
useForm 中 scheme 选项 slot 与 component冲突

### ISSUE THREAD

**Issue by lx11573** [vbenjs/vue-vben-admin#2126]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
useForm 中 scheme 的选项可以使用 slot，但是 component 为必填属性，如果不添加 component属性，slot 就无法生效

### 复现 Bug
[官方预览项目](https://vvbin.cn/next/#/comp/form/useForm)
## 系统信息

- 操作系统: Mac OS BigSur
- Node 版本: 16.13
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 7.6

**Comment by lhywell** [comment]
我也碰到这个问题

**Comment by wangjue666** [comment]
是的 `component ` 为必填属性,  这里的类型可以改成  `component ` 和 `slot` 为互斥类型, 或者 `slot`属性存在 `component `属性可为可选。这样比较合适

**Comment by wangjue666** [comment]
@likui628 大佬看看能否解决下这个类型问题

**Comment by likui628** [comment]
是这个意思吗？
FormSchemaA：component和slot任意设置一个即可
FormSchemaB：component和slot只能二选一

![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/1bcf57b4-1182-4202-8473-dcf63130e875)


[Typescript Playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcDCEC2kB2wcwAqyqAvAFBxwA+cA5AJI5gCuMdlN9TrMA4lAgswHKrUbM2ABQCGAZzkB3aABNRXCbwDKwGVADGACw7kAlgWBQAZjP2oAQvOAAxaJi1HgmGXADenK1NgABsVAC44ORgocwBzAG5OYJkAIxCAdVMVGEMAfgiomJxYrhwWTDSoRIBfcjMLa1tUDGwIPAJXKHdPbzhQGHwVOThHORc3D0MvH38qfSxcfBgIlsWCYhQauvMBxrs4LWCIGE7uqd7+weHR8a7J6b9OOSPlyOi4rfJQSFgEEjhTvdvABBOCkdALNpLQE9Hy0Q7HGHnGRfcDQeBIFAAiaw+xguAAClWUI6OORcAAZH5Ii98nA8AA3SxwaoASi4BIRJzJDypvjg81a7RgdMZzLZiTqwWA8DksIAjBEkdNQeD+c9jhE6PL5XQADRwZJpYKZbKGCLygAMloNgRC4XodtCupZ5GlsthACYlTyQfj+YK1q9NGwBEIRLagqEtU6VC7au7IrCAMw+u6w1XUwMk4M8UOCYT6mma+g6ouxmNRuN0V1umVJ5EAFjTZ2meLVxeDZYNRoyWRyFutkftlft8brHuRAFYW0CZO2s5DhVq8-wCxG4BXHVXx4m5ciAGyz3H+gVLpYryRr8NFjVd3XD6Pbsc16pAA)

**Comment by wangjue666** [comment]
@likui628  嗯嗯 `是的，FormSchemaA `就挺好

**Comment by wangjue666** [comment]
这个类型写起来简单 我之前设想用类型体操来实现，太痛苦了
