### ISSUE TITLE
在编辑表单中使用useForm时调用setFieldsValue后，组件的onChange未主动触发

### ISSUE THREAD

**Issue by xslsl** [vbenjs/vue-vben-admin#2142]
{
    field: 'f1',
    label: 'cs',
    component: 'ApiSelect',
    required: true,
    componentProps: {
    api: getXXX,
    onChange: (value, options) => {
        nextTick(() => {
        console.log(123);
        });
    },
}

setFieldsValue 设置完成以后可以正常绑定，但onChange 没有触发，求教如何在绑定完成值后自动触发

**Comment by uncarbon97** [comment]
=.=原来设置事件是这么写的啊 学到了

**Comment by 17797776321** [comment]
> 

请问您这个问题解决了吗？

**Comment by uncarbon97** [comment]
> > 
> 
> 请问您这个问题解决了吗？

也许 setFieldsValue 不会触发到 watch 事件？
不然只能把 onChange 事件要做的业务逻辑另外封到一个 function 里手动调用 了

**Comment by xslsl** [comment]
> > 
> 
> 请问您这个问题解决了吗？

我原本需求是，第一个下拉点击事件里面 加载第二个下拉的数据，尝试很多种方式无法触发onChange事件后，换了一种思路解决问题。即：在第二个下拉加载数据时，参数绑定到第一个下拉值，这样就能实现代码如下，希望对你有所帮助：
`{
    field: 'f2',
    label: 'f2',
    component: 'ApiSelect',
    required: true,
    componentProps: ({ schema, tableAction, formActionType, formModel }) => {
      return {
        api: getListXXX,
        params: {
          orgId: formModel.f1,
        },
      };
    },
  }`

**Comment by uncarbon97** [comment]
> > > 
> > 
> > 
> > 请问您这个问题解决了吗？
> 
> 我原本需求是，第一个下拉点击事件里面 加载第二个下拉的数据，尝试很多种方式无法触发onChange事件后，换了一种思路解决问题。即：在第二个下拉加载数据时，参数绑定到第一个下拉值，这样就能实现代码如下，希望对你有所帮助： `{ field: 'f2', label: 'f2', component: 'ApiSelect', required: true, componentProps: ({ schema, tableAction, formActionType, formModel }) => { return { api: getListXXX, params: { xxx: formModel.f1, }, }; }, }`

谢谢，官方示例代码里有个“省份与城市联动”的，我参考那个完成的

**Comment by acegank** [comment]
这样做会有问题的，f2会多请求一次，因为params watch到两次
