### ISSUE TITLE
编辑表格一次性加载1000条数据，加载很长时间，数据量更大一些页面崩溃

### ISSUE THREAD

**Issue by Vsa1968911450** [vbenjs/vue-vben-admin#2154]
使用setTableData方法去往可以编辑行的table去添加数据 如果数据量过大会导致页面崩溃，请问下怎么优化（1000条setTableData进去会很卡，如果数据量变成1万条页面会崩溃）
或者能否在table中做成一个虚拟滚动的效果
例子可以使用vben官网https://vvbin.cn/next/#/comp/table/editRowTable  里面的内容 处理数据量大会比较吃力
vue：3.2.26
ant design vue: 3.2.0
- Operating System: win10 
- Node version: 16.10.0
- Package manager (npm/yarn/pnpm) and version:7.1.7

**Comment by fanhoucheng** [comment]
table支持大数据量，你得找一些第三方的table控件，vben这个只是前端框架，不是万能的，
vben的table控件，适合常用的分页查询

另外从用户角度来说你一页显示上万条数据能带来什么好处？让操作用户一天就停留在这个页面慢慢看这一万条数据？
