### ISSUE TITLE
/public/resource/tinymce/ 下的文件需要更新，和当前使用的tinymce版本不一致，导致部分功能有问题

### ISSUE THREAD

**Issue by slmev** [vbenjs/vue-vben-admin#2155]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

如题

### 复现 Bug
[https://vvbin.cn/next/#/comp/editor/tinymce/index](https://vvbin.cn/next/#/comp/editor/tinymce/index)

![image](https://user-images.githubusercontent.com/18041237/183828776-e9cefd9e-7dc3-4017-bc83-c38444988eea.png)

下拉选择框失效

**Comment by wujieli0207** [comment]
请合并代码
