### ISSUE TITLE
vite2的版本的服务比较慢，导致首次加载页面时间太长，建议升级vite到3的版本

### ISSUE THREAD

**Issue by yeyuliang2015** [vbenjs/vue-vben-admin#2160]
vite2的版本的服务比较慢，导致首次加载页面时间太长，建议升级vite到3的版本

**Comment by yeyuliang2015** [comment]
升级后加载main.ts不会再卡住pending了

**Comment by M69W** [comment]
提 PR？

**Comment by iconFehu** [comment]
PR早提了 https://github.com/vbenjs/vue-vben-admin/pull/2083/commits/f44183e77e8c8f00a21fe4697485c4b60595970e

**Comment by iconFehu** [comment]
![image](https://user-images.githubusercontent.com/46149128/184057975-811a8ada-5556-4179-b223-c11edbb3e307.png)

**Comment by yeyuliang2015** [comment]
> 提 PR？

还需要再提一遍么？

**Comment by iconFehu** [comment]
一个月了都，pr还没通过呢

**Comment by yeyuliang2015** [comment]
@M69W 

> 一个月了都，pr还没通过呢

这个有提过PR了

**Comment by KongYoutao** [comment]
vite2.0升级3.0需要注意什么吗

**Comment by iconFehu** [comment]
![image](https://user-images.githubusercontent.com/46149128/187371656-4f4df5b4-3450-442d-b181-c536f144209b.png)
https://cn.vitejs.dev/guide/migration.html

**Comment by cnzdq** [comment]
@iconFehu 改成vite 3还是老样子，main.ts 需要 30s 等待，你们解决了吗

**Comment by iconFehu** [comment]
@cnzdq 
![image](https://user-images.githubusercontent.com/46149128/188565201-21684553-7afb-4ef1-a0ed-3d632312ee74.png)
测试了下 页面加载完大概5秒钟

**Comment by nguyenhan-se** [comment]
@iconFehu hi, i have a problem when i upgrade vite 3
![image](https://user-images.githubusercontent.com/51753522/188618240-7e10d9f2-5a26-41b0-9ede-adc608fc7347.png)
Can u support me?

**Comment by nguyenhan-se** [comment]
@iconFehu i cloned new vben project and apply like https://github.com/vbenjs/vue-vben-admin/commit/f44183e77e8c8f00a21fe4697485c4b60595970e  but it's not working for me

**Comment by nguyenhan-se** [comment]
@iconFehu maybe i found the problem, the reason is "vite version 3.1.0"

**Comment by iconFehu** [comment]
@nguyenhan-se vite-plugin-theme v0.8.6 and vite v3.1.0 may not be compatible

**Comment by WangShayne** [comment]
@nguyenhan-se use vite 3.0.2

**Comment by cnzdq** [comment]
![image](https://user-images.githubusercontent.com/30411977/189054541-c0fee34a-70f2-4709-b2b3-14b1c5ddf8cc.png)

@iconFehu 我下了你的项目跑，虽然快了不少。但还是需要20s，不明白哪里不一样。你的是首次打开页面时的加载时间吗，就是从 pnpm dev 运行后第一次打开页面。首次加载完成之后，后面再刷新就很快了。我部署到云服务，不开启 gzip情况也是 15s，开启 gzip 后会快很多，大概3s

**Comment by haozileung** [comment]
> @iconFehu maybe i found the problem, the reason is "vite version 3.1.0"

More precisely, It's now working since vite 3.1.0-beta.1.

See https://github.com/vbenjs/vite-plugin-theme/issues/27

**Comment by yeyuliang2015** [comment]
@iconFehu 升级后，你们有出现国际化没有被翻译的问题吗？

**Comment by yeyuliang2015** [comment]
@iconFehu

<img width="255" alt="image" src="https://user-images.githubusercontent.com/10381702/190834854-516dab40-2aae-485a-855f-9bb2dffca158.png">

**Comment by yeyuliang2015** [comment]
解决了

**Comment by yeyuliang2015** [comment]
@iconFehu 升级到3.0.9版本打包后，页面出现空白现象，无法访问。

**Comment by dh13899396662** [comment]
> 
Thanks four your suggestion, it has been fixed.
Then when I first run yarn serve, the dashboard page spent 25s to load, it's still slow

**Comment by ma-lihui** [comment]
> 额...满怀期待升级了一下 但是特意加载对比了, 好像没什么明显的提升....

我升级后发现也依然很慢，后来发现是这个插件build/vite/plugin/styleImport.ts按需加载antd的样式非常耗时，作者之前做了优化，只在生产环境启用。后来不知道为啥又[注释](https://github.com/vbenjs/vue-vben-admin/commit/52257f061d95cf4a3b5a11e4a52c48774a6042be?diff=split#diff-53701deb171a9b0e8a5a2783abf431711b6ddd83b122bd6ef27a18e7f7e10e64)了。可以还原这两段代码试试
![image](https://user-images.githubusercontent.com/16605318/193236631-6ac0f798-074c-4691-89ec-82832cb39c1e.png)
![image](https://user-images.githubusercontent.com/16605318/193236721-db89f746-5dee-4582-983c-734c2016bb3e.png)

**Comment by mamba-in** [comment]
更新后比之前快了30多秒，现在首加载16s左右，虽然还是有点长，确实比之前快多了

yeyuliang2015 ***@***.***> 于2022年8月16日周二 11:10写道：

**Comment by qwerlp** [comment]
升级过程中报错 __COLOR_PLUGIN_OUTPUT_FILE_NAME__ is not defined请问这个怎么解决vite-plugin-theme

**Comment by fanzihui** [comment]
什么时候可以升级到vite3 啊

**Comment by M69W** [comment]
> 什么时候可以升级到vite3 啊

https://github.com/vbenjs/vue-vben-admin/blob/next/package.json#L3

**Comment by yeyuliang2015** [comment]
你们升级到vite3打包后，没有出现页面空白的现象吗？ @iconFehu

**Comment by qwerlp** [comment]
> 升级过程中报错 **COLOR_PLUGIN_OUTPUT_FILE_NAME** is not defined请问这个怎么解决vite-plugin-theme
这里有解决方案
https://github.com/vbenjs/vite-plugin-theme/issues/27#issuecomment-1304458370

**Comment by LuoHuacheng** [comment]
> > 额...满怀期待升级了一下 但是特意加载对比了, 好像没什么明显的提升....
> 
> 我升级后发现也依然很慢，后来发现是这个插件build/vite/plugin/styleImport.ts按需加载antd的样式非常耗时，作者之前做了优化，只在生产环境启用。后来不知道为啥又[注释](https://github.com/vbenjs/vue-vben-admin/commit/52257f061d95cf4a3b5a11e4a52c48774a6042be?diff=split#diff-53701deb171a9b0e8a5a2783abf431711b6ddd83b122bd6ef27a18e7f7e10e64)了。可以还原这两段代码试试 ![image](https://user-images.githubusercontent.com/16605318/193236631-6ac0f798-074c-4691-89ec-82832cb39c1e.png) ![image](https://user-images.githubusercontent.com/16605318/193236721-db89f746-5dee-4582-983c-734c2016bb3e.png)

这里注释的内容放在 `build/vite/plugin/theme` 里面的 `antdDarkThemePlugin` 方法 `preloadFiles` 参数中去了，我把vite升级到最新的4.1.4之后按照这个 [issue](https://github.com/vbenjs/vite-plugin-theme/issues/27#issuecomment-1304458370)添加全局变量后切换暗黑模式有问题，把注释的这两个地方还原然后把 `preloadFiles` 去掉了，可以正常运行。

**Comment by houyaowei** [comment]
@LuoHuacheng  在vite@4版本打包后能正常运行么？我这边打包后html文件中没有注入js文件

**Comment by houyaowei** [comment]
所以只能将到3.2.5版本

**Comment by huhyge** [comment]
> 



> 你们升级到vite3打包后，没有出现页面空白的现象吗？ @iconFehu

我在升级成vite3.0.x打包后也出现了同样的问题,请问您解决了嘛如何解决的

**Comment by houyaowei** [comment]
> > 
> 
> > 你们升级到vite3打包后，没有出现页面空白的现象吗？ @iconFehu
> 
> 我在升级成vite3.0.x打包后也出现了同样的问题,请问您解决了嘛如何解决的

我的是一个插件导致的，把插件去掉就可以了

**Comment by XiongAmao** [comment]
@houyaowei Hello，请教一下你们是去掉哪个插件解决白屏问题的？
