### ISSUE TITLE
手动从vben-admin-thin-next升级到vue-vben-admin后，BasicColumn中dataIndex不能使用"."符号了

### ISSUE THREAD

**Issue by c4ys** [vbenjs/vue-vben-admin#2162]
### 描述 Bug

在vben-admin-thin-next中，order table的columns定义可以使用`dataIndex: user.username`，会直接显示username。

手动文件对比，升级到vue-vben-admin后，发现不能这样用了。不知道我升级过程遗漏了什么？

### 升级前可以这样用

```
export const Columns: BasicColumn[] = [
  {
    title: '用户',
    dataIndex: 'user.username',
  }
]
```

### 升级后必须用format(format的text取不到值了)

```
export const Columns: BasicColumn[] = [
  {
    title: '用户',
    dataIndex: 'user.username',
    format: (_, record) => {
      return record.user.username';
    },
  }
]
```

建议：如果vben-admin-thin-next不能保持更新，建议去掉这个项目吧。

**Comment by VENI-VIDIVICI** [comment]
这是因为ant-design-vue   2 -> 3 的变更

**Comment by uncarbon97** [comment]
我自己也是后来升级了发现不支持了……
只能手动设置 render 事件，手动从结构体里取值了

**Comment by passioncsu** [comment]
支持 dataIndex: ['user', 'username'],
这样的写法了
