### ISSUE TITLE
后端返回的字段前后带有空格，table中空格被去除了

### ISSUE THREAD

**Issue by luojianxhlxt** [vbenjs/vue-vben-admin#2163]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

后端返回数据
``` JSON
[
    {
        "id": "1557580423817728000",
        "account": "sed ",
        "name": "她将代共合",
        "email": "v.dicupzuxr@qq.com",
        "phone": "18138703780",
        "roleList": [
            "超级管理员",
            "超级管理员",
            "操作员",
            "超级管理员"
        ],
        "roleNames": "超级管理员,超级管理员,操作员,超级管理员",
        "remark": " 123 123 2"
    }
]
```
，前端在account列显示为"sed"、前端的remark列显示"123 123 2"。字符串前面和尾部的空格被去除了

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:win10
- Node 版本:16.15.0
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm,7.9.0

**Comment by passioncsu** [comment]
可能有什么特殊优化吧  加个 
        customRender: ({ text }) => text,
应该就原始输出了
