### ISSUE TITLE
编辑表格里面要用要ApiSelect组件,  要根据查询条件请求数据

### ISSUE THREAD

**Issue by github-ZH-cn** [vbenjs/vue-vben-admin#2167]
查询出来数组怎么赋值到ApiSelect 里面
![7@6MU{)4BTD~1TBD86YQJ{U](https://user-images.githubusercontent.com/67533362/184347722-a78c5cc7-cf8c-46dd-a97b-2e21413781a1.png)

**Comment by silianpan** [comment]
```js
api: (info) =>
  getAccountList(info).then((res) => ({
    items: res.rows,
    total: res.total,
  })),
beforeFetch: (info: BasicPageParams) => {
  return {
    pageNum: info.page,
    pageSize: info.pageSize,
    ...getForm().getFieldsValue(),
  };
},
```

**Comment by github-ZH-cn** [comment]
这种的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vbenjs/vue-vben-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月13日(星期六) 晚上9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vbenjs/vue-vben-admin] 编辑表格里面要用要ApiSelect组件,  要根据查询条件请求数据 (Issue #2167)





 api: (info) =&gt;   getAccountList(info).then((res) =&gt; ({     items: res.rows,     total: res.total,   })), beforeFetch: (info: BasicPageParams) =&gt; {   return {     pageNum: info.page,     pageSize: info.pageSize,     ...getForm().getFieldsValue(),   }; },
