### ISSUE TITLE
项目跑不起来报错问题

### ISSUE THREAD

**Issue by fxzer** [vbenjs/vue-vben-admin#2174]
抱歉，遇到了一个错误。感谢您抽出宝贵的时间进行解答！
 

![image](https://user-images.githubusercontent.com/68853957/184588203-fd389ec7-544d-411d-b268-3d9082b1cf77.png)
![image](https://user-images.githubusercontent.com/68853957/184588582-3022a70d-8e4d-4c16-b3b1-75cbdd93bc26.png)
![image](https://user-images.githubusercontent.com/68853957/184588431-159acdb0-bbad-482b-8d2d-979cc9e87c92.png)

 
 
![image](https://user-images.githubusercontent.com/68853957/184588476-8f56c3e6-1148-4851-9129-088943a80a4e.png)

### Describe the bug
请问为什么我clone项目跑不起来呢，我来来回回安装删除了依赖好几遍，就是没跑起来项目??
我明明安装的是`ant-design-vue@3.2.11`，但是一直报错不存在，请问有没有大佬知道这是啥问题，求指教！

**Comment by zwtvip** [comment]
我是先clone下来后 先安装依赖，然后升级 pnpm update ant-design-vue 可以跑起来

**Comment by CoderFXJ** [comment]
非常感谢楼上的道友，管用！！！

**Comment by wx923** [comment]
请问，能给出为什么会这样的原因吗？
