### ISSUE TITLE
Table的searchForm里的select onChange事件调用formActionType.submit()失败

### ISSUE THREAD

**Issue by wangmin0314** [vbenjs/vue-vben-admin#2180]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

Table的searchForm里的select onChange事件调用formActionType.submit()失败
```js
{
    field: 'investType',
    label: '',
    component: 'Select',
    componentProps: ({ formActionType }) => ({
      allowClear: true,
      placeholder: '交易来源',
      options: allOptions.invest_type,
      onChange: () => {
        formActionType.submit();
      },
   }),
}
```
![image](https://user-images.githubusercontent.com/23734878/185334326-3d550285-9b35-4ade-b233-54481c531b38.png)

**Comment by Coder-wb** [comment]
需要自定义submitFunc

**Comment by banxia-999** [comment]
`
onChange: () => {
    nextTick(() => {
        formActionType.submit();
    });
},
`
亲测可用

**Comment by amu1433** [comment]
我也遇到这个问题....自定义submitFunc 不会自动提交搜索的表单...进入死循环
