### ISSUE TITLE
formTable（开启搜索区域），搜索表单为“收起”状态的时候，table切换分页会产生抖动。

### ISSUE THREAD

**Issue by RSS1102** [vbenjs/vue-vben-admin#2181]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已在 Issues 中搜索了相关的关键词
- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
formTable功能（开启搜索区域），搜索表单为“收起”状态的时候，table切换分页会产生抖动。（如从第一页切换到第二页的时候页面就会产生抖动）

### 复现 Bug
https://vvbin.cn/next/#/comp/table/formTable
官网demo即可呈现bug。（当搜索表单为“收起”的时候切换分页）

个人认为，是因为展开/收起默认值为`展开状态`，每次切换分页 的时候重新进行获取参数，致使页面产生抖动。
## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by wangmin0314** [comment]
当表单是收起状态的时候，reload table的时候会抖动

**Comment by RSS1102** [comment]
看到这里有一个pr:https://github.com/vbenjs/vue-vben-admin/pull/2125,是关于这个的。

**Comment by zhaowei2530** [comment]
> 看到这里有一个pr:#2125 ，是关于这个的。

pr:#2125 代码是否合并到main分支下，十一节前试了下还是会出现表单抖动问题？

**Comment by RSS1102** [comment]
> > 看到这里有一个pr:#2125 ，是关于这个的。
> 
> pr:#2125 代码是否合并到main分支下，十一节前试了下还是会出现表单抖动问题？

好像已经关闭了（并没有合并）。
@jinmao88 能否关注一下这个pr: https://github.com/vbenjs/vue-vben-admin/pull/2125 和bug的修复问题。

**Comment by jinmao88** [comment]
他自己close了

**Comment by RSS1102** [comment]
> 他自己close了



> 他自己close了
...   =_=
好吧，那我晚上试试能不能修一下。

**Comment by zhaowei2530** [comment]
> > 他自己close了
> 
> > 他自己close了
> > ...   =_=
> > 好吧，那我晚上试试能不能修一下。

表单查询抖动的问题解决了吗？我看最新的代码，收起状态查询还是抖了一抖

**Comment by RSS1102** [comment]
> > > 他自己close了
> > 
> > 
> > > 他自己close了
> > > ...   =_=
> > > 好吧，那我晚上试试能不能修一下。
> 
> 表单查询抖动的问题解决了吗？我看最新的代码，收起状态查询还是抖了一抖

=.=没搞定.........

**Comment by ElsaOOo** [comment]
> > > > 他自己close了
> > > 
> > > 
> > > > 他自己close了
> > > > ...   =_=
> > > > 好吧，那我晚上试试能不能修一下。
> > 
> > 
> > 表单查询抖动的问题解决了吗？我看最新的代码，收起状态查询还是抖了一抖
> 
> =.=没搞定.........

还是有这个问题

**Comment by RSS1102** [comment]
> > > > > 他自己close了
> > > > 
> > > > 
> > > > > 他自己close了
> > > > > ...   =_=
> > > > > 好吧，那我晚上试试能不能修一下。
> > > 
> > > 
> > > 表单查询抖动的问题解决了吗？我看最新的代码，收起状态查询还是抖了一抖
> > 
> > 
> > =.=没搞定.........
> 
> 还是有这个问题
你看下这个：https://github.com/vbenjs/vue-vben-admin/commit/58b30aae9a1d749fdbeaca4f1310059a7cc96db2

**Comment by ElsaOOo** [comment]
> 

哦哦，看到啦
