### ISSUE TITLE
官网demo，前端权限管理，从super切换到test后刷新页面会回到super权限。

### ISSUE THREAD

**Issue by yolo815815** [vbenjs/vue-vben-admin#2185]
### 描述 Bug

官网前端权限demo中，从super切换到test后，刷新页面会回到super权限。但实际应该还是test权限。

**Comment by M69W** [comment]
可能是因为没有真实的后台，只是mock 临时数据而已吧？

**Comment by leedawn** [comment]
这个不是 bug，刷新后就会请求到默认的 super 角色
