### ISSUE TITLE
以params形式传参会有问题

### ISSUE THREAD

**Issue by karainsun** [vbenjs/vue-vben-admin#2190]
### 描述 Bug

当没有config.data的情况下，以下代码会将params设置为undefined，导致参数传不到后台
`
 // 非GET请求如果没有提供data，则将params视为data
  config.data = params;
  config.params = undefined;
`
在文件120行
[http/axios/index.ts](https://github.com/vbenjs/vue-vben-admin/blob/main/src/utils/http/axios/index.ts)

**Comment by mynetfan** [comment]
非GET请求时提供非空data参数就可以使params参数有效了。这里的注释我写的，但逻辑并非我写的。我猜测原本作者的想法是想让无论GET还是POST都使用params传递要提交的数据。
