### ISSUE TITLE
官网演示项目放置一定时间后，再点击无任何响应

### ISSUE THREAD

**Issue by kangweiming1996** [vbenjs/vue-vben-admin#2195]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
https://vvbin.cn/next/#/dashboard/analysis
官网演示项目放置一定时间后，再点击无任何响应

### 复现 Bug
点击无任何响应，F12控制台js报错

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by mynetfan** [comment]
放置的这段时间内项目有commit被推送，就会触发构建任务，文件的hash会改变，旧的文件就会被删掉
