### ISSUE TITLE
根据getMenuList动态设置BASE_HOME

### ISSUE THREAD

**Issue by fanhoucheng** [vbenjs/vue-vben-admin#2200]
### Subject of the feature

动态设置BASE_HOME
### Problem

#361

### Expected behaviour
权限管理中BASE_HOME有可能某用户并不拥有该权限，所以是不是可以动态设置BASE_HOME

比如使用后台权限管理，根据getMenuList结果中某个参数动态设置BASE_HOME，meta？？？
前台权限管理的话，根据其他什么决定？

**Comment by acdxxx177** [comment]
在获取后端用户信息的时候，后端传过来有个homePath参数，可以根据这个参数动态调整每个用户的首页
示列里的vben和test的首页就是不同的
