### ISSUE TITLE
导航模式：顶部导航混合模式应该是头部一级目录，左侧为子菜单的模式。

### ISSUE THREAD

**Issue by lm356536** [vbenjs/vue-vben-admin#2214]
<img width="968" alt="image" src="https://user-images.githubusercontent.com/20919577/188856263-50f0b5d6-32c0-4ecc-baeb-de64b9c66362.png">

**Comment by mynetfan** [comment]
![image](https://user-images.githubusercontent.com/17241274/198494583-1032707f-d83b-4206-81a1-31cb57357bef.png)
打开如图所示配置项才是你想要的布局
