### ISSUE TITLE
mac安装pnpm后，运行pnpm serve报错跑不起来

### ISSUE THREAD

**Issue by feader** [vbenjs/vue-vben-admin#2215]

**Comment by feader** [comment]
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/22908871/188877006-f614299d-79b7-4147-98d7-58ebf55d0c94.png">
node是v16.12.0
pnpm是6.7.6
有参照网上说的一些情况，调整过package.json，如下图所示
<img width="803" alt="image" src="https://user-images.githubusercontent.com/22908871/188877380-63688ec0-909e-4a2a-a3bf-883e2aa82200.png">
新手入坑，请教各位大佬帮忙一下，感谢！

**Comment by shencong12** [comment]
试试 run serve呢

**Comment by feader** [comment]
参考其他issues提到的安装ant-design-vue问题，别人是跑pnpm update ant-design-vue后可以，我这边是跑pnpm install ant-design-vue让它自己更新ant-design-vue库版本后问题解决
