### ISSUE TITLE
首次进入页面和第一次切换菜单时加载很慢

### ISSUE THREAD

**Issue by janly-li** [vbenjs/vue-vben-admin#2216]
首次进入页面时和第一次切换菜单时加载很慢

**Comment by janly-li** [comment]
![image](https://user-images.githubusercontent.com/56383656/189076037-69681797-ce57-4a22-a207-262e5c3b2670.png

**Comment by liuzongyang255** [comment]
vite开发模式 了解一下

**Comment by liuzongyang255** [comment]
为了光速启动项目  按需加载组件  所以会慢  开发的时候不需要编译整个项目  有时候只需要修改某个菜单  所以打开项目  进入菜单   就OK了

**Comment by janly-li** [comment]
> 为了光速启动项目 按需加载组件 所以会慢 开发的时候不需要编译整个项目 有时候只需要修改某个菜单 所以打开项目 进入菜单 就OK了

不止是开发模式，生产环境也很慢

**Comment by liuzongyang255** [comment]
你看看官方的预览地址，那个速度就是正常的，更高的速度取决于网速、服务器速度

**Comment by dzhl** [comment]
确实挺慢，本地搭建，不存在网速问题，启动也慢，官网也慢，虽然这个框架上手难，不过我喜欢

**Comment by gaojiangtao-git** [comment]
升级到vite3  会有很大的提升

**Comment by zhangyuanliang** [comment]
这样修改可以提升10秒时间
`
main.ts
import Antd from 'ant-design-vue';
import 'ant-design-vue/dist/antd.css';

app.use(Antd).mount('#app');

build/vite/plugin/index.ts
vite-plugin-style-import注释掉
`
