### ISSUE TITLE
项目封装

### ISSUE THREAD

**Issue by liuzongyang255** [vbenjs/vue-vben-admin#2218]
### Subject of the feature

因为有N多子项目拟改造，或者后面有很多新项目想用这个框架，所以想要把整个项目封装一下，后期有什么改动只需要修改封装的组件，publish到私服，请问有什么思路和注意事项吗？

**Comment by coderwyd** [comment]
> ### Subject of the feature
> 
> 因为有N多子项目拟改造，或者后面有很多新项目想用这个框架，所以想要把整个项目封装一下，后期有什么改动只需要修改封装的组件，publish到私服，请问有什么思路和注意事项吗？

等vben3.x的版本吧，文件目录大更新，会修改为monorepo方式管理
