### ISSUE TITLE
配合弹框模式无效

### ISSUE THREAD

**Issue by zqx-git** [vbenjs/vue-vben-admin#2225]
配合弹框模式无效

_Originally posted by @accpman in https://github.com/vbenjs/vue-vben-admin/issues/807#issuecomment-918094174_

表单弹框时，配置useForm({fieldMapToTime})无效，未解构。

**Comment by zqx-git** [comment]
![image](https://user-images.githubusercontent.com/44970684/189861811-28c957f8-7218-4504-889a-752137b34860.png)
![image](https://user-images.githubusercontent.com/44970684/189861924-09c2370a-6a63-45ac-a0cc-65cd4fc6216f.png)

**Comment by HoboCY** [comment]
这个问题怎么解决的，我也遇到了

**Comment by wangjue666** [comment]
> 这个问题怎么解决的，我也遇到了

这块的代码拷贝下，新版本正常的

**Comment by HoboCY** [comment]
> > 这个问题怎么解决的，我也遇到了
> 
> 这块的代码拷贝下，新版本正常的

谢谢，新版本解决了，我当时用的是thin项目，才发现那个很久没更新了
