### ISSUE TITLE
找不到相关资源文件

### ISSUE THREAD

**Issue by jianqi-liu0874** [vbenjs/vue-vben-admin#2231]
测试人员停留在上个系统版本，我重新发布一个新版本覆盖上一个版本的资源文件，这时测试人员点击以前没有访问过的页面，就会报错找不到相关的资源文件。原因是vite打包后js相关文件较细，进入新页面的时候需要加载服务器资源，此时上个版本的资源已经替换成新版本的资源，所以找不到资源文件。请问这种情况有什么好的办法解决吗？

**Comment by zieru** [comment]
Failed to fetch dynamatically imported module ?

**Comment by ChungQ-make** [comment]
https://www.v2ex.com/t/855521
