### ISSUE TITLE
使用setFieldsValue给select赋值，传的是int类型，赋值后是varchar类型。

### ISSUE THREAD

**Issue by wphubs** [vbenjs/vue-vben-admin#2239]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

select组件value是number类型，使用setFieldsValue赋值传的是int类型，实际赋值的是varchar类型，导致无法默认选项

### Reproduction
```
    setFieldsValue({
          addressId: 8,  //实际赋值  '8'
     });
```

**Comment by wangmin0314** [comment]
解决了吗？

**Comment by wphubs** [comment]
> 解决了吗？

BUG没解决，换了个方式，绑定时手动转成varchar了

**Comment by anncwb** [comment]
Hello @wphubs. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by likui628** [comment]
最新版本上没发现这个问题
![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/e60a64b0-4741-40f9-8512-da7f98af3c5d)
![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/5895d22f-c95b-4efa-af09-bebae963bb2d)
