### ISSUE TITLE
Upload组件开发环境跟发布环境表现不一致

### ISSUE THREAD

**Issue by liuhuanghui** [vbenjs/vue-vben-admin#2245]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

开发环境能上传文件，发布环境编译后无法上传

### 复现 Bug

Demo里面的upload上传组件可以复现
![1665129665476](https://user-images.githubusercontent.com/18409590/194503919-d1bd2579-22bf-4469-9281-c40dee3c9e33.jpg)
https://vvbin.cn/next/#/comp/upload

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by flywin8** [comment]
发现同样的问题

**Comment by CoraLi1** [comment]
我碰到的问题是，开发环境没问题；服务器上，上传成功，点击保存，弹窗虽然关了，但是蒙层还在，导致页面点击不了。

**Comment by lrwhtp377** [comment]
在 `.env.production`  文件里面将发布环境的mock关闭就行了 VITE_USE_MOCK 设为false

**Comment by 949387017** [comment]
@CoraLi1 你好，请问是如何解决的，我也遇到这个问题

**Comment by guohui666** [comment]
经过debug后发现错误为
`re.upload.addEventListener in not a function。`

[搜索问题](https://www.cnblogs.com/leeke98/p/10491358.html)

后面将正式环境VITE_USE_MOCK设置为false解决了
