### ISSUE TITLE
Uncaught ReferenceError: __COLOR_PLUGIN_OUTPUT_FILE_NAME__ is not defined

### ISSUE THREAD

**Issue by fanhoucheng** [vbenjs/vue-vben-admin#2252]
### 描述 Bug
npm run dev后，打开网页出现如下错误，以至于应用无法正常
client.js:5 Uncaught ReferenceError: __COLOR_PLUGIN_OUTPUT_FILE_NAME__ is not defined
    at client.js:5:35

### 复现 Bug

修改package.json,升级 "vite": "^2.9.5",  到  "vite": "^3.1.0",及以上

## 系统信息

- 操作系统:windows11
- Node 版本:v16.16.0
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm7.13.3

**Comment by jinmao88** [comment]
不要升级 很多问题

**Comment by qwerlp** [comment]
请问有没有解决，我发现是这个变量COLOR_PLUGIN_OUTPUT_FILE_NAME是vite-plugin-theme这插件里面的

**Comment by TonyLuo** [comment]
建议少用自定义的插件，吃力不讨好

**Comment by dh13899396662** [comment]
这问题解决了吗
