### ISSUE TITLE
useTable组件setColumns和setTableData之后数据和表头确实刷新了，但是tableSetting里面的字段列表没有更新（请看我的截图）

### ISSUE THREAD

**Issue by yeyuchen198** [vbenjs/vue-vben-admin#2257]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

useTable组件setColumns和setTableData之后数据和表头确实刷新了，但是tableSetting里面的字段列表并没有更新（请看我的截图）
我用另1种方法来更新数据和表头，还是一样
setProps({
          dataSource: myDataSource,
          columns: myColumns,
}）
我不知道这是个bug还是我缺少了某些设置？希望大佬们有时间帮忙看看
![1665379062977_0397B7AA-B666-4fe0-98C0-77B9F4CACBFE](https://user-images.githubusercontent.com/89305403/194819526-3e7ef307-b4e2-4403-acbd-e08a47707b07.png)

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统: Windows 10 64位
- Node 版本: node -v=16.17.1
- 包管理器 (npm/yarn/pnpm) 及其版本: npm -v=8.19.2，pnpm -v=7.13.2

**Comment by qwerlp** [comment]
请问有解决吗，我也碰到了类似的问题

**Comment by yeyuchen198** [comment]
> 请问有解决吗，我也碰到了类似的问题

还没有。。实在不行就不显示设置好了，还是直接打开Excel来筛选编辑数据吧

**Comment by datangkang123** [comment]
一样的问题，已经提出半年多了，目前无法我解决

**Comment by yinbiao** [comment]
在ColumnSetting.vue文件中，在监听columns对象中，将columns变量定义在setTimeout外面，就可以自动更新了。
watchEffect(() => {
        const columns = table.getColumns();
        setTimeout(() => {
          // const columns = table.getColumns();
          if (columns.length && !state.isInit) {
            init();
          }
        }, 0);
      });

**Comment by Winter-L** [comment]
> 请问有解决吗，我也碰到了类似的问题

我在useColums.ts里新增了个setCacheColumns的方法，对cacheColumns做了个刷新，暂时解决了

**Comment by LuoHuacheng** [comment]
> > 请问有解决吗，我也碰到了类似的问题
> 
> 我在useColums.ts里新增了个setCacheColumns的方法，对cacheColumns做了个刷新，暂时解决了

你好，请问可以贴一下代码参考一下吗？我也遇到这个问题了。

**Comment by quanbisen** [comment]
> setCacheColumns

你好，请问一下具体是怎么解决的，在哪个位置加哪些代码？刚学这个项目做需求，不太了解。

**Comment by quanbisen** [comment]
我好像解决了这个问题，因为ColumnSetting里的watchEffect监听表格列的数据不生效，导致没有成功设置cacheColumn变量，看我的[merge_request](https://github.com/vbenjs/vue-vben-admin/pull/2599/files)

**Comment by yeyuchen198** [comment]
我这边测试了一下，确实解决了这个问题，感谢大佬！！
不过还是有个小问题，只能解决第1次的数据加载字段不显示问题，第二次如果用不同字段的数据，列设置里面还是显示第一次的字段，比如我有个页面是做JSON解析的，每次JSON的字段可能都不一样，这样只能解析一次JSON刷新一下页面

**Comment by yeyuchen198** [comment]
> 我这边测试了一下，确实解决了这个问题，感谢大佬！！
> 不过还是有个小问题，只能解决第1次的数据加载字段不显示问题，第二次如果用不同字段的数据，列设置里面还是显示第一次的字段，比如我有个页面是做JSON解析的，每次JSON的字段可能都不一样，这样只能解析一次JSON刷新一下页面

我这边测试了一下，确实解决了这个问题，感谢大佬！！
不过还是有个小问题，只能解决第1次的数据加载字段不显示问题，第二次如果用不同字段的数据，列设置里面还是显示第一次的字段，比如我有个页面是做JSON解析的，每次JSON的字段可能都不一样，这样只能解析一次JSON刷新一下页面

**Comment by yeyuchen198** [comment]
> 我好像解决了这个问题，因为ColumnSetting里的watchEffect监听表格列的数据不生效，导致没有成功设置cacheColumn变量，看我的[merge_request](https://github.com/vbenjs/vue-vben-admin/pull/2599/files)

我这边测试了一下，确实解决了这个问题，感谢大佬！！
不过还是有个小问题，只能解决第1次的数据加载字段不显示问题，第二次如果用不同字段的数据，列设置里面还是显示第一次的字段，比如我有个页面是做JSON解析的，每次JSON的字段可能都不一样，这样只能解析一次JSON刷新一下页面

**Comment by quanbisen** [comment]
> > 我好像解决了这个问题，因为ColumnSetting里的watchEffect监听表格列的数据不生效，导致没有成功设置cacheColumn变量，看我的[merge_request](https://github.com/vbenjs/vue-vben-admin/pull/2599/files)
> 
> 我这边测试了一下，确实解决了这个问题，感谢大佬！！ 不过还是有个小问题，只能解决第1次的数据加载字段不显示问题，第二次如果用不同字段的数据，列设置里面还是显示第一次的字段，比如我有个页面是做JSON解析的，每次JSON的字段可能都不一样，这样只能解析一次JSON刷新一下页面

你这个问题，看源码可以知道，详见`src\components\Table\src\components\settings\ColumnSetting.vue`的
```
watchEffect(() => {
      const columns = table.getColumns();
      setTimeout(() => {
        if (columns.length && !state.isInit) {
          init();
        }
      }, 0);
    });
```
这里的init初始化只初始化了一次，后面columns变化了，也不会执行init方法，为什么这么写，作者那边应该是有他的考虑。如果你只是实现你的需求，可以尝试把这个!state.isInit的条件去掉吧。

**Comment by GauharChan** [comment]
#2745 已经修复
