### ISSUE TITLE
节日主题

### ISSUE THREAD

**Issue by Suomm** [vbenjs/vue-vben-admin#2258]
国庆节红红火火，国祭日无色调……

**Comment by wphubs** [comment]
有个哀悼日模式，不过感觉没啥用途，后台管理又不是那些社交平台，没啥必要

**Comment by huangwenboha563** [comment]
> 有个哀悼日模式，不过感觉没啥用途，后台管理又不是那些社交平台，没啥必要

确实是，但是如果是政务平台、医院、公检法、铁路、大型国企、供应链等（就是一切对公项目）有这个主题的话，确实感觉很高大上

**Comment by Suomm** [comment]
> > 有个哀悼日模式，不过感觉没啥用途，后台管理又不是那些社交平台，没啥必要
> 
> 确实是，但是如果是政务平台、医院、公检法、铁路、大型国企、供应链等（就是一切对公项目）有这个主题的话，确实感觉很高大上

也只有灰色模式比较明显。
