### ISSUE TITLE
希望能够增加二级菜单默认展开配置

### ISSUE THREAD

**Issue by linjiade627** [vbenjs/vue-vben-admin#2263]
我希望能自定义某些或者所有一级菜单项下的二级菜单默认就处于展开状态。
我看ant-design-vue 里的menu组件可以为菜单项配置key，然后通过设置属性openKeys可以实现这个目的，但是在查阅vben官方文档以及读了Vben里封装的组件BasicMenu.vue的代码后，我还是没能找到要如何做才能达到同样的效果。希望懂行的大佬指点一二！！

**Comment by li88qq** [comment]
直接处理一级菜单的reidirect属性为需要展开的路由。默认为第一个子菜单的路由就好。如果多级，可以递归处理。
