### ISSUE TITLE
级联选择器设置默认值时，希望可直接选中指定项，且获取焦点时直接展开对应选中

### ISSUE THREAD

**Issue by 742087271** [vbenjs/vue-vben-admin#2267]
现在效果：未展示选中项目
![image](https://user-images.githubusercontent.com/51225616/195074798-247bf848-f20d-4723-887d-579df5d8be4f.png)

预期效果：点击输入框直接展示对应的选中条目
![image](https://user-images.githubusercontent.com/51225616/195074458-788b34d3-f5a0-4785-8388-e78d266e78e4.png)

**Comment by mynetfan** [comment]
例子中是动态加载的选项，展开后才会加载下一级。在表单初始化时，默认选中项的数据尚未加载，不能选中。如需默认选中，不要使用动态加载级联选项
