### ISSUE TITLE
生产环境下Tab页空白

### ISSUE THREAD

**Issue by Suomm** [vbenjs/vue-vben-admin#2270]
### 描述 Bug

![image](https://user-images.githubusercontent.com/27558987/195252617-50e1c6ef-2379-4fcf-9453-744f4ddf43ce.png)
![image](https://user-images.githubusercontent.com/27558987/195252764-6e8ada98-6f0c-40f1-ad2e-953cd41f9978.png)

### 复现 Bug

测试环境没有任何问题，点击菜单显示路由界面。生产环境下点击菜单，Tab页空白。

**Comment by Suomm** [comment]
而且测试环境（pnpm run dev）的时候首页是不可以关闭的（没有后面的x），为什么到了生产环境（pnpm run build）首页就可以关闭了呢？

**Comment by anncwb** [comment]
Hello @Suomm. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by Mr-LiuDC** [comment]
这个问题好像还在，我也遇到了。
我在列表页的详情按钮上加了保存到 LocalStorage 的操作，自己本地调试 “顾客资料”和“就诊记录”不管怎样切换都没问题，编译发布到生产环境后只有初次渲染界面正常，后面从就诊记录切回到顾客资料时，顾客资料就不显示了。
<img width="484" alt="1686191114764" src="https://github.com/vbenjs/vue-vben-admin/assets/18117854/42bd35b6-83a2-434d-a01b-bd1dfa214245">

```
function handleView(record: Recordable) {
  customerStore.setCustomerDetail(CUSTOMER_INFO_KEY, record);
  go({
    // @ts-ignore
    name: 'CustomerDetail',
    query: { id: record.id },
    params: record,
  });
}



<template #footer>
  <a-tabs default-active-key="details" v-model:activeKey="currentTab">
    <a-tab-pane key="details" tab="顾客资料" />
    <a-tab-pane key="medicalPlans" tab="就诊记录" />
  </a-tabs>
</template>
<div class="m-1 pt-0">
  <template v-if="currentTab === 'details'">
    <Description @register="userDetailRegister" />
  </template>
  <template v-if="currentTab === 'medicalPlans'">
    <div v-for="i in 10" :key="i">这是顾客 {{ data.name }} 就诊记录</div>
  </template>
</div>





// 详情页面数据从 LocalStorage 获取
const data = customerStore.getCustomerDetail(CUSTOMER_INFO_KEY);
if (isEmpty(data)) {
  notification.error({
    duration: 5,
    message: t('sys.api.dataExpired'),
    onClose: () => {
      go('/membership/customer');
    },
  });
}
```
