### ISSUE TITLE
完整版的站点挂掉了

### ISSUE THREAD

**Issue by TrancyAlois** [vbenjs/vue-vben-admin#2273]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

地址：https://vvbin.cn/next/

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by M69W** [comment]
可能是改了配置
https://github.com/vbenjs/vue-vben-admin/commit/1a8cdeb374202319a53450c78d96bc7d3eedffcf

**Comment by miaobowei** [comment]
快修复把 急着用呢

**Comment by MochiFairyhood** [comment]
自己pull下，然后本地启动把

**Comment by chensy1998** [comment]
> 自己pull下，然后本地启动把

包括文档也gg了，开发进度直接停滞。

**Comment by liujianchao1995** [comment]
现在文档也挂了

**Comment by liujianchao1995** [comment]
完整版站点地址被改成 http://vben.mufei88.com/#/dashboard/analysis 了
