### ISSUE TITLE
vben官方文档已经挂掉

### ISSUE THREAD

**Issue by chensy1998** [vbenjs/vue-vben-admin#2275]
- 如果github.io的模式不太稳定，能否提供文档的开源代码，无法查询文档对二次开发的影响是非常大的。
- 例如element ui就也是使用github.io部署，404和加载慢已经是常态，这实在不是一个很成熟的部署方案。

**Comment by liujianchao1995** [comment]
昨天只是完整版预览站点挂掉了，今天连文档都挂了。。。

**Comment by webxiu** [comment]
估计是不想开源了, 故意这么干

**Comment by mayuanyuancode** [comment]
介斯要干嘛

**Comment by NortonLee** [comment]
作者也不出来解释一下子

**Comment by qiaochangwei** [comment]
https://vbenjs.github.io/vue-vben-admin-doc/  新的文档地址

**Comment by NortonLee** [comment]
> https://vbenjs.github.io/vue-vben-admin-doc/ 新的临时文档地址

优秀

**Comment by vintonHuang** [comment]
在线的示例文档也已经挂掉了
