### ISSUE TITLE
'vite' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by marshall-li** [vbenjs/vue-vben-admin#2276]
> vben-admin@2.8.0 serve D:\vue3-vben\vue-vben-admin
> npm run dev

> vben-admin@2.8.0 dev
> vite

'vite' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
 ELIFECYCLE  Command failed with exit code 1.

**Comment by NortonLee** [comment]
要不先把vite依赖安装一下试试

**Comment by mynetfan** [comment]
这是你的本地环境配置问题，请查阅相关资料自行解决
