### ISSUE TITLE
👍👍👍最新的官网地址

### ISSUE THREAD

**Issue by sunpm** [vbenjs/vue-vben-admin#2277]
具体的commit在https://github.com/vbenjs/vue-vben-admin-doc/commit/be78712297f4d6fa3690f2a476eddf2b03d9ba65

完整版源码：https://github.com/vbenjs/vue-vben-admin
完整版预览：http://vben.mufei88.com/#/dashboard/analysis
精简版预览：https://vvbin.cn/thin/next
精简版源码：https://github.com/vbenjs/vben-admin-thin-next
文档源码：https://github.com/vbenjs/vue-vben-admin-doc

文档地址：https://vbenjs.github.io/vue-vben-admin-doc/

**Comment by vintonHuang** [comment]
在线示例的完整版文档挂了，目前好像还没有修复哦

**Comment by sunpm** [comment]
> 在线示例的完整版文档挂了，目前好像还没有修复哦

哪个链接呢，我看了都可以访问呢

**Comment by xietongjian** [comment]
换网址了
