### ISSUE TITLE
表单验证-自定义校验会执行两次

### ISSUE THREAD

**Issue by jueying** [vbenjs/vue-vben-admin#2279]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

使用官网测试：

![image](https://user-images.githubusercontent.com/2921679/195573686-4fd70b09-450f-4a93-b276-46f90b95d0b9.png)

**Comment by An0nymous0** [comment]
如何处理的
