### ISSUE TITLE
生产环境打包的时候，生成的文件名，hash值每次都不一样

### ISSUE THREAD

**Issue by astonishqft** [vbenjs/vue-vben-admin#2292]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

使用vben在每次打包的时候，生成的文件名的hash值每次都不一样，rollup默认应该是根据文件内容生成的hash值，也就是说文件内容如果不变的话hash值不变才对，这样才能充分利用浏览器的缓存机制，我自己使用vite3+vue3模板工程测试的时候发现如果文件内容没有变化，hash值应该是不变的。

**第一次打包**
<img width="349" alt="image" src="https://user-images.githubusercontent.com/15138753/196360357-c540758b-2d09-4eda-b8b4-f5fca2877f31.png">

**文件内容没有任何变化，重新打包**
<img width="319" alt="image" src="https://user-images.githubusercontent.com/15138753/196360358-a8970594-02ac-4b7b-a6cc-ebb674cf22a2.png">

### 复现 Bug

使用的是vue-vben-admin的模板工程

## 系统信息

- 操作系统: macos
- Node 版本:  v14.19.0
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 7.1.0

**Comment by anncwb** [comment]
Hello @astonishqft. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by likui628** [comment]
新版本上未发现
