### ISSUE TITLE
导航栏模式能否增加顶部加左侧布局

### ISSUE THREAD

**Issue by MrQiaoLei** [vbenjs/vue-vben-admin#2293]
意思顶部显示系统名称，左侧显示具体菜单。可以理解为一个大系统里有多个小系统，顶部用于切换系统，左侧用于显示各系统菜单

**Comment by xietongjian** [comment]
这个想法不错。支持

**Comment by mynetfan** [comment]
demo已经有了。
![image](https://user-images.githubusercontent.com/17241274/198753392-3a4b920b-46b7-4f56-b15d-c20f3112ed89.png)

**Comment by xietongjian** [comment]
感谢您的来信，您的来信我会及时回复
有事请致电13510419502 或QQ583110978联系
姓名：谢桐健 
联系方式：手机13510419502  QQ583110978 
中级软件工程师，系统架构师，网站网页设计工程师
有意者请致电话或QQ联系
