### ISSUE TITLE
Table分页修改问题

### ISSUE THREAD

**Issue by Inaisen** [vbenjs/vue-vben-admin#2299]
大佬，如何我后端返回的数据是
![image](https://user-images.githubusercontent.com/39794731/196890490-f88c94a3-60ae-4179-8813-4ca9758b3a09.png)
这样的格式，我要如何修改才能让分页正常显示？

**Comment by wanglei520** [comment]
做数据模型转换，调用后端接口外再套一层，对数据进行处理成table组件想要的数据结构！！

**Comment by FallstarWing** [comment]
返回格式类似于这样的格式
{
    "success": true,
    "code": 0,
    "message":""
    "result": {
        "total": 1149,
        "items": [
            {}
        ]
    },
}
