### ISSUE TITLE
useTable配置afterFetch拿不到接口数据

### ISSUE THREAD

**Issue by yang-xianzhu** [vbenjs/vue-vben-admin#2300]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ✅] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [❌ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ✅] 已在 Issues 中搜索了相关的关键词
- [✅ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
useTable中配置afterFetch拿不到接口返回的数据

### 复现 Bug
```vue
afterFetch:(data)=>{
 console.log(data) // undefined
}

```
## 系统信息
64位

- 操作系统:windows 11专业版
- Node 版本: 
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm

**Comment by yang-xianzhu** [comment]
接口返回字段跟配置时的字段不一样afterFetch就无法返回接口数据

**Comment by mynetfan** [comment]
> 接口返回字段跟配置时的字段不一样afterFetch就无法返回接口数据

afterFetch的设计初衷就是如此

**Comment by ITt-mac** [comment]
在componentSetting文件里配置好表格的fetchSetting值，返回后就能拿到了~具体原因可以看下useDataSource里的判断实现

**Comment by Jzow** [comment]
请问现在实现了吗
