### ISSUE TITLE
外链页面新窗口问题

### ISSUE THREAD

**Issue by hulu20** [vbenjs/vue-vben-admin#2301]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [✅] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [✅] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [✅] 已在 Issues 中搜索了相关的关键词
- [✅] 不是 ant design vue 组件库的 Bug

### 描述 Bug

不确定是否为bug,  测试外链路由时，点击打开的为当前新页面，不是新开窗口(target: _blank) 模式

### 复现 Bug

创建外链页面路由即可复现

### 系统信息

操作系统:windows 11专业版x64
Node 版本:
包管理器 (npm/yarn/pnpm) 及其版本: pnpm

## 解决方法
src\utils\index.ts --> openWindow function --> __blank 改为 _blank

const { target = '__blank', noopener = true, noreferrer = true } = opt || {};
改为
const { target = '_blank', noopener = true, noreferrer = true } = opt || {};

**Comment by yeyuchen198** [comment]
借楼，我也发现一个路由外链问题。在某个路由ts文件里面，
外链问题：
设置path: 'https://tb.xxx.com/#/tools', 可以打开；
设置path: 'https://tb.xxx.com/#/tools/', 不可以打开
设置path: 'https://tb.xxx.com/#/tools/1', 不可以打开

**Comment by hulu20** [comment]
试试这个正则 - src\utils\is.ts
  const reg =
    /^(http(s)?:\/\/(www\.)?)[a-zA-Z0-9]+([\-\.]{1}[a-zA-Z0-9]+)*\.[a-zA-Z]{2,5}(:[0-9]{1,5})?(\/.*)?$/;

**Comment by hulu20** [comment]
> 借楼，我也发现一个路由外链问题。在某个路由ts文件里面， 外链问题： 设置path: 'https://tb.xxx.com/#/tools', 可以打开； 设置path: 'https://tb.xxx.com/#/tools/', 不可以打开 设置path: 'https://tb.xxx.com/#/tools/1', 不可以打开

试试这个正则 - src\utils\is.ts
const reg =
/^(http(s)?://(www.)?)[a-zA-Z0-9]+([-.]{1}[a-zA-Z0-9]+).[a-zA-Z]{2,5}(:[0-9]{1,5})?(/.)?$/;

**Comment by mynetfan** [comment]
> 借楼，我也发现一个路由外链问题。在某个路由ts文件里面， 外链问题： 设置path: 'https://tb.xxx.com/#/tools', 可以打开； 设置path: 'https://tb.xxx.com/#/tools/', 不可以打开 设置path: 'https://tb.xxx.com/#/tools/1', 不可以打开

fixed:https://github.com/vbenjs/vue-vben-admin/commit/513ccb954317c9cbe2d1697cbeb0720669496781
