### ISSUE TITLE
表单中点击重置按钮时，自定义组件ApiTree没有重置回初始状态

### ISSUE THREAD

**Issue by MissLiu34** [vbenjs/vue-vben-admin#2307]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/9619604/197677809-546cb0bc-cb42-4c9f-9780-a63a531440a9.png">

选中远程Tree的某个选项，然后点击重置按钮，发现自定义组件ApiTree没有重置回初始状态，之前选中的“选项0-0”仍然是勾选状态。

使用的官方demo ，版本号最新。

**Comment by mynetfan** [comment]
这个组件尚不完整，请暂时不要使用。
