### ISSUE TITLE
表格开启搜索区域伸缩问题

### ISSUE THREAD

**Issue by nekomata05** [vbenjs/vue-vben-admin#2313]
⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x]  确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

描述 Bug
表格开启搜索区域，进入页面加载第一次，搜索区域第一时间没有隐藏，导致页面会产生抖动*

复现 Bug
官网demo能复现出问题

**Comment by wangjue666** [comment]
最新版本已修复这个问题
