### ISSUE TITLE
Modal组件的全局样式导致Ant的Modal组件样式被更改

### ISSUE THREAD

**Issue by lvzhenbo** [vbenjs/vue-vben-admin#2330]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

当vben的Modal和Ant 的Modal一起使用时，Ant的Modal的样式会被vben更改，根据分析是因为使用了全局样式

### 复现 Bug

我想应该不需要，这不应该使用全局样式

## 系统信息

- 操作系统:win10
- Node 版本:16
- 包管理器 (npm/yarn/pnpm) 及其版本:npm8

**Comment by wangjue666** [comment]
这个问题在`2.10.1`版本得到了修复
