### ISSUE TITLE
FormSchema里面怎么对某个单独的input进行设置字体属性

### ISSUE THREAD

**Issue by bieshaoxiong** [vbenjs/vue-vben-admin#2331]
FormSchema里面怎么对某个单独的input进行设置字体属性
![image](https://user-images.githubusercontent.com/64937534/200233728-6c7faed7-1f5a-43a8-bb0e-85afb251eb90.png)
这样设置不生效

**Comment by yang-xianzhu** [comment]
写个render

**Comment by johnshi** [comment]
应该写在componentProps这个里面吧。
    componentProps: {
      style: 'font-size: 1.25rem; line-height: 1.75rem; font-weight: 700',
    },

**Comment by bieshaoxiong** [comment]
感谢大家，最后我用css实现了
<style lang="less" scoped>
  :deep(#form_item_code) {
    color: red;
    font-weight: bold;
  }
</style>
