### ISSUE TITLE
在form里面使用ApiTransfer

### ISSUE THREAD

**Issue by ddd-x** [vbenjs/vue-vben-admin#2333]
在表单里面使用了ApiTransfer组件，这个表单在modal里面，操作了穿梭框后，关闭modal页面会记住对穿梭框之前的操作，没法清空（表单值是重置了的），重新给表单项赋值 穿梭框页面也不会变，还是上一次操作后的样子。求解~

**Comment by wangjue666** [comment]
`modal`组件打开后再关闭还是会缓存组件的内容，给 modal组件设置属性 `destroyOnClose = true`即可
