### ISSUE TITLE
国际化切换语言后useForm表单的字段label没有切换语言

### ISSUE THREAD

**Issue by baihua0207** [vbenjs/vue-vben-admin#2334]
页面上使用了BasicForm组件
使用useForm配置表单字段时字段的label使用了useI18n()的t()返回的label的值
切换语言的时候label不会改变，需要刷新页面才会改变成对应语言。
[http://qcplay-qcity.oss-cn-hangzhou.aliyuncs.com/qingyu/85XEPF100000L000.png](繁体)
[http://qcplay-qcity.oss-cn-hangzhou.aliyuncs.com/qingyu/D5XEPF100000M000.png](切换为英文时)

**Comment by likui628** [comment]
请提供重现代码
