### ISSUE TITLE
热更新 很慢怎么解决呢

### ISSUE THREAD

**Issue by oEstate** [vbenjs/vue-vben-admin#2340]
改一个文字 大概2秒左右才更新

**Comment by oEstate** [comment]
![1667976713565](https://user-images.githubusercontent.com/30233122/200759489-db686dfa-4b83-4d6a-a583-4d282373e3cd.png)
修改一个页面 加载很多
之前版本 只加载一个 是当前修改页面的
请问在哪里配置呢

**Comment by oEstate** [comment]
![1667982630250](https://user-images.githubusercontent.com/30233122/200780206-ce6bd1bd-90e4-4675-a7e1-3daeae3ffe68.png)
改成这样加载快了
最新版本的删除了，是解决了，还是我电脑问题啊

**Comment by CrazyRocks** [comment]
我也慢的不得了

**Comment by zhangyuanliang** [comment]
这样修改可以提升10秒时间

```
main.ts
import Antd from 'ant-design-vue';
import 'ant-design-vue/dist/antd.css';

app.use(Antd).mount('#app');

build/vite/plugin/index.ts
vite-plugin-style-import注释掉
```

**Comment by mark0614** [comment]
> 我也慢的不得了

慢的问题解决没有？？同求
