### ISSUE TITLE
build之后，使用live-server运行生成文件，F5刷新页面就404，页面空白了

### ISSUE THREAD

**Issue by XiaoNode** [vbenjs/vue-vben-admin#2342]
### 描述 Bug

使用thin版本，npm run build之后，使用live-server运行生成文件，F5刷新就404

## 系统信息

- 操作系统:
- win 10
- Node 版本:
- 16.15.0
- 包管理器 (npm/yarn/pnpm) 及其版本:
- 8.5.5

**Comment by suwenyin** [comment]
我也出现同样的问题，F5刷新后，就加载404，期待能找到解决方法或思路

**Comment by suwenyin** [comment]
> ### 描述 Bug
> 使用thin版本，npm run build之后，使用live-server运行生成文件，F5刷新就404
> 
> ## 系统信息
> * 操作系统:
> * win 10
> * Node 版本:
> * 16.15.0
> * 包管理器 (npm/yarn/pnpm) 及其版本:
> * 8.5.5



> 我也出现同样的问题，F5刷新后，就加载404，期待能找到解决方法或思路

已解决，参见：https://github.com/vbenjs/vue-vben-admin/issues/1303

**Comment by suwenyin** [comment]
> 我也出现同样的问题，F5刷新后，就加载404，期待能找到解决方法或思路

已确决，参见：https://github.com/vbenjs/vue-vben-admin/issues/1303
