### ISSUE TITLE
期望你们开发一个ApiSelect的增强组件

### ISSUE THREAD

**Issue by cchhcui** [vbenjs/vue-vben-admin#2346]
### 提出问题
我们在实际开发工作中，用到引用内容的时候， 经常采用下拉列表，但是下拉列表一般只展示一两个列，想做搜索等功能的时候，更是不好在狭窄的空间完成多条件搜索。

### 期望的特性

期望这个增加的新组件（比如叫ApiPopSelect）左边有一个输入框，右边是按钮（放大镜等图标），点击按钮，弹出一个modal，上面是多个查询条件输入框，下面是Table，可以翻页，选择记录后，关闭Modal，返回选择的列表的行的idList等内容，在新组件的左边的输入框展示选择的内容。

我尝试写这样的东西，功力不够，总是报错，我想可能是循环引用等问题导致的，期待你们能理解我的想法，丰富一下组件或者组合用法，这种对于数据量比较大、逻辑复杂的应用有意义。

### 其它可选方案

或者可以考虑封装新组件和Modal组合的方式，麻烦做个例子，放在咱们的新版本里

非常感谢你们的辛苦付出！

**Comment by vintonHuang** [comment]
默默的说一句，这个东西，已经非常偏向你自己的特殊的业务了，还是得你自己利用项目的特性自己去封装。

**Comment by Wang62646264** [comment]
![1672294190929](https://user-images.githubusercontent.com/100344896/209910846-164dfe6d-dc6e-41cf-8388-744298ad474d.jpg)
是这种吗？

**Comment by vintonHuang** [comment]
你想要的时候，把Modal 组件和table组件组合起来一个直接可以使用的组件是这样吗？

**Comment by cchhcui** [comment]
> ![1672294190929](https://user-images.githubusercontent.com/100344896/209910846-164dfe6d-dc6e-41cf-8388-744298ad474d.jpg) 是这种吗？

是的，就是这种，你这个是多选的，还有单选方式的，都是为了数据量比较大时，方便弹出条件查询并且分页查找用的

**Comment by cchhcui** [comment]
> 你想要的时候，把Modal 组件和table组件组合起来一个直接可以使用的组件是这样吗？
基本是这样的意思，正如上面[Wang62646264](https://github.com/Wang62646264)所说的这种。我是希望有这样的组件（一种类型，比如叫ApiPopSelect），属于FormItem的一个类型，弹出的Modal直接使用BasicTable，循环引用的问题，可以通过动态引用来解决：
<component  :title="curPopModuleName"
              @register="registerDrawer"
              :is="components.get(compName)"
/>
可能这些连在一起当组件用有些庞大了，但是真的比较实用，在做管理软件的业务中，这种用法会很多

**Comment by Wang62646264** [comment]
> > ![1672294190929](https://user-images.githubusercontent.com/100344896/209910846-164dfe6d-dc6e-41cf-8388-744298ad474d.jpg) 是这种吗？
> 
> 是的，就是这种，你这个是多选的，还有单选方式的，都是为了数据量比较大时，方便弹出条件查询并且分页查找用的

![image](https://user-images.githubusercontent.com/100344896/210928448-81370be7-f83d-41d6-96e9-848de57e5183.png)
我这单选是靠限制个数的，
![image](https://user-images.githubusercontent.com/100344896/210928540-b9e9fcfc-557c-4080-adb3-b916067bf139.png)
