### ISSUE TITLE
调用父组件方法关闭modal时，会闪烁一下

### ISSUE THREAD

**Issue by bieshaoxiong** [vbenjs/vue-vben-admin#2347]
父子组件关系
index.vue=>modal.vue=>form.vue

**form.vue 代码**：

![image](https://user-images.githubusercontent.com/64937534/200993189-89266ebd-92f7-4034-8a6f-cb3b4f8d1eaa.png)
![image](https://user-images.githubusercontent.com/64937534/200993190-46c2d812-88c0-45f8-b04f-06000deaf689.png)

**modal.vue 代码：**
![image](https://user-images.githubusercontent.com/64937534/200993248-5233bdb9-f0e1-4c2e-a36e-fd8a615fb5c0.png)
![image](https://user-images.githubusercontent.com/64937534/200993285-02a93c48-f973-475f-9acf-4b338f91b53c.png)
![image](https://user-images.githubusercontent.com/64937534/200993315-2617c0d8-7619-42ad-a021-6b494b994129.png)

**index.vue 代码：**
![image](https://user-images.githubusercontent.com/64937534/200993382-1bc4212d-e347-4bd1-ba69-a35d14f89fc8.png)
![image](https://user-images.githubusercontent.com/64937534/200993421-382f8fb2-b76a-49f3-b7f9-3d9357368e5b.png)

哪里写错了吗？
每次添加完数据关闭时，会很快的闪烁一下，他会关闭modal 然后再迅速的打开关闭一下。直接X掉modal和取消不会有这样的情况

**Comment by qyn980427** [comment]
我猜测是弹窗还没有完全关闭的问题，亲测在afterClose事件中处理emit可以解决这个问题

**Comment by bieshaoxiong** [comment]
> 我猜测是弹窗还没有完全关闭的问题，亲测在afterClose事件中处理emit可以解决这个问题

感谢大哥，我把reload放在modal的 after-close里面就可以了
