### ISSUE TITLE
升级vite3报错

### ISSUE THREAD

**Issue by 714871549** [vbenjs/vue-vben-admin#2348]
如题：
![image](https://user-images.githubusercontent.com/20897369/201025453-4f542053-4704-4c62-9142-90c8b2944eec.png)

**Comment by fanzihui** [comment]
你可以去看看这个回答 #2160

**Comment by Git-So** [comment]
不使用 [vite-plugin-theme](https://github.com/anncwb/vite-plugin-theme) 即可，相关代码自己实现或不切换主题

**Comment by 714871549** [comment]
> 不使用 [vite-plugin-theme](https://github.com/anncwb/vite-plugin-theme) 即可，相关代码自己实现或不切换主题

我就是没有调用主题，注释了，就好了

**Comment by charlesluo2014** [comment]
什么时候能升级vite3？
