### ISSUE TITLE
安卓端 钉钉内  无法正常加载项目

### ISSUE THREAD

**Issue by zeekrs** [vbenjs/vue-vben-admin#2352]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

安卓端 钉钉内  无法正常加载项目  

### 复现 Bug

安卓端 钉钉内 打开 https://vvbin.cn/next/ 这个链接   一直在加载页面转圈 无法正常加载内容

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by zeekrs** [comment]
找到原因了  升级了一下 ant-design-vue 的依赖就好了 😂

**Comment by kangweiming1996** [comment]
> 找到原因了 升级了一下 ant-design-vue 的依赖就好了 😂

请问具体升级了哪些依赖呢，我也遇到了相同的问题

**Comment by yumianlv** [comment]
@kangweiming1996 可以尝试 https://blog.csdn.net/sq66666/article/details/125561990
检索关键字：globalThis is not defined

**Comment by kangweiming1996** [comment]
> @kangweiming1996 可以尝试 https://blog.csdn.net/sq66666/article/details/125561990 检索关键字：globalThis is not defined

感谢！解决了
