### ISSUE TITLE
TreeSelect组件将replaceFields属性更换至fieldNames

### ISSUE THREAD

**Issue by vvebzen** [vbenjs/vue-vben-admin#2355]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

antd3.2.0 表单FormSchema使用TreeSelect组件控制台会飘红 `replaceFields` is deprecated, please use fieldNames instead，
将自定义字段更换成fieldNames后，传除了title这个字符串，其他都是 --- 不能正确显示

### 复现 Bug

![1668091580653](https://user-images.githubusercontent.com/32607516/201122253-a80df07a-ebb1-4f83-be3a-8b6437ddfd6b.png)
![1668090942772](https://user-images.githubusercontent.com/32607516/201121439-6303a1e9-ca49-4939-b5e1-a5e912df9fe1.jpg)
![1668091246779](https://user-images.githubusercontent.com/32607516/201121454-fcd5ef76-487c-4757-85ca-79bdd3ddde00.jpg)

## 系统信息

- 操作系统:
- Node 版本: v14.19.1
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by ZackLeonardo** [comment]
请问这个bug还没有修复吗？

**Comment by likui628** [comment]
https://github.com/vbenjs/vue-vben-admin/blob/8df2590aae8d646880e8c064e6b4ba48cb54086d/src/components/Table/src/components/editable/EditableCell.vue#L319-L335

**Comment by likui628** [comment]
componentProps属于用户自己输入的，没必要在BasicForm里去特定转换
