### ISSUE TITLE
setFieldsValue 赋值赋不上

### ISSUE THREAD

**Issue by bieshaoxiong** [vbenjs/vue-vben-admin#2364]
我用props传过来的值赋值没效果
![image](https://user-images.githubusercontent.com/64937534/201453707-1087cf7d-e351-4ed3-bb77-967d5bb5db1c.png)

但是我在父组件调用子组件的方法，方法里面再写setFieldsValue 就能赋值上了
![image](https://user-images.githubusercontent.com/64937534/201453736-dabce627-3ae4-44ba-8fc4-50ccae136ce4.png)

这是为啥，是不是不能直接写在setUp里面，我少写了什么代码吗？

**Comment by yang-xianzhu** [comment]
setup执行时机

**Comment by vintonHuang** [comment]
你这个可以在赋值的操作，放在nextTick 函数里面，应该就可以了

**Comment by GauharChan** [comment]
setup等价于beforeCreate和createed生命周期，你的registerForm还没有挂载到节点；所以找不到实例执行setFieldsValue函数，打开console看一下就知道了
