### ISSUE TITLE
ApiSelect 怎样让某行数据默认被选中

### ISSUE THREAD

**Issue by bieshaoxiong** [vbenjs/vue-vben-admin#2374]
ApiSelect 怎样让某行数据默认被选中

**Comment by YIDA-max** [comment]
数据双向绑定,或者给默认值都可以
![image](https://user-images.githubusercontent.com/73836808/201563531-c2574a16-a7fa-411d-a6e2-8ef7920133d7.png)

**Comment by bieshaoxiong** [comment]
> 数据双向绑定,或者给默认值都可以 ![image](https://user-images.githubusercontent.com/73836808/201563531-c2574a16-a7fa-411d-a6e2-8ef7920133d7.png)
感谢老哥

**Comment by bieshaoxiong** [comment]
> 数据双向绑定,或者给默认值都可以 ![image](https://user-images.githubusercontent.com/73836808/201563531-c2574a16-a7fa-411d-a6e2-8ef7920133d7.png)

哦 不对，还是有个问题，我数据源是这样的 lable value isDefault  
我需要判断isDefault为true的把他默认选中，我刚刚尝试在field里面写isDefault  在 defaultValue：true，这样针对一个下拉框是可行的，但是我的我的其他下拉框数据源也是这样的格式 我就不能再field再次写isDefault了
还有其他的实现方法吗？或则在ApiSelect封装代码里面调整一下什么代码也能实现？

**Comment by bieshaoxiong** [comment]
有没有下拉框加载完数据的事件
这样我在这个事件里面去给value赋值也行，但是我没找到这个事件

**Comment by bieshaoxiong** [comment]
> > 有没有下拉框加载完数据的事件 这样我在这个事件里面去给value赋值也行，但是我没找到这个事件
> 
> ApiSelect的onOptionsChange事件可以吗？
感谢大哥，这个可以，有效果
请问一下onOptionsChange这个事件在个文档可以找到，我在vben admin 和 ant design vue 文档里面都没找到这个
