### ISSUE TITLE
登录后，存在安全漏洞

### ISSUE THREAD

**Issue by foundations** [vbenjs/vue-vben-admin#2380]
最新官方版本
登录后，取用户信息接口超时失败，没做登出或任何后续的错误处理，
页面停留在登录界面，给人错觉是未能登录成功，实际上已登录，存在安全漏洞！

建议做错误处理，或者直接登出。

**Comment by abao-chen** [comment]
现有代码里有做请求的通用拦截，后续需求可以自己处理的
https://github.com/vbenjs/vue-vben-admin/blob/7fad00cb77e7b8b83ea69c9ccbf1753a802edff4/src/utils/http/axios/index.ts#L57
