### ISSUE TITLE
EditCellTable ApiSelect如何监听回车事件

### ISSUE THREAD

**Issue by haliuhei** [vbenjs/vue-vben-admin#2382]
### 描述 Bug

关于EditCellTable中只有input能监控键盘回车事件，其他像select无法监听到onPressEnter，想要实现选中选项后键盘 回车可以执行（beforeEditSubmit）操作，该怎么实现
```
 onPressEnter: (e) => {
     console.log(e);
 }
```

### 复现 Bug
参见官方demo，只有input回车才有效

https://github.com/vbenjs/vue-vben-admin/blob/7fad00cb77e7b8b83ea69c9ccbf1753a802edff4/src/views/demo/table/EditCellTable.vue#L3

**Comment by bieshaoxiong** [comment]
大佬这个问题解决了吗

**Comment by haliuhei** [comment]
> 大佬这个问题解决了吗

太久了记不太清，好像业务通过onChange里延迟执行onSubmitEdit处理了提交

**Comment by bieshaoxiong** [comment]
哦  妈的，刚刚尝试了一下可以了
在ApiSelect 里面的Select里面加一个  @keyup.enter="handleEnterKey"
 emits: ['options-change', 'change', 'enter-key'],
 
 然后再到EditableCell 的onPressEnter={this.handleEnter}下面加上  onEnterKey={this.handleEnter}
 
 这样就可以了触发了
