### ISSUE TITLE
预览地址无法打开 404问题

### ISSUE THREAD

**Issue by yrieIrving** [vbenjs/vue-vben-admin#2387]
在线预览地址无法打开 404问题

**Comment by yrieIrving** [comment]
在线预览地址无法打开 404问题

**Comment by suka233333** [comment]
对 官网404了...

**Comment by liangdaozheng** [comment]
文档：[https://doc.vvbin.cn/](https://www.kookapp.cn/go-wild.html?url=https%3A%2F%2Fdoc.vvbin.cn%2F) 
demo网站：[https://vben.vvbin.cn/](https://www.kookapp.cn/go-wild.html?url=https%3A%2F%2Fvben.vvbin.cn%2F)

**Comment by M69W** [comment]
楼上为何要做跳转？直连不好？

> 文档：[https://doc.vvbin.cn/](https://www.kookapp.cn/go-wild.html?url=https%3A%2F%2Fdoc.vvbin.cn%2F) demo网站：[https://vben.vvbin.cn/](https://www.kookapp.cn/go-wild.html?url=https%3A%2F%2Fvben.vvbin.cn%2F)

**Comment by M69W** [comment]
文档：[https://doc.vvbin.cn/](https://doc.vvbin.cn/)
demo网站：[https://vben.vvbin.cn/](https://vben.vvbin.cn/)
