### ISSUE TITLE
jsp项目引入antv g2的data-set.min.js，运行报错：Cannot read properties of undefined (reading 'Graph')

### ISSUE THREAD

**Issue by HG-CALGHA** [vbenjs/vue-vben-admin#2388]
Describe the bug
在jsp项目运行引用了data-set.min.js，虽然不影响页面实现，但还是疑问为什么会出现这种报错Cannot read properties of undefined (reading 'Graph')

Your Example Website or App

Steps to Reproduce the Bug or Issue
1. 下载data-set.min.js文件
2. 在jsp页面中引入
3. 访问页面控制台报错
![image](https://user-images.githubusercontent.com/55530737/202110049-31447985-f5cd-4555-b5e1-d594c1a18d86.png)

Platform
data-set.min.js：0.10.2
OS: Windows10
Browser: Chrome

**Comment by wangjue666** [comment]
看起来跟本项目无关，可以找antdv g2寻求帮助
