### ISSUE TITLE
官方文档库挂了知道吗？

### ISSUE THREAD

**Issue by darksunnydong** [vbenjs/vue-vben-admin#2389]
官方文档库挂了，挂了多久了还没人管，vvbin.cn
官方组件示例站也挂了，vben.vvbin.cn
是不是准备把doc也关了

官方提供的QQ群也搜不到，连个官人都找不到
是要干嘛

**Comment by yang-xianzhu** [comment]
新地址：https://doc.vvbin.cn/guide/introduction.html
