### ISSUE TITLE
setFieldsValue赋值时间组件问题

### ISSUE THREAD

**Issue by banana-wu** [vbenjs/vue-vben-admin#2399]
通过setFieldsValue赋值时间组件 本地环境没问题 打包部署测试环境代码报错 
<img width="220" alt="image" src="https://user-images.githubusercontent.com/57582674/202986619-e6d32d9b-cf0e-4a9d-aeb2-051d6245e1cb.png">

<img width="907" alt="image" src="https://user-images.githubusercontent.com/57582674/202986786-5ce9856a-6639-41c0-97ec-610e21f52bd4.png">

**Comment by anncwb** [comment]
Hello @banana-wu. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by likui628** [comment]
贴图报错信息看不全
