### ISSUE TITLE
reason: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by zsl1549** [vbenjs/vue-vben-admin#2401]
### 描述 Bug
pnpm install 报错
请清晰地描述此 Bug 的具体表现。
执行pnpm install 报错
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/32888522/203090611-2705aea6-6dc9-4aaa-88fd-70be37d0e2e6.png">

### 复现 Bug
pnpm install 报错
请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:Mac 13.0.1
- Node 版本:v16.17.1
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 7.16.1

**Comment by wangjue666** [comment]
不要用淘宝源，开个代理试试
