### ISSUE TITLE
执行yarn build，一直卡在这个界面，需要半个多小时才能构建完成。

### ISSUE THREAD

**Issue by tangyun-92** [vbenjs/vue-vben-admin#2404]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [是] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [是] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [是] 已在 Issues 中搜索了相关的关键词
- [是] 不是 ant design vue 组件库的 Bug

### 描述 Bug

执行yarn build，一直卡在这个界面，需要半个多小时才能构建完成。但是当我在cmd中按 command+c 的时候，就会立马输出 build success!

### 复现 Bug
<img width="650" alt="image" src="https://user-images.githubusercontent.com/53557002/203275586-d4812bf1-f4cb-45ca-84c2-6c3a3995f691.png">

## 系统信息

- 操作系统: mac os
- Node 版本: 14.17.6
- 包管理器 (npm/yarn/pnpm) 及其版本: yarn

**Comment by Lz020316** [comment]
请问大佬解决了嘛，我也遇到了这个问题
