### ISSUE TITLE
建议采用sass作为预处理css，ant design都放弃了less，采用了css-in-js

### ISSUE THREAD

**Issue by DowCore** [vbenjs/vue-vben-admin#2408]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by my6521** [comment]
还在用less吗

**Comment by xingyu4j** [comment]
ant design vue 还是less啊

**Comment by SKT1yang** [comment]
> ant design vue 还是less啊

ant design 不是ant design vue

**Comment by SKT1yang** [comment]
less是有很大的问题，开发环境编译相应慢很大的一个原因就是less，scss也一般，希望有个好的方案

**Comment by xingyu4j** [comment]
> less是有很大的问题，开发环境编译相应慢很大的一个原因就是less，scss也一般，希望有个好的方案

这个也得ant design vue跟进吧，再说了现在作者已经不维护了。。
