### ISSUE TITLE
beforeFetch传递数组参数

### ISSUE THREAD

**Issue by bieshaoxiong** [vbenjs/vue-vben-admin#2414]
![image](https://user-images.githubusercontent.com/64937534/203514370-843e334e-cae7-4e93-9d95-9e766f794719.png)
![image](https://user-images.githubusercontent.com/64937534/203514462-56cf601d-055b-46f1-bedc-4b5a8ec4260c.png)

怎么让请求接口的时候参数变成 deptIdList = [1, 2, 3]

**Comment by Jzow** [comment]
请问分页的话怎么定义
