### ISSUE TITLE
账号管理-新增账号异步验证未进行防抖处理

### ISSUE THREAD

**Issue by jingluo99** [vbenjs/vue-vben-admin#2415]
### Subject of the feature
账号管理-新增账号异步验证未进行防抖处理
Describe your issue here.
校验用户是否存在时，每键入一个值都会发两次请求
![image](https://user-images.githubusercontent.com/69838091/203577954-68a6f121-db27-4509-85ef-c28d616a06b5.png)

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour
请问这种情况如何作防抖处理或者当失去焦点时才出发验证
What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by wangjue666** [comment]
```
{
    field: 'account',
    label: '用户名',
    component: 'Input',
    helpMessage: ['本字段演示异步验证', '不能输入带有admin的用户名'],
    rules: [
      {
        required: true,
        message: '请输入用户名',
      },
      {
        validator(_, value) {
          return new Promise((resolve, reject) => {
            isAccountExist(value)
              .then(() => resolve())
              .catch((err) => {
                reject(err.message || '验证失败');
              });
          });
        },
        trigger: 'blur',
      },
    ],
  },
```

添加 `trigger` 即可， 或者自行在 `validator` 函数内做防抖操作
