### ISSUE TITLE
component.toUpperCase is not a function 路由报错

### ISSUE THREAD

**Issue by Hiphone-Du** [vbenjs/vue-vben-admin#2422]
通过后台配置路由，模拟写个JSON数据。 PermissionModeEnum已设置成BACK, 首次登录正常显示，登出之后，再登录总是报错。
报：component.toUpperCase is not a function

查了好久，发现是transformObjToRoute，动态引入组件出了问题。正常const component = route.component as string;首次登录得到的compont是LAYOUT，但是登出之后，再登录，compont是 () => import('/src/layouts/default/index.vue?t=1669273454546')，请问有大牛帮我解决下吗？万分感谢！

配置的路由JSON如下：
[
    {
      "path": "/dashboard",
      "name": "Dashboard",
      "component":"LAYOUT",
      "redirect": "/dashboard/analysis",
 
      "meta": {
        "title": "routes.dashboard.dashboard",
        "icon": "bx:bx-home"
      },
      "children": [
        {
          "path": "analysis",
          "name": "Analysis",
          "component": "/dashboard/analysis/index",
          "meta": {
              "title": "routes.dashboard.analysis",
              "icon": "bx:bx-home"
          }
      }
      ]
    }
  ]

备注：使用的Vue-vben-admin最新版本

**Comment by Hiphone-Du** [comment]
最后发现，在vue-vben-admin-main/src/store/modules/user.ts文件中，将logout逻辑改成如下即解决问题，感觉应该是本地模拟JSON数据太快了，需要延迟一下，谁能告诉我根本原因？

    async logout(goLogin = false) {
      if (this.getToken) {
        try {
          await doLogout();
        } catch {
          console.log('注销Token失败');
        }
      }
      this.setToken(undefined);
      this.setSessionTimeout(false);
      this.setUserInfo(null);
      window.localStorage.clear();
      window.sessionStorage.clear();
      // goLogin && router.push(PageEnum.BASE_LOGIN);

      setTimeout(() => {
        goLogin && location.reload();
      }, 100);

    },

**Comment by Hiphone-Du** [comment]
最后发现，在vue-vben-admin-main/src/store/modules/user.ts文件中，将logout逻辑改成如下即解决问题，感觉应该是本地模拟JSON数据太快了，需要延迟一下，谁能告诉我根本原因？

    async logout(goLogin = false) {
      if (this.getToken) {
        try {
          await doLogout();
        } catch {
          console.log('注销Token失败');
        }
      }
      this.setToken(undefined);
      this.setSessionTimeout(false);
      this.setUserInfo(null);
      window.localStorage.clear();
      window.sessionStorage.clear();
      // goLogin && router.push(PageEnum.BASE_LOGIN);

      setTimeout(() => {
        goLogin && location.reload();
      }, 100);

    },

**Comment by idleeggs** [comment]
大佬原因知道了吗

**Comment by ethzzz** [comment]
我也遇到了，一模一样的情况
