### ISSUE TITLE
ICON 怎么让他访问本地的图片

### ISSUE THREAD

**Issue by bieshaoxiong** [vbenjs/vue-vben-admin#2423]
![image](https://user-images.githubusercontent.com/64937534/203754017-4f153a40-a6ef-407e-b91b-7fa349385ef4.png)
zhe'l这里的额图片都是从这里下载的https://icones.netlify.app/collection，开发环境有外网，生产环境可能没有外网，这个要怎么处理

**Comment by canices** [comment]
请问你解决这个问题了吗？文档上给的方法是yarn gen:icon，但是我搜了下issue，好像在某一版已经更改了，现在我也不知道咋整了

**Comment by chenhw** [comment]
相同的问题，[icons](gen:icon)删除后如何处理

**Comment by wangjue666** [comment]
https://github.com/vbenjs/vue-vben-admin/pull/3158 已支持菜单传递自定义的图片
