### ISSUE TITLE
thin版本缺少文件

### ISSUE THREAD

**Issue by bosombaby** [vbenjs/vue-vben-admin#2427]
thin版本在src/settings/componentSetting.ts里面打开时，第一行引入组件import type { SorterResult } from '../components/Table'。
这个文件夹Table只在main版本有这个文件夹，thin版本会出现报错

**Comment by xingyu4j** [comment]
我抽离了一个精简版，可以看看

**Comment by mark0614** [comment]
我也遇到这个问题
