### ISSUE TITLE
希望支持顶部一级菜单和左侧菜单联动

### ISSUE THREAD

**Issue by my6521** [vbenjs/vue-vben-admin#2428]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by 107295472** [comment]
+1

**Comment by tybt** [comment]
不会自己写吗？

**Comment by likui628** [comment]
请把需求写的具体点
