### ISSUE TITLE
多语言出不来

### ISSUE THREAD

**Issue by coolliyong** [vbenjs/vue-vben-admin#2436]
bug描述：
当前版本: "2.8.0"

页面显示异常，多语言出不来。
在刷新后可能出现多个多语言变量都出不来，多数情况下弹窗的确认按钮出不来。

上图：

ctrl+f5刷新后可能出现这种
![微信图片_20221202173015](https://user-images.githubusercontent.com/25497230/205261628-3282d8a9-ffec-44ab-9739-609a3f95d3f5.png)

正常登录，进入页面，打开弹窗，确认按钮和取消文字 的多语言无法显示
![微信截图_20221202173103](https://user-images.githubusercontent.com/25497230/205261618-48db6c76-e59b-4667-89d7-6df71eb78086.png)

### 复现 Bug

正常登录，进入页面，打开弹窗，确认按钮和取消文字 的多语言无法显示

关键代码：
```
<template>
  <BasicModal v-bind="$attrs" destroyOnClose @register="register" title="批量导入">
    <div class="modal w-full h-full flex flex-col justify-center">
      <div class="modal__content flex flex-row justify-center items-center">
        <div class="flex flex-col items-center modal__content--module">
          <p class="px14">1、下载excel数据模版，填写信息</p>
          <img src="" alt="" class="excel-icon" />
          <p class="px12">注：请不要变动模板格式及字段信息</p>
          <a-button>下载模板</a-button>
        </div>
        <div class="line"></div>
        <div class="flex flex-col items-center modal__content--module">
          <p class="px14">2、上传填写好的excel文件</p>
          <img src="" alt="" class="excel-icon" />
          <p class="px12 opacity-0">注：请不要变动模板格式及字段信息</p>
          <a-button>下载模板</a-button>
        </div>
      </div>
    </div>
  </BasicModal>
</template>
```

## 系统信息

- 操作系统:  win11
- Node 版本:  v16.16.0
- 包管理器 (npm/yarn/pnpm) 及其版本: 
- yarn 1.22.19 
- npm 8.11.0
- pnpm 7.17.1

**Comment by coolliyong** [comment]
关闭是因为我从releases里面下最后一个版本是没问题的，但是最后一个版本是去年发布的。。

**Comment by waveTan** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/36431831/6399a2d1-5ba9-4a7f-a591-db2463ce9999)
我遇到相似的问题，刷新界面的时候很容易出现这样的情况，显示不出多语言

**Comment by waveTan** [comment]
有大神知道怎么处理么
