### ISSUE TITLE
searchFormSchema内定义一个solt 如何在BasicTable展示 

### ISSUE THREAD

**Issue by zsl1549** [vbenjs/vue-vben-admin#2437]
![image](https://user-images.githubusercontent.com/32888522/205493525-52bbf976-3320-4e02-bb84-46842f4c2eed.png)

**Comment by zsl1549** [comment]
@pzgz 求大佬指点

**Comment by nguyenhan-se** [comment]
u must prefix form-taxcode

**Comment by zsl1549** [comment]
谢谢大神指点

**Comment by yonghui666** [comment]
> 谢谢大神指点

大佬；怎么解决的啊；加的啥前缀？
