### ISSUE TITLE
BasicTable columns内容多 表头和内容没有对齐

### ISSUE THREAD

**Issue by zsl1549** [vbenjs/vue-vben-admin#2438]
![image](https://user-images.githubusercontent.com/32888522/205604443-a606b5de-256d-4a3d-af7d-413a3de4a0c0.png)

**Comment by FallstarWing** [comment]
留一列不要设置宽度就可以了对齐了

**Comment by wangjue666** [comment]
请参考 https://github.com/vbenjs/vue-vben-admin/issues/3085
