### ISSUE TITLE
最新版本出现failed to fetch dynamically imported module  报错

### ISSUE THREAD

**Issue by zhuichen** [vbenjs/vue-vben-admin#2441]
### Describe the bug
把当前仓库的main分支拉下来，build之后，访问正常，但是再重新build一次后，不刷新页面的情况下，点击其他路由会出现failed to fetch dynamically imported module   indexxxx.js 404的报错

### Reproduction
重现步骤
1. git clone https://github.com/vbenjs/vue-vben-admin.git
2. yarn install&build 后
3. 通过ng访问build后的前端
4. 此时点击菜单页面，显示正常
5. 重新再build一次，不刷新页面的情况下，点击没有访问过的菜单，就会报错failed to fetch dynamically imported module   indexxxx.js 404

注：把动态路由改成静态路由就不会出现这样的问题

## System Info

- win10
- node verison  v19.0.0:
- yarn verison 1.17.3:

**Comment by luocong2016** [comment]
你用 vite 预览 能不能访问
