### ISSUE TITLE
API TREE  setFieldsValue回显失败

### ISSUE THREAD

**Issue by VaCameos** [vbenjs/vue-vben-admin#2446]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
使用setFieldsValue对表单进行回显时 表单值成功填入 但tree的勾选异常

### 复现 Bug
`const [registerForm, { resetFields, setFieldsValue, validateFields, updateSchema }] = useForm({
  labelWidth: 100,
  schemas: authSchemas,
  showActionButtonGroup: false,
  layout: 'vertical',
  baseColProps: {
    span: 24,
  },
});
const [register, { closeModal }] = useModalInner(async (data) => {
  await setFieldsValue(data)
});`
表单信息成功填充 如下图
![1670482343633](https://user-images.githubusercontent.com/103049831/206378654-a04c3606-ce09-4bdb-8909-cefb02ce9964.png)
但tree的勾选没有勾上

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by likui628** [comment]
请提供具体的demo代码，`authSchemas`和`useModalInner(async (data) => { await setFieldsValue(data) });`中的data值不知道
