### ISSUE TITLE
打包后 上传组件报错 不知道是哪里出的问题

### ISSUE THREAD

**Issue by lqins** [vbenjs/vue-vben-admin#2450]
![image](https://user-images.githubusercontent.com/18568384/206646001-13211a2e-3ef0-46aa-b91f-f664efcbfd89.png)
![image](https://user-images.githubusercontent.com/18568384/206646127-b9dc1781-0c51-4af1-b456-0906cb046ef1.png)
"TypeError: Cannot read properties of undefined (reading 'requestOptions')
    at responseInterceptorsCatch (http://39.108.143.25/assets/index.42e5119f.js:157:8387)
    at http://39.108.143.25/assets/index.42e5119f.js:152:17201"

**Comment by zyintel** [comment]
我也遇到了这个问题。请问您是怎么解决的？

**Comment by nyanboard** [comment]
我也晕倒了，真的坑

**Comment by nyanboard** [comment]
我也遇到了，本地可以，测试和正式环境不行

**Comment by mortence** [comment]
> 

https://github.com/vbenjs/vue-vben-admin/issues/2245
