### ISSUE TITLE
某些情况下展开的菜单不能自动关闭

### ISSUE THREAD

**Issue by hvppy** [vbenjs/vue-vben-admin#2451]
在顶部菜单模式下,展开了菜单,然后点击已打开的菜单(这个菜单是iframe),展开的菜单不能自动关闭,现在想手动调用下关闭,没有思路,请大佬指点下迷津!

**Comment by hvppy** [comment]
补充下,菜单不是默认的移出区域消失的模式,已经改为了点击才消失的模式

**Comment by anncwb** [comment]
Hello @hvppy. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.
