### ISSUE TITLE
整合monaco-editor 发布到生产报错

### ISSUE THREAD

**Issue by l54808821** [vbenjs/vue-vben-admin#2454]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

尝试在最新的主干代码整合monaco-editor，本地调试没有问题，但是发布到Nginx时报错

### 复现 Bug

1、pnpm install monaco-editor
2、封装组件
`<template>
  <div :id="editorId" :style="{ width: '100%', height: '300px' }"></div>
</template>

<script setup>
  import { onMounted } from 'vue';
  import * as monaco from 'monaco-editor';
  import editorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker';
  import jsonWorker from 'monaco-editor/esm/vs/language/json/json.worker?worker';
  import cssWorker from 'monaco-editor/esm/vs/language/css/css.worker?worker';
  import htmlWorker from 'monaco-editor/esm/vs/language/html/html.worker?worker';
  import tsWorker from 'monaco-editor/esm/vs/language/typescript/ts.worker?worker';

  /**
   * setup MonacoEnvironment
   * @type {{getWorker(*, *): (*)}}
   */
  self.MonacoEnvironment = {
    getWorker(_, label) {
      if (label === 'json') {
        return new jsonWorker();
      }
      if (label === 'css' || label === 'scss' || label === 'less') {
        return new cssWorker();
      }
      if (label === 'html' || label === 'handlebars' || label === 'razor') {
        return new htmlWorker();
      }
      if (label === 'typescript' || label === 'javascript') {
        return new tsWorker();
      }
      return new editorWorker();
    },
  };

  const editorId = Math.random().toString(36).slice(-10);
  onMounted(() => {
    // 创建editor并挂载
    monaco.editor.create(document.getElementById(editorId), {
      contextmenu: false,
      selectOnLineNumbers: true, // 显示行号
      value: '{}',
      language: 'json',
      scrollBeyondLastLine: false, // 去掉最下面的空白行
      theme: 'vs', //vs-dark、vs、hc-black
      automaticLayout: true,
      readOnly: false, // 是否只读
      autoIndent: true, // 自动布局
      fontSize: 13,
      tabSize: 2, // tab缩进长度
      minimap: {
        enabled: false,
      },
      dragAndDrop: false,
    });
  });
</script>`

3、发布到nginx，进入到有这个组件的页面报错截图如下
<img width="457" alt="image" src="https://user-images.githubusercontent.com/49773498/207514010-ee64babb-e06a-458a-826b-c3887216d9fe.png">

## 系统信息

- 操作系统: mac
- Node 版本: v14.18.2
- pnpm版本: 7.17.0

**Comment by wangjue666** [comment]
引入`monaco-editor`后， vite打包也需要配置额外的东西， 去详细看下monaco-editor文档教程吧。
