### ISSUE TITLE
完整版预览地址  简化版地址 404 

### ISSUE THREAD

**Issue by tzy13755126023** [vbenjs/vue-vben-admin#2458]
完整版预览地址  简化版地址 404
我看到 文档地址已经切换到 [https://doc.vvbin.cn/](https://doc.vvbin.cn/)
完整版预览地址 已经切换到 [https://vben.vvbin.cn/](https://vben.vvbin.cn/)
但是 你的 github 跟 git 的 md 中 未同步

**Comment by Sunny-117** [comment]
你好，我提了一个pr，https://github.com/vbenjs/vue-vben-admin/pull/2462
