### ISSUE TITLE
希望更新antdv版本

### ISSUE THREAD

**Issue by despire1119** [vbenjs/vue-vben-admin#2471]
### Subject of the feature

希望更新antdv版本

### Problem

目前antdv已不推荐使用2.x版本，请问是否有计划更新antdv版本？

### Expected behaviour

更新antdv至3.x+，谢谢

**Comment by vintonHuang** [comment]
目前的vben 2.8.0 都已经更新了啊antvd3.x 的版本的啊

**Comment by coderwyd** [comment]
https://github.com/vbenjs/vue-vben-admin/blob/main/package.json#L46

**Comment by despire1119** [comment]
我升级一波！感谢感谢！

**Comment by wang-cola** [comment]
> 我升级一波！感谢感谢！

你好层主，我想问一下，你已经用了这个项目了，最开始是用git clone去用的，那本项目更新了之后，你是怎么更新自己的项目的呢，我git clone完这个项目之后，就把git地址改为公司的git了，然后去搞公司的业务逻辑去了，感觉框架开发者后续的更新，我不好加进去啊
