### ISSUE TITLE
table 组件使用插槽 headerCell  获取不到 title 的值 ， antd原生组件可以获取到

### ISSUE THREAD

**Issue by SanpLee** [vbenjs/vue-vben-admin#2489]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

table 组件使用插槽 headerCell  获取不到 title 的值 ， antd原生组件可以获取到。
而且如果我只想改其中一个表头用headerCell后所有的表头都必须重新写一遍，不然都不显示

antd版本：3.2.15
vben版本是精简版

### 复现 Bug

写法如下：
``` js
<BasicTable
      :columns="columns"
      :dataSource="dataSource"
      :striped="striped"
      :bordered="border"
      showTableSetting
      :pagination="{ pageSize: 10 }"
      @columns-change="handleColumnChange"
    >
      <template #headerCell="{ title, column }">
        <template v-if="column.key === 'projectID'">
          <span>
            <unordered-list-outlined />
            {{ title }}
          </span>
        </template>
     </template>
</BasicTable>
```

## 系统信息

- 操作系统:
- Node 版本:19.0.0
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm 7.18.0

**Comment by bieshaoxiong** [comment]
你试试用 column.dataIndex

**Comment by SanpLee** [comment]
> 你试试用 column.dataIndex

试了可以拿到，column.dataIndex和column.key都可以拿到，只有title不行

**Comment by likui628** [comment]
https://github.com/vbenjs/vue-vben-admin/commit/8df2590aae8d646880e8c064e6b4ba48cb54086d

**Comment by gloriaqing** [comment]
customTitle
