### ISSUE TITLE
modal关闭抖动的问题

### ISSUE THREAD

**Issue by ChaosLcc** [vbenjs/vue-vben-admin#2494]
### 描述 Bug
modal弹出，直接关闭时，抖动不明显。在modal中操作，或者调用接口后 关闭modal 抖动明显

### 复现 Bug

https://user-images.githubusercontent.com/16434139/211956368-0c5e7d5c-62bb-4812-9a2f-6170d4f9f7a8.mp4

## 系统信息

- 操作系统: mac win
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by slmev** [comment]
同遇到此问题，未找到具体原因，不过关闭弹窗后延迟调用reload后没有出现这个问题
