### ISSUE TITLE
demo无法登录

### ISSUE THREAD

**Issue by jeff-wangzhen** [vbenjs/vue-vben-admin#2498]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

demo无法登录
![image](https://user-images.githubusercontent.com/24654210/212528850-ebd70a20-afa9-4956-ad4d-669d26a649f6.png)

### 复现 Bug

访问https://vben.vvbin.cn/#/login?redirect=/dashboard 直接点击登录

## 系统信息

- 操作系统:win11
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by coderwyd** [comment]
可以正常登录。

**Comment by jeff-wangzhen** [comment]
@coderwyd 但是我试了不行。。
![image](https://user-images.githubusercontent.com/24654210/212809182-1cc6ba3f-955a-4993-b86d-5796ef9773eb.png)

**Comment by nanfb** [comment]
我登陆在控制台都看不到他的网路请求，

**Comment by jeff-wangzhen** [comment]
现在可以登录了

**Comment by jeff-wangzhen** [comment]
> 我登陆在控制台都看不到他的网路请求，

好像他删掉了登录接口，直接跳转路由了
