### ISSUE TITLE
使用BasicForm的usform模式使用插槽渲染，在提交的时候并不会收集插槽本身的数据

### ISSUE THREAD

**Issue by nanfb** [vbenjs/vue-vben-admin#2502]
### Subject of the feature
插槽使用
`    <BasicForm @register="register">
      <template #estate="{ model, field }">
        <a-input v-model:value="model[field]" />
      </template>
    </BasicForm>
`
表单中配置
` {
    field: 'title2',
    component: 'Input',
    label: '标题2',
    colProps,
    slot: 'estate',
  },
`
useForm配置
`
  const [register, { validate, getFieldsValue, setProps }] = useForm({
        labelCol: {
          span: 8,
        },
        wrapperCol: {
          span: 15,
        },
        schemas: schemas,
        actionColOptions: {
          offset: 8,
          span: 23,
        },
        submitButtonOptions: {
          text: '提交',
        },
        submitFunc: customSubmitFunc,
      });
`
在调用的customSubmitFunc的时候打印getFieldsValue获取到提交表单的内容，我不太清除绑定的 v-model:value="model[field]"是什么，但是他的value字段是不可替换的，
我的需求是一个select框的字段变化后，input框的字段也发生变化，，两个都是用插槽的情况下，我必须在input框上v-model绑定我自己定义的字段，这样的话，提交表单就获取不到值。
目前的方案是提交后重新添加两个插槽的值，

我的诉求是希望可以改变这个value字段，或者可以在options中修改，这样把value占住的话要显示其他的就很困难

**Comment by vintonHuang** [comment]
没有怎么看懂要表达的是什么

**Comment by nanfb** [comment]
> 没有怎么看懂要表达的是什么

就是使用插槽的时候提交收集数据的字段冲突了，框架v-model只能绑定固定的值，所以在提交的时候收集不到我想要的数据

**Comment by vintonHuang** [comment]
你想说的是，你在一个插槽里面使用了一个select下拉框，还有一个input框嘛

**Comment by nanfb** [comment]
> 你想说的是，你在一个插槽里使用了一个select下拉框，还有一个input框嘛

是的，我想在v-model上绑定值，但是他的字段是固定的model[field]

**Comment by nanfb** [comment]
> 你想说的是，你在一个插槽里使用了一个select下拉框，还有一个input框嘛

有什么好的方案吗？目前的方案是提交校验的时候手动加值进去
