### ISSUE TITLE
插件版本 升级后报错. 

### ISSUE THREAD

**Issue by HeartDawnWY** [vbenjs/vue-vben-admin#2506]
Uncaught ReferenceError: __COLOR_PLUGIN_OUTPUT_FILE_NAME__ is not defined

有计划升级各个插件到最新吗？

**Comment by xingyuv** [comment]
https://github.com/xingyuv/vue-vben-admin

我这个基本升级到最新了

**Comment by HeartDawnWY** [comment]
> https://github.com/xingyuv/vue-vben-admin
> 
> 我这个基本升级到最新了

非常感谢你。
