### ISSUE TITLE
热更新会重新引入所有其他依赖，导致热更新速度很慢

### ISSUE THREAD

**Issue by tttleon** [vbenjs/vue-vben-admin#2507]
只是在`src/views/dashboard/analysis/index.vue` 中添加修改几个字
![image](https://user-images.githubusercontent.com/66937093/215378832-ba2f632d-09ad-47d0-aafb-b4244e6a5793.png)
但是会重新加载其他的所有依赖，而不是只更新当前修改的文件
![image](https://user-images.githubusercontent.com/66937093/215378945-756f49d3-cb9d-4af1-8fd4-a7a006dddf3e.png)

**Comment by mark0614** [comment]
我也遇到这个问题，启动后，加载main.ts巨慢，一直在编译。有什么方案么？

**Comment by callmeyan** [comment]
对对对，就是太慢了，都想放弃用其他的框架了~
第一次就更不用说了！还不如webpack

**Comment by tttleon** [comment]
- 参考： (https://github.com/vbenjs/vue-vben-admin/issues/2340#issuecomment-1308395790)
- 使用效果：目前按照上述方法可以解决。修改后秒更新。即使刷新页面，加载速度也很快。
- 涉及问题：回复中提及的`关联文件修改的热跟新时效`问题，没遇到过。不过如果遇到了，看没效果直接刷新页面就好了，而且改完后刷新页面比现在的热更新快的多，
@mark0614  @callmeyan

**Comment by tttleon** [comment]
顺便复制下代码
vite.config.ts
```
    // The vite plugin used by the project. The quantity is large, so it is separately extracted and managed
    plugins: [
      ...createVitePlugins(viteEnv, isBuild),
      {
        name:'singleHMR',
        handleHotUpdate({modules,file}){
          if(file.match(/xml$/)) return []

          modules.map((m) => {
            m.importedModules = new Set()
            m.importers= new Set()
          })

        }
      }
    ],
```

**Comment by ma-lihui** [comment]
> * 参考： ([热更新 很慢怎么解决呢 #2340 (comment)](https://github.com/vbenjs/vue-vben-admin/issues/2340#issuecomment-1308395790))
> * 使用效果：目前按照上述方法可以解决。修改后秒更新。即使刷新页面，加载速度也很快。
> * 涉及问题：回复中提及的`关联文件修改的热跟新时效`问题，没遇到过。不过如果遇到了，看没效果直接刷新页面就好了，而且改完后刷新页面比现在的热更新快的多，
>   @mark0614  @callmeyan

这样改后修改vue文件确实更新很快秒刷，但是修改ts文件还是会reload整个页面，加载几百个文件，就很慢了。
