### ISSUE TITLE
表格使用多级表头时，单元格编辑失效。

### ISSUE THREAD

**Issue by lshhuhongtao** [vbenjs/vue-vben-admin#2515]
### 描述 Bug

表格使用多级表头时，单元格编辑失效。

### 复现 Bug
![image](https://user-images.githubusercontent.com/46209677/215981330-904a0b38-a7c8-4985-87e7-502edc8d3ddf.png)
![image](https://user-images.githubusercontent.com/46209677/215981362-36475459-35b0-46b6-a54f-5c82c776e1d5.png)

## 系统信息

- 操作系统: windows10
- Node 版本: v16.13.1
- 包管理器 (npm/yarn/pnpm) 及其版本: npm 8.1.2

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
