### ISSUE TITLE
高级表单中成员管理的表格的body设置高度不起作用。

### ISSUE THREAD

**Issue by xiangjihan** [vbenjs/vue-vben-admin#2519]
### 描述 Bug

演示中的高级表单下边有一个成员管理的表格，这个表格的body高度设置的非常小，不能正确的展示下边的数据。
通过scroll: { y: 100 }设置高度并不起作用。
![微信图片_20230202233243](https://user-images.githubusercontent.com/3070542/216387070-35eb3626-cd69-4fe3-9b7f-1d04d2457991.png)
如果是我用法错误，还请指正，点击下边的“新增成员”可以让高度增大，但是这不是我想要的效果。我想在加载的时候就能调整这个地方的高度。
如果可能，能不能告诉我点击“新增成员”，高度重置的原理，实在没找到代码中起作用的部分。

### 复现 Bug
![微信图片_20230203004219](https://user-images.githubusercontent.com/3070542/216387121-20801874-2666-421c-9b33-90a13d215f50.png)

## 系统信息

- 操作系统:Windows 10 专业工作站版 版本号22H2  内部版本19045.2546
- Node 版本: v18.13.0
- 包管理器 (npm/yarn/pnpm) 及其版本: 8.19.3

**Comment by xiangjihan** [comment]
scroll: { y: 100 }，我又试了一下，应该是管用，现在就是想知道“新增成员”那个地方是如何更改的height

**Comment by luocong2016** [comment]
然并卵

**Comment by luocong2016** [comment]
你这个好像也没解决问题，我看了下CSS 高度只有8px多一点，应该是没有重新计算高度

**Comment by luocong2016** [comment]
### 临时方案，应该符合目前案例
```ts
scroll: { y: "100%" }
```

**Comment by xiangjihan** [comment]
> ### 临时方案，应该符合目前案例
> ```ts
> scroll: { y: "100%" }
> ```

也就是说   初始化的时候没有办法让canResize生效对嘛

**Comment by luocong2016** [comment]
@xiangjihan 感觉应该是数据渲染后 没有触发视图更新

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
