### ISSUE TITLE
热更新丢失样式

### ISSUE THREAD

**Issue by luocong2016** [vbenjs/vue-vben-admin#2525]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [√ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [√] 不是 ant design vue 组件库的 Bug

### 描述 Bug
![image](https://user-images.githubusercontent.com/25705196/217166609-d86e8ff4-6201-4449-8fb4-c1d7d5a2d4a5.png)

### 复现 Bug
1. 热更新中，`/login` 页面 css 会出现背景丢失
2. 停留在登录页面， 更新或格式化代码。等待更新后，能复现

## 系统信息

- 操作系统:
- Node 版本:  v16.14.2
- 包管理器 (npm/yarn/pnpm) 及其版本: yarn 1.22.18

**Comment by nejinn** [comment]
我的也是哎，更新到最新，式样就丢失了
