### ISSUE TITLE
document.title 在哪写死

### ISSUE THREAD

**Issue by 714871549** [vbenjs/vue-vben-admin#2530]
![image](https://user-images.githubusercontent.com/20897369/217201673-a8ccc3f0-35c0-430e-a441-8e14bb5267a2.png)
想把这个文字固定其他的，比如 管理系统等
一直找不到在哪，封装太深了

**Comment by Frank2-Liu** [comment]
修改以下变量与常量即可。
——前置标题路径：`src\hooks\web\useTitle.ts`
——后置标题路径： `.env`
![pic_2](https://user-images.githubusercontent.com/114206461/217211244-66876b08-a874-433c-b3f8-75ada3050b39.png)
![pic_1](https://user-images.githubusercontent.com/114206461/217211277-4105a9d7-dd66-42f0-8a04-3b3e4322ab7f.png)

**Comment by 714871549** [comment]
> useTitle

谢啦
