### ISSUE TITLE
warning build issue can't be bundled without type="module"

### ISSUE THREAD

**Issue by dh336699** [vbenjs/vue-vben-admin#2531]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

WARN  <script src="/_app.config.js?v=1.0.0-1675769197103"> in "/index.html" can't be bundled without type="module" attribute     

### Reproduction

Clone Vben code, and build it..

## System Info

- Operating System: Windows 10
- Node version: v16.17.0
- Package manager (npm/yarn/pnpm) and version: pnpm: 7.12.1

**Comment by wmz1930** [comment]
Me too.

**Comment by jzfan** [comment]
Me too +1

**Comment by wupeng128** [comment]
Me too.

**Comment by googlegis** [comment]
这个问题有人解决了吗？我也碰到这个问题，生成的index.html 文件直接引用js文件，找不到文件。 生成环境运行不了
![image](https://github.com/vbenjs/vue-vben-admin/assets/830946/9a6ed75e-031a-411f-8be4-0d5fb22487d3)

**Comment by Jiachenglong2518** [comment]
Me too, 导致构建后_app.config.js404

**Comment by Jiachenglong2518** [comment]
@wangjue666  请问下解决问题的提交是哪个能指出来吗

**Comment by wangjue666** [comment]
> @wangjue666 请问下解决问题的提交是哪个能指出来吗

你好 拉取仓库最新代码能复现吗

**Comment by Jiachenglong2518** [comment]
@wangjue666 大佬你好， 新版本没有问题，可是我现在用的2.8版本的没法升级，所以想请问下在2.8版本上如何升级才能解决问题

**Comment by Jiachenglong2518** [comment]
> > @wangjue666 请问下解决问题的提交是哪个能指出来吗
> 
> 你好 拉取仓库最新代码能复现吗

@wangjue666 1

**Comment by Jiachenglong2518** [comment]
> 新版本没有问题，可是我现在用的2.8版本的没法升级，所以想请问下在2.8版本上如何升级才能解决问题

新版本没有问题，可是我现在用的2.8版本的没法升级，所以想请问下在2.8版本上如何升级才能解决问题

**Comment by Jiachenglong2518** [comment]
> > @wangjue666 请问下解决问题的提交是哪个能指出来吗
> 
> 你好 拉取仓库最新代码能复现吗

>> 新版本没有问题，可是我现在用的2.8版本的没法升级，所以想请问下在2.8版本上如何升级才能解决问题

**Comment by wangjue666** [comment]
@Jiachenglong2518  这个问题能提供个复现吗，把你的问题再截个图

**Comment by Jiachenglong2518** [comment]
@wangjue666  这是本地构建
![image](https://github.com/vbenjs/vue-vben-admin/assets/22738724/071bafea-c45a-48aa-8f4a-5538e9721be6)

**Comment by Jiachenglong2518** [comment]
@wangjue666 
这是本地构建的
![image](https://github.com/vbenjs/vue-vben-admin/assets/22738724/01de2c25-9d24-485b-9428-b8ce36691880)
这是CICD构建的
![image](https://github.com/vbenjs/vue-vben-admin/assets/22738724/c1abd2e8-b21a-4539-8de0-e76d0384a87b)
这是发布之后浏览器404
![image](https://github.com/vbenjs/vue-vben-admin/assets/22738724/a32c6f4d-efa3-4835-b222-4e03a711faef)
这是当前版本
![image](https://github.com/vbenjs/vue-vben-admin/assets/22738724/9da8ed27-c174-4348-8e0a-6024df25afe2)

**Comment by wangjue666** [comment]
@Jiachenglong2518  
![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/2fd7eb3a-73a3-4bbd-be9a-0e2755fcf916) 是这个版本吗， 我电脑是node20, win10, 打包时候会有这个警告提示，但是编译后运行是正常的
![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/a87c7b03-fefe-42dd-8600-ba3bbb6c780e)

**Comment by Jiachenglong2518** [comment]
@wangjue666  是的，我的本地也是没问题的。但是在服务器构建时这个文件就没了

**Comment by Jiachenglong2518** [comment]
![Uploading image.png…]()
@wangjue666  这是服务器上构建后的dist目录，

**Comment by wangjue666** [comment]
@Jiachenglong2518  兄弟你图片没传上来

**Comment by wangjue666** [comment]
> @wangjue666 是的，我的本地也是没问题的。但是在服务器构建时这个文件就没了

你本地打包 dist文件上传到服务器正常，但是服务器运行打包命令就不行了，是这样吗

**Comment by Jiachenglong2518** [comment]
@wangjue666  对的在服务器执行 npm run build后就没有_app.config文件

**Comment by Jiachenglong2518** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/22738724/a95f34f0-d24d-4b4a-82a1-7653e3aaf948)
服务器打包后dist文件目录

**Comment by wangjue666** [comment]
你服务器的环境提供下

**Comment by Jiachenglong2518** [comment]
@wangjue666 
![image](https://github.com/vbenjs/vue-vben-admin/assets/22738724/fdb45206-e306-4951-b3e9-5896f44985c5)

**Comment by linf-hub** [comment]
我的项目部署在二级域名下，打包后 src="/_app.config.js" 没有二级域名，导致文件无法访问，二级域名在VITE_PUBLIC_PATH中已配置，请问怎么解决，我是用的是2.10.1版本

**Comment by Jiachenglong2518** [comment]
@linf-hub 
![image](https://github.com/vbenjs/vue-vben-admin/assets/22738724/5dcfa014-23f1-44af-bb8a-40777bf3e429)
看下这块呢
