### ISSUE TITLE
VxeTable表格文档

### ISSUE THREAD

**Issue by liumaowen** [vbenjs/vue-vben-admin#2537]
希望大佬尽快出VxeTable表格文档，看到大佬封装的VxeTable表格很好用，给大佬个赞

**Comment by lzdjack** [comment]
文档请查看vxetable文档，api调用和参数配置和vxetable官网事例并无区别

**Comment by liumaowen** [comment]
大佬的封装很复杂，看来只能我去研究了

**Comment by lzdjack** [comment]
只是简单使用，那么vxetable官网事例怎么使用vben封装的就可以怎么使用，甚至可以复制vxetable官方事例代码，只需改下标签即可，如果想扩展或是适配antdv插件那么这部分需要阅读下vextable高级用法或者看vben封装的源码

**Comment by liumaowen** [comment]
受教了大佬
