### ISSUE TITLE
useReques hooks 管理 Promise Ajax 方法

### ISSUE THREAD

**Issue by luocong2016** [vbenjs/vue-vben-admin#2539]
### Subject of the feature

> 目前的 axios 封装了多个方法，使得 Ajax 变得复杂且不纯粹。

1. 业务场景分析

很多中后台项目都是单点登录，且单点登录类型很多。

更特别是部署时，来回切换登录方式。

需要实现多个 axios 实例拦截，登录逻辑会变得非常复杂。

2. 防抖，节流，可见重新，错误重试等功能

3. 消息通知类型

4. 监听功能，缓存，复用 hooks，手动触发等
 
若上述多个场景都封装到 axios 实例，这就会让 ajax 请求变得非常复杂，且错误后调试非常麻烦。
特别是在对接api接口的时候。

#### 推荐下状态方法管理
我之前开发过 ahooks 的vue 版本的 request
[useRequest](https://www.npmjs.com/package/@yx-frame/request)

文档可以参考下：
https://ahooks.js.org/zh-CN/hooks/use-request/index

这个比目前封装的 axios 和 Form 下面很多API组件实用, 耦合度会降低很多

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

希望改成可插拔型的 Promise 方法

![1677226225984](https://user-images.githubusercontent.com/25705196/221126477-2e2c4bde-31a1-48b3-b0e1-94ea57a07368.png)

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by tttleon** [comment]
[vueuse](https://vueuse.org/integrations/useAxios/#useaxios)

**Comment by tttleon** [comment]
vue3 有vueuse,
[useaxios](https://vueuse.org/integrations/useAxios/#useaxios)
[useasyncstate](https://vueuse.org/core/useAsyncState/#useasyncstate)
axios和useRequest不是一个东西，axios是用来请求，useRequest是异步状态管理。

**Comment by luocong2016** [comment]
> vue3 有vueuse, [useaxios](https://vueuse.org/integrations/useAxios/#useaxios) [useasyncstate](https://vueuse.org/core/useAsyncState/#useasyncstate) axios和useRequest不是一个东西，axios是用来请求，useRequest是异步状态管理。

没说是一个东西。
说的是，这个东西比现在项目封装的 axios 适用。
比如：
1. 错误重试
2.取消
3.防抖、节流
4.激活重新请求

**Comment by wangjue666** [comment]
resolve https://github.com/vbenjs/vue-vben-admin/pull/3447

**Comment by likui628** [comment]
刚看到，我觉得还是作为npm包导入比较合适。
@luocong2016
