### ISSUE TITLE
src/views/demo/table/VxeTable.vue 运行告警 [Vue warn]: injection "Symbol(basic-table)" not found. 

### ISSUE THREAD

**Issue by thegreatocean2014** [vbenjs/vue-vben-admin#2540]
### 描述 Bug
2023-02-07下载的最新库，整合到自己的业务系统中，发现新增了vxe-table组件，想测试一下，
src/views/demo/table/VxeTable.vue这个模块的功能，运行后发现控制台告警，如下：

[Vue warn]: injection "Symbol(basic-table)" not found. 
  at <TableAction actions= (3) [{…}, {…}, {…}] > 

### 复现 Bug

经排查，发现如下代码
src/views/demo/table/VxeTable.vue文件
```
<template>
  <PageWrapper
    title="VxeTable表格"
    content="只展示部分操作，详细功能请查看VxeTable官网事例"
    contentFullHeight
    fixedHeight
  >
    <VxeBasicTable ref="tableRef" v-bind="gridOptions">
      <template #action="{ row }">
        <TableAction :actions="createActions(row)" />
      </template>
    </VxeBasicTable>
  </PageWrapper>
</template>
```
该代码中使用了组件TableAction ，进入组件后发现，引入了如下模块
import { useTableContext } from '../hooks/useTableContext';
useTableContext代码为：
```
export function useTableContext(): RetInstance {
  return inject(key) as RetInstance;
}
```
其中 key 为 const key = Symbol('basic-table');
进而排查createTableContext代码：
```
export function createTableContext(instance: Instance) {
  provide(key, instance);
}
```
发现调用此模块的只有 src/components/Table/src/BasicTable.vue代码，是针对一般表格setup过程中调用的语句。
自此，发现集成的VxeBasicTable组件是来自VxeBasicTable模块，而非BasicTable模块，所以会报这个错误
希望能完善该模块功能，在VxeBasicTable模块中也加入createTableContext相应代码。
多谢，辛苦！

## 系统信息

- 操作系统:win10
- Node 版本:v16.19.0
- 包管理器 (npm/yarn/pnpm) 及其版本:npm 8.19.3

**Comment by WitMiao** [comment]
加个outside属性就行了，大佬设计时候都想到了，只是有点小bug我刚修掉了，等代码合并进去就好了

**Comment by thegreatocean2014** [comment]
加了outside，在
```
      let table: Partial<TableActionType> = {};
      if (!props.outside) {
        table = useTableContext();
      }
```
代码段是通过了，但是在后续的代码段还是会出问题，如：
```
      const getActions = computed(() => {
        return (toRaw(props.actions) || [])
          .filter((action) => {
            return hasPermission(action.auth) && isIfShow(action);
          })
          .map((action) => {
            const { popConfirm } = action;
            return {
              getPopupContainer: () => unref((table as any)?.wrapRef.value) ?? document.body,
              type: 'link',
              size: 'small',
              ...action,
              ...(popConfirm || {}),
              onConfirm: popConfirm?.confirm,
              onCancel: popConfirm?.cancel,
              enable: !!popConfirm,
            };
          });
      });
```

**Comment by WitMiao** [comment]
> 加了outside，在
> 
> ```
>       let table: Partial<TableActionType> = {};
>       if (!props.outside) {
>         table = useTableContext();
>       }
> ```
> 
> 代码段是通过了，但是在后续的代码段还是会出问题，如：
> 
> ```
>       const getActions = computed(() => {
>         return (toRaw(props.actions) || [])
>           .filter((action) => {
>             return hasPermission(action.auth) && isIfShow(action);
>           })
>           .map((action) => {
>             const { popConfirm } = action;
>             return {
>               getPopupContainer: () => unref((table as any)?.wrapRef.value) ?? document.body,
>               type: 'link',
>               size: 'small',
>               ...action,
>               ...(popConfirm || {}),
>               onConfirm: popConfirm?.confirm,
>               onCancel: popConfirm?.cancel,
>               enable: !!popConfirm,
>             };
>           });
>       });
> ```

同步下最新的代码，修改的已经同步进主分支了，去掉.value就行了，outside模式时候是没wrapRef的，有unref就不需要.value
