### ISSUE TITLE
修改env等配置文件时需要重启vite才能生效

### ISSUE THREAD

**Issue by maddenBoy** [vbenjs/vue-vben-admin#2541]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
修改env等配置文件时需要重启vite才能生效
请清晰地描述此 Bug 的具体表现。
例如修改.env文件中VITE_GLOB_APP_TITLE的值，页面不会热更新这个值，需要重启项目才能看到生效的值
### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码
1、把修改.env文件中VITE_GLOB_APP_TITLE的值改成Vben，保存文件，页面不会热更新这个值
2、关闭vite，重启项目
3、此时VITE_GLOB_APP_TITLE才会更新成Vben
4、把build文件夹下的utils.ts文件中下图的代码注释掉，则无上述问题，但不知道去掉会有什么影响，为什么要这么写
![image](https://user-images.githubusercontent.com/71129660/217976914-1fb0dad9-bbbd-4cd2-9bb4-8bf1fbfb8aef.png)

## 系统信息

- 操作系统:
- Node 版本:v18.13.0
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm

**Comment by vintonHuang** [comment]
同问，有大佬知道这个是为什么嘛？

**Comment by likui628** [comment]
这种配置文件不能热更新的
