### ISSUE TITLE
初次启动慢

### ISSUE THREAD

**Issue by mark0614** [vbenjs/vue-vben-admin#2545]
我是一名前端新手，参与后端多一些。最近看了vben-admin，运行之后，发现初次运行时页面加载巨慢。看了其他人的issue，也没有找到合适的方案。

**Comment by yuhldr** [comment]
build 部署以后就不慢了，你觉得慢是因为在本地serve

**Comment by ljfrocky** [comment]
> build 部署以后就不慢了，你觉得慢是因为在本地serve

但 build 的等待时间很长，如果每次修改完代码想看效果都要build一次，开发效率很低
