### ISSUE TITLE
pnpm serve 启动报错

### ISSUE THREAD

**Issue by CatKingYa** [vbenjs/vue-vben-admin#2549]
ERROR  error when starting dev server:                                                                                                                            13:46:39  
TypeError: commandResult.toString(...).replaceAll is not a function

**Comment by zhuchunlan** [comment]
是的，我也是这个错误

**Comment by CatKingYa** [comment]
> 是的，我也是这个错误
我搞了半天，项目都没启起来，人麻了

**Comment by zhuchunlan** [comment]
一样一样

**Comment by superlovetomato** [comment]
![图片](https://user-images.githubusercontent.com/57446068/219001077-b6aad0c0-6544-458f-8c1d-071e06171161.png)

一样，项目启不来

**Comment by masterjiyuhang** [comment]
报错的话，尝试切换一下node版本，16以上应该可以， 我用的16.19.0。

**Comment by CherishMvp** [comment]
是的，nvm安装16.14.2成功解决

**Comment by Gaofancy** [comment]
如果开发环境用不https的可以直接删掉这个插件vite-plugin-mkcert，然后在vite.config.ts注释掉https: true即可

**Comment by Miaodashu** [comment]
升级node版本    使用nvm安装16版本以上即可

**Comment by yeyuchen198** [comment]
用pnpm run dev试试，我这边可以
