### ISSUE TITLE
TableAction的action按钮为disabled时，tooltip不生效

### ISSUE THREAD

**Issue by quanbisen** [vbenjs/vue-vben-admin#2550]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

```
<TableAction
            :actions="[
              {
                icon: 'clarity:info-standard-line',
                tooltip: '查看用户详情',
                disabled: true,   // 禁用后，无法显示tooltip文本
                onClick: handleView.bind(null, record),
              },
            ]"
/>
```

### Reproduction

目前最新版代码也存在该问题，试了一下ant-design官网的同版本的`ant-design-vue`，按钮禁用状态，是可以显示tooltip文本的，尝试过修改源码的`TableAction`组件使用ant-design的`<a-button>`，问题依然存在，似乎与项目的配置有关。

----修改 2023.02.24
尝试修改TableAction组件的代码，使用ant-design-vue的组件引入方式，发现是在按钮disabled状态下是可以显示tooptip文本的
```
<Tooltip v-if="action.tooltip" v-bind="getTooltip(action.tooltip)">
    <Button disabled>123</Button>
    <!-- <PopConfirmButton v-bind="action">
      <Icon :icon="action.icon" :class="{ 'mr-1': !!action.label }" v-if="action.icon" />
      <template v-if="action.label">{{ action.label }}</template>
    </PopConfirmButton> -->
</Tooltip>
```

## System Info

- Operating System: win10
- Node version: v14.20.0
- Package manager (npm/yarn/pnpm) and version: npm:6.14.17

**Comment by wangjue666** [comment]
@quanbisen  感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
