### ISSUE TITLE
DatePicker设置defaultValue

### ISSUE THREAD

**Issue by a531267910** [vbenjs/vue-vben-admin#2568]
* 问题描述
Form表单component值为DatePicker，并且设置了defaultValue，format，valueFormat
 ![image](https://user-images.githubusercontent.com/82574609/220513091-8a7a6ceb-d35d-4e1c-8da4-35b48b80e096.png)
* 期待效果：页面展示为20230422，getFieldsValue()获取表单值也为20230422
* 实际结果：页面展示正确，但是获取表单值非期待值
![image](https://user-images.githubusercontent.com/82574609/220513174-fb75b8a3-8da3-422f-8a12-169f9a1d4266.png)
* 建议prop.ts中的transformDateFunc修改默认格式化处理，根据valueFormat或者format传的格式，设置默认格式
![image](https://user-images.githubusercontent.com/82574609/220513820-9fffee68-2d88-45e2-bad8-cbec29a4cbc9.png)

**Comment by likui628** [comment]
```
    {
      field: 'field1',
      component: 'DatePicker',
      label: '字段1',
      colProps: { span: 8 },
      componentProps: {
        format: 'YYYYMMDD',
        valueFormat: 'YYYYMMDD',
      },
      defaultValue: '20230422',
    },
```
![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/a20d1f70-2b6c-4179-9a3b-5ba6dcbf078a)

**Comment by anncwb** [comment]
Hello @a531267910. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.
