### ISSUE TITLE
上传组件问题

### ISSUE THREAD

**Issue by mxyhi** [vbenjs/vue-vben-admin#2579]
上传组件问题，上传一个列表会显示两个，会多出一个null，
预览界面时删除图片后，再次上传新的图片后，预览界面无法显示新的图片

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
