### ISSUE TITLE
![图片](https://user-images.githubusercontent.com/57446068/219001077-b6aad0c0-6544-458f-8c1d-071e06171161.png)

### ISSUE THREAD

**Issue by weiweihaoflower** [vbenjs/vue-vben-admin#2580]
![图片](https://user-images.githubusercontent.com/57446068/219001077-b6aad0c0-6544-458f-8c1d-071e06171161.png)

一样，项目启不来

_Originally posted by @superlovetomato in https://github.com/vbenjs/vue-vben-admin/issues/2549#issuecomment-1431090906_

**Comment by luocong2016** [comment]
你这个issuce写的一言难尽。
```sh
$ node -v
```
首先，你看下node版本能支持你跑vite?

**Comment by luocong2016** [comment]
![图片](https://user-images.githubusercontent.com/57446068/219001077-b6aad0c0-6544-458f-8c1d-071e06171161.png)
