### ISSUE TITLE
ApiSelect的onChange事件获取不到第二个参数

### ISSUE THREAD

**Issue by wangmin0314** [vbenjs/vue-vben-admin#2592]
![image](https://user-images.githubusercontent.com/23734878/222324491-6b2444ac-3844-424e-b86b-bd3b2f284544.png)
```
{
    field: 'projectId',
    label: '选择交易/项目',
    component: 'ApiSelect',
    required: true,
    componentProps: ({ formModel }) => ({
      api: ProjectListByCreateId,
      'show-search': true,
      labelField: 'projectName',
      resultField: 'data',
      valueField: 'id',
      onChange: (_val, option) => {
        console.log('option:', option);  //   option: undefined
        formModel.projectName = option.label;
      },
    }),
  }

**Comment by lzdjack** [comment]
是否是最新版本？

**Comment by wangmin0314** [comment]
> 是不是最新版本？

ApiSelect组件是最新版本

**Comment by tianyuan233** [comment]
![image](https://user-images.githubusercontent.com/33889406/225197074-efe26b71-3823-4458-b22d-6d0c576c8882.png)
断点调试加查看提交历史发现似乎是这里去掉了了 nextTick 导致的, @lzdjack

**Comment by Ddoudou** [comment]
这里如果加了nextTick，会导致apiselect第一次选择时校验必定错的问题，这个怎么解决呀

**Comment by manbuxinghe** [comment]
> 这里如果加了nextTick，会导致apiselect第一次选择时校试必定错误的问题，这个怎么解决呀

@Ddoudou 有解决这个问题吗？

**Comment by Ddoudou** [comment]
> 

暂时把nextTick替换成了setTimeout

**Comment by Angle-bo** [comment]
最新版这个问题如何解决？
