### ISSUE TITLE
BasicForm.vue下的return { ...props, ...unref(propsRef) } as FormProps TS报错实例化过深

### ISSUE THREAD

**Issue by sandwichLili** [vbenjs/vue-vben-admin#2603]
const getProps = computed((): FormProps => {
        return { ...props, ...unref(propsRef) } as FormProps
      })

增加其他的断言类型也没办法修改，目前没有阻碍代码运行，只是ts一直报错

**Comment by likui628** [comment]
请提供具体的代码位置
