### ISSUE TITLE
页面使用BasicTable并配置编辑行模式，在测试环境导致项目崩溃

### ISSUE THREAD

**Issue by JJJHChen** [vbenjs/vue-vben-admin#2614]
我的页面使用了BasicTable，在对表格中每一列进行配置中使用了editRow: true；在本地环境能正常运行，发布到linux下的测试环境，点开该页面，直接导致页面崩溃，经过测试发现，用了editRow就会出现该问题。ant-design-vue版本为3.2.14。

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
