### ISSUE TITLE
Rollup failed to resolve import***

### ISSUE THREAD

**Issue by wd603546401** [vbenjs/vue-vben-admin#2617]
Rollup failed to resolve import "node_modules/_ant-design-vue@3.2.15@/ant-design-vue/es/config-provider/style/index" from "src/App.vue".
This is most likely unintended because it can break your application at runtime

如上，代码拉下来，啥也没改动，npm run serve项目可以正常启动，但是npm run build时就报错了

**Comment by tianyuan233** [comment]
没有复现这个问题 用`pnpm`试试
```bash
cd vue-vben-admin

pnpm install

pnpm serve
```

**Comment by rmd1710714107** [comment]
大哥，你解决了吗，我也遇到这个错误了
