### ISSUE TITLE
Upload 组件示例中文件上传成功校验无法清除

### ISSUE THREAD

**Issue by zwtvip** [vbenjs/vue-vben-admin#2618]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

Upload 组件示例中文件上传成功校验无法清除

### 复现 Bug

https://vben.vvbin.cn/#/comp/upload 
![图片](https://i.postimg.cc/hjnZ9t4k/a316a0e682d4034f4fe581745b66c80.png)

## 系统信息

- 操作系统: window11
- Node 版本: 16.18.0
- 包管理器 (npm/yarn/pnpm) 及其版本: 7.28.0

**Comment by lzdjack** [comment]
已修复

**Comment by zwtvip** [comment]
> 已修复

好的，辛苦大佬
