### ISSUE TITLE
打包后，antv的Radio.Group和Radio.Button组件无法渲染

### ISSUE THREAD

**Issue by qishenliang** [vbenjs/vue-vben-admin#2626]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

打包后，antv的Radio.Group和Radio.Button组件无法渲染
![image](https://user-images.githubusercontent.com/30789373/224735667-390eeee7-e7c7-4e2f-ae46-6d913748a5c9.png)
除了截图的例子，在setup写法下，Radio.Group和Radio.Button都无法渲染出来，开发环境表现正常

### Reproduction

复现链接，参照官网预览  https://vben.vvbin.cn/#/comp/form/basic

## System Info

- Operating System: Windos
- Node version: 16.5.1
- Package manager (npm/yarn/pnpm) and version: 7.13.5

**Comment by gwq123456** [comment]
vite版本问题，我也遇到过，改成2.7.5我的就可以了

**Comment by qishenliang** [comment]
> vite版本问题，我也遇到过，改成2.7.5我的就可以了

原来如此，感谢你的宝贵答案
