### ISSUE TITLE
tinymce 上传图片，无法正常显示

### ISSUE THREAD

**Issue by Anima-No** [vbenjs/vue-vben-admin#2627]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

请清晰地描述此 Bug 的具体表现。
![微信截图_20230314164128](https://user-images.githubusercontent.com/44191876/224944500-f570550e-aca5-45d7-87c1-8e73924dcdaf.png)
点击图片上传后，显示的地址不正确，无法正常预览

### 复现 Bug

https://vben.vvbin.cn/#/comp/editor/tinymce/editor
点击富文本内上的图片上传，出来的地址有问题
## 系统信息

- 操作系统:Windows10
- Node 版本:v16.14.1
- 包管理器 (npm/yarn/pnpm) 及其版本:yarn

**Comment by tianyuan233** [comment]
是因为上传接口 405了

**Comment by ztt00** [comment]
这个问题该如何解决啊

**Comment by WWWsy03** [comment]
同问该如何解决这个问题

**Comment by Anima-No** [comment]
> 同问该如何解决这个问题

你要进去看源代码，然后实现那个上传接口，上传后会返回一个地址，就可以正常渲染了

**Comment by fengwenyi** [comment]
> > 同问该如何解决这个问题
> 
> 你要进去看源代码，然后实现那个上传接口，上传后会返回一个地址，就可以正常渲染了

你的说的是实现哪个函数，我看源码 这里默认 解析的url  

```java
      function handleChange(info: Record<string, any>) {
        const file = info.file;
        const status = file?.status;
        const url = file?.response?.url;
        const name = file?.name;

        if (status === 'uploading') {
          if (!uploading) {
            emit('uploading', name);
            uploading = true;
          }
        } else if (status === 'done') {
          emit('done', name, url);
          uploading = false;
        } else if (status === 'error') {
          emit('error');
          uploading = false;
        }
      }
```

**Comment by Anima-No** [comment]
> > > 同问该如何解决这个问题
> 
> > 
> 
> > 你要进去看源代码，然后实现那个上传接口，上传后会返回一个地址，就可以正常渲染了
> 
> 
> 
> 你的说的是实现哪个函数，我看源码 这里默认 解析的url  
> 
> 
> 
> ```ts
> 
>       function handleChange(info: Record<string, any>) {
> 
>         const file = info.file;
> 
>         const status = file?.status;
> 
>         const url = file?.response?.url;
> 
>         const name = file?.name;
> 
> 
> 
>         if (status === 'uploading') {
> 
>           if (!uploading) {
> 
>             emit('uploading', name);
> 
>             uploading = true;
> 
>           }
> 
>         } else if (status === 'done') {
> 
>           emit('done', name, url);
> 
>           uploading = false;
> 
>         } else if (status === 'error') {
> 
>           emit('error');
> 
>           uploading = false;
> 
>         }
> 
>       }
> 
> ```

不是这里，是富文本源码那里，有上传图片的接口到服务器，，需要实现，这里才会返回真正可以打开的url ，

**Comment by fengwenyi** [comment]
> > > > 同问该如何解决这个问题
> > 
> > 
> > > 
> > 
> > 
> > > 你要进去看源代码，然后实现那个上传接口，上传后会返回一个地址，就可以正常渲染了
> > 
> > 
> > 你的说的是实现哪个函数，我看源码 这里默认 解析的url
> > ```ts
> >       function handleChange(info: Record<string, any>) {
> > 
> >         const file = info.file;
> > 
> >         const status = file?.status;
> > 
> >         const url = file?.response?.url;
> > 
> >         const name = file?.name;
> > 
> > 
> > 
> >         if (status === 'uploading') {
> > 
> >           if (!uploading) {
> > 
> >             emit('uploading', name);
> > 
> >             uploading = true;
> > 
> >           }
> > 
> >         } else if (status === 'done') {
> > 
> >           emit('done', name, url);
> > 
> >           uploading = false;
> > 
> >         } else if (status === 'error') {
> > 
> >           emit('error');
> > 
> >           uploading = false;
> > 
> >         }
> > 
> >       }
> > ```
> 
> 不是这里，是富文本源码那里，有上传图片的接口到服务器，，需要实现，这里才会返回真正可以打开的url ，

你说富文本是 Editor 这个吗？是哪个方法 可以写个示例

我看他写的 ImgUpload 组件  然后这个组件里面用的 antdv 的 Upload 组件，这个组件 上传成功就会调 `handleChange` 。

**Comment by Anima-No** [comment]
> ImgUpload

对，所以你是不是要实现一下这个上传逻辑呢？

**Comment by fengwenyi** [comment]
> > ImgUpload
> 
> 对，所以你是不是要实现一下这个上传逻辑呢？

还是不太懂 ，照你的意思  我只改这句就行了呗：

```ts
const url = file?.response?.url;
```

那就改了源码了

这个获取返回的地址 没留自定义处理

**Comment by Anima-No** [comment]
> > > ImgUpload
> 
> > 
> 
> > 对，所以你是不是要实现一下这个上传逻辑呢？
> 
> 
> 
> 还是不太懂 ，照你的意思  我只改这句就行了呗：
> 
> 
> 
> ```ts
> 
> const url = file?.response?.url;
> 
> ```
> 
> 
> 
> 那就改了源码了
> 
> 
> 
> 这个获取返回的地址 没留自定义处理
可以查询富文本，相关的上传图片的插件，然后实现它，会更方便

**Comment by fengwenyi** [comment]
我是这样改的：
```ts
        // const url = file?.response?.url;
        const url = file?.response?.body?.ossUrl;
```
可以上传回显示
