### ISSUE TITLE
表单BasicForm，如果后端json有30个字段，前端只想处理10个，formSchema里配置10个，剩余20个会丢失

### ISSUE THREAD

**Issue by xiatiandegaga** [vbenjs/vue-vben-admin#2634]
const values = await validate();
只会取到10个值，传到后端就有问题了，请问怎么处理合适？formSchema里用 show: false配置剩下的20个字段太冗余了。

**Comment by xiatiandegaga** [comment]
有没办法绑定一个对象，而不是通过formSchema拼成一个对象

**Comment by xiatiandegaga** [comment]
![image](https://user-images.githubusercontent.com/47713355/225564531-53fce754-b9f4-4fb4-a29e-dba743c9afc6.png)
我定义一个对象，关联到useForm里的model，但似乎并没有双向绑定

**Comment by oooplz** [comment]
把其他字段都写上，但是提供 defaultValue 并且 ifShow: false
```
{
   fieldId: 'foo',
   defaultValue: 'bar',
   ifShow: false
}
```
