### ISSUE TITLE
新增/修改菜单有异常

### ISSUE THREAD

**Issue by tonghb** [vbenjs/vue-vben-admin#2636]
![image](https://user-images.githubusercontent.com/14266782/225917740-c578ba8f-9c35-4bd4-829f-a5f8bf2b7ead.png)

**Comment by tonghb** [comment]
> ![image](https://user-images.githubusercontent.com/14266782/225917740-c578ba8f-9c35-4bd4-829f-a5f8bf2b7ead.png)

红框内的应该是可以选择的按钮，在开发时是可以显示的，但打包后就变成如图所示，官网也是如此。

**Comment by tonghb** [comment]
好像是所有的RadioButtonGroup组件打包后都有问题，开发时是可以正常显示

**Comment by tonghb** [comment]
经过检查所有的RadioButtonGroup打包后都不能正常显示使用，如组件-Form-基础表单-基础字段-字段10
![image](https://user-images.githubusercontent.com/14266782/226084338-46b03612-3b0f-4078-b52f-e4bf5d6e00b6.png)

**Comment by xingyuv** [comment]
http://vben.x-surge.com/

没发现这个问题啊

**Comment by tonghb** [comment]
> http://vben.x-surge.com/
> 
> 没发现这个问题啊
https://vben.vvbin.cn/#/system/menu
我是从这个网址看的有这个问题，现在官网变了？而且我自己在本地打包预览后也有这个问题。

**Comment by xingyuv** [comment]
> > http://vben.x-surge.com/
> > 没发现这个问题啊
> > https://vben.vvbin.cn/#/system/menu
> > 我是从这个网址看的有这个问题，现在官网变了？而且我自己在本地打包预览后也有这个问题。

我是自己改了改，升级到vite4了https://github.com/xingyuv/vue-vben-admin

**Comment by tonghb** [comment]
> > > http://vben.x-surge.com/
> > > 没发现这个问题啊
> > > https://vben.vvbin.cn/#/system/menu
> > > 我是从这个网址看的有这个问题，现在官网变了？而且我自己在本地打包预览后也有这个问题。
> 
> 我是自己改了改，升级到vite4了https://github.com/xingyuv/vue-vben-admin

看了，你用了最新的script setup的语法，应该没有影响才对。是要升级到vite4来解决吗？好奇怪的bug

**Comment by elvisii** [comment]
不知道什么原因，打包之后，RadioButtonGroup组件没有被正确解析。
<img width="850" alt="1681314513404" src="https://user-images.githubusercontent.com/12507353/231512347-3faa30ad-20d1-45f8-a419-b393389657a3.png">

**Comment by SLiGe** [comment]
我升级到vite4后正常了
