### ISSUE TITLE
侧边栏图标不能用组件库的图标

### ISSUE THREAD

**Issue by yx-lxy** [vbenjs/vue-vben-admin#2638]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by yx-lxy** [comment]
请问侧边栏的图标 为什么我用组件的库的图标不生效

**Comment by anncwb** [comment]
Hello @yx-lxy. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.
