### ISSUE TITLE
使用tinymce组件，只设置disabled时，第一次打开查看模式下含有该组件的弹窗，tinymce组件没有禁用。

### ISSUE THREAD

**Issue by czhsun** [vbenjs/vue-vben-admin#2640]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

请清晰地描述此 Bug 的具体表现。
使用tinymce组件时，只设置disabled时，第一次打开查看模式下含有该组件的弹窗，tinymce组件没有禁用。
```
     render: ({ model, field }) => {
        return h(Tinymce, {
          options: {
            // toolbar: true, //隐藏工具栏
            menubar: false, //隐藏菜单栏
            // inline: true, //开启内联模式
            // readonly: [ActionEnum.VIEW].includes(type.value),
            //readonly: ActionEnum.VIEW == type.value,
          },
          disabled: ActionEnum.VIEW == type.value,
          showImageUpload: false,
          value: model[field],
          onChange: (value: string) => {
            model[field] = value;
          },
        });
      },
```
分析原因，主要是封装该组件的代码中有同时实现了disabled禁用和readonly只读，二者的功能冲突导致的。
tinymce组件封装代码，位置src\components\Tinymce\src\Editor.vue
````
    const disabled = computed(() => {
        const { options } = props;
        const getdDisabled = options && Reflect.get(options, 'readonly');
        const editor = unref(editorRef);
        if (editor) {
          editor.setMode(getdDisabled ? 'readonly' : 'design');
        }
        return getdDisabled ?? false;
      });
      watch(
        () => attrs.disabled,
        () => {
          const editor = unref(editorRef);
          if (!editor) {
            return;
          }
          editor.setMode(attrs.disabled ? 'readonly' : 'design');
        },
      );
````
分析原因及解决办法：
watch监听disabled，第一次打开页面时editorRef值取不到，导致第一次打开页面时禁用功能失效，连续打开同一面也会一直失效，这是由于disabled值没有变化，editorRef值有值，监听回调也不执行。
可以同时监听editorRef和disabled解决。
用watchEffect，可以响应式追踪editorRef和disabled值变化，也可以解决该问题。
但是用disabled禁用有个缺陷，是没法控制上传按钮禁用，而且与readonly只读的功能重复，代码中需要配置disabled禁用和readonly只读两处都配置才能完全实现该组件的禁用功能。
而且代码中只配置disabled禁用时，会与readonly只读功能会冲突，导致禁用失效。
所以建议去掉watch监听的disabled禁用，只保留readonly只读的禁用功能。

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:  win10
- Node 版本:  v16.17.0
- 包管理器 (npm/yarn/pnpm) 及其版本:  yarn   1.22.19

**Comment by wangjue666** [comment]
@czhsun  你的写法问题，`tinymce`组件压根不支持 `disabled`属性, 如果要禁用需要传递 `options: { readonly: true }`
 
```
 {
      field: 'tinymce',
      component: 'Input',
      label: 'tinymce',
      defaultValue: 'defaultValue',
      rules: [{ required: true }],
      render: ({ model, field }) => {
        return h(Tinymce, {
          value: model[field],
          onChange: (value: string) => {
            model[field] = value;
          },
          options: { readonly: true },
        });
      },
    },
```
