### ISSUE TITLE
暗色模式下, 部分组件上会有一个白边

### ISSUE THREAD

**Issue by RealHeart** [vbenjs/vue-vben-admin#2651]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [*] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [*] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [*] 已在 Issues 中搜索了相关的关键词
- [*] 不是 ant design vue 组件库的 Bug

### 描述 Bug
![image](https://user-images.githubusercontent.com/24838944/228001113-8d4a4675-3846-487b-9edc-19ed58addab0.png)
![image](https://user-images.githubusercontent.com/24838944/228001273-e08c5550-5c3b-447c-aa97-3b53b67b1422.png)
![image](https://user-images.githubusercontent.com/24838944/228001307-acaee278-5909-4b64-a5e4-6933c9c8905c.png)

请清晰地描述此 Bug 的具体表现。

### 复现 Bug
https://vben.vvbin.cn/#/system/account
请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by WitMiao** [comment]
表单设计器 里的代码改的问题，不用的话建议去掉相关组件代码，打包时间也会快很多
