### ISSUE TITLE
[bug] 少了花括号

### ISSUE THREAD

**Issue by milcery** [vbenjs/vue-vben-admin#2659]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
/src/components/Form/src/hooks/useFormEvents.ts
useFormEvents 最后少了个花括号

**Comment by RealHeart** [comment]
#2655 已修复

**Comment by oooplz** [comment]
我写的，因为改的东西太多了，直接从编译器里复制过来的，没检查好，请 close issue
