### ISSUE TITLE
我想请问下，如果后台传对象不是数组，前端需要怎么处理啊

### ISSUE THREAD

**Issue by Lonely-SSH** [vbenjs/vue-vben-admin#2669]
![image](https://user-images.githubusercontent.com/35214837/229702501-c1aa97bf-73b5-45c6-bf5b-d5fea2d42cb0.png)
![image](https://user-images.githubusercontent.com/35214837/229702608-c4830a86-b0b2-4902-b961-df6b7d6b071f.png)

**Comment by Lonely-SSH** [comment]
![image](https://user-images.githubusercontent.com/35214837/229702775-db7120f9-820d-4122-a210-28434f962a99.png)
怎么解析这个数据呢

**Comment by ChunyuPCY** [comment]
使用 afterFetch，在接收到数据后，处理成前端需要的 list 数据
