### ISSUE TITLE
在做params传参时，刷新当前页面会导致params参数传递失败

### ISSUE THREAD

**Issue by wuyanfei86** [vbenjs/vue-vben-admin#2671]
在做params传参时，刷新当前页面会导致params参数传递失败
usePage.ts:49 
       
       [Vue Router warn]: Discarded invalid param(s) "id", "_redirect_type" when navigating. See https://github.com/vuejs/router/blob/main/packages/router/CHANGELOG.md#414-2022-08-22 for more details.

**Comment by coderwyd** [comment]
这和vben没啥关系吧

**Comment by wereppnn** [comment]
> 在做params传参时，刷新当前页面会导致params参数传递失败 usePage.ts:49
> 
> ```
>    [Vue Router warn]: Discarded invalid param(s) "id", "_redirect_type" when navigating. See https://github.com/vuejs/router/blob/main/packages/router/CHANGELOG.md#414-2022-08-22 for more details.
> ```
搞定了没

**Comment by 7kyun** [comment]
https://github.com/vbenjs/vue-vben-admin/pull/2753
