### ISSUE TITLE
浏览器console提示 Uncaught ReferenceError: Cannot access 'Icon' before initialization

### ISSUE THREAD

**Issue by yaoxiaoheng** [vbenjs/vue-vben-admin#2680]
最新版本调试运行，启动页面一直显示滚动加载，浏览器console提示 Uncaught ReferenceError: Cannot access 'Icon' before initialization，提示 src\components\Icon\index.ts 这个文件
![image](https://user-images.githubusercontent.com/3426073/230305201-d151ab0b-f21f-4515-9408-6c4453419185.png)
![image](https://user-images.githubusercontent.com/3426073/230305056-fbc6a85e-e3e4-4ae5-b720-914df64f52f5.png)
![image](https://user-images.githubusercontent.com/3426073/230305377-493229ed-7ebe-4d88-b243-5fb4323ccfb9.png)

**Comment by Secret1007** [comment]
+1

**Comment by EarhartZhao** [comment]
移除 export default Icon; 将 import Icon from 改为 import { Icon } from 可以解决;

**Comment by fspstudy** [comment]
移除 export default Icon;
把import { Icon } from '/@/components/Icon'; 改为 import Icon from '/@/components/Icon/src/Icon.vue';

**Comment by xingyuv** [comment]
https://github.com/vbenjs/vue-vben-admin/pull/2683
