### ISSUE TITLE
VITE_PUBLIC_PATH value setting not working

### ISSUE THREAD

**Issue by RakeshShrestha** [vbenjs/vue-vben-admin#2684]
Previously I was using /myappname/ folder and VITE_PUBLIC_PATH value was setup /myappname/ and it was working but with new releases after the value is not working

**Comment by SLiGe** [comment]
I also encountered this problem,Here's a solution:
edit the package.json:
```
"build": "cross-env NODE_ENV=production NODE_OPTIONS=--max-old-space-size=8192 pnpm vite build --base=/myappname/",
```

**Comment by RakeshShrestha** [comment]
Yes thanks for the fix now it is working on uri path also

**Comment by SLiGe** [comment]
#2822 
The reason is that the ```base``` has not been set.

**Comment by SLiGe** [comment]
#2822

**Comment by SLiGe** [comment]
> #2822 The reason is that the `base` has not been set.
