### ISSUE TITLE
咱说明文档底部留的qq群号码显示不存在，是写错了吗？

### ISSUE THREAD

**Issue by tengrenli** [vbenjs/vue-vben-admin#2699]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by wangjue666** [comment]
没有写错，现在讨论移动到qq频道里了， 在qq频道搜vben admin 即可
