### ISSUE TITLE
咱啥时候出一个最新版的精简版呢？

### ISSUE THREAD

**Issue by tengrenli** [vbenjs/vue-vben-admin#2700]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by oooplz** [comment]
我不会说完整版是真好用，但这是事实
