### ISSUE TITLE
BasicTable  BasicForm 主动调用搜索

### ISSUE THREAD

**Issue by Anima-No** [vbenjs/vue-vben-admin#2702]
### Subject of the feature

就是我们在用BasicTable的时候，有BasicForm开启搜索情况下。经常在一些功能没办法满足，我们就需要自己render重新写一个组件，比如我弄了一个按钮的集合，我想点击这个按钮后直接调用查询功能，此时我发现好像都不知道怎么去调用他，目前render内出来的有参数schema，values，model，field像componentProps内的formActionType可以调用到submit(），但是现在是我render，就不懂怎么用了，尽管我自己重写一样的组件非render引入的，emit出来触发了componentProps内的formActionType，也会失败，失败原因大概是#2180 的问题，然后我加了useRuleFormItem各种下去，也不行，实在崩溃，所以还是想说怎么弄个简单的一点的，直接可以调用到当前的form内的一个方法
### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.
现在找不到，自己写也不太符合自己需求
### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by WitMiao** [comment]
点击按钮后直接调用查询功能, 是有现成的参数的：submitOnChange;
不管你的form渲染成什么样，数据绑定有变化就会调用submit.

**Comment by Anima-No** [comment]
> 点击按钮后直接调用查询功能, 是有现成的参数的：submitOnChange; 不管你的form渲染成什么样，数据绑定有变化就会调用submit.

了讴歌，我看到了。但是能不能只针对单个组件内有这个效果，formConfig配置submitOnChange，这个每个值变化都会提交。能不能针对某个值有变化在提交。我看了在FormSchema这个类型内都没这种参数，有没有好的解决方案，比如
<code>
 {
    field: 'name',
    label: 姓名,
    component: 'Input',
    colProps: { span: 8 },
  },
</code>

这个变化了会提交，其余的变化还是要点击查询在进行提交
