### ISSUE TITLE
table组件增加一个表格设置工具的浏览器缓存

### ISSUE THREAD

**Issue by qwerlp** [vbenjs/vue-vben-admin#2703]
### Subject of the feature

table组件增加一个表格设置工具的浏览器缓存

### Problem

现在就是配置完表格的工具后，刷新又回到原来的状态了
![image](https://user-images.githubusercontent.com/42144393/231337967-d705171f-b745-45ad-8bb4-33b00c013351.png)

### Expected behaviour

希望能缓存每次操作的状态，刷新后不要回到初始状态

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by liangyouzhu** [comment]
同问这个有在考虑么

**Comment by GauharChan** [comment]
#2745
这个`pr`更改后，实现了你提出的问题。除非点击工具的重置、或者你代码中`setProps`、`setColumns`。否则`form`中的查询、`reload`不会重置工具

**Comment by qwerlp** [comment]
> #2745 这个`pr`更改后，实现了你提出的问题。除非点击工具的重置、或者你代码中`setProps`、`setColumns`。否则`form`中的查询、`reload`不会重置工具
不行呀，我的vben版本是2.8.0的，少了很多东西

**Comment by GauharChan** [comment]
> > #2745 这个`pr`更改后，实现了你提出的问题。除非点击工具的重置、或者你代码中`setProps`、`setColumns`。否则`form`中的查询、`reload`不会重置工具
> > 不行呀，我的vben版本是2.8.0的，少了很多东西

那肯定是要升级的呀兄弟，我提交了但是你不去升级，那我能怎么办。要是想验证我的实现有没有问题，可以到线上预览地址查看

**Comment by qwerlp** [comment]
> > > #2745 这个`pr`更改后，实现了你提出的问题。除非点击工具的重置、或者你代码中`setProps`、`setColumns`。否则`form`中的查询、`reload`不会重置工具
> > > 不行呀，我的vben版本是2.8.0的，少了很多东西
> 
> 那肯定是要升级的呀兄弟，我提交了但是你不去升级，那我能怎么办。要是想验证我的实现有没有问题，可以到线上预览地址查看

请问有没升级文档呢

**Comment by qwerlp** [comment]
> > > #2745 这个`pr`更改后，实现了你提出的问题。除非点击工具的重置、或者你代码中`setProps`、`setColumns`。否则`form`中的查询、`reload`不会重置工具
> > > 不行呀，我的vben版本是2.8.0的，少了很多东西
> 
> 那肯定是要升级的呀兄弟，我提交了但是你不去升级，那我能怎么办。要是想验证我的实现有没有问题，可以到线上预览地址查看

太多地方改动了，没有升级文档很难进行
