### ISSUE TITLE
你好，我发现console.log 放到ts文件下没反应

### ISSUE THREAD

**Issue by ckbabby** [vbenjs/vue-vben-admin#2704]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

vue-vben-admin\src\views\sys\login\useLogin.ts 例如这个文件我在
![图片](https://user-images.githubusercontent.com/22540944/231343847-c89bf063-a006-4309-b234-2c1706a2974c.png)
![图片](https://user-images.githubusercontent.com/22540944/231344287-675f665f-efc7-42d4-be09-e54f99fa1a0c.png)

这里分别写console.log("测试"） 和 alert(’测试‘) 发现console.log 无效,，但是我在vue 文件写console.log 是有效的
我已经检查过浏览器设置了，不知道是否跟 最新版ts.config 引用@vben/ts-config/vue-app.json 库有关，谢谢了

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by 3070631350** [comment]
我也遇到了同样的问题,在vue文件中可以console.log,在ts文件中无效

**Comment by speed-git** [comment]
我也遇到了，是什么原因？

**Comment by Samsany** [comment]
> 我也遇到了，是什么原因？

新版本改变了配置，要启用console和debug，得去vue-vben-admin/internal/vite-config/src/config/common.ts 修改配置。
<img width="828" alt="image" src="https://user-images.githubusercontent.com/45546251/231425376-0467c451-8f7d-4c04-bc92-85784f53072e.png">

**Comment by pamxy** [comment]
注掉了drop: ['console', 'debugger'] 直接pnpm vite还没有什么变化，直到我重新pnpm install后再pnpm vite貌似就OK了，有点神奇，不管了，反正可以了，谢谢！
