### ISSUE TITLE
2.10.0版本部分样式错乱

### ISSUE THREAD

**Issue by Samsany** [vbenjs/vue-vben-admin#2707]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ x ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ x ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ x ] 已在 Issues 中搜索了相关的关键词
- [ x ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

新版本部分样式异常

### 复现 Bug

例如图片预览
![Snipaste_2023-04-12_17-57-57](https://user-images.githubusercontent.com/45546251/231426439-a6bb3bd6-997c-4330-b17d-9316356edf86.png)

## 系统信息

- 操作系统:
- Node 版本: node16.20.0
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 8.1.0

**Comment by wmf1993** [comment]
Add the following CSS code to your CSS file:  
```
ul {
  list-style: none;
  margin: 0;
  padding: 0;
}

img, svg, iframe {
  display: block;
  vertical-align: middle;
}
```
