### ISSUE TITLE
2.8.0 basic form 插槽

### ISSUE THREAD

**Issue by 2084796919** [vbenjs/vue-vben-admin#2709]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

在basticform当中使用插槽好像我发完成替换
vbenadmin 2.8.0中 basicform组件 使用插槽不生效
<BasicForm layout="inline" @register="registerForm" :max-height="520">
      <template #[stickReplacePn]="{ model, onChange }">
        <a-input :value="model" @input="onChange" placeholder="请输入晶棒pn" />
      </template>
    </BasicForm>
schme是这样定义的 
 {
    field: 'stickReplacePn',
    label: '批次号',
    required: true,
    component: 'Input',
    componentProps: {
      slotName: 'stickReplacePn',
    },
  },

### 复现 Bug

vbenadmin 2.8.0中 basicform组件 使用插槽不生效
<BasicForm layout="inline" @register="registerForm" :max-height="520">
      <template #[stickReplacePn]="{ model, onChange }">
        <a-input :value="model" @input="onChange" placeholder="请输入晶棒pn" />
      </template>
    </BasicForm>
schme是这样定义的 
 {
    field: 'stickReplacePn',
    label: '批次号',
    required: true,
    component: 'Input',
    componentProps: {
      slotName: 'stickReplacePn',
    },
  },

## 系统信息

- 操作系统:
- Node 版本: 16
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm

**Comment by acegank** [comment]
#stickReplacePn ？

**Comment by Anima-No** [comment]
#[stickReplacePn] ？？？
不应该是 #stickReplacePn？
