### ISSUE TITLE
子菜单为顶部TOP_MENU 无法打开对应路由的页面，

### ISSUE THREAD

**Issue by kiwimg** [vbenjs/vue-vben-admin#2718]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
代码分支 ：vue-vben-admin-thin
master 分支无此问题
    // Menu mode
    mode: MenuModeEnum.HORIZONTAL,
    // Menu type
    type: MenuTypeEnum.TOP_MENU,

子菜单 无法打开对应路由的页面，但是通过设置为 VERTICAL 就可以了打开

### 复现 Bug
// Menu configuration
  menuSetting: {
    // sidebar menu bg color
    bgColor: SIDE_BAR_BG_COLOR_LIST[0],
    //  Whether to fix the left menu
    fixed: true,
    // Menu collapse
    collapsed: false,
    // When sider hide because of the responsive layout
    siderHidden: false,
    // Whether to display the menu name when folding the menu
    collapsedShowTitle: false,
    // Whether it can be dragged
    // Only limited to the opening of the left menu, the mouse has a drag bar on the right side of the menu
    canDrag: false,
    // Whether to show no dom
    show: true,
    // Whether to show dom
    hidden: false,
    // Menu width
    menuWidth: 210,
    // Menu mode
    mode: MenuModeEnum.INLINE,
    // Menu type
    type: MenuTypeEnum.TOP_MENU,
    // Menu theme
    theme: ThemeEnum.DARK,
    // Split menu
    split: false,
    // Top menu layout
    topMenuAlign: 'start',
    // Fold trigger position
    trigger: TriggerEnum.HEADER,
    // Turn on accordion mode, only show a menu
    accordion: true,
    // Switch page to close menu
    closeMixSidebarOnChange: false,
    // Module opening method ‘click’ |'hover'
    mixSideTrigger: MixSidebarTriggerEnum.CLICK,
    // Fixed expanded menu
    mixSideFixed: false,
  },

## 系统信息

- 操作系统: windows
- Node 版本: 16
- 包管理器 (npm/yarn/pnpm) 及其版本: 最新

**Comment by zjx9772** [comment]
![1683187103932](https://user-images.githubusercontent.com/32201437/236145302-bdaa2e76-e508-45e4-be60-bc1ffa6c3e94.png)

修改Menu组件下的BasicMenu.vue文件

**Comment by likui628** [comment]
vue-vben-admin-thin不维护了，在vue-vben-admin最新版本上试一下
