### ISSUE TITLE
怎么修改打包后的输出路径啊

### ISSUE THREAD

**Issue by pzting** [vbenjs/vue-vben-admin#2726]
![image](https://user-images.githubusercontent.com/24772628/233302817-42a477d1-9db5-417a-9747-e6ea3ae08fef.png)
internal
这个是啥，没用过啊。
需求就是文件名是时间戳，在json里是写不了方法的
vben2.10.0设置路径没用，也找不到
![image](https://user-images.githubusercontent.com/24772628/233308775-49d05300-33be-45b0-969e-c3456cf953cf.png)

而且看文档搜这个路径也根本搜不到哪里用过
![image](https://user-images.githubusercontent.com/24772628/233519088-1948d3c9-2e05-455a-b9f1-a56d6a27460d.png)

**Comment by M69W** [comment]
看下文档。

**Comment by HelloYu** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/6134340/f75980a5-480a-4093-9aac-684b91d8b7ee)
给Vite配置加个base，配置被封装成库真的不是一个好的设计.......

**Comment by lzdjack** [comment]
文档对2.9以下的友好，以上就看源码阅读能力了，封装成库在2.x版本好处还没体现出来，3.0版本就能体现出这么设计的好处了
