### ISSUE TITLE
BasicColumn里的dataIndex，FormSchema里的field 不支持 a.b.c 这种形式

### ISSUE THREAD

**Issue by 157677678** [vbenjs/vue-vben-admin#2727]
BasicColumn里的dataIndex，FormSchema里的field 不支持 a.b.c 这种形式
我现在使用需要将数据重新解构才行
这个antd是支持的，如果方便希望能改一下。

**Comment by Anima-No** [comment]
> BasicColumn里的dataIndex，FormSchema里的field 不支持 a.b.c 这种形式 我现在使用需要将数据重新解构才行 这个antd是支持的，如果方便希望能改一下。

可以的。要用数组，比如  dataIndex: ['a', 'b','c],

**Comment by 157677678** [comment]
> 
能写一下具体指点一下么？  ['a', 'b','c] 这个是数组啊？ 我的结构是a.b， 改成['a','b']?

**Comment by Anima-No** [comment]
> > 
> 
> 能写一下具体指点一下么？ ['a', 'b','c] 这个是数组啊？ 我的结构是a.b， 改成['a','b']?

是

**Comment by 157677678** [comment]
> > > 
> > 
> > 
> > 能写一下具体指点一下么？ ['a', 'b','c] 这个是数组啊？ 我的结构是a.b， 改成['a','b']?
> 
> 是

dataIndex 确实可以 感谢 
不过 field 不行 因为field 就是string 
是有别的写法？  还是说 form里不能支持么？

**Comment by Anima-No** [comment]
field
直接点就好了user.name

**Comment by Anima-No** [comment]
> > > > 
> > > 
> > > 
> > > 能写一下具体指点一下么？ ['a', 'b','c] 这个是数组啊？ 我的结构是a.b， 改成['a','b']?
> > 
> > 
> > 是
> 
> dataIndex 确实可以 感谢 不过 field 不行 因为field 就是string 是有别的写法？ 还是说 form里不能支持么？

我弄了一个群133084854 扣扣的
