### ISSUE TITLE
升级到V2.10.0之后、暗黑主题、主题、系统主题、菜单主题、顶栏主题、都不展示了。

### ISSUE THREAD

**Issue by wmz1930** [vbenjs/vue-vben-admin#2731]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

升级到V2.10.0之后、暗黑主题、主题、系统主题、菜单主题、顶栏主题、都不展示了。

### 复现 Bug

现在了最新的V2.10.0 发布版本，主题设置没有了。

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by xingyuv** [comment]
都移除了

**Comment by wmz1930** [comment]
> 都移除了

移出的原因是？

**Comment by nguyenhan-se** [comment]
> 

for vben3 alpha, if you want stable version check release 2.9.0

**Comment by xingyuv** [comment]
antdv 4.0 移除了less采用了cssinjs方案，所有的主题都要重写

**Comment by nicefan** [comment]
2.10版也没有用antdv4.0啊。太随意了

**Comment by nicefan** [comment]
2.10版也没有用antdv4.0啊。太随意了

**Comment by wangjue666** [comment]
https://github.com/vbenjs/vue-vben-admin/pull/2947 这个pr恢复了暗黑主题切换

**Comment by 2125zyrc** [comment]
> > 都移除了
> 
> 移出的原因是？

代码被注释了  但是放开之后  依旧有 bug  目前我测了 修改主题是无法生效的
