### ISSUE TITLE
导出 Excel 表头错位

### ISSUE THREAD

**Issue by Mr-LiuDC** [vbenjs/vue-vben-admin#2734]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

我将表格数据导出为 Excel 时，不调整表头时导出正常，调整 header 后导出的 Excel 表头和数据错位了，如下图：
![1682320808557](https://user-images.githubusercontent.com/18117854/233926139-1ef88ec7-1684-4e44-875b-aa98f00bb0d9.png)

导出 Excel 的代码：
```
      function defaultHeader({ filename, bookType }: ExportModalResult) {
        // 默认Object.keys(data[0])作为header
        // 只导出以下字段，并且重新调整表头
        const dataToExport = state.expData.map((item) => {
          return {
            name: item.name,
            alias: item.alias,
            type: item.type,
            commonMeasure: item.commonMeasure,
            inventory: item.inventory,
            measureUnit: item.measureUnit,
            createdDate: item.createdDate,
          };
        });
        jsonToSheetXlsx({
          data: dataToExport,
          filename,
          header: [
            '药品名称',
            '药品别名',
            '药品类型',
            '常用剂量',
            '现有库存',
            '剂量单位',
            '添加时间',
          ],
          write2excelOpts: { bookType },
        });
      }
```

## 系统信息

操作系统: Windows 10 专业版
Node 版本: v14.19.3
包管理器 (npm/yarn/pnpm) 及其版本: npm 6.14.17， pnpm 7.11.0

**Comment by anncwb** [comment]
Hello @Mr-LiuDC. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by jiaowoxiaobala** [comment]
@Mr-LiuDC  把`header`改成这样，这个`Issue`可以关掉了。

```js
header: {
  name: '药品名称',
  alias: '药品别名',
  type: '药品类型',
  commonMeasure: '常用剂量',
  inventory: '现有库存',
  measureUnit: '剂量单位',
  createdDate: '添加时间',
}
```
