### ISSUE TITLE
使用proxy后在浏览器输入前端地址导致后端接收的参数丢失

### ISSUE THREAD

**Issue by s641135196** [vbenjs/vue-vben-admin#2736]
使用:  vite v2.9.5
前端地址:  http://localhost:3100
后端地址:    http://localhost:44378

.env.development配置文件. 
VITE_PROXY = [["/api","http://localhost:44378/api","/upload","http://localhost:44378/api"]]

如果在浏览器输入前端地址
http://localhost3100/api/home/loginByWechat?id=1&reload=true&redirect=%2Fworkorder%2Fupdate
在后端接受不到?号后面的参数. 

如果直接使用后端地址  http://localhost:44378/api/home/loginByWechat?id=1&reload=true&redirect=%2Fworkorder%2Fupdate
是没有问题的. 

测试在新建的vue项目中参数并不会丢失. 
这要修改vue-admin中哪个配置文件了?

**Comment by hyperq** [comment]
建议先搞清楚什么叫前后端分离

**Comment by s641135196** [comment]
> 建议先搞清楚什么叫前后端分离
  这块我还是清楚的,  不过小项目为了方便把前后端是放一起的了. 
 应该是vue的web服务器转发到后端时丢失了参数.

**Comment by shiyi-yujian** [comment]
我也遇到了。你看看是不是这个问题
https://github.com/vbenjs/vue-vben-admin/issues/3203
把vite-plugin-html的版本升级到3.2.1及以上就行
