### ISSUE TITLE
table使用usesearchForm apiSelect组件重复请求

### ISSUE THREAD

**Issue by penguinlin** [vbenjs/vue-vben-admin#2738]
![image](https://user-images.githubusercontent.com/25530732/234212906-6e72dfbc-42f0-42f2-84c5-ffe4cddf20d5.png)

**Comment by Alkaidcc** [comment]
same issue

**Comment by lijian3828940** [comment]
+1

**Comment by wangjue666** [comment]
https://github.com/vbenjs/vue-vben-admin/pull/3107 这个PR应该解决了
