### ISSUE TITLE
Modal设置destroyOnClose=true，第二次打开弹框 Description 组件 无法正常渲染

### ISSUE THREAD

**Issue by MvM-OLO** [vbenjs/vue-vben-admin#2743]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

创建了一个Modal组件，其中包裹了一个Description组件，且设置了destroy-on-close

### 复现 Bug

第二次打开弹框 Description 组件 无法正常渲染

## 系统信息

- 操作系统:win10
- Node 版本:node 16。19.1
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm 7.30.0

**Comment by SanpLee** [comment]
我也遇到这个问题

**Comment by anncwb** [comment]
Hello @MvM-OLO. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.
