### ISSUE TITLE
tabs选项卡渲染问题，点击没加载过的菜单页，新增的选项卡不是追加到最后

### ISSUE THREAD

**Issue by smirkQAQ** [vbenjs/vue-vben-admin#2744]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

点击菜单添加新的选项卡不是追加到最后，或者拖拽两个tabs选项卡排序后现有的其余两个选项卡也会互相改变位置。
经过排查tableList数据是正确的排序，视图不一致。有可能是渲染的问题

### 复现 Bug

三个tabs选项卡来回拖拽排序可触发bug。

## 系统信息

- 操作系统: win11
- Node 版本:  v16.5
- 包管理器 (npm/yarn/pnpm) 及其版本:  pnpm: 8.3.1

**Comment by likui628** [comment]
重现步骤:
1. 打开http://localhost:5173/#/ 进入`分析页`
2. 打开http://localhost:5173/#/dashboard/workbench 进入`工作台`
3. 将`分析页`拖到`工作台`后面
4. 打开http://localhost:5173/#/feat/icon 进入`图标`
![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/95e5a8e7-8fea-4b54-98d7-30df632d8fc3)

**Comment by likui628** [comment]
tableList顺序是正确的，不知道为什么v-for遍历的顺序不同

**Comment by DesignHhuang** [comment]
> tableList顺序是正确的，不知道为什么v-for遍历的顺序不同

虽然tablist是正确的，但是拖拽后sortablejs貌似改变了dom，可能导致v-for无法检测到变化，所以需要更新一下这个组件。
