### ISSUE TITLE
前端小白真的很蒙，哪来的build文件夹啊

### ISSUE THREAD

**Issue by qing-root** [vbenjs/vue-vben-admin#2747]
根据官网一步步来，git clone下来后用pnpm安装了所有依赖，但这里生成图标文件夹使用yarn gen:icon的时候
![image](https://user-images.githubusercontent.com/30001685/235691337-e37e2832-416c-4eee-a7cb-e356b28c0969.png)

请问哪里来的./build/generate/icon/index.ts文件啊？

**Comment by WitMiao** [comment]
在这一次提交后被删了：[perf: Refactor vite configuration](https://github.com/vbenjs/vue-vben-admin/commit/5e99463cd0d6f7a642a8e06624a7de7ad4b79fac#diff-29fc99fda5e2f98e0fcfc085a59a4c4bb59e6a587ac802c4b3eb7c5316ae2419)

**Comment by cnelf** [comment]
2.9重构了一版，估计文档没跟上

**Comment by wangjue666** [comment]
现在文档会陆续更新

**Comment by wuzhican** [comment]
所以现在，gen icon要如何处理

**Comment by M69W** [comment]
文档还没更新
