### ISSUE TITLE
页面开启了缓存，打开tab页面不会重新发送请求

### ISSUE THREAD

**Issue by zfing** [vbenjs/vue-vben-admin#2750]
### 问题

页面开启了缓存，遇到的情况：一个详情页面组件，唯一的组件name。打开多个详情tab（eg：A tab， B tab），当关闭了A tab后，再点击打开A tab，此时的A tab页面不会重新发送请求。若A B tab都关闭（此时详情页面组件都关了），再打开详情tab就会有请求。
### 期望
开启页面缓存后，打开多个tab时候，已存在tab栏的页面，随意切换不会发生请求（这个目前没问题），**新打开**的tab页需要即使在缓存页面的情况下也要有新的请求发生。

**Comment by ma-lihui** [comment]
在\src\store\modules\multipleTab.ts中的addTab方法中
```js
      async addTab(route: RouteLocationNormalized) {
           ...
          // 给route.meta加上uid，用于keep-alive的缓存
          if (route.meta) {
            route.meta.uid = getIncrementedKey();
          }
          this.tabList.push(route);
      }
```
在src/layouts/page/index.vue中使用这个uid作为component的key

**Comment by likui628** [comment]
缓存时打开tab页面不重新发送请求是合理的，
既要缓存又要重新发送请求，在`onActivated` 生命周期里去处理
