### ISSUE TITLE
Cannot find module '@vben/shared' or its corresponding type declarations

### ISSUE THREAD

**Issue by mamba-in** [vbenjs/vue-vben-admin#2751]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

@vben/shared引用报错

### 复现 Bug

项目中引入@vben/shared的地方

## 系统信息

- 操作系统: MacOS 12.5.1
- Node 版本: 17.3.0
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 8.3.1

**Comment by wangjue666** [comment]
这个项目没有引入过这个包，npm上也没有这个包
