### ISSUE TITLE
菜单编辑是 上级下拉选项中 出现多个重复选项

### ISSUE THREAD

**Issue by xuanbee** [vbenjs/vue-vben-admin#2755]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

系统管理 -> 菜单编辑 :  第二次 以及更多次 点击编辑按钮  编辑弹窗上上级菜单 下拉选项框中会出现重复选项 

### 复现 Bug

多次点击编辑按钮

## 系统信息

- 操作系统:
- Node 版本:   16.17.1
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm

**Comment by HelloYu** [comment]
一样的问题，而且还会遇到卡顿~
