### ISSUE TITLE
Cannot destructure property 'token' of 'data' as it is undefined.

### ISSUE THREAD

**Issue by huashuiwujiale** [vbenjs/vue-vben-admin#2758]
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/72371848/236485750-e1e0046a-04e4-497e-afab-d9440e8fa332.png">
不知道为什么说token未定义

**Comment by ZhouZiXuan-imb** [comment]
@huashuiwujiale 你好，我也出现了同样的问题，原因可能是因为你把/mock/_util.ts文件中的resultSuccess函数的返回值result键名改为了data。这种行为可以理解为服务端返回数据结构与mock时不符，所以需要修改返回的数据结构，我也是这样操作的。原因是在/src/utils/index.ts中解构了默认的result变量，找不到所以报错data is undefined，解决方式就是找到/src/utils/index.ts
<img width="653" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/55371133/67620e02-b4de-4a86-8cf3-ccd7b88e66ba">

**需要注意的是 transformResponseHook函数的参数res的类型是AxiosResponse<Result>，这里需要找到Result类型接口，把Result中原本的result字段改为data即可解决问题**

**Comment by phphy** [comment]
同样的问题也是困住我好久
