### ISSUE TITLE
图标不对齐

### ISSUE THREAD

**Issue by fzxiang** [vbenjs/vue-vben-admin#2763]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
最新版本UI表现有点问题
![image](https://user-images.githubusercontent.com/38209301/236790153-a1e0a44e-5ad5-48b5-94e8-cb91511d3c6f.png)

请清晰地描述此 Bug 的具体表现。
下载最新版本，` pnpm dev`启动服务，登录后观察，所有非`.app-iconify`图标类没有对齐，考虑是否未兼容

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"

- Node 版本: v16
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm v8.4.0

**Comment by kissIce** [comment]
span.anticon:not(.app-iconify) {
    vertical-align: 0.125em!important;
}
这行css导致的没对齐，注释即可
