### ISSUE TITLE
加载慢的问题能不能修复一下？

### ISSUE THREAD

**Issue by hdtopku** [vbenjs/vue-vben-admin#2764]
线上环境，5M带宽，恐怖的11.07秒。不要说第一次加载慢后面会快，手机经常杀后台，每次打开都要等待10几秒，体验真的非常非常差了。希望把框架做精简好用，而不是大而全

### 描述 Bug
![image](https://user-images.githubusercontent.com/14859466/236979531-29a7e124-3299-4707-b80e-bfb2103b9988.png)

## 系统信息

- 操作系统: linux
- Node 版本: v16.14.2
- 包管理器 (npm/yarn/pnpm) 及其版本: yarn, 1.19.0

**Comment by hdtopku** [comment]
vue3本意是快，从这点上说，vben倒退了

**Comment by TengChongChong** [comment]
<img width="712" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/11783658/319155fb-a1a6-4701-b61a-94568c9693ac">
开启gzip之类的试试呢？

**Comment by xingyuv** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/41043753/06265d41-cc82-4ece-a72d-cb0532d9d4b2)
确实

**Comment by hyperq** [comment]
你这个数据有8M 带宽才5M 就是说服务器流出最大流量是5/8=0.625m/s 那么传输12秒难道不合理吗
给你几个建议:
1.开启gzip压缩
2.服务器使用按量付费模式,尽量加大服务器的带宽
3.考虑将前端的js和css文件上传到类似阿里云oss服务器上

**Comment by hdtopku** [comment]
开启gzip确实快了，还需要5s，还有没有办法能3s加载出来？
![image](https://github.com/vbenjs/vue-vben-admin/assets/14859466/d1883129-1a61-477c-a161-72e21a331749)

**Comment by 3070631350** [comment]
你有没有使用pageWrapper组件?我把pageWrapper组件去掉之后就变得很快了,不知道是不是这个组件的原因

**Comment by xiaochen1** [comment]
简直离谱，本地环境，进个首页，加载上千个文件， 几分钟了还在那转转转。。。
<img width="1440" alt="QQ20240420-201127@2x" src="https://github.com/vbenjs/vue-vben-admin/assets/20479179/18727df1-cf3c-4852-ac0d-a427ed745502">
