### ISSUE TITLE
带表单和列筛选项的table 点击表单中的重置，无法重置table列中筛选条件

### ISSUE THREAD

**Issue by lj350201364** [vbenjs/vue-vben-admin#2769]
带表单和列筛选项的table 点击表单中的重置，无法同时重置table列中筛选条件

**Comment by DesignHhuang** [comment]
form的重置只是重置表单。若要同时控制Table中的筛选和排序的话，可以通过代码来实现。具体的代码实现可以参考：https://www.antdv.com/components/table-cn#components-table-demo-reset-filter

**Comment by likui628** [comment]
> form的重置只是重置表单。若要同时控制Table中的筛选和排序的话，可以通过代码（控制columns属性）来实现。具体的代码实现可以参考：https://www.antdv.com/components/table-cn#components-table-demo-reset-filter

有道理，可以提供clearFilters，clearSorter函数

**Comment by wangjue666** [comment]
@lj350201364  可以使用 `basicform resetFunc` 这个钩子函数

![1697274697742](https://github.com/vbenjs/vue-vben-admin/assets/24707417/82fdffe0-5a01-4813-9902-c91245457e02)
