### ISSUE TITLE
main分支升级antdv 4.0版本运行报错

### ISSUE THREAD

**Issue by holiy930561** [vbenjs/vue-vben-admin#2771]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
main 分支 antdv升级运行报错，"ant-design-vue": "^4.0.0-beta.4",
请清晰地描述此 Bug 的具体表现。
![image](https://github.com/vbenjs/vue-vben-admin/assets/63273780/80afa180-72d7-4ac9-90ff-15fd548a72c2)

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本: v19.1.0
- 包管理器 (npm/yarn/pnpm) 及其版本:
pnpm: 8.5.0

**Comment by frankchen211** [comment]
你好，请问你的会出现样式不对的情况吗？是如何解决的呢？

**Comment by frankchen211** [comment]
> 解决了，antdv 4.0版本移除对 ant-design-vue less的引用，采用 CSS-in-JS，更好地支持动态主题 <ConfigProvider :theme="{ token: { colorPrimary: themePrimaryColor, }, }"
> 
> >

你好，请问你的会出现样式不对的情况吗？是如何解决的呢？
