### ISSUE TITLE
thin 精简版本地开发项目启动非常慢，

### ISSUE THREAD

**Issue by huanglei-0** [vbenjs/vue-vben-admin#2779]
每次改一点东西，页面都要等很久，想问问有没有什么方案可以解决这个问题

![image](https://github.com/vbenjs/vue-vben-admin/assets/52777338/d48390e2-3f06-4242-80c0-e51c7ca23b54)

**Comment by xingyuv** [comment]
精简版都好久没更新了，用master自己删一删吧

**Comment by huanglei-0** [comment]
> 精简版都好久没有更新了，用master自己删一删吧

现在拉最新的master 样式又好像有一些问题，还有主题开关和暗黑模式也不见了

**Comment by allen-lhj** [comment]
主题开关更新依赖前去掉了，现在应该恢复了

**Comment by huanglei-0** [comment]
> 主题开关更新依赖前去掉了，现在应该恢复了

我拉的就是最新的master 代码 没有额，有联系方式可以私信嘛

**Comment by hfpp2012copy** [comment]
不会慢呀 https://www.qiuzhi99.com/playlists/vben-login.html
