### ISSUE TITLE
请问怎么在data.ts中使用异步枚举

### ISSUE THREAD

**Issue by huangtian615** [vbenjs/vue-vben-admin#2780]
<img width="335" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/36736809/cd11d72d-aa7c-41d1-bcc0-e6186613ad11">

componentProps中的options是异步枚举数据该怎么优雅的替换呀？

**Comment by WitMiao** [comment]
拿到数据后用updateSchema：
updateSchema({field:'riskSts',componentProps: {options:riskStsOptions},})
