### ISSUE TITLE
项目重新部署时，左上角的用户dropmenu无法打开，控制台报错

### ISSUE THREAD

**Issue by Jerry-bbq** [vbenjs/vue-vben-admin#2782]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

项目重新部署时，左上角的用户dropmenu无法打开，控制台报错，报错信息如下：
DropMenuItem.4d9386b3.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

### 复现 Bug

项目重新部署时，鼠标移动到用户上，左上角的用户dropmenu无法打开

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by Alkaidcc** [comment]
请问解决了吗？
