### ISSUE TITLE
新clone下来的项目yarn dev报错

### ISSUE THREAD

**Issue by Dwjem** [vbenjs/vue-vben-admin#2783]
### 描述 Bug

按照[本地运行文档](https://doc.vvbin.cn/guide/introduction.html#%E6%9C%AC%E5%9C%B0%E8%BF%90%E8%A1%8C%E6%96%87%E6%A1%A3)执行到yarn dev时项目报错
![image](https://github.com/vbenjs/vue-vben-admin/assets/96096980/4ed9d6e2-b65c-4f18-a74a-8d2e53722431)
![image](https://github.com/vbenjs/vue-vben-admin/assets/96096980/7477e2d9-d5e6-41cd-aeed-413499902e8c)

## 系统信息

- 操作系统:
- Node 版本: v16.14.0
- 包管理器 (npm/yarn/pnpm) 及其版本: yarn  v1.22.19

**Comment by kirklin** [comment]
最新版本加了 "preinstall": "npx only-allow pnpm"。所以只能使用pnpm安装项目

**Comment by 3070631350** [comment]
使用pnpm
