### ISSUE TITLE
pnpm i 时报错  Failed to unpack the tarball from

### ISSUE THREAD

**Issue by luyu3283** [vbenjs/vue-vben-admin#2786]
我在安装依赖时提示错误
 ERR_PNPM_TARBALL_EXTRACT  Failed to unpack the tarball from "https://packages.aliyun.com/5f1015f55fd102f22f6b7b02/npm/npm-registry/@typescript-eslint/eslint-plugin/-/eslint-plugin-5.57.1.tgz": Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?

**Comment by a303557339** [comment]
我也遇到了类似问题，请问解决了吗

**Comment by jacksplwxy** [comment]
> 我也遇到了类似问题，请问解决了吗

可以尝试用管理员权限执行安装命令，解压包的过程需要写入权限

**Comment by lzj2504476514** [comment]
> 我在安装依赖时提示错误  ERR_PNPM_TARBALL_EXTRACT  Failed to unpack the tarball from "https://packages.aliyun.com/5f1015f55fd102f22f6b7b02/npm/npm-registry/@typescript-eslint/eslint-plugin/-/eslint-plugin-5.57.1.tgz": Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?

使用npm i 可以解决
