### ISSUE TITLE
使用后端路由path为链接时报错，Route paths should start with a "/": "http://xxx" should be "/http://xxx".

### ISSUE THREAD

**Issue by dapeng0201** [vbenjs/vue-vben-admin#2790]
![image](https://github.com/vbenjs/vue-vben-admin/assets/28396334/0b78bae5-fa93-423e-9cb8-a7cdbded89b8)

![image](https://github.com/vbenjs/vue-vben-admin/assets/28396334/6fdddc59-dda5-4060-9bd9-a1676d982e09)

**Comment by dapeng0201** [comment]
在store/user.ts和router/permissionGuard.ts里都有添加路由操作  
添加try catch可以解决  也能正常跳转  但是看了好几个别的框架都没有做任何处理也能正常跳转，不知道什么原因
![image](https://github.com/vbenjs/vue-vben-admin/assets/28396334/aefe047d-7db6-401c-9906-930a0841d2b0)
![image](https://github.com/vbenjs/vue-vben-admin/assets/28396334/12b89e18-8cf0-4307-8b56-b17378f41fd9)

**Comment by likui628** [comment]
这个报错是vue router报的，
好几个其它框架不特别处理也支持外联有没有可能是vue router版本的问题
