### ISSUE TITLE
文档描述不对（指向了ant-d的2.x）应为3.x

### ISSUE THREAD

**Issue by queen2021** [vbenjs/vue-vben-admin#2796]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
<img width="931" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/21352238/f8f74f4b-b470-4a1a-a636-1683eddaf5df">

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by wangjue666** [comment]
https://github.com/vbenjs/vue-vben-admin-doc/commit/d286be2d7a4216d65ff22e15ec899a21e5faf08f 已更正

**Comment by queen2021** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
