### ISSUE TITLE
在table表格 在非第一页，切换标签， 表格页面会重置为第一页

### ISSUE THREAD

**Issue by lt0000007** [vbenjs/vue-vben-admin#2798]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
![image](https://github.com/vbenjs/vue-vben-admin/assets/76671218/490b88fb-8e23-4a7b-9cfb-476531441282)

请清晰地描述此 Bug 的具体表现。

在table表格 在非第一页，切换标签， 表格页面会重置为第一页
比如现在表格数据较多， 我点击查看第二页， 此时我切换导航标签。 
会发现表格，分页数据自动重置为第一页

## 系统信息

- 操作系统:  deepin 
- Node 版本:  v18.15.0
- 包管理器 (npm/yarn/pnpm) 及其版本:7.30.3

**Comment by wangjue666** [comment]
没有设置页面缓存吧？ 或者页面的name跟路由设置的name不一致,导致你切换标签，会重新加载页面
