### ISSUE TITLE
在较低版本Chrome开发时，无限转圈，无法到达登录页的问题

### ISSUE THREAD

**Issue by uncarbon97** [vbenjs/vue-vben-admin#2800]
【主要是给后来者指引以解决问题】

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
自Vben引入UnoCSS后，在较低版本的Chrome（如v87版本）开发时，会出现无限转圈，无法进入登录页

### 复现 Bug
使用 Chrome 87.0.4280.88 Windows x64版，运行最新代码即可

### 解决办法
在查阅`UnoCSS`仓库后找到issue
- https://github.com/unocss/unocss/issues/1461
- https://github.com/unocss/unocss/pull/2066

在Vben工程的`internal/vite-config/src/config/common.ts`文件增加：
```
plugins: [
    UnoCSS({
      presets: [presetUno(), presetTypography()],
      // Helio: 避免在较低版本Chrome(如v87)下开发时，无限转圈，无法到达登录页的问题
      hmrTopLevelAwait: false,
    }),
  ],
```

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by LJNaN** [comment]
thank you!!!!
