### ISSUE TITLE
表格选择点击卡顿

### ISSUE THREAD

**Issue by lsqGitHub716** [vbenjs/vue-vben-admin#2801]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

**表格数据，点击选中的时候，有明显延迟卡顿，表格数据也不是很多，为什么会出现这种情况？**

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本: 16.14.1
- 包管理器 (npm/yarn/pnpm) 及其版本:8.15.0

**Comment by js123321** [comment]
解决了吗

**Comment by anncwb** [comment]
Hello @lsqGitHub716. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.
