### ISSUE TITLE
updateSchema 更新不了TreeSelect组件的treeData属性，treeData被重复复制

### ISSUE THREAD

**Issue by shaojson** [vbenjs/vue-vben-admin#2803]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

请清晰地描述此 Bug 的具体表现。

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码
![999999999999999999微信截图_20230525082626](https://github.com/vbenjs/vue-vben-admin/assets/5163565/9abe0ebe-70b5-4d16-9366-4c613961aa6e)
![88888888888888微信截图_20230525082826](https://github.com/vbenjs/vue-vben-admin/assets/5163565/0601c593-de12-41a8-83fd-27a67e322a90)
![777777777777微信截图_20230525082903](https://github.com/vbenjs/vue-vben-admin/assets/5163565/2c03559c-fe52-42ca-8e5d-85caeb492e72)
![666666666666微信截图_20230525083135](https://github.com/vbenjs/vue-vben-admin/assets/5163565/ef43bbcb-5809-4fd8-944d-f607268f9654)

![5555555555555微信截图_20230525083347](https://github.com/vbenjs/vue-vben-admin/assets/5163565/cdb1b0e5-d586-4fc5-a400-428d3251e63b)

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by HelloYu** [comment]
使用deepClone复制一份数据

**Comment by my6521** [comment]
问题依然存在

**Comment by coderluojz** [comment]
#2831

**Comment by kingsaj1211** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/83277741/68b59dc4-5937-4d52-aab2-ded6dc17096b)
![image](https://github.com/vbenjs/vue-vben-admin/assets/83277741/4b1a4c59-13fd-49c1-986a-b15374acc590)
