### ISSUE TITLE
searchFormSchema里面的Select组件；支持远程搜索返回选项吗？

### ISSUE THREAD

**Issue by yonghui666** [vbenjs/vue-vben-admin#2805]
<img width="473" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/49012394/8196782a-54cf-4f75-b8d8-36bb83346a34">
请问；在searchFormSchema里面，这种需要根据用户输入的值，异步或者选项的情况这么写呢

**Comment by GauharChan** [comment]
事件需要拼上`on`，所以是`onSearch: fetchTags`

**Comment by hyperq** [comment]
有个组件是ApiSelect吧
