### ISSUE TITLE
设置了children可编辑表格失效问题

### ISSUE THREAD

**Issue by js123321** [vbenjs/vue-vben-admin#2815]
{
    title: 'GS资源数据',
    dataIndex: 'name66',
    children: [
      {
        title: '起',
        dataIndex: 'name55',
        edit: true,
        editRule: true,
        editComponent: 'Input',
      },
    ],
  },

**Comment by anncwb** [comment]
Hello @js123321. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by likui628** [comment]
请给出完整的重现代码
