### ISSUE TITLE
官网的左侧菜单混合模式样式丢失

### ISSUE THREAD

**Issue by shark-lajiao** [vbenjs/vue-vben-admin#2818]
![image](https://github.com/vbenjs/vue-vben-admin/assets/86769380/7d3f4665-fa8b-462c-86ac-41c27135685f)

**Comment by Zeng3531** [comment]
你的这个问题搞定了没有
我也遇到这个问题了

**Comment by zuihou** [comment]
已解决： https://github.com/vbenjs/vue-vben-admin/commit/c054d73fe631e93e50c7f3761ec8b81fdec6d146
