### ISSUE TITLE
新增菜单 上级菜单 下拉选框 查看选项 会不断多出来一组重复的列表

### ISSUE THREAD

**Issue by xmasuhai** [vbenjs/vue-vben-admin#2820]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

上级菜单 下拉选框 查看选项 会不断多出来一组重复的列表

### 复现 Bug

左侧菜单 > 系统管理 > 菜单管理 > 点击 新增菜单 > 点击 上级菜单 下拉选框 查看选项 > 退出（关闭 点击取消） 新增菜单 抽屉组件 > 点击 新增菜单 >  点击 上级菜单 下拉选框 查看选项 发现多出来一组重复的列表

## 系统信息

- 官网实例: https://vben.vvbin.cn/#/system/menu
- 操作系统: win10
- 浏览器版本: Chrome 113
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by coderluojz** [comment]
#2831
