### ISSUE TITLE
2.10.0版本无法打印console.log()的内容？

### ISSUE THREAD

**Issue by peteryang2016** [vbenjs/vue-vben-admin#2821]
为什么2.10.0版本在store/modules/user.ts中无法打印console.log()的内容？

**Comment by SLiGe** [comment]
看下环境变量配置文件
```VITE_DROP_CONSOLE=false```

**Comment by peteryang2016** [comment]
> 看下环境变化配置文件 `VITE_DROP_CONSOLE=false`

我的是2.10.0版本的，配置文件里是没有VITE_DROP_CONSOLE这个配置，你是哪个版本的？

**Comment by SLiGe** [comment]
> > 看下环境变化配置文件 `VITE_DROP_CONSOLE=false`
> 
> 我的是2.10.0版本的，配置文件里是没有VITE_DROP_CONSOLE这个配置，你是哪个版本的？

2.10.0, 你可以加上试试

**Comment by peteryang2016** [comment]
> > > 看下环境变化配置文件 `VITE_DROP_CONSOLE=false`
> > 
> > 
> > 我的是2.10.0版本的，配置文件里是没有VITE_DROP_CONSOLE这个配置，你是哪个版本的？
> 
> 2.10.0, 你可以加上试试

加过了，依然不起作用。 加到了这个文件中：.env.development

**Comment by peteryang2016** [comment]
> > > 看下环境变化配置文件 `VITE_DROP_CONSOLE=false`
> > 
> > 
> > 我的是2.10.0版本的，配置文件里是没有VITE_DROP_CONSOLE这个配置，你是哪个版本的？
> 
> 2.10.0, 你可以加上试试

而且我发现加debugger后看到的源码都是编译后的代码。这个也要配置吗

**Comment by masicheng** [comment]
目录\internal\vite-config\src\config\common.ts    
esbuild: {
    // drop: ['console', 'debugger'],
 },
 把这段注释了

**Comment by peteryang2016** [comment]
> 目录\internal\vite-config\src\config\common.ts esbuild: { // drop: ['console', 'debugger'], }, 把这段注解了

非常感谢，按照你指导的方式，console.log在控制台打印和加断点看源码的问题都已解决。
