### ISSUE TITLE
关于form的 resetFields 不生效问题

### ISSUE THREAD

**Issue by harrisyangbo** [vbenjs/vue-vben-admin#2832]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

当在页面中调用 resetFields 这个hook后，拿到的还是 resetFields 之前的值! 加了 await 也一样；通过排查发现源码中是如下这样写的：
<img width="904" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/17607468/65719f63-5425-400a-988b-02b0dc786229">

上面这种写法设计的原因是？想请教下是有什么其他考虑。或者说 是否可以改成如下这种写法呢？改成下面这种写法在使用的过程中是符合预期的
<img width="493" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/17607468/b592da23-5bf5-4dc1-a752-b591d5e807cf">

### Reproduction

```
watch(
  () => props.pageTarget,
  async (newVal, oldVal) => {
    await resetFields()
  },
  {
    deep: true,
    immediate: true,
  },
)
```

## System Info

- Operating System: 
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by harrisyangbo** [comment]
这项目是废了吗？ 没人维护了......

**Comment by harrisyangbo** [comment]
> 

没感觉对性能有什么影响呢

**Comment by harrisyangbo** [comment]
> resetFields

没感觉对性能有什么影响呢，使用await也是可以的吧

**Comment by likui628** [comment]
> > resetFields
> 
> 没感觉对性能有什么影响呢，使用await也是可以的吧

如果submitOnReset为true的话会涉及到重新查询，这个时间可能会比较长
https://github.com/vbenjs/vue-vben-admin/blob/main/src/components/Form/src/hooks/useFormEvents.ts#L81-L103

**Comment by harrisyangbo** [comment]
> > > resetFields
> > 
> > 
> > 没感觉对性能有什么影响呢，使用await也是可以的吧
> 
> 如果submitOnReset为true的话会涉及到重新查询，这个时间可能会比较长 https://github.com/vbenjs/vue-vben-admin/blob/main/src/components/Form/src/hooks/useFormEvents.ts#L81-L103

可是如果这么写的话，在业务页面中使用就会有如下问题：当在页面中调用 resetFields 这个hook后，拿到的还是 resetFields 之前的值! 加了 await 也一样；

这种大佬有什么方案吗

**Comment by likui628** [comment]
resetFields后找个合适的时机调用getFieldsValue获取值。

你可以考虑下reset事件的处理。
https://github.com/vbenjs/vue-vben-admin/blob/1c1ce4b0e36bd4ad2cf30041089e3e353b76b636/src/components/Form/src/hooks/useFormEvents.ts#L101
