### ISSUE TITLE
vben admin有没2.8.0升级到2.10.0的文档呢

### ISSUE THREAD

**Issue by qwerlp** [vbenjs/vue-vben-admin#2840]
### Subject of the feature

vben admin有没2.8.0升级到2.10.0的文档呢

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by susanliy** [comment]
同意 强烈推荐出一个文档   整理对应的更改，要不然改动太大，对于现有功能改动不清楚呀

**Comment by wangjue666** [comment]
改动有些太多了， 建议当前的项目就不要变更了
