### ISSUE TITLE
ApiSelect的onChange事件 第二个参数

### ISSUE THREAD

**Issue by Angle-bo** [vbenjs/vue-vben-admin#2845]
[问题Issues](https://github.com/vbenjs/vue-vben-admin/issues/2592#issue-1606051385)

nextTick或者setTimeout，都会导致第一次选择校验报错。

**Comment by x-thence** [comment]
用setTimeout包一层就可以了

**Comment by wangjue666** [comment]
这个PR https://github.com/vbenjs/vue-vben-admin/pull/3071 已修复
