### ISSUE TITLE
打开同一个路由，参数不同，setTitle修改的永远是第一个，没有修改到最新的那个

### ISSUE THREAD

**Issue by qwerlp** [vbenjs/vue-vben-admin#2851]
### 描述 Bug

打开同一个路由，参数不同，setTitle修改的永远是第一个，没有修改到最新的那个
其它就是最开始设置路由名称
<img width="441" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/42144393/3b50cb03-4a8c-475d-8cd6-c5e90bff887b">

### 复现 Bug

打开同一个路由，参数不同，setTitle修改的永远是第一个，没有修改到最新的那个

## 系统信息

- vben admin：2.8.0

**Comment by anncwb** [comment]
Hello @qwerlp. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by DesignHhuang** [comment]
建议参考账号管理中的用户详情去做，应该是你代码处理有问题。 @qwerlp 
![image](https://github.com/vbenjs/vue-vben-admin/assets/3368397/e9bc2542-d0c4-408e-b4f7-7d93cec7eb91)
![image](https://github.com/vbenjs/vue-vben-admin/assets/3368397/9d2668ee-0e4a-4c77-8776-2fbc10778c0e)
