### ISSUE TITLE
ReferenceError: Cannot access 'pageWrapper' before initialization  热更新报错  

### ISSUE THREAD

**Issue by boyGdm** [vbenjs/vue-vben-admin#2852]
### 描述 Bug

 使用 BaseTable组件后 会出现  热更新 问题 。  
具体报错 ：ReferenceError: Cannot access 'pageWrapper' before initialization ， 要重新启动项目才正常。

## 系统信息

- 操作系统: windows
- Node 版本: 16.14
- 包管理器 (npm/yarn/pnpm) 及其版本:  8.3.1

**Comment by boyGdm** [comment]
已解决

**Comment by Bing-lemon** [comment]
我现在也有这个问题
