### ISSUE TITLE
弹窗口确认按钮无法点击

### ISSUE THREAD

**Issue by lijian3828940** [vbenjs/vue-vben-admin#2863]
![QQ截图20230614155058](https://github.com/vbenjs/vue-vben-admin/assets/5735244/73752b31-4cf4-49c8-836d-315648ef7d59)
在 https://vben.vvbin.cn/#/system/account 页面中，当第一点击编辑用户资料后，按保存。第二次点编辑用户资料，确认按钮一直无法点击。

**Comment by kirklin** [comment]
修复于PR：#2872
