### ISSUE TITLE
可编辑单元格editCellTable，当值为空时无法进行编辑

### ISSUE THREAD

**Issue by haliuhei** [vbenjs/vue-vben-admin#2866]
### 描述 Bug
单元格内值为空时，设置edit为true，鼠标滑过无法进行编辑

### 复现 Bug

拉取当前最新代码，运行官方demo,将mock的其中一项值改为空字符串‘’，查看页面，鼠标滑动到红框中，编辑图标不出现，无法触发编辑
![image](https://github.com/vbenjs/vue-vben-admin/assets/57513459/0904d0b4-5ed7-4ebc-8783-a45897bd526a)

**Comment by wangjue666** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/2b1114e6-063a-4380-b38b-f5b3969771c9)

最新版本是正常的
