### ISSUE TITLE
表单设计页面

### ISSUE THREAD

**Issue by kissjanna** [vbenjs/vue-vben-admin#2868]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
表单设计页面当添加了很多内容后页面无法向下滚动

栗子：如图所示中分割线下还有很多内容，但是页面无法向下滚动看不到下面内容

是在你们的演示页面：https://vben.vvbin.cn/#/form-designer/design
![image](https://github.com/vbenjs/vue-vben-admin/assets/63863023/6a5e238a-debd-47e3-a8a1-b25bad46dcea)

请清晰地描述此 Bug 的具体表现。

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

chrome：版本 114.0.5735.110（正式版本） （64 位）

**Comment by hehepeng** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/23272117/6d5854ed-ab99-485f-b644-18cb55775316)
表单设计器，有部分组件不显示，这个bug，你遇到过吗

**Comment by zhangxiaozhao11** [comment]
src\views\form-design\components\VFormDesign\modules\FormComponentPanel.vue    
 .draggable-box {
      height: calc(100vh - 120px);    // 这个地方改成-220px就可以了
