### ISSUE TITLE
左边的菜单缩小后，没法点击展示，右上角的项目设置，设置后没法更新回来

### ISSUE THREAD

**Issue by fangxux** [vbenjs/vue-vben-admin#2869]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [1] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [1] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [1] 已在 Issues 中搜索了相关的关键词
- [1] 不是 ant design vue 组件库的 Bug

### 描述 Bug

左边的菜单缩小后，点击展示没有回来

### 复现 Bug

右上角的项目设置，点击配置一些，下次进来没法选中上

## 系统信息

- 操作系统: mac
- Node 版本: v18.16.0
- 包管理器 (npm/yarn/pnpm) 及其版本: 8.6.2

**Comment by Duanxs** [comment]
```js
// src/store/modules/app.ts
this.projectConfig.menuSetting = deepMerge(this.projectConfig.menuSetting, setting)
```
`deepMerge` 无效，修改后的值未合并上

**Comment by kirklin** [comment]
修复于PR：#2872

**Comment by fangxux** [comment]
thanks
