### ISSUE TITLE
BasicDrawer在点击“确定”后，setDrawerProps({ confirmLoading: false }) 未正常执行

### ISSUE THREAD

**Issue by uncarbon97** [vbenjs/vue-vben-admin#2870]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
BasicDrawer组件在点击“确定”按钮后，Drawer自动关闭；但再次点开后，“确定”按钮还是停留在loading状态
本人为二开用户，最后一次跟随main分支更新的是（2023-04-30 22:52时的，b97d58839228c29fba696e52213664f16adf399f）修订，未出现本问题
因技术能力不够，暂时还未排查到问题所在，特来求教

### 复现 Bug
官方演示站 https://vben.vvbin.cn/#/system/menu 即可复现
1. 找到第三行的“按钮1-1”
2. 点击右侧的“编辑”
3. 无需任何改动，直接点击“确定”
4. 重复步骤2，即可复现（点击“新增菜单”亦可）

## 系统信息
- 操作系统: Win11 家庭版 21H2
- Node 版本: 18.16.0
- 包管理器 (npm/yarn/pnpm) 及其版本: 8.4.0

**Comment by uncarbon97** [comment]
补充：最新的main分支代码也可以复现

**Comment by yaoxiaoheng** [comment]
弹窗组件也出现这种情况，如 setModalProps({ loading: false, confirmLoading: false })全部无效，执行后依然停留在loading状态

**Comment by kirklin** [comment]
修复于PR：#2872
