### ISSUE TITLE
yarn  build 打包报错：unocss:global:build:scan

### ISSUE THREAD

**Issue by yonghui666** [vbenjs/vue-vben-admin#2876]
-运行打包命令就会报错；有大佬遇到过这个问题吗？
[unocss:global:build:scan] [postcss] /Users/yonghui/Desktop/code/duixin/admin-web/assets/index-!~{001}~.js-unocss-hash.css:1:2470: Unknown word 

![Uploading image.png…]()

**Comment by yonghui666** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/49012394/1223d88e-b899-47cc-8f31-30946a0dfd9f)

**Comment by zwtvip** [comment]
用pnpm build 打包呢
