### ISSUE TITLE
axios升级为v1.x后post请求使用FormData格式上传时Content-Type类型没有改变

### ISSUE THREAD

**Issue by A-XiongLiJun** [vbenjs/vue-vben-admin#2878]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

axios v0.x使用正常  Content-Type会自动multipart/form-data

### 复现 Bug

async handleUploadFile(event) {
  const file = event.target.files[0]
  let formData = new FormData()
  formData.append('files', file)
  const res = await service({
    url: '/api/files/upload',
    method: 'POST',
    data: formData
  })
  console.log(res.data);
}

## 系统信息

- 操作系统:
- Node 版本:  v16.16.0
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm v8.6.1

**Comment by crazyTanuki** [comment]
自行在http文件夹的axios文件里面修改实现
