### ISSUE TITLE
主题和颜色切换还会恢复吗？

### ISSUE THREAD

**Issue by zhangchenghang** [vbenjs/vue-vben-admin#2879]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by baifachuan** [comment]
同问，vben-admin-thin-next 这个工程的主题切换是没问题的，但是vue-vben-admin没有主题切换

**Comment by bzb745300** [comment]
同问。迫切需要主题切换回归。

**Comment by wangjue666** [comment]
@zhangchenghang  @bzb745300  https://github.com/vbenjs/vue-vben-admin/pull/2947 这个pr恢复了暗黑主题切换
