### ISSUE TITLE
请问modal中是没办法填写多个标签页的form吗？

### ISSUE THREAD

**Issue by qing-root** [vbenjs/vue-vben-admin#2881]
这里写了一个按钮，点击以后弹窗，希望的是效果是弹出来的modal是有多个tab，点击不同tab显示不同的输入框
如下是正常moal的代码
```
<template>

  <BasicModal v-bind="$attrs" @register="register" title="添加任务" @visible-change="handleVisibleChange" >
        <div class="pt-3px pr-3px">
       <BasicForm @register="registerForm" :model="model" />
        </div>

  </BasicModal>

</template>
```
<img width="641" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/30001685/a644ded4-b6ac-4a10-8ecc-7982d333269a">

然后我尝试使用如下选项卡代码等均没有效果，无论是tabs标签包裹BasicModal部分，还是BasicModal包裹TabPane都没有效果
```
<TabPane>
      <Tabs>
xxx
 </TabPane>
      </Tabs>
```

请问是不支持还是我写法有错误，前端小白实在没解决才来提issue ，抱歉

**Comment by zwtvip** [comment]
demo 有例子 http://localhost:3100/#/comp/form/tabsForm

**Comment by qing-root** [comment]
> demo 有例子 http://localhost:3100/#/comp/form/tabsForm

我测说了，如果basicmodal下，使用vben admin的多标签是没有任何效果的，我尝试引入antd vue的多标签以后，使用antd的标签是有效果的：

<img width="570" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/30001685/ff31bf63-697b-4e85-86bd-166dddb06139">
