### ISSUE TITLE
thin分支当前版本还停留在2.8.0，最近可以升级到2.10吗？

### ISSUE THREAD

**Issue by lishuncoder** [vbenjs/vue-vben-admin#2882]
### Subject of the feature

thin分支当前版本还停留在2.8.0，最近可以升级到2.10吗？
我看项目main分支已经是2.10了

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by zwtvip** [comment]
thin 建议不要用了 ，用main 一样的，把demo删除就行了

**Comment by lishuncoder** [comment]
> thin 建议不要用了 ，用main 一样的，把demo删除就行了

啊？老铁，为何，因为有坑吗？

**Comment by zwtvip** [comment]
> > thin 建议不要用了 ，用main 一样的，把demo删除就行了
> 
> 啊？老铁，为何，因为有坑吗？

thin太久没同步更新了，肯定有很多问题

**Comment by lishuncoder** [comment]
> > > thin 建议不要用了 ，用main 一样的，把demo删除就行了
> > 
> > 
> > 啊？老铁，为何，因为有坑吗？
> 
> thin太久没同步更新了，肯定有很多问题

![image](https://github.com/vbenjs/vue-vben-admin/assets/35674916/e8fc1609-9fae-4ab3-bc16-ec73c43c4af0)
老铁，项目里到处都是这种红色报错提示，我咋弄啊？看着太太太太太恼火了啊！！！
