### ISSUE TITLE
BasicTable 组件开启分页后出现滚动条. 需要滚一下才能完整看到分页

### ISSUE THREAD

**Issue by licheng1013** [vbenjs/vue-vben-admin#2883]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

![image](https://github.com/vbenjs/vue-vben-admin/assets/46236080/f275cdef-4e94-4aa3-93ba-a535ddf30f23)

### 复现 Bug
- 我开启分页后出现了滚动条. 这个该如何解决. 我看了几个 Issue 好像都没有给出解决方法..

```
    <BasicTable
      title="基础示例"
      titleHelpMessage="温馨提醒"
      :columns="columns"
      :dataSource="data"
      :canResize="true"
      :loading="false"
      :striped="false"
      :bordered="false"
      :showTableSetting="false"
      :pagination="true"
      @columns-change="handleColumnChange"
    >
```
## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by licheng1013** [comment]
解决方法:
- 设置 resize-height-offset 偏移
```
    <BasicTable
      title="基础示例"
      titleHelpMessage="温馨提醒"
      :columns="columns"
      :dataSource="data"
      :resize-height-offset="35"
      :canResize="true"
      :loading="false"
      :striped="false"
      :bordered="false"
      :showTableSetting="false"
      :pagination="true"
      @columns-change="handleColumnChange"
    >

    </BasicTable>
```

**Comment by Tian-ya-luer** [comment]
resize-height-offset 设置成12的倍数，或许可以解决table表头和table主体边框无法对齐问题

**Comment by Tian-ya-luer** [comment]
如果需要表单边框，不出现滚动条的情况下，表头和表单主体会对不齐。。。
