### ISSUE TITLE
.env.test里配置的VITE_PUBLIC_PATH，在执行npm run build:test 以后，不起作用，使用的还是.env.production里的VITE_PUBLIC_PATH ；

### ISSUE THREAD

**Issue by wangmin0314** [vbenjs/vue-vben-admin#2887]
"build:test": "cross-env NODE_ENV=test vite build && esno ./build/script/postBuild.ts",

**Comment by anncwb** [comment]
Hello @wangmin0314. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by likui628** [comment]
@wangmin0314 请提供版本号，新版本没问题
