### ISSUE TITLE
框架封装的公共组件能否抽出来做成独立的npm使用?

### ISSUE THREAD

**Issue by crazyTanuki** [vbenjs/vue-vben-admin#2890]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by ZexinW** [comment]
抽容易，改呢？改就改不了了.....

**Comment by crazyTanuki** [comment]
改了就会像我现在这样,想升级都升级不了,现在相当于自己一个人维护整套组件...

**Comment by M69W** [comment]
用这个框架的人，直接用一点也不改的估计没有吧。
升级或维护，对操作人有一定的要求、熟悉程度。
熟悉使用 git 能一定程度降低 升级/维护的难度(这个 issue 对应的解答 应该有，例如 https://github.com/vbenjs/vue-vben-admin/issues/472 )

请问：目前有没有 所谓的  npm 包 以拼积木的形式 拼凑成 像 vben 一样的框架吗？
如果有，麻烦请大佬们分享一下

**Comment by crazyTanuki** [comment]
感觉你们说的解决不了我的问题，我的项目是基于2.8.0的，antdv2.0的，升级代价太大了，现在都是引用element当作功能补充
