### ISSUE TITLE
首次加载这么慢，这么致命的缺点一直没解决，有人敢用？

### ISSUE THREAD

**Issue by wenpengpeng** [vbenjs/vue-vben-admin#2892]
首次加载这么慢，这么致命的缺点一直没解决，有人敢用？

**Comment by nullcache** [comment]
我这边很快啊

**Comment by wenpengpeng** [comment]
> 

请问是用的哪个分支版本呢？是做了什么优化？我本地启动首次加载就一直很慢，后面才很快，而且我看官方预览网站首次访问就是加载很慢的，几十秒

**Comment by wenpengpeng** [comment]
> > 
> 
> 请问是用的哪个分支版本呢？是做了什么优化？我本地启动首次加载就一直很慢，后面才很快，而且我看官方预览网站首次访问就是加载很慢的，几十秒

我用的是thin版本的，这个版本好像很久没更新了，大家直接拉master版本现在应该是2.10版本自己删删拿来用吧，我的电脑上最新版本速度提升不少，首次加载大概在10s左右，在能够接受的范围

**Comment by nuoyuezuo** [comment]
是很慢，慢死了
