### ISSUE TITLE
组件中遇到的TS报错

### ISSUE THREAD

**Issue by scottMan1001** [vbenjs/vue-vben-admin#2898]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [√] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [1] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [1] 已在 Issues 中搜索了相关的关键词
- [1] 不是 ant design vue 组件库的 Bug

### 描述 Bug
vben: version 2.10.0 ,随便打开几个组件都有类似的TS校验问题，有没有大佬可以解惑

![image](https://github.com/vbenjs/vue-vben-admin/assets/38151889/6ece164f-1eed-465f-98f7-a5675bfcc46b)

## 系统信息

- 操作系统:win10
- Node 版本:16.16.0
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm 8.6.6

**Comment by kirklin** [comment]
你插件升级了没

**Comment by scottMan1001** [comment]
> 你插件升级了没

![image](https://github.com/vbenjs/vue-vben-admin/assets/38151889/ab5d6885-7bd9-4897-8624-97507528048d)
只安了这个，请问需要升级什么
