### ISSUE TITLE
[bug] Tinymce 富文本 图片回显问题

### ISSUE THREAD

**Issue by milcery** [vbenjs/vue-vben-admin#2899]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

Tinymce富文本上传图片回显有问题，如果遇到会被转义的图片名，会找不到替换的内容。需要改进getUploadingImgName函数
![微信图片_20230705094951](https://github.com/vbenjs/vue-vben-admin/assets/90891463/e8908114-987e-4abf-bb6a-c8fc5961ddc7)

### 复现 Bug

上传的文件名出现空格，破折号

## 系统信息

- 操作系统: 
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by likui628** [comment]
没发现有什么问题，你用新版本的试一下
![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/55ef5c60-1370-46dc-b2c1-14ed3e052484)

**Comment by anncwb** [comment]
Hello @milcery. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by milcery** [comment]
@likui628 我试了下最新代码，没有发现问题了

**Comment by milcery** [comment]
"<p>v出现在v这些[uploading:组件13 - 2x.png]</p>".replace(`[uploading:${"组件13 - 2x.png"}]`, `<img src="${"https://vben.vvbin.cn/assets/logo-63028018.png"}"/>`)
