### ISSUE TITLE
ApiCascader

### ISSUE THREAD

**Issue by amazalupa** [vbenjs/vue-vben-admin#2901]
vben封装的ApiCascader，默认changeOnSelect=true，但我将changeOnSelect设置为false时，同时require=true（设置必填），我的OnSelect方法会失效，选中的时候会报错未选中
`{
        field: 'CategoryId',
        label: '分类',
        component: 'ApiCascader',
        componentProps: ({ formActionType }) => {
          return {
            api: Option,
            resultField: 'list',
            fieldNames: {
              label: 'title',
              value: 'id',
              children: 'children',
            },
            changeOnSelect: false,
            onSelect: async (_, checkedoption) => {
              const { setFieldsValue } = formActionType
              setFieldsValue({
                id: checkedoption.value,
              })
            },
          }
        },
      },`

**Comment by wangjue666** [comment]
@amazalupa  级联没有 onSelect事件，应该是 onChange 事件， 至于选中报错,我没有复现出来这个问题， 你需要提供下你的接口详细信息
