### ISSUE TITLE
在表单增删示例中,当你删除一行的inpu,再新增一行inpu,内部的默认值会变成现存的上一行的值

### ISSUE THREAD

**Issue by timeIsMemory** [vbenjs/vue-vben-admin#2908]
如图,新建三行input,每个input都输入值,然后删除第二行,再点击新增按钮,你会发现新建的input会跟它上一行一模一样,甚至label也一样
![1](https://github.com/vbenjs/vue-vben-admin/assets/131134473/7055475d-e18b-4e78-9dc0-6028e80000f3)
![2](https://github.com/vbenjs/vue-vben-admin/assets/131134473/38db7396-334d-48e5-affe-e468b504b5b9)
![3](https://github.com/vbenjs/vue-vben-admin/assets/131134473/71e16da1-8e59-4a7b-a5b2-387b30d92ef2)

**Comment by timeIsMemory** [comment]
解决方案是在删除按钮的事件处理函数那里的n.value--不要就可以了

function del(field) {
  removeSchemaByField([`field${field}a`, `field${field}b`, `${field}`])
//  n.value--  //注释掉这行
}

**Comment by zwtvip** [comment]
用 n.value = Number(field) 呢？
