### ISSUE TITLE
iconify 离线情况下 不显示

### ISSUE THREAD

**Issue by zhang-yuer** [vbenjs/vue-vben-admin#2909]
iconify 离线情况下 不显示 怎么解决

**Comment by codeterminater** [comment]
建议看下官网文档。人家说的很清楚  https://doc.vvbin.cn/dep/icon.html#%E7%94%9F%E6%88%90

在线图标(项目默认,推荐)
该方式会在图标选择器使用到图标的时候进行在线请求,然后缓存对应的图标到浏览器。可以有效减少代码打包体积。

如果你的项目可以访问外网，建议可以使用这种方式

缺点： 在局域网或者无法访问到外网的环境中图标显示不出来
