### ISSUE TITLE
 header notify图标位置未居中

### ISSUE THREAD

**Issue by byte-voyager** [vbenjs/vue-vben-admin#2912]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

最新main分支代码 header notify图标位置未居中

### 复现 Bug

运行代码
![image](https://github.com/vbenjs/vue-vben-admin/assets/16448666/ea6f3439-79bb-41f0-babb-880821816aa2)

## 系统信息

- 操作系统:linux
- Node 版本: v18.16.1
- 包管理器 (npm/yarn/pnpm) 及其版本:8.6.7

**Comment by fangxux** [comment]
<img width="176" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/33439371/9452a85f-2474-432e-a3e8-83bfa7a123dd">
<img width="191" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/33439371/f354189e-3c24-4607-b9c4-114223b50038">
还有很多地方有这个情况，麻烦修复下

**Comment by HughCodeX** [comment]
#2917 已修改

**Comment by fangxux** [comment]
thanks

**Comment by fangxux** [comment]
还有个地方
<img width="210" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/33439371/8c5c7b57-4d57-4b86-971e-44da1ffd2177">

**Comment by likui628** [comment]
> 还有个地方 <img alt="image" width="210" src="https://user-images.githubusercontent.com/33439371/255651341-8c5c7b57-4d57-4b86-971e-44da1ffd2177.png">

已改
