### ISSUE TITLE
Unsupported platform: win32 ia32 LE

### ISSUE THREAD

**Issue by loveLan18913** [vbenjs/vue-vben-admin#2915]
### Describe the bug
main分支，下载下来以后 install出现 Unsupported platform: win32 ia32 LE

### Reproduction

![image](https://github.com/vbenjs/vue-vben-admin/assets/57902256/a8768b53-a6b5-4dff-a1a6-afd9dfc3e150)

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by wangjue666** [comment]
是的，turbo这个工具不支持
