### ISSUE TITLE
生产环境Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by jiuyi919** [vbenjs/vue-vben-admin#2918]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

生产环境打开网页找不到文件，.env.production中的VITE_PUBLIC_PATH改成./也不行
<img width="1487" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/81691786/be1d7cdd-da84-415e-9662-b44bf27e6127">

### 复现 Bug

<img width="1505" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/81691786/8c544162-708e-40ec-84a1-31ed2e876a2c">
<img width="1471" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/81691786/e5328f22-7062-4332-b800-b326e9179af8">

## 系统信息

- 操作系统:mac
- Node 版本:v16.20.0
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm 8.6.3

**Comment by HughCodeX** [comment]
1. vite.config.js内overrides对象添加一个属性`base:'./'`
2. .env.production内添加一个`VITE_GLOB_APP_TITLE = app`
