### ISSUE TITLE
pnpm i 报错  ERROR  run failed: error hashing package files: git error: 'git status'

### ISSUE THREAD

**Issue by bryant0623** [vbenjs/vue-vben-admin#2922]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug
### 描述 Bug
clone master分支后安装依赖(pnpm i)报以下错误
ERROR  run failed: error hashing package files: git error: 'git status'
<img width="1427" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/126851917/f0eb9bb7-6490-44f6-b0f3-62cc233df410">

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:macOs Monterey 12.6.3
- Node 版本:20.3.0
- 包管理器 (npm/yarn/pnpm) 及其版本:
npm:9.6.7
pnpm:8.6.9

**Comment by HughCodeX** [comment]
我尝试了`pnpm i` 一切正常, 我使用了跟你相同版本Node和pnpm, 唯一不同的是我的操作系统是windows10, 或许你应该考虑切换一下node或者pnpm的版本

**Comment by Curry3O** [comment]
我也遇到同样的问题，大佬们有解决方法吗？

**Comment by fengfeng0603** [comment]
我也遇到了这个问题，刚查了下，将你电脑上的git升级一下，就可以了。参见 [https://github.com/vercel/turbo/issues/5447](url)

**Comment by fengfeng0603** [comment]
我也遇到了这问题， 更新下电脑的git版本就可以了。 问题原因参见[https://github.com/vercel/turbo/issues/5447](url)

**Comment by bryant0623** [comment]
> 我也遇到同样的问题，大佬们有解决方法吗？

将turbo的版本改成1.10.6就可以了

**Comment by fengfeng0603** [comment]
> 我尝试了`pnpm i` 一切正常, 我使用了跟你相同版本Node和pnpm, 唯一不同的是我的操作系统是windows10, 或许你应该考虑切换一下node或者pnpm的版本

亲测2.15.0的git版本, 在执行install时，turbo 报错

**Comment by bryant0623** [comment]
> 我也遇到了这问题， 更新下电脑的git版本就可以了。 [问题原因参见](https://github.com/vercel/turbo/issues/5447)

更新git版本我当时也试了，没有效果。后面将turbo的版本改成1.10.6就可以了

**Comment by jiehuanxiang** [comment]
遇到同样的问题，没有更新git版本，turbo降级至1.10.6即可，需要开发人员兼容一下咯。
