### ISSUE TITLE
侧边栏的手风琴模式下，在滚动到屏幕偏上位置时展开第一个长的菜单，再往下滚动到屏幕偏上位置时展开第二个短的菜单，第二个短的菜单会滑出当前可视区域

### ISSUE THREAD

**Issue by leleccccc** [vbenjs/vue-vben-admin#2924]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

侧边栏的手风琴模式下，在滚动到屏幕偏上位置时展开第一个长的菜单，再往下滚动到屏幕偏上位置时展开第二个短的菜单，第二个短的菜单会滑出当前可视区域，element-admin的此处的处理会让第二个短的菜单固定在可视区域的顶部

### 复现 Bug

侧边栏的手风琴模式下，在滚动到屏幕偏上位置时展开第一个长的菜单，再往下滚动到屏幕偏上位置时展开第二个短的菜单，第二个短的菜单会滑出当前可视区域

## 系统信息

- 操作系统: windows
- Node 版本: 1614.0
- 包管理器 (npm/yarn/pnpm) 及其版本: yarn 1.22.4

**Comment by HughCodeX** [comment]
我不是很清楚你的描述, 可以上传个gif或者视频展示一下这种情况吗?
