### ISSUE TITLE
BasicTable 套用BasicForm 查询  切换页数搜索 page不变

### ISSUE THREAD

**Issue by Bing-lemon** [vbenjs/vue-vben-admin#2925]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

BasicTable中套用了BasicForm 表单查询，切换table页数时，搜索内容时，点击form的查询按钮请求接口，page永远是1，而不是切换后的页数

### Reproduction

BasicTable中套用了BasicForm 表单查询，切换table页数时，搜索内容时，点击form的查询按钮请求接口，page永远是1，而不是切换后的页数

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by Bing-lemon** [comment]
操作系统: windows
Node 版本: 16.17.0
包管理器 (npm/yarn/pnpm) 及其版本: yarn 1.22.19

**Comment by GauharChan** [comment]
举个🌰，现在初始化的条件你有3页数据；现在你切到第三页。现在你更换搜索条件(服务端查出只有一页的数据)，按你的这个要求，搜索的时候page传了3给接口。请问阁下该如何应对？

**Comment by HughCodeX** [comment]
如果我没理解错的话, 你预期的是数据量超过3页, 搜索过后页面仍在第3页?但是搜索之后在第一页是正常应用的处理逻辑吧?

**Comment by GauharChan** [comment]
CLOSES #2925 @jinmao88
