### ISSUE TITLE
基于2.10版本升级antdv 4.0

### ISSUE THREAD

**Issue by xingyuv** [vbenjs/vue-vben-admin#2927]
基于2.10版本升级antdv 4.0

https://gitee.com/xingyuv/vue-vben-admin

https://github.com/xingyuv/vue-vben-admin

有没有一起搞的，现在大部分功能已经升级好

**Comment by YogaZong** [comment]
nb 还得是你 star && fork && watch

**Comment by geng130127** [comment]
啊？已经升级完成了吗

**Comment by xingyuv** [comment]
> 啊？已经升级完成了吗

是啊，现在还差主题这些，以及一些功能性的测试

**Comment by cometlj** [comment]
mark一下

**Comment by zwwmin** [comment]
厉害厉害，能不能说下升级方法

**Comment by billydong1973** [comment]
好快的动作，已fork

**Comment by zusrsoft** [comment]
这个必须得大大的支持你！！！

**Comment by yanyu2022** [comment]
antdv4版本推荐一套框架[antdv-pro](https://github.com/antdv-pro/antdv-pro)
ant-design-vue团队成员维护

**Comment by likui628** [comment]
不考虑PR吗

**Comment by ChunyuPCY** [comment]
ant-design-vue目前已经到4.0.1，应该是ant-design-vue 版本也没有稳定吧，坐等大佬升级
