### ISSUE TITLE
克隆下项目后，用pnpm install 安装依赖报错

### ISSUE THREAD

**Issue by Curry3O** [vbenjs/vue-vben-admin#2930]
安装依赖时报错： ERROR  run failed: error hashing package files: git error: 'git status' 
<img width="869" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/51936110/15650f1b-4a3c-4b31-9240-b8d6c681ecd7">
并且拉下项目后发现自带了几个文件更改记录：
<img width="411" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/51936110/71e4ccde-ec70-4fc3-831b-65d409ba6828">

**Comment by huhyge** [comment]
我也遇到同样的报错,本地开发没问题,在构建到jinkins时,在拉取代码并且下载依赖包时出现了同样问题 node版本 16.17.x,pnpm版本8.6.x

**Comment by longli61990** [comment]
遇到同样的问题，m1芯片，node16.17.0，pnpm8.7.1

**Comment by huhyge** [comment]
升级turbo版本能解决
![image](https://github.com/vbenjs/vue-vben-admin/assets/114255939/5a251a20-20c2-411d-92ba-76b39b9345e6)
