### ISSUE TITLE
VITE_PROXY 不生效的问题

### ISSUE THREAD

**Issue by crazytimor** [vbenjs/vue-vben-admin#2933]
1
初次安装使用，阅读文档，在尝试使用 
.env.development 中
VITE_PROXY=[["/basic-api","http://localhost:3000"]] 
实测并没有生效
只能在 vite.config.ts 中修改 proxy

2
在修改vite.config.ts 后尝试进行登录操作，在login 过程中  post http://localhost:5173/basic-api/login 必定返回的设置好的登录信息，不受代理影响，但是 get 受影响
![image](https://github.com/vbenjs/vue-vben-admin/assets/38139384/570b7a1c-05d5-4813-8a87-7c6b6e142003)
所以特意问问这个问题

**Comment by codeterminater** [comment]
建议检查你的请求api url是如何写的， vite proxy中启用了 rewrite,  以‘/basic-api’开头的请求会补代理转发。所以要注意api请求url中是以'/basic-api'开头不是会影响代理是否启用

**Comment by joyhooian** [comment]
@crazytimor 从v3.0.0开始，作者重构了vite.config.ts，新版本不再支持VITE_PROXY环境变量。

**Comment by wangjue666** [comment]
> 是不是应该更新一下文档，说明一下。

是的， 也欢迎你的PR

**Comment by wuzhican** [comment]
https://github.com/vbenjs/vue-vben-admin-doc/issues/129
提交了文档的pr，麻烦合并一下
