### ISSUE TITLE
生產環境:VITE_GLOB_APP_TITLE' of 'C' as it is undefined

### ISSUE THREAD

**Issue by Zzongke** [vbenjs/vue-vben-admin#2937]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
生產環境:VITE_GLOB_APP_TITLE' of 'C' as it is undefined,我的項目要是設置VITE_GLOB_APP_TITLE的值不包含空格生產環境就不會出現這個問題。

### 复现 Bug
拉取項目，不需要修改，直接打包預覽啟動

## 系统信息

- 操作系统:window10
- Node 版本:16.20.0
- 包管理器 (npm/yarn/pnpm) 及其版本:8.6.9

**Comment by oloshe** [comment]
`src/utils/env.ts` 中这里改成这样就行：
<img width="749" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/40467840/c141369e-549e-4b73-b090-aa8498083bd8">

**Comment by Zzongke** [comment]
> `src/utils/env.ts` 中这里改成这样就行： <img alt="image" width="749" src="https://user-images.githubusercontent.com/40467840/257570999-c141369e-549e-4b73-b090-aa8498083bd8.png">

非常感謝，這解決了問題！

**Comment by bihell** [comment]
我刚也碰到这个问题，感谢楼主和 [oloshe](https://github.com/oloshe)

**Comment by yking1996** [comment]
thx! same problem
