### ISSUE TITLE
在Table组件中调用接口返回10条，在`afterFetch`中处理后得到5条，但页面还是显示10条

### ISSUE THREAD

**Issue by gnyuan** [vbenjs/vue-vben-admin#2938]
### Describe the bug

在Table组件中调用接口返回10条，在`afterFetch`中处理后得到5条，但页面还是显示10条

### Reproduction

```typescript
const [registerTable, { reload }] = useTable({
        api: getData,
        searchInfo: params,
        afterFetch: transformData,
});
// transformData入口处有10条，处理完5条，页面显示5条，但页脚显示数量是10.
```

## System Info

- Operating System: Docker node:18.16.1
- Node version: 18.16.1
- Package manager (npm/yarn/pnpm) and version: npm==9.5.1

**Comment by GauharChan** [comment]
把`transformData`具体实现贴出来看看

**Comment by GauharChan** [comment]
你指的是分页的pageSize是吧😥那个是设置一页请求多少条数据，为什么要和你这个骚操作所关联呢。按你这次afterFetch处理后，那我切换分页请求的时候究竟是请求5条还是10条呢？

**Comment by gnyuan** [comment]
> 你指的是分页的pageSize是吧😥那个是设置一页请求多少条数据，为什么要和你这个骚操作所关联呢。按你这次afterFetch处理后，那我切换分页请求的时候究竟是请求5条还是10条呢？

您好，是的，我指`pageSize`还是10条。按我理解`afterFetch:请求之后对返回值进行处理`,即返回后处理可能本身条数会改变。在我的case里，我需要从后端取得`row1,col1`,`row1,col2`,`row2,col1`,`row2,col2`等，最后前端拼接成`row1,col1,co2`,`row2,col1,col2`。后来我把这个请求包了一层，框架只会看到我请求5条了。

或许您能否调用了`api`以及`afterFetch`之后才拿到总条数；或者说在文档里标注一下`afterFetch`处理的返回值不能增减原有条数，谢谢啦！

**Comment by GauharChan** [comment]
> > 你指的是分页的pageSize是吧😥那个是设置一页请求多少条数据，为什么要和你这个骚操作所关联呢。按你这次afterFetch处理后，那我切换分页请求的时候究竟是请求5条还是10条呢？
> 
> 您好，是的，我指`pageSize`还是10条。按我理解`afterFetch:请求之后对返回值进行处理`,即返回后处理可能本身条数会改变。在我的case里，我需要从后端取得`row1,col1`,`row1,col2`,`row2,col1`,`row2,col2`等，最后前端拼接成`row1,col1,co2`,`row2,col1,col2`。后来我把这个请求包了一层，框架只会看到我请求5条了。
> 
> 或许您能否调用了`api`以及`afterFetch`之后才拿到总条数；或者说在文档里标注一下`afterFetch`处理的返回值不能增减原有条数，谢谢啦！

`pageSize`是你请求之前确定好的接口参数，和你请求之后的`afterFetch`处理有什么关系？
如果你希望更改分页的数据，那么就调用`setPagination`(和你上面的reload同一个地方导出的)去设置

**Comment by gnyuan** [comment]
> > > 你指的是分页的pageSize是吧😥那个是设置一页请求多少条数据，为什么要和你这个骚操作所关联呢。按你这次afterFetch处理后，那我切换分页请求的时候究竟是请求5条还是10条呢？
> > 
> > 
> > 您好，是的，我指`pageSize`还是10条。按我理解`afterFetch:请求之后对返回值进行处理`,即返回后处理可能本身条数会改变。在我的case里，我需要从后端取得`row1,col1`,`row1,col2`,`row2,col1`,`row2,col2`等，最后前端拼接成`row1,col1,co2`,`row2,col1,col2`。后来我把这个请求包了一层，框架只会看到我请求5条了。
> > 或许您能否调用了`api`以及`afterFetch`之后才拿到总条数；或者说在文档里标注一下`afterFetch`处理的返回值不能增减原有条数，谢谢啦！
> 
> `pageSize`是你请求之前确定好的接口参数，和你请求之后的`afterFetch`处理有什么关系？ 如果你希望更改分页的数据，那么就调用`setPagination`(和你上面的reload同一个地方导出的)去设置

不好意思，之前说错了，不是`pageSize`，是数据总条数`totalSize`。我想问问有没有属性可以设置Table组件的总条数，或者它会根据`dataSource`来调整的吗？因为我看到`dataSource`里有5条，这是预期内的。

**Comment by GauharChan** [comment]
> > > > 你指的是分页的pageSize是吧😥那个是设置一页请求多少条数据，为什么要和你这个骚操作所关联呢。按你这次afterFetch处理后，那我切换分页请求的时候究竟是请求5条还是10条呢？
> > > 
> > > 
> > > 您好，是的，我指`pageSize`还是10条。按我理解`afterFetch:请求之后对返回值进行处理`,即返回后处理可能本身条数会改变。在我的case里，我需要从后端取得`row1,col1`,`row1,col2`,`row2,col1`,`row2,col2`等，最后前端拼接成`row1,col1,co2`,`row2,col1,col2`。后来我把这个请求包了一层，框架只会看到我请求5条了。
> > > 或许您能否调用了`api`以及`afterFetch`之后才拿到总条数；或者说在文档里标注一下`afterFetch`处理的返回值不能增减原有条数，谢谢啦！
> > 
> > 
> > `pageSize`是你请求之前确定好的接口参数，和你请求之后的`afterFetch`处理有什么关系？ 如果你希望更改分页的数据，那么就调用`setPagination`(和你上面的reload同一个地方导出的)去设置
> 
> 不好意思，之前说错了，不是`pageSize`，是数据总条数`totalSize`。我想问问有没有属性可以设置Table组件的总条数，或者它会根据`dataSource`来调整的吗？因为我看到`dataSource`里有5条，这是预期内的。

total的取值有两种情况：
- api返回的数据是数组，则取它的长度
- 否则就是通过你配置的totalField字段名进行匹配赋值
我想补充的是，total是用于计算当前的pageSize下有多少个分页；而并不是你这一次请求回来之后有多少数据(在你有第二页的前提下)
