### ISSUE TITLE
v2.10.0 中所有.vue 中 exprot default 报错

### ISSUE THREAD

**Issue by fzxiang** [vbenjs/vue-vben-admin#2941]
- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
在vscode编辑器中，打开任何一个export default defineComponents() 会有类型报错：没有引用 .pnpm/vue-types@3.0.2_vue@3.2.47/node_modules/vue-types
<img width="857" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/38209301/3fa377f8-9e1e-4bee-952b-f53a100cb4c7">

### 复现 Bug
正常打开src/components/Table/src/components/TableAction.vue，编辑器文件报错

## 系统信息
- 操作系统: mac
- Node 版本: 16.20.0
- 包管理器 (npm/yarn/pnpm) 及其版本: 8.4.0

**Comment by ZHANGJIAWEIQAQ** [comment]
对啊对啊，我也是

**Comment by ZHANGJIAWEIQAQ** [comment]
强迫症犯了

**Comment by ChunyuPCY** [comment]
可以自己改成 setup方法，再用上 defineOptions
<img width="758" alt="截屏2023-08-03 10 57 25" src="https://github.com/vbenjs/vue-vben-admin/assets/21986942/75bd7cfc-cc96-449c-882e-ee9136cd0ee5">

没有测，只是改了一下，不再报红

**Comment by xiaoai7904** [comment]
遇到了同样的问题

**Comment by fourthCities** [comment]
![0d9c748a-4d71-439b-b2ea-93bf1db76c1e](https://github.com/vbenjs/vue-vben-admin/assets/28562837/620f4032-146f-4025-9e3d-b09c5f9494e2)
我是这么修的！！！！

**Comment by fzxiang** [comment]
> 

这个配置项是 生成相应的 '.d.ts' 文件，会有其它副作用吗

**Comment by fourthCities** [comment]
> > 
> 
> 这个配置项是 生成相应的 '.d.ts' 文件，会有其它副作用吗
I don't know。因为我没有应用到生产环境，只是在学习。
