### ISSUE TITLE
drawer中使用到了ApiSelect，如何打开drawer的时候设置ApiSelect的默认值为第一行数据

### ISSUE THREAD

**Issue by datasre** [vbenjs/vue-vben-admin#2943]
如果使用onOptionsChange则只有第一次打开drawer才会触发，后面关闭了drawer后重新打开drawer后则默认值没了
![image](https://github.com/vbenjs/vue-vben-admin/assets/54182063/6623804f-a15d-439b-b82c-433ed297e59e)

**Comment by datasre** [comment]
已经解决

**Comment by doooghan** [comment]
请问是怎么解决的呢？
