### ISSUE TITLE
Cannot destructure property 'VITE_GLOB_APP_TITLE' of 'C' as it is undefined.

### ISSUE THREAD

**Issue by icysky** [vbenjs/vue-vben-admin#2949]
git clone当前版本，无法正常进入页面，控制台输出以下错误
Cannot destructure property 'VITE_GLOB_APP_TITLE' of 'C' as it is undefined.

**Comment by wangjue666** [comment]
@icysky  把 VITE_GLOB_APP_TITLE的值 Vben Admin 空格去掉改为 VbenAdmin

**Comment by LiuYnag** [comment]
@wangjue666 官网的那个Demo<https://vben.vvbin.cn/>在报这个错误

**Comment by icysky** [comment]
> @icysky 把 VITE_GLOB_APP_TITLE的值 Vben Admin 空格去掉改为 VbenAdmin

抱歉，是我没说清楚，这个问题只出现在生产环境中。

**Comment by icysky** [comment]
> @icysky 把 VITE_GLOB_APP_TITLE的值 Vben Admin 空格去掉改为 VbenAdmin
这前这个问题一直存在于生产环境中，刚才按你说的方法测试了一下，确实可以解决这个问题。感谢！

**Comment by wangjue666** [comment]
@LiuYnag 对呀 官网就是用的最新的代码编译部署的
