### ISSUE TITLE
useTheme报错

### ISSUE THREAD

**Issue by gnyuan** [vbenjs/vue-vben-admin#2951]
### 描述 Bug
```typescript
import { useTheme } from 'vite-plugin-windicss';
const theme = useTheme();
console.log(theme('colors.blue-100'));
```
想要取得tailwind css某个配置时报错。

**Comment by likui628** [comment]
报什么错了

**Comment by gnyuan** [comment]
任意组件里执行我上面提供的语句，就会报无法获取动态加载的模块的错误。
```
Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://192.168.3.27:8080/src/views/test/index.vue?t=1693493259629
```

**Comment by likui628** [comment]
压根没有导出```useTheme```,你在哪里看到可以这样用的
![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/ef3e46a1-1752-47f8-908c-c13bd2113fba)
<img width="664" alt="Snipaste_2023-09-01_11-50-22" src="https://github.com/vbenjs/vue-vben-admin/assets/90845831/4969806b-05d3-47aa-a713-47e5a64e21b3">
