### ISSUE TITLE
访问https://vben.vvbin.cn/报错index.js:1 Uncaught TypeError: Cannot destructure property 'VITE_GLOB_APP_TITLE' of 'C' as it is undefined.

### ISSUE THREAD

**Issue by MayWu91** [vbenjs/vue-vben-admin#2953]
访问：https://vben.vvbin.cn/ 长时间loading，console里有报错

index.js:1 Uncaught TypeError: Cannot destructure property 'VITE_GLOB_APP_TITLE' of 'C' as it is undefined.
    at getAppEnvConfig (index.js:1:153285)
    at getCommonStoragePrefix (index.js:1:152965)
    at getStorageShortName (index.js:1:153082)
    at createOptions (index.js:1:179996)
    at index.js:1:180038

<img width="1501" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/20208514/446e1343-1264-436e-9a65-3c02c28baee2">

**Comment by ChunyuPCY** [comment]
项目的 .env 文件里面有，写上就行了

**Comment by q8462880** [comment]
写上了 为什么还是解构不了 是什么原因
