### ISSUE TITLE
修改breakpoint.less里面的css变量，在页面上并没有生效

### ISSUE THREAD

**Issue by owl-lei** [vbenjs/vue-vben-admin#2964]
### Discussed in https://github.com/vbenjs/vue-vben-admin/discussions/2963

<div type='discussions-op-text'>

<sup>Originally posted by **owl-lei** August 14, 2023</sup>
在Login.vue组件，使用了@screen-xl

    @media (max-width: @screen-xl) {
      background-color: #293146;

      .@{prefix-cls}-form {
        background-color: #fff;
      }
    }

页面渲染出来的是max-width:1200px;我想把他改为1280，跟unocss里的xl:text-gray-600尺寸保持一致，
但修改breakpoint.less里面的@screen-xl: 1280px;并没有生效。

我改如何做才能调整@screen-xl的值？</div>

**Comment by likui628** [comment]
我在https://github.com/vbenjs/vue-vben-admin/discussions/2963 里评论了原因，

本来想提PR的，但是不知道如何入手，你可以在[vue-vben-admin/internal/vite-config/src/utils/modifyVars.ts](https://github.com/vbenjs/vue-vben-admin/blob/e31525a803ee5a7c9770b4eccebe91cc90f7aa60/internal/vite-config/src/utils/modifyVars.ts#L28)临时设置下。

**Comment by owl-lei** [comment]
> 我在#2963 里评论了原因，
> 
> 本来想提PR的，但是不知道如何入手，你可以在[vue-vben-admin/internal/vite-config/src/utils/modifyVars.ts](https://github.com/vbenjs/vue-vben-admin/blob/e31525a803ee5a7c9770b4eccebe91cc90f7aa60/internal/vite-config/src/utils/modifyVars.ts#L28)临时设置下。

好的，解决了。谢谢哈
