### ISSUE TITLE
ApiSelect第一次选中数据后，会出现表单校验，第二次则不会。

### ISSUE THREAD

**Issue by Kevin-KangShao-Yang** [vbenjs/vue-vben-admin#2965]
原因：hooks-》component-》useFormItem文件
const state: any = computed({
    get() {
      return innerState.value
    },
    set(value) {
      if (isEqual(value, defaultState.value)) return
      innerState.value = value as T[keyof T]
      nextTick(() => {
        console.log('emit', value, toRaw(unref(emitData)))
        emit?.(changeEvent, value, ...(toRaw(unref(emitData)) || []))
      })
    }
  })
  
  测试nextTick 中emitData的数据为[]空数组，导致的校验出现。猜测原因为执行顺序先后问题导致nextTick中emitData为上一次的值。

解决方案：有两种方式
1、将nextTick 改为setTimeout即可；
2、在ApiSelect等组件中handleChange 方法中改用 emit('change', value, ...args);即可

**Comment by wangjue666** [comment]
已修复，具体原因见 PR https://github.com/vbenjs/vue-vben-admin/pull/3071

**Comment by badaozhenqi** [comment]
这个问题还存在，我才拉的最新版。。。
