### ISSUE TITLE
TableAction 打包之后样式丢失

### ISSUE THREAD

**Issue by nuo-promise** [vbenjs/vue-vben-admin#2966]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

TableAction 组件 颜色 开发时候 都是正常显示，打包之后 就变成黑色了，我看元素样式，是在打包时候 生成 button : { color: inherit} 使用父级颜色了。

### 开发模式
![image](https://github.com/vbenjs/vue-vben-admin/assets/46160170/79b06a12-17cb-43a1-ba3a-5d08bc626c0b)
### 打包模式
![image](https://github.com/vbenjs/vue-vben-admin/assets/46160170/f901437a-3ba4-4999-a098-b7a33245aad6)

## 系统信息

- 操作系统: 开发: MacOs  生产 : centos7
- Node 版本: V18.7.0
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm  v7.29.0

**Comment by nuo-promise** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/46160170/a8c7884e-86a9-4dd6-bf4c-a42a48b13722)
我搜了代码种找不到这个样式,还请帮忙下。

**Comment by HughCodeX** [comment]
能否提供一下demo代码, 我无法复现你的问题

**Comment by nuo-promise** [comment]
通过 修改 属性 color 去实现样式了。
