### ISSUE TITLE
createAsyncComponent加载的异步组件，无法正常推到出props

### ISSUE THREAD

**Issue by Coke-Code** [vbenjs/vue-vben-admin#2967]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [*] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [*] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [*] 已在 Issues 中搜索了相关的关键词
- [*] 不是 ant design vue 组件库的 Bug

### 描述 Bug
switchItem有`title`等属性，使用createAsyncComponent引入后，props丢失
```ts
const SwitchItem = createAsyncComponent(() => import('./SwitchItem.vue'))
```
### 复现 Bug
main分支最新提交`61c4c1bf7cf0843f2584903fd9a82dcef75efd24`可以复现
详见`SettingDrawer.tsx`报错
## 系统信息

- 操作系统:win11
- Node 版本:v18.16.0
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm@8.6.2

**Comment by Coke-Code** [comment]
这个项目typescript问题挺多的。想加入处理

**Comment by coderwyd** [comment]
提pr就行
