### ISSUE TITLE
多栏布局页面刷新侧边栏状态丢失问题？

### ISSUE THREAD

**Issue by Youmzhi** [vbenjs/vue-vben-admin#2973]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [1 ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [1 ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [1 ] 已在 Issues 中搜索了相关的关键词
- [1 ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

状态丢失

### 复现 Bug

布局方式：
![image](https://github.com/vbenjs/vue-vben-admin/assets/75533551/d7ac14ba-6e82-4713-af19-3fd184af32dc)
权限方式： BACK
bug复现： 
![image](https://github.com/vbenjs/vue-vben-admin/assets/75533551/db2efef9-a826-4b15-866a-a7bf933a42e6)

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by anncwb** [comment]
Hello @Youmzhi. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.
