### ISSUE TITLE
`Select`,`RadioGroup` 和 `RadioButtonGroup` 三个组件在 options 使用 number 类型的 value 时校验规则异常

### ISSUE THREAD

**Issue by wencaizhang** [vbenjs/vue-vben-admin#2975]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

使用 `basicForm` 中的`Select`,`RadioGroup` 和 `RadioButtonGroup` 三个组件的时候，如果 `options` 中 `value` 使用 `number` 类型，并且校验规则使用必填的时候，即使已经选中了某一项，仍然会触发校验 error。

<img width="1018" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/34718241/64d4bc61-9216-44a4-a511-3cbd83f705b8">

其中 `Select` 的配置如下：

```js
    {
      field: 'field4',
      component: 'Select',
      label: '字段4',
      colProps: {
        span: 8,
      },
      componentProps: {
        options: [
          {
            label: '选项1',
            value: 1,
            key: '1',
          },
          {
            label: '选项2',
            value: 2,
            key: '2',
          },
        ],
      },
      rules: [
        {
          required: true,
          message: '请选择',
        },
      ],
    },
```

### 复现 Bug

我基于官方仓库创建了一个可复现仓库（复现代码在 `issues-select-option-number-value` 分支）：

```bash
git clone -b issues-select-option-number-value https://github.com/wencaizhang/vue-vben-admin.git
```

然后安装依赖，启动服务：

```bash
cd vue-vben-admin

pnpm install

pnpm run dev
```

页面路径：`组件/Form/基础表单`

代码位置：`src/views/demo/form/index.vue`

## 系统信息

- 操作系统: MacOS
- Node 版本: v16.18.1
- 包管理器 (npm/yarn/pnpm) 及其版本:  pnpm  8.6.10

**Comment by likui628** [comment]
找到原因了,如果rule里没有type属性就会根据组件类型设置为number或string
https://github.com/vbenjs/vue-vben-admin/blob/e31525a803ee5a7c9770b4eccebe91cc90f7aa60/src/components/Form/src/components/FormItem.vue#L220-L222

我看了下最初的提交历史，最早也是给了默认值，我不确定去掉会怎么样
![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/28ea33d9-b2bc-4789-8b6a-80fcf861cfa2)

你可以给rule加个type，暂时这样。
```
    rules: [
      {
        required: true,
        message: '请选择',
        type: 'number',
      },
    ],
```

**Comment by wencaizhang** [comment]
> 找到原因了,如果rule里没有type属性就会根据组件类型设置为number或string
> 
> https://github.com/vbenjs/vue-vben-admin/blob/e31525a803ee5a7c9770b4eccebe91cc90f7aa60/src/components/Form/src/components/FormItem.vue#L220-L222
> 
> 我看了下最初的提交历史，最早也是给了默认值，我不确定去掉会怎么样 ![image](https://user-images.githubusercontent.com/90845831/263433733-28ea33d9-b2bc-4789-8b6a-80fcf861cfa2.png)
> 
> 你可以给rule加个type，暂时这样。
> 
> ```
>     rules: [
>       {
>         required: true,
>         message: '请选择',
>         type: 'number',
>       },
>     ],
> ```

好的，加个 type 确实可以了。
