### ISSUE TITLE
ReferenceError: Cannot access 'pageWrapperComponent' before initialization

### ISSUE THREAD

**Issue by horizon188** [vbenjs/vue-vben-admin#2978]
ReferenceError: Cannot access 'pageWrapperComponent' before initialization
刷新偶尔会报错

**Comment by horizon188** [comment]
![VKK8%_DT(QQ2TP215239%I](https://github.com/vbenjs/vue-vben-admin/assets/37240607/f7e02687-6f24-43fc-b38f-6388c60b7eeb)

**Comment by horizon188** [comment]
开发环境出现该报错，怎么刷新都会报错。目前解决就是删除cookie再刷新就正常

**Comment by bogdanpetrovsky** [comment]
Hey guys, I have researched this issue in the web.
And it's a Circular Dependency Problem. 
Check out this: https://github.com/vitejs/vite/issues/4430
