### ISSUE TITLE
edge浏览器登录页显示错乱

### ISSUE THREAD

**Issue by liwenxin-jam** [vbenjs/vue-vben-admin#2981]
同样大小的屏幕大小，chrome正常，edge异常，请问这算正常的情况吗？
edge显示如下:
![image](https://github.com/vbenjs/vue-vben-admin/assets/18021581/0b0b9ca0-1804-460b-9f32-224df32a1a77)
chrome显示如下：
![image](https://github.com/vbenjs/vue-vben-admin/assets/18021581/c5c99ebf-7738-48b7-a313-0c24cd7094bb)

**Comment by wangjue666** [comment]
@liwenxin-jam 查看下edge是否安装了 一些浏览器扩展或油猴脚本啥的，有的话关了再看下

**Comment by liwenxin-jam** [comment]
> 

没有安装任何拓展，这台是清洗过的电脑，理论上也是没有油猴脚本
![image](https://github.com/vbenjs/vue-vben-admin/assets/18021581/6c0d06c2-7300-45fa-a94f-735a6a0b1ae0)

**Comment by likui628** [comment]
调试模式下开启响应式
![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/334df24a-c9b4-40f3-8a2f-fe4d0a100c0b)
调试模式下未开启响应式
![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/3867c936-20fe-45b9-a76e-1244db1534bf)
