### ISSUE TITLE
 默认每页显示多少条 defaultPageSize配置项没有起到作用

### ISSUE THREAD

**Issue by 90757665** [vbenjs/vue-vben-admin#2983]
我想设置默认页面显示的条数
defaultPageSize配置项没有起到作用

配置如下：
pageSizeOptions: ['30', '90', '100', '1000', '1000'], 
defaultPageSize: '30',

bug见图
![image](https://github.com/vbenjs/vue-vben-admin/assets/41498674/efa71621-3763-4409-bbb5-72e26932b007)
总是显示10条，是哪里出了问题

**Comment by likui628** [comment]
看了下代码，始终使用的是默认值
https://github.com/vbenjs/vue-vben-admin/blob/7b26c5994cad301ec2b9ee8810b42e97ca10340e/src/components/Table/src/hooks/usePagination.tsx#L42-L62

**Comment by wangjue666** [comment]
改写成

```
pagination: { 
  pageSizeOptions: ['30', '90', '100', '1000', '1000'],
  pageSize: 30
 },
```
问题出在 `/src/components/Table/src/hooks/usePagination.ts`这个文件下的

```
return {
      current: 1,
      pageSize: PAGE_SIZE,
      size: 'small',
      defaultPageSize: PAGE_SIZE,
      showTotal: (total) => t('component.table.total', { total }),
      showSizeChanger: true,
      pageSizeOptions: PAGE_SIZE_OPTIONS,
      itemRender: itemRender,
      showQuickJumper: true,
      ...(isBoolean(pagination) ? {} : pagination),
      ...unref(configRef),
    };
```
在 `antd` 的` pagination` 组件中是 `pageSize` 的生效优先级高于 `defaultPageSize` 

可以看到` PAGE_SIZE` 是个常量，所以生效的只有是 `pageSize`，

解决方案也很简单 删除  `pageSize: PAGE_SIZE,` 这行即可

**Comment by likui628** [comment]
我看错了，传入pageSize就行
```
      :pagination="{
        pageSize: 30,
        pageSizeOptions: ['30', '90', '100', '1000', '1000'],
      }"
```

**Comment by 90757665** [comment]
好的，谢谢
