### ISSUE TITLE
在表格中开启搜索区`useSearchForm:true`,怎样监听搜索字段输入框事件？

### ISSUE THREAD

**Issue by gnyuan** [vbenjs/vue-vben-admin#2984]
在表格中开启搜索区`useSearchForm:true`，请问怎样监听搜索字段输入框事件。

我想达到用户输入搜索词后按回车就立刻搜索，而不需要点击搜索按钮。`@keyup.enter="handleSearch"`这个事件应该写在哪呢？

**Comment by gnyuan** [comment]
已解决，在formConfig中，设置搜索字段Input组件的componentProps即可。
例如：
```javascript
const searchFormSchema = [
    {
    field: 'name',
    label: '名称',
    component: 'Input',
    componentProps: {
        onKeydown: (e: any) => {
        if (e.key === 'Enter') {
            nextTick(async () => {
            handleSearch({ name: e.target.value });
            });
        }
        },
    },
    },

const [registerTable, { reload, expandAll, collapseAll }] = useTable({
    formConfig: {
    schemas: searchFormSchema,
    },
    handleSearchInfoFn: handleSearch,
});

function handleSearch(searchParams: any) {
    searchAreaList(searchParams).then((res) => {
    areaData.data = res;
    reload();
    nextTick(expandAll);
    });
}
```
但有个问题，`searchFormSchema `本来放在data.ts里，但使用了`handleSearch`？有没有朋友知道如何在data.ts里引用`handleSearch`呢？

**Comment by likui628** [comment]
> handleSearch

你可以用formSlots，这样方便点

**Comment by gnyuan** [comment]
找到`Table`中的属性`autoSubmitOnEnter` 设置为true即可，还是很方便的。 [链接](https://doc.vvbin.cn/components/form.html#props)
> 在input中输入时按回车自动提交

**Comment by jobn123** [comment]
> 已解决，在formConfig中，设置搜索字段Input组件的componentProps即可。 例如：
> 
> ```js
> const searchFormSchema = [
>     {
>     field: 'name',
>     label: '名称',
>     component: 'Input',
>     componentProps: {
>         onKeydown: (e: any) => {
>         if (e.key === 'Enter') {
>             nextTick(async () => {
>             handleSearch({ name: e.target.value });
>             });
>         }
>         },
>     },
>     },
> 
> const [registerTable, { reload, expandAll, collapseAll }] = useTable({
>     formConfig: {
>     schemas: searchFormSchema,
>     },
>     handleSearchInfoFn: handleSearch,
> });
> 
> function handleSearch(searchParams: any) {
>     searchAreaList(searchParams).then((res) => {
>     areaData.data = res;
>     reload();
>     nextTick(expandAll);
>     });
> }
> ```
> 
> 但有个问题，`searchFormSchema `本来放在data.ts里，但使用了`handleSearch`？有没有朋友知道如何在data.ts里引用`handleSearch`呢？

这个问题咋解决的呀
