### ISSUE TITLE
RadioButtonGroup 在部署之后样式消失

### ISSUE THREAD

**Issue by FuAdmin** [vbenjs/vue-vben-admin#2986]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
在部署上线之后RadioButtonGroup 在部署之后样式消失

![image](https://github.com/vbenjs/vue-vben-admin/assets/108501535/860372ba-e211-4886-9224-87748ad537df)

请清晰地描述此 Bug 的具体表现。

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by likui628** [comment]
给个最小实现demo

**Comment by oEstate** [comment]
![P9MY7KO N R8HVI}Z)1W86X](https://github.com/vbenjs/vue-vben-admin/assets/30233122/cbb8dff0-824c-4759-85ce-634de596148e)
