### ISSUE TITLE
表单提交报错信息useForm组件Uncaught(in promise) Error:[objec Objec]

### ISSUE THREAD

**Issue by horizon188** [vbenjs/vue-vben-admin#2987]
![369fc19edbd72c092c790d3f4b694f69](https://github.com/vbenjs/vue-vben-admin/assets/37240607/fb2be30b-c48f-4805-95c0-d9e503c8a5e1)
不懂这个报错是什么原因造成的，刷新页面就可以了

**Comment by horizon188** [comment]
期望：解决这个问题
频率：这问题是偶发的

**Comment by horizon188** [comment]
表单组件点击提交按钮

**Comment by likui628** [comment]
看不出来，给个可运行的demo
