### ISSUE TITLE
usetable的api使用  后端是必须有格式限制吗？？

### ISSUE THREAD

**Issue by qing-root** [vbenjs/vue-vben-admin#2992]
文档真的对小白太不友好了  

我api定义如下
<img width="538" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/30001685/733cd1ea-74d4-4248-8375-77721e28c8b0">
`export async function getSiteApi (){

  defHttp.get<SitesResultModel>({
    url: Api.Base,

  });
}
`

-----
SitesResultModel的相关定义如下：

`
export interface ArlBasicFetchResult<T> {
  items: T[];
  total: number;
  page: number;
  size: number;
  query: string;
  code: number;
}

export interface SiteItem {
  site: string;
  title: string;
  headers: string;
  finger: string;
  screenshot: string;
}

//站点信息返回值

export type SitesResultModel = ArlBasicFetchResult<SiteItem>;
`

我这么写是按照我接口的返回值写的：
<img width="738" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/30001685/2573fc03-ecff-4e86-be70-a64c706dd42c">

但是就是请求失败 我确定看到了成功的请求但是表格是没有数据的，表格的dataindex和SiteItem结构里的都一一对应  还是不行

**Comment by byte-voyager** [comment]
数据返回是在result里?

**Comment by qing-root** [comment]
> 

不是的。。。我如果使用它封装的api，我后端的数据比如都在result的字段里吗

**Comment by byte-voyager** [comment]
> > 
> 
> 不是的。。。我如果使用它封装的api，我后端的数据比如都在result的字段里吗

```
{
    "message": "Ok",
    "code": 0,
    "result": {
        "total": 1,
        "items": [
            {
                "id": 3,
            
            }
        ]
    }
}
```

**Comment by qing-root** [comment]
> 

所以如果我使用它封装的defHttp api我后端就必须是这样的返回格式对吗？如果我后端没有result这一层怎么办呢？比如我后端直接返回的数据是：
```
{
        "xxx":2222,
        "total": 1,
        "items": [
            {
                "id": 3,
                 "name":"test",
            }
        ]
    
}
```

我使用的代码如下  ：
```
useTable({api:getSiteApi });



export const getSiteApi2 = (): Promise<返回结构> => {

    defHttp.get<返回结构>({
      url: '/api/site/',
    });

};
```

**Comment by byte-voyager** [comment]
> 

必须调整格式或修改代码

**Comment by qing-root** [comment]
> > 
> 
> 必须调整格式或修改代码

请问如果不改后端的代码，我仅仅在
```
export const getSiteApi2 = (): Promise<返回结构> => {

    defHttp.get<返回结构>({
      url: '/api/site/',
    });

};
``` 这样处理返回格式的话应该怎么改呢？实在搞了很久搞不出来请教下老哥，能用请老哥喝个星巴克

**Comment by likui628** [comment]
看下这里，可以在这里将后端返回的数据转换下
https://github.com/vbenjs/vue-vben-admin/blob/1c1ce4b0e36bd4ad2cf30041089e3e353b76b636/src/utils/http/axios/index.ts#L53
没什么难的，实在不行就加个断点

**Comment by qing-root** [comment]
> 看下这里，可以在这里将后端返回的数据转换下
> 
> https:github.com/vbenjs/vue-vben-admin/blob/1c1ce4b0e36bd4ad2cf30041089e3e353b76b636/src/utils/http/axios/index.ts#L53-L57
> 
> 
> 没什么难的，实在不行就加个断点

好的老哥  我先试试
