### ISSUE TITLE
使用usetable获取数据第一页正常，但后面必卡，加载不出来数据

### ISSUE THREAD

**Issue by qing-root** [vbenjs/vue-vben-admin#2993]
我试了很久很久  一天差不多 都没找到原因，难道又是bug？

   最新版也是，我是这样写的  usetable里设置了api属性为getSiteApi   ，这里我没有用封装的请求函数，直接用的原生的：
这是api的定义，返回的结构字段都和我表格表头dataindex一致
```
export async function getSiteApi(params: SiteParams):Promise<SitesResultModel['items']>  {

    try {
      const response = await axios({
        url: Api.Base,
        params,
        method: 'GET',
        maxRedirects: 5,

      });

      return response.data as SitesResultModel['items'];
    } catch (error) {
      throw error;
    }

  }
```
访问第一页是正常的
<img width="1354" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/30001685/af3e3b4a-905f-4d20-bfc5-6a548c94b8b7">

点击下一页直接卡住转圈 等多久都没用 
<img width="1329" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/30001685/acfbb915-cf14-46e4-9f75-b6c39ab96b81">

而且确定第二个请求是正常返回了数据的 
<img width="1380" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/30001685/302c7820-e4f6-452c-b67e-2bc145d1860b">

**Comment by qing-root** [comment]
真用不一点  费太多时间了

**Comment by likui628** [comment]
``` return response.data as SitesResultModel['items'];```
你的响应结果里只有items，没有data

**Comment by qing-root** [comment]
> ` return response.data as SitesResultModel['items'];` 你的响应结果里只有items，没有data

不是的  response.data才是取到返回的值， 从这里面找iterms

现在是能获取第一页数据 ，但是翻页就转圈卡住，哎
