### ISSUE TITLE
本地图标

### ISSUE THREAD

**Issue by byte-voyager** [vbenjs/vue-vben-admin#2995]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

本地图标功能是移除了? 

https://doc.vvbin.cn/dep/icon.html#%E7%94%9F%E6%88%90

**Comment by wangjue666** [comment]
是的 移除了
