### ISSUE TITLE
useTable返回的getRawDataSource与getDataSource是一样的

### ISSUE THREAD

**Issue by gnyuan** [vbenjs/vue-vben-admin#2999]
这两个是一样的？我以为一个是原始数据，一个是展示到Table上的数据，毕竟定义column的时候可能会写一些format函数，而想要导出excel时，又要执行format函数，如果有办法得到展示在页面上已经格式化好的数据源就好了。

**Comment by vancenlee** [comment]
数据是你自己传送给Table的，你自己应该是有的吧？table上的数据既然不能用，可以直接用你自己的数据即可。
