### ISSUE TITLE
[bug] Tinymce 富文本 图片上传后（replace）未同步更新value

### ISSUE THREAD

**Issue by milcery** [vbenjs/vue-vben-admin#3002]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
 tinymce上传图片成功后，立即提交（获取value）。富文本的内容还是上传中的内容。
 原因：上传完后通过replace替换富文本中的占位字符，只调用了[setValue](https://github.com/vbenjs/vue-vben-admin/blob/89d7a19f3f533fcc0c605548857c915fdd4d488a/src/components/Tinymce/src/Editor.vue#L309C31-L309C31) ，没有emit('update:value' / 'change') 去更新value

### 复现 Bug

上传完后不再去修改富文本就会触发

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by likui628** [comment]
试了下没问题，注意下uploadUrl返回的数据格式

以下代码```response```即接口返回的数据
https://github.com/vbenjs/vue-vben-admin/blob/89d7a19f3f533fcc0c605548857c915fdd4d488a/src/components/Tinymce/src/ImgUpload.vue#L55

**Comment by milcery** [comment]
我试了下确实没问题，抱歉哈。
