### ISSUE TITLE
vxeTable remote api full demo

### ISSUE THREAD

**Issue by doraemonxxx** [vbenjs/vue-vben-admin#3011]
### Subject of the feature

vxeTable remote API full demo
 - create
 - delete
 - update 
 -  reload the table after inserting, delete, and update

**Comment by DesignHhuang** [comment]
> ### Subject of the feature
> vxeTable remote API full demo
> 
> * create
> * delete
> * update
> * reload the table after inserting, delete, and update

This feature has already been implemented in http://localhost:5173/#/comp/table/vxeTable

**Comment by DesignHhuang** [comment]
> how to pass a parameter to vxe table remote api like basic table **searchInfo**

You can organize the required parameters in the form, proxyConfig.ajax.query can accept type like ({ page, sort, sorts, filters, form }) => Promise<any> , you can use `form`  to pass a parameter

**Comment by DesignHhuang** [comment]
> calling `vxeTable.value.proxyConfig.ajax.query(exampleParams);` will just call the Rest API but it won't reload the table. I tried to uses the `commitProxy('query')` but the parameters like form data cannot change

just like this 
![image](https://github.com/vbenjs/vue-vben-admin/assets/3368397/4d488663-840b-4798-bd13-7a333b0432ae)

![image](https://github.com/vbenjs/vue-vben-admin/assets/3368397/b50508bb-6053-4d70-a393-e8a3d27be610)
