### ISSUE TITLE
Use bun as package manager and compiler

### ISSUE THREAD

**Issue by doraemonxxx** [vbenjs/vue-vben-admin#3017]
### Subject of the feature
use bun as compiler and package manager.

Describe your issue here.

### Problem

Current setup is kinda slow. Maybe using Bun will make it faster?

### Expected behaviour

Make application more faster

### Alternatives

None

**Comment by wangjue666** [comment]
@doraemonxxx  It seems that the support for the window platform is not particularly good


![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/7e862a8e-b6be-41f1-bc68-f6bafc88eeb6)
