### ISSUE TITLE
antdv升级4.x版本后项目重新下载下来编译报错

### ISSUE THREAD

**Issue by yaoxiaoheng** [vbenjs/vue-vben-admin#3018]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
请教下大神们，看到antdv升级到4.x版本后我把项目重新拉下来，编译后直接就报这个错，是什么原因呢？

### 复现 Bug
. postinstall$ turbo run stub
│ • Packages in scope: @vben/eslint-config, @vben/hooks, @vben/stylelint-config, @vben/ts-config, @vben/types, @vben/vite-config, server
│ • Running stub in 7 packages
│ • Remote caching disabled
│ @vben/vite-config:stub: cache miss, executing 62ba695850d6adea
│ @vben/eslint-config:stub: cache miss, executing 44b09245502d2df5
│ @vben/stylelint-config:stub: cache miss, executing 1c6b5219aac8d5ce
│ @vben/vite-config:stub:
│ @vben/vite-config:stub: > @vben/vite-config@1.0.0 stub D:\project\vue3.0\vue-vben-admin-main\internal\vite-config
│ @vben/vite-config:stub: > pnpm unbuild --stub
│ @vben/vite-config:stub:
│ @vben/eslint-config:stub:
│ @vben/eslint-config:stub: > @vben/eslint-config@1.0.0 stub D:\project\vue3.0\vue-vben-admin-main\internal\eslint-config
│ @vben/eslint-config:stub: > pnpm unbuild --stub
│ @vben/eslint-config:stub:
│ @vben/stylelint-config:stub:
│ @vben/stylelint-config:stub: > @vben/stylelint-config@1.0.0 stub D:\project\vue3.0\vue-vben-admin-main\internal\stylelint-config
│ @vben/stylelint-config:stub: > pnpm unbuild --stub
│ @vben/stylelint-config:stub:
│ @vben/eslint-config:stub: D:\project\vue3.0\vue-vben-admin-main\node_modules\.pnpm\@babel+types@7.22.5\node_modules\@babel\types\lib\index.js:66
│ @vben/eslint-config:stub: Object.defineProperty(exports, "__internal__deprecationWarning", {
│ @vben/eslint-config:stub:        ^
│ @vben/eslint-config:stub:
│ @vben/eslint-config:stub: TypeError: Cannot redefine property: __internal__deprecationWarning
│ @vben/eslint-config:stub:     at Function.defineProperty (<anonymous>)
│ @vben/eslint-config:stub:     at Object.<anonymous> (D:\project\vue3.0\vue-vben-admin-main\node_modules\.pnpm\@babel+types@7.22.5\node_modules\@babel\types\lib\i…  
│ @vben/eslint-config:stub:     at Module._compile (node:internal/modules/cjs/loader:1241:14)
│ @vben/eslint-config:stub:     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
│ @vben/eslint-config:stub:     at Module.load (node:internal/modules/cjs/loader:1091:32)
│ @vben/eslint-config:stub:     at Module._load (node:internal/modules/cjs/loader:938:12)
│ @vben/eslint-config:stub:     at Module.require (node:internal/modules/cjs/loader:1115:19)
│ @vben/eslint-config:stub:     at require (node:internal/modules/helpers:130:18)
│ @vben/eslint-config:stub:     at Object.<anonymous> (D:\project\vue3.0\vue-vben-admin-main\node_modules\.pnpm\@babel+types@7.22.5\node_modules\@babel\types\lib\b…  
│ @vben/eslint-config:stub:     at Module._compile (node:internal/modules/cjs/loader:1241:14)
│ @vben/eslint-config:stub:
│ @vben/eslint-config:stub: Node.js v20.6.0
│ @vben/stylelint-config:stub: D:\project\vue3.0\vue-vben-admin-main\node_modules\.pnpm\@babel+types@7.22.5\node_modules\@babel\types\lib\index.js:66
│ @vben/stylelint-config:stub: Object.defineProperty(exports, "__internal__deprecationWarning", {
│ @vben/stylelint-config:stub:        ^
│ @vben/stylelint-config:stub:
│ @vben/stylelint-config:stub: TypeError: Cannot redefine property: __internal__deprecationWarning
│ @vben/stylelint-config:stub:     at Function.defineProperty (<anonymous>)
│ @vben/stylelint-config:stub:     at Object.<anonymous> (D:\project\vue3.0\vue-vben-admin-main\node_modules\.pnpm\@babel+types@7.22.5\node_modules\@babel\types\li…  
│ @vben/stylelint-config:stub:     at Module._compile (node:internal/modules/cjs/loader:1241:14)
│ @vben/stylelint-config:stub:     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
│ @vben/stylelint-config:stub:     at Module.load (node:internal/modules/cjs/loader:1091:32)
│ @vben/stylelint-config:stub:     at Module._load (node:internal/modules/cjs/loader:938:12)
│ @vben/stylelint-config:stub:     at Module.require (node:internal/modules/cjs/loader:1115:19)
│ @vben/stylelint-config:stub:     at require (node:internal/modules/helpers:130:18)
│ @vben/stylelint-config:stub:     at Object.<anonymous> (D:\project\vue3.0\vue-vben-admin-main\node_modules\.pnpm\@babel+types@7.22.5\node_modules\@babel\types\li…  
│ @vben/stylelint-config:stub:     at Module._compile (node:internal/modules/cjs/loader:1241:14)
│ @vben/stylelint-config:stub:
│ @vben/stylelint-config:stub: Node.js v20.6.0
│ @vben/eslint-config:stub:  ELIFECYCLE  Command failed with exit code 1.
│ @vben/vite-config:stub: D:\project\vue3.0\vue-vben-admin-main\node_modules\.pnpm\@babel+types@7.22.5\node_modules\@babel\types\lib\index.js:66
│ @vben/vite-config:stub: Object.defineProperty(exports, "__internal__deprecationWarning", {
│ @vben/vite-config:stub:        ^
│ @vben/vite-config:stub:
│ @vben/vite-config:stub: TypeError: Cannot redefine property: __internal__deprecationWarning
│ @vben/vite-config:stub:     at Function.defineProperty (<anonymous>)
│ @vben/vite-config:stub:     at Object.<anonymous> (D:\project\vue3.0\vue-vben-admin-main\node_modules\.pnpm\@babel+types@7.22.5\node_modules\@babel\types\lib\ind…  
│ @vben/vite-config:stub:     at Module._compile (node:internal/modules/cjs/loader:1241:14)
│ @vben/vite-config:stub:     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
│ @vben/vite-config:stub:     at Module.load (node:internal/modules/cjs/loader:1091:32)
│ @vben/vite-config:stub:     at Module._load (node:internal/modules/cjs/loader:938:12)
│ @vben/vite-config:stub:     at Module.require (node:internal/modules/cjs/loader:1115:19)
│ @vben/vite-config:stub:     at require (node:internal/modules/helpers:130:18)
│ @vben/vite-config:stub:     at Object.<anonymous> (D:\project\vue3.0\vue-vben-admin-main\node_modules\.pnpm\@babel+types@7.22.5\node_modules\@babel\types\lib\bui…  
│ @vben/vite-config:stub:     at Module._compile (node:internal/modules/cjs/loader:1241:14)
│ @vben/vite-config:stub:
│ @vben/vite-config:stub: Node.js v20.6.0
│ @vben/stylelint-config:stub:  ELIFECYCLE  Command failed with exit code 1.
│ @vben/vite-config:stub:  ELIFECYCLE  Command failed with exit code 1.
│ @vben/eslint-config:stub: ERROR: command finished with error: command (D:\project\vue3.0\vue-vben-admin-main\internal\eslint-config) pnpm run stub exited (1)       
│ command (D:\project\vue3.0\vue-vben-admin-main\internal\eslint-config) pnpm run stub exited (1)
│  Tasks:    0 successful, 3 total
│ Cached:    0 cached, 3 total
│   Time:    2.173s
│ Failed:    @vben/eslint-config#stub
│  ERROR  run failed: command  exited (1)
└─ Failed in 2.2s at D:\project\vue3.0\vue-vben-admin-main

## 系统信息

- 操作系统: win10
- Node 版本: v20.6.0
- 包管理器 (npm/yarn/pnpm) 及其版本: npm-9.8.1   pnpm-8.7.5

**Comment by wangjue666** [comment]
是安装依赖成功后postinstall指令的问题，而不是打包的问题（其实项目这时候是可以跑的)。 你可以删除所有依赖，开个代理重新安装下试试

**Comment by yaoxiaoheng** [comment]
没有代理，升级nodejs到v20.6.1后，postinstall指令就正常了
