### ISSUE TITLE
最新代码 antd4 modal全屏显示有bug

### ISSUE THREAD

**Issue by 1455668754** [vbenjs/vue-vben-admin#3019]
modal全屏显示有bug，最新代码 antd4

![image](https://github.com/vbenjs/vue-vben-admin/assets/88491446/2993c7a4-6fc8-406b-84ed-3c6dac1be39f)

**Comment by wangjue666** [comment]
@1455668754  已修复，可以关闭issue了

**Comment by tw358** [comment]
![Snipaste_2023-09-19_09-39-34](https://github.com/vbenjs/vue-vben-admin/assets/20203597/18484962-b5e4-4026-aa77-61ecb18d5c79)

全屏存在样式BUG

**Comment by wangjue666** [comment]
@tw358  那个圆角就是新版antd组件的变动
