### ISSUE TITLE
升级antd4后，在顶部菜单混合模式下，头部导航栏样式错位

### ISSUE THREAD

**Issue by cnzdq** [vbenjs/vue-vben-admin#3021]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

运行最新代码，在在顶部菜单混合模式下，并且打开分割菜单选项，头部导航栏样式错位

### 复现 Bug

![image](https://github.com/vbenjs/vue-vben-admin/assets/30411977/669f06d8-7984-4a67-83fb-6f2cc4a7d1e1)

![image](https://github.com/vbenjs/vue-vben-admin/assets/30411977/77d45da6-d79c-4dc5-b174-8864eca55556)

## 系统信息

- 操作系统: windows
- Node 版本: 18.12.1
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm

**Comment by wangjue666** [comment]
@cnzdq  已修复，可以关闭issue了
