### ISSUE TITLE
RadioButtonGroup 组件 onChange事件会触发两次

### ISSUE THREAD

**Issue by chen-collab** [vbenjs/vue-vben-admin#3025]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

在table组件中包裹时 RadioButtonGroup 按钮chang事件触发两次执行

onChange事件会触发两次

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统: win11
- Node 版本: 18.11.0
- 包管理器 (npm/yarn/pnpm) 及其版本:  8

**Comment by likui628** [comment]
给个能复现的demo

**Comment by KaneOne** [comment]
> 给个能复现的demo
我也遇到了，在demo的基础表单中添加RadioButtonGroup组件即可复现：
```
    {
      field: 'fieldradiobutton',
      label: 'RadioButtonGroup测试',
      component: 'RadioButtonGroup',
      componentProps: {
        options: ['a', 'b'],
        onChange: (e) => {
          console.log('RadioButtonGroup====>:', e);
        },
      },
      colProps: {
        span: 12,
      },
    },
```
![image](https://github.com/vbenjs/vue-vben-admin/assets/1954595/9bd85d56-0afe-47b1-af2b-52bd74f4fc3d)
onChange事件会触发两次，第一次是传入了Event对象，第二次传入了Value，看起来是封装时因为事件冒泡导致的
![image](https://github.com/vbenjs/vue-vben-admin/assets/1954595/1a2c7203-87ca-46a9-acf5-6f3c8380e4d4)
