### ISSUE TITLE
重新进入页面后如何不刷新

### ISSUE THREAD

**Issue by jixiaomm** [vbenjs/vue-vben-admin#3031]
问题描述：
从列表页跳转到任务详情页，再返回列表页时，页面会自动刷新，且回到列表第一页
需求：
返回到列表页后，不刷新

**Comment by likui628** [comment]
文档里有写[如何开启页面缓存](https://doc.vvbin.cn/guide/router.html#%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AF%E9%A1%B5%E9%9D%A2%E7%BC%93%E5%AD%98)

**Comment by bzb745300** [comment]
> 文档里有写[如何开启页面缓存](https://doc.vvbin.cn/guide/router.html#%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AF%E9%A1%B5%E9%9D%A2%E7%BC%93%E5%AD%98)

thanks
