### ISSUE TITLE
两个问题，麻烦看一下

### ISSUE THREAD

**Issue by Jvinhao** [vbenjs/vue-vben-admin#3032]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
1.   新 git下来的代码，和线上的环境无差异，但是表格的展开报错了，进入展开表格的页面，页面就崩溃了。
2.  另外还有一个ant的组件过期了，升级到4.0之后出现了该问题，直接使用ToolTip，无异常, 比对之后，BasicTable 这个组件里面可能用到了ToolTip，因为页面中注释掉BasicTable，无该警告，深入进去可能是由于这里可能需要更新：BasicTable -》HeaderCell -〉BasicHelp -》BasicHelp 用到了 Tooltip
请清晰地描述此 Bug 的具体表现。

### 复现 Bug
1、bug截图
<img width="1439" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/49309753/c75ae2cf-05b8-42d5-a13c-7b3fd96a076d">
2、代码截图
<img width="910" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/49309753/9fad33fb-57f7-4f2f-be57-d765c536c88e">

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by Jvinhao** [comment]
操作系统: MacOS
Node 版本:  node v16.19.1 (npm v8.19.3)
包管理器 (npm/yarn/pnpm) 及其版本: pnpm

**Comment by wangjue666** [comment]
@Jvinhao  再重新下载下最新的代码 表格展开正常的

**Comment by wangjue666** [comment]
@Jvinhao  第二个组件过期的问题 已提PR #3033

**Comment by Jvinhao** [comment]
@wangjue666 收到，已经拉取了最新代码，可以展开了
