### ISSUE TITLE
BasicTable 开启搜索表单之后查询按钮失效

### ISSUE THREAD

**Issue by Jvinhao** [vbenjs/vue-vben-admin#3034]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
BasicTable 开启搜索表单，点击查询按钮无反应，点击重置按钮会请求接口 

### 复现 Bug
1、点击重置按钮有请求
<img width="1439" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/49309753/f2d9e6fa-0f1a-4f41-b06d-5f12446ca71f">
2、点击查询按钮无请求
<img width="1437" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/49309753/288fcf71-d0f1-4239-ac44-68c9270d02e0">

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by Tairy** [comment]
+1+1. 升级了最新的代码之后就出这个问题了，demo 网站上的也不能用。

**Comment by klgd** [comment]
+1 我以为我的业务代码有问题，调试半天

**Comment by likui628** [comment]
已修复 #3036
