### ISSUE TITLE
ROUTE_MAPPINGl路由模式下刷新路由丢失

### ISSUE THREAD

**Issue by sugar258596** [vbenjs/vue-vben-admin#3041]
ROUTE_MAPPINGl路由模式下，关闭了mock数据模拟，登录的时候是有路由的，但是进行页面刷新后，路由丢失了，并且进行路由导航无法导航

**Comment by DesignHhuang** [comment]
关闭了mock数据模拟，你是怎么登录的额。。。使用真实的Api，也要判断是不是异步加载路由的等等

**Comment by sugar258596** [comment]
解决了，需要调用一个方法进行获取路由




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月27日(星期三) 下午5:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vbenjs/vue-vben-admin] ROUTE_MAPPINGl路由模式下刷新路由丢失 (Issue #3041)





 
关闭了mock数据模拟，你是怎么登录的额。。。使用真实的Api，也要判断是不是异步加载路由的等等
