### ISSUE TITLE
Remove transitions for form validation and dark mode

### ISSUE THREAD

**Issue by doraemonxxx** [vbenjs/vue-vben-admin#3042]
Can please remove the slow transition/animation when form validation and dark mode? Because it causes delay and is not good for the eye of the user.

Please refer to this: https://www.awesomescreenshot.com/video/20848249?key=020d3f62da70afcb9fd5ac0e09f3028f

**Comment by wangjue666** [comment]
@doraemonxxx  yeah, Maybe you can modify the _useModalInner_ function to add a hook function to _closeModal_

> The form validation reset field should be call before closing a modal or a drawer. this way when opening the modal or drawer again, the input errors should not be seen.

**Comment by wangjue666** [comment]
slow transition animation when toggle mode, Mmm, I upgraded the way to switch to dark mode, Switching to dark mode should be smoother now. see pr https://github.com/vbenjs/vue-vben-admin/pull/3051
