### ISSUE TITLE
ScrollContainer的一个问题

### ISSUE THREAD

**Issue by wf2019** [vbenjs/vue-vben-admin#3046]
我看见文档上面说是参考 element-ui 的 el-scrollbar 组件实现的。
但是我遇到一个问题，就是当ScrollContainer组件里面的内容高度发生变化的时候，滚动条的高度并没有因为内容的高度变化而变化。
这样就出现一个样式问题，就是内容高度增加了，滚动条可能需要超出容器才能滑动到底部。
相反的，内容高度减少了，滚动条可能滑动到一半的时候就到底了。。。

**Comment by wf2019** [comment]
在系统管理->账号管理->新增账号，将备注的输入框高度拖高就能复现。关闭重新打开，滚动条高度就正确了。

**Comment by likui628** [comment]
问题出在这里
![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/6228282f-c755-43e6-92e8-825994ba9e1d)
监听不到resize的变化

**Comment by DesignHhuang** [comment]
> 问题出在这里 ![image](https://user-images.githubusercontent.com/90845831/273488902-6228282f-c755-43e6-92e8-825994ba9e1d.png) 监听不到resize的变化

添加了一个scrollheight用来监听scrollbar内部元素的realheight，若realheight改变的话则重新计算scrollbar的sizeHeight。

**Comment by DesignHhuang** [comment]
其实也可以使用原生的scrollbar，原生的scrollbar不会出现这种问题。
只要设置scrollbar组件的native为true就可以了，可以在代码中自行控制。如果native设置为false，可以采用 #3119 方式。
![image](https://github.com/vbenjs/vue-vben-admin/assets/3368397/b164093d-ef2f-4c89-8567-c1a65078a6f0)
