### ISSUE TITLE
讲道理 暗黑模式真的丑 会修改吗？

### ISSUE THREAD

**Issue by Jzow** [vbenjs/vue-vben-admin#3047]

**Comment by wangjue666** [comment]
@Jzow  你好，切换暗黑主题的方案已经做出了调整，可以查看这个PR [#3051](https://github.com/vbenjs/vue-vben-admin/pull/3051)，之后要扩展新主题可以参考 [antd4的定制主题](https://next.antdv.com/docs/vue/customize-theme-cn)

**Comment by Jzow** [comment]
@wangjue666  好像还是有点问题 暗黑模式下 还是windows高亮模式那种效果 可能需要再check一下

**Comment by wangjue666** [comment]
@Jzow  这里的暗黑主题用的是antd默认提供的暗黑配色，可能你需要自己去调整一下配色

**Comment by Jzow** [comment]
> @Jzow 这里的暗黑主题用的是antd默认提供的暗黑配色，可能你需要自己去调整一下配色

有没有联系方式加一个

**Comment by wangjue666** [comment]
qq: 396449661
