### ISSUE TITLE
日期相关组件选择完会再次展开面板

### ISSUE THREAD

**Issue by zmcode** [vbenjs/vue-vben-admin#3048]
### 描述 Bug

使用表单组件的时候, 使用日期相关组件, 选择完日期后, 会导致面板继续展开 ,可以看官网的例子: https://vben.vvbin.cn/#/comp/form/basic
![image](https://github.com/vbenjs/vue-vben-admin/assets/48686959/c7fdf091-6a7e-4faf-8889-4e3a80ddccd7)

ant-design-vue 官网的日期是不会有这个情况的

### 复现 Bug
https://vben.vvbin.cn/#/comp/form/basic  

 滚动到日期范围那个选择项

 选择完日期后, 还是弹出面板, 让用户选择日期

## 系统信息

- 操作系统: window10
- Node 版本: 16.14.0
- pnpm: 8.4.0

**Comment by zmcode** [comment]
还有一个问题 在hover 日期的时候(显示虚线范围), 会明显的卡顿, 

例如RangePicker在hover日期, 选择范围时, 会很卡, 官网就不会

**Comment by likui628** [comment]
经排查是antdv的bug

**Comment by mosu1314** [comment]
临时问题修复：
vue-vben-admin/src/components/Form/src/components/FormItem.vue 
内将
getPopupContainer: (trigger: Element) => trigger.parentNode
修改成
getPopupContainer:
  component === 'RangePicker'
    ? (trigger: Element) => {
        const { parentNode } = trigger;
        return parentNode?.parentNode || parentNode;
      }
    : (trigger: Element) => trigger.parentNode

**Comment by DesignHhuang** [comment]
> 经排查是antdv的bug [vueComponent/ant-design-vue#6911](https://github.com/vueComponent/ant-design-vue/issues/6911)

这个问题应该已经解决了，我在Antdv上的PR已经合并了。。。

**Comment by likui628** [comment]
@DesignHhuang 带时间的范围还是有问题，可以看下我的PR #3160
![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/2e2d1404-2cf8-4043-af23-0e26cee69f47)

**Comment by DesignHhuang** [comment]
> @DesignHhuang 带时间的范围还是有问题，可以看下我的PR #3160 ![image](https://user-images.githubusercontent.com/90845831/275517058-2e2d1404-2cf8-4043-af23-0e26cee69f47.png)

嗯，时间选择器也需要处理下，我明天再提个PR给antdv

**Comment by likui628** [comment]
等待 https://github.com/vueComponent/ant-design-vue/pull/7026
