### ISSUE TITLE
TypeError: Cannot destructure property 'VITE_GLOB_APP_TITLE' of 'C' as it is undefined.

### ISSUE THREAD

**Issue by sunfeng90** [vbenjs/vue-vben-admin#3053]
你好，我用贵项目做为乾坤的子应用，结果报如下错误：

TypeError: Cannot destructure property 'VITE_GLOB_APP_TITLE' of 'C' as it is undefined.

不知道如何解决

"vite-plugin-html": "^3.2.0",降级为2.1.2,，貌似也不行

.env的配置如下：

# port
VITE_PORT = 3300

# spa-title
VITE_GLOB_APP_TITLE =XXXX超管端

# spa shortname
VITE_GLOB_APP_SHORT_NAME = DevlingAdmin

**Comment by likui628** [comment]
参考下先
https://github.com/vbenjs/vue-vben-admin/pull/2794
https://github.com/vbenjs/vue-vben-admin/issues/2949

**Comment by sunfeng90** [comment]
VITE_GLOB_APP_TITLE全部中文，并且没有横线分割，这个可以的吧？

**Comment by sunfeng90** [comment]
VITE_GLOB_APP_SHORT_NAME是不是要全部大写？我目前是DevelopingAdmin

**Comment by sunfeng90** [comment]
我修改VITE_GLOB_APP_TITLE为全大写，下划线分割，横向分割，都不能解决问题，依然提示：'VITE_GLOB_APP_TITLE' of 'C' as it is undefined

我单独启动是好的，发布到线上就不行

**Comment by likui628** [comment]
本地开发环境和线上版本的配置不一样吧

**Comment by sunfeng90** [comment]
一样的



---- 回复的原邮件 ----
| 发件人 | Li ***@***.***> |
| 日期 | 2023年09月20日 19:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [vbenjs/vue-vben-admin] TypeError: Cannot destructure property 'VITE_GLOB_APP_TITLE' of 'C' as it is undefined. (Issue #3053) |

本地开发环境和线上版本的配置不一样吧

**Comment by sunfeng90** [comment]
现在提示n is not defined



---- 回复的原邮件 ----
| 发件人 | Li ***@***.***> |
| 日期 | 2023年09月20日 19:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [vbenjs/vue-vben-admin] TypeError: Cannot destructure property 'VITE_GLOB_APP_TITLE' of 'C' as it is undefined. (Issue #3053) |

本地开发环境和线上版本的配置不一样吧

**Comment by sunfeng90** [comment]
ypeError: Cannot destructure property 'VITE_GLOB_APP_TITLE' of 't' as it is undefined

现在提示这个错误

**Comment by sunfeng90** [comment]
最后解决了下面代码有问题

export function getAppEnvConfig() {
  // const ENV_NAME = getConfigFileName(import.meta.env)

  // const ENV = import.meta.env.DEV
  //   ? // Get the global configuration (the configuration will be extracted independently when packaging)
  //     (import.meta.env as unknown as GlobEnvConfig)
  //   : (window[ENV_NAME as any] as unknown as GlobEnvConfig)

  // const {
  //   VITE_GLOB_APP_TITLE,
  //   VITE_GLOB_API_URL,
  //   VITE_GLOB_APP_SHORT_NAME,
  //   VITE_GLOB_API_URL_PREFIX,
  //   VITE_GLOB_UPLOAD_URL,
  // } = ENV
}
直接写死全局配置就可以了，因为环境变量获取不到导致的

**Comment by Jzow** [comment]
> 最后解决了下面代码有问题
> 
> export function getAppEnvConfig() { // const ENV_NAME = getConfigFileName(import.meta.env)
> 
> // const ENV = import.meta.env.DEV // ? // Get the global configuration (the configuration will be extracted independently when packaging) // (import.meta.env as unknown as GlobEnvConfig) // : (window[ENV_NAME as any] as unknown as GlobEnvConfig)
> 
> // const { // VITE_GLOB_APP_TITLE, // VITE_GLOB_API_URL, // VITE_GLOB_APP_SHORT_NAME, // VITE_GLOB_API_URL_PREFIX, // VITE_GLOB_UPLOAD_URL, // } = ENV } 直接写死全局配置就可以了，因为环境变量获取不到导致的

参考 #2794 就可以了 可以不用注释
