### ISSUE TITLE
CountdownInput组件 如何才能添加自定义验证

### ISSUE THREAD

**Issue by Jzow** [vbenjs/vue-vben-admin#3054]
```typescript
      <FormItem name="sms" class="enter-x">
        <CountdownInput
          size="large"
          class="fix-auto-fill"
          v-model:value="formData.sms"
          :placeholder="t('sys.login.smsCode')"
        />
```

我在用手机号码注册，但是手机号还没有进行输入，倒计时组件就可以运行，应该判断手机号进行输入了才能进行倒计时

**Comment by Jzow** [comment]
sendCodeApi 函数如何使用有例子吗

**Comment by DesignHhuang** [comment]
sendCodeApi 就是用来控制是否开始的。
好好读这段代码吧：
![image](https://github.com/vbenjs/vue-vben-admin/assets/3368397/9ca8dd51-940a-42aa-82b5-235e26eb714c)

如果想控制手机号，可以这样写：
![image](https://github.com/vbenjs/vue-vben-admin/assets/3368397/88c57cda-4fb7-4f1b-817b-2a93a10da3f5)

但具体的逻辑还是要你自己去的，这个Issue关了吧
