### ISSUE TITLE
公共封装主键报错

### ISSUE THREAD

**Issue by IT0010** [vbenjs/vue-vben-admin#3066]
### 描述 Bug

打包时出现两个报错，代码如下
 WARN  Export "default" of module "src/components/Icon/src/SvgIcon.vue" was reexported through module "src/components/Icon/index.ts" while both modules are dependencies of each other and will end up in different chunks 
by current Rollup settings. This scenario is not well supported at the moment as it will produce a circular dependency between chunks and will likely lead to broken execution order.
Either change the import in "src/views/demo/feat/icon/index.vue?vue&type=script&lang.ts" to point directly to the exporting module or reconfigure "output.manualChunks" to ensure these modules end up in the same chunk.  

 WARN  [plugin:vite:reporter]                                                                                                                                                                                    17:59:32  
(!) C:/Users/Administrator/Desktop/daiLI/vue-vben-admin/src/components/SimpleMenu/src/SimpleMenuTag.vue is dynamically imported by C:/Users/Administrator/Desktop/daiLI/vue-vben-admin/src/components/SimpleMenu/src/SimpleSubMenu.vue?vue&type=script&lang.ts but also statically imported by C:/Users/Administrator/Desktop/daiLI/vue-vben-admin/src/components/SimpleMenu/index.ts, dynamic import will not move module into another chunk.

### 复现 Bug

打包时出现

## 系统信息

- 操作系统: window10
- Node 版本: 18.14.2
- 包管理器 (npm/yarn/pnpm) 及其版本: 最新版

**Comment by wangjue666** [comment]
重新安装下依赖看看
