### ISSUE TITLE
expandedRowRender与headerCell插槽不能共存

### ISSUE THREAD

**Issue by youxiaqishi** [vbenjs/vue-vben-admin#3070]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

请清晰地描述此 Bug 的具体表现。

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by likui628** [comment]
给个代码段看看

**Comment by youxiaqishi** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/25716402/c3e75b3c-ae2e-4c8c-be8e-a79ce11fd7de)
![image](https://github.com/vbenjs/vue-vben-admin/assets/25716402/aad8bf11-ad5e-4e37-9959-1a7bc0a11738)
上面一个是报错 下面一个是两个插槽同时使用的情况

**Comment by DesignHhuang** [comment]
不要在组件代码中做这件事，应该在业务代码中处理，如下：
![image](https://github.com/vbenjs/vue-vben-admin/assets/3368397/7cb2c7ac-f8bf-4aba-9a5d-16d1a64905db)

**Comment by lovelyJason** [comment]
怎么解决的
