### ISSUE TITLE
basictree删除根节点后报错

### ISSUE THREAD

**Issue by sunkunGitHub** [vbenjs/vue-vben-admin#3073]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
basictree组件 ![微信图片_20230926143321](https://github.com/vbenjs/vue-vben-admin/assets/14904244/403cfd98-065c-479d-9606-f15ed1b283bb)
TypeError: Cannot read properties of undefined (reading 'parent')

请清晰地描述此 Bug 的具体表现。

### 复现 Bug
1、在basictree中添加一个根节点
2、在这个根节点中再添加一个子节点
3、刷新页面
4、删除根节点，控制台出现报错信息
请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:windows server 2022 standard
- Node 版本:16.17.0
- 包管理器 (npm/yarn/pnpm) 及其版本:8.6.5

**Comment by wangjue666** [comment]
@sunkunGitHub  提供下复现代码

**Comment by sunkunGitHub** [comment]
<template&gt; <div&gt; <PageWrapper contentClass="flex" dense contentFullHeight fixedHeight&gt; <BasicTree ref="treeRef" toolbar search class="w-1/4 xl:w-1/5" :treeData="treeData" :actionList="actionList" :showIcon="true" @select="onSelect" draggable @dragstart="onDragStart" @dragenter="onDragEnter" @drop="onDrop" /&gt; <FormVerify ref="formVerify" :entity="entity" :type="params.type" :privilege="false" :page="'ex-tree/operation'" :pageChildren="[]" @load-rule="callBackRule" dense contentFullHeight fixedHeight contentClass="flex" class="w-3/4 xl:w-4/5 pl-1" :contentStyle="{ 'background-color': 'white', padding: '20px 20px 0px 20px', }" &gt; <template #headerContent&gt; <a-button type="primary" class="mr-2" @click="submit" v-if="params.type != 'info'"&gt; 保存 </a-button&gt; <a-button type="primary" class="mr-2" @click="cancel" v-if="params.type != 'info'"&gt; 取消 </a-button&gt; </template&gt; <BasicForm @register="register" :disabled="params.type == 'info'" style="width: 100%" /&gt; </FormVerify&gt; </PageWrapper&gt; </div&gt;</template&gt;
<script lang="ts"&gt; import { defineComponent, ref, unref, nextTick, h, onMounted, createVNode } from 'vue'; import { PageWrapper } from '/@/components/Page'; import { FormVerify } from '/@/components/FormVerify'; import { BasicTree, TreeActionType, TreeActionItem, TreeItem, TreeNodeMoveType, } from '/@/components/Tree/index'; import { usePermission } from '/@/hooks/web/usePermission'; import { PlusOutlined, EditOutlined, DeleteOutlined, ExclamationCircleOutlined, } from ***@***.***/icons-vue'; import { AntTreeNodeDragEnterEvent, AntTreeNodeDropEvent } from 'ant-design-vue/es/tree'; import { BasicForm, useForm } from '/@/components/Form'; import { buildUUID } from '/@/utils/uuid'; import { get, getTreeList, move, deleteById, create, update } from '/@/api/demo/ex-tree/ex-tree'; import { orderBy } from 'lodash-es'; import { Modal } from 'ant-design-vue'; import { useMessage } from '/@/hooks/web/useMessage'; import { ExTree } from '/@/api/demo/ex-tree/model/extreeModel';
export default defineComponent({ name: 'ExTree', });</script&gt;
<script lang="ts" setup&gt; const { createMessage } = useMessage(); const params = ref({ type: 'info', }); const entity = ref<ExTree&gt;({ id: buildUUID() }); const entity_beforeModify = ref<ExTree&gt;({}); const formVerify = ref<any&gt;(); const formVerifyRule = ref<any&gt;(); const treeRef = ref<Nullable<TreeActionType&gt;&gt;(null); const treeData = ref<TreeItem[]&gt;([]); const { hasPermission } = usePermission(); const formSchema = ref<any&gt;([]); const expandedKeys = ref<any&gt;(); console.log('document: ', document.body.clientHeight);
const actionList: TreeActionItem[] = [ { show: () =&gt; { return hasPermission('ex-tree.add'); }, // 新增节点 render: (node) =&gt; { return h(PlusOutlined, { title: '新增', onClick: (event) =&gt; { // 处理节点select逻辑 getTree().setSelectedKeys([node.key]); event.stopPropagation();
get({ id: node.key }).then((res) =&gt; { entity_beforeModify.value = { ...res }; });
params.value.type = 'add'; entity.value = new ExTree(); entity.value.parentId = node.key;
setFieldsValue(entity.value); }, }); }, }, { // 修改节点 show: (record) =&gt; { return record.extends.canUpdate &amp;&amp; hasPermission('ex-tree.update'); }, render: (node) =&gt; { return h(EditOutlined, { title: '修改', onClick: async (event) =&gt; { // 处理节点select逻辑 getTree().setSelectedKeys([node.key]); event.stopPropagation();
params.value.type = 'update'; entity.value = await get({ id: node.key }); entity_beforeModify.value = { ...entity.value }; setFieldsValue(entity.value); }, }); }, }, { // 删除节点 show: (record) =&gt; { return hasPermission('ex-tree.delete'); }, render: (node) =&gt; { return h(DeleteOutlined, { title: '删除', onClick: (event) =&gt; { // 处理节点select逻辑 getTree().setSelectedKeys([node.key]); event.stopPropagation(); const searchValue = getTree().getSearchValue(); Modal.confirm({ title: () =&gt; `确认删除该节点吗？`, icon: () =&gt; createVNode(ExclamationCircleOutlined), content: () =&gt; '该节点及其所有子节点数据将一同被删除。', okText: () =&gt; '确定', okType: 'danger', cancelText: () =&gt; '取消', onOk() { deleteById({ id: node.key }).then(() =&gt; { createMessage.success('删除成功');
getTree().deleteNodeByKey(node.key);
getTree().setSearchValue(searchValue); }); }, }); }, }); }, }, ];
/** 树节点点击选择事件方法 */ async function onSelect(selectedKeys, e) { params.value.type = 'info'; if (e.selected) { entity.value = await get({ id: selectedKeys[0] }); } else { entity.value = new ExTree(); } setFieldsValue(entity.value); }
function onDragStart(info) { console.log(info); }
function onDragEnter(info: AntTreeNodeDragEnterEvent) { expandedKeys.value = info.expandedKeys; }
function onDrop(info: AntTreeNodeDropEvent) { let sourceId = info.dragNode.key; let sourceTitle = info.dragNode.extends.title; let targetId = info.node.key; let targetTitle = info.node.extends.title; let moveType: TreeNodeMoveType | undefined = undefined; let moveTypeStr = '';
let dropPosition = info.dropPosition; let dropToGap = info.dropToGap; /* 目标节点内部 dropPosition=目标节点dropPosition,dropToGap=false 目标节点之前 dropPosition=-1,dropToGap=true 目标节点之后 dropPosition=目标节点dropPosition+1,dropToGap=true */ if (dropToGap == false) { moveType = TreeNodeMoveType.Inner; moveTypeStr = `内部`; } else if (dropPosition == -1 &amp;&amp; dropToGap == true) { moveType = TreeNodeMoveType.Before; moveTypeStr = `之前`; } else if (dropPosition &gt; 0 &amp;&amp; dropToGap == true) { moveType = TreeNodeMoveType.After; moveTypeStr = `之后`; }
if (moveType === undefined) { Modal.error({ title: '节点移动错误', content: `未明确节点的移动目标位置`, }); } else { Modal.confirm({ title: () =&gt; `确认移动“${sourceTitle}”吗？`, icon: () =&gt; createVNode(ExclamationCircleOutlined), content: () =&gt; `将该节点移动到“${targetTitle}”${moveTypeStr}`, okText: () =&gt; '确定', okType: 'danger', cancelText: () =&gt; '取消', onOk() { move({ id: sourceId, targetId: targetId, moveType: moveType }).then(async () =&gt; { createMessage.success('操作成功');
await initTree([sourceId]); nextTick(() =&gt; { expandedKeys.value.push(targetId); getTree().setExpandedKeys(expandedKeys.value); });
entity.value = await get({ id: sourceId }); setFieldsValue(entity.value); }); }, }); } }
// 表单对象 const [register, { setFieldsValue, updateSchema, validate }] = useForm({ labelWidth: 120, baseColProps: { span: 8 }, layout: 'vertical', wrapperCol: { style: 'margin:0px 15px 0px 0px' }, showActionButtonGroup: false, schemas: formSchema, });
async function callBackRule(rule: any) { formVerifyRule.value = rule; formSchema.value = [ { field: 'treeCode', component: 'Input', label: '节点编码', componentProps: { readonly: true, placeholder: '自动生成', }, }, { field: 'code', component: 'Input', label: '业务编码', defaultValue: 0, componentProps: { disabled: formVerifyRule.value['code'].disabled, }, rules: formVerifyRule.value['code'].rules, show: !formVerifyRule.value['code'].invisible, }, { field: 'name', component: 'Input', label: '业务名称', componentProps: { disabled: formVerifyRule.value['name'].disabled, }, rules: formVerifyRule.value['name'].rules, show: !formVerifyRule.value['name'].invisible, }, { field: 'isActive', component: 'Checkbox', label: '是否启用', componentProps: { disabled: formVerifyRule.value['isActive'].disabled, }, rules: formVerifyRule.value['isActive'].rules, show: !formVerifyRule.value['isActive'].invisible, }, ]; updateSchema(formSchema.value); }
onMounted(async () =&gt; { let key = await initTree(); if (key) { // 加载节点的详细数据 entity.value = await get({ id: key[0] }); setFieldsValue(entity.value); }
formVerify.value.init(); });
/** 获取树对象 */ function getTree() { const tree = unref(treeRef); if (!tree) { throw new Error('tree is null!'); } return tree; }
/** 初始化树，展开第1级。默认选中并返回第一个根节点id */ async function initTree(selectedKeys?: (number | string)[]) { // 获取树的嵌套数据 treeData.value = await getTreeData(); if (treeData.value) { // setTimeout(() =&gt; { // getTree().filterByLevel(1); // }, 500); nextTick(() =&gt; { getTree().filterByLevel(1); });
// 设置默认选中的节点 if (!selectedKeys) { selectedKeys = []; selectedKeys.push(treeData.value[0].key); } getTree().setSelectedKeys(selectedKeys); }
return selectedKeys; }
/** 获取tree组件嵌套结构的数据 */ async function getTreeData() { let list = (await getTreeList()).items; let roots = orderBy( list.filter((x) =&gt; x.parentId == null), ['sort'], ['asc'], );
let result: any[] = []; for (let i = 0; i < roots.length; i++) { result[i] = { title: roots[i].title, key: roots[i].id, // disabled: roots[i].type == 0, icon: roots[i].type == 0 ? 'ant-design:cloud-upload-outlined' : '', style: roots[i].isStop == true ? 'color: #0960bd;' : '', extends: roots[i], }; if (list.filter((x) =&gt; x.parentId == roots[i].id)) { buildTreeNodeChildren(result[i], list); } }
return result; }
/** 递归tree节点的子数据 */ function buildTreeNodeChildren(node, list) { let children = orderBy( list.filter((x) =&gt; x.parentId == node.key), ['sort'], ['asc'], ); if (children &amp;&amp; children.length &gt; 0) { node.children = []; for (let i = 0; i < children.length; i++) { node.children[i] = { title: children[i].title, key: children[i].id, // disabled: children[i].type == 0, icon: children[i].type == 0 ? 'ant-design:cloud-upload-outlined' : '', style: children[i].type == 0 ? 'color: #0960bd;' : '', extends: children[i], }; buildTreeNodeChildren(node.children[i], list); } } else { return; } }
/** 表单保存提交 */ async function submit() { try { const [values] = await Promise.all([validate()]); Object.assign(entity.value, values);
if (params.value.type == 'add') { create(entity.value).then((res) =&gt; { createMessage.success('新增成功'); // tree增加节点 let ext: any = {}; Object.assign(ext, res); ext.canUpdate = true; ext.canDelete = true; ext.type = 1; ext.title = res.displayName; getTree().insertNodeByKey({ parentKey: res.parentId, node: { key: res.id, title: res.displayName, extends: ext, }, push: 'push', // 往后插入。unshift往前插入 });
// 展开并选中节点 getTree().setExpandedKeys(res.expandedIds); getTree().setSelectedKeys([res.id]); params.value.type = 'info'; }); } else if (params.value.type == 'update') { update(entity.value).then(() =&gt; { createMessage.success('保存成功');
let ext: any = {}; ext = entity.value; //Object.assign(ext, entity.value); ext.canUpdate = true; ext.canDelete = true; ext.title = entity.value.name; const nodeKey: any = entity.value.id; getTree().updateNodeByKey(nodeKey, { title: entity.value.name, extends: ext, }); params.value.type = 'info'; }); } } catch (error: any) { if (error &amp;&amp; error.errorFields) { // let errStr = ''; // error.errorFields.forEach((element) =&gt; { // errStr += element.errors[0] + '<br/&gt;'; // }); // createErrorModal({ title: '验证错误', content: errStr }); } } }
/** 表单取消 */ async function cancel() { params.value.type = 'info'; setFieldsValue({ ...entity_beforeModify.value }); }</script&gt;




该邮件从移动设备发送


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vbenjs/vue-vben-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月27日(星期三) 下午3:07
***@***.***&gt;;
抄送:&nbsp;"㎜　　安然失笑 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [vbenjs/vue-vben-admin] basictree删除根节点后报错 (Issue #3073)





 
@sunkunGitHub  提供下复现代码

**Comment by wangjue666** [comment]
@sunkunGitHub  我滴大哥，用markdown语法包一下 字符都转义了

**Comment by sunkunGitHub** [comment]
<template> <div> <PageWrapper contentClass="flex" dense contentFullHeight fixedHeight> <BasicTree ref="treeRef" toolbar search class="w-1/4 xl:w-1/5" :treeData="treeData" :actionList="actionList" :showIcon="true" @select="onSelect" draggable @dragstart="onDragStart" @dragenter="onDragEnter" @drop="onDrop" /> <FormVerify ref="formVerify" :entity="entity" :type="params.type" :privilege="false" :page="'ex-tree/operation'" :pageChildren="[]" @load-rule="callBackRule" dense contentFullHeight fixedHeight contentClass="flex" class="w-3/4 xl:w-4/5 pl-1" :contentStyle="{ 'background-color': 'white', padding: '20px 20px 0px 20px', }" > <template #headerContent> <a-button type="primary" class="mr-2" @click="submit" v-if="params.type != 'info'"> 保存 </a-button> <a-button type="primary" class="mr-2" @click="cancel" v-if="params.type != 'info'"> 取消 </a-button> </template> <BasicForm @register="register" :disabled="params.type == 'info'" style="width: 100%" /> </FormVerify> </PageWrapper> </div></template>
<script lang="ts"> import { defineComponent, ref, unref, nextTick, h, onMounted, createVNode } from 'vue'; import { PageWrapper } from '/@/components/Page'; import { FormVerify } from '/@/components/FormVerify'; import { BasicTree, TreeActionType, TreeActionItem, TreeItem, TreeNodeMoveType, } from '/@/components/Tree/index'; import { usePermission } from '/@/hooks/web/usePermission'; import { PlusOutlined, EditOutlined, DeleteOutlined, ExclamationCircleOutlined, } from '@ant-design/icons-vue'; import { AntTreeNodeDragEnterEvent, AntTreeNodeDropEvent } from 'ant-design-vue/es/tree'; import { BasicForm, useForm } from '/@/components/Form'; import { buildUUID } from '/@/utils/uuid'; import { get, getTreeList, move, deleteById, create, update } from '/@/api/demo/ex-tree/ex-tree'; import { orderBy } from 'lodash-es'; import { Modal } from 'ant-design-vue'; import { useMessage } from '/@/hooks/web/useMessage'; import { ExTree } from '/@/api/demo/ex-tree/model/extreeModel';
export default defineComponent({ name: 'ExTree', });</script>
<script lang="ts" setup> const { createMessage } = useMessage(); const params = ref({ type: 'info', }); const entity = ref<ExTree>({ id: buildUUID() }); const entity_beforeModify = ref<ExTree>({}); const formVerify = ref<any>(); const formVerifyRule = ref<any>(); const treeRef = ref<Nullable<TreeActionType>>(null); const treeData = ref<TreeItem[]>([]); const { hasPermission } = usePermission(); const formSchema = ref<any>([]); const expandedKeys = ref<any>(); console.log('document: ', document.body.clientHeight);
const actionList: TreeActionItem[] = [ { show: () => { return hasPermission('ex-tree.add'); }, // 新增节点 render: (node) => { return h(PlusOutlined, { title: '新增', onClick: (event) => { // 处理节点select逻辑 getTree().setSelectedKeys([node.key]); event.stopPropagation();
get({ id: node.key }).then((res) => { entity_beforeModify.value = { ...res }; });
params.value.type = 'add'; entity.value = new ExTree(); entity.value.parentId = node.key;
setFieldsValue(entity.value); }, }); }, }, { // 修改节点 show: (record) => { return record.extends.canUpdate && hasPermission('ex-tree.update'); }, render: (node) => { return h(EditOutlined, { title: '修改', onClick: async (event) => { // 处理节点select逻辑 getTree().setSelectedKeys([node.key]); event.stopPropagation();
params.value.type = 'update'; entity.value = await get({ id: node.key }); entity_beforeModify.value = { ...entity.value }; setFieldsValue(entity.value); }, }); }, }, { // 删除节点 show: (record) => { return hasPermission('ex-tree.delete'); }, render: (node) => { return h(DeleteOutlined, { title: '删除', onClick: (event) => { // 处理节点select逻辑 getTree().setSelectedKeys([node.key]); event.stopPropagation(); const searchValue = getTree().getSearchValue(); Modal.confirm({ title: () => `确认删除该节点吗？`, icon: () => createVNode(ExclamationCircleOutlined), content: () => '该节点及其所有子节点数据将一同被删除。', okText: () => '确定', okType: 'danger', cancelText: () => '取消', onOk() { deleteById({ id: node.key }).then(() => { createMessage.success('删除成功');
getTree().deleteNodeByKey(node.key);
getTree().setSearchValue(searchValue); }); }, }); }, }); }, }, ];
/** 树节点点击选择事件方法 */ async function onSelect(selectedKeys, e) { params.value.type = 'info'; if (e.selected) { entity.value = await get({ id: selectedKeys[0] }); } else { entity.value = new ExTree(); } setFieldsValue(entity.value); }
function onDragStart(info) { console.log(info); }
function onDragEnter(info: AntTreeNodeDragEnterEvent) { expandedKeys.value = info.expandedKeys; }
function onDrop(info: AntTreeNodeDropEvent) { let sourceId = info.dragNode.key; let sourceTitle = info.dragNode.extends.title; let targetId = info.node.key; let targetTitle = info.node.extends.title; let moveType: TreeNodeMoveType | undefined = undefined; let moveTypeStr = '';
let dropPosition = info.dropPosition; let dropToGap = info.dropToGap; /* 目标节点内部 dropPosition=目标节点dropPosition,dropToGap=false 目标节点之前 dropPosition=-1,dropToGap=true 目标节点之后 dropPosition=目标节点dropPosition+1,dropToGap=true */ if (dropToGap == false) { moveType = TreeNodeMoveType.Inner; moveTypeStr = `内部`; } else if (dropPosition == -1 && dropToGap == true) { moveType = TreeNodeMoveType.Before; moveTypeStr = `之前`; } else if (dropPosition > 0 && dropToGap == true) { moveType = TreeNodeMoveType.After; moveTypeStr = `之后`; }
if (moveType === undefined) { Modal.error({ title: '节点移动错误', content: `未明确节点的移动目标位置`, }); } else { Modal.confirm({ title: () => `确认移动“${sourceTitle}”吗？`, icon: () => createVNode(ExclamationCircleOutlined), content: () => `将该节点移动到“${targetTitle}”${moveTypeStr}`, okText: () => '确定', okType: 'danger', cancelText: () => '取消', onOk() { move({ id: sourceId, targetId: targetId, moveType: moveType }).then(async () => { createMessage.success('操作成功');
await initTree([sourceId]); nextTick(() => { expandedKeys.value.push(targetId); getTree().setExpandedKeys(expandedKeys.value); });
entity.value = await get({ id: sourceId }); setFieldsValue(entity.value); }); }, }); } }
// 表单对象 const [register, { setFieldsValue, updateSchema, validate }] = useForm({ labelWidth: 120, baseColProps: { span: 8 }, layout: 'vertical', wrapperCol: { style: 'margin:0px 15px 0px 0px' }, showActionButtonGroup: false, schemas: formSchema, });
async function callBackRule(rule: any) { formVerifyRule.value = rule; formSchema.value = [ { field: 'treeCode', component: 'Input', label: '节点编码', componentProps: { readonly: true, placeholder: '自动生成', }, }, { field: 'code', component: 'Input', label: '业务编码', defaultValue: 0, componentProps: { disabled: formVerifyRule.value['code'].disabled, }, rules: formVerifyRule.value['code'].rules, show: !formVerifyRule.value['code'].invisible, }, { field: 'name', component: 'Input', label: '业务名称', componentProps: { disabled: formVerifyRule.value['name'].disabled, }, rules: formVerifyRule.value['name'].rules, show: !formVerifyRule.value['name'].invisible, }, { field: 'isActive', component: 'Checkbox', label: '是否启用', componentProps: { disabled: formVerifyRule.value['isActive'].disabled, }, rules: formVerifyRule.value['isActive'].rules, show: !formVerifyRule.value['isActive'].invisible, }, ]; updateSchema(formSchema.value); }
onMounted(async () => { let key = await initTree(); if (key) { // 加载节点的详细数据 entity.value = await get({ id: key[0] }); setFieldsValue(entity.value); }
formVerify.value.init(); });
/** 获取树对象 */ function getTree() { const tree = unref(treeRef); if (!tree) { throw new Error('tree is null!'); } return tree; }
/** 初始化树，展开第1级。默认选中并返回第一个根节点id */ async function initTree(selectedKeys?: (number | string)[]) { // 获取树的嵌套数据 treeData.value = await getTreeData(); if (treeData.value) { // setTimeout(() => { // getTree().filterByLevel(1); // }, 500); nextTick(() => { getTree().filterByLevel(1); });
// 设置默认选中的节点 if (!selectedKeys) { selectedKeys = []; selectedKeys.push(treeData.value[0].key); } getTree().setSelectedKeys(selectedKeys); }
return selectedKeys; }
/** 获取tree组件嵌套结构的数据 */ async function getTreeData() { let list = (await getTreeList()).items; let roots = orderBy( list.filter((x) => x.parentId == null), ['sort'], ['asc'], );
let result: any[] = []; for (let i = 0; i < roots.length; i++) { result[i] = { title: roots[i].title, key: roots[i].id, // disabled: roots[i].type == 0, icon: roots[i].type == 0 ? 'ant-design:cloud-upload-outlined' : '', style: roots[i].isStop == true ? 'color: #0960bd;' : '', extends: roots[i], }; if (list.filter((x) => x.parentId == roots[i].id)) { buildTreeNodeChildren(result[i], list); } }
return result; }
/** 递归tree节点的子数据 */ function buildTreeNodeChildren(node, list) { let children = orderBy( list.filter((x) => x.parentId == node.key), ['sort'], ['asc'], ); if (children && children.length > 0) { node.children = []; for (let i = 0; i < children.length; i++) { node.children[i] = { title: children[i].title, key: children[i].id, // disabled: children[i].type == 0, icon: children[i].type == 0 ? 'ant-design:cloud-upload-outlined' : '', style: children[i].type == 0 ? 'color: #0960bd;' : '', extends: children[i], }; buildTreeNodeChildren(node.children[i], list); } } else { return; } }
/** 表单保存提交 */ async function submit() { try { const [values] = await Promise.all([validate()]); Object.assign(entity.value, values);
if (params.value.type == 'add') { create(entity.value).then((res) => { createMessage.success('新增成功'); // tree增加节点 let ext: any = {}; Object.assign(ext, res); ext.canUpdate = true; ext.canDelete = true; ext.type = 1; ext.title = res.displayName; getTree().insertNodeByKey({ parentKey: res.parentId, node: { key: res.id, title: res.displayName, extends: ext, }, push: 'push', // 往后插入。unshift往前插入 });
// 展开并选中节点 getTree().setExpandedKeys(res.expandedIds); getTree().setSelectedKeys([res.id]); params.value.type = 'info'; }); } else if (params.value.type == 'update') { update(entity.value).then(() => { createMessage.success('保存成功');
let ext: any = {}; ext = entity.value; //Object.assign(ext, entity.value); ext.canUpdate = true; ext.canDelete = true; ext.title = entity.value.name; const nodeKey: any = entity.value.id; getTree().updateNodeByKey(nodeKey, { title: entity.value.name, extends: ext, }); params.value.type = 'info'; }); } } catch (error: any) { if (error && error.errorFields) { // let errStr = ''; // error.errorFields.forEach((element) => { // errStr += element.errors[0] + '<br/>'; // }); // createErrorModal({ title: '验证错误', content: errStr }); } } }
/** 表单取消 */ async function cancel() { params.value.type = 'info'; setFieldsValue({ ...entity_beforeModify.value }); }</script>

**Comment by anncwb** [comment]
Hello @sunkunGitHub. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.
