### ISSUE TITLE
引入 renovate 或 dependabot 这样的bot来管理package.json的依赖更新

### ISSUE THREAD

**Issue by wangjue666** [vbenjs/vue-vben-admin#3074]
[dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates) 

[renovate](https://github.com/apps/renovate)

Dependabot和Renovate都是用于自动化管理GitHub仓库的依赖更新的工具，Renovate配置方式更灵活一些，[vue3项目](https://github.com/vuejs/core/graphs/contributors)是两者都引入了

**Comment by likui628** [comment]
vuejs/core现在用的是dependabot，renovate最新的提交记录是Sep 21, 2023

**Comment by likui628** [comment]
@jinmao88

**Comment by jinmao88** [comment]
vben2的依赖更新还是手动吧 不需要一直跟新

**Comment by wangjue666** [comment]
ok

> vben2的依赖更新还是手动吧 不需要一直跟新
