### ISSUE TITLE
则无法命名 "default" 的推断类型

### ISSUE THREAD

**Issue by loveLan18913** [vbenjs/vue-vben-admin#3076]
![image](https://github.com/vbenjs/vue-vben-admin/assets/57902256/1263a053-d7cc-49d8-9e73-46b8089ff452)
![image](https://github.com/vbenjs/vue-vben-admin/assets/57902256/e0e60088-3722-4cff-99ba-64622a33a943)

如果没有引用 ".pnpm/csstype@3.1.2/node_modules/csstype"，则无法命名 "default" 的推断类型。这很可能不可移植。需要类型注释。ts(2742)

请问这个咋解决

**Comment by anncwb** [comment]
Hello @loveLan18913. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by sky124380729** [comment]
> ![image](https://private-user-images.githubusercontent.com/57902256/270607829-1263a053-d7cc-49d8-9e73-46b8089ff452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzMwNjYsIm5iZiI6MTcwMjYzMjc2NiwicGF0aCI6Ii81NzkwMjI1Ni8yNzA2MDc4MjktMTI2M2EwNTMtZDdjYy00OWQ4LTllNzMtNDZiODA4OWZmNDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA5MzI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NjdjYjkxNDJmOGQxY2RjZDczODcyNWY3MjVkYzcwZDU1ZjQ4MGE4ZTVmNDFmOWUxYmUyZGQ1NWRhMjk5NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kUGjrtwmDuMzPzbj4cV2TjUbEbUBmBHrUsIejuMj4MM) ![image](https://private-user-images.githubusercontent.com/57902256/270607890-e0e60088-3722-4cff-99ba-64622a33a943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzMwNjYsIm5iZiI6MTcwMjYzMjc2NiwicGF0aCI6Ii81NzkwMjI1Ni8yNzA2MDc4OTAtZTBlNjAwODgtMzcyMi00Y2ZmLTk5YmEtNjQ2MjJhMzNhOTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA5MzI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZTY2NWE3NzdiOTcxY2E0YzBjZTY3M2EyMjg3YjcyOWM4ODhhN2I0ZTk3NTg0YzRiZGY3ZDc1YzE2Y2EzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zB6cpFKB3Pk5NbuzibOlfuoW2VSdvWTGBhXby1hw0WE)
> 
> 如果没有引用 ".pnpm/csstype@3.1.2/node_modules/csstype"，则无法命名 "default" 的推断类型。这很可能不可移植。需要类型注释。ts(2742)
> 
> 请问这个咋解决

![image](https://github.com/vbenjs/vue-vben-admin/assets/23203328/84c06a8f-0525-4961-9c2f-910fca09372c)
修改编译器ts的接管模式

**Comment by lyk990** [comment]
> > ![image](https://private-user-images.githubusercontent.com/57902256/270607829-1263a053-d7cc-49d8-9e73-46b8089ff452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzMwNjYsIm5iZiI6MTcwMjYzMjc2NiwicGF0aCI6Ii81NzkwMjI1Ni8yNzA2MDc4MjktMTI2M2EwNTMtZDdjYy00OWQ4LTllNzMtNDZiODA4OWZmNDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA5MzI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NjdjYjkxNDJmOGQxY2RjZDczODcyNWY3MjVkYzcwZDU1ZjQ4MGE4ZTVmNDFmOWUxYmUyZGQ1NWRhMjk5NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kUGjrtwmDuMzPzbj4cV2TjUbEbUBmBHrUsIejuMj4MM) ![image](https://private-user-images.githubusercontent.com/57902256/270607890-e0e60088-3722-4cff-99ba-64622a33a943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzMwNjYsIm5iZiI6MTcwMjYzMjc2NiwicGF0aCI6Ii81NzkwMjI1Ni8yNzA2MDc4OTAtZTBlNjAwODgtMzcyMi00Y2ZmLTk5YmEtNjQ2MjJhMzNhOTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA5MzI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZTY2NWE3NzdiOTcxY2E0YzBjZTY3M2EyMjg3YjcyOWM4ODhhN2I0ZTk3NTg0YzRiZGY3ZDc1YzE2Y2EzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zB6cpFKB3Pk5NbuzibOlfuoW2VSdvWTGBhXby1hw0WE)
> > 如果没有引用 ".pnpm/csstype@3.1.2/node_modules/csstype"，则无法命名 "default" 的推断类型。这很可能不可移植。需要类型注释。ts(2742)
> > 请问这个咋解决
> 
> ![image](https://private-user-images.githubusercontent.com/23203328/290784974-84c06a8f-0525-4961-9c2f-910fca09372c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2Mzc3MzMsIm5iZiI6MTcwMjYzNzQzMywicGF0aCI6Ii8yMzIwMzMyOC8yOTA3ODQ5NzQtODRjMDZhOGYtMDUyNS00OTYxLTljMmYtOTEwZmNhMDkzNzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDEwNTAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZTk4MTJmMjUxZjkzMGNmYTVmNGU1YmUwMDlhODkwZTM5ODUyMjA1NDdjOTE1NGJiOWNlMzU1NWM5NGFiYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NmaFuc9PnnSikKc35M3vz2vhLm0D_pSgEE44vUjComQ) 修改编译器ts的接管模式

图片看不到，能重新上传下吗，我也遇到了这个问题，麻烦了哈

**Comment by sky124380729** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/57902256/270607829-1263a053-d7cc-49d8-9e73-46b8089ff452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzMwNjYsIm5iZiI6MTcwMjYzMjc2NiwicGF0aCI6Ii81NzkwMjI1Ni8yNzA2MDc4MjktMTI2M2EwNTMtZDdjYy00OWQ4LTllNzMtNDZiODA4OWZmNDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA5MzI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NjdjYjkxNDJmOGQxY2RjZDczODcyNWY3MjVkYzcwZDU1ZjQ4MGE4ZTVmNDFmOWUxYmUyZGQ1NWRhMjk5NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kUGjrtwmDuMzPzbj4cV2TjUbEbUBmBHrUsIejuMj4MM) ![image](https://private-user-images.githubusercontent.com/57902256/270607890-e0e60088-3722-4cff-99ba-64622a33a943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzMwNjYsIm5iZiI6MTcwMjYzMjc2NiwicGF0aCI6Ii81NzkwMjI1Ni8yNzA2MDc4OTAtZTBlNjAwODgtMzcyMi00Y2ZmLTk5YmEtNjQ2MjJhMzNhOTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA5MzI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZTY2NWE3NzdiOTcxY2E0YzBjZTY3M2EyMjg3YjcyOWM4ODhhN2I0ZTk3NTg0YzRiZGY3ZDc1YzE2Y2EzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zB6cpFKB3Pk5NbuzibOlfuoW2VSdvWTGBhXby1hw0WE)
> > > 如果没有引用 ".pnpm/csstype@3.1.2/node_modules/csstype"，则无法命名 "default" 的推断类型。这很可能不可移植。需要类型注释。ts(2742)
> > > 请问这个咋解决
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/23203328/290784974-84c06a8f-0525-4961-9c2f-910fca09372c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2Mzc3MzMsIm5iZiI6MTcwMjYzNzQzMywicGF0aCI6Ii8yMzIwMzMyOC8yOTA3ODQ5NzQtODRjMDZhOGYtMDUyNS00OTYxLTljMmYtOTEwZmNhMDkzNzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDEwNTAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZTk4MTJmMjUxZjkzMGNmYTVmNGU1YmUwMDlhODkwZTM5ODUyMjA1NDdjOTE1NGJiOWNlMzU1NWM5NGFiYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NmaFuc9PnnSikKc35M3vz2vhLm0D_pSgEE44vUjComQ) 修改编译器ts的接管模式
> 
> 图片看不到，能重新上传下吗，我也遇到了这个问题，麻烦了哈

![image](https://github.com/vbenjs/vue-vben-admin/assets/23203328/e394b886-2df2-4b09-bcd5-4a4291737c70)
能看到了吗，就是编译器最底下有个takeover，切换一下就行

**Comment by lyk990** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/57902256/270607829-1263a053-d7cc-49d8-9e73-46b8089ff452.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzMwNjYsIm5iZiI6MTcwMjYzMjc2NiwicGF0aCI6Ii81NzkwMjI1Ni8yNzA2MDc4MjktMTI2M2EwNTMtZDdjYy00OWQ4LTllNzMtNDZiODA4OWZmNDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA5MzI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NjdjYjkxNDJmOGQxY2RjZDczODcyNWY3MjVkYzcwZDU1ZjQ4MGE4ZTVmNDFmOWUxYmUyZGQ1NWRhMjk5NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kUGjrtwmDuMzPzbj4cV2TjUbEbUBmBHrUsIejuMj4MM) ![image](https://private-user-images.githubusercontent.com/57902256/270607890-e0e60088-3722-4cff-99ba-64622a33a943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzMwNjYsIm5iZiI6MTcwMjYzMjc2NiwicGF0aCI6Ii81NzkwMjI1Ni8yNzA2MDc4OTAtZTBlNjAwODgtMzcyMi00Y2ZmLTk5YmEtNjQ2MjJhMzNhOTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA5MzI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZTY2NWE3NzdiOTcxY2E0YzBjZTY3M2EyMjg3YjcyOWM4ODhhN2I0ZTk3NTg0YzRiZGY3ZDc1YzE2Y2EzZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zB6cpFKB3Pk5NbuzibOlfuoW2VSdvWTGBhXby1hw0WE)
> > > > 如果没有引用 ".pnpm/csstype@3.1.2/node_modules/csstype"，则无法命名 "default" 的推断类型。这很可能不可移植。需要类型注释。ts(2742)
> > > > 请问这个咋解决
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/23203328/290784974-84c06a8f-0525-4961-9c2f-910fca09372c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2Mzc3MzMsIm5iZiI6MTcwMjYzNzQzMywicGF0aCI6Ii8yMzIwMzMyOC8yOTA3ODQ5NzQtODRjMDZhOGYtMDUyNS00OTYxLTljMmYtOTEwZmNhMDkzNzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDEwNTAzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZTk4MTJmMjUxZjkzMGNmYTVmNGU1YmUwMDlhODkwZTM5ODUyMjA1NDdjOTE1NGJiOWNlMzU1NWM5NGFiYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NmaFuc9PnnSikKc35M3vz2vhLm0D_pSgEE44vUjComQ) 修改编译器ts的接管模式
> > 
> > 
> > 图片看不到，能重新上传下吗，我也遇到了这个问题，麻烦了哈
> 
> ![image](https://private-user-images.githubusercontent.com/23203328/291118848-e394b886-2df2-4b09-bcd5-4a4291737c70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NjE4ODQsIm5iZiI6MTcwMjg2MTU4NCwicGF0aCI6Ii8yMzIwMzMyOC8yOTExMTg4NDgtZTM5NGI4ODYtMmRmMi00YjA5LWJjZDUtNGE0MjkxNzM3YzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDAxMDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzMDQ0ZjhmYmZlNjQ5YjA1ZWNiMjk1MzIzNzE0ODdkOGMxY2I1YzVhM2M3NWYxOTkxNzIyYTgzY2UyMDFiMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hcE2YQ0nC_WaPyaR62e90ySQBnWRa_O89OMeXYvgFJo) 能看到了吗，就是编译器最底下有个takeover，切换一下就行

看到了  感谢哈
