### ISSUE TITLE
最新代码 ApiTransfer编辑后无法正常显示数据

### ISSUE THREAD

**Issue by 1455668754** [vbenjs/vue-vben-admin#3077]
![1695780822782](https://github.com/vbenjs/vue-vben-admin/assets/88491446/bfe93cfb-7c18-4131-8257-5a9653ccbe5e)

编辑后
再次打开时 显示的依旧是原来的内容，未正常进行刷新

**Comment by DesignHhuang** [comment]
@1455668754 这是你自己的系统么?自己的系统中应该自己控制数据的存储和展示吧？有没有更详细的问题描述。

**Comment by 1455668754** [comment]
@DesignHhuang 不是业务性问题，是框架中的ApiTransfer对应的Form放在Modal中，只有第一次Modal加载时，能正常初始化ApiTransfer中的数据，之后无法用setFieldsValue方式更新ApiTransfer选中值。
测试完，只有每次都销毁Modal，才能正常更新ApiTransfer初始化数据，应该是这个组件内部代码问题
![1695798330858](https://github.com/vbenjs/vue-vben-admin/assets/88491446/28bcf882-0f32-409a-b9e4-7f5baf0a9783)

**Comment by DesignHhuang** [comment]
看一下这个 PR 能不能解决你的问题

**Comment by likui628** [comment]
@1455668754 方便的话把这个modal里的代码示例贴出来
