### ISSUE TITLE
mac用edge浏览器时，只显示英文（中英切换都是显示英文），windows正常

### ISSUE THREAD

**Issue by 1455668754** [vbenjs/vue-vben-admin#3079]
![7a49de588ab5978a7cbe529df3d4afe](https://github.com/vbenjs/vue-vben-admin/assets/88491446/efebd896-c5d9-448c-ae33-afde22f68ca5)
mac用edge浏览器时，只显示英文（中英切换都是显示英文），windows正常

**Comment by wangjue666** [comment]
按下f12看下 看着是i18n没有配置上

**Comment by 1455668754** [comment]
![1695799237523](https://github.com/vbenjs/vue-vben-admin/assets/88491446/c94b8dab-09f7-4e8f-b189-431538027e21)
@wangjue666 请问是看哪里呢

**Comment by wangjue666** [comment]
@1455668754  用chrome查看是否显示正常

**Comment by 1455668754** [comment]
@wangjue666 都一样，换了好几个浏览器，都是这样，且chrome啥的都更新成了最新版本试，也一样

**Comment by wangjue666** [comment]
打开[vben.vvbin.cn/](https://vben.vvbin.cn/) 也是如此吗

**Comment by 1455668754** [comment]
@wangjue666 打开线上的显示正常，但是直接拉仓库代码启动，3就有这个中英问题
![1695807497792](https://github.com/vbenjs/vue-vben-admin/assets/88491446/0f561c18-7657-4c13-9309-0c8c64fc9aa9)

**Comment by wangjue666** [comment]
本地没有禁用js吧？

**Comment by 1455668754** [comment]
@wangjue666 禁用js?

**Comment by likui628** [comment]
看下控制台有没有打印log

**Comment by lixiaolong117** [comment]
我逐个测试了一下，2.10.0这个版本和之前的版本是正常的，2.10.1这个版本就成英文了，哪位大佬给分析一下

**Comment by wangjue666** [comment]
@lixiaolong117  怎么复现的？

**Comment by wangjue666** [comment]
@lixiaolong117  是英文还是i18n的那种字符？

**Comment by lixiaolong117** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/e2e1d650-ea48-4adc-a821-f8edc5754dd9)

**Comment by lixiaolong117** [comment]
就是这样的英文

**Comment by lixiaolong117** [comment]
> @lixiaolong117 怎么复现的？

就我的mac电脑这个样子，其他电脑好像没事

**Comment by lixiaolong117** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/82850dd1-74f9-4dc5-bd7e-82905abdd0b8)
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/3f194ca3-78a6-40d6-8928-8b2402947510)
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/e73ebed6-ad59-4859-9d48-1d4ae1a6fa0b)

**Comment by wangjue666** [comment]
你试着清除下浏览器缓存看看， 也是跟上面那个同学反馈问题的一致吗 在线上运行没问题 线下开发这样？

**Comment by lixiaolong117** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/73988e17-1d04-4130-9765-a5e63893008c)
是一个问题，上面说的方法都尝试了，都没有解决；2.10.0这个版本和之前的版本是正常的，2.10.1版本就不正常了，知道最新版的跟之前的版本有什么区别吗？可能是哪里的区别导致的这个问题呢？@wangjue666

**Comment by wangjue666** [comment]
@lixiaolong117  2.10.0很混乱 近一年都接受commit但没有更新版本

**Comment by likui628** [comment]
https://github.com/vbenjs/vue-vben-admin/compare/v2.10.0...2.10.1
对比变更意义不大，debugger看下

**Comment by wangjue666** [comment]
但是最近并没有变更i18n相关的代码

**Comment by lixiaolong117** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/7502e818-60a3-49fc-bd79-465058f1f5f8)
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/b2f2b0ec-5342-4e80-a641-6513bc904dbe)
本地起来点登录
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/26943315-3be5-495b-b21f-96f0ef3d12fa)
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/763e3a60-5ab9-473d-92c6-b3fe24cda4b3)
也没有报错 @likui628 ，debugger具体怎么操作呢？我小白一个，不会写代码

**Comment by lixiaolong117** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/6c399b0d-52f7-4bde-81c7-0a4d6a0925fd)
谁懂这里呢？这里的意思是不是我的依赖都不是新下载的，都是加载的之前下载的，那有没有可能我之前下载的版本跟现在的不匹配呢？怎么能删掉之前下载的重新下载呢？我尝试删掉项目中的node_modules文件夹，没有用，有没有懂这个的，分析一下，是不是这个原因呢？

**Comment by wangjue666** [comment]
@lixiaolong117  别用pnpm安装了 试试yarn或者npm

**Comment by lixiaolong117** [comment]
我试一下

**Comment by lixiaolong117** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/beff1542-a6c2-4911-92fd-208a3fb820dd)
是命令错了吗？还是需要改代码呢？ @wangjue666

**Comment by wangjue666** [comment]
@lixiaolong117  不是，是npm不支持这样解析包，你继续用pnpm 你暂时把代码回滚到 [dbdd811](https://github.com/vbenjs/vue-vben-admin/commit/dbdd811705b76cd9814afb65e640392e36c9dcce) 看看显示是否正常

**Comment by wangjue666** [comment]
或者你再拿手机访问下 开发网址就是 192.168那个地址 看显示

**Comment by lixiaolong117** [comment]
> 或者你再拿手机访问下 开发网址就是 192.168那个地址 看显示

手机试过，用其他电脑也试过，手机的话一直转，不显示登录页面，用其他电脑的话还是英文

**Comment by wangjue666** [comment]
@lixiaolong117  你看下f12有没有什么报错提示

**Comment by wangjue666** [comment]
再往前回滚， 顺带再看下网络那列

**Comment by lixiaolong117** [comment]
> 再往前回滚， 顺带再看下网络那列

![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/bff88690-41d2-4e56-a598-103ed9a3b984)
[dbdd811]这个版本的网络

**Comment by wangjue666** [comment]
再回滚一下 重新下载下antdv3依赖

**Comment by lixiaolong117** [comment]
重新下载下antdv3依赖

> 再回滚一下 重新下载下antdv3依赖

这个怎么重新下载啊？是吧项目中这个文件夹node_modules删掉吗？

**Comment by wangjue666** [comment]
回滚后 删除node_modules 再下载

**Comment by lixiaolong117** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/db3ae2ef-ae55-499c-8017-63962367042d)
从这个开始出现的英文
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/467b3c76-b081-4b94-bf97-21759a8b45ac)
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/80232f56-a2ee-41f6-a9d5-bc7f9f874408)
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/ec92eddf-5851-45b0-9f4b-de1ec7b747d5)
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/e5477e8a-b150-4f29-af9b-4f808fdc149e)
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/aa16494a-ae67-4c8c-9d68-711357438b45)
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/bb6a50a9-0e57-4cd3-b58d-b6b5cd8bfccf)
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/2b8bccee-20e3-4990-8afc-85cbe7b768fb)

**Comment by lixiaolong117** [comment]
问题已经解决，启动命令错了，我用的还是vite，换成pnpm vite就可以了
