### ISSUE TITLE
版本2.10.1  Table表格位置错乱BUG，表头的列与数据行的列对不齐错乱问题！号称 vben 史上最强BUG王？

### ISSUE THREAD

**Issue by zusrsoft** [vbenjs/vue-vben-admin#3085]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [是] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [是 ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [是] 已在 Issues 中搜索了相关的关键词
- [是 ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
组件/Table 这个组件下的table 多种类型都有同样的bug
Table表格位置错乱BUG，表头的列与数据行的列对不齐错乱问题！
![image](https://github.com/vbenjs/vue-vben-admin/assets/26666544/31be9dc1-d105-437c-8aa2-8c8e33edf671)

 

### 复现 Bug
组件/Table  这个组件下的table 多种类型都有同样的bug, 只要字段table 稍多一点，比如十多个字段，超过一屏，需要向右划动滚动条，就非常明显的出现 “表头的列与数据行的列对不齐错乱问题！” **这个问题好像是一个解决不了的 vben BUG 王， 二年前就有数十条Issue,现在发布的2.10.1版本，还是这个问题没解决**，这可是前端Table  基础中基础了，如此错乱问题，是非常不友好的。如何能使用呢？

官方自己发布的演示环境示例，例如： https://vben.vvbin.cn/#/comp/table/authColumn

## 系统信息

官方自己发布的演示环境 或 按官方版本要求的环境

**Comment by zusrsoft** [comment]
记得在 [2.7.0]版本时代没有这个bug

**Comment by wangjue666** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/29c07be4-60e7-408f-8045-641d89e4a7e3)

**Comment by wangjue666** [comment]
[antdv的问题哈](https://www.antdv.com/components/table-cn#components-table-demo-fixed-columns-header)

**Comment by wangjue666** [comment]
额2.10.1是我升的 主要是升级了antdv4，解决大家反馈问题不好定位版本， 这两天我一直在处理issues,也注意到之前的这些issues反馈的问题了，正在慢慢整理哈，现在常维护这个仓库的就三四个人， 需要一些时间来搞:)

**Comment by zusrsoft** [comment]
antdv已经告知了有可能出现字段列数量稍多时会对不齐，并且也把解决方案给出了，那vben是可以适配一下的哟，这也是为作为集成框架Vben的价值哟，适配一次，造福所有的vben粉丝   ：）  也能使框架越来越好~~~

**Comment by zusrsoft** [comment]
向常维护这个仓库的你们致敬~~~

**Comment by Jzow** [comment]
@zusrsoft 现在升级到antdv4 难眠会有些问题，适配是需要时间的，建议你可以先看一下antdv4的新文档

**Comment by zusrsoft** [comment]
OK~~

**Comment by wangjue666** [comment]
@zusrsoft  已解决 看下这个PR https://github.com/vbenjs/vue-vben-admin/pull/3087

**Comment by zusrsoft** [comment]
神速，给力，谢谢

**Comment by wangjue666** [comment]
@zusrsoft  不客气~ 有啥问题及时说就好

**Comment by zusrsoft** [comment]
感觉这个框架注入了新的力量了，有你们的加入，大伙都会活跃起来。之前这个框架是比较消极的。。

**Comment by zusrsoft** [comment]
可以发动一下社区的力量，搞些线上讨论会活动（参考阿里cloud社区），群策群力。

**Comment by wangjue666** [comment]
哈哈好滴， 也期待你的PR
