### ISSUE TITLE
pnpm clean:cache command not found

### ISSUE THREAD

**Issue by doraemonxxx** [vbenjs/vue-vben-admin#3086]
The *clean:cache* command is not found when I run the *pnpm build:no-cache*. 

Am I missing something?

Thank you!

**Comment by Jzow** [comment]
You can try manually clearing the cache. `rm -rf .pnpm-store`

I just fixed it. You can refer to and modify your own project `package.json` file.

**Comment by likui628** [comment]
https://github.com/orgs/pnpm/discussions/4413
