### ISSUE TITLE
在vue文件中添加<svg></svg>标签,从该页面切换到其他页面都无法正常显示

### ISSUE THREAD

**Issue by CJL6015** [vbenjs/vue-vben-admin#3093]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

例如在vue文件添加<template> <svg></svg> <Divider /></template>,当这个页面切换到别的页面时,所有页面都无法显示,但是如果是<template> <svg></svg> </template>是正常的,如果svg同级含有别的标签页就无法正常显示

### 复现 Bug

<template> <svg></svg> <Divider /></template>

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by anncwb** [comment]
Hello @CJL6015. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by Jzow** [comment]
@anncwb When will ApiTreeSelect be fixed? Opening the module will not request Api, and this PR has been merged without verification

**Comment by CJL6015** [comment]
[index.txt](https://github.com/vbenjs/vue-vben-admin/files/12840594/index.txt)
这是我完整的代码,当我从这个页面切换到别的页面后就无法正常显示

**Comment by wangjue666** [comment]
[4ac679ba-12c4-4184-a5eb-82470fdfe050.webm](https://github.com/vbenjs/vue-vben-admin/assets/24707417/fa850972-0319-459e-ba6f-105cfe360351)

@CJL6015  是你自己的业务代码问题
