### ISSUE TITLE
系统角色演示代码VSCode 代码检查不通过

### ISSUE THREAD

**Issue by phphy** [vbenjs/vue-vben-admin#3111]
### 描述 Bug

src/views/demo/system/role/role.data.ts
第31行：return h(Switch, {
Switch报如下

没有与此调用匹配的重载。
  最后一个重载给出了以下错误。
    类型“{ new (...args: any[]): { $: ComponentInternalInstance; $data: {}; $props: { disabled?: boolean | undefined; autofocus?: boolean | undefined; loading?: boolean | undefined; ... 28 more ...; readonly unCheckedChildren?: any; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T exten...”的参数不能赋给类型“DefineComponent<{ checked: boolean; checkedChildren: string; unCheckedChildren: string; loading: any; onChange(checked: boolean): void; }, {}, {}, ComputedOptions, MethodOptions, ... 7 more ..., {}>”的参数。
      不能将类型“{ new (...args: any[]): { $: ComponentInternalInstance; $data: {}; $props: { disabled?: boolean | undefined; autofocus?: boolean | undefined; loading?: boolean | undefined; ... 28 more ...; readonly unCheckedChildren?: any; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T exten...”分配给类型“DefineComponent<{ checked: boolean; checkedChildren: string; unCheckedChildren: string; loading: any; onChange(checked: boolean): void; }, {}, {}, ComputedOptions, MethodOptions, ... 7 more ..., {}>”。
        不能将类型“{ new (...args: any[]): { $: ComponentInternalInstance; $data: {}; $props: { disabled?: boolean | undefined; autofocus?: boolean | undefined; loading?: boolean | undefined; ... 28 more ...; readonly unCheckedChildren?: any; }; ... 10 more ...; $watch<T extends string | ((...args: any) => any)>(source: T, cb: T exten...”分配给类型“ComponentPublicInstanceConstructor<{ $: ComponentInternalInstance; $data: {}; $props: { loading?: any; style?: unknown; key?: string | number | symbol | undefined; class?: unknown; readonly checkedChildren: string; ... 11 more ...; onVnodeUnmounted?: VNodeMountHook | ... 1 more ... | undefined; }; ... 10 more ...; $...”。
          不能将类型“{ $: ComponentInternalInstance; $data: {}; $props: { disabled?: boolean | undefined; autofocus?: boolean | undefined; loading?: boolean | undefined; checkedValue?: string | ... 2 more ... | undefined; ... 27 more ...; readonly unCheckedChildren?: any; }; ... 10 more ...; $watch<T extends string | ((...args: any) => ...”分配给类型“{ $: ComponentInternalInstance; $data: {}; $props: { loading?: any; style?: unknown; key?: string | number | symbol | undefined; class?: unknown; readonly checkedChildren: string; ... 11 more ...; onVnodeUnmounted?: VNodeMountHook | ... 1 more ... | undefined; }; ... 10 more ...; $watch<T extends string | ((...args:...”。
            不能将类型“{ $: ComponentInternalInstance; $data: {}; $props: { disabled?: boolean | undefined; autofocus?: boolean | undefined; loading?: boolean | undefined; checkedValue?: string | ... 2 more ... | undefined; ... 27 more ...; readonly unCheckedChildren?: any; }; ... 10 more ...; $watch<T extends string | ((...args: any) => ...”分配给类型“{ $: ComponentInternalInstance; $data: {}; $props: { loading?: any; style?: unknown; key?: string | number | symbol | undefined; class?: unknown; readonly checkedChildren: string; ... 11 more ...; onVnodeUnmounted?: VNodeMountHook | ... 1 more ... | undefined; }; ... 10 more ...; $watch<T extends string | ((...args:...”。
              属性“$props”的类型不兼容。
                不能将类型“{ disabled?: boolean | undefined; autofocus?: boolean | undefined; loading?: boolean | undefined; checkedValue?: string | number | boolean | undefined; unCheckedValue?: string | number | boolean | undefined; ... 26 more ...; readonly unCheckedChildren?: any; }”分配给类型“{ loading?: any; style?: unknown; key?: string | number | symbol | undefined; class?: unknown; readonly checkedChildren: string; readonly unCheckedChildren: string; readonly checked: boolean; readonly onChange: (checked: boolean) => void; ... 8 more ...; onVnodeUnmounted?: VNodeMountHook | ... 1 more ... | undefined...”。
                  属性“checkedChildren”在类型“{ disabled?: boolean | undefined; autofocus?: boolean | undefined; loading?: boolean | undefined; checkedValue?: string | number | boolean | undefined; unCheckedValue?: string | number | boolean | undefined; ... 26 more ...; readonly unCheckedChildren?: any; }”中为可选，但在类型“{ loading?: any; style?: unknown; key?: string | number | symbol | undefined; class?: unknown; readonly checkedChildren: string; readonly unCheckedChildren: string; readonly checked: boolean; readonly onChange: (checked: boolean) => void; ... 8 more ...; onVnodeUnmounted?: VNodeMountHook | ... 1 more ... | undefined...”中为必选。ts(2769)
runtime-core.d.ts(1490, 25): 在此处声明最后一个重载。
(alias) const Switch: {
    new (...args: any[]): {
        $: import("vue").ComponentInternalInstance;
        $data: {};
        $props: {
            disabled?: boolean | undefined;
            autofocus?: boolean | undefined;
            loading?: boolean | undefined;
            checkedValue?: string | number | boolean | undefined;
            ... 27 more ...;
            readonly unCheckedChildren?: any;
        };
        ... 10 more ...;
        $watch<T extends string | ((...args: any) => any)>(source: T, cb: T extends (...args: any) => infer R ? (args_0: R, args_1: R) => any : (...args: any) => any, options?: import("vue").WatchOptions<boolean>): import("vue").WatchStopHandle;
    } & Readonly<...> & ShallowUnwrapRef<...> & ComponentCustomProperties;
    __isFragment?: undefined;
    __isTeleport?: undefined;
    __isSuspense?: undefined;
} & ... 4 more ... & Plugin<...>
import Switch

### 复现 Bug

打开vscode 就可以看到代码检查不通过的错误提示

## 系统信息

- 操作系统: Windows 11
- Node 版本: v18.17.0
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 8.8.0
- vscode版本： 1.83
- typescript版本: 5.2.2

**Comment by wangjue666** [comment]
https://github.com/vbenjs/vue-vben-admin/issues/2719 这些类型错误正在陆续处理哈

**Comment by phphy** [comment]
非常感谢
