### ISSUE TITLE
StrengthMeter 组件校验bug

### ISSUE THREAD

**Issue by gavin-james** [vbenjs/vue-vben-admin#3118]
三个组件的校验规则都是
```
{
        min: 6,
        max: 16,
        message: '密码长度不能小于6且超过16个字符',
}
```
其中StrengthMeter符合条件后，并没有移除错误提示

https://github.com/vbenjs/vue-vben-admin/assets/62117658/e06de1c4-e5be-41ad-93ea-c060d95ad530

**Comment by wangjue666** [comment]
@gavin-james  已修复，这个校验引发的原因具体可以看 https://github.com/vbenjs/vue-vben-admin/pull/3071
