### ISSUE TITLE
内置的CodeEditor希望能添加一个boarded的属性控制边框，这样在form中使用CODEEditor的时候风格会更加统一

### ISSUE THREAD

**Issue by wuzhican** [vbenjs/vue-vben-admin#3134]
### Subject of the feature

现在的CodeEditor中是没有边框的，当作为自定义组件放到Form中时，CodeEditor会和背景混淆在一起就像下面一样：
![image](https://github.com/vbenjs/vue-vben-admin/assets/38750781/c651562e-4323-43e4-ac30-01d86d58cced)

### Expected behaviour
给CodeEditor添加一个属性，让其可以像inputbox一样具备相关的边框样式

### Alternatives
解决方法就是让CodeEditor的class中添加ant-input,这样antd的边框属性也会作用到CodeEditor上。可以通过一个属性控制是否开启边框。

**Comment by wuzhican** [comment]
我有调好的代码，要pr吗？

**Comment by wangjue666** [comment]
> 我有调好的代码，要pr吗？
当然，非常欢迎PR

**Comment by auqf** [comment]
加了以后，页面乱了
![image](https://github.com/vbenjs/vue-vben-admin/assets/8895540/78b68f50-f04c-4b54-9d17-a08a2177bdb6)
