### ISSUE TITLE
[plugin:vite:css] Failed to load PostCSS config

### ISSUE THREAD

**Issue by zj1312114390** [vbenjs/vue-vben-admin#3136]
[plugin:vite:css] Failed to load PostCSS config
文件在朋友电脑上可以运行不用改什么东西，在我这边install之后dev报错，而且postcss.config.js里面配置一样
![image](https://github.com/vbenjs/vue-vben-admin/assets/110399274/bde404c1-e2b1-4b30-b8be-abcf405a6a41)

麻烦看到的大佬指点一下

**Comment by zj1312114390** [comment]
朋友压缩给我的不包含modules，然后自己install再dev报错
Internal server error: Failed to load PostCSS config (searchPath: D:/工作/笔记/Epaiban/Epaiban): [ReferenceError] module is not defined in ES module scope

**Comment by likui628** [comment]
请提供
1. 执行的命令行
2. 报错的详细信息

**Comment by zj1312114390** [comment]
> 请提供
> 
> 1. 执行的命令行
> 2. 报错的详细信息

![image](https://github.com/vbenjs/vue-vben-admin/assets/110399274/f4723e22-4778-430a-b884-506c0061c119)

**Comment by likui628** [comment]
用pnpm试一下
参考：https://github.com/vbenjs/vue-vben-admin#install-and-use

**Comment by zj1312114390** [comment]
> 用pnpm试一下 参考：https://github.com/vbenjs/vue-vben-admin#install-and-use

vben-admin框架？我刚刚看网址里面好像没看到postcss.config.js这个文件

**Comment by zj1312114390** [comment]
朋友说好像是因为es模块有问题。
朋友帮我在package.json中将type改成commonjs，再然后在postcss.config.js中改成exports就好了。
我的问题就这样解决了。要是不行的话可以再看看其它的
