### ISSUE TITLE
左侧菜单样式能否调整成新版

### ISSUE THREAD

**Issue by weikun321688** [vbenjs/vue-vben-admin#3138]
升级了antdv4后看vben应该用的是官方的兼容模式升级的
这个菜单样式感觉无从下手啊
<img width="330" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/9813274/e596f76e-469e-41db-8c1d-1cc5b1d4ad95">

**Comment by wangjue666** [comment]
@weikun321688 我不太理解你的意思，啥叫兼容模式升级的？ 你要改菜单样式就把`vben`侧边栏组件定义的样式移除就好

**Comment by weikun321688** [comment]
> @weikun321688 我不太理解你的意思，啥叫兼容模式升级的？ 你要改菜单样式就把`vben`侧边栏组件定义的样式移除就好

<img width="1256" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/9813274/2b320b9e-0b20-460f-bb05-c989e737c6a9">
我看代码好像是这种兼容包升级的
然后 antdv4  Menu 自带的样式是这样的

<img width="887" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/9813274/a839762a-aa7e-4287-8e3a-80e717e57377">

**Comment by wangjue666** [comment]
@weikun321688  这块我给升级的，我没有用它，直接覆盖的样式，之前版本也是这样做的，如果不想要这些样式，你移除它就好

**Comment by weikun321688** [comment]
> @weikun321688 这块我给升级的，我没有用它，直接覆盖的样式，之前版本也是这样做的，如果不想要这些样式，你移除它就好

我看动效什么的和新版也不一致，而且暗黑模式下的样式有些问题

<img width="265" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/9813274/e25c823f-3f3d-47a1-bd06-91aecaee3352">

**Comment by wangjue666** [comment]
@weikun321688  欢迎 PR 哈

**Comment by weikun321688** [comment]
> @weikun321688 欢迎 PR 哈

知道为啥了。。。除了水平模式 菜单都是用了SimpleMenu组件，这个不是antdv的组件，把这个if去掉就好了，我不确定去了之后有啥影响，就先不PR了。。。暗黑模式下白框我再看看
<img width="1292" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/9813274/7fae0dd6-dfcf-43d0-9e95-e37c5b96cdb3">
