### ISSUE TITLE
顶部菜单，点击分割菜单之后，顶部菜单点击功能失效

### ISSUE THREAD

**Issue by AidenYan97** [vbenjs/vue-vben-admin#3140]
这个版本 [vben-admin-thin-next](https://vben.vvbin.cn/thin/next/) - Simplified Chinese site

顶部菜单，点击分割菜单之后，顶部菜单点击功能失效

![image](https://github.com/vbenjs/vue-vben-admin/assets/51433157/adba4dd8-bd58-4906-9262-8e696fd21786)

- Node 版本:16.13.0
- 包管理器 (npm/yarn/pnpm) 及其版本:yarn 1.22.19

**Comment by wangjue666** [comment]
@AidenYan97 `thin`分支好久没更新了 试试用`main`分支
