### ISSUE TITLE
各位大佬有没有遇到这种情况、啥原因目前无法解决。

### ISSUE THREAD

**Issue by Forevery1** [vbenjs/vue-vben-admin#3145]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

项目启动后打开首页就会报
<img width="1643" alt="企业微信截图_2994129a-d4ef-4bc3-9c78-f80450497ec2" src="https://github.com/vbenjs/vue-vben-admin/assets/19872771/a65ab190-f520-4806-aeb0-a5a79dbda40f">
<img width="502" alt="企业微信截图_58eb87f2-1a5a-43c4-ad90-7b5bfe6d4762" src="https://github.com/vbenjs/vue-vben-admin/assets/19872771/f8347442-b033-4ed0-812e-b86e3ff693bc">
<img width="767" alt="企业微信截图_d1c877a5-197d-4b81-a298-281521aaed71" src="https://github.com/vbenjs/vue-vben-admin/assets/19872771/67612a24-527a-43b5-8cb7-a8e3627f5486">

### 复现 Bug

项目启动后打开首页就会报

## 系统信息

- 操作系统: mac os
- Node 版本: v16.19.1
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 8.9.0

**Comment by likui628** [comment]
https://github.com/vbenjs/vue-vben-admin/issues/2978

**Comment by wangjue666** [comment]
@Forevery1  是拉取的最新的仓库代码吗，没有复现呀

**Comment by DesignHhuang** [comment]
没遇到过，把包更新下看看呢

**Comment by Forevery1** [comment]
> @Forevery1 是拉取的最新的仓库代码吗，没有复现呀

是拉的最新代码、不过我改了些文件。还升级了下依赖。不知道是哪个文件改的有问题了、所以想问问你们有没有啥办法可以找到是哪文件的问题

**Comment by wangjue666** [comment]
@Forevery1  看报错是你的`Basicform`定义的位置不正确， 回滚下代码进行调试吧
