### ISSUE TITLE
ApiTransfer 不支持disabled(ant design vue 支持)，没将参数传进去

### ISSUE THREAD

**Issue by zs555zs** [vbenjs/vue-vben-admin#3147]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
ApiTransfer 不支持disabled(ant design vue 支持)，没将参数传进去，没有 v-bind="getAttrs" 

### 复现 Bug

charge-platform-ui/src/components/Form/src/components/ApiTransfer.vue
ApiTransfer 不支持disabled(ant design vue 支持)，没将参数传进去，没有 v-bind="getAttrs" 

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by zs555zs** [comment]
// disabled: { type: Boolean, default: false }, 
注意props中 disabled 注释掉，再添加 v-bind="getAttrs"

**Comment by DesignHhuang** [comment]
> // disabled: { type: Boolean, default: false }, 注意先将 props中 disabled 注释掉，再添加 v-bind="getAttrs"

有没有哪个页面用到这个的？我看一下
