### ISSUE TITLE
后端权限，更换登录信息后，权限不能及时更新的问题

### ISSUE THREAD

**Issue by crazytimor** [vbenjs/vue-vben-admin#3150]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

后端控制权限，例如某个人有root权限，能看到表格种所有信息。切换普通用户登录，没有那么多权限，但打开同一个页面后依然能看到不应该看到的内容，只有通过刷新页面F5,才会展示应该看到的内容。

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by wangjue666** [comment]
这里的功能是需要你主动处理的呀，切换用户登录你需要主动刷新 **页面路由菜单**，vben也提供了demo演示 https://vben.vvbin.cn/#/permission/back/page

**Comment by crazytimor** [comment]
不是页面路由的问题，例如页面有张带查询的表格，申明了查询配置 formConfig: formConfig,

`//申明了查询配置 formConfig: formConfig
export const formConfig: Partial<FormProps> = {
  labelWidth: 100,
  schemas: [
    {
      field: `channel_group_id`,
      label: `群组ID`,
      component: 'InputNumber',
      colProps: {
        lg: 4,
      },
      ifShow: hasPermission('is_manager'),
    },
    {
      field: `channel_user_id`,
      label: `业务员ID`,
      component: 'InputNumber',
      colProps: {
        lg: 4,
      },
      ifShow: hasPermission(['is_manager', 'team_leader']),
    },
  ],
};`

当切换身份后 formConfig 没有再改变。导致的问题

**Comment by wangjue666** [comment]
@crazytimor `hasPermission('is_manager')` 返回的结果不是响应式数据呀
