### ISSUE TITLE
接口调用参数加密功能

### ISSUE THREAD

**Issue by gavin-james** [vbenjs/vue-vben-admin#3152]
像登录接口，有一个统一的参数能否进行参数的加密，以防止出现数据泄漏等问题

**Comment by wangjue666** [comment]
那加密方式也要定义一个处理，这块需要你自己根据业务在`axios`的`beforeRequestHook`处理下。多说一句, 前台参数加密没有太多意义，该破解照样破解，给你举个例子

`google`的开发人员算是一流的吧，谷歌翻译的接口破解 `npm`包有上百个，去年谷歌翻译后台不再完全依赖前台接口的加密了，现在这些npm包可谓是全军覆没。

你需要做的是网站升级成**https**,安全防护还是需要后端处理好。
