### ISSUE TITLE
页面不能打开本地的pdf文件

### ISSUE THREAD

**Issue by susanliy** [vbenjs/vue-vben-admin#3163]
**#描述 Bug：**
页面点击不能打开本地pdf文件，路由会重定向到首页； 直接访问本地pdf文件时为空白页
![image](https://github.com/vbenjs/vue-vben-admin/assets/34951760/6f20b08b-2e47-4450-a127-acd5fa91e018)

**#复现 Bug：**
在 public/static/XXX.png 目录下添加pdf文件
![image](https://github.com/vbenjs/vue-vben-admin/assets/34951760/141108ef-6942-4d6d-bc40-db5caac73a2b)

在页面中打开pdf文件，点击a标签会重定向到首页  不能直接打开pdf文件

` <a href="/public/static/BusinessPlatformOperationManual.pdf">12313</a>`

![012ba7c5fcbea8fe077a92386ef2289](https://github.com/vbenjs/vue-vben-admin/assets/34951760/00d8b1af-bcd7-414a-831b-47d77dbb4d1b)

**### 系统信息**
操作系统: Windows 10 专业版
Node 版本: v18.16.0
包管理器 (npm/yarn/pnpm) 及其版本: pnpm 8.6.5
vebn版本：2.10.0

**Comment by wangjue666** [comment]
@susanliy  请参考https://github.com/vbenjs/vue-vben-admin/issues/1822, 是vben 依赖的vite插件问题

**Comment by susanliy** [comment]
试过https://github.com/vbenjs/vue-vben-admin/issues/1822的方法不可行， 之前在vben 2.8.0的版本的时候是可以用的，在2.10.0版本就不行了

**Comment by susanliy** [comment]
> @susanliy 请参考#1822, 是vben 依赖的vite插件问题

试过 https://github.com/vbenjs/vue-vben-admin/issues/1822 的方法不可行， 之前在vben 2.8.0的版本的时候是可以用的，在2.10.0版本就不行了

**Comment by wangjue666** [comment]
开发模式打不开其实也没关系 打包后就正常了

**Comment by susanliy** [comment]
> 开发模式打不开其实也没关系 打包后就正常了

打包 发布之后 访问的pdf也是空白的 
![b3e5d79e9b9fcb66fa1ee330d15ca67](https://github.com/vbenjs/vue-vben-admin/assets/34951760/62844c2e-3b18-47d6-8f71-81982938a644)

**Comment by wangjue666** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/d48c79a1-6175-40bb-b20a-409d5c4ddc31)

这不是还是访问的首页吗

**Comment by wangjue666** [comment]
# 号去了

**Comment by wangjue666** [comment]
duplicate https://github.com/vbenjs/vue-vben-admin/issues/1744
