### ISSUE TITLE
 考虑迁移持久化实现以简化项目维护

### ISSUE THREAD

**Issue by kirklin** [vbenjs/vue-vben-admin#3165]
**当前情况：**
Currently, Vben has self-encapsulated the Persistent feature. I propose considering migrating the project to `pinia-plugin-persistedstate` to take advantage of `vueUse` and `pinia-plugin-persistedstate`, which could effectively reduce the project's maintenance complexity. This issue is mainly for discussing the feasibility and benefits of the migration.
目前，Vben 自行封装了 Persistent 功能。我建议考虑将项目迁移到 `pinia-plugin-persistedstate`，以充分利用 `vueUse` 和 `pinia-plugin-persistedstate`，从而有效降低项目的维护复杂性。这个问题主要是为了讨论迁移的可行性和好处。

**建议：**
Consider using `pinia-plugin-persistedstate` to replace the current self-encapsulated Persistent feature. This may reduce the project's maintenance complexity. Before the migration, appropriate testing and validation should be performed to ensure that the new solution does not introduce new issues.
考虑使用 `pinia-plugin-persistedstate` 来替代当前的自行封装的 Persistent 功能。这样做可能会减少项目的维护复杂性。在迁移之前，需要进行适当的测试和验证，以确保新的解决方案不会引入新的问题。

**Comment by wangjue666** [comment]
可以，欢迎PR
