### ISSUE TITLE
ApiSelect Dev 环境报出警告

### ISSUE THREAD

**Issue by Pluto1219** [vbenjs/vue-vben-admin#3168]
选择option时报出以下警告
[Vue warn]: Invalid prop: type check failed for prop "value". Expected Object, got String with value "5".

**Comment by likui628** [comment]
> @Pluto1219 提供复现示例

http://localhost:5173/#/comp/form/basic
此界面可见这种warning

**Comment by wangjue666** [comment]
@Pluto1219  修复了:)
