### ISSUE TITLE
ApiSelect选择变化 会触发Form的field-value-change2次

### ISSUE THREAD

**Issue by JonasYans** [vbenjs/vue-vben-admin#3170]
第一次value是object 里面是{label:***,value:****} 第二次是value
把handleChange的emit注释就行了 如下：
      function handleChange(_, ...args) {
        // emit('change', ...args);
        emitData.value = args;
      }

**Comment by likui628** [comment]
https://github.com/vbenjs/vue-vben-admin/commit/0f2c2eabd671af457febbb16fa3996c845bae145

**Comment by wangjue666** [comment]
https://github.com/vbenjs/vue-vben-admin/commit/b103c6495428a99b164467ff597155948f48323c 再改动下这个，这样就解决首次验证问题了
