### ISSUE TITLE
ignoreKeepAlive: false is not working on the <script setup>

### ISSUE THREAD

**Issue by doraemonxxx** [vbenjs/vue-vben-admin#3175]
When I tried to use the `ignoreKeepAlive: false ` in a router, it doesn't cache the component when the vue file is using `<script setup>` but when using the `defineComponent({name: 'xxx'})`. The `ignoreKeepAlive: false` is working because the router name is the same as the defineComponent name.

Am I missing something with the code?

related issue: https://github.com/vbenjs/vue-vben-admin/issues/1889

Thank you!

**Comment by likui628** [comment]
What is the name of your component?

**Comment by likui628** [comment]
> the name if my file is **index** under **category/index.vue**
> 
> Should I rename my file into **Category** ? (`Category.vue`)

yes, script-setup automatically setting the name option from inferred filename.
https://github.com/vuejs/core/pull/4997
