### ISSUE TITLE
打包后主题primaryColor 没有生效

### ISSUE THREAD

**Issue by KTBOY** [vbenjs/vue-vben-admin#3178]
### 描述 Bug

在themeConfig.ts默认主题修改为#0e7a3e，但打包后生产环境没有生效，在dev本地运行开发环境生效
`export const primaryColor = '#0e7a3e'; `

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码
**开发环境**
![image](https://github.com/vbenjs/vue-vben-admin/assets/52773276/3ee276e6-e303-4b62-890d-a229fc1ea06e)

**生产环境**
![image](https://github.com/vbenjs/vue-vben-admin/assets/52773276/75f18009-0f02-4dd4-b976-997b9021f937)
![image](https://github.com/vbenjs/vue-vben-admin/assets/52773276/eb212de2-4296-4f5e-a519-0a2869df2a16)
自定义的颜色被覆盖
![image](https://github.com/vbenjs/vue-vben-admin/assets/52773276/06b88280-77aa-47ee-845b-8d89752909b6)

## 系统信息

- 操作系统:window11
- Node 版本:18.15.0
- 包管理器 (npm/yarn/pnpm) 及其版本:yarn:1.22.19

**Comment by likui628** [comment]
你什么版本，用新版本试一下

**Comment by likui628** [comment]
那得你自己想办法调试了

**Comment by 2125zyrc** [comment]
我在 dev 环境下也无法切换主题
