### ISSUE TITLE
表格自适应超出页面高度

### ISSUE THREAD

**Issue by BenXi630** [vbenjs/vue-vben-admin#3185]
表格自适应如果带分页就会超出页面高度，如图
![image](https://github.com/vbenjs/vue-vben-admin/assets/38492283/c7461a62-33ce-4a3d-a945-43326e5f59ef)
只需要把BasicTable.vue里的第437行改成
`.ant-pagination {
      margin: 10px 0 0 !important;
    }`

**Comment by wangjue666** [comment]
@BenXi630  可以提个pr
