### ISSUE TITLE
vben管理后台菜单权限

### ISSUE THREAD

**Issue by zj1312114390** [vbenjs/vue-vben-admin#3186]
大佬，这个用户信息是后台返回的用户信息包含角色信息和菜单信息嘛？
![1b2262a10dec5e4fed30a3cae765e4f5](https://github.com/vbenjs/vue-vben-admin/assets/110399274/728b73fe-929b-41e8-9790-ff34a3221850)
左侧菜单栏怎么样可以动态加载出来，目前页面是在router里面写死的。
希望路过的大佬指教，万分感谢

**Comment by wangjue666** [comment]
在本地运行看下

![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/127514d7-a4b4-453d-8669-3e02f9e6585d)

![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/2ad7f862-66bb-47d9-b9bd-6761051f12f1)
