### ISSUE TITLE
使用插槽 ApiSelect首次选择值时仍然提示校验

### ISSUE THREAD

**Issue by web-wade** [vbenjs/vue-vben-admin#3188]
<img width="483" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/24384393/5fde3d4f-9691-44e3-beb1-95d63a3bc787">
<img width="608" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/24384393/10ac8e79-2895-4076-9c01-2fc70b042478">
<img width="1086" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/24384393/c1d7946b-ca7a-4b74-8bca-cf7863fd82eb">

**Comment by ljw-codeking** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/75002215/04b7b61c-c884-413d-a159-531135faff16)
把nextTick给注释掉就可以解决这个问题了，我不明白这里为什么要加nextTick

**Comment by web-wade** [comment]
> ![图像](https://user-images.githubusercontent.com/75002215/277932980-04b7b61c-c884-413d-a159-531135faff16.png) src\hooks\component\useFormItem.ts 把nextTick给注释掉就可以解决这个问题了，我不明白这里为什么要加nextTick

测试了还是不可以

**Comment by wangjue666** [comment]
@web-wade 添加 autoLink 为 false 试试

**Comment by wangjue666** [comment]
是拉取的最新版本的仓库代码吗？

**Comment by web-wade** [comment]
最新的代码，main分支，不设置默认值，上来直接操作，不要操作其他输入框，操作其他之后再选择就不会触发

**Comment by web-wade** [comment]
<img width="797" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/24384393/04dd4f15-44f7-41a0-b9d6-e62bc41b6f11">
把itemProps改成props.schema.itemProps就可以，使用itemProps第一次没有修改autoLink

**Comment by wangjue666** [comment]
嗯 你把 `component: 'ApiSelect',` 写成这样就会设定上

**Comment by web-wade** [comment]
@wangjue666 这样可以设定，但是没有选择值点击提交出现验证，在选择不会取消

**Comment by wangjue666** [comment]
或者 

```
{
      field: 'field31',
      component: 'Input',
      label: '下拉本地搜索',
      helpMessage: ['ApiSelect组件', '远程数据源本地搜索', '只发起一次请求获取所有选项'],
      required: true,
      slot: 'localSearch',
      colProps: {
        span: 8,
      },
      itemProps: {
        autoLink: false,
      },
      defaultValue: '',
    },
```

**Comment by web-wade** [comment]
这样解决都会导致前一个问题，先提交在修改不能触发验证

**Comment by web-wade** [comment]
可以在change事件里面调用一下验证

**Comment by MosYCo** [comment]
<img width="789" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/87270979/b618e4e5-1c69-4eb5-a2cf-75a42c266688">

<img width="521" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/87270979/079a4aab-ba82-4a49-8e54-d15c96936e70">

我试了一下，在handleChange里emit('update:value')就可以了。其实这里我不是很明白为什么要watch state.value，state已经是双向绑定的了, usrRulesFormItem里已经有watchEffect了，感觉这里再watch有点多余

**Comment by badaozhenqi** [comment]
> ![image](https://private-user-images.githubusercontent.com/75002215/277932980-04b7b61c-c884-413d-a159-531135faff16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MjMzNzMsIm5iZiI6MTcwMTQyMzA3MywicGF0aCI6Ii83NTAwMjIxNS8yNzc5MzI5ODAtMDRiN2I2MWMtYzg4NC00MTNkLWExNTktNTMxMTM1ZmFmZjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA5MzExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MGMxN2ZhNGViYTdlNDI1NDllOGMzMDhmMzUyYTgxNzQzM2NjZjI4M2JhNzY3NGI3ZjU4YWQ5OTYzZjNhYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CfpV4eAlLgzbPF4yvmu6DKIKMb_waA9CF45Ona34QiY) src\hooks\component\useFormItem.ts把nextTick给注释掉就可以解决这个问题了，我不明白这里为什么要加nextTick

目前用这个方法可以解决，没有深究为什么。

**Comment by 814096703** [comment]
一个古老的bug

**Comment by rookiePrgrmer** [comment]
> ![image](https://private-user-images.githubusercontent.com/75002215/277932980-04b7b61c-c884-413d-a159-531135faff16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MjQxNzEsIm5iZiI6MTcwOTUyMzg3MSwicGF0aCI6Ii83NTAwMjIxNS8yNzc5MzI5ODAtMDRiN2I2MWMtYzg4NC00MTNkLWExNTktNTMxMTM1ZmFmZjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDAzNDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZDc0NzM2NDM0YTg1OWRjOGE5NjY1MDMwYmFmMDZhOWI3ZWMwNDFhMDVlZGQ1OWEyOThlZThjMTU4NzBkYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0dcHinktvVHWTom_s3ikbuxsqxjTzHUpQpgvSNg6ESI) src\hooks\component\useFormItem.ts把nextTick给注释掉就可以解决这个问题了，我不明白这里为什么要加nextTick

这样做会导致，onChange事件的第二个参数，总是上一次变化后的值，不是当前值。

**Comment by lovelyJason** [comment]
俺的那篇issue里也是这个问题

**Comment by lovelyJason** [comment]
> <img alt="image" width="483" src="https://private-user-images.githubusercontent.com/24384393/277919686-5fde3d4f-9691-44e3-beb1-95d63a3bc787.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDA4NjcsIm5iZiI6MTcxMjc0MDU2NywicGF0aCI6Ii8yNDM4NDM5My8yNzc5MTk2ODYtNWZkZTNkNGYtOTY5MS00NGUzLWJlYjEtOTVkNjNhM2JjNzg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA5MTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0YmMyNWJmNDEyOTk4ZGE0NjdhMDg1M2JkYmYzYWE4N2ZjMmZjNTQxZDRjMjU1OWY5YzkxZmE5NTJiYTE5ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SYpiW87z5GyBqjqc4Pkj8v6SjN-_N5JcQUMVd0DP4eU"> <img alt="image" width="608" src="https://private-user-images.githubusercontent.com/24384393/277919744-10ac8e79-2895-4076-9c01-2fc70b042478.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDA4NjcsIm5iZiI6MTcxMjc0MDU2NywicGF0aCI6Ii8yNDM4NDM5My8yNzc5MTk3NDQtMTBhYzhlNzktMjg5NS00MDc2LTljMDEtMmZjNzBiMDQyNDc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA5MTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1M2JlYjk0MDFjNGRkMjdjYzhiNDg5ZDdiYjc5OTIyODMyYjA1YWM5ZTFmYjkxZWU1NDAzNmYwNmNmODI4YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BzcJkUrGOFgLGT9NZkMRNqsYCdP45xPP6NAw9hUyc7A"> <img alt="image" width="1086" src="https://private-user-images.githubusercontent.com/24384393/277919850-c1d7946b-ca7a-4b74-8bca-cf7863fd82eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NDA4NjcsIm5iZiI6MTcxMjc0MDU2NywicGF0aCI6Ii8yNDM4NDM5My8yNzc5MTk4NTAtYzFkNzk0NmItY2E3YS00Yjc0LThiY2EtY2Y3ODYzZmQ4MmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA5MTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MGFjZGNjZGViZjM2MTU0NjhlODg3OTAxYzNjMWQwMzg2YmY0ZWIzZDUwNWE0OWRjMTEzNDMzZGYwNzQ0MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MV8fmGfTwU3um_s2Icr_hDkzCmI09YKRmTA0Su1Cqik">

最终你咋解决的

**Comment by supermebing** [comment]
有没有结果？

**Comment by lovelyJason** [comment]
> 有没有结果？
我反正是有结果了

**Comment by betgar** [comment]
分享一下，我在`Modal`中使用表单`Form`的一点经验，规避问题的经验：

```html
 <BasicModal
    v-bind="$attrs"
    :min-height="30"
    :maskClosable="false"
    title="测试"
    @register="registerModal"
    @cancel="closeModal"
    @open-change="onVisibleChange"
    @ok="onOk"
  >
    <BasicForm
      @register="registerForm"
      :model="compStates.dataModel"
      @field-value-change="onFieldValueChange"
    />
  </BasicModal>

```
```js
const compStates = ref({
    dataModel: { id: '' },
  });
// 判断是否是新增
const isNewModelRef = computed(() => {
    return isNil(compStates.value.dataModel.id) || isEmpty(compStates.value.dataModel.id);
  });

// 表单
  const [registerForm, { validate: validateForm, getFieldsValue, setFieldsValue, clearValidate, validateFields }] =
    useForm(useFormOptions());

// modal
  const [registerModal, { closeModal }] = useModalInner((data: ViewEntityInfoRel) => {
    // compStates.value.dataModel = data;
    setFieldsValue(data);
  });

// modal显示
  function onVisibleChange(visible) {
    if (visible) {
      nextTick(() => {
        // 新增，打开时，不想看到已经触发的validate message
        if (isNewModelRef.value) {
          clearValidate();
        }
      });
    }
  }

// 字段变更
const onFieldValueChange = () => {
    // 消除异常的验证消息
    nextTick(() => validateForm()); // clearValidate; validateFields 
  };
```

上述的代码 仅供示意，参考，不可运行

1.  modal显示时，字段已经显示了校验信息，规避这个问题，在`onFieldValueChange `中`clearValidate()`信息
2. 表单的元素，需要渲染成 自定义的 静态文本，表单需要配置`model`属性，如果不配置model属性，render函数内部无法取值
```js
{
      field: 'id',
      component: 'Input',
      label: 'ID',
      labelWidth: '100px',
      colProps: {
        span: 22,
      },
      render({ model, field }) { // 如果不配置model属性，这里的model是空的，不能取值
        return h('span', { class: 'ant-form-text' }, model[field]);
      },
    }
```
3.  `ApiSelect`异步加载的数据，第一次选择之后，出现校验信息的规避尝试
   - `Form`配置`model`属性，虽然你不一定需要用
   - `Modal`的回调函数里面使用`setFieldsValue`设置表单的初始化值（上述代码有示例），尝试直接`compStates.value.dataModel = data` 赋值的方式不行
   - 如果还不生效，考虑结合`onFieldValueChange`试试
