### ISSUE TITLE
main版本代码，全局引入ant-design-vue，项目报错无法运行

### ISSUE THREAD

**Issue by crydear** [vbenjs/vue-vben-admin#3189]
最新版本的main分支代码，克隆下来后安装完依赖，在main.ts里
1:import Antd from 'ant-design-vue';
2:app.use(Antd).mount('#app');
执行上述两步后，项目报错，提示‘isFunction is not a function’

**Comment by wangjue666** [comment]
@crydear  在 `src/components/registerGlobComp.ts` 这个文件下执行全局注册
