### ISSUE TITLE
怎么实现vben中某一列的控件根据另外一个参数变成文本框下拉框等控件

### ISSUE THREAD

**Issue by zj1312114390** [vbenjs/vue-vben-admin#3195]
![image](https://github.com/vbenjs/vue-vben-admin/assets/110399274/6331c4d3-d6a7-4850-942a-82acfc1399e5)
怎么样每一行显示不同的控件类型

**Comment by wangjue666** [comment]
https://vben.vvbin.cn/#/comp/table/customerCell 看demo示例代码
