### ISSUE TITLE
   background-color: rgb(0 0 0 / 5%); 克隆下来以后 install 启动后打开页面报错，请问这个怎么解决呢

### ISSUE THREAD

**Issue by Aa805837680** [vbenjs/vue-vben-admin#3200]
[less] error evaluating function rgb: color functions take numbers as parameters

**Comment by wangjue666** [comment]
你电脑的node版本多少

**Comment by Aa805837680** [comment]
> 你电脑的节点版本是多少

v16.16.0  我刚改为 v20.1.0 重新 install 了一下 还是会报同样的错误

**Comment by wangjue666** [comment]
@Aa805837680  我这边测试没问题， 依赖是通过 pnpm进行安装的吗？
