### ISSUE TITLE
next 分支， 打包@vben/types目录报错

### ISSUE THREAD

**Issue by zrnwsy** [vbenjs/vue-vben-admin#3202]
遇到下面这个问题，有大佬遇到过吗？可以告知一下怎么解决吗？

### Describe the bug

拉取了next分支，打包，就报错：
@vben/types:build: i Building @vben/types
@vben/types:build: Generated an empty chunk: "index".
@vben/types:build: Generated an empty chunk: "global".
@vben/types:build: src/global.ts(1,16): error TS2664: Invalid module name in augmentation, module 'vue-router' cannot be found.

### Reproduction

重现步骤：pnpm install  -> pnpm build

## System Info

- win10系统
- Node 版本:  v18.16.0
- pnpm 版本：v8.6.0

**Comment by likui628** [comment]
next分支没有在维护，新版本请关注vben3

**Comment by zrnwsy** [comment]
这个打包配置怎么改一下比较好呢？这个next分支作者大哥没有时间维护了吗？
