### ISSUE TITLE
vite proxy浏览器GET请求丢失参数

### ISSUE THREAD

**Issue by quanbisen** [vbenjs/vue-vben-admin#3203]
- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

相关issue：[vite-plugin-html#38](https://github.com/vbenjs/vite-plugin-html/issues/38)
修复PR：[vite-plugin-html#96](https://github.com/vbenjs/vite-plugin-html/pull/96)
该PR能修复改问题，麻烦作者merge一下修复代码，release一个新版本，目前我只能手动修改node_packages的源码包

为什么有这个场景，因为第三方认证通过后是需要回调的，回调到URL一般是 GET http://xxx/xx/callback?code=xxxx&state=state，回调接口无法获取到code参数。
### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System: mac
- Node version: v16.19.1
- Package manager (npm/yarn/pnpm) and version: pnpm:8.9.2

**Comment by likui628** [comment]
@jinmao88

**Comment by zwtvip** [comment]
大佬，你在作者的这个qq群没：569291866
![Uploading %Q[S423((XEBLUR{KIH4CLQ.png…]()

**Comment by zwtvip** [comment]
大佬，你在作者的这个qq群没：569291866
![%Q S423((XEBLUR{KIH4CLQ](https://github.com/vbenjs/vue-vben-admin/assets/29778465/e14a2ec9-aeca-4ae6-a187-e3530393d1c5)

**Comment by likui628** [comment]
我不在这个群，有什么事请讲，我帮你转达

**Comment by zwtvip** [comment]
> 我不在这个群，有什么事请讲，我帮你转达

我在那个群，很多人在里面，大佬要不要进去，有问题好沟通，金毛也在里面

**Comment by likui628** [comment]
> > 我不在这个群，有什么事请讲，我帮你转达
> 
> 我在那个群，很多人在里面，大佬要不要进去，有问题好沟通，金毛也在里面

我在vben3的群里，最近开始搞vben3了

**Comment by zwtvip** [comment]
> > > 我不在这个群，有什么事请讲，我帮你转达
> > 
> > 
> > 我在那个群，很多人在里面，大佬要不要进去，有问题好沟通，金毛也在里面
> 
> 我在vben3的群里，最近开始搞vben3了

大佬，群号是多少，我进去学习一下

**Comment by ivanberry** [comment]
这个问题不打算解决了吗？很影响开发体验啊
