### ISSUE TITLE
右侧功能菜单弹出样式错乱

### ISSUE THREAD

**Issue by TCxiu** [vbenjs/vue-vben-admin#3211]
### 描述 Bug

![fc2a97c6158469cf46c65f0c322252c](https://github.com/vbenjs/vue-vben-admin/assets/31518009/55df3e4d-bc01-4009-963d-9cec94f30a9d)

### 复现 Bug
![fc2a97c6158469cf46c65f0c322252c](https://github.com/vbenjs/vue-vben-admin/assets/31518009/a423de95-5d0b-461c-a67c-33c16a281eff)
点击即出现

**Comment by wangjue666** [comment]
@TCxiu 修复了 antd组件的问题
