### ISSUE TITLE
为什么Vben的文档又挂了。

### ISSUE THREAD

**Issue by Jimmyloua** [vbenjs/vue-vben-admin#3213]
有没有临时的文档可以用呢？

**Comment by wangjue666** [comment]
https://doc.vvbin.cn/ 正常呀

**Comment by Jimmyloua** [comment]
> https://doc.vvbin.cn/ 正常呀
![QQ截图20231031104647](https://github.com/vbenjs/vue-vben-admin/assets/71743591/854f8b99-1809-4690-a13c-97062fda1918)
但是我访问这个网站就是这样，而且让另一个访问也进不去。

**Comment by Jimmyloua** [comment]
> https://doc.vvbin.cn/ 正常呀

不好意思，好像是网络的问题，我用手机热点能进去。

**Comment by wangjue666** [comment]
> 不好意思，好像是网络的问题，我用手机热点能进去。

没事，有问题及时问
