### ISSUE TITLE
vben运用ant-design的上传组件按钮出现了，其它的没用

### ISSUE THREAD

**Issue by zj1312114390** [vbenjs/vue-vben-admin#3221]
![b19d548f462e5601ff0b47109225ab1](https://github.com/vbenjs/vue-vben-admin/assets/110399274/1a715e5e-260d-40cb-85a5-d9770f55cd1c)
![c7eccaa560680f6da3bd166e21766d5](https://github.com/vbenjs/vue-vben-admin/assets/110399274/01253d77-8d23-49c7-be2e-7d5616ac0f69)
![88c8d2d8a93de7100bde5cc711c86d0](https://github.com/vbenjs/vue-vben-admin/assets/110399274/6ab31709-9214-4258-82b6-ef8785a2b14b)
![e1ec441b1a446f6f9639bc419866480](https://github.com/vbenjs/vue-vben-admin/assets/110399274/39d3ee9f-9080-4704-a01b-82baa354debd)
代码拿过来，按钮有了，a-upload-trigger也试了，那个filelist加载不出来，按钮也没有选择文件的弹出

**Comment by DesignHhuang** [comment]
看了一下你的代码，有没有可能你没有引用```a-upload``` 这个组件呢。。。

**Comment by wangjue666** [comment]
antd的示例代码 默认组件是全局引用的，vben是按需引用的
