### ISSUE TITLE
useTable下 formConfig设置submitOnChange: true ，schemas 属性下有设置defaulfValue时会重复请求

### ISSUE THREAD

**Issue by zs555zs** [vbenjs/vue-vben-admin#3224]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
使用 useTable，设置
```
api: getTable,
useSearchForm: true,
    formConfig: {
      schemas: billSearchSchema,   // 下面的表格项设置 defaulfValue
      submitOnChange: true,  // 为true 
    },
```
schemas 下有设置 defaulfValue，  submitOnChange: true 时，会执行两次请求 getTable
### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by DesignHhuang** [comment]
如果一次是默认请求，一次是表格项OnChange导致的话，可以试试将```immediate```设为```false```
![image](https://github.com/vbenjs/vue-vben-admin/assets/3368397/cb69b17c-64d0-4f2a-8249-e2eeceb8a530)

**Comment by zs555zs** [comment]
> 如果一次是默认请求，一次是表格项OnChange导致的话，可以试试将`immediate`设为`false` ![image](https://user-images.githubusercontent.com/3368397/279638419-cb69b17c-64d0-4f2a-8249-e2eeceb8a530.png)

这样确实可以

**Comment by Jzow** [comment]
这个参数在table里一点效果没有

```typescript
 const [registerTable, { getSelectRows, reload }] = useTable({
      title: '操作',
      rowKey: 'id',
      columns: ReceiptColumn,
      api: getReceipt,
      searchInfo: {
        "type": type.value,
        "subType": subType.value,
      },
      rowSelection: {
        type: 'radio',
      },
      formConfig: {
        labelWidth: 110,
        schemas: searchSchema,
      },
      showIndexColumn: false,
      bordered: true,
      showTableSetting: true,
      canResize: true,
      tableSetting: { fullScreen: true },
      useSearchForm: true,
      clickToRowSelect: true,
      immediate: false,
    });
```

他放在table里的目的又是什么 如果只是为了解决ApiSelect

**Comment by DesignHhuang** [comment]
> 这个参数在table里一点效果没有
> 
> ```ts
>  const [registerTable, { getSelectRows, reload }] = useTable({
>       title: '操作',
>       rowKey: 'id',
>       columns: ReceiptColumn,
>       api: getReceipt,
>       searchInfo: {
>         "type": type.value,
>         "subType": subType.value,
>       },
>       rowSelection: {
>         type: 'radio',
>       },
>       formConfig: {
>         labelWidth: 110,
>         schemas: searchSchema,
>       },
>       showIndexColumn: false,
>       bordered: true,
>       showTableSetting: true,
>       canResize: true,
>       tableSetting: { fullScreen: true },
>       useSearchForm: true,
>       clickToRowSelect: true,
>       immediate: false,
>     });
> ```
> 
> 他放在table里的目的又是什么 如果只是为了解决ApiSelect

![image](https://github.com/vbenjs/vue-vben-admin/assets/3368397/12b2a6b8-2493-47b8-8cec-7d12386c025d)
在有api的情况下，这个参数可以控制表格是否立即去请求数据。

**Comment by Jzow** [comment]
> 在有api的情况下，这个参数可以控制表格是否立即去请求数据。

就上面的demo当他为false的时候他是可以阻止打开table去直接请求，但是什么时候触发true 请求

**Comment by DesignHhuang** [comment]
> > 在有api的情况下，这个参数可以控制表格是否立即去请求数据。
> 
> 就上面的demo当他为false的时候他是可以阻止打开table去直接请求，但是什么时候触发true 请求

reload(),或者控制fetch

**Comment by Jzow** [comment]
> > > 在有api的情况下，这个参数可以控制表格是否立即去请求数据。
> > 
> > 
> > 就上面的demo当他为false的时候他是可以阻止打开table去直接请求，但是什么时候触发true 请求
> 
> reload(),或者控制fetch

```typescript
    const [registerModal, {setModalProps, closeModal}] = useModalInner(async (data) => {
      setModalProps({confirmLoading: false, destroyOnClose: true, width: 1200});
      type.value = data.type
      subType.value = data.subType
      getTitle.value = data.title
      reload({
        "type": type.value,
        "subType": subType.value,
      });
    });
    
    export function getReceipt(params: queryReceipt, type: string, subType: string) {
    console.info(params)
    console.info(type)
    console.info(subType)
    return defHttp.get<BaseDataResp<ReceiptResp>>(
        {
            url: API.GetOtherReceipt,
            params: params
        }
    );
}
```
这样的话它好像并没有把值传到Api当中  打印出的结果都是undefined，显然我在传递之前确保他肯定是有值

**Comment by Jzow** [comment]
#1407 #3269
