### ISSUE TITLE
期望form ApiSelect增加mode入参，便于进行多选multiple

### ISSUE THREAD

**Issue by keepsl** [vbenjs/vue-vben-admin#3231]
目前自己改造了一下  奈何技术菜  期望作者能够加上该功能，感谢

### 实现后错误效果
![1698918703475](https://github.com/vbenjs/vue-vben-admin/assets/8720143/198e2a16-5782-4f65-b0d6-a06319ef697d)

### 示例代码
![222](https://github.com/vbenjs/vue-vben-admin/assets/8720143/9b904911-0f79-4b4a-9aff-be6778e30034)

**Comment by zwtvip** [comment]
不是在这里改，不要动源文件，在componentProps这个对象里面加mode

**Comment by wangjue666** [comment]
`ApiSelect`组件是支持多选的呀， 你要在 `vxetable`中使用应该用插槽
