### ISSUE TITLE
登录页loginForm.vue 记住用户名使用setAuthCache(RememberMe,'xxx')方法后，刷新页面getAuthCache('RememberMe')取值为undfined

### ISSUE THREAD

**Issue by zwtvip** [vbenjs/vue-vben-admin#3232]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by likui628** [comment]
项目配置是CacheTypeEnum.LOCAL的情况下按理说应该存在localstorage里。
```
export function setAuthCache(key: BasicKeys, value) {
  const fn = isLocal ? Persistent.setLocal : Persistent.setSession;
  return fn(key, value, true);
}
```
看标题，RememberMe一个有单引号，一个没有单引号，是打错了吗？
```setAuthCache(RememberMe,'xxx') ```
```getAuthCache('RememberMe')```

**Comment by zwtvip** [comment]
> 项目配置是CacheTypeEnum.LOCAL的情况下按理说应该存在localstorage里。
> 
> ```
> export function setAuthCache(key: BasicKeys, value) {
>   const fn = isLocal ? Persistent.setLocal : Persistent.setSession;
>   return fn(key, value, true);
> }
> ```
> 
> 看标题，RememberMe一个有单引号，一个没有单引号，是打错了吗？ `setAuthCache(RememberMe,'xxx') ` `getAuthCache('RememberMe')`

打错了，你可以测试一下，我怎么试都拿不到local模式下的值，set的时候我看浏览器local已经有值了

**Comment by wangjue666** [comment]
再调试下吧， 看下设置的时候key 取的时候key 是否一致， 浏览器里能看到有值肯定可以获取到
