### ISSUE TITLE
改造登录页面以及登录接口，路由可以跳转，但是会导致页面卡死

### ISSUE THREAD

**Issue by yin2017168** [vbenjs/vue-vben-admin#3233]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

调整登录页面和登录逻辑，导致页面卡死在登录页
![image](https://github.com/vbenjs/vue-vben-admin/assets/26922373/db324ea7-aafc-499a-bf8b-2cb141927be0)
user.ts:125 [Vue warn]: Unhandled error during execution of render function 
  at <Index key=0 > 
  at <PageLayout> 
  at <LayoutContent> 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... > 
  at <ALayout class="vben-default-layout-main" > 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... > 
  at <ALayout class="ant-layout ant-layout-has-sider" > 
  at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... > 
  at <ALayout class="vben-default-layout" > 
  at <DefaultLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< null > > 
  at <RouterView> 
  at <AppProvider> 
  at <Anonymous value= {hashed: true, components: {…}, theme: undefined, token: {…}} > 
  at <ALocaleProvider locale= {locale: 'zh-cn', Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} ANT_MARK__="internalMark" > 
  at <LocaleReceiver children=fn<children> > 
  at <AConfigProvider locale= {locale: 'zh-cn', Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} theme= {token: {…}} > 
  at <App>

### 复现 Bug

调整登录页面，调整store-下的user.ts,调整http请求改为测试环境对应地址
![image](https://github.com/vbenjs/vue-vben-admin/assets/26922373/b3754f5e-4117-4c54-bd68-ceba7b8ae2cf)

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by wangjue666** [comment]
你的业务问题，但你提供的信息的太少，无法判断是哪儿的问题, 建议你先将代码回滚到正常运行的状态，然后单步调试下
