### ISSUE TITLE
无法切换主题色

### ISSUE THREAD

**Issue by cubeking** [vbenjs/vue-vben-admin#3250]
### 描述 Bug

系统在为什么无法切换主题色? 低版本, 还可以的? 高版本怎么没了?

## 系统信息

- 操作系统:
- Node : v16.16.0
- pnpm : 7.29.3

**Comment by wangjue666** [comment]
请参考 https://github.com/vbenjs/vue-vben-admin/issues/3251#issuecomment-1800920997
