### ISSUE TITLE
BasicTree的appendNodeByKey方法新增节点，视图虽然有更新，但是打印treeData数据源仍然是旧值，没有新增的节点数据，导致递归查找新增节点为null

### ISSUE THREAD

**Issue by zwtvip** [vbenjs/vue-vben-admin#3253]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by wangjue666** [comment]
提供示例代码

**Comment by wangjue666** [comment]
@zwtvip  你传递的treedata 并不会被组件更改，现在basictree 增加了 `getTreeData` 方法，用这个来获取当前tree的数据
