### ISSUE TITLE
BasicModal组件:title设置存在无效情况

### ISSUE THREAD

**Issue by SihuiHu6** [vbenjs/vue-vben-admin#3258]
将计算属性赋值给BasicModal中的title无效

**Comment by jiaowoxiaobala** [comment]
给个示例代码

**Comment by SihuiHu6** [comment]
Template
`
<BasicDrawer
  @register="drawerRegister"
  :title="getTitle"
  width="50%"
  @ok="handleSubmit"
  @close="handleClose"
  showFooter
  :showCancelBtn="false"
  okText="Submit"
>
.....
</BasicDrawer>
`

Script
`
let isCreate = ref(true);

const getTitle = computed(() => {
  return !unref(isCreate) ? 'Add Product' : 'Edit Product';
});
`

**Comment by DesignHhuang** [comment]
> **Template**
> 
> <BasicDrawer @register="drawerRegister" :title="getTitle" width="50%" @ok="handleSubmit" @close="handleClose" showFooter :showCancelBtn="false" okText="Submit" > ...... </BasicDrawer>
> 
> **Script**
> 
> let isCreate = ref(true);
> 
> const getTitle = computed(() => { return !unref(isCreate) ? 'Add Product' : 'Edit Product'; });

没有发现你所说的问题额。

**Comment by Changechoice1** [comment]
@DesignHhuang  <BasicDrawer
@register="drawerRegister"
:title="getTitle"
width="50%"
@ok="handleSubmit"
https://github.com/close="handleClose"
showFooter
:showCancelBtn="false"
okText="Submit"
>
......
</BasicDrawer>

Script

let isCreate = ref(true);

const getTitle = computed(() => {
return !unref(isCreate) ? 'Add Product' : 'Edit Product';
});

**Comment by Changechoice1** [comment]
@DesignHhuang

**Comment by Changechoice1** [comment]
@DesignHhuang

**Comment by shijunpeng15** [comment]
我也遇到这样的问题，看了看官方的示例，官方也是这样的问题。下面s是一个动图，展示这个问题的
![PixPin_2023-12-10_12-05-35](https://github.com/vbenjs/vue-vben-admin/assets/46516257/f9b67d7d-e63e-4f02-aec5-8d077feb6066)

**Comment by jiaowoxiaobala** [comment]
> 我也遇到这样的问题，看了看官方的示例，官方也是这样的问题。下面s是一个动图，展示这个问题的 ![PixPin_2023-12-10_12-05-35](https://private-user-images.githubusercontent.com/46516257/289336913-f9b67d7d-e63e-4f02-aec5-8d077feb6066.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODQwNzYsIm5iZiI6MTcwMjI4Mzc3NiwicGF0aCI6Ii80NjUxNjI1Ny8yODkzMzY5MTMtZjliNjdkN2QtZTYzZS00ZjAyLWFlYzUtOGQwNzdmZWI2MDY2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA4MzYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZTg5ZTNkYTdhNzU5MDdjMjZmODY1ZjdkMDY5MWUwMjI4YWU4MmM5MzAyYjRiZjE4Y2ExOGMyZjIxNTU4YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DvxTSDv4d2SvVTgRniXY3hj5Q-dwBmW9uGEoL08UjV0) [ ![PixPin_2023-12-10_12-05-35](https://private-user-images.githubusercontent.com/46516257/289336913-f9b67d7d-e63e-4f02-aec5-8d077feb6066.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODQwNzYsIm5iZiI6MTcwMjI4Mzc3NiwicGF0aCI6Ii80NjUxNjI1Ny8yODkzMzY5MTMtZjliNjdkN2QtZTYzZS00ZjAyLWFlYzUtOGQwNzdmZWI2MDY2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA4MzYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZTg5ZTNkYTdhNzU5MDdjMjZmODY1ZjdkMDY5MWUwMjI4YWU4MmM5MzAyYjRiZjE4Y2ExOGMyZjIxNTU4YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DvxTSDv4d2SvVTgRniXY3hj5Q-dwBmW9uGEoL08UjV0) ](https://private-user-images.githubusercontent.com/46516257/289336913-f9b67d7d-e63e-4f02-aec5-8d077feb6066.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODQwNzYsIm5iZiI6MTcwMjI4Mzc3NiwicGF0aCI6Ii80NjUxNjI1Ny8yODkzMzY5MTMtZjliNjdkN2QtZTYzZS00ZjAyLWFlYzUtOGQwNzdmZWI2MDY2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA4MzYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZTg5ZTNkYTdhNzU5MDdjMjZmODY1ZjdkMDY5MWUwMjI4YWU4MmM5MzAyYjRiZjE4Y2ExOGMyZjIxNTU4YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DvxTSDv4d2SvVTgRniXY3hj5Q-dwBmW9uGEoL08UjV0) [ ](https://private-user-images.githubusercontent.com/46516257/289336913-f9b67d7d-e63e-4f02-aec5-8d077feb6066.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODQwNzYsIm5iZiI6MTcwMjI4Mzc3NiwicGF0aCI6Ii80NjUxNjI1Ny8yODkzMzY5MTMtZjliNjdkN2QtZTYzZS00ZjAyLWFlYzUtOGQwNzdmZWI2MDY2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA4MzYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZTg5ZTNkYTdhNzU5MDdjMjZmODY1ZjdkMDY5MWUwMjI4YWU4MmM5MzAyYjRiZjE4Y2ExOGMyZjIxNTU4YmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DvxTSDv4d2SvVTgRniXY3hj5Q-dwBmW9uGEoL08UjV0)

@shijunpeng15 已提PR修复
