### ISSUE TITLE
thin版无法启动

### ISSUE THREAD

**Issue by SihuiHu6** [vbenjs/vue-vben-admin#3259]
git clone https://github.com/anncwb/vue-vben-admin.git      正常
git branch thin     正常
pnpm install         正常
pnpm serve          报错
`
 ERROR  error when starting dev server:  Error: read ECONNRESET at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
`

pnpm -v       8.9.2
node -v         v18.17.1

main 版本启动正常

**Comment by likui628** [comment]
thin分支目前没人维护了
