### ISSUE TITLE
如何头部不刷新内容，左侧菜单刷新内容

### ISSUE THREAD

**Issue by zj1312114390** [vbenjs/vue-vben-admin#3262]
![f5b2f1bf870a3e249a86c146d21fc07](https://github.com/vbenjs/vue-vben-admin/assets/110399274/4ade7792-de08-43f0-b1d1-b9a20495008f)

头部tab不刷新内容，右侧的刷新按钮才会刷新

**Comment by wangjue666** [comment]
@zj1312114390  能否详细描述下你的需求？

**Comment by wangjue666** [comment]
已经有刷新当前页面的功能，你就给左侧菜单点击后，额外增加个执行刷新页面的函数
