### ISSUE TITLE
vben3的preview组件为什么会请求两次图片地址 

### ISSUE THREAD

**Issue by dengdai11201** [vbenjs/vue-vben-admin#3267]
近日在使用preview组件时（采用无预览图方法），imgList中自定义了图片地址，实际中在点击打开预览时，图片会请求两次（甚至关闭预览都会请求一次）,而看请求结果常常时第一次成功而第二次失败，然后整个图片就无法展示，请大佬帮忙看看这个问题。
![20231109-161009](https://github.com/vbenjs/vue-vben-admin/assets/132820822/2a452bc9-f97f-49e9-b4f2-770889097cc9)
报错内容是rpc error: code = Internal desc = unexpected EOF；
代码如下：
`<div>`
`<Tooltip placement="rightTop" title="图片预览" @click="handlePreview" >`
`<Icon style="margin-right: 4px" icon="ant-design:chrome-filled" size="24px" class="iconStyle"/>`
`</Tooltip>`
`</div>`
`export default defineComponent({
    name: 'imgPreview',
    components: { Icon, Tooltip, Image },
    props: ['taskInfo'],
    setup(props) {
        let imgList: string[]=[];
        async function handlePreview() {
            imgList=[
                // 'https://picsum.photos/id/66/346/216',
                `/track/tile/point_img?tile_id=0&tile_branch=${props.taskInfo.tile_branch}&trail_id=0&type=260&task_id=TO${props.taskInfo.id}`
            ];
            await createImgPreview({ imageList: imgList,defaultWidth:500,maskClosable:true});
        }
        return { handlePreview };
    },
});`

**Comment by wangjue666** [comment]
@dengdai11201  你要提供一个我能复现的代码， 传递的props是个啥呀

**Comment by dengdai11201** [comment]
@wangjue666 这个我直接复制官网的示例内容也会有多次请求的情况，感觉是内部逻辑的问题

**Comment by wangjue666** [comment]
@dengdai11201  不是的 因为官网demo的访问图片的链接被重定向了 

![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/acca320d-6972-4f71-9b2c-1ecd34f53e48)


> @wangjue666 这个我直接复制官网的示例内容也会有多次请求的情况，感觉是内部逻辑的问题

**Comment by dengdai11201** [comment]
@wangjue666 我用的官网示例，这里点击预览，是请求了两次的（是因为重定向吗？），大佬你那里只有一次请求吗？
![20231110-113802](https://github.com/vbenjs/vue-vben-admin/assets/132820822/1cb74cbc-3f8a-46d8-b5e9-a871db31b8e9)

**Comment by wangjue666** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/bc3df995-eb59-467e-bc24-68ba56ec1928)

这不是正好两次重定向 你换个图片链接测试好了

**Comment by dengdai11201** [comment]
@wangjue666 这里我换成了自己要用的图片链接http://hdmap-go-service-dev-cell0np.inner.chj.cloud/api/v1/tile/point_img?tile_id=0&tile_branch=tile_branch_2023_11_09_01_06_01_113081628066215937_0&trail_id=0&type=260&task_id=TO98158
没看见有重定向，但也请求了两次（第一次成功，第二次失败），由于没有都请求成功，所以没看到预览图
![20231110-113802](https://github.com/vbenjs/vue-vben-admin/assets/132820822/bd3c7c86-9de5-4bf3-8287-fa0652568625)

**Comment by wangjue666** [comment]
你的这个图片链接 放到浏览器就是无法正常打开

**Comment by dengdai11201** [comment]
图里那个第一条请求，返回黑乎乎的就是正确的图片

**Comment by wangjue666** [comment]
https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png  你换成这个图片试试

**Comment by dengdai11201** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/132820822/643d0ee9-dea1-43b6-9e73-ed5ebbc435a8)
大佬，这个可以请求成功，但也是请求了两次，我想知道为什么要请求两次（甚至关闭预览也会请求一次），每次请求的作用是什么

**Comment by wangjue666** [comment]
你说的两次请求我复现不了， 这样吧你直接使用 antd的image组件测试正常不 https://www.antdv.com/components/image-cn

**Comment by dengdai11201** [comment]
我用image组件组件试过，请求只有一次，使用preview时才会出现两次请求
