### ISSUE TITLE
表单设计器

### ISSUE THREAD

**Issue by hehepeng** [vbenjs/vue-vben-admin#3268]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug
表单设计，拖拽左侧组件到容器后，右侧的配置内容不显示，去掉绝对定位后，显示了，但是部分组件无法显示
A clear and concise description of what the bug is..

![image](https://github.com/vbenjs/vue-vben-admin/assets/23272117/c65c6e39-917f-464c-b462-1b5d1e6a47e9)

还有滑动高度也有问题，默认的height: calc(100% - 50px);但是内容无法滚动 
### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System: window11
- Node version: 18.14.2
- Package manager (npm/yarn/pnpm) and version: pnpm:8.8.0

**Comment by HughCodeX** [comment]
我定位到问题出现在哪里了, 今天或者明天将会提交pr

**Comment by HughCodeX** [comment]
fix in #3300
