### ISSUE TITLE
更新到4.0.6 DatePicker 国际化失效了？看官方有人提issue

### ISSUE THREAD

**Issue by zwtvip** [vbenjs/vue-vben-admin#3272]
![1699635011738](https://github.com/vbenjs/vue-vben-admin/assets/29778465/eb535da8-bed0-458f-adb2-cce707926596)

**Comment by JunFanChen** [comment]
我也遇到同样的问题，请问怎么解决？

**Comment by zwtvip** [comment]
> 我也遇到同样的问题，请问如何解决？

我提了pr 你看下

**Comment by wang-cola** [comment]
> > 我也遇到同样的问题，请问如何解决？
> 
> 我提了pr 你看下

你好层主，我想问一下，你已经用了这个项目了，最开始是用git clone去用的，那本项目更新了之后，你是怎么更新自己的项目的呢

**Comment by zwtvip** [comment]
文档有说明








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年4月16日(周二) 晚上7:10写道:

  

   
我也遇到同样的问题，请问如何解决？
  
我提了pr 你看下
  
你好层主，我想问一下，你已经用了这个项目了，最开始是用git clone去用的，那本项目更新了之后，你是怎么更新自己的项目的呢
