### ISSUE TITLE
Websocket:  The client is unable to receive a message when another client sends one

### ISSUE THREAD

**Issue by doraemonxxx** [vbenjs/vue-vben-admin#3275]
I opened the app on Google Chrome (User 1) and Firefox (User 2). When attempting to send a message from User 1, User 2 failed to receive the message.

Am I missing something with the websocket?

Thank you!

**Comment by Jzow** [comment]
This usually requires you to directly implement it, and I recommend using message queue technology for implementation. Of course, the front-end also requires websocket monitoring
