### ISSUE TITLE
抽屉组件滚动条bug

### ISSUE THREAD

**Issue by lixiaolong117** [vbenjs/vue-vben-admin#3279]
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/b71a40de-2c21-4adb-a197-8ae6985dd348)

抽屉组件（打开Drawer并传递数据）内滚动条拉到最下面，但是下面还是有一块区域显示不出来。

**Comment by jiaowoxiaobala** [comment]
看着像是内部容器写了固定高度+`overflow-y: auto`，去掉试试

**Comment by lixiaolong117** [comment]
没有写固定高度，很奇怪，你能帮忙试一下吗？

**Comment by HughCodeX** [comment]
看着像是你这个表单的固定高度超过了表单内容的高度导致滚动条没有完全覆盖。能否给个测试用例方便复现问题呢?

**Comment by jiaowoxiaobala** [comment]
> 没有写固定高度，很奇怪，你能帮忙试一下吗？

 给个代码看看

**Comment by anncwb** [comment]
Hello @lixiaolong117. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by lixiaolong117** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/8656d0dd-0aa9-4c96-afbb-b7cb86fea8d9)

**Comment by jiaowoxiaobala** [comment]
> ![image](https://user-images.githubusercontent.com/73454983/283653398-8656d0dd-0aa9-4c96-afbb-b7cb86fea8d9.png)

渲染的动态组件的外层容器是不是写死了固定高度

**Comment by lixiaolong117** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/73454983/1ce1ab42-24c1-44cc-a7c2-ceabc9565cc2)
红框区域是个小的滚动窗口，这个窗口的下边被遮挡了一部分

**Comment by jiaowoxiaobala** [comment]
> ![image](https://user-images.githubusercontent.com/73454983/283988111-1ce1ab42-24c1-44cc-a7c2-ceabc9565cc2.png) 红框区域是个小的滚动窗口，这个窗口的下边被遮挡了一部分

这个红色区域不写死固定高度就可以了

**Comment by lixiaolong117** [comment]
找到问题原因了，谢谢，不是bug，是代码问题。
