### ISSUE TITLE
mac 运行和大包 报错 DEP0040

### ISSUE THREAD

**Issue by bigbrid** [vbenjs/vue-vben-admin#3280]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
mac 本地运行,打包控制台有一条错误信息

 ERROR  (node:26902) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

请清晰地描述此 Bug 的具体表现。

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- mac
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by wangjue666** [comment]
@bigbrid node 版本多少

**Comment by anncwb** [comment]
Hello @bigbrid. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by bigbrid** [comment]
用nvm安装的node版本

**Comment by bigbrid** [comment]
用nvm安装的node 20.9.0 
执行 dev和build 
控制台先提示
ERROR (node:26902) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.
(Use node --trace-deprecation ... to show where the warning was created)

然后会运行成功或打包成功

**Comment by wangjue666** [comment]
就是说 首次执行指令会报错 但是第二次就成功 对吗？
