### ISSUE TITLE
给table表格设置useSearchForm为true时，再次打开能加个清空form的api吗

### ISSUE THREAD

**Issue by hou-zhe** [vbenjs/vue-vben-admin#3282]
### 在抽屉drawer或者modal弹窗中嵌套了table表格，并且打开了form，form的数据怎么清空

能不能添加个api或者有什么别的方法吗

![image](https://github.com/vbenjs/vue-vben-admin/assets/56286640/2c9f035f-f016-4d57-bbc8-3be2a25a7665)
![image](https://github.com/vbenjs/vue-vben-admin/assets/56286640/8f65da55-ff9c-4e4b-aca5-76181a0b4be8)
![image](https://github.com/vbenjs/vue-vben-admin/assets/56286640/c1c4210b-e463-4924-bdd1-5c658a3ac04e)

**Comment by wangjue666** [comment]
getform这个函数里头有 reset方法，去仔细过一遍文档吧

**Comment by hou-zhe** [comment]
> getform这个函数里头有reset方法，仔细看一遍文档吧

hhh, 可以通过该函数获取表单对象函数进行操作，好吧，没往这方面想，原来打印出来getform就有了
<img width="285" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/56286640/9ea9a50a-c7d4-4ea9-a80e-a85435becaf9">
感谢！！
