### ISSUE TITLE
对象使用方括号方式取属性值，ts类型检查报错

### ISSUE THREAD

**Issue by yyTopfine** [vbenjs/vue-vben-admin#3289]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

src/utils/env.ts第32行代码报：元素隐式具有 "any" 类型，因为索引表达式的类型不为 "number"。ts(7015)错误

### 复现 Bug
建议对ENV_NAME 做类型断言，代码：
const ENV = import.meta.env.DEV
    ? (import.meta.env as unknown as GlobEnvConfig)
    : (window[ENV_NAME as keyof Window] as unknown as GlobEnvConfig)

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by jiaowoxiaobala** [comment]
拉下最新代码，看代码之前是直接断言`any`了
