### ISSUE TITLE
是否考虑逐步将setup语法重构为script setup

### ISSUE THREAD

**Issue by xingyuv** [vbenjs/vue-vben-admin#3291]
优势
1. 减少页面代码量，例如defineComponent、return等
2. 引入的组件可以直接使用，无需通过components进行注册
3. defineProps、defineEmits、defineExpose、defineOptions 等也更直观方便
4. 增加代码可阅读性

**Comment by wangjue666** [comment]
可以呀, 先考虑一些demo类的组件，  欢迎PR,
