### ISSUE TITLE
VFormDesign组件用到的过程中的报错

### ISSUE THREAD

**Issue by datasre** [vbenjs/vue-vben-admin#3304]
![image](https://github.com/vbenjs/vue-vben-admin/assets/54182063/0a5b8d0a-7776-4e46-9966-713d91dba057)

这个位置若找不到则idx为-1，此时判断if(idx)也为true进入到了判断里面就报错了

**Comment by wangjue666** [comment]
@datasre  是的，你可以提个pr修复他

**Comment by datasre** [comment]
bug已修复
