### ISSUE TITLE
项目在route_mapping的权限模式下，路由鉴权的问题

### ISSUE THREAD

**Issue by Nick955** [vbenjs/vue-vben-admin#3311]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

在route__mapping的权限模式下，配置了路由中ignoreAuth为true
<img width="1003" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/49111166/10d97b5b-7f29-45c9-916f-665b9b31affe">

也不能正常进入该路由。原因是此时还未构建好菜单，无法鉴权，即无法直接进入不需要权限的页面
![image](https://github.com/vbenjs/vue-vben-admin/assets/49111166/39a94444-23b5-400e-8cc4-8b41b5ff5d25)

### Reproduction

1. `src/settings/projectSetting.ts`里配置permissionMode为PermissionModeEnum.ROUTE_MAPPING模式
2. `src/router/routes/modules`中的`about.ts`中配置index路由的meta对象ignoreAuth为true

## System Info

- Operating System: Mac Pro 18
- Node version: 16.14
- Package manager (npm/yarn/pnpm) and version: 8.11

**Comment by DesignHhuang** [comment]
你好，你的复现过程是什么？用的什么权限的账号？在route__mapping的权限模式即使什么都不设置，关于页面是直接可以进去的啊。 还有，你设置ignoreAuth为true在父路由上也要设置吧，不只是在children中设置吧。

**Comment by Nick955** [comment]
请问跟账号的权限是有关系吗，route_mapping模式下要先登录才能鉴权吗

我的操作步骤就是
1. 先将父路由和对应的子路由设置了的ignoreAuth为true
<img width="1311" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/49111166/3e5962a3-4e96-4fbb-b60d-3491961fa2fe">

2. 在不登录的情况下，通过地址栏直接跳转到我设置了ignoreAuth为true的子路由about/index
![image](https://github.com/vbenjs/vue-vben-admin/assets/49111166/3dbf7726-090d-4f04-9a39-400664e7e251)

3. 此时路由守卫拿不到我路由设置的meta信息，会重定向到登录页，也就是无法绕过登录，直接进入对应的子路由
![image](https://github.com/vbenjs/vue-vben-admin/assets/49111166/13cb4a4b-ad6b-471b-9a58-9e13cd2216c8)

**Comment by DesignHhuang** [comment]
> 请问跟账号的权限是有关系吗，route_mapping模式下要先登录才能鉴权吗
> 
> 我的操作步骤就是
> 
> 1. 先将父路由和对应的子路由设置了的ignoreAuth为true
> 
> <img alt="image" width="1311" src="https://user-images.githubusercontent.com/49111166/285113786-3e5962a3-4e96-4fbb-b60d-3491961fa2fe.png">
> 2. 在不登录的情况下，通过地址栏直接跳转到我设置了ignoreAuth为true的子路由about/index
>    ![image](https://user-images.githubusercontent.com/49111166/285114630-3dbf7726-090d-4f04-9a39-400664e7e251.png)
> 3. 此时路由守卫拿不到我路由设置的meta信息，会重定向到登录页，也就是无法绕过登录，直接进入对应的子路由
>    ![image](https://user-images.githubusercontent.com/49111166/285114829-13cb4a4b-ad6b-471b-9a58-9e13cd2216c8.png)

ok，我明白你的意思了，我看一下

**Comment by DesignHhuang** [comment]
@Nick955  原因：因为about页面是asyncRoutes，所以逻辑上需要登录的状态下才能看到（因为它带有layout信息，比如sidebar,header，multipletab等等）。它并不是一个外部页面，所有不适合直接访问。
![image](https://github.com/vbenjs/vue-vben-admin/assets/3368397/eea45299-4a97-4f51-81df-e3f2f77cefaf)
结局办法：
方案1： 你可以将about抽成单独的外部页面（如main-out页面）。
方案2：你可以将about加入基础页面，使它能够正常访问，做如下改动
![image](https://github.com/vbenjs/vue-vben-admin/assets/3368397/a4fd6e97-0315-4948-b985-27a04307c91f)
这样它可以直接不登录访问。但是点击sidebar中的其他菜单还是需要去登录的，他们都是异步路由。

不知道我说的清不清楚，以上内容希望可以帮助到你。

**Comment by Nick955** [comment]
好的，感谢回答，也就是说异步路由配置ignoreAuth其实就是无效的，只能配置好移入到basicRoutes里才可以实现不登录访问
