### ISSUE TITLE
谁改出问题了，/src/views/demo/form/RefForm.vue 通过ref 拿不到表单实例了

### ISSUE THREAD

**Issue by zwtvip** [vbenjs/vue-vben-admin#3313]
![image](https://github.com/vbenjs/vue-vben-admin/assets/29778465/d56e4545-f94c-48c9-9e8e-bc419fcbe449)

**Comment by sugar258596** [comment]
贴代码

**Comment by wangjue666** [comment]
@zwtvip 试着回滚下调试看看
