### ISSUE TITLE
node18.18 / node16.20 docker镜像中编译vben框架的vue前端代码，pnpm install 报错： @vben/eslint-config@workspace:*: Workspace not found 

### ISSUE THREAD

**Issue by bigbenz** [vbenjs/vue-vben-admin#3314]
- Operating System:
-   Nodejs的Docker :: FROM node:16.20 as build-stage
- Node version:
- Package manager (npm/yarn/pnpm) and version:
- nodejs 18.18
- pnpm 8.10.5
- yarn  1.22.19

ERROR MSG : 
Step 10/18 : RUN pnpm install
 ---> Running in cc66b57d5bf2
Progress: resolved 1, reused 0, downloaded 0, added 0
Progress: resolved 17, reused 0, downloaded 14, added 0
Progress: resolved 35, reused 0, downloaded 23, added 0
Progress: resolved 58, reused 0, downloaded 45, added 0
 ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@vben/eslint-config@workspace:*" is in the dependencies but no package named "@vben/eslint-config" is present in the workspace
This error happened while installing a direct dependency of /home/wms-web/projects/ep-wms-web

**Comment by wangjue666** [comment]
@bigbenz  是拉取的最新版本的仓库代码吗

**Comment by wangjue666** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/3dd8253a-2a78-4cf1-a129-c7eda1d42130)

ci构建也这俩版本呢，而且打包没有问题

**Comment by wangjue666** [comment]
尝试重新运行下` pnpm install`

**Comment by bigbenz** [comment]
> ![image](https://user-images.githubusercontent.com/24707417/284767177-3dd8253a-2a78-4cf1-a129-c7eda1d42130.png)
> 
> ci构建也这俩版本呢，而且打包没有问题

您是直接拉取的node18的docker镜像在容器里面编译的吗

**Comment by bigbenz** [comment]
![Uploading error2.png…]()

**Comment by bigbenz** [comment]
package.json 里面 写 
    "@vben/hooks": "workspace:*",
   workspace:* 相关的都无法被识别，是因为写法的问题吗

**Comment by wangjue666** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/54d7a409-887d-465c-87b7-99a83f6ab8cc)

这俩差不多 ci是运行在 unbuntu 上

**Comment by bigbenz** [comment]
> ![image](https://user-images.githubusercontent.com/24707417/284769026-54d7a409-887d-465c-87b7-99a83f6ab8cc.png)
> 
> 这俩差不多 ci是运行在 unbuntu 上

我也是CI gitlab-runner 去跑的编译，请问下 "@vben/hooks": "workspace:", 这种写法是从哪边去拉取的依赖呢?

**Comment by wangjue666** [comment]
> package.json 里面 写 "@vben/hooks": "workspace:_", workspace:_ 相关的都无法被识别，是因为写法的问题吗

这个是pnpm monorepo写法 看样子pnpm不识别， 你再核实下是打包的文件是否完整， 有没有 `packages` 这个文件夹

**Comment by bigbenz** [comment]
> unbuntu
您跑CI的系统是不是已经安装了node环境？

**Comment by wangjue666** [comment]
你在本地电脑上运行正常不

**Comment by bigbenz** [comment]
> 是否



> 你在本地电脑上运行正常不

正常的，现在集成到gitlab-runner 自动化编译有问题，我再去看看脚本吧 谢谢

**Comment by wangmingzhitu** [comment]
@bigbenz  ,问题解决了吗，我在本地也是可以，但是jenkins编译提示Workspace的错误

**Comment by Jzow** [comment]
```shell
PS E:\opensource\flow\flow-admin-ui> pnpm install
 ERR_PNPM_WORKSPACE_PKG_NOT_FOUND  In : "@vben/stylelint-config@workspace:*" is in the dependencies but no package named "@vben/stylelint-config" is present in the workspace

This error happened while installing a direct dependency of E:\opensource\flow\flow-admin-ui

Packages found in the workspace:
Progress: resolved 0, reused 1, downloaded 0, added 0
```

请问解决了吗 使用 pnpm install 还是这个错误

**Comment by kankantian** [comment]
看看是不是删掉了根目录下的pnpm-workspace.yaml文件

**Comment by kankantian** [comment]
> 看看是不是删掉了根目录下的pnpm-workspace.yaml文件
