### ISSUE TITLE
Uncaught TypeError: Cannot destructure property 'VITE_GLOB_APP_TITLE' of 't' as it is undefined.

### ISSUE THREAD

**Issue by bihell** [vbenjs/vue-vben-admin#3317]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

太诡异了，以前出现过，但是这次真是环境又出现了，我对比了一下最近的源码，没有什么不同，完全不知道哪里错了

### 复现 Bug

pnpm preview

## 系统信息

- 操作系统: macOS 14.1.1 (23B81)
- Node 版本: v18.17.1
- 包管理器 (npm/yarn/pnpm) 及其版本: 8.9.2

<img width="1728" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/19926035/a127ba46-2967-461d-a147-0428e2d38b80">

**Comment by bihell** [comment]
补一下我的代码地址 ：https://github.com/bihell/Dice

**Comment by xingyuv** [comment]
(window[ENV_NAME] as unknown as GlobEnvConfig)

应该是这里的问题
