### ISSUE TITLE
View页面来换切换后会有空白页。

### ISSUE THREAD

**Issue by luqizheng** [vbenjs/vue-vben-admin#3322]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
假设A页面 是 在 template 后 第一行是 注释。

 先到 B 正常显示，B 切换到 A 页面 正常显示，再切换到B 空白页面。 

出现Bug的A页面如下 
```
<template>
<!-- name: 这个是注释引发错误 -->
  <PageWrapper title="A-Page">
    
   <h3> 我是A页面</h3>
  </PageWrapper>
</template>
<script lang="ts">
  import { PageWrapper } from '/@/components/Page';

  export default {
    components: { PageWrapper },
  };
</script>
```

这是B页面
```
<template>
  <PageWrapper title="我是B-page">
    
   <h3> 我是B页面</h3>
  </PageWrapper>
</template>
<script lang="ts">
  import { PageWrapper } from '/@/components/Page';

  export default {
    components: { PageWrapper },
  };
</script>
```
把A页面注释去除后，就正常，如下
```
<template>

  <PageWrapper title="A-Page">
    
   <h3> 我A页面</h3>
  </PageWrapper>
</template>
<script lang="ts">
  import { PageWrapper } from '/@/components/Page';

  export default {
    components: { PageWrapper },
  };
</script>
```

## 系统信息

- 操作系统: win10
- Node 版本: 18.1.16
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 8.6.3

**Comment by likui628** [comment]
最好不要这么做，这样就会导致attrs传递出问题，除非你再去绑定
![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/acac72b4-c55a-43c1-ab97-a71476134b5a)
[vue playground](https://play.vuejs.org/#eNp9krFOwzAQhl/FeClITSPUrU0rAaoEDIAAicVLlFzTFMe2bCcURZkRDDwHO+9Uibfg7LQplYDt7r7f9n++q+mJUoOqBDqikUl0riwxYEs1ZSIvlNSWnMlCkbmWBekNQpc4eW/c8ZpomJNmI3GMCSYSKYwlhcnIxPHD3jlwLsmD1Dw96B0xEYXtc/gQJhYKxWMLmBESLY6nde0PN00UYuaruVClJVVQyBT4hFHkjLbIezT2mQPWE8mlHmlIx4yGyKOwu532qTVobZ5ng6WRAruu3QXuUKFyDvpa2RytMzoinjgWo/OnS1+zuoT+tp4sIHn8pb40K1dj9EaDAV0Box2zsc7Atnh2dwUrjDuInZUc1f/AWzCSl85jKzstRYq2f+i82ws/m1xk92a2siDMtiln1Ckbr2cU5+U+76/Wd3aHg6E/x0SDv7jdA7c2u9lp/OyDIIjSvJquPz++Xt7W769R6NIgaLGLXRDHPvWsjfav2d9FL9jsC22+AT2e6ug=)

![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/2fb6af78-8fb9-4e0e-896a-8296cc399247)

**Comment by Y-Yin** [comment]
感谢， 终于找到问题所在了
