### ISSUE TITLE
DatePicker 日期展示错误

### ISSUE THREAD

**Issue by CruxCv** [vbenjs/vue-vben-admin#3323]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

问题如题
![image](https://github.com/vbenjs/vue-vben-admin/assets/26268758/56139f5a-0f07-483e-b53e-c02f6a77fc76)

查看官方展示demo也有这个问题
<img width="1504" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/26268758/666cd07a-77ba-4f6e-a0e7-ff22c8e1a864">

### 复现 Bug

-

## 系统信息

- 操作系统: mac
- Node 版本: v16.17.0
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 8.7.6

**Comment by likui628** [comment]
会不会是antdv的问题

**Comment by zwtvip** [comment]
已修复，已提pr
