### ISSUE TITLE
ApiSelect tagRender插槽无效

### ISSUE THREAD

**Issue by guilunmei** [vbenjs/vue-vben-admin#3347]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by jiaowoxiaobala** [comment]
`mode`为`multiple`或`tags`吗

**Comment by guilunmei** [comment]
<template #moudleSlot="{ model, field }">
            <ApiSelect
              :api="getModules"
              showSearch
              v-model:value="model[field]"
              resultField="rows"
              valueField="id"
              labelField="chineseName"
              mode="tag"
              @change="
                (e, option) =>
                  setFieldsValue({ moduleName: option.label, moduleNameEn: option.name })
              "
            >
              <template #option="{ label, name }">{{ label }} [ {{ name }} ]</template>
              <template #tagRender="{ value: val, label, closable, onClose, option }">
                <Tag :closable="closable" style="margin-right: 3px" @close="onClose">
                  {{ label }}&nbsp;&nbsp;
                  <span role="img" :aria-label="val">{{ option.name }}</span>
                </Tag>
              </template>
            </ApiSelect>
          </template>
