### ISSUE TITLE
dev 模式下 访问本地 public 中的 html 文件被路由重定向到404页面

### ISSUE THREAD

**Issue by ljb2458** [vbenjs/vue-vben-admin#3349]
目标文件：
public/resource/xxx.html

```html
<iframe src="resource/charting_library/static/xxx.html#hashxxx"/>
```

![image](https://github.com/vbenjs/vue-vben-admin/assets/101191648/795e70c7-8598-4daf-91b6-9df142d968d2)

这个文件是真实存在的！

![image](https://github.com/vbenjs/vue-vben-admin/assets/101191648/a512061c-717f-41ae-b948-65f16462ddf7)

**Comment by wangjue666** [comment]
https://github.com/vbenjs/vue-vben-admin/issues/1822 请参考这个issue

**Comment by wangjue666** [comment]
@ljb2458 你可以在本地起个静态服务器过渡下，这个问题生产环境下不会出现

**Comment by ljb2458** [comment]
@wangjue666  因为 html 文件的特殊性，得是同源的。关于这个问题，能否给我一些可能造成的原因呢？或许我在解决后可以给你们方案，我已经尝试了一整天了！

**Comment by ljb2458** [comment]
@wangjue666 我使用  --disable-web-security --user-data-dir=D:\temp, 参数启动浏览器进行调试，避开了开发环境的跨域问题！那么我要关闭 issues 了
