### ISSUE TITLE
2023年11月30日 访问项目预览地址全都失效，包括文档地址

### ISSUE THREAD

**Issue by cMing1997** [vbenjs/vue-vben-admin#3365]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

项目中所能提供的预览地址 全部访问失效`（访问其他网站很流畅）
![image](https://github.com/vbenjs/vue-vben-admin/assets/40878104/d66f8ce0-8fe4-425e-94a6-3abe4ba5708f)
![image](https://github.com/vbenjs/vue-vben-admin/assets/40878104/e62d9a81-3cb2-441b-b32c-cf8f17d28e06)
![image](https://github.com/vbenjs/vue-vben-admin/assets/40878104/66a5f13e-4fba-4fc7-bdf2-b71e5f9cf296)
![image](https://github.com/vbenjs/vue-vben-admin/assets/40878104/2495d893-ea3a-48db-b0cd-61b2ffc72fcc)
![image](https://github.com/vbenjs/vue-vben-admin/assets/40878104/507ddd7a-9d8f-4869-97c6-53aa71ee0bf6)
![image](https://github.com/vbenjs/vue-vben-admin/assets/40878104/e49b401b-2384-41de-ac6b-201bea2b4400)

### 复现 Bug
无

## 系统信息
略

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by sugar258596** [comment]
@cMing1997 现在是北京时间2023-12-1-8:28  。文档地址正常
![image](https://github.com/vbenjs/vue-vben-admin/assets/84883966/b1e97112-d2eb-4db8-a91d-e8de8411884f)

**Comment by cMing1997** [comment]
> @cMing1997 现在是北京时间2023-12-1-8:28 。文档地址正常 ![image](https://private-user-images.githubusercontent.com/84883966/287106113-b1e97112-d2eb-4db8-a91d-e8de8411884f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzOTU2MDgsIm5iZiI6MTcwMTM5NTMwOCwicGF0aCI6Ii84NDg4Mzk2Ni8yODcxMDYxMTMtYjFlOTcxMTItZDJlYi00ZGI4LWE5MWQtZThkZTg0MTE4ODRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDAxNDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMjYwODUzZTllMjk3Y2Y2NjUxMWM2MTdlMTUxZjUyZmQ1ODUzODM2ZjlhYzFkZjMxOWRhNWFhNWRiZGMzNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Qev1GOcu5e7Vm2tuMsh2R4AkRANFoG5LRenjQiFUq8)

使用的网络是武汉电信 不能打开，但是移动的是可以的，不知道是不是提供部署服务的网络服务商将武汉电信的屏蔽了还是怎么

**Comment by xdj0516** [comment]
同武汉电信 不能打开

**Comment by tchlexder** [comment]
预览的页面好像全挂了

**Comment by cMing1997** [comment]
经过测试，走欧美ip的 是可以访问的，但是走亚洲这边是不行的

**Comment by phphy** [comment]
预览站上海还是404

**Comment by wangjue666** [comment]
> 是需要等一会儿再访问嘛？现在时间 2023-12-04 14:17:01 访问还是一样

额，我也是前天测试访问不了的，但是什么都没进行操作, 刚刚访问突然正常了，问了下金毛大佬应该是gitpage的问题，你要着急的话 项目先拉到本地预览吧

**Comment by cMing1997** [comment]
2023年12月15号 下午三点16分 在线预览可以打开，暂时关闭这个 issues
