### ISSUE TITLE
ApiSelect param参数没有发生变化 重复发送请求

### ISSUE THREAD

**Issue by guilunmei** [vbenjs/vue-vben-admin#3379]
### 描述 Bug

ApiSelect 组件本身 change 会触发api重复请求，配置的参数值是其他表单项 并没有发生变化 

### 复现 Bug

<img width="1920" alt="企业微信截图_20231205141444" src="https://github.com/vbenjs/vue-vben-admin/assets/23629665/5100442e-8852-4c78-899c-d69412da20b1">

## 系统信息

- 操作系统:
- Node 版本:18.18.2
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm 8.9.0

**Comment by wangjue666** [comment]
@guilunmei  这个问题修复了https://github.com/vbenjs/vue-vben-admin/commit/ccf4027533d2adabd21bade025ca7bc7d34d75f6  

原因在于 watch 不能直接监听params普通对象数据，因为每次触发组件更新， 每次绑定的对象都是个新对象，`{} != {}`.  在使用schema动态表达格式的话， params会变成`ref`对象，不会存在这样的问题

![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/96e914ed-0e76-407c-a38d-7f03c00ab80c)
