### ISSUE TITLE
Tab切换页面，页面内容无刷新请求

### ISSUE THREAD

**Issue by zj1312114390** [vbenjs/vue-vben-admin#3380]
我想问一下为什么Tab有的可以刷新页面，有的不能刷新页面，请问是缺了什么
![5ef3686a7b2c6bc251265e42983945eb](https://github.com/vbenjs/vue-vben-admin/assets/110399274/a61e80be-fb1d-4cb3-aa2c-80672498de02)

**Comment by zj1312114390** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/110399274/15e69189-b73b-4570-b5df-af6efcdb0605)
加了这个then就可以刷新了，但是我另外一个项目没有这个then也能刷新，没找到具体原因

**Comment by wangjue666** [comment]
看路由是否开启了keep-alive， 并且组件与路由名字是否一致
