### ISSUE TITLE
模态框内表格的分页

### ISSUE THREAD

**Issue by zj1312114390** [vbenjs/vue-vben-admin#3381]
第一次打开组织机构模态框时modal的下拉不下来，也看不见分页的信息
![image](https://github.com/vbenjs/vue-vben-admin/assets/110399274/837d50ca-030d-48c6-b41d-4a3ab2f66659)
第二次再打开时只有表格的请求(没有左边BasicTree的刷新)，modal的下拉可以下拉，但是还是不见分页信息
![image](https://github.com/vbenjs/vue-vben-admin/assets/110399274/9c0e38dd-a0ed-4463-848a-2c56cc8ceffb)

**Comment by wangjue666** [comment]
表格高度设置下 这是布局问题吧

**Comment by zj1312114390** [comment]
> 表格高度设置下 这是布局问题吧

设置了高度分页出来了，想问一下就是进入这个模态框之前的查询条件如何清除，而且选中了左侧的树结构其中一个，下次打开还是这些查询条件

**Comment by wangjue666** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/24707417/48746c1e-e3ed-4d86-8183-6888c0778186)

看antd的modal文档
