### ISSUE TITLE
BasicTree组件树节点点击传参问题 

### ISSUE THREAD

**Issue by zqxxjs** [vbenjs/vue-vben-admin#3396]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [是] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [是 ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [是 ] 已在 Issues 中搜索了相关的关键词
- [是] 不是 ant design vue 组件库的 Bug

### 描述 Bug
对接项目时发现部门管理页面传参有问题，奇数次点击树节点可以正常传参，偶数次传参为空字符串
### 复现 Bug
就在刚刚，拉取GitHub最新代码不做任何修改 ，仅执行 pnpm install 和 pnpm run dev 命令,打开本地地址后确认代码又bug
<img width="1259" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/125987992/3c335c47-bc51-4009-8c13-e470d30db0f2">

## 系统信息

- 操作系统: Win10专业版
- Node 版本: v18.17.1
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm/8.12.0

**Comment by jiaowoxiaobala** [comment]
非bug，节点支持反选

**Comment by jiaowoxiaobala** [comment]
> 嗯，了解了，应该是没考虑到的情形，账号管理页的部门树组件其实不需要考虑反选的，因为它并不需要多选，只需要固定的点击传参就行。我记得有个multiple属性可以开启多选的，能否优化一下？优化成multiple属性为true的时候才需要考虑反选传参。

这里的反选和多选没关系，可以理解成我选中这个部门的节点就搜索这个部门下的数据，取消后就是搜索所有部门
