### ISSUE TITLE
调用validate()方法后updateSchema的值被重置

### ISSUE THREAD

**Issue by quanbisen** [vbenjs/vue-vben-admin#3409]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

useForm的updateSchema更新select组件的options属性，调用useForm的validate()方法后，options选项被清空，应该是重置到最先传入的useForm的schema了

### Reproduction

```typescript
onBeforeMount(async () => {
    // 查询app分支
    const res = await getAppBranch(appId.value);
    const branchOptions = res.items;
    updateSchema([
          {
            field: 'branch',
            componentProps: {
              options: branchOptions,
            },
          },
    ]);
}
```
然后提交的时候调用validate()
```typescript
async function submit() {
      try {
        await setProps({ submitButtonOptions: { loading: true } });
        const values = await validate();
        console.log('values', values);
        await resetFields();
      } catch (e) {
        console.log('validate error', e);
      } finally {
        setProps({ submitButtonOptions: { loading: false } });
      }
}
```

## System Info

- Operating System: 
- Node version: v18.18.2
- Package manager (npm/yarn/pnpm) and version: pnpm:8.9.2

**Comment by xachary** [comment]
@quanbisen 建议fork一下，提供、切个可以重现的分支和示例看看呗。

**Comment by quanbisen** [comment]
> ```ts
> onBeforeMount
> ```

我这边克隆了最新的代码测试，已经无法复现了，可能是我当时代码写的有问题，先关闭了。
