### ISSUE TITLE
请问这是什么vscode的插件或者设置，会把部分文件显示成目录？觉得不习惯，想按正常的文件显示。求解惑！

### ISSUE THREAD

**Issue by xachary** [vbenjs/vue-vben-admin#3424]
### Discussed in https://github.com/vbenjs/vue-vben-admin/discussions/3423

<div type='discussions-op-text'>

<sup>Originally posted by **xachary** December 16, 2023</sup>
![image](https://github.com/vbenjs/vue-vben-admin/assets/16830398/dfdf0677-3036-4de4-964d-63827c2124b5)
</div>

**Comment by wangjue666** [comment]
`.vscode`文件夹下` setting.json` `"explorer.fileNesting.enabled": true,`  改为`false`就好

**Comment by xachary** [comment]
> `.vscode`文件夹下` setting.json` `"explorer.fileNesting.enabled": true,` 改为`false`就好

666
