### ISSUE TITLE
vite 版本升级到 5.x

### ISSUE THREAD

**Issue by wangjue666** [vbenjs/vue-vben-admin#3425]
当前依赖版本为 `4.x`

[vite5 主要变化](https://cn.vitejs.dev/blog/announcing-vite5#main-changes)

**要注意的地方**

> Node.js Support
> Vite no longer supports Node.js 14 / 16 / 17 / 19, which reached its EOL. Node.js 18 / 20+ is now required.

**Comment by xingyuv** [comment]
https://github.com/vbenjs/vue-vben-admin/pull/3465
这个pr抽时间看一下，如果没问题，后面就升级vite，vite有一些依赖版本都升级了

**Comment by wangjue666** [comment]
@xingyuv  ok
