### ISSUE TITLE
getPermCode返回的是什么？

### ISSUE THREAD

**Issue by zj1312114390** [vbenjs/vue-vben-admin#3442]
![image](https://github.com/vbenjs/vue-vben-admin/assets/110399274/83c77d53-7b9a-4609-b187-afe54688b429)
后端返回了动态菜单，现在要做按钮权限，getPermCode是后端返回什么数据呢

**Comment by wangjue666** [comment]
https://vben.vvbin.cn/#/permission/back/btn  切换到后台权限模式看示例
