### ISSUE TITLE
使用 npm run commit 命令的时候提示  npm ERR! Missing script: "lint-staged"

### ISSUE THREAD

**Issue by cMing1997** [vbenjs/vue-vben-admin#3444]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
由于系统中和别人合作，但是不是所有人对 .commitlintrc 这些规范熟悉，所以我就将 .commitlintrc 内的中文对照打开，英文注释，然后使用提示的 `npm run commit` 命令。但是运行之后，提示 
```
npm ERR! Missing script: "lint-staged"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
```

### 复现 Bug
1.  `pnpm install`
2.  修改代码 运行 `npm run commit`

## 系统信息

- 操作系统:  window11
- Node 版本: v21.3.0
- 包管理器 (npm/yarn/pnpm) 及其版本:  
   ```
     npm： 10.2.4  
     pnpm：8.11.0  
     yarn：1.22.21
   ````

**Comment by wangjue666** [comment]
哦你是想关闭 提交校验是吗？

**Comment by wangjue666** [comment]
`.husky` 文件夹删除掉试试

**Comment by cMing1997** [comment]
> 哦你是想关闭 提交校验是吗？

不是的，相反我是希望这个校验成功的，只是运行了之后提示  `npm ERR! Missing script: "lint-staged"` 这个

**Comment by wangjue666** [comment]
你拉下vben的项目 什么都不改动 测试提交下

**Comment by cMing1997** [comment]
> 你拉下vben的项目 什么都不改动 测试提交下

官方的可以

**Comment by cMing1997** [comment]
> 你拉下vben的项目 什么都不改动 测试提交下

我在package.json 的脚本命令中增加 `"lint:lint-staged":"lint-staged",` 才行
