### ISSUE TITLE
Upload组件如何载入已有的文件

### ISSUE THREAD

**Issue by gnyuan** [vbenjs/vue-vben-admin#3448]
```js
  {
    field: 'url',
    label: '上传文件',
    component: 'Upload',
    componentProps: {
      maxSize: 10,
      maxNumber: 5,
      value: () => ["/static/a.pdf"],
    },
    colProps: { span: 8 },
  },
```
想实现的功能是修改某行记录对应的附件，该附件地址从后台返回，设置到`value`中不起作用。

**Comment by gnyuan** [comment]
应该是有另外一个组件展示已上传附件，在那个组件中管理附件的，对吧？

**Comment by gnyuan** [comment]
关闭。仔细看BasicUpload组件

**Comment by wangmingzhitu** [comment]
请问是怎么加载既存文件的，还是不明白，能说明或者粘一下代码吗？

我设置如下：

componentProps: {
        api: null,
        value:['https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png'],
      },

不起作用

**Comment by gnyuan** [comment]
> 请问是怎么加载既存文件的，还是不明白，能说明或者粘一下代码吗？
> 
> 我设置如下：
> 
> componentProps: { api: null, value:['https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png'], },
> 
> 不起作用

Upload组件有个预览，你看看`BasicUpload`这个组件源码就知道了。
![image](https://github.com/vbenjs/vue-vben-admin/assets/6140657/6bc3ca53-5e5d-4129-92ef-caefa699f67e)
