### ISSUE TITLE
table的序号列跑到了最后一列

### ISSUE THREAD

**Issue by ZackLeonardo** [vbenjs/vue-vben-admin#3449]
table的序号列跑到了最后一列（20231221更新后出现了这个问题）

**Comment by Forevery1** [comment]
<img width="1429" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/19872771/92003af8-861a-4a0c-adcc-6867967266dc">
重置下就行

**Comment by ZackLeonardo** [comment]
让用户重置不适合，我写代码重置不是根本解决bug的方式哟

**Comment by xachary** [comment]
> 让用户重置不适合，我写代码重置不是根本解决bug的方式哟

@ZackLeonardo 

目前最新策略是这样的，列设置默认是关闭缓存功能的，目的是首先维持与旧版本的ColumnSetting的使用习惯，以免影响以前使用者的体验。

如果开启关闭，可以参考这里的代码变更记录：
https://github.com/vbenjs/vue-vben-admin/pull/3446

至于，开启了缓存功能后，既然是缓存，进入页面显示的就是缓存的列设置，包括 显示/隐藏、排序、fixed、序号列、rowSelection。一般情况下，交付给客户的版本，基于接口，能显示的列数量是固定的。如果用户设置过了，想重置只能手动点击，这个是使用习惯/方式，需要说明培训（例如界面设置，其实有很多功能都不是一目了然的，可能都需要讲述/培训/尝试），否则，就不应该使用开启缓存的场景了（例如交互/业务设计，列是根据场景动态变化的，应该不合适了）。

而且，在这个基础上，为了应对版本更新导致列的数量和种类发生变化，显示列之前会做一个简单的对比，

https://github.com/vbenjs/vue-vben-admin/blob/main/src/components/Table/src/components/settings/ColumnSetting.vue
"const diff"这个方法，主要就是“remove消失的列、push新出现的列”

所以，我怀疑是不是“push”逻辑有问题，把后增加序号列放到后面去了。

**Comment by xachary** [comment]
> table的序号列跑到了最后一列（20231221更新后出现了这个问题）

能提供一个可复现的fork and branch吗？

@ZackLeonardo

**Comment by YueSeSuiFeng** [comment]
也遇到了，写的table表格界面都是这样的，重置一下可以解决序号会跑到首列，但是只限于当次的，刷新浏览器后序号就又自动跑到后面去了
![image](https://github.com/vbenjs/vue-vben-admin/assets/26158197/ae9156f1-27ba-495a-843c-4e018d38251f)

**Comment by YueSeSuiFeng** [comment]
vben官网在线示例就有这个问题https://vben.vvbin.cn/#/comp/table/customerCell 
![image](https://github.com/vbenjs/vue-vben-admin/assets/26158197/9a55a02e-8fb0-4052-ab15-c625e3bc720a)

**Comment by xachary** [comment]
@YueSeSuiFeng 找到原因了，刚提了个pr，试试看
https://github.com/vbenjs/vue-vben-admin/pull/3463
