### ISSUE TITLE
ApiTreeSelect  接口参数改变 接口无法重新请求

### ISSUE THREAD

**Issue by SanpLee** [vbenjs/vue-vben-admin#3467]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

版本   "version": "2.10.1",
ApiTreeSelect  接口参数改变 接口无法重新请求

文件 src/components/Form/src/components/ApiTreeSelect.vue  

修改了此处才可以

 

 
<img width="737" alt="未命名" src="https://github.com/vbenjs/vue-vben-admin/assets/26083949/4ef541dd-7338-479f-a18b-4c7b111104b6">

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by wangjue666** [comment]
试试这个

https://github.com/vbenjs/vue-vben-admin/blob/cc97f0635438c102b97102a1e0a9d5550961d6fa/src/components/Form/src/components/ApiSelect.vue#L99

**Comment by SanpLee** [comment]
> 试试这个
> 
> https://github.com/vbenjs/vue-vben-admin/blob/cc97f0635438c102b97102a1e0a9d5550961d6fa/src/components/Form/src/components/ApiSelect.vue#L99
这样也可以

**Comment by Bentan95** [comment]
> 试试这个
> 
> https://github.com/vbenjs/vue-vben-admin/blob/cc97f0635438c102b97102a1e0a9d5550961d6fa/src/components/Form/src/components/ApiSelect.vue#L99

大大，这个是bug还是不是，看提问也快一个月了，新版本还没修复
