### ISSUE TITLE
vben上传附件可以打开高拍仪拍照上传吗

### ISSUE THREAD

**Issue by zj1312114390** [vbenjs/vue-vben-admin#3478]
![ee47e739249bd0a7a7eee18f33b79ea](https://github.com/vbenjs/vue-vben-admin/assets/110399274/1eaaa574-ad94-41e5-9598-4bfdc9cf2608)

这个选取文件可以直接打开外联设备拍照后照片显示在上传列表吗

**Comment by wangjue666** [comment]
这跟vben没关系 `浏览器`支持 就能支持
