### ISSUE TITLE
对 Form 组件 设置默认值的传递有一些不解

### ISSUE THREAD

**Issue by cMing1997** [vbenjs/vue-vben-admin#3488]
### Subject of the feature

我看 Form 组件设置默认值存在两种设置 `defaultValue` 以及 `defaultValueObj` ，按理来说应该只需要 `defaultValue`  这一种设置的，组件这一块在设计之初是有什么考究嘛？

**Comment by xachary** [comment]
```js
  function initDefault() {
    const schemas = unref(getSchema);
    const obj: Recordable = {};
    schemas.forEach((item) => {
      const { defaultValue, defaultValueObj } = item;
      const fieldKeys = Object.keys(defaultValueObj || {});
      if (fieldKeys.length) {
        fieldKeys.map((field) => {
          obj[field] = defaultValueObj![field];
          if (formModel[field] === undefined) {
            formModel[field] = defaultValueObj![field];
          }
        });
      }
      if (!isNil(defaultValue)) {
        obj[item.field] = defaultValue;

        if (formModel[item.field] === undefined) {
          formModel[item.field] = defaultValue;
        }
      }
    });
    defaultValueRef.value = cloneDeep(obj);
  }
```

例如默认值取自某个对象obj

那么，下面效果一样，只是后者是从obj里遍历找到对应field的值

```js
defaultValue: obj.A,

defaultValueObj: obj,
```

**Comment by cMing1997** [comment]
> ```js
>   function initDefault() {
>     const schemas = unref(getSchema);
>     const obj: Recordable = {};
>     schemas.forEach((item) => {
>       const { defaultValue, defaultValueObj } = item;
>       const fieldKeys = Object.keys(defaultValueObj || {});
>       if (fieldKeys.length) {
>         fieldKeys.map((field) => {
>           obj[field] = defaultValueObj![field];
>           if (formModel[field] === undefined) {
>             formModel[field] = defaultValueObj![field];
>           }
>         });
>       }
>       if (!isNil(defaultValue)) {
>         obj[item.field] = defaultValue;
> 
>         if (formModel[item.field] === undefined) {
>           formModel[item.field] = defaultValue;
>         }
>       }
>     });
>     defaultValueRef.value = cloneDeep(obj);
>   }
> ```
> 
> 例如默认值取自某个对象obj
> 
> 那么，下面效果一样，只是后者是从obj里遍历找到对应field的值
> 
> ```js
> defaultValue: obj.A,
> 
> defaultValueObj: obj,
> ```

我看了这块的源码，只是觉得如果要设置初始默认值的话，完全可以只需要设置 defaultValue 就可以的，毕竟就算是设置 defaultValueObj 一个表单项里面只能取一个

**Comment by DesignHhuang** [comment]
@cMing1997 
![image](https://github.com/vbenjs/vue-vben-admin/assets/3368397/3e45634b-81aa-493f-aa1d-7f747a27ad2b)
你可以看一下这种例子，用来处理自定义的组件的。
开源项目需要通用（所以设计上意味着要包含多而全的考虑）。
但在实际的项目中很多内容是不需要的 ，是冗余的，这方面可以自己依据项目需求做优化，做最优解。

**Comment by cMing1997** [comment]
> @cMing1997 ![image](https://private-user-images.githubusercontent.com/3368397/294454838-3e45634b-81aa-493f-aa1d-7f747a27ad2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjI2MzEsIm5iZiI6MTcwNDc2MjMzMSwicGF0aCI6Ii8zMzY4Mzk3LzI5NDQ1NDgzOC0zZTQ1NjM0Yi04MWFhLTQ5M2YtYWExZC03Zjc0N2EyN2FkMmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDlUMDEwNTMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDc5ZjVkYTk2OTNjNzAwZDIyOWEwMThjN2Q3NTk1MzZlZGQ0YTliMDJjMDQ2YjUyNDVkY2NjYzhhMTliZjNjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.WzX7C9RagzFJqjaWtgK1-ozcRHGHTIcEuQBmaB9W6CU) 你可以看一下这种例子，用来处理自定义的组件的。 开源项目需要通用（所以设计上意味着要包含多而全的考虑）。 但在实际的项目中很多内容是不需要的 ，是冗余的，这方面可以自己依据项目需求做优化，做最优解。

举得这个例子那我懂了，感谢解惑
