### ISSUE TITLE
菜单导航向左收缩成图标后，鼠标放在对应的菜单图标上无法显示子菜单

### ISSUE THREAD

**Issue by DoverDee** [vbenjs/vue-vben-admin#3492]
### 描述 Bug
目录导航收缩成图标后，鼠标放在对应的菜单图标上无法点选子级菜单
鼠标放在对应菜单图标上，子级菜单无法显示，但好像出现了模糊的黑影，见截图红框：
![image](https://github.com/vbenjs/vue-vben-admin/assets/8557230/6ce4f387-d313-4bc0-ab82-c1585e14f8b6)

### 复现 Bug
点击菜单向左变成小图标显示时，点击任意一个带二级子菜单的目录
## 系统信息

- 操作系统: windows10
- Node 版本: 18.14.0
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 8.13.1

**Comment by xachary** [comment]
@DoverDee 排查是到受以下 commit 的影响：
SHA-1: 841840f866b55d87b65deb41e5b38d2fc9d7231a
* fix: 修复表单按钮的类型定义外部无法修改重置或者提交按钮的文字的问题

问题已经定位，在此修复：
https://github.com/vbenjs/vue-vben-admin/pull/3499
