### ISSUE TITLE
createConfirm  确定和取消回调触发 但弹窗不关闭

### ISSUE THREAD

**Issue by VaCameos** [vbenjs/vue-vben-admin#3495]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
退出系统时，使用createConfrim创建弹窗，并给其options配置onOk ，onCancel回调，发现回调中的函数触发了，但是弹窗不关闭，即使我使用回调中所给的关闭函数依然无法关闭

### 复现 Bug

正常点击退出系统即可
![image](https://github.com/vbenjs/vue-vben-admin/assets/103049831/eb2609a7-a559-458f-9fad-d4214e88e38a)
![image](https://github.com/vbenjs/vue-vben-admin/assets/103049831/81659639-5f0e-449b-a242-b3507dd31716)

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by 13982720426** [comment]
我更新了最新代码，按照截图这个代码测试 没有复现。你看看控制台有没有报错信息，或者是其他地方的代码影响到了

**Comment by YangHgtc** [comment]
我也遇到了同样的问题

**Comment by Anchoror** [comment]
巧了，我今天也被这个bug困扰一天，明明回调执行成功了，但弹窗并未消失。很奇怪，换了台电脑就可以的，node是同一个版本的，浏览器也都是谷歌
![image](https://github.com/vbenjs/vue-vben-admin/assets/99526261/df64d946-e447-4406-b9c3-79b66636d5e0)

**Comment by VaCameos** [comment]
> 我更新了最新代码，按照截图这个代码测试 没有复现。你看看控制台有没有报错信息，或者是其他地方的代码影响到了

感谢回复。实际上这个问题我在官方demo中是不会出现的，但对于我的项目中，并没有修改这一部分的逻辑，同时控制台并无报错，且之前并不会这样，因此排查起来特别困难，所以提issues想看看有没有人遇到同样的问题并有解决方案。

**Comment by VaCameos** [comment]
> 巧了，我今天也被这个bug困扰一天，明明回调执行成功了，但弹窗并未消失。很奇怪，换了台电脑就可以的，node是同一个版本的，浏览器也都是谷歌 ![image](https://private-user-images.githubusercontent.com/99526261/293657999-df64d946-e447-4406-b9c3-79b66636d5e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxODY5ODMsIm5iZiI6MTcwNDE4NjY4MywicGF0aCI6Ii85OTUyNjI2MS8yOTM2NTc5OTktZGY2NGQ5NDYtZTQ0Ny00NDA2LWI5YzMtNzliNjY2MzZkNWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDA5MTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OTgxNmY5YzJjM2NkNTZmZDdkOWUxNDQzZTczYTFmYTk3YjU0NTEyMTQ5OTA1MjI5MDI3MDljNWVlZWMxMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wnWxjEQcz1WT798zO6ssTOb7Gh8HkupoJle5Rj6HL4s)

我似乎也是这样，且只有这个退出系统的弹窗会这样，怀疑this混乱导致，因为我直接调用其回调中的close3函数，依旧无法完成关闭

**Comment by boai92** [comment]
我暂时通过固定了vue的版本3.3.4解决这个问题了
我看vue官方3天前更新了版本到3.4.3，大概率是这个原因造成的？

**Comment by YangHgtc** [comment]
我按照https://github.com/vueComponent/ant-design-vue/issues/7239的建议把ant-design-vue升级到4.0.8解决了这个问题

**Comment by Anchoror** [comment]
> 我暂时通过固定了vue的版本3.3.4解决这个问题了 我看vue官方3天前更新了版本到3.4.3，大概率是这个原因造成的？

已解决，感谢

**Comment by VaCameos** [comment]
> 我暂时通过固定了vue的版本3.3.4解决这个问题了 我看vue官方3天前更新了版本到3.4.3，大概率是这个原因造成的？

but我的vue是3.2.33 :(

**Comment by VaCameos** [comment]
> 我暂时通过固定了vue的版本3.3.4解决这个问题了 我看vue官方3天前更新了版本到3.4.3，大概率是这个原因造成的？

已解决，感谢🙏

**Comment by Tairy** [comment]
+1

**Comment by ccrc001** [comment]
我也遇到这个问题了，今天测试页面发现也不能关闭，vue版本3.2.47,从用vben就没有更新过版本，看到评论大佬的3.3.4版本可以解决，但我这里还是无法关闭

**Comment by bigbrid** [comment]
只要重新install过之后createConfrim就关闭不了了，更换版本无用。麻烦大佬们修复

**Comment by ryuusennka** [comment]
我也遇到不能关闭弹窗的问题了..还有
...vue更新太快了吧,你们前两天说的3.4.3,我今天上午安装时看已经3.4.4了,现在看已经3.4.5了?

**Comment by VaCameos** [comment]
> 我也遇到这个问题了，今天测试页面发现也不能关闭，vue版本3.2.47,从用vben就没有更新过版本，看到评论大佬的3.3.4版本可以解决，但我这里还是无法关闭

vue没锁版本，只要你install过就会下最新版

**Comment by 2919807875** [comment]
> 我也遇到这个问题了，今天测试页面发现也不能关闭，vue版本3.2.47,从用vben就没有更新过版本，看到评论大佬的3.3.4版本可以解决，但我这里还是无法关闭

你解决了码

**Comment by 2919807875** [comment]
> 我也遇到了，现在版本3.3.4，并且在后端返回的错误提示上也不能自动关闭

你解决了吗，我这里修改了版本号还是一样，

**Comment by VaCameos** [comment]
> > 我也遇到了，现在版本3.3.4，并且在后端返回的错误提示上也不能自动关闭
> 
> 你解决了吗，我这里修改了版本号还是一样，

把package.json里的版本号前面的^删掉，重新install试试

**Comment by wangjue666** [comment]
https://github.com/vueComponent/ant-design-vue/issues/7239

**Comment by ccrc001** [comment]
> > 我也遇到了，现在版本3.3.4，并且在后端返回的错误提示上也不能自动关闭
> 
> 你解决了吗，我这里修改了版本号还是一样，

应该是只要更update了，项目不管删除node_modules 或是重新install都没有用了，我以为是pnpm的缓存，又重新开了一个文件夹拉取项目，换了一个版本的node，还是有那个bug，好在那天没有写过代码就发现了问题，直接把同事的项目打包拿着用了

**Comment by wangjue666** [comment]
antdv已经修复这个问题了， 耐心等待下他发布新版本到npm~

**Comment by wangjue666** [comment]
大家可以执行 `pnpm install -w ant-design-vue@4.1.0 --save`  或重新拉取下最新仓库代码 即可解决

**Comment by xachary** [comment]
> 大家可以执行 `pnpm install -w ant-design-vue@4.1.0 --save` 或重新拉取下最新仓库代码 即可解决

@wangjue666 

vue@3.4.5 + ant-design-vue@4.1.0 这个搭配，ant-design-vue@4.1.0 类型声明的变化，导致 pnpm type:check 无法通过。

![image](https://github.com/vbenjs/vue-vben-admin/assets/16830398/ae5dde25-4070-44ff-b466-7e14e41ce5f2)

**Comment by wangjue666** [comment]
> vue@3.4.5 + ant-design-vue@4.1.0 这个搭配，ant-design-vue@4.1.0 类型声明的变化，导致 pnpm type:check 无法通过。

@xachary  嗯 我这两天抽时间处理下，或者你有额外的时间吗？欢迎你帮忙处理下！

**Comment by xachary** [comment]
> vue@3.4.5 + ant-design-vue@4.1.0 这个搭配，ant-design-vue@4.1.0 类型声明的变化，导致 pnpm type:check 无法通过。
@wangjue666 

之前的正常：
> node_modules\.pnpm\ant-design-vue@4.0.8_vue@3.4.5\node_modules\ant-design-vue\es\table\index.d.ts
```ts
            bodyCell?: import("vue").Slot<{
                text: any;
                value: any;
                record: Record<string, any>;
                index: number;
                column: import("./interface").ColumnType<any>;
            }>;
            headerCell?: import("vue").Slot<{
                title: any;
                column: import("./interface").ColumnType<any>;
            }>;
```

现在的异常：
> node_modules\.pnpm\ant-design-vue@4.1.0_vue@3.4.5\node_modules\ant-design-vue\es\table\index.d.ts
```ts
        bodyCell?: {
            text: any;
            value: any;
            record: Record<string, any>;
            index: number;
            column: import("./interface").ColumnType<any>;
        };
        headerCell?: {
            title: any;
            column: import("./interface").ColumnType<any>;
        };
```

为何去除了 "import("vue").Slot<T>" 的定义，搞不懂，不懂

**Comment by wangjue666** [comment]
@xachary  嗯 我测试antdv官网示例也不正常 这样吧  先回滚锁死antdv的版本跟vue的版本， 等antdv修复了再升级依赖

**Comment by wangjue666** [comment]
@xachary  现在ci通过了

**Comment by leleccccc** [comment]
锁定vue3.3.4可以，但是vue更新了什么内容，会导致这个问题？
