### ISSUE TITLE
Slider侧边栏能否添加一个类似于@vben3项目或者语雀的侧边栏收缩/展开样式

### ISSUE THREAD

**Issue by LelandACM** [vbenjs/vue-vben-admin#3503]
### Subject of the feature
添加侧边栏收缩、展开方式

Describe your issue here.
目前
![image](https://github.com/vbenjs/vue-vben-admin/assets/19402747/6c0a7fce-234a-4e22-9fa9-4da6a4f5b65d)

添加语雀或者Vben3侧边栏展开、收缩样式
演示网站暂时打不开：https://vben.mufei88.com/#/login?redirect=/dashboard
类似于语雀的侧边栏收缩、展开
![image](https://github.com/vbenjs/vue-vben-admin/assets/19402747/7d43ccd0-df8a-47c6-b45e-1b33503c6cf1)

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by 13982720426** [comment]
点击左上角这个图标应该就是你说的那个功能，可以展开和收缩
![image](https://github.com/vbenjs/vue-vben-admin/assets/71159959/e76366b1-da42-4461-88cf-6146f077d750)

**Comment by LelandACM** [comment]
@13982720426 我知道，纯粹是绝对这个样式不好看。。。

**Comment by cMing1997** [comment]
> @13982720426 我知道，纯粹是绝对这个样式不好看。。。

样式不好看，可以自己改一下样式不就可以，功能交互可以借原有的

**Comment by LelandACM** [comment]
@cMing1997 好的，我以为这个仓库后面的功能会对齐 vben3

**Comment by cMing1997** [comment]
> vben3

我看了一下 vben3 ，那个还没有这个完善，所以建议以这个为主，但是可以借鉴一下 vben3

**Comment by LelandACM** [comment]
> > vben3
> 
> 我看了一下 vben3 ，那个还没有这个完善，所以建议以这个为主，但是可以借鉴一下 vben3

好，那我先关闭这个issue
