### ISSUE TITLE
点击菜单打开页面，页面内容不显示，重新刷新url才会显示；切换标签页也不显示内容。

### ISSUE THREAD

**Issue by ZackLeonardo** [vbenjs/vue-vben-admin#3513]
点击菜单打开页面，页面内容不显示，重新刷新url才会显示；切换标签页也不显示内容。

**Comment by wangjue666** [comment]
你的电脑看官网也是如此吗？

**Comment by ZackLeonardo** [comment]
> 你的电脑看官网也是如此吗？

不是呀，我电脑之前也不是啊，昨天merge下来就这样了

**Comment by wangjue666** [comment]
merge 来依赖重新安装下看看

**Comment by wangjue666** [comment]
这几天antdv有些问题

**Comment by ZackLeonardo** [comment]
> merge 来依赖重新安装下看看

依然存在这个问题，切换到某一个标签，这个标签内容不显示，再切换到其他标签，也不显示

**Comment by ZackLeonardo** [comment]
> > merge 来依赖重新安装下看看
> 
> 依然存在这个问题，切换到某一个标签，这个标签内容不显示，再切换到其他标签，也不显示

发现是一个特定的标签页，只要打开这个标签页，再切换到其他标签页，就会不显示，然而这个标签页也没报错误啊

**Comment by ZackLeonardo** [comment]
> > > merge 来依赖重新安装下看看
> > 
> > 
> > 依然存在这个问题，切换到某一个标签，这个标签内容不显示，再切换到其他标签，也不显示
> 
> 发现是一个特定的标签页，只要打开这个标签页，再切换到其他标签页，就会不显示，然而这个标签页也没报错误啊

修复啦，太粗心了，模板template里需要加一个div括住多个组件

**Comment by ZackLeonardo** [comment]
模板template里需要加一个div括住多个组件
