### ISSUE TITLE
以下验证用户是否存在的异步校验，只需要在创建时校验，而无需在修改时校验

### ISSUE THREAD

**Issue by kunlong-luo** [vbenjs/vue-vben-admin#3520]
### 描述 Bug

以下验证用户是否存在的异步校验，只需要在创建时校验，而无需在修改时校验
```
  {
    field: 'username',
    label: '用户名',
    component: 'Input',
    helpMessage: ['不能输入带有admin的用户名'],
    rules: [
      {
        required: true,
        message: '请输入用户名',
      },
      {
        trigger: 'blur',
        validator(_, value) {
          return new Promise((resolve, reject) => {
            if (!value) return resolve("");
            userExist(value)
              .then(res => {
                if (res) {
                  reject('用户名已存在');
                } else {
                  resolve("");
                }
              })
              .catch((err) => {
                reject(err.message || '验证失败');
              });
          });
        },
      },
    ],
  },
```

### 复现 Bug

```
  async function handleSubmit() {
    try {
      const values = await validate();
      setModalProps({ confirmLoading: true });
      if (isUpdate) {
        await apiEdit(values);
      } else {
        await apiCreate(values);
      }
      closeModal();
      emit('success', { isUpdate: unref(isUpdate), values: { ...values, id: rowId.value } });
    } finally {
      setModalProps({ confirmLoading: false });
    }
  }
```

**Comment by xachary** [comment]
isUpdate 是基于路径参数么？例如：

```js
const isUpdate = ref(!!route.params?.id); 
// ...
rules: [
      {
        required: true,
        message: '请输入用户名',
      },
      ...(isUpdate.value?[{
        trigger: 'blur',
        validator(_, value) {
          return new Promise((resolve, reject) => {
            if (!value) return resolve("");
            userExist(value)
              .then(res => {
                if (res) {
                  reject('用户名已存在');
                } else {
                  resolve("");
                }
              })
              .catch((err) => {
                reject(err.message || '验证失败');
              });
          });
        },
      }]:[]),
    ],
```

**Comment by kunlong-luo** [comment]
> isUpdate 是基于路径参数么？例如：
> 
> ```js
> const isUpdate = ref(!!route.params?.id); 
> // ...
> rules: [
>       {
>         required: true,
>         message: '请输入用户名',
>       },
>       ...(isUpdate.value?[{
>         trigger: 'blur',
>         validator(_, value) {
>           return new Promise((resolve, reject) => {
>             if (!value) return resolve("");
>             userExist(value)
>               .then(res => {
>                 if (res) {
>                   reject('用户名已存在');
>                 } else {
>                   resolve("");
>                 }
>               })
>               .catch((err) => {
>                 reject(err.message || '验证失败');
>               });
>           });
>         },
>       }]:[]),
>     ],
> ```

![image](https://github.com/vbenjs/vue-vben-admin/assets/40263163/f89cfc76-0636-49d1-bc8f-c0de87758747)
isUpdate 被定义在UserModal里面，如何才能拿到呢

**Comment by xachary** [comment]
> 被定义在UserModal里面，如何才能拿到呢
@kunlong-luo getFieldsValue 获取？
```ts
        validator(_, value) {
          return getFieldsValue().isUpdate ? Promise.resolve() : new Promise((resolve, reject) => {
            // ...
          });
        }
```

**Comment by kunlong-luo** [comment]
> > 被定义在UserModal里面，如何才能拿到呢
> > @kunlong-luo getFieldsValue 获取？
> 
> ```ts
>         validator(_, value) {
>           return getFieldsValue().isUpdate ? Promise.resolve() : new Promise((resolve, reject) => {
>             // ...
>           });
>         }
> ```

![image](https://github.com/vbenjs/vue-vben-admin/assets/40263163/83a07f6e-bb9c-48f6-a0a3-aa1269ba600c)

![image](https://github.com/vbenjs/vue-vben-admin/assets/40263163/eab1bf7c-c77e-465e-9d3f-fd34b3be5114)
getFieldsValue 获取会报错

**Comment by kunlong-luo** [comment]
> > 获取会报错
> > 实例化时机未到，要么做一些非空判断，要么实例化完成后再setProps设置schemas，场景比较灵活
> > @kunlong-luo

我把 form data 放到 form 里面就可以了
