### ISSUE TITLE
BasicTable的istreeTabel能不能一次只能展开一个呢?

### ISSUE THREAD

**Issue by 33550** [vbenjs/vue-vben-admin#3525]
BasicTable的istreeTabel能不能一次只能展开一个呢?在嵌套表格的时候,展开多个,会将表格分裂开,不太方便,能否做成手风琴式的呢?

**Comment by xachary** [comment]
@33550 
提了一个 pr（https://github.com/vbenjs/vue-vben-admin/pull/3533）

**Comment by 33550** [comment]
感谢,已解决
