### ISSUE TITLE
框架bug-InputNumber组件使用setFieldsValue设置值后，返回的值会变成string类型

### ISSUE THREAD

**Issue by boblk570** [vbenjs/vue-vben-admin#3526]
框架bug-InputNumber组件使用setFieldsValue设置值后，返回的值会变成string类型

**Comment by boblk570** [comment]
/Users/admin/Documents/Clients/star/admin/src/components/Form/src/helper.ts  
export const defaultValueComponents = [
  'Input',
  'InputPassword',
  'InputNumber',
  'InputSearch',
  'InputTextArea',
];

**Comment by xachary** [comment]
@boblk570 
从这里 https://github.com/vbenjs/vue-vben-admin/pull/3288 开始，InputNumber 被加进去了

**Comment by xachary** [comment]
我直接移除 handleInputNumberValue 的使用了，输入输出类型不一致，更多例如接口返回类型就是不对的。

**Comment by crudboy** [comment]
这个会导致问题导致InputNumber 显示了数字但是 校验会失败 我移除handleInputNumberValue 就可以正常使用了

**Comment by wwavelet** [comment]
> 我直接移除 handleInputNumberValue 的使用了，输入输出类型不一致，更多例如接口返回类型就是不对的。

@xachary 请问下移除是直接把这行代码注释掉吗？
`value = handleInputNumberValue(schema?.component, value);`

**Comment by pylist** [comment]
同样这个bug, 怎么解决

**Comment by goodsxx** [comment]
搜索 `handleInputNumberValue` 方法
将
```csharp
export function handleInputNumberValue(component?: ComponentType, val?: any) {
  if (!component) return val;
  if (defaultValueComponents.includes(component)) {
    return val && isNumber(val) ? `${val}` : val ;
  }
  return val;
}
```
改为
```csharp
export function handleInputNumberValue(component?: ComponentType, val?: any) {
  if (!component) return val;
  if (defaultValueComponents.includes(component)) {
    return val && isNumber(val) ? val : `${val}`;
  }
  return val;
}
```
我已提交了一个修复#3802
