### ISSUE TITLE
Table 组件的rowKey使用函数返回形式时，启用rowSelection后点击行选中的问题

### ISSUE THREAD

**Issue by miomiomonster** [vbenjs/vue-vben-admin#3528]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

描述bug:
列表数据没有类似id的单独关键字，需要由两个字段组合形成唯一的关键字
在设置了rowKey: (record:Recordable) => record['test1'] + record['test2']后，可以正常点击checkbox，
但是点击行后，checkbox无变化，但是选择记录添加了一条，

找到了Table组件hooks的 useCustomRow 的 getKey() 方法，将其中判断rowKey为function后的返回修改后，可以正常变化:
 if (isFunction(rowKey)) {                          if (isFunction(rowKey)) {
    return record[rowKey(record)];   →        return rowKey(record);    
  }                                                              }

不知道是不是我使用方式的问题

**Comment by xachary** [comment]
@miomiomonster 
我建议，在数据对象中按你的规则，定义规则去组装、新增一个 id 字段，例如 "A值,B值"、"A值_B值"等等。提交接口的之前，再用 split、正则 拆分恢复 A值 和 B值。
我觉得目前非数值型的rowKey，做 selection 的支持不太好。
毕竟还是基于 ant 的 table组件，看看 selectedRowKeys 定义也只是 string[]。
即使是 src\components\Table\src\hooks\useRowSelection.ts setSelectedRowKeys，也是 string | number。

**Comment by miomiomonster** [comment]
> @miomiomonster 我建议，在数据对象中按你的规则，定义规则去组装、新增一个 id 字段，例如 "A值,B值"、"A值_B值"等等。提交接口的之前，再用 split、正则 拆分恢复 A值 和 B值。 我觉得目前非数值型的rowKey，做 selection 的支持不太好。 毕竟还是基于 ant 的 table组件，看看 selectedRowKeys 定义也只是 string[]。 即使是 src\components\Table\src\hooks\useRowSelection.ts setSelectedRowKeys，也是 string | number。

好的，非常感谢回复和建议，我明白了~
