### ISSUE TITLE
升级antd4.0.8后使用BasicTable的展开行报错(expandedRowRender)

### ISSUE THREAD

**Issue by seawave0564** [vbenjs/vue-vben-admin#3531]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

升级antd4.0.8后使用BasicTable的展开行报错,未升级之前无问题

### 复现 Bug
![微信截图_20240110155850](https://github.com/vbenjs/vue-vben-admin/assets/73242157/d103d88f-afc8-4a36-8c8e-319fb661c627)

## 系统信息

- 操作系统:
- Node 版本: 18.17.1
- 包管理器 (npm/yarn/pnpm) 及其版本:8.7.1

**Comment by lovelyJason** [comment]
怎么解决的，怎么突然就关了

**Comment by lovelyJason** [comment]
我是4.0.2，但是我和你不一样，我单独使用expandedRowRender可以显示， 但是和expandColumnTitle一起用就全是你发的这个报错信息
