### ISSUE TITLE
引入vue-advanced-chat问题

### ISSUE THREAD

**Issue by Pluto1219** [vbenjs/vue-vben-admin#3548]
我现在引入vue-advanced-chat组件，按照官方文档提示，需要在vite.config.ts注册一下，但是注册后项目就无法启动，会提示At least one <template> or <script> is required in a single file component.错误

![image](https://github.com/vbenjs/vue-vben-admin/assets/15402976/4086d678-9718-4e6c-bf50-ec3fbc26a221)

// vite.config.js
import vue from '@vitejs/plugin-vue'
plugins: [
      vue({
        template: {
          compilerOptions: {
            // treat all tags with a dash as custom elements
            isCustomElement: (tagName) => {
              return tagName === 'vue-advanced-chat' || tagName === 'emoji-picker';
            },
          },
        },
      }),
    ],

![image](https://github.com/vbenjs/vue-vben-admin/assets/15402976/174c1389-ba1f-4786-a6b6-f5d86d3ca122)

vue-advanced-chat 地址
https://github.com/advanced-chat/vue-advanced-chat

![image](https://github.com/vbenjs/vue-vben-admin/assets/15402976/c9351efa-ed02-4e0d-aacd-dc5536e6162a)

请教各位大佬，这个如何解决，感谢
@xachary @wangjue666

**Comment by Pluto1219** [comment]
`<template>
  <vue-advanced-chat
    height="calc(100vh - 100px)"
    :current-user-id="username"
    :loading-rooms="loadingRooms"
    :rooms-loaded="roomsLoaded"
    :messages-loaded="messagesLoaded"
    :single-room="false"
    :show-search="false"
    :show-add-room="false"
    :show-files="false"
    :show-audio="false"
    :show-emojis="false"
    :show-reaction-emojis="false"
    .rooms="rooms"
    .messages="messages"
    @fetch-messages="fetchMessages($event.detail[0])"
    @send-message="sendMessage($event.detail[0])"
  />
</template>
<script setup lang="ts">
  import { register } from 'vue-advanced-chat';
  import { ref } from 'vue';

  register();

  const username = ref('123');
  const rooms = ref([
    {
      roomId: '1',
      roomName: 'Room 1',
      avatar: 'https://66.media.tumblr.com/avatar_c6a8eae4303e_512.pnj',
      users: [
        { _id: '1234', username: 'John Doe' },
        { _id: '4321', username: 'John Snow' },
      ],
    },
    {
      roomId: '2',
      roomName: 'Room 2',
      avatar: 'https://66.media.tumblr.com/avatar_c6a8eae4303e_512.pnj',
      users: [
        { _id: '1234', username: 'John Doe' },
        { _id: '4321', username: 'John Snow' },
      ],
    },
  ]);
  const roomsLoaded = ref(false);
  const loadingRooms = ref(false);

  const messages = ref([]);
  const messagesLoaded = ref(false);

  const currentRoom = ref(null);
  const fetchMessages = () => {};
  const sendMessage = () => {};
</script>
<style scoped lang="less"></style>`

**Comment by Pluto1219** [comment]
[pdd.vue.zip](https://github.com/vbenjs/vue-vben-admin/files/13944879/pdd.vue.zip)
这是vue文件，复制上来代码会丢失

**Comment by xachary** [comment]
> [pdd.vue.zip](https://github.com/vbenjs/vue-vben-admin/files/13944879/pdd.vue.zip) 这是vue文件，复制上来代码会丢失

markdown 语法”代码块“，怎么会丢失呢？
@Pluto1219

**Comment by Pluto1219** [comment]
`<template>
  <vue-advanced-chat
    height="calc(100vh - 100px)"
    :current-user-id="userId"
    :loading-rooms="loadingRooms"
    :rooms-loaded="roomsLoaded"
    :messages-loaded="messagesLoaded"
    :single-room="false"
    :show-search="false"
    :show-add-room="false"
    :show-files="true"
    :show-audio="false"
    :show-emojis="true"
    :show-reaction-emojis="false"
    .rooms="rooms"
    .messages="messages"
    @fetch-messages="fetchMessages($event.detail[0])"
    @send-message="sendMessage($event.detail[0])"
  />
</template>
<script setup lang="ts">
  import { register } from 'vue-advanced-chat';
  import { ref } from 'vue';

  register();

  const userId = ref('123');
  const rooms = ref([
    {
      roomId: '1',
      roomName: '客服小白',
      avatar: 'https://img.ddtouxiang.com/upload/touxiang/20221009/n4sgzaioxwz.jpg',
      users: [
        { _id: '1234', username: 'John Doe' },
        { _id: '4321', username: 'John Snow' },
      ],
      lastMessage: {
        _id: 'xyz',
        content: '我的货到了吗？',
        senderId: '1234',
        username: 'John Doe',
        timestamp: '10:20',
        saved: true,
        distributed: false,
        seen: false,
        new: true,
      },
    },
    {
      roomId: '2',
      roomName: '客服小王',
      avatar: 'https://img.ddtouxiang.com/upload/touxiang/20221009/rr0zx0214fg.jpg',
      users: [
        { _id: '1234', username: 'John Doe' },
        { _id: '4321', username: 'John Snow' },
      ],
      lastMessage: {
        content: '好的，谢谢',
        timestamp: '10:20',
      },
      new: false,
    },
  ]);
  const roomsLoaded = ref(false);
  const loadingRooms = ref(false);

  const messages = ref([]);
  const messagesLoaded = ref(false);

  const currentRoom = ref(null);
  const fetchMessages = () => {};
  const sendMessage = (message) => {
    console.log(message);
    messages.value = [
      ...messages.value,
      {
        _id: messages.value.length,
        content: message.content,
        senderId: userId.value,
        timestamp: new Date().toString().substring(16, 21),
        date: new Date().toDateString(),
      },
    ];
  };
</script>
<style scoped lang="less"></style>
`

**Comment by Pluto1219** [comment]
```
<template>
  <vue-advanced-chat
    height="calc(100vh - 100px)"
    :current-user-id="userId"
    :loading-rooms="loadingRooms"
    :rooms-loaded="roomsLoaded"
    :messages-loaded="messagesLoaded"
    :single-room="false"
    :show-search="false"
    :show-add-room="false"
    :show-files="true"
    :show-audio="false"
    :show-emojis="true"
    :show-reaction-emojis="false"
    .rooms="rooms"
    .messages="messages"
    @fetch-messages="fetchMessages($event.detail[0])"
    @send-message="sendMessage($event.detail[0])"
  />
</template>
<script setup lang="ts">
  import { register } from 'vue-advanced-chat';
  import { ref } from 'vue';

  register();

  const userId = ref('123');
  const rooms = ref([
    {
      roomId: '1',
      roomName: '客服小白',
      avatar: 'https://img.ddtouxiang.com/upload/touxiang/20221009/n4sgzaioxwz.jpg',
      users: [
        { _id: '1234', username: 'John Doe' },
        { _id: '4321', username: 'John Snow' },
      ],
      lastMessage: {
        _id: 'xyz',
        content: '我的货到了吗？',
        senderId: '1234',
        username: 'John Doe',
        timestamp: '10:20',
        saved: true,
        distributed: false,
        seen: false,
        new: true,
      },
    },
    {
      roomId: '2',
      roomName: '客服小王',
      avatar: 'https://img.ddtouxiang.com/upload/touxiang/20221009/rr0zx0214fg.jpg',
      users: [
        { _id: '1234', username: 'John Doe' },
        { _id: '4321', username: 'John Snow' },
      ],
      lastMessage: {
        content: '好的，谢谢',
        timestamp: '10:20',
      },
      new: false,
    },
  ]);
  const roomsLoaded = ref(false);
  const loadingRooms = ref(false);

  const messages = ref([]);
  const messagesLoaded = ref(false);

  const currentRoom = ref(null);
  const fetchMessages = () => {};
  const sendMessage = (message) => {
    console.log(message);
    messages.value = [
      ...messages.value,
      {
        _id: messages.value.length,
        content: message.content,
        senderId: userId.value,
        timestamp: new Date().toString().substring(16, 21),
        date: new Date().toDateString(),
      },
    ];
  };
</script>
<style scoped lang="less"></style>


```

**Comment by Pluto1219** [comment]
@xachary 这是代码，谢谢
vite.config.ts

import vue from '@vitejs/plugin-vue';

```
 plugins: [
      vue({
        template: {
          compilerOptions: {
            // treat all tags with a dash as custom elements
            isCustomElement: (tagName) => {
              return tagName === 'vue-advanced-chat' || tagName === 'emoji-picker';
            },
          },
        },
      }),
    ],
```

**Comment by xachary** [comment]
@Pluto1219 很顺畅，没发现异常
```bash
pnpm i -w -s vue-advanced-chat
```

![image](https://github.com/vbenjs/vue-vben-admin/assets/16830398/b0dd3e50-ff48-4ebb-b67f-7b91e7853c71)
![image](https://github.com/vbenjs/vue-vben-admin/assets/16830398/d50d77c7-13cb-40c8-add2-59816cb801d9)
![image](https://github.com/vbenjs/vue-vben-admin/assets/16830398/cd9b95aa-97f8-49fb-8a7f-6ffcfd4c966b)
![image](https://github.com/vbenjs/vue-vben-admin/assets/16830398/3ba116cc-c5d6-4c39-b1f1-7cf966702b77)

**Comment by Pluto1219** [comment]
> @Pluto1219 很顺畅，没发现异常
> 
> ```shell
> pnpm i -w -s vue-advanced-chat
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/16830398/296941693-b0dd3e50-ff48-4ebb-b67f-7b91e7853c71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODQ3MzAsIm5iZiI6MTcwNTM4NDQzMCwicGF0aCI6Ii8xNjgzMDM5OC8yOTY5NDE2OTMtYjBkZDNlNTAtZmY0OC00ZWJiLWI2N2YtN2I5MWU3ODUzYzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA1NTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlY2JkNWY4MWMyYWRjYWM5ZTdkZjlmY2E3ZTI1NmMxMzQ0OWJjMmQ2MWVjZDRlYzY5NzUwYjM0YTkwOWJiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hGmW7A46QqIPXb0qTPNouhFHoXIz0_ReKbV1TuXbAOU) ![image](https://private-user-images.githubusercontent.com/16830398/296941760-d50d77c7-13cb-40c8-add2-59816cb801d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODQ3MzAsIm5iZiI6MTcwNTM4NDQzMCwicGF0aCI6Ii8xNjgzMDM5OC8yOTY5NDE3NjAtZDUwZDc3YzctMTNjYi00MGM4LWFkZDItNTk4MTZjYjgwMWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA1NTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MTgxNjkxZmQ3ZDIyMDVjMjViNGU5NjZhZDZkODc5MGM5YTE4YjRlYzUxZmNkMmMzOTVlNWU3N2IwOGYzODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f4gdds8IDvx4YIz8dJCazVaDYIZuHO8tNzHl3_FaDHM) ![image](https://private-user-images.githubusercontent.com/16830398/296941829-cd9b95aa-97f8-49fb-8a7f-6ffcfd4c966b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODQ3MzAsIm5iZiI6MTcwNTM4NDQzMCwicGF0aCI6Ii8xNjgzMDM5OC8yOTY5NDE4MjktY2Q5Yjk1YWEtOTdmOC00OWZiLThhN2YtNmZmY2ZkNGM5NjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA1NTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZGY3MmQyMmNlNDlkMTExZTRiNjMyMjU0ZjMyMzFhYTFkMjUzOGEyZGExMjk3NjAzYWE3YWM5YjA0NGM5MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UIBvsuFZnSLXLiIBMAtyq3cKlZI7nLqHD230HWVL1zY) ![image](https://private-user-images.githubusercontent.com/16830398/296941647-3ba116cc-c5d6-4c39-b1f1-7cf966702b77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODQ3MzAsIm5iZiI6MTcwNTM4NDQzMCwicGF0aCI6Ii8xNjgzMDM5OC8yOTY5NDE2NDctM2JhMTE2Y2MtYzVkNi00YzM5LWIxZjEtN2NmOTY2NzAyYjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA1NTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMWQ4ODU4NTUxOGVjMDRiYTdhNjFmZWRiYzVhMzc3NTM2MGRhMjM4NGQxY2UzMTE0N2FlZjdiMjc3OWNlOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0sp8aE2aD00zfpFDX5AlF4Q6cC7cFWik-O67wJtoro4)

控制台也没有异常吗？奇怪，那我再看看，谢谢你

**Comment by Pluto1219** [comment]
> @Pluto1219 很顺畅，没发现异常
> 
> ```shell
> pnpm i -w -s vue-advanced-chat
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/16830398/296941693-b0dd3e50-ff48-4ebb-b67f-7b91e7853c71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODQ3MzAsIm5iZiI6MTcwNTM4NDQzMCwicGF0aCI6Ii8xNjgzMDM5OC8yOTY5NDE2OTMtYjBkZDNlNTAtZmY0OC00ZWJiLWI2N2YtN2I5MWU3ODUzYzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA1NTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlY2JkNWY4MWMyYWRjYWM5ZTdkZjlmY2E3ZTI1NmMxMzQ0OWJjMmQ2MWVjZDRlYzY5NzUwYjM0YTkwOWJiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hGmW7A46QqIPXb0qTPNouhFHoXIz0_ReKbV1TuXbAOU) ![image](https://private-user-images.githubusercontent.com/16830398/296941760-d50d77c7-13cb-40c8-add2-59816cb801d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODQ3MzAsIm5iZiI6MTcwNTM4NDQzMCwicGF0aCI6Ii8xNjgzMDM5OC8yOTY5NDE3NjAtZDUwZDc3YzctMTNjYi00MGM4LWFkZDItNTk4MTZjYjgwMWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA1NTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MTgxNjkxZmQ3ZDIyMDVjMjViNGU5NjZhZDZkODc5MGM5YTE4YjRlYzUxZmNkMmMzOTVlNWU3N2IwOGYzODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f4gdds8IDvx4YIz8dJCazVaDYIZuHO8tNzHl3_FaDHM) ![image](https://private-user-images.githubusercontent.com/16830398/296941829-cd9b95aa-97f8-49fb-8a7f-6ffcfd4c966b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODQ3MzAsIm5iZiI6MTcwNTM4NDQzMCwicGF0aCI6Ii8xNjgzMDM5OC8yOTY5NDE4MjktY2Q5Yjk1YWEtOTdmOC00OWZiLThhN2YtNmZmY2ZkNGM5NjZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA1NTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1ZGY3MmQyMmNlNDlkMTExZTRiNjMyMjU0ZjMyMzFhYTFkMjUzOGEyZGExMjk3NjAzYWE3YWM5YjA0NGM5MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UIBvsuFZnSLXLiIBMAtyq3cKlZI7nLqHD230HWVL1zY) ![image](https://private-user-images.githubusercontent.com/16830398/296941647-3ba116cc-c5d6-4c39-b1f1-7cf966702b77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzODQ3MzAsIm5iZiI6MTcwNTM4NDQzMCwicGF0aCI6Ii8xNjgzMDM5OC8yOTY5NDE2NDctM2JhMTE2Y2MtYzVkNi00YzM5LWIxZjEtN2NmOTY2NzAyYjc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDA1NTM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMWQ4ODU4NTUxOGVjMDRiYTdhNjFmZWRiYzVhMzc3NTM2MGRhMjM4NGQxY2UzMTE0N2FlZjdiMjc3OWNlOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0sp8aE2aD00zfpFDX5AlF4Q6cC7cFWik-O67wJtoro4)

我明白了，多谢大神指点
