### ISSUE TITLE
原来国际化，是支持ts文件的，现在只支持json，特性缺失

### ISSUE THREAD

**Issue by ydaydayup** [vbenjs/vue-vben-admin#3550]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

原来国际化，是支持ts文件的，现在只支持json，特性缺失， src/locales

### Reproduction

在src/locales新增多语种，失败

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

建议改成下面的
```ts
const modules = import.meta.glob(['./zh-CN/**/*.json', './zh-CN/**/*.ts'], { eager: true });

```

**Comment by likui628** [comment]
https://github.com/mrmlnc/fast-glob?tab=readme-ov-file#braceexpansion
