### ISSUE TITLE
路由设置缓存后，弹框打开新页面，新页面弹框依然在

### ISSUE THREAD

**Issue by Xunje** [vbenjs/vue-vben-admin#3556]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

请清晰地描述此 Bug 的具体表现。

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by xachary** [comment]
@Xunje 
”路由设置缓存后“，具体是什么设置？
”弹框打开新页面“，”弹框“不是”Modal“么？”页面“不是在”多页签Tabs“中显示么？
”新页面弹框“，疑问同上。
”依然在“，疑问同上上上。

**Comment by Xunje** [comment]
> @Xunje “路由设置缓存后”，具体是什么设置？ ”弹框打开新页面“，”弹框“不是”Modal“么？”页面“不是在”多页签Tabs“中显示么？ ”新页面弹框“，疑问同上。 ”仍然在“，疑问同上。

<img width="1497" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/49667186/72dcb1d9-5318-4631-808d-b891f34490a3">

**Comment by Xunje** [comment]
> @Xunje “路由设置缓存后”，具体是什么设置？ ”弹框打开新页面“，”弹框“不是”Modal“么？”页面“不是在”多页签Tabs“中显示么？ ”新页面弹框“，疑问同上。 ”仍然在“，疑问同上。
因为 下拉选择的情况下 下拉没有该数据 需要跳转页面进行 新增 此时 modal 已经填写了 数据 不能关闭 所以需要缓存数据   跳转之后 modal 还是存在

**Comment by xachary** [comment]
@Xunje 
你可能需要用 getContainer 去指定 modal 所在的位置，默认是 body 吧，只要不关闭，modal 当然一直在。
按你上面的场景，这个 modal 应该属于当前 tab 的组件，getContainer 就要指向这个组件的 dom。

[Ant Design Vue 官方文档](https://antdv.com/components/modal-cn#api)

![image](https://github.com/vbenjs/vue-vben-admin/assets/16830398/e5551005-b591-4354-bcbc-5c6cdb2a2584)
