### ISSUE TITLE
已打开的菜单导航文本左右未对齐并且关闭x号显示出来的时候上下未对其

### ISSUE THREAD

**Issue by DoverDee** [vbenjs/vue-vben-admin#3557]
最新版本：已打开的菜单导航文本左右未对齐并且关闭x号显示出来的时候上下未对其

![image](https://github.com/vbenjs/vue-vben-admin/assets/8557230/ec20c612-25ad-426b-a54d-60b00dcdd993)

**Comment by xachary** [comment]
@DoverDee 我在 chrome 和 edge 看，有这个情况，但没你图里那么严重，不过还是提个 pr（https://github.com/vbenjs/vue-vben-admin/pull/3560）微调一下：
![image](https://github.com/vbenjs/vue-vben-admin/assets/16830398/db7de83d-7939-4f30-a774-58684df60802)
