### ISSUE TITLE
针对 KeepAlive 未生效的问题

### ISSUE THREAD

**Issue by cMing1997** [vbenjs/vue-vben-admin#3565]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [*] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [*] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [*] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug
项目中开启了 KeepAlive，但是在切换 tab 的时候，似乎并没有进行缓存

### Reproduction
1. 项目中配置了 `openKeepAlive: true` 和  多标签页的 MultiTabsSetting 的show 设置为 true
2. 项目路由如下 
![image](https://github.com/vbenjs/vue-vben-admin/assets/40878104/f69d485a-15e8-493e-a318-33c3edaf3ee0)

3. 在 `src\layouts\page\index.vue` 页面打印了一下参数，如下
![image](https://github.com/vbenjs/vue-vben-admin/assets/40878104/c30a1956-5837-443d-a312-e76770df51a4)

4. 比如在打开的 `UserMgr` 页面填写了一些东西之后， 点击 `tab` 切换到 `BackUp` 再切换到 `UserMgr` ,，发现之前在 `UserMgr` 填写的东西都不见了

## System Info

- Operating System: window11
- Node version: 21
- Package manager (npm/yarn/pnpm) and version: 
```
pnpm: 8.11.0
yarn: 1.22.21
npm: 10.2.4
```

**Comment by xachary** [comment]
@cMing1997 要用 defineOptions 给页面组件定义 name 哦

**Comment by xachary** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/16830398/281daafc-4e49-4185-9ead-51eefe02628c)

**Comment by Atw-Lee** [comment]
文档上是写错了吗defineComponent
