### ISSUE TITLE
BasicTable 动态设置表头不生效

### ISSUE THREAD

**Issue by zwtvip** [vbenjs/vue-vben-admin#3567]
说明： 表格第一列固定，从第二列开始由接口获取动态展示表头，调用setColumns方法会将第一列覆盖

<img width="1243" alt="屏幕截图 2024-01-22 174838" src="https://github.com/vbenjs/vue-vben-admin/assets/29778465/83cb30af-6dc2-499b-a1fc-de405af948ec">
<img width="381" alt="屏幕截图 2024-01-22 175014" src="https://github.com/vbenjs/vue-vben-admin/assets/29778465/c822cd0f-8b1d-4a13-8951-e3b2edc72460">

**Comment by xachary** [comment]
@zwtvip https://github.com/vbenjs/vue-vben-admin/issues/3559 这里也算动态设置表头
用官方 demo 改一个最小示例，markdown 代码出来？接口部分，promiseTimeout 假装一下？
