### ISSUE TITLE
table表单重置问题

### ISSUE THREAD

**Issue by Leonsama** [vbenjs/vue-vben-admin#3568]
basicModal内嵌套了一个开启查询框的basicTable，怎么操作才能每次打开modal都能重置这个table的查询框？

我尝试了给modal加上key字段，但是随机key会导致modal无法打开

**Comment by xachary** [comment]
@Leonsama 直觉：
BasicModal 的 @open-change，open  的时候 nextTick 之后执行 BasicTable 的 getForm->form->resetFields

**Comment by Leonsama** [comment]
成功了 谢谢
