### ISSUE TITLE
在解决富文本下拉框滚动页面问题后引起的无法使用返回顶部按钮

### ISSUE THREAD

**Issue by Anima-No** [vbenjs/vue-vben-admin#3580]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

(https://github.com/vbenjs/vue-vben-admin/pull/1996)
在#1996 这个修复中，注释掉了  overflow-x: hidden !important;这个代码，可以解决富文本下拉并滚动页面时候不会出现错位的问题，但是也引起了另外一个组件的bug就是antd内的BackTop组件，会出现没法触发的问题

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by xachary** [comment]
@Anima-No 提了个 pr 修复
https://github.com/vbenjs/vue-vben-admin/pull/3581
