### ISSUE TITLE
登录地址重定向

### ISSUE THREAD

**Issue by gnyuan** [vbenjs/vue-vben-admin#3588]
例如未登录状态访问地址`https://vben.vvbin.cn/#/login?redirect=/useRequest/base`
输入用户名以及密码后，不能正确重定向到`/useRequest/base`
哪里可以设置登录后正常跳转呢?

**Comment by xachary** [comment]
@gnyuan 提了个 pr（https://github.com/vbenjs/vue-vben-admin/pull/3592）
不过，主动登出到 /login 是不带 redirect 的，如需测试，改为 logout(false) 即可。
管理员先评审一下@wangjue666

**Comment by gnyuan** [comment]
> @gnyuan 提了个 pr（[https://github.com/vbenjs/vue-vben-admin/pull/3592）](https://github.com/vbenjs/vue-vben-admin/pull/3592%EF%BC%89) 不过，主动登出到 /login 是不带 redirect 的，如需测试，改为 logout(false) 即可。 管理员先评审一下@wangjue666

大佬，您这太强了！！ 这个PR LGTM
