### ISSUE TITLE
有没有办法在ctrl+r刷新页面后，打开的tab全部都保留下来？

### ISSUE THREAD

**Issue by imokyou** [vbenjs/vue-vben-admin#3591]
有没有办法在ctrl+r刷新页面后，打开的tab学保留下来？

![截屏2024-02-02 15 24 09](https://github.com/vbenjs/vue-vben-admin/assets/3397309/67d59f69-60f9-4197-ab5a-c0db7d407683)

**Comment by xachary** [comment]
@imokyou 
src\settings\projectSetting.ts
multiTabsSetting.cache
这个？

**Comment by imokyou** [comment]
我找到了，在multipleTab.ts 里这样就行了
cacheTab && Persistent.setLocal(MULTIPLE_TABS_KEY, this.tabList, true) 

在切换角色、换账号、退出的时候把这个  Persistent.setLocal(MULTIPLE_TABS_KEY, [], true) 就行了。  问题不大
