### ISSUE TITLE
关于图片超过限制大小情况下(uploadError), 仍然触发图片上传Upload的问题

### ISSUE THREAD

**Issue by Musery** [vbenjs/vue-vben-admin#3594]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
涉及CropperModal组件中关于图片大小限制的返回处理, 依然会触发图片上传接口。
代码位置
<img width="530" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/25795604/f2a73eb3-048b-4839-bfce-dd627931a253">

请清晰地描述此 Bug 的具体表现。
如上文所述,  应该在代码位置设置返回false
![image](https://github.com/vbenjs/vue-vben-admin/assets/25795604/b72cde05-940f-4e5b-9423-6cd141026426)

### 复现 Bug
1. 设置图片上传大小限制, 默认5M
2. 准备超过设置的图片大小限制的图片。
3. 在CropperAvater等使用CropperModal组件中执行图片上传, 会发现触发了图片上传的接口请求

## 系统信息

- 操作系统:  Macos
- Node 版本:  18.1.0
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 8.14.0

**Comment by likui628** [comment]
https://antdv.com/components/upload/#Upload
> Uploading will be stopped with false or a rejected Promise returned.
