### ISSUE TITLE
精简版开启tab页缓存不生效

### ISSUE THREAD

**Issue by mawenqing1** [vbenjs/vue-vben-admin#3595]
openKeepAlive设置为true，路由的name和对应组件的name也完全一致，但是切换tab回来后还是会重新加载

看了下缓存那块 getCaches，路由name也都有
![image](https://github.com/vbenjs/vue-vben-admin/assets/82371562/61064e8f-0985-4aab-bb20-d66065256d1f)

是要做额外的什么配置吗

**Comment by likui628** [comment]
精简版现在没人维护了
