### ISSUE TITLE
希望数字表单也能添加前后缀

### ISSUE THREAD

**Issue by Mr-LiuDC** [vbenjs/vue-vben-admin#3599]
目前发现好像只有Input类型字段可以添加前后缀，数字字段也有这个需求。
![image](https://github.com/vbenjs/vue-vben-admin/assets/18117854/f44c1467-ff17-42a0-bbef-49a388afa7df)
![image](https://github.com/vbenjs/vue-vben-admin/assets/18117854/8fe66c43-3658-497d-a5cc-76766c4337d4)

**Comment by likui628** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/90845831/921e21d3-1e62-4ed8-ac12-20adf6868209)
试了下，本身是可以的

**Comment by anncwb** [comment]
Hello @Mr-LiuDC. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by Mr-LiuDC** [comment]
难道是我的版本比较旧的原因吗，我用的 2.8.0 版本
