### ISSUE TITLE
对于使用 BasicForm 中的自定义component，我发现这么写还是有问题

### ISSUE THREAD

**Issue by cMing1997** [vbenjs/vue-vben-admin#3603]
我发现这么写还是有问题
```ts
import { FormSchema } from '@/components/Form';

export const step1Schemas: FormSchema[] = [
    {
        field: 'category',
        label: '资源类别',
        component: 'CheckableTags',
    },
];
```
CheckableTags 为自定义的组件
![image](https://github.com/vbenjs/vue-vben-admin/assets/40878104/5af6e950-3267-4792-9d4f-35736b6f2773)

_Originally posted by @cMing1997 in https://github.com/vbenjs/vue-vben-admin/issues/3426#issuecomment-1950975655_

**Comment by xachary** [comment]
src\components\Form\src\types\index.ts
```ts
export interface ComponentProps {
  // 这里加一下自定义表单组件？
}
```
@cMing1997

**Comment by cMing1997** [comment]
> src\components\Form\src\types\index.ts
> 
> ```ts
> export interface ComponentProps {
>   // 这里加一下自定义表单组件？
> }
> ```
> 
> @cMing1997

@xachary  基于 https://github.com/vbenjs/vue-vben-admin/pull/3426 这个里面的回答，再结合线上文档来说，对于自定义组件最好的是使用 slot  而不是 在 ComponentProps  里面 添加自定义组件的类型，同样的，线上的文档也需要更新了，那么在最新的代码里面 其实 useComponentRegister 这个方法也就失去了对应的作用了
