### ISSUE TITLE
Exception 组件status参数传入success | error | info | warning icon没有显示

### ISSUE THREAD

**Issue by Bo-Teng** [vbenjs/vue-vben-admin#3604]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

传入 warning没有显示对应的icon

### 复现 Bug

![image](https://github.com/vbenjs/vue-vben-admin/assets/73982811/1b9f09f3-67d7-41d7-96ab-b4a13f443497)

## 系统信息

- 操作系统: win10
- Node 版本:18.19.0
- 包管理器 (npm/yarn/pnpm) 及其版本:yarn 1.22.21

**Comment by xachary** [comment]
使用的是 Result（ant-design-vue）的 [icon 插槽](https://antdv.com/components/result-cn#components-result-demo-customicon)，显示的是自定义的 icon：
src\views\sys\exception\Exception.vue
```jsx
          <Result
            class={prefixCls}
            status={status as any}
            title={props.title || title}
            sub-title={props.subTitle || subTitle}
          >
            {{
              extra: () =>
                btnText && (
                  <Button type="primary" onClick={handler}>
                    {() => btnText}
                  </Button>
                ),
              icon: () => (icon ? <img src={icon} /> : null),
            }}
          </Result>
```
@Bo-Teng 
也许你可以微调一下：
```jsx
             icon:
                status && ExceptionEnum[status] === void 0
                  ? () => (icon ? <img src={icon} /> : null)
                  : undefined
```

**Comment by Bo-Teng** [comment]
@xachary 好的谢谢
