### ISSUE TITLE
BasicTable里加TableAction时设置icon显示异常

### ISSUE THREAD

**Issue by Serendipity99** [vbenjs/vue-vben-admin#3607]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
请清晰地描述此 Bug 的具体表现。
使用版本为最新的2.10.1
pnpm i 命令有一个这个
dependencies:
iconify/iconify 2.2.1 (3.1.1 is available) deprecated
然后BasicTable里加TableAction时设置icon，页面有多余的文字
### 复现 Bug
![Snipaste_2024-02-19_17-33-05](https://github.com/vbenjs/vue-vben-admin/assets/31979987/df9c0847-c97a-4699-9a53-6b2192a47ebe)

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:18.19.0
- 包管理器 (npm/yarn/pnpm) 及其版本: pnpm 8.11.0

**Comment by likui628** [comment]
原因是TableAction内引用的PopConfirmButton包含了[antdv Popconfirm](https://antdv.com/components/popconfirm/#Popconfirm)接收了icon参数导致的
