### ISSUE TITLE
在安装了对应vscode插件，写tailwind 类名的时候没有智能提示

### ISSUE THREAD

**Issue by electroluxcode** [vbenjs/vue-vben-admin#3611]
### Subject of the feature

将tailwind.config.js 提取到最外层可以解决这个问题

**Comment by electroluxcode** [comment]
但是想了想，感觉这也有可能是设计者有意不把tailwind.config.js提取到最顶上哈哈，如果打扰了直接关闭pr和issue就好了

**Comment by likui628** [comment]
你安装的是[UnoCSS](https://marketplace.visualstudio.com/items?itemName=antfu.unocss)吗

**Comment by electroluxcode** [comment]
> 你安装的是[UnoCSS](https://marketplace.visualstudio.com/items?itemName=antfu.unocss)吗

对的，而且我问了我的同事。同一个项目，在mac 下面这个项目有tailwind的提示，window下面没有提示

**Comment by electroluxcode** [comment]
> > 你安装的是[UnoCSS](https://marketplace.visualstudio.com/items?itemName=antfu.unocss)吗
> 
> 对的，而且我问了我的同事。同一个项目，在mac 下面这个项目有tailwind的提示，window下面没有提示

补充一下，我的vscode 也装了 unocss for vscode 的插件，但是仍然只有把tailwind.config.js 提到根目录才有智能提示

**Comment by likui628** [comment]
那你试一下有没有可能是什么冲突了，把可能冲突的先禁用了。
我这边是可以的

**Comment by electroluxcode** [comment]
> 那你试一下有没有可能是什么冲突了，把可能冲突的先禁用了。 我这边是可以的

okok，麻烦你了
