### ISSUE TITLE
登陆页面卡死！

### ISSUE THREAD

**Issue by H402861965** [vbenjs/vue-vben-admin#3620]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by zwtvip** [comment]
我也遇到了，新拉的代码有问题
![image](https://github.com/vbenjs/vue-vben-admin/assets/29778465/8accab91-cb4b-4d25-9d03-e23ab8bc077a)
![image](https://github.com/vbenjs/vue-vben-admin/assets/29778465/b5e29ee3-5abd-470a-91ca-8ba927076f4b)

**Comment by youtao531** [comment]
同样也登录卡死

**Comment by youtao531** [comment]
我也遇到

**Comment by BigRockCandy** [comment]
不知道啥时候能解决

**Comment by chenhw** [comment]
@xachary #3592 提交的问题
