### ISSUE TITLE
远程加载表格报警告

### ISSUE THREAD

**Issue by zwtvip** [vbenjs/vue-vben-admin#3641]
![image](https://github.com/vbenjs/vue-vben-admin/assets/29778465/7d53433f-9dc7-4a98-a249-65856158b933)

**Comment by cszhjh** [comment]
这个警告是说在PageWrapper组件上传递了一个fixedHeight为true的时候，BasicTable组件的canResize可能会不起作用，如果你想要去掉这个警告的话可以在views/table/FetchTable.vue中将PageWrapper上的“fixedHeight”属性去掉

**Comment by zwtvip** [comment]
@cszhjh 感谢解惑
