### ISSUE TITLE
【Bug】 示例的Form和Table页面无法显示

### ISSUE THREAD

**Issue by BigCat20196** [vbenjs/vue-vben-admin#3662]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

当我使用pnpm run dev运行项目时，点击Form或Table，弹窗扩展，抽屉扩展等路由会一直显示在加载中，无法进入对应页面，请帮忙看下

### Reproduction

win10
vben-admin版本: 2.10.1
git clone 
cd vue-vben-admin/
pnpm install
pnpm run dev

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by cszhjh** [comment]
@BigCat20196 无法复现这个问题，你可以提供更详细的说明吗？例如：控制台报错信息、node已经pnpm版本、一个最小化可复现问题的repo等

**Comment by BigCat20196** [comment]
> @BigCat20196 无法复现这个问题，你可以提供更详细的说明吗？例如：控制台报错信息、node已经pnpm版本、一个最小化可复现问题的repo等

node 版本20.11.1
pnpm版本8.15.4

![image](https://github.com/vbenjs/vue-vben-admin/assets/51037443/12a667a0-5323-43f0-bf4b-ad2377b03443)

**Comment by cszhjh** [comment]
> > @BigCat20196 无法复现这个问题，你可以提供更详细的说明吗？例如：控制台报错信息、node已经pnpm版本、一个最小化可复现问题的repo等
> 
> node 版本20.11.1 pnpm版本8.15.4
> 
> ![image](https://private-user-images.githubusercontent.com/51037443/311150882-12a667a0-5323-43f0-bf4b-ad2377b03443.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MDU2MDIsIm5iZiI6MTcwOTkwNTMwMiwicGF0aCI6Ii81MTAzNzQ0My8zMTExNTA4ODItMTJhNjY3YTAtNTMyMy00M2YwLWJmNGItYWQyMzc3YjAzNDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDEzNDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYzYwZmM1OTllYzUyMGIxMmZkODgwMTU2MzJlYmFiNzM2ODI0YjZlNWU2ZjFmMjJhYTVlOWFlOWVkZDkzMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aKG8847VZ0KY97Rxub7zE7WkyVms1ad9nO-UL45ds_c)

这看起来像是isComponentFormSchema导出语句的语法错误？但是我检查了语法并没有发现问题，或许是与版本有关？需要帮助 @wangjue666

**Comment by wangjue666** [comment]
@BigCat20196  我本地运行也正常呢， 光是你的提及到的示例文件打不开吗？ 其他页面可以正常访问？

**Comment by BigCat20196** [comment]
> @BigCat20196 我本地运行也正常呢， 光是你的提及到的示例文件打不开吗？ 其他页面可以正常访问？

是的，带有isComponentFormSchema和formItem的都打不开。我觉得是个环境问题，还需要我提供哪些插件的版本呢？
我只是clone了项目 然后pnpm install和pnpm run dev 没有修改过任何代码

**Comment by wangjue666** [comment]
> 是的，带有isComponentFormSchema和formItem的都打不开。我觉得是个环境问题，还需要我提供哪些插件的版本呢？ 我只是clone了项目 然后pnpm install和pnpm run dev 没有修改过任何代码

没遇到这种情况，应该不是环境问题，试着重新安装下依赖看看， 或者试着在你本地打包访问下打包文件看看有没有这种情况

**Comment by BigCat20196** [comment]
> > 是的，带有isComponentFormSchema和formItem的都打不开。我觉得是个环境问题，还需要我提供哪些插件的版本呢？ 我只是clone了项目 然后pnpm install和pnpm run dev 没有修改过任何代码
> 
> 没遇到这种情况，应该不是环境问题，试着重新安装下依赖看看， 或者试着在你本地打包访问下打包文件看看有没有这种情况

重新clone项目和重装依赖都试过了 还是不行 相同的报错

**Comment by wangjue666** [comment]
> > > 是的，带有isComponentFormSchema和formItem的都打不开。我觉得是个环境问题，还需要我提供哪些插件的版本呢？ 我只是clone了项目 然后pnpm install和pnpm run dev 没有修改过任何代码
> > 
> > 没遇到这种情况，应该不是环境问题，试着重新安装下依赖看看， 或者试着在你本地打包访问下打包文件看看有没有这种情况
> 
> 重新clone项目和重装依赖都试过了 还是不行 相同的报错

你试试从release那块下载下试试看

**Comment by wangjue666** [comment]
@BigCat20196  对了你的chrome版本是否是最新的

**Comment by BigCat20196** [comment]
> > > > 是的，带有isComponentFormSchema和formItem的都打不开。我觉得是个环境问题，还需要我提供哪些插件的版本呢？ 我只是clone了项目 然后pnpm install和pnpm run dev 没有修改过任何代码
> > > 
> > > 
> > > 没遇到这种情况，应该不是环境问题，试着重新安装下依赖看看， 或者试着在你本地打包访问下打包文件看看有没有这种情况
> > 
> > 
> > 重新clone项目和重装依赖都试过了 还是不行 相同的报错
> 
> 你试试从release那块下载下试试看

尝试了release的2.10.1 可以正常运行，没有报错
用的edge浏览器，内核版本120.0.2210.91

**Comment by wangjue666** [comment]
@BigCat20196  你换成chrome试试看

**Comment by BigCat20196** [comment]
> @BigCat20196 你换成chrome试试看

用chrome  121.0.6167.185
之前clone下来的和release下载的都可以 没报错，看来是浏览器的问题。不过edge用的也是google内核呀 :( 有点搞不懂

**Comment by wangjue666** [comment]
> 用chrome 121.0.6167.185 之前clone下来的和release下载的都可以 没报错，看来是浏览器的问题。不过edge用的也是google内核呀 :( 有点搞不懂

ok~, 能正常运行就好， 可能是解析js语法有出入吧

**Comment by Foglotus** [comment]
> > @BigCat20196 无法复现这个问题，你可以提供更详细的说明吗？例如：控制台报错信息、node已经pnpm版本、一个最小化可复现问题的repo等
> 
> node 版本20.11.1 pnpm版本8.15.4
> 
> ![image](https://private-user-images.githubusercontent.com/51037443/311150882-12a667a0-5323-43f0-bf4b-ad2377b03443.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MjY0MjEsIm5iZiI6MTcxMDcyNjEyMSwicGF0aCI6Ii81MTAzNzQ0My8zMTExNTA4ODItMTJhNjY3YTAtNTMyMy00M2YwLWJmNGItYWQyMzc3YjAzNDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDAxNDIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhOTFkM2M5MzFlYTEwY2M1NzUxMTI1OTdhZGNmYjUwMmI4MzFiODI5YTc2NjA4OTgwYWI3NWUxMDI0ZTExNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M2kJ8jskgLu9vDRYL-nSuOk5jK7lDMSZY2VVvlnImDQ)

我也遇到了相同的问题，F12控制台，Disable Cache后刷新正常，可能是缓存的问题。

**Comment by zhangyi1234** [comment]
2024年05月14日14:20:06 拉取main分支代码后,提示更新pnpm和nodejs出现了相同问题
按F12, Disable Cache解决
