### ISSUE TITLE
BasicForm在register配置CropperAvatar问题

### ISSUE THREAD

**Issue by kongchengxinde** [vbenjs/vue-vben-admin#3673]
版本2.8.0，在BasicForm组件中使用register配置CropperAvatar组件会出现报错
![606429345](https://github.com/vbenjs/vue-vben-admin/assets/45890956/24a4b0ae-39d9-407b-a40a-463aec2e5cf4)
![2619355185](https://github.com/vbenjs/vue-vben-admin/assets/45890956/824482ac-922c-4108-bd84-f3e90ecfeaf0)
这个该怎么解决

**Comment by anncwb** [comment]
Hello @kongchengxinde. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by likui628** [comment]
请提供完成的代码片段
