### ISSUE TITLE
BACK模式下,菜单名称读取方式不统一,有的读title有的读name,子菜单也是

### ISSUE THREAD

**Issue by dogfunc** [vbenjs/vue-vben-admin#3679]
拉了最新代码后在BACK模式下,
左侧菜单模式的菜单名称读取的是title,
顶部菜单模式 和 左侧菜单混合模式的菜单名称读取的是name,
读取方式不统一,我感觉是不是都取title好一些,

![image](https://github.com/vbenjs/vue-vben-admin/assets/41114616/d61d84cf-ed0b-4178-af88-04aaaa7bb292)
好像只有第一个模式都读取的title作为菜单名称,其他两个都不统一

如果回退这个更新的话就都统一了
![image](https://github.com/vbenjs/vue-vben-admin/assets/41114616/e82118f5-ed84-4eab-a1a7-05e0dbe7642d)

**Comment by lanochan** [comment]
TOP模式下菜单只显示英文，不显示中文
侧边正常。

**Comment by dogfunc** [comment]
> TOP模式下菜单只显示英文，不显示中文 侧边正常。

混合模式根目录名称显示英文,子带单名称显示中文

**Comment by dogfunc** [comment]
1
