### ISSUE TITLE
useEcharts does not work in List Rendering of Vue

### ISSUE THREAD

**Issue by doraemonxxx** [vbenjs/vue-vben-admin#3685]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

When I Used useEcharts and added inside the element list. The chart does not show and will throw an error  `root.appendChild is not a function at new SVGPainter2`

### Reproduction

```
   <div
      v-for="(data, index) in chartData"
    >
     <div ref="chartRef"></div>
    </div>
    
   import { useECharts } from '@/hooks/web/useECharts';
     
  const chartRef = ref<HTMLDivElement | null>(null);
  const { setOptions } = useECharts(chartRef as Ref<HTMLDivElement>);
  
    onMounted(() => {
     setOptions({});
    });

```
## System Info

- Operating System: Windows 11
- Node version:  v20.11.0
- Package manager (npm/yarn/pnpm) and version: pnpm 8.14.1

**Comment by zwtvip** [comment]
你这个不是会有多个chartRef，不应该要 :ref="chartRef"进行绑定？

**Comment by zwtvip** [comment]
@doraemonxxx 
`
<div
      v-for="(data, index) in chartData"
    >
     <div :ref="chartRef"></div>
</div>

const chartRefs: Ref<HTMLDivElement>[]= [];
const chartRef: Ref<HTMLDivElement>= refEl => {
  if (refEl) {
    chartRefs.push(refEl );
  }
};
function fn(i) {
     if (chartRefs.length > 0) {
        chartRefs.forEach((ref, i) => {
            if (i === j) {
               itemRefs[i].xxx(); // some function
          }
     });
  }
}
`

**Comment by zwtvip** [comment]
@doraemonxxx 
`
<div
      v-for="(data, index) in chartData"
    >
     <div :ref="chartRef" @click="fn(index)"></div>
</div>

const chartRefs: Ref<HTMLDivElement>[]= [];
const chartRef: Ref<HTMLDivElement>= refEl => {
  if (refEl) {
    chartRefs.push(refEl );
  }
};
function fn(i) {
     if (chartRefs.length > 0) {
        chartRefs.forEach((ref, j) => {
            if (i === j) {
               chartRefs[i].xxx(); // some function
          }
     });
  }
}
`

**Comment by zwtvip** [comment]
@doraemonxxx 
`
<div
      v-for="(data, index) in chartData"
    >
     <div :ref="chartRef" @click="fn(index)"></div>
</div>

const chartRefs: Ref<HTMLDivElement>[]= [];
const chartRef: Ref<HTMLDivElement>= refEl => {
  if (refEl) {
    chartRefs.push(refEl );
  }
};
function fn(i) {
     if (chartRefs.length > 0) {
        chartRefs.forEach((ref, j) => {
            if (i === j) {
               chartRefs[i].xxx(); // some function
          }
     });
  }
}
`
