### ISSUE TITLE
这个项目加载好慢好慢

### ISSUE THREAD

**Issue by itveteran9** [vbenjs/vue-vben-admin#3697]
这个项目加载好慢好慢 运行成功访问网页的时候 转半小时要

**Comment by wangjue666** [comment]
用本地开发预览吧, 毕竟用爱发电的，服务器带宽小

**Comment by xiaochen1** [comment]
难以置信， npm  run dev 进个首页，加载了几百个文件，几分钟了还在那转转转。。。。。
<img width="1440" alt="QQ20240420-201127@2x" src="https://github.com/vbenjs/vue-vben-admin/assets/20479179/5e5cc671-7cdf-442b-9310-cb66f0bcc351">
