### ISSUE TITLE
css-dev-only-do-not-override 样式覆盖如何关闭

### ISSUE THREAD

**Issue by kankantian** [vbenjs/vue-vben-admin#3705]
### 描述 Bug
![image](https://github.com/vbenjs/vue-vben-admin/assets/8832463/632ee308-7f41-4d0d-91e8-c91afde33d3c)
form组件样式覆盖，请问这个是如何出现的？如何关闭呢

## 系统信息
- vben-admin 2.10.1
- 
- 操作系统:
- Node 版本: 20.12.0
- 包管理器 (npm/yarn/pnpm) 及其版本: 8.15.5

**Comment by ahhxyz** [comment]
同问

**Comment by cMing1997** [comment]
@kankantian  @ahhxyz  正常写就行，只要你的css是在它的后面执行就行。例如 你框选的 要覆盖的话，就可以写
```less
.ant-form{
  font-size:16px
}
```

**Comment by axinss** [comment]
@kankantian @ahhxyz  这个问题其实是ant-design内部为了向下兼容而做的处理。并不会影响开发。

可以查看官方说明 https://next.antdv.com/docs/vue/compatible-style-cn
