### ISSUE TITLE
文件上传组件BUG及修复

### ISSUE THREAD

**Issue by tfzyxs** [vbenjs/vue-vben-admin#3711]
### 描述 Bug
/home/greatwall/li/vue-vben-admin/src/components/Upload/src/components/UploadModal.vue
async function handleStartUpload() {
    const { maxNumber } = props;
    if ((fileListRef.value.length + props.previewFileList?.length ?? 0) > maxNumber) {
      return createMessage.warning(t('component.upload.maxNumber', [maxNumber]));
    }

代码中的？？，有问题，应该是||

### 修复

async function handleStartUpload() {
    const { maxNumber } = props;
    if ((fileListRef.value.length + props.previewFileList?.length || 0) > maxNumber) {
      return createMessage.warning(t('component.upload.maxNumber', [maxNumber]));
    }

**Comment by likui628** [comment]
这个其实没什么问题，只是可读性不太强。
previewFileList本身有默认值为[]了，??和||都可以不用写

**Comment by likui628** [comment]
https://github.com/vbenjs/vue-vben-admin/commit/6528dc45df6efd829103cd10b3f3bc409148aa69
