### ISSUE TITLE
执行 pnpm  install   出现错误Unsupported URL Type "workspace:": workspace:*

### ISSUE THREAD

**Issue by DimplesHei** [vbenjs/vue-vben-admin#3716]
执行 pnpm  install   出现错误 Unsupported URL Type "workspace:": workspace:*

**Comment by wangjue666** [comment]
pnpm版本多少，更新成最新的试试

**Comment by DimplesHei** [comment]
node 版本 v20.11.1 
pnpm 版本 8.15.6

**Comment by DimplesHei** [comment]
> node 版本 v20.11.1
> pnpm 版本 8.15.6

**Comment by axinss** [comment]
我试了一下没有发现你说的这个错误。

建议你检查一下自己的package.json里面是否有书写错误

**Comment by DimplesHei** [comment]
之前是好的，把node_modules 删除，重新pnmp ，就出现上述问题。

**Comment by ywwsw** [comment]
加上 -w

**Comment by DimplesHei** [comment]
加上 -w  还是不行。

**Comment by RossWeisseLoVe** [comment]
加上 -wd
