### ISSUE TITLE
VITE_PROXY代理貌似只针对开发环境有效，生产环境配置VITE_PROXY代理接口会直接报错404，这也是我一个疑问点，生产环境使用VITE_PROXY代理难道无效？

### ISSUE THREAD

**Issue by fuckphptxt** [vbenjs/vue-vben-admin#3717]
![quirky](https://github.com/vbenjs/vue-vben-admin/assets/38744782/6c2f6798-a436-40f8-be19-f2c9e5d42c9e)

VITE_PROXY代理貌似只针对开发环境有效，生产环境配置VITE_PROXY代理接口会直接报错404，感觉没有代理上请求，这也是我一个疑问点，生产环境下使用VITE_PROXY代理难道无效？

**Comment by zwtvip** [comment]
生产环境你都mock怎么还是开着的

**Comment by fuckphptxt** [comment]
> 生产环境你都mock怎么还是开着的

目前还是测试环境，还没正式上线，这个到时候会改的，问题不大

**Comment by axinss** [comment]
https://cn.vitejs.dev/config/server-options.html#server-proxy

**官方文档明确说明是为开发服务器配置自定义代理规则**

**Comment by fuckphptxt** [comment]
> https://cn.vitejs.dev/config/server-options.html#server-proxy
> 
> **官方文档明确说明是为开发服务器配置自定义代理规则**
> 
> 生产环境的这个配置没用。直接配置Nginx做代理就可。
> 
> 并且，vben这个生产的代理应该只是用来为mock服务的。正常开发就不需要了

好的  已解决  感谢大佬

**Comment by Cys-cc** [comment]
但是 如果项目里面需求请求不同域名的端口 怎么配置阿  不管我怎么设置  部署上线以后 请求域名都是部署的域名,然后如果直接用 axios 发起请求就报错网络错误
