### ISSUE TITLE
第一次用vue。麻烦帮忙看下代码问题出在哪了。

### ISSUE THREAD

**Issue by Atw-Lee** [vbenjs/vue-vben-admin#3729]
### 描述 Bug
自定义封装的表单item，组件中调用了onChange后，验证的报错信息没有自动消失。手动validate之后是可以消失的。

### 复现 Bug
我理解的handleOk执行onchange，表单就有这个值了，手动validate也确实是有的，但是为什么提示信息没有随着它有值而消失呢？

```
defineOptions({ name: 'FormQueryBackService' });
  const attrs = useAttrs();
  const value = ref();

    const handleOk = () => {
    attrs.value?.onChange?.(selectRecord.value);
  };

  watchEffect(() => {
    const { tarName = '', tarCode = '' } = attrs?.value?.value ?? {};
    if (!tarName || !tarCode) {
      value.value = undefined;
    } else {
      value.value = `${tarCode}-${tarName}`;
    }
  });
```
<img width="304" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/95407716/8a4fb449-816e-48ca-a6df-50ca86d5d97e">

**Comment by Atw-Lee** [comment]
<img width="648" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/95407716/09c8e611-cdb3-408d-acbc-3ab007f8ca67">
我的解决办法是在回调里手动validate一下，但是感觉这样很呆。

**Comment by tinna123cjt** [comment]
组件参数里改下 itemProps: { validateTrigger: 'blur' },试试
