### ISSUE TITLE
pnpm dev 报错

### ISSUE THREAD

**Issue by Well634890** [vbenjs/vue-vben-admin#3735]
Failed to resolve entry for package "@vben/vite-config". The package may have incorrect main/module/exports specified in its package.json. [plugin externalize-deps]

node@20.11.0
pnpm@8.15.6

2024-04-11 16:50，克隆下来的代码

**Comment by moderateMan** [comment]
一样的问题

**Comment by moderateMan** [comment]
> 一样的问题

电脑是M1 pro的芯片，安装依赖报错
<img width="584" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/85022930/aef6ebf6-e972-41fd-b269-d3169cf82489">
去掉postInstall命令，运行npm run devb报错
<img width="1201" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/85022930/6f1cb933-e6ac-4956-aab3-b10620f86686">

**Comment by moderateMan** [comment]
> > 一样的问题
> 
> 电脑是M1 pro的芯片，安装依赖报错 <img alt="image" width="584" src="https://private-user-images.githubusercontent.com/85022930/322239512-aef6ebf6-e972-41fd-b269-d3169cf82489.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNTkzNTksIm5iZiI6MTcxMzA1OTA1OSwicGF0aCI6Ii84NTAyMjkzMC8zMjIyMzk1MTItYWVmNmViZjYtZTk3Mi00MWZkLWIyNjktZDMxNjljZjgyNDg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDAxNDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MDVlZWQ5OTEwNzMwZTE2MmI1M2EzMzE5MmFhZTMyNTQ5ZjZlYzY1MTA1M2NjNGQ0NTAyNWMyZDA5YzM1Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gnptwf2JtIgSHtCdM6JMFiSlUZDGTRzBfwDuNbYdQVc"> 去掉postInstall命令，运行npm run devb报错 <img alt="image" width="1201" src="https://private-user-images.githubusercontent.com/85022930/322239542-6f1cb933-e6ac-4956-aab3-b10620f86686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNTkzNTksIm5iZiI6MTcxMzA1OTA1OSwicGF0aCI6Ii84NTAyMjkzMC8zMjIyMzk1NDItNmYxY2I5MzMtZTZhYy00OTU2LWFhYjMtYjEwNjIwZjg2Njg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDAxNDQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZGQ4ZDUyNTVmZjUxYTFiNTA3YTgyODg0NTQ4YjIyYzVlYjQ1ZGQ5NWYxYzk4MWQ3MGViNjhmYzc0NGE5ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nI3X7UgnaGKJTwFEJF_AwLvty1BjScU70Y8kN_0VVF0">

<img width="430" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/85022930/7ed54765-fd90-4c01-b5b9-f1e9c5d93b0b">
手动执行了tsc对这个包进行了编译，然后运行成功了
