### ISSUE TITLE
更新PNPM版本

### ISSUE THREAD

**Issue by dacongda** [vbenjs/vue-vben-admin#3754]
### Subject of the feature

更新PNPM版本至9.x

### Problem

昨天发现仓库的CI寄了，检查发现是PNPM升级了版本到9.x，报不支持8.x的项目，希望能更新下项目的PNPM版本

**Comment by gnyuan** [comment]
刚刚做CI也发现了。先把pnpm版本固定下来。 `npm install --no-progress  -g pnpm@8.1.0`
