### ISSUE TITLE
ApiSelect 远程搜索功能似乎没有起作用

### ISSUE THREAD

**Issue by mlie-lh** [vbenjs/vue-vben-admin#3759]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

<img width="847" alt="image" src="https://github.com/vbenjs/vue-vben-admin/assets/17594199/f03423b5-93ea-4881-b877-7f92667d7c97">

这段代码好像因为`props.params`总是返回一个对象，在isEqual的时候被返回了，导致输入关键字无法继续往后进行查询

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by a141178** [comment]
请问这个问题有办法解决吗

**Comment by nanyaqinglongdev** [comment]
遇到相同问题,输入关键词没有搜索远程数据,而且搜索只能搜索value 不能搜索label 也没有相应的参数设置
