### ISSUE TITLE
升级依赖后 打包预览切换路由页面空白！！

### ISSUE THREAD

**Issue by fwd001** [vbenjs/vue-vben-admin#3783]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

![image](https://github.com/vbenjs/vue-vben-admin/assets/32030418/db92fb7d-3b4a-4a0d-b88d-eb97156feb8e)
升级依赖后切换路由页面空白报错
### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统: windows 11
- Node 版本: v18.19.1
- pnpm 版本: 9.0.5

**Comment by fwd001** [comment]
操作系统: windows 11
Node 版本: v18.19.1
pnpm 版本: 9.0.5

**Comment by zhiqiang-arctomsci** [comment]
一样问题

**Comment by zhiqiang-arctomsci** [comment]
![Uploading 微信图片_20240423190319.png…]()

**Comment by zhiqiang-arctomsci** [comment]
![Uploading 微信图片_20240423190319.png…]()

**Comment by zhiqiang-arctomsci** [comment]
一样问题

**Comment by fwd001** [comment]
是vue 新版本的问题，他们团队已经再提pr 了，目前解决方案退一个.23版本,

**Comment by fwd001** [comment]
> 一样问题

是vue 新版本的问题，他们团队已经再提pr 了，目前解决方案退一个.23版本,

**Comment by ShuangxiHan** [comment]
我vue回退到.23也不行，你们都是打包后切换路由才空白页的吗，我的在本地启动的时候切换路由就是空白页，但是我在同一个目录菜单切换是正常的，换个目录菜单切换就空白了，要重新刷新页面才显示

**Comment by zhiqiang-arctomsci** [comment]
> > 一样问题
> 
> 是vue 新版本的问题，他们团队已经再提pr 了，目前解决方案退一个.23版本,

退回并固定版本就正常了

**Comment by Jzow** [comment]
> 我vue回退到.23也不行，你们都是打包后切换路由才空白页的吗，我的在本地启动的时候切换路由就是空白页，但是我在同一个目录菜单切换是正常的，换个目录菜单切换就空白了，要重新刷新页面才显示

我也是换目录就不行了，请问解决了吗

**Comment by ShuangxiHan** [comment]
我的依然有问题，我不知道是什么原因，报了警告，
![image](https://github.com/vbenjs/vue-vben-admin/assets/143981998/85e0ef61-a5eb-4a43-9267-42bf18678a20)
只要有一个菜单报了这个警告，后面再点就会空白页

**Comment by wangjue666** [comment]
> 我的依然有问题，我不知道是什么原因，报了警告， ![image](https://private-user-images.githubusercontent.com/143981998/325239480-85e0ef61-a5eb-4a43-9267-42bf18678a20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMDc0OTYsIm5iZiI6MTcxNDAwNzE5NiwicGF0aCI6Ii8xNDM5ODE5OTgvMzI1MjM5NDgwLTg1ZTBlZjYxLWE1ZWItNGE0My05MjY3LTQyYmYxODY3OGEyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwMTA2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODljNTFmY2E5MDg3NGQ1Njc2ZDA1NjE3NzJjMDI2MDQwOWEwM2U4NzAxNDJhODVmNWY4NTkyOTE4OWIzMTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a0qJ6Qu7fQtz47yJXHXp_Y7aBPUqTh0M_m2y3meLanI) 只要有一个菜单报了这个警告，后面再点就会空白页

pnpm-lock.yaml 也要替换

**Comment by Jzow** [comment]
> 我的依然有问题，我不知道是什么原因，报了警告， ![image](https://private-user-images.githubusercontent.com/143981998/325239480-85e0ef61-a5eb-4a43-9267-42bf18678a20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMDk0MjgsIm5iZiI6MTcxNDAwOTEyOCwicGF0aCI6Ii8xNDM5ODE5OTgvMzI1MjM5NDgwLTg1ZTBlZjYxLWE1ZWItNGE0My05MjY3LTQyYmYxODY3OGEyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNVQwMTM4NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWJiZjYyODAyNjhjZmM0MzM5MmEzMTE0MWUwYTMwMTYwYWFlNTNlNzhhZTM1M2JkMDI2MDRkZTM3OWQ2YWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X9C5x2VnxtzCW0CK7FycYRwAmE9CA17zLqCqqS2r1e8) 只要有一个菜单报了这个警告，后面再点就会空白页

这句话的意思是组件渲染无法设置动画的非元素根节点

如果退回版本和替换`pnpm-lock.yaml`文件还是不正常，就请检查你报警告的index.vue文件，最外层需要用`<div>`标签包起来
```vue
<template>
  <div>
  　　<div></div>
    ~someone~
  </div>
</template>
```
