### ISSUE TITLE
合并最新代码后，input 输入框右边的 x 号点击，无法删除出入的内容，报错

### ISSUE THREAD

**Issue by Tairy** [vbenjs/vue-vben-admin#3791]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

合并了近期更新的代码之后，发现 input 输入框的 x 点击之后无法删除输入内容，并报错了

### Reproduction

![image](https://github.com/vbenjs/vue-vben-admin/assets/2605905/8dbf3160-f67a-4261-9f23-8e13bf5d3216)

**Comment by cszhjh** [comment]
antdesign vue的bug，[issue](https://github.com/vueComponent/ant-design-vue/issues/7524)

**Comment by cszhjh** [comment]
最新合并的代码已经解决这个问题
