### ISSUE TITLE
表单增删示例中，输入框清空按钮无效

### ISSUE THREAD

**Issue by ShuangxiHan** [vbenjs/vue-vben-admin#3793]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug
开发中发现表单增删中的输入框的清空按钮无效，然后去官网的演示环境查看依然无效

### 复现 Bug
![image](https://github.com/vbenjs/vue-vben-admin/assets/143981998/055e68a6-2787-4a7b-a487-89fe42fa327a)

## 系统信息

- 操作系统: Windows11
- Node 版本: 18.16.1
- pnpm 版本: 9.0.4

**Comment by 6LWa6ZKx** [comment]
已经修复了，等合并。或者自行升级版本

https://github.com/vbenjs/vue-vben-admin/pull/3790
