### ISSUE TITLE
有穿梭框的组件吗,多个穿梭框组件还可关联的,demo组件中没看到

### ISSUE THREAD

**Issue by QingShan09** [vbenjs/vue-vben-admin#3801]
就类似于这种的
![Snipaste_2024-04-29_17-47-58](https://github.com/vbenjs/vue-vben-admin/assets/150325660/349a2bdd-95f8-415c-80e0-db80fc2d446f)

**Comment by pengguan06** [comment]
要自己写吧，使用antdv官方组件
