### ISSUE TITLE
vue 修饰符的使用

### ISSUE THREAD

**Issue by johnsnow20087349** [vbenjs/vue-vben-admin#3824]
### Subject of the feature

没有找到对vue修饰符的使用介绍

### Problem

比如：.trim，一般在input框中会考虑加这个来清空空白，看了文档，似乎没有这方面的使用介绍。

[vue修饰符](https://cn.vuejs.org/guide/essentials/forms#modifiers)
`<input v-model.trim="msg" />`

### Expected behaviour

希望有这个功能

**Comment by coderwyd** [comment]
直接看vue文档不就好了

**Comment by johnsnow20087349** [comment]
> 直接看vue文档不就好了

文档肯定是看了的，vue文档人家是写在v-model后面的，而这个就不知道写在哪里了，vben的文档里没有这个的描述，你知道咋写吗
