### ISSUE TITLE
如何实现不隐藏没权限的菜单，但是点击时提示无权限？

### ISSUE THREAD

**Issue by klgd** [vbenjs/vue-vben-admin#3834]
RT
现在路由设置role后，没有权限的话，菜单也是不显示了，有无设置可以让没有权限的角色也可以看到菜单，但是点击菜单时提示无权限？

**Comment by chenwei1109** [comment]
这个可以改啊，现在的菜单策略都是没权限的东西不让用户看到，在获取权限的时候过滤掉了，你可以自己修改不过滤，设置指令点击无权限的菜单添加无权限提示
