### ISSUE TITLE
axios方法为put时，提示网络请求错误,请求方法未允许

### ISSUE THREAD

**Issue by lackoxy** [vbenjs/vue-vben-admin#3845]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

发送put方式接口请求时，系统提示“网络请求错误,请求方法未允许!” 控制台后台提示错误代码为405

### 复现 Bug
接口代码
![image](https://github.com/vbenjs/vue-vben-admin/assets/57206117/8f07d207-2cf6-493e-95b1-ab51d25c5e81)
请求后系统提示
![image](https://github.com/vbenjs/vue-vben-admin/assets/57206117/f4b47a7f-f07e-4ebb-9e02-cb933d6ed461)
控制台错误展示
![image](https://github.com/vbenjs/vue-vben-admin/assets/57206117/fe75d64a-2577-45b9-8936-c4c6c82952bf)

## 系统信息

- 操作系统:
- Node 版本: v18.20.0
- pnpm 版本: v9.1.0

**Comment by lackoxy** [comment]
defhttp.get defhttp.post defhttp.delete均可以使用

**Comment by HughCodeX** [comment]
405状态码表示服务器无法处理你请求中指定的方法，跟你前端代码没关系

**Comment by lackoxy** [comment]
> 405状态码表示服务器无法处理你请求中指定的方法，跟你前端代码没关系

但是后端代码使用postman测试是完全可行的，是我后端代码的问题吗

**Comment by HughCodeX** [comment]
> > 405状态码表示服务器无法处理你请求中指定的方法，跟你前端代码没关系
> 
> 但是后端代码使用postman测试是完全可行的，是我后端代码的问题吗
我也是自己写的后端代码测试，postman和项目里axios请求都是可通的，建议你排查一下后端哪里配置出问题了

**Comment by HughCodeX** [comment]
> > 405状态码表示服务器无法处理你请求中指定的方法，跟你前端代码没关系
> 
> 但是后端代码使用postman测试是完全可行的，是我后端代码的问题吗

我也是自己写的后端代码测试，postman和项目里axios请求都是可通的，建议你排查一下后端哪里配置出问题了

**Comment by lackoxy** [comment]
后端我排查了一遍，个人感觉没什么问题，但是在排查前端的时候我发现一个很神奇的事情
接口方法
![image](https://github.com/vbenjs/vue-vben-admin/assets/57206117/8027b214-0e09-41b1-a4b0-e1891c98ea80)
我在此处分别打印了config 与 深拷贝后的conf （Axios.ts）
![image](https://github.com/vbenjs/vue-vben-admin/assets/57206117/3ddbdffc-9db0-434a-97f2-a8edff505412)
但打印后发现原本传入的params在深拷贝后莫名奇妙变成了conf中的data，这个是什么问题导致的（前不久才刚开始学习前端所以对一些原理可能不是很了解，请见谅）

**Comment by HughCodeX** [comment]
> 后端我排查了一遍，个人感觉没什么问题，但是在排查前端的时候我发现一个很神奇的事情 接口方法 ![image](https://private-user-images.githubusercontent.com/57206117/331024351-8027b214-0e09-41b1-a4b0-e1891c98ea80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjgwODQsIm5iZiI6MTcxNTgyNzc4NCwicGF0aCI6Ii81NzIwNjExNy8zMzEwMjQzNTEtODAyN2IyMTQtMGUwOS00MWIxLWE0YjAtZTE4OTFjOThlYTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyNDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNzdlOTVmNDAwNDQxYjI1ZmQyOWZmYzMxY2RkZDdiMTEzM2UwMGFjYzk1MWM2N2E4YmQ4MjI5YTZiZDU5YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sHQ65n0UBhnixWXnKvZYlcVWniUqxyLOu8lX9J27fP8) 我在此处分别打印了config 与 深拷贝后的conf （Axios.ts） ![image](https://private-user-images.githubusercontent.com/57206117/331024898-3ddbdffc-9db0-434a-97f2-a8edff505412.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjgwODQsIm5iZiI6MTcxNTgyNzc4NCwicGF0aCI6Ii81NzIwNjExNy8zMzEwMjQ4OTgtM2RkYmRmZmMtOWRiMC00MzRhLTk3ZjItYThlZGZmNTA1NDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyNDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYTM4YTc2YTFmYTdlN2E3ODIxYjkwYmU2ZWIwMjJjNTFjZGQ4M2YwZDQ0NzcwOTQ1NzFiYzJjYmJmMjk4OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NiVcZEQ1mdFAjPgZ-FaobEOqb5Lz92eizMaIGw0iheU) 但打印后发现原本传入的params在深拷贝后莫名奇妙变成了conf中的data，这个是什么问题导致的（前不久才刚开始学习前端所以对一些原理可能不是很了解，请见谅） ![image](https://private-user-images.githubusercontent.com/57206117/331025808-720ecee6-a2f3-49c2-808b-567c38b91f2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjgwODQsIm5iZiI6MTcxNTgyNzc4NCwicGF0aCI6Ii81NzIwNjExNy8zMzEwMjU4MDgtNzIwZWNlZTYtYTJmMy00OWMyLTgwOGItNTY3YzM4YjkxZjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyNDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYmNkZDdmZTM1MWM3YjY3ZWM0ZDAyMGQyOTk5ZjIyNDI1Mjg3MmJmOTE0NDI0MWM5ZWViODFjYzgwYzlkYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NLgh2vqSbsgQCEcntcmUbGDCTNdZ-XdIcsYwVGphZlk)

因为你用console.log打印对象的时候，浏览器是获取这个对象初始值的快照，你可以看到对象展开前两个值是一样的，这说明他们初始值一样。但是当你去展开这个对象的时候，代码已经执行完毕了，重新获取到的是修改之后的值。如果你想要看到conf准确的是初始值，你可以这样打印

**Comment by lackoxy** [comment]
> > 后端我排查了一遍，个人感觉没什么问题，但是在排查前端的时候我发现一个很神奇的事情 接口方法 ![image](https://private-user-images.githubusercontent.com/57206117/331024351-8027b214-0e09-41b1-a4b0-e1891c98ea80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjgwODQsIm5iZiI6MTcxNTgyNzc4NCwicGF0aCI6Ii81NzIwNjExNy8zMzEwMjQzNTEtODAyN2IyMTQtMGUwOS00MWIxLWE0YjAtZTE4OTFjOThlYTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyNDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkNzdlOTVmNDAwNDQxYjI1ZmQyOWZmYzMxY2RkZDdiMTEzM2UwMGFjYzk1MWM2N2E4YmQ4MjI5YTZiZDU5YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sHQ65n0UBhnixWXnKvZYlcVWniUqxyLOu8lX9J27fP8) 我在此处分别打印了config 与 深拷贝后的conf （Axios.ts） ![image](https://private-user-images.githubusercontent.com/57206117/331024898-3ddbdffc-9db0-434a-97f2-a8edff505412.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjgwODQsIm5iZiI6MTcxNTgyNzc4NCwicGF0aCI6Ii81NzIwNjExNy8zMzEwMjQ4OTgtM2RkYmRmZmMtOWRiMC00MzRhLTk3ZjItYThlZGZmNTA1NDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyNDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlYTM4YTc2YTFmYTdlN2E3ODIxYjkwYmU2ZWIwMjJjNTFjZGQ4M2YwZDQ0NzcwOTQ1NzFiYzJjYmJmMjk4OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NiVcZEQ1mdFAjPgZ-FaobEOqb5Lz92eizMaIGw0iheU) 但打印后发现原本传入的params在深拷贝后莫名奇妙变成了conf中的data，这个是什么问题导致的（前不久才刚开始学习前端所以对一些原理可能不是很了解，请见谅） ![image](https://private-user-images.githubusercontent.com/57206117/331025808-720ecee6-a2f3-49c2-808b-567c38b91f2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjgwODQsIm5iZiI6MTcxNTgyNzc4NCwicGF0aCI6Ii81NzIwNjExNy8zMzEwMjU4MDgtNzIwZWNlZTYtYTJmMy00OWMyLTgwOGItNTY3YzM4YjkxZjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAyNDk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYmNkZDdmZTM1MWM3YjY3ZWM0ZDAyMGQyOTk5ZjIyNDI1Mjg3MmJmOTE0NDI0MWM5ZWViODFjYzgwYzlkYTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NLgh2vqSbsgQCEcntcmUbGDCTNdZ-XdIcsYwVGphZlk)
> 
> 因为你用console.log打印对象的时候，浏览器是获取这个对象初始值的快照，你可以看到对象展开前两个值是一样的，这说明他们初始值一样。但是当你去展开这个对象的时候，代码已经执行完毕了，重新获取到的是修改之后的值。如果你想要看到conf准确的是初始值，你可以这样打印
> 
> ```
>     console.log('config :>> ', JSON.stringify(config));
>     console.log('conf :>> ', JSON.stringify(conf));
> ```
谢谢你的解答，至于为什么params变成了data，我在beforeRequestHook（axios/index.ts）这个函数下找到了答案
![image](https://github.com/vbenjs/vue-vben-admin/assets/57206117/1a8e49ae-7e73-4edd-bd93-8de76c688e6c)
至于前面的405问题，我发现确实原因在我，我前端接口url写错了，还是再次谢谢你耐心解答我的问题
