### ISSUE TITLE
官方demo严重UI问题，select 与结果页相分离

### ISSUE THREAD

**Issue by hegang8** [vbenjs/vue-vben-admin#3848]
![Image_20240516164734](https://github.com/vbenjs/vue-vben-admin/assets/26988806/aa4445ef-93c7-4a96-8683-4d7f9791b9ee)

**Comment by fourteendp** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/53899166/f88e9218-f9ff-4d19-badf-7355a770cfb2)

**Comment by majian12344321** [comment]
> ![image](https://private-user-images.githubusercontent.com/53899166/342972001-f88e9218-f9ff-4d19-badf-7355a770cfb2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDE5MzUsIm5iZiI6MTcxOTQwMTYzNSwicGF0aCI6Ii81Mzg5OTE2Ni8zNDI5NzIwMDEtZjg4ZTkyMTgtZjlmZi00ZDE5LWJhZGYtNzM1NWE3NzBjZmIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDExMzM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NGI2YjE0ZjRjYmUyZDM0NmJjZGYxNTY4ZGExNDI2MDJkZGIxOGMwYWI5ZDgyMzBjODRmNWQwZDBiMWYxZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x_Bd8MBx_GdyErBG_fss__8wOexrIRiTOPyN5pTcpr8)

你试着往下滑动一下

**Comment by fourteendp** [comment]
复现了，先打开下拉框然后滚动并没有跟随或关闭

**Comment by majian12344321** [comment]
这是一封自动回复邮件。已经收到您的来信。

**Comment by majian12344321** [comment]
这是一封自动回复邮件。已经收到您的来信。
