### ISSUE TITLE
使用setWatermark设置水印，刷新页面后水印会消失

### ISSUE THREAD

**Issue by ye17186** [vbenjs/vue-vben-admin#3862]

**Comment by pengguan06** [comment]
全局使用的话放这里试试 src\layouts\default\index.vue

**Comment by ye17186** [comment]
做一下修改，即可在页面展示水印了，谢谢大佬
`
<Watermark :content="[userStore.getUserInfo.username, userStore.getUserInfo.realName]">
<PageLayout />
</Watermark>
`

**Comment by ye17186** [comment]
close
