### ISSUE TITLE
table中的columns设置了with，table的列还是对不齐

### ISSUE THREAD

**Issue by mike3344557788** [vbenjs/vue-vben-admin#3879]
![截屏2024-05-27 16 53 47](https://github.com/vbenjs/vue-vben-admin/assets/169156909/b49ebc69-2869-40eb-a1b8-ec3a972d2020)

**Comment by majian12344321** [comment]
> ![截屏2024-05-27 16 53 47](https://private-user-images.githubusercontent.com/169156909/334108453-b49ebc69-2869-40eb-a1b8-ec3a972d2020.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDIxNjAsIm5iZiI6MTcxOTQwMTg2MCwicGF0aCI6Ii8xNjkxNTY5MDkvMzM0MTA4NDUzLWI0OWViYzY5LTI4NjktNDBlYi1hMWI4LWVjM2E5NzJkMjAyMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxMTM3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmNhMDhjM2NjOGY0ZjlkMjU2OTc5OGU2NDU1ODFlODdlYjEyYTgwNGQzODNiZGYzODc3NzE1ZmYwNmI5ZWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fJKk_Wy9vVu9_rALTZTrZry-zs1V62KmcjmbX6hj6aM)

这个框架没啥毛病  但是 UI 属于劝退型的  你把每个tab的宽度 width: 180,   就可以了  这个框架需要18CM
