### ISSUE TITLE
版本高于nodejs18的时候报错

### ISSUE THREAD

**Issue by ZHIFENG1991** [vbenjs/vue-vben-admin#3889]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

版本高于nodejs18的时候报错

### 复现 Bug

nodejs版本安装20或者22

## 系统信息

- 操作系统:windows11
- Node 版本:20.11.1
- pnpm 版本:9.1.4

**Comment by wangjue666** [comment]
报错信息是什么 ci就是用的 node的18和20版本呀 都可以正常编译打包

**Comment by ZHIFENG1991** [comment]
![screenshot-20240604-164141](https://github.com/vbenjs/vue-vben-admin/assets/25770157/46d2e047-bb27-44eb-9a7a-0af1f771af23)

**Comment by ZHIFENG1991** [comment]
> 报错信息是什么 ci就是用的 node的18和20版本呀 都可以正常编译打包

![screenshot-20240604-164141](https://github.com/vbenjs/vue-vben-admin/assets/25770157/3fec298d-219c-4742-9604-980a342aa2d2)

**Comment by ZHIFENG1991** [comment]
> 你拉取下仓库最新代码运行看看

就是刚刚拉了重新跑的,nodejs18可以,20不行

**Comment by wangjue666** [comment]
你是用的nvm工具切换node版本吗

**Comment by ZHIFENG1991** [comment]
> 你是用的nvm工具切换node版本吗

是的

**Comment by wangjue666** [comment]
我是win10系统 试了下20跟21版本都正常运行呢， 你身边有其他电脑吗

**Comment by ZHIFENG1991** [comment]
> 我是win10系统 试了下20跟21版本都正常运行呢， 你身边有其他电脑吗

算了吧,18凑合用算了,感觉只有我有问题,没看到有别人遇到
