### ISSUE TITLE
菜单标签设置中设置 dot 为 true，content:'1'，该菜单项没有显示小圆点也没有显示content的内容

### ISSUE THREAD

**Issue by wangchaoxx** [vbenjs/vue-vben-admin#3899]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/). 并且该功能在文档中有描述
- [x] 代码为main分支最新
- [x] 不在Issues中
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

在路由配置项添加 tag 属性提示“对象字面量只能指定已知属性，并且“tag”不在类型“AppRouteRecordRaw”中。”，并且该菜单项没有显示小圆点也没有显示content的内容

### 复现 Bug

在任何一个路由配置项总添加标签设置代码
文件位置：src/router/routes/basic.ts

```
export const ERROR_LOG_ROUTE: AppRouteRecordRaw = {
  path: '/error-log',
  name: 'ErrorLog',
  component: LAYOUT,
  redirect: '/error-log/list',
  meta: {
    title: 'ErrorLog',
    hideBreadcrumb: true,
    hideChildrenInMenu: true,
  },
  tag: {
    type: 'error',
    dot: true,
    content: '1',
  },
  children: [
    {
      path: 'list',
      name: 'ErrorLogList',
      component: () => import('@/views/sys/error-log/index.vue'),
      meta: {
        title: t('routes.basic.errorLogList'),
        hideBreadcrumb: true,
        currentActiveMenu: '/error-log',
      },
      tag: {
        type: 'error',
        dot: true,
        content: '1',
      },
    },
  ],
};

```

![image](https://github.com/vbenjs/vue-vben-admin/assets/42869522/39ea8fc9-a917-4fb3-b9a0-7da01f5760de)

## 系统信息

- 操作系统: macos 13.2.1
- Node 版本: v21.7.1
- pnpm 版本: 9.1.3

**Comment by sunxy** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/5026875/dd3db10f-fc6b-4368-8488-9f4c340b220e)
![image](https://github.com/vbenjs/vue-vben-admin/assets/5026875/bbb8f708-3eae-4353-a364-07d845fe7baf)
