### ISSUE TITLE
Modal的visible-change事件不触发

### ISSUE THREAD

**Issue by PuYunXi** [vbenjs/vue-vben-admin#3901]
### 描述 Bug

从2.8升级到2.11后,将页面迁移到新版本时发现Modal的打开关闭事件不再触发,仓库最新的demo也能复现

### 复现 Bug
仓库源码 Modal4.vue
![image](https://github.com/vbenjs/vue-vben-admin/assets/39524883/f56d3ef8-de76-4c2a-8fbd-149f0a397cb0)

**Comment by liunnn1994** [comment]
文档错误，看了源码发现改名叫 open-change 了
![image](https://github.com/vbenjs/vue-vben-admin/assets/23442840/2009f120-46bb-4a55-954e-1dfa9b6cac31)
