### ISSUE TITLE
Question: Why were the timestamp and hash removed in application.ts

### ISSUE THREAD

**Issue by doraemonxxx** [vbenjs/vue-vben-admin#3905]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

# Question

https://github.com/vbenjs/vue-vben-admin/commit/dcbe5510d42c3dc5e93b68704a5fa24c88d4de69

> Update docker packaging logic: The original fixed entry is to facilitate the replacement of environment variables, and in the nginx configuration, each time you get js and other resources, you don't need to use the cache. The problem is that the first opening will be very slow.
> Therefore, the solution used this time is to return to the original hash+timestamp entry file name of vben, but use fuzzy matching when replacing environment variables.
> 

Why were the timestamp and hash removed in https://github.com/vbenjs/vue-vben-admin/commit/a6086f4cc8f33fea7431f3d39eb73dda20c325bd?

The commit message in the revision https://github.com/vbenjs/vue-vben-admin/commit/dcbe5510d42c3dc5e93b68704a5fa24c88d4de69 mentions that keeping the timestamp and hash would enhance the app's loading speed during the initial opening or load.

**Comment by likui628** [comment]
没有时间戳没问题的，但是不保留hash值就不对了
应该是这样的`entryFileNames: assets/entry/[name]-[hash].js`
