### ISSUE TITLE
UploadPreviewModal.vue的lint错误

### ISSUE THREAD

**Issue by dacongda** [vbenjs/vue-vben-admin#3906]
### 描述 Bug

components/Upload/src/components/UploadPreviewModal.vue 在允许lint检查时报错

https://github.com/vbenjs/vue-vben-admin/blob/8d3981f599f073b226c822a8d28af9aecf00a667/src/components/Upload/src/components/UploadPreviewModal.vue#L100

这地方的赋值是有什么特殊的必要的

### 复现 Bug

运行 `pnpm run lint:eslint`

**Comment by electroluxcode** [comment]
看起来没有什么必要赋值哈哈
