### ISSUE TITLE
通知组件打开导致页面卡死。整个页面本地运行都明显感觉到卡顿或者说有延迟，不管是切换页面还是点击事件等等

### ISSUE THREAD

**Issue by chenwei1109** [vbenjs/vue-vben-admin#3909]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- pnpm version:

**Comment by nongyehong** [comment]
这个可能是Ant-Design-Vue中的Typography.Paragraph组件的ellipsis参数出现的问题，把ellipsis设置的{ rows: xxx }里面的参数去掉，ellipsis是可以接收boolean | ellipsis类型的，所以你直接设置为true就可以了，但就会导致ellipsis中的功能无法使用了。

**Comment by nongyehong** [comment]
但是你去看官方给的浏览链接却是可以正常使用的
