### ISSUE TITLE
vxe-table 更新后，编译报错

### ISSUE THREAD

**Issue by KaneOne** [vbenjs/vue-vben-admin#3913]
项目流水线部署报错，
![image](https://github.com/vbenjs/vue-vben-admin/assets/1954595/5938ae63-c2fc-442f-bfe1-f672d52415d3)
查看发现vxe-table 依赖更新到4.7.9，原styles目录下，没有index.scss文件了

**Comment by chenbanghe** [comment]
怎么解决呢

**Comment by KaneOne** [comment]
> 怎么解决呢

styles目录下有一个all.scss文件，我把引用从index 改为all了，demo看起来样式没有变化
