### ISSUE TITLE
当表格值为0，且column设置了edit: true的情况下，页面这格会显示空白

### ISSUE THREAD

**Issue by HoboCY** [vbenjs/vue-vben-admin#3914]
我给column设置了edit: true，然后某一行的这列值为0，结果页面这一格就显示空白，是否有解决方案
![image](https://github.com/vbenjs/vue-vben-admin/assets/31683826/d1088646-d9c7-4773-8b3f-420e062830f0)
![image](https://github.com/vbenjs/vue-vben-admin/assets/31683826/2a754ce5-9d3c-4517-b0ae-d222cdc54362)

**Comment by a1043860923** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/37471049/80082bcb-b842-43f9-89d6-102e5d174030)
![image](https://github.com/vbenjs/vue-vben-admin/assets/37471049/25f15d66-616f-495f-a343-cde4a955f616)
未复现出来，不知道是不是已修复了
