### ISSUE TITLE
疑似hook的回调造成的进程阻塞

### ISSUE THREAD

**Issue by yvygyyth** [vbenjs/vue-vben-admin#3934]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

匿名回调执行时间过长

### Reproduction

我在写一个对拖拽元素进行自定义的demo，使用了用render方法挂载自定义vue模块的方式（类似全局消息提示），但是不知道为什么在这个项目使用会有卡顿，一开始是用每次拖拽创建，放下销毁的方式一次就会开始卡顿，后来换成先创建一个，只是修改prop传入数据，多次执行后还是存在卡顿，拖拽事件文件放在了hook文件夹下

## System Info

- Operating System:windows 11
- Node version:v20.15.0
- pnpm version:9.4.0
[Uploading Trace-20240628T172147.json…]()

**Comment by JACK-ZHANG-coming** [comment]
我也遇到了类似问题，我引入了antv x6拖拽，每次拖拽都会更新所有pinia的函数（但是我并没有这样的写），只要一用拖拽就很卡，需要紧急修复，求大佬指点
