### ISSUE TITLE
为兼容谷歌v87以下版本 在使用antd 的 StyleProvider时所有antd的组件均无法加载出来

### ISSUE THREAD

**Issue by AALiujiajun** [vbenjs/vue-vben-admin#3946]
### Describe the bug

目前需要兼容谷歌v87以下版本 使用了legacy后能成功加载文件打开但是antd4的where写法不能在87以下执行 所以渲染不出组件 遂使用
StyleProvider对antd进行处理 在App.vue

  <ConfigProvider :locale="getAntdLocale" :theme="themeConfig">
    <StyleProvider hash-priority="high" :transformers="[legacyLogicalPropertiesTransformer]">
    <AppProvider>
      <RouterView />
    </AppProvider>
  </StyleProvider>
  </ConfigProvider>

后大量样式无法展示且 antv组件也无法渲然 请问有无解决办法

版本为3月份的版本 antd为最新版本4.3

**Comment by liudenaxietian** [comment]
我也遇到了同样的问题 目前在chrome内核版本为V86.0.4240.198的浏览器上面无法渲染出页面  有哪位大神知道是什么原因导致的呀
