### ISSUE TITLE
开启控制台后，页面卡顿严重

### ISSUE THREAD

**Issue by 1455668754** [vbenjs/vue-vben-admin#3947]
开启控制台后，页面卡顿严重

**Comment by ADogc** [comment]
我也遇到了这个问题，持续关注一下

**Comment by 246859** [comment]
我也遇到了同样的问题，关注下

**环境**
node: v20.11.1
pnm: 9.4.0
vben: 2.11.5
os：win10
Chrome: 126.0.6478.127

**描述**
在**开发模式**下打开浏览器控制台，页面会逐渐变的卡顿，直到最后浏览器进程几乎卡死，强制kill掉浏览器后，重新执行`pnpm vite`命令，此时再次打开浏览器即便不打开控制台也会有严重卡顿，只有重启电脑才能恢复。

**Comment by BigRockCandy** [comment]
我也遇到了这个问题，持续关注一下

**Comment by jiagnhu** [comment]
我也遇到这个问题，这是什么原因引起的？刚开始做功能的时候，还没有察觉到，等功能越来越多时，就很明显的卡顿。

**Comment by 246859** [comment]
> 我也遇到这个问题，这是什么原因引起的？刚开始做功能的时候，还没有察觉到，等功能越来越多时，就很明显的卡顿。

用2.11.4版本就没有这个问题了
