### ISSUE TITLE
添加全局Loading效果

### ISSUE THREAD

**Issue by Thunder7991** [vbenjs/vue-vben-admin#3952]
我希望在发起请求的时候，添加全局的loading，等待全部请求结束后，自动关闭 。 这个功能可以实现吗，或者有没有其他的可替代的办法。

**Comment by zwtvip** [comment]
这个自己用里面封装好的loading组件实现，你可以在封装好的axios 添加自己的loading配置，针对某些接口是否开启

**Comment by wodb** [comment]
我是这样实现的，在局部定义了个loading的方法。然后加载和关闭数量对应后在隐藏

`export function useLoading(
  opt: Partial<LoadingProps> | Partial<UseLoadingOptions>,
): [Fn, Fn, (string) => void] {
  let props: Partial<LoadingProps>;
  let target: HTMLElement | Ref<ElRef> = document.body;
  let scope = true;

  if (Reflect.has(opt, 'target') || Reflect.has(opt, 'props') || Reflect.has(opt, 'scope')) {
    const options = opt as Partial<UseLoadingOptions>;
    props = options.props || {};
    target = options.target || document.body;
    scope = options.scope || true;
  } else {
    props = opt as Partial<LoadingProps>;
  }

  let loadingCount = 0;

  const instance = createLoading(props, undefined, true);

  const open = (): void => {
    const t = unref(target as Ref<ElRef>);
    if (!t) return;
    if (loadingCount === 0) {
      instance.open(t);
    }
    loadingCount += 1;
  };

  const close = (): void => {
    if (loadingCount <= 0) {
      return;
    }
    loadingCount -= 1;
    if (loadingCount === 0) {
      instance.close();
    }
  };

  const setTip = (tip: string) => {
    instance.setTip(tip);
  };

  scope &&
    tryOnUnmounted(() => {
      instance.destroy();
    });

  return [open, close, setTip];
}

const [showLoading, hideLoading] = useLoading({ scope: false });

export { showLoading, hideLoading };
`
