### ISSUE TITLE
BasicUpload 删除失效

### ISSUE THREAD

**Issue by ZackLeonardo** [vbenjs/vue-vben-admin#3958]
\vue-vben-admin\src\components\Upload\src\components\UploadModal.vue  中删除方法失效，record.uuid修改为record.record.uuid可以获取到uuid

// 删除
  function handleRemove(record: FileItem) {
    const index = fileListRef.value.findIndex((item) => item.uuid === record.uuid);
    index !== -1 && fileListRef.value.splice(index, 1);
    isUploadingRef.value = fileListRef.value.some(
      (item) => item.status === UploadResultStatus.UPLOADING,
    );
    emit('delete', record);
  }

**Comment by BenXi630** [comment]
还是有问题，index永远都是 0
