### ISSUE TITLE
Input组件field为search时，使用setFieldsValue，value校验为Funtion异常

### ISSUE THREAD

**Issue by gzq0616** [vbenjs/vue-vben-admin#3966]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
使用setFieldsValue, key为search时报value校验值错误

请清晰地描述此 Bug 的具体表现。

### 复现 Bug
首先定义schema，field设置为search
export const searchSchema: FormSchema[] = [
  {
    field: 'search',
    label: '搜索',
    component: 'Input',
    colProps: { span: 8 },
  },
];

然后使用setFieldsValue设置form
setFieldsValue({search: 'test'})

 Invalid prop: type check failed for prop "value". Expected String | Number | Symbol, got Function

**Comment by clddup** [comment]
![image](https://github.com/user-attachments/assets/acea0ffc-61fc-406a-aeab-92828c4460af)

排查了下, 主要是这个原因, value是你的值'test',   然后 `get(value, key)`  其实获取到的是字符串的 `search`方法, 现在还不清楚这里为什么要这么做, 为什么不直接用value, 而是还需要 `get(value, key)`判断一下是否有值
