### ISSUE TITLE
Chrome浏览器兼容性问题

### ISSUE THREAD

**Issue by liudenaxietian** [vbenjs/vue-vben-admin#3969]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

在Chrome浏览器(内核版本V86.0.4240.198)下 部分区域显示空白

### Reproduction

在改版本浏览器下打开完整版链接即可重现

## System Info

- Operating System: window10
- Node version: V18
- pnpm version :V9.2

**Comment by M69W** [comment]
开启 legacy  试试？

**Comment by liudenaxietian** [comment]
试过了 开启legacy打包兼容旧版浏览器的包 部署后也是不行呀！
