### ISSUE TITLE
多系统多服务，如何把某一个页面共享给其他系统作为内嵌，在其他系统中打开？

### ISSUE THREAD

**Issue by dyzhuang** [vbenjs/vue-vben-admin#3975]
### Subject of the feature

多系统多服务，如何把某一个页面共享给其他系统作为内嵌，在其他系统中打开？

### Problem

我的项目有多套系统，需要把我做好的某个功能业务共享给其他系统打开，他打开的只有我共享的单独页面。就像我们内嵌其他页面一样给其他系统内嵌。在Vben中要如何实现？

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by zwtvip** [comment]
有个独立路由main-out模块

**Comment by dyzhuang** [comment]
非常感觉，非常棒的一个框架。

**Comment by honghonghong-plus** [comment]
可以考虑蚂蚁金服的 乾坤微服务框架
