### ISSUE TITLE
ApiSelect组件，设置默认参数后，通过api请求联动效果，数据渲染失败

### ISSUE THREAD

**Issue by jy-githup** [vbenjs/vue-vben-admin#3989]
### 描述 Bug
实现省市区联动效果
省设置默认参数，市区会根据省设置的默认值查询市区数据，就导致市区数据不准确，渲染成了code值

### 复现 Bug
新增情况，使用默认数据
<img width="914" alt="image" src="https://github.com/user-attachments/assets/8d883610-12c3-46e4-8158-c77c94e59fc5">
修改时
<img width="932" alt="image" src="https://github.com/user-attachments/assets/d134dcc9-6e0e-4a94-a13d-9f699487ac72">

{
      field: 'province',
      component: 'ApiSelect',
      label: '省',
      required: true,
      colProps: {
        span: 12,
      },
      rules: [{ required: true, message: '请选择省', trigger: 'blur' }],
      defaultValue: '410000',
      componentProps: ({ formModel }) => {
        return {
          api: getSelector,
          params: { source: 'ProvinceSelector', param: '' },
          onChange: () => {
            formModel.town = '';
            formModel.county = '';
          },
        };
      },
    },
    {
      field: 'town',
      component: 'ApiSelect',
      label: '市',
      required: true,
      colProps: {
        span: 12,
      },
      rules: [{ required: true, message: '请选择市', trigger: 'blur' }],
      defaultValue: '410100',
      componentProps: ({ formModel }) => {
        return {
          api: getSelector,
          params: {
            source: 'TownByProvinceIdSelector',
            param: formModel.province,
          },
          onChange: () => {
            formModel.county = '';
          },
        };
      },
    },
    {
      field: 'county',
      component: 'ApiSelect',
      label: '县/区',
      required: true,
      colProps: {
        span: 12,
      },
      rules: [{ required: true, message: '请选择县/区', trigger: 'blur' }],
      defaultValue: '410101',
      componentProps: ({ formModel }) => {
        return {
          api: getSelector,
          params: {
            source: 'CountyByTownIdSelector',
            param: formModel.town,
          },
        };
      },
    },

## 系统信息

- Node 版本:20.12.2
- pnpm 版本:9.14

**Comment by mynetfan** [comment]
提供复现链接
