### ISSUE TITLE
What happend to the REPOSITORY? 

### ISSUE THREAD

**Issue by doraemonxxx** [vbenjs/vue-vben-admin#3990]
pinging admin
- @wangjue666 
- @jinmao88
- @likui628 

Hello, why can someone merge a pull request without your approvals? Pls fix the settings of merging the pull request

**Comment by likui628** [comment]
vben 5.0.0 马上发布了，目前仓库的管理有点乱，后面会好的。

1. https://doc.vben.pro/
2. https://www.vben.pro/
