### ISSUE TITLE
Bug: Tinymce 上传图片成功后，光标被重置到了首位

### ISSUE THREAD

**Issue by JzwOnly** [vbenjs/vue-vben-admin#4005]
### Version

Vben Admin Pro

### Describe the bug?

上传图片成功后，光标会被重置到首位

### Reproduction

![142cf39576eeb6376f9468302e0fa54](https://github.com/user-attachments/assets/6c01ef86-fbaa-4868-901d-4b7a608bb6a6)
![d96d70e7aad0c7cc2a40d32902e5119](https://github.com/user-attachments/assets/fac7b61d-a8d8-44d7-8283-71a75feebd1a)

### System Info

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
    Memory: 2.02 GB / 11.91 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.0.5 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Internet Explorer: 11.0.17763.298
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jinmao88** [comment]
你看一下是vben的问题还是tinymce的问题
