### ISSUE TITLE
Bug: vben5.0版本tab宽度是固定的 无法设置最大最小宽度

### ISSUE THREAD

**Issue by falcon-jin** [vbenjs/vue-vben-admin#4033]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/e1a84ab4-ece7-475e-b8d0-2d9d412f9b37)
![image](https://github.com/user-attachments/assets/d2dc0545-28ea-49de-8f29-66e8d519a38b)
v2版本tab宽度可以自适应 v5的好像不行

### Reproduction

v2版本tab宽度可以自适应 v5的好像不行

### System Info

```shell
linux
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
你可以换成其他风格的标签页，只有这个风格是固定宽度的
