### ISSUE TITLE
Docs: 最新版本中没有components了，要使用里面的组件该如何做呢（旧版直接复制过来会报很多依赖的组件找不到）？

### ISSUE THREAD

**Issue by polaris0129** [vbenjs/vue-vben-admin#4044]
### Documentation is

- [X] Missing
- [ ] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in Detail

新版没有常用的页面和组件demo了，也没有了components目录，不知道我有没有找对

### Your Suggestion for Changes

建议如旧版一样提供常见demo页面和组件

### Steps to reproduce

null

**Comment by polaris0129** [comment]
恳请路过大神解答，拜谢！

**Comment by mojiefong** [comment]
应该只能迁移纯手动写的组件了，新版中用了3套UI框架，全局组件应该是没法适配的

**Comment by vince292007** [comment]
现在刚发布，还在进行bug修复，稳定后会开始做这块工作
