### ISSUE TITLE
FEATURE: 感觉vben admin v5注定是个小众的框架.

### ISSUE THREAD

**Issue by jsparrow58** [vbenjs/vue-vben-admin#4053]
### Version

Vben Admin V5

### Description

不可否认的是v5写的非常强大，扩展性与重用性都非常利害，但是门槛太过于高了，维护与开发带了极大的复杂度。一般没有完整的团队来运营的话，很难玩转这样的框架。

### Proposed Solution

还是希望能够分开来单独管理各个项目。

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by aonoa** [comment]
https://doc.vben.pro/guide/introduction/why.html
框架的目标是让开发者能够快速上手，专注于业务逻辑的开发。
