### ISSUE TITLE
Docs: 最新版本中如何使用动态表单呢？

### ISSUE THREAD

**Issue by a303557339** [vbenjs/vue-vben-admin#4064]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [X] Confusing
- [ ] Not sure?

### Explain in Detail

最新版本中没有原先的 components 组件里面的动态表单和 table，现在要如何使用呢？

### Your Suggestion for Changes

。

**Comment by vince292007** [comment]
duplicate #4044
