### ISSUE TITLE
Bug: 执行pnpm install报错:postinstall$ turbo run stub安装失败

### ISSUE THREAD

**Issue by ketongxue** [vbenjs/vue-vben-admin#4080]
### Version

Vben Admin V5

### Describe the bug?

执行pnpm install报错

### Reproduction

pnpm install

### System Info

```shell
win11
node v20.13.0
npm 10.5.2
pnpm 9.7.0
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by likui628** [comment]
报了什么错误？

**Comment by ketongxue** [comment]
> 报了什么错误？
![Uploading 微信截图_20240808114941.png…]()

**Comment by ketongxue** [comment]
> 报了什么错误？

![image](https://github.com/user-attachments/assets/53272948-ab66-4929-ab82-4b7564c07f9f)

**Comment by likui628** [comment]
很早之前有过，https://github.com/vbenjs/vue-vben-admin/issues/3457，看下评论可能有解决办法

**Comment by ketongxue** [comment]
> 很早之前有过，#3457 ，看下评论可能有解决办法

还是不行 换了node版本也一样， #4098 遇到的应该也是一样的问题

**Comment by anncwb** [comment]
duplicate #4098
