### ISSUE TITLE
Bug: 一些组件的primary色样式有问题

### ISSUE THREAD

**Issue by dapeng0201** [vbenjs/vue-vben-admin#4081]
### Version

Vben Admin V5

### Describe the bug?

包括但不限于`message.loading` `Tag`等

message.loading 切换为后端路由可见样式异常
![image](https://github.com/user-attachments/assets/d1d462da-9708-4adf-be14-e79a6fad19f0)

Tag：

![image](https://github.com/user-attachments/assets/83fc5447-126c-461b-a79f-02ee7982dfe6)

### Reproduction

```vue
import { Tag } from 'ant-design-vue';
 <Tag color="processing">测试测试</Tag>
```

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700KF
    Memory: 12.62 GB / 31.85 GB
  Binaries:
    Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.5.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by likui628** [comment]
```
 <a-tag color="pink">pink</a-tag>
    <a-tag color="red">red</a-tag>
    <a-tag color="orange">orange</a-tag>
    <a-tag color="green">green</a-tag>
    <a-tag color="cyan">cyan</a-tag>
    <a-tag color="blue">blue</a-tag>
    <a-tag color="purple">purple</a-tag>
```
tag你给的颜色是错的，颜色转换使用的@ctrl/tiny-color, 错误的颜色会被转换成rgb(0,0,0)

**Comment by dapeng0201** [comment]
感谢
