### ISSUE TITLE
Bug: 菜单徽标变成黑色，checkbox的方框变成了圆圈。

### ISSUE THREAD

**Issue by f3dfax** [vbenjs/vue-vben-admin#4088]
### Version

Vben Admin V5

### Describe the bug?

菜单徽标变成黑色，checkbox的方框变成了圆圈。

### Reproduction

1

### System Info

```shell
1
```

### Relevant log output

```shell
1
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by likui628** [comment]
徽标问题解决了，checkbox方框变圆圈麻烦给给截图

**Comment by f3dfax** [comment]
<img width="383" alt="pic1" src="https://github.com/user-attachments/assets/5cfcaddb-3118-40f0-b1e5-d9e108b9596d">
<img width="638" alt="pic2" src="https://github.com/user-attachments/assets/3990e926-011f-4475-9c0b-d37927792752">

**Comment by likui628** [comment]
受到圆角的影响
https://antdv.com/theme-editor
![image](https://github.com/user-attachments/assets/ded54640-fe09-4f5c-9c05-d733041040c0)
设置borderRadius过大就会变圆角，不算问题
可以通过偏好设置调整
![image](https://github.com/user-attachments/assets/d55a1de4-cd5b-46f0-95c7-231198770cf5)
