### ISSUE TITLE
Bug: 消息示例hooks/web/useMessage问题

### ISSUE THREAD

**Issue by wego-xuchang** [vbenjs/vue-vben-admin#4090]
### Version

Vben Admin V2

### Describe the bug?

环境
node 18
Chrome 127
mac pro m1

消息示例hooks/web/useMessage取消和确定都都无法关闭弹窗，在v5和v2版本都存在这个问题，下面是图片和复现的视频

[录屏2024-08-08 22.22.44.zip](https://github.com/user-attachments/files/16549523/2024-08-08.22.22.44.zip)
<img width="1088" alt="image" src="https://github.com/user-attachments/assets/6fbb4353-ec95-4f9e-b617-7d3537d94e2e">

### Reproduction

环境
node 18
Chrome 127
mac pro m1

消息示例hooks/web/useMessage取消和确定都都无法关闭弹窗，在v5和v2版本都存在这个问题，下面是图片和复现的视频

[Uploading 录屏2024-08-08 22.22.44.zip…]()

<img width="1096" alt="image" src="https://github.com/user-attachments/assets/d5867ddd-8a74-4ad9-a527-997b5d83c398">

### System Info

```shell
环境
node 18
Chrome 127
mac pro m1

消息示例hooks/web/useMessage取消和确定都都无法关闭弹窗，在v5和v2版本都存在这个问题，下面是图片和复现的视频
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wangjue666** [comment]
https://github.com/user-attachments/assets/2b8beb0e-1866-4274-b08b-c5c46d1d7e03

**Comment by wangjue666** [comment]
没有问题 估计还是 vue版本的问题 参考下这个https://github.com/vbenjs/vue-vben-admin/issues/3495

**Comment by wego-xuchang** [comment]
固定vue版本和ant版本就好了
