### ISSUE TITLE
FEATURE: 登录组件AuthenticationLogin对多租户的支持

### ISSUE THREAD

**Issue by Zhao-sj** [vbenjs/vue-vben-admin#4093]
### Version

Vben Admin V5

### Description

可以考虑登录组件AuthenticationLogin对多租户的支持吗？例如：登录组件增加一个租户选择组件

### Proposed Solution

可以考虑登录组件AuthenticationLogin对多租户的支持吗？例如：登录组件增加一个租户选择组件

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by jinmao88** [comment]
这个需求可以自己加

**Comment by aonoa** [comment]
pull https://github.com/vbenjs/vue-vben-admin/pull/4352 已支持，示例在 `playground/src/views/_core/authentication/login.vue`
