### ISSUE TITLE
Bug: Ant [Popconfirm] [Tooltip]组件样式与官方不一致

### ISSUE THREAD

**Issue by dapeng0201** [vbenjs/vue-vben-admin#4097]
### Version

Vben Admin V5

### Describe the bug?

官方为三角  框架为矩形

官方ant样式
![image](https://github.com/user-attachments/assets/53cb46ff-d00b-46a2-b83d-49de93c86bda)

框架
![image](https://github.com/user-attachments/assets/9b7bb5d5-bffb-488e-b5f1-8ddc043a3605)

![image](https://github.com/user-attachments/assets/52fed543-1c33-43fe-89dd-b8498c65e758)

### Reproduction

<script setup lang="ts">
import { Button, Popconfirm } from 'ant-design-vue';
</script>

<template>
  <div class="m-[32px]">
    <Popconfirm placement="top" title="测试popconfirm">
      <Button type="primary">测试按钮</Button>
    </Popconfirm>
  </div>
</template>

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700KF
    Memory: 14.90 GB / 31.85 GB
  Binaries:
    Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.5.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by dapeng0201** [comment]
```vue
<script setup lang="ts">
import { Button, Popconfirm, Space, Tooltip } from 'ant-design-vue';
</script>

<template>
  <div class="m-[32px]">
    <Space>
      <Popconfirm placement="top" title="测试popconfirm">
        <Button type="primary">测试按钮</Button>
      </Popconfirm>
      <Tooltip placement="top" title="测试tooltip">
        <Button type="primary">测试按钮</Button>
      </Tooltip>
    </Space>
  </div>
</template>
```

**Comment by likui628** [comment]
https://github.com/vbenjs/vue-vben-admin/issues/4088
该issue中描述的checkbox样式变化应该跟这个项有关系

**Comment by anncwb** [comment]
https://github.com/vueComponent/ant-design-vue/issues/7684 ant-design-vue的bug，可显注释这行代码解决
tokens.borderRadius = getCssVariableValue('--radius', false);
