### ISSUE TITLE
Bug: MenuBadge 组件徽标颜色问题

### ISSUE THREAD

**Issue by lionjiadong** [vbenjs/vue-vben-admin#4122]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/56f2c19f-7245-4c96-8855-ef71481c7812)
只要菜单里的badgeVariants设置非hsl得字符串值都将显示黑色,那这个组件里的variantsMap对象将永远不会生效,将无法用字符串快速替换预设的颜色(eg: success, warning, primary)

### Reproduction

const props = withDefaults(defineProps<Props>(), {});

const variantsMap: Record<string, string> = {
  default: 'bg-green-500',
  destructive: ' bg-destructive',
  primary: 'bg-primary',
  success: ' bg-green-500',
  warning: ' bg-yellow-500',
};

const isDot = computed(() => props.badgeType === 'dot');

const badgeClass = computed(() => {
  const { badgeVariants } = props;

  if (!badgeVariants) {
    return variantsMap.default;
  }

  return variantsMap[badgeVariants] || badgeVariants;
});

const badgeStyle = computed(() => {
  if (badgeClass.value) {
    return {
      backgroundColor: convertToRgb(badgeClass.value),
    };
  }
  return {};
});

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 147.21 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v21.5.0/bin/npm
    pnpm: 9.7.0 - ~/.nvm/versions/node/v21.5.0/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.100
    Safari: 17.5
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by likui628** [comment]
已经改过了
