### ISSUE TITLE
FEATURE: 偏好设置按钮---能否鼠标悬浮在按钮上才高亮显示，或和2x版本一样放在右上角。

### ISSUE THREAD

**Issue by saykuqi137** [vbenjs/vue-vben-admin#4123]
### Version

Vben Admin V5

### Description

如标题

### Proposed Solution

![image](https://github.com/user-attachments/assets/8e4a6448-7947-45cb-b82e-8c2fa42219b6)

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by mynetfan** [comment]
在文件`packages/effects/layouts/src/widgets/preferences/preferences-sheet.vue`的第222行中的class里添加```opacity-20 hover:opacity-100```，如下：
```
<div class="z-100 fixed right-0 top-1/2 opacity-20 hover:opacity-100">
```

**Comment by saykuqi137** [comment]
感谢
