### ISSUE TITLE
FEATURE: 建议 table 搜索框增加自动提交功能

### ISSUE THREAD

**Issue by linzea** [vbenjs/vue-vben-admin#4124]
### Version

Vben Admin V5

### Description

在table formConfig 配置内允许自动提交, 下拉或input输入后自动提交查询

### Proposed Solution

在table formConfig 配置内允许自动提交, 只刷新 table 内容,  emit('reload'); 刷新会将整个页面刷新

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by Swarz** [comment]
table哪来的 我拉的仓库没table 啊

**Comment by linzea** [comment]
我用的是v3 版本, 使用有这个问题, 建议新版的时候各位大佬费心

Swarz ***@***.***> 于2024年8月13日周二 11:50写道：

**Comment by vince292007** [comment]
table 组件写完后，再来，目前还要点时间
