### ISSUE TITLE
最近从vben2迁移到vben5，发现vben5路由和菜单部分做了一些调整

### ISSUE THREAD

**Issue by TengChongChong** [vbenjs/vue-vben-admin#4125]
### Version

Vben Admin V5

### Description

最近从vben2迁移到vben5，发现vben5路由和菜单部分做了一些调整，比如
1、vben2中的routeHelper.ts transformObjToRoute() 将后端路由数据转为路由的方法中，对一级路由component不是“LAYOUT”的进行了包装，外面套了一层LAYOUT路由，vben5中没有继承此逻辑
2、vben2中的menuHelper.ts transformRouteToMenu() 路由转菜单的方法中，对只有一个子路由的菜单进行了菜单等级提升的操作，vben5中没有继承此逻辑，这样导致了菜单最少有两级才行（也可能是我不知道怎么配置）
大佬们知道为什么这么设计吗？
由于业务系统中难以避免使用一级菜单，我们目前将vben2中的逻辑迁移到vben5中，是否有更好的方式可以实现？
![QQ20240810-184259](https://github.com/user-attachments/assets/5ac1d126-5efe-42fe-9ae9-b0d9ef028e87)
![QQ20240810-184208](https://github.com/user-attachments/assets/06a08357-9239-42fc-bf8d-399e2a595915)

### Proposed Solution

。。。

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by mynetfan** [comment]
关于你说的第二条，目前你可以这样处理：
在这个唯一的子路由的meta中添加hideInMenu和activePath:
```
...
{
        ...
        meta: {
          activePath: '指向上级路由的path',
          hideInMenu: true,    // 不在菜单中显示
          ...
}
```
这样处理的话，这个子路由就不会在菜单中显示，基本上可以满足你的“使用一级菜单”的需求。

**Comment by TengChongChong** [comment]
> 关于你说的第二条，目前你可以这样处理： 在这个唯一的子路由的meta中添加hideInMenu和activePath:
> 
> ```
> ...
> {
>         ...
>         meta: {
>           activePath: '指向上级路由的path',
>           hideInMenu: true,    // 不在菜单中显示
>           ...
> }
> ```
> 
> 这样处理的话，这个子路由就不会在菜单中显示，基本上可以满足你的“使用一级菜单”的需求。

多谢，我试试

**Comment by fzq1998** [comment]
> 关于你说的第二条，目前你可以这样处理： 在这个唯一的子路由的meta中添加hideInMenu和activePath:
> 
> ```
> ...
> {
>         ...
>         meta: {
>           activePath: '指向上级路由的path',
>           hideInMenu: true,    // 不在菜单中显示
>           ...
> }
> ```
> 
> 这样处理的话，这个子路由就不会在菜单中显示，基本上可以满足你的“使用一级菜单”的需求。

我试了一下,  以 `apps/web-ele` 的修改,  `activePath` 指定的时候似乎并不生效
eg: 
```typescript
const routes: RouteRecordRaw[] = [
  {
    component: BasicLayout,
    meta: {
      icon: 'ic:baseline-view-in-ar',
      keepAlive: true,
      order: 1000,
      title: $t('page.demos.title'),
    },
    name: 'Demos',
    path: '/demos',
    children: [
      {
        meta: {
          activePath: '/demos',
          hideInMenu: true,
          title: $t('page.demos.element-plus'),
        },
        name: 'NaiveDemos',
        path: '/demos/element',
        component: () => import('#/views/demos/element/index.vue'),
      },
    ],
  },
];
```
目前最好的实践方案是如果要实现一级菜单,  `path` 保持一致并且设置子路由 `hideInMenu: true` 即可
```typescript
const routes: RouteRecordRaw[] = [
  {
    component: BasicLayout,
    meta: {
      icon: 'ic:baseline-view-in-ar',
      keepAlive: true,
      order: 1000,
      title: $t('page.demos.title'),
    },
    name: 'Demos',
    path: '/demos/element',
    children: [
      {
        meta: {
          hideInMenu: true,
          title: $t('page.demos.element-plus'),
        },
        name: 'NaiveDemos',
        path: '/demos/element',
        component: () => import('#/views/demos/element/index.vue'),
      },
    ],
  },
];
```
