### ISSUE TITLE
Bug: 菜单的选择不应该触发顶部导航自动隐藏与显示

### ISSUE THREAD

**Issue by zxuanhong** [vbenjs/vue-vben-admin#4127]
### Version

Vben Admin V5

### Describe the bug?

1. 菜单的选择不应该触发顶部导航自动隐藏与显示

https://github.com/user-attachments/assets/a0d21748-7be2-4797-8cd1-f389fa4e0c4d

### Reproduction

1. 开启顶部导航自动隐藏与显示
2. 手动选择菜单最上面一条
3. 此时出发了顶部导航的隐藏与显示

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 12.07 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.0.5 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
  Browsers:
    Chrome: 127.0.6533.100
    Safari: 17.5
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
z-index层级问题
