### ISSUE TITLE
Bug: 静态路由开启后没有在菜单中显示

### ISSUE THREAD

**Issue by Zhao-sj** [vbenjs/vue-vben-admin#4128]
### Version

Vben Admin V5

### Describe the bug?

使用静态路由后能够访问到对应的路由，但是在菜单中并没有显示

### Reproduction

// 有需要可以自行打开注释，并创建文件夹
const staticRouteFiles = import.meta.glob('./static/**/*.ts', { eager: true }); 
/** 动态路由 */
const dynamicRoutes: RouteRecordRaw[] = mergeRouteModules(dynamicRouteFiles);
/** 静态路由列表，访问这些页面可以不需要权限 */
const staticRoutes: RouteRecordRaw[] = mergeRouteModules(staticRouteFiles); 

### System Info

```shell
System:
    OS: Windows 11 22631.3880
    CPU: 13th Gen Intel(R) Core(TM) i9-13900H   2.60 GHz
    Memory: 21.3 GB / 32.0 GB
  Binaries:
    Node: 20.16.0 - D:\Application\nodejs\node.exe
    npm: 10.5.0 - D:\Application\nodejs\npm.cmd
    pnpm: 9.6.0 - D:\Application\nodejs\pnpm.cmd
  Browsers:
    Chrome: 127.0.6533.100
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
看下你怎么写的

**Comment by Zhao-sj** [comment]
1. 根据文档提示开启注释
2. 建立对应文件夹
3. 将同级目录中mudules里dashboard移动到静态文件夹

查看代码好像静态文件夹下面的路由直接交给vue-router了，没有进行菜单处理

**Comment by anncwb** [comment]
这里应该描述错了，staticRoutes 取名错了。如果你只是需要固定显示某个菜单，只需要在meta设置 ignoreAccess 即可。不需要放在staticRoutes。staticRoutes会去掉，改成externalRoutes，用于不需要Layout的场景
