### ISSUE TITLE
Bug: 某些图标在menu和tab上表现不一致，menu多一个框

### ISSUE THREAD

**Issue by Swarz** [vbenjs/vue-vben-admin#4135]
### Version

Vben Admin V5

### Describe the bug?

某些图标在menu和tab上表现不一致，menu多一个框

### Reproduction

我两台都是，应该是可以100%复现。

icon替换为mingcute:classify-2-line
classify搜索结果几个mingcute开头的图标都不行
![微信截图_20240813110621](https://github.com/user-attachments/assets/9fd9fda7-7e66-4efe-b338-537a0e3cb81e)

看了一下，确实有外框的path，删掉就没有框了。
![image](https://github.com/user-attachments/assets/5d5321bf-aeb9-4a58-be07-3fa4ab567361)

很奇怪 为啥menu的外框为啥fill了颜色

### System Info

```shell
System:
    OS: Windows 10 10.0.17763
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 6.32 GB / 15.82 GB
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.5.0 - ~\AppData\Local\pnpm\pnpm.EXE
    bun: 1.1.17 - ~\.bun\bin\bun.EXE
  Browsers:
    Internet Explorer: 11.0.17763.2989
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by likui628** [comment]
https://icon-sets.iconify.design/mingcute/classify-2-line/
![image](https://github.com/user-attachments/assets/c139fca4-3e6f-48ad-99bb-a8ccf8aef4df)

看样子是菜单那里是错的
