### ISSUE TITLE
accessToken过期后，刷新页面无法跳转至登录页Bug: 

### ISSUE THREAD

**Issue by ye17186** [vbenjs/vue-vben-admin#4148]
### Version

Vben Admin V5

### Describe the bug?

登录过期模式未弹框时，如果accessToken过期了，这时刷新页面后出现空白页，不能正常弹框和跳转登录页。
在线预览页能跳转，是因为模拟登录过期按钮，点了之后会清空accessToken。  如果刷新页面时accessToken存在，但是后端接口返回了登录过期，则不能正常弹框和跳转登录页。

### Reproduction

刷新页面时会自动加载用户信息接口，该接口返回登录过期。这是犹豫accessToken存在，所以无法正常跳转到登录页

### System Info

```shell
MacOS
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
后端登录接口返回了什么状态码？演示的是401才会跳。

**Comment by likui628** [comment]
首先目前的mock环境不存在登录过期这一说，有一种办法确实会触发报错，在localstorage直接修改accessToken。

```
GET http://localhost:5666/api/user/info 500 (Internal Server Error)                      request-client.ts:223 
[error handler] TypeError: Cannot destructure property 'password' of 'user' as it is undefined.   bootstrap.ts:26
```

**Comment by vince292007** [comment]
token直接修改，对于后端接口来说，英国会鉴权失败，也是返回401之类状态码

**Comment by ye17186** [comment]
不是这个意思，我的问题不是mock server造成的。  
复现步骤：
1、登录成功后先停留在首页
2、然后修改localstorage直接修改accessToken（注意，不要删除token，而是修改为一个无效值，模拟后端接口的登录过期）
3、再刷新页面（注意，是刷新页面，不是点某个按钮发起ajax请求），这是就会出现白屏，不会跳转登录页

出现问题的原因：
1、刷新页面后，进入路由跳转，apps/web-antd/src/router/guard.ts的判断里，由于token存在，所以不会触发跳转登录页
2、刷新页面后，由于http://localhost:5666/api/user/info返回的是401，所以首页不能正常加载出来，也就不会弹窗登录框

**Comment by likui628** [comment]
> 不是这个意思，我的问题不是mock server造成的。 复现步骤： 1、登录成功后先停留在首页 2、然后修改localstorage直接修改accessToken（注意，不要删除token，而是修改为一个无效值，模拟后端接口的登录过期） 3、再刷新页面（注意，是刷新页面，不是点某个按钮发起ajax请求），这是就会出现白屏，不会跳转登录页
> 
> 出现问题的原因： 1、刷新页面后，进入路由跳转，apps/web-antd/src/router/guard.ts的判断里，由于token存在，所以不会触发跳转登录页 2、刷新页面后，由于[http://localhost:5666/api/user/info返回的是401，所以首页不能正常加载出来，也就不会弹窗登录框](http://localhost:5666/api/user/info%E8%BF%94%E5%9B%9E%E7%9A%84%E6%98%AF401%EF%BC%8C%E6%89%80%E4%BB%A5%E9%A6%96%E9%A1%B5%E4%B8%8D%E8%83%BD%E6%AD%A3%E5%B8%B8%E5%8A%A0%E8%BD%BD%E5%87%BA%E6%9D%A5%EF%BC%8C%E4%B9%9F%E5%B0%B1%E4%B8%8D%E4%BC%9A%E5%BC%B9%E7%AA%97%E7%99%BB%E5%BD%95%E6%A1%86)

所以mockServer判断token无效返回401就解决这个问题了。

**Comment by zxj176381** [comment]
我也遇到跟题主一样的问题，手动更改 token 导致token过期后，刷新页面由于接口无法返回数据，导致获取不到路由列表，路由无法进入，所以无法弹窗出modal登录窗口，应该如何解决这个问题呢？

**Comment by ye17186** [comment]
> 我也遇到跟题主一样的问题，手动更改 token 导致token过期后，刷新页面由于接口无法返回数据，导致获取不到路由列表，路由无法进入，所以无法弹窗出modal登录窗口，应该如何解决这个问题呢？

除accessToken外，我新增了一个token过期时间expiredAt，路由守卫了新增判断token是否过期，如果过期了，则导航到登录页
![image](https://github.com/user-attachments/assets/14ef7ec8-675d-45a5-8cb6-7fb4ce8c5935)

**Comment by zxj176381** [comment]
> > 我也遇到跟题主一样的问题，手动更改 token 导致token过期后，刷新页面由于接口无法返回数据，导致获取不到路由列表，路由无法进入，所以无法弹窗出modal登录窗口，应该如何解决这个问题呢？
> 
> 除accessToken外，我新增了一个token过期时间expiredAt，路由守卫了新增判断token是否过期，如果过期了，则导航到登录页 ![image](https://private-user-images.githubusercontent.com/33926823/358144827-14ef7ec8-675d-45a5-8cb6-7fb4ce8c5935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTUxNjksIm5iZiI6MTcyMzcxNDg2OSwicGF0aCI6Ii8zMzkyNjgyMy8zNTgxNDQ4MjctMTRlZjdlYzgtNjc1ZC00NWE1LThjYjYtN2ZiNGNlOGM1OTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA5NDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZWFhZjNjMmFjMjE0ZGViMTFlMDVmYTg1ZDRhNzk2NmE2ZWQyZTMzODQ5YzBkMTg5ZWIyOGM1NWMxNmVmNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KJEY2ZxpW3bTKp91WLiWYlAYjswt2np7YeD9BOxZ8Wk)

像您一样使用了过期时间以后，弹窗也会正常，刷新页面也会正常对吗

**Comment by likui628** [comment]
这个先关闭了，会和#4157 冲突

**Comment by likui628** [comment]
#4157 在做refreshToken, 等做好在看这个还有没有问题

**Comment by likui628** [comment]
新版本refreshToken上线了，这个issue先关闭了
