### ISSUE TITLE
Docs: V5版本设置后端获取菜单信息时报错

### ISSUE THREAD

**Issue by thanksU** [vbenjs/vue-vben-admin#4150]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in Detail

想使用后端方式生成路由菜单，按照咱文档上的提示，将应用目录下的preferences.ts，设置了accessMode='backend'，将应用下的 src/router/access.ts中的return await getAllMenus();改成了return dashboardMenus;其中dashboardMenus是文档给的后端数据示例。基于以上修改，重新登录系统，在登录页面登录时报错了，直接在浏览器中输入http://localhost:5777/时系统可以按照dashboardMenus数据格式生成页面菜单，没有报错。目前问题就是出在登录页面的报错，通过在@vben/utils的@vben/utils的generate-routes-backend.ts模块设置console.log查看错误原因，在浏览器发现报错如下，请教下这是什么原因导致的呀  是系统的BUG还是我哪里设置错了呀

### Your Suggestion for Changes

这是什么原因导致的呀  是系统的BUG还是我哪里设置错了呀

**Comment by likui628** [comment]
https://doc.vben.pro/guide/in-depth/access.html#%E6%AD%A5%E9%AA%A4-1
请仔细看文档

**Comment by thanksU** [comment]
请问我应该如何修改呀  试了很久问题还是得不到解决  谢谢
