### ISSUE TITLE
Bug: Button添加图标后样式错乱

### ISSUE THREAD

**Issue by TengChongChong** [vbenjs/vue-vben-admin#4153]
### Version

Vben Admin V5

### Describe the bug?

```vue
      import { Button, Card } from 'ant-design-vue';

      <Button :type="roleButtonType('super')" @click="changeAccount('super')">
        <template #icon>
          <ArrowDown />
        </template>
        切换为 Super 账号
      </Button>
```
![QQ_1723646326076](https://github.com/user-attachments/assets/a7060a25-5436-4b38-99bb-026521f61b9e)

### Reproduction

解析后的dom与andv官网示例相比较，缺少一层span
![QQ_1723646407567](https://github.com/user-attachments/assets/d9d82a89-4a8a-452a-b19b-d899943b887f)
下图为官网截图
![QQ_1723646424389](https://github.com/user-attachments/assets/b09d80fd-e8a4-4b44-bade-4370f4667c1a)

### System Info

```shell
mac/chrome
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Alkaidcc** [comment]
这里的 `ArrowDown` 用的是 [lucide](https://lucide.dev/guide/packages/lucide-vue-next)的图标而不是antdv的图标。默认为svg格式。你可以在全局加一个样式覆盖来解决这个问题，使用vue的style块（无scoped），或者在css文件中添加以下内容。
```css
.lucide {
	display: initial;
}
```

**Comment by Alkaidcc** [comment]
显示异常是因为tailwindcss的默认reset会把svg元素的样式设置成
```css	
svg {
	display: block;
	vertical-align: middle;
}
```

**Comment by TengChongChong** [comment]
> 显示异常是因为tailwindcss的默认reset会把svg元素的样式设置成
> 
> ```css
> svg {
> 	display: block;
> 	vertical-align: middle;
> }
> ```

感谢，我去试试

**Comment by TengChongChong** [comment]
使用@ant-design/icons-vue图标不换行了，但是图标会下沉
![QQ_1723685243849](https://github.com/user-attachments/assets/1a951c0f-865a-483d-9e60-e1d496b6ed5b)
看了下是由于tailwind设置了
![QQ_1723685271405](https://github.com/user-attachments/assets/d109279d-6d65-44c9-a7ce-93301a4a0d10)
图标设置了
![QQ_1723685350271](https://github.com/user-attachments/assets/26288966-b500-4c02-a394-9925b8449398)
导致的下沉

**Comment by Alkaidcc** [comment]
使用antdv的icon可以试试覆盖svg样式 `vertical-align: unset;`

**Comment by TengChongChong** [comment]
好，谢谢
