### ISSUE TITLE
Bug: playground 项目中 功能下 标签栏（tabs）跳转多个详情 设置tabs 的标题问题

### ISSUE THREAD

**Issue by zxj176381** [vbenjs/vue-vben-admin#4158]
### Version

Vben Admin V5

### Describe the bug?

跳转详情时，ID不同，设置tabs标题时会讲所有已经打开的tabs的标题一起修改掉

### Reproduction

http://10.0.16.22:5555/demos/features/tabs/detail/1
http://10.0.16.22:5555/demos/features/tabs/detail/2
http://10.0.16.22:5555/demos/features/tabs/detail/3

### System Info

```shell
vue
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by M69W** [comment]
大佬，重现代码呢

**Comment by zxj176381** [comment]
> 大佬，重现代码呢

官方演示项目就可以复现
