### ISSUE TITLE
Bug: 组件导入了但没有提示

### ISSUE THREAD

**Issue by Luo-RongLi** [vbenjs/vue-vben-admin#4159]
### Version

Vben Admin V5

### Describe the bug?

![微信图片_20240815115049](https://github.com/user-attachments/assets/cd582468-ed2b-42f3-a60f-865b296572af)
![微信截图_20240815115156](https://github.com/user-attachments/assets/f586e702-40af-4238-80e8-cfea4d550365)
![微信截图_20240815120029](https://github.com/user-attachments/assets/e0f5c01d-a987-4591-ba4d-669ac9de1920)

我这是采用了自动导入的方式，样式什么的都生效，唯独提示没有

### Reproduction

https://stackblitz.com/edit/vitest-dev-vitest-ktxlu2?file=vite.config.ts

### System Info

```shell
windows11
谷歌
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Alkaidcc** [comment]
可以看看 `components.d.ts` 中有没有生成 element-plus 的组件类型引入。或者可以尝试刷新浏览器页面或者重启volar看看👀
我这边的实际使用情况是，只有浏览器加载到对应组件（需要打开正在编写中的页面），unplugin才会更新 .d.ts文件，volar才会有类型支持。

**Comment by Luo-RongLi** [comment]
已经找到问题了，vscode的官方Vue - Official 提示还不够完善，我换webstrom又可以使用了
