### ISSUE TITLE
Bug: vben 开启树表的情况下使用ustable的api方式返回的数据子级无法取消选中

### ISSUE THREAD

**Issue by zqmhub** [vbenjs/vue-vben-admin#4167]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/8b23fab0-ef05-4528-b0c3-e04b66d7b304)
![image](https://github.com/user-attachments/assets/852a0c26-80ff-45b3-98e4-cc43827089da)
以上配置无法点击复选框取消勾选

### Reproduction

无

### System Info

```shell
无
```

### Relevant log output

```shell
df
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
v2版本组件问题需要自行检查。
