### ISSUE TITLE
FEATURE: Add Table Component

### ISSUE THREAD

**Issue by anncwb** [vbenjs/vue-vben-admin#4182]
### Version

Vben Admin V5

### Description

Add Table Component

### Proposed Solution

Add Table Component

### Validations

- [x] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [x] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [x] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by gitskybo** [comment]
请问预计什么时候出来table组件呢

**Comment by pihc** [comment]
非常期待这个组件，加油

**Comment by zhengyuanchao-xinye** [comment]
同求table组件！！！

**Comment by Rosario9527** [comment]
啊啊啊啊，这个最重要了，怎么没有BasicTable了， 大佬期待啊！

**Comment by Rwing** [comment]
请问大概什么时候可以推出？

**Comment by xqh-jason** [comment]
等待table组件出来，就可以上生产了，加油
