### ISSUE TITLE
Bug: Build process hava many Error

### ISSUE THREAD

**Issue by Mxucc** [vbenjs/vue-vben-admin#4186]
### Version

Vben Admin V5

### Describe the bug?

first is Cannot find module 'cssnano'，but exec`pnpm i cssnano` solved，
but next appear：
 ERROR  error during build:                                                                                   10:44:49
[vite]: Rollup failed to resolve import "@vben-core/shared/color" from "E:/Windows/Mxu/Desktop/Vben/packages/utils/src/index.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
![微信截图_20240818104714](https://github.com/user-attachments/assets/f22ed6b5-d030-492d-964f-5e6ec9124915)

### Reproduction

https://github.com/vbenjs/vue-vben-admin

### System Info

```shell
win11 node20
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wangjue666** [comment]
please execute the `pnpm install` command first

**Comment by Mxucc** [comment]
已经运行过`pnpm install` 但是还是需要`pnpm i cssnano`，然后build过程还是会出现这个错误，具体看图
![微信图片_20240819163751](https://github.com/user-attachments/assets/b1a258aa-a119-4ad0-8505-95a842842f4c)

**Comment by wangjue666** [comment]
@Mxucc 要先在大仓下执行`npm run build`  然后再去web-antd项目下 执行 `npm run build`

**Comment by Mxucc** [comment]
@wangjue666 我又编译了几次，找到问题了，是路径不能有中文名，我的错

**Comment by hao-hongbao** [comment]
我也是这个错误，路径没有中文名，把doc文件夹删掉了就好了
