### ISSUE TITLE
Bug: 路由生成菜单时，二级菜单order排序不起作用

### ISSUE THREAD

**Issue by thanksU** [vbenjs/vue-vben-admin#4187]
### Version

Vben Admin V5

### Describe the bug?

采用后端获取路由、菜单模式，按照约定格式获取路由后，前端正常生成了目录菜单，一级目录菜单order方式为降序模式（order越大越排在前面），二级菜单设置order时 前端菜单排序不发生变化。

### Reproduction

图一：无论dashboard、workspace页面order如何设置和变化，排序均未受影响，均是“分析页”排在“工作台前面”
![image](https://github.com/user-attachments/assets/d7d2471d-9aa8-4be2-9f93-5ff3c86d6332)
图二：后端生成菜单路由
![image](https://github.com/user-attachments/assets/573b33c6-dfd7-4580-bd52-2ad2a3fb2ce3)

### System Info

```shell
..
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
这个是预期的，后端返回数据应该由后端来进行数据排序。这里的order使用场景是：前端routes是通过动态加载的方式来处理，没办法指定顺序，order用于处理这个情况，也是一级路由起作用。二级路由由代码顺序决定，后续文档会补充下。
