### ISSUE TITLE
FEATURE: 推荐 fast-crud 做基础控件 ，与 vben  设计理很是契合

### ISSUE THREAD

**Issue by levin950825** [vbenjs/vue-vben-admin#4190]
### Version

Vben Admin V5

### Description

[fast-crud](https://github.com/fast-crud/fast-crud)  主要包装了element-plus、antdv、navite-ui 完美契合 vben 的体系 这样意味着集合二者用户可以随意切换，而且维护起来也相对容易

### Proposed Solution

[fast-crud](https://github.com/fast-crud/fast-crud)  主要包装了element-plus、antdv、navite-ui 完美契合 vben 的体系 这样意味着集合二者用户可以随意切换，而且维护起来也相对容易

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by likui628** [comment]
看了下fast-crud，可以很方便的集成进来，并不需要框架上做什么特别的支持。
