### ISSUE TITLE
Bug: i18n反复切换异常

### ISSUE THREAD

**Issue by Zhao-sj** [vbenjs/vue-vben-admin#4191]
### Version

Vben Admin V5

### Describe the bug?

在使用组件库element-plus时多次切换语言，只有第一次会生效，之后的切换则没有效果，好像是提供loadMessages只有第一次加载时才会执行

### Reproduction

在使用组件库element-plus时多次切换语言，只有第一次会生效，之后的切换则没有效果，好像是提供loadMessages只有第一次加载时才会执行

### System Info

```shell
System:
    OS: Windows 11 22631.3880
    CPU: 13th Gen Intel(R) Core(TM) i9-13900H   2.60 GHz
    Memory: 21.3 GB / 32.0 GB
  Binaries:
    Node: 20.16.0 - D:\Application\nodejs\node.exe
    npm: 10.8.1 - D:\Application\nodejs\npm.cmd
    pnpm: 9.6.0 - D:\Application\nodejs\pnpm.cmd
  Browsers:
    Chrome: 127.0.6533.120
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by likui628** [comment]
antdv的版本有问题吗

**Comment by Zhao-sj** [comment]
> antdv的版本有问题吗
使用这种注册的应该都有问题吧，只有第一次切换才会触发响应式，后续切换这个函数都不执行了，可以试试用组件库的日期时间组件后切换查看
![image](https://github.com/user-attachments/assets/1e84aeb1-62a3-429c-b37c-a9a4461060b3)

**Comment by likui628** [comment]
https://github.com/vueComponent/ant-design-vue/blob/2666cb79abf9825872e37b55d6d9d4c1cf30e62a/components/config-provider/demo/locale.vue

上述代码包含跟locale相关的组件，可以看出确实有这个问题
