### ISSUE TITLE
Bug: 标签栏样式错误

### ISSUE THREAD

**Issue by lizan658** [vbenjs/vue-vben-admin#4197]
### Version

Vben Admin V5

### Describe the bug?

在布局为混合菜单的模式下，侧边栏菜单一次折叠展开操作后，最后一个标签页会不见了，需要操作一次向左滚动向右滚动或切换一次标签页才重新会出来；侧边栏菜单折叠或是展开，点击标签栏最大化后，样式都存在一定程度错误

### Reproduction

侧边栏菜单一次折叠展开操作后，离线页面这个标签页这时不见了
![Snipaste_2024-08-20_09-41-08](https://github.com/user-attachments/assets/f1f2842a-2152-48bc-a3af-03981257631a)

侧边栏菜单展开，点击标签栏最大化后，样式存在错误
![Snipaste_2024-08-20_09-27-05](https://github.com/user-attachments/assets/bce39cb0-d532-41b4-abb4-22464f80e28e)

侧边栏菜单折叠，点击标签栏最大化后，样式存在错误，更多按钮、还原按钮不见了
![Snipaste_2024-08-20_09-49-56](https://github.com/user-attachments/assets/37d6b09a-8d16-416f-9b4c-b8e6c4a19f0a)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 3.94 GB / 15.80 GB
  Binaries:
    Node: 20.14.0 - C:\Program Files\nodejs\node.EXE       
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.7.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.128)
    Internet Explorer: 11.0.19041.4355
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 156704883** [comment]
还有一个小bug，谷歌风格的标签页的样式没有随自定义样式改变，一直是灰色的
![image](https://github.com/user-attachments/assets/bd986031-efdb-4252-9e37-a8b75ded0753)
