### ISSUE TITLE
FEATURE: 期望 vben 可以添加 【行为验证码】【普通验证码】等登录案例

### ISSUE THREAD

**Issue by levin950825** [vbenjs/vue-vben-admin#4208]
### Version

Vben Admin V5

### Description

目前的登录方式比较单一普通，期望  vben 可以添加 【行为验证码】【普通验证码】等登录案例，以及短信验登录等交互方式 如 发送之前触发验证码流程之类的（虽然开发者可以基于VBEN进行自主开发，但框架自带体系后可以更方便快速的集成开发）

### Proposed Solution

【行为验证码】【普通验证码】等登录案例

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by anncwb** [comment]
close [000172e](https://github.com/vbenjs/vue-vben-admin/commit/000172e482da2999b813616e788f0a152bb5a602)
