### ISSUE TITLE
Bug: 侧标菜单栏滚动，主体内容也跟着滚动

### ISSUE THREAD

**Issue by pzzyf** [vbenjs/vue-vben-admin#4214]
### Version

Vben Admin V5

### Describe the bug?

侧标菜单栏滚动，主体内容也跟着滚动

### Reproduction

侧标菜单栏滚动，主体内容也跟着滚动

### System Info

```shell
win11
chrome
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by likui628** [comment]
折叠菜单栏情况下鼠标放在菜单栏，菜单栏自动展开，然后鼠标滚轮会影响到内容页面

https://github.com/user-attachments/assets/f3ecf342-d50c-4861-94c1-95458abee94f
