### ISSUE TITLE
Bug: ignoreAccess 无效

### ISSUE THREAD

**Issue by aonoa** [vbenjs/vue-vben-admin#4226]
### Version

Vben Admin V5

### Describe the bug?

路由配置 ignoreAccess ，通过地址栏访问依然会被拦截跳转到登陆页面

### Reproduction

1. 修改`apps/web-antd/src/router/routes/modules/demos.ts`，添加`ignoreAccess`属性
```
   19         meta: {
   20           title: $t('page.demos.antd'),
+  21           ignoreAccess: true
   22         },

```
2. 浏览器访问 `http://localhost:5666/demos/ant-design` ，会跳转到登陆页面

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
    Memory: 14.10 GB / 31.18 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.7.0 - /usr/local/bin/npm
    pnpm: 9.4.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 112.0.5615.165
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by likui628** [comment]
这里如果ignoreAccess让访问的话有个问题，布局内比如用户下拉，消息 按理说应该隐藏掉的。
![image](https://github.com/user-attachments/assets/a8537ffe-2993-45b7-983d-fc89c78e2197)

这种的场景是什么，是不是可以用externalRoutes代替

**Comment by aonoa** [comment]
`ignoreAccess` 目前的使用效果为：设置为`true`，用户登陆后如果没有设置角色或者权限也能访问到这个页面，无法在不登陆的情况下使用（与`authority`设置为`[]`效果一样），如需要在未登陆的情况下访问页面，需要使用externalRoutes(只显示页面，不显示布局)

**Comment by fzq1998** [comment]
因为 `ignoreAcess` 判断条件的前提 `token`  不存在,  加上目前项目里的 `modules`  都是动态路由, 路由还没生成就获取不到`meta`信息

<img width="2247" alt="image" src="https://github.com/user-attachments/assets/0553942b-bf97-4bc6-8eda-a5a91c31a437">

**Comment by 531431988** [comment]
有没有一种情况不需要登录也能访问的页面（像404），且可以配置路由是否在菜单中显示？

**Comment by mynetfan** [comment]
不登陆就没有菜单。如果要做一些不登陆就可以显示的页面，放在`apps/web-antd/src/router/routes/core.ts`的`coreRoutes`里。

**Comment by mynetfan** [comment]
> 不登陆就没有菜单。如果要做一些不登陆就可以显示的页面，放在`apps/web-antd/src/router/routes/core.ts`的`coreRoutes`里。

也可以按照注释，写在`apps/web-antd/src/router/routes/index.ts`的`externalRoutes`里

**Comment by 531431988** [comment]
> > 不登陆就没有菜单。如果要做一些不登陆就可以显示的页面，放在`apps/web-antd/src/router/routes/core.ts`的`coreRoutes`里。
> 
> 也可以按照注释，写在`apps/web-antd/src/router/routes/index.ts`的`externalRoutes`里

这种两我都知道，现在就有一种场景就是不登录也能查看到对应的页面，且显示在菜单中，目前我是直接把路由拦截去掉解决的，是不是需要考虑一下“ignoreAccess ”这个配置的菜单可以不需要任何的权限包括登录，在通过hideInMenu来控制是否在菜单中展示

**Comment by 531431988** [comment]
现在只有modules中的路由才会在菜单中显示，core中添加的或者自定义能否也支持默认在菜单中显示，且支持配置是否展示到菜单中
