### ISSUE TITLE
FEATURE: 后期是否有Javascript版本的计划呢？

### ISSUE THREAD

**Issue by zuome** [vbenjs/vue-vben-admin#4247]
### Version

Vben Admin V5

### Description

后期是否有Javascript版本的计划呢？

### Proposed Solution

是|否

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by vince292007** [comment]
没有，全部用any，或者关闭严格模式写，跟js没什么区别

**Comment by M69W** [comment]
也可以使用 JavaScript 写法呀
比如 vue 里面 `<script setup lang="ts">` 这里去掉
