### ISSUE TITLE
Bug: electron-vit分支下的内容运行之后样式混乱

### ISSUE THREAD

**Issue by sxlh0814** [vbenjs/vue-vben-admin#4256]
### Version

Vben Admin V5

### Describe the bug?

我更新了V5,然后下载了electron-vit这个版本,然后发现样式混乱
<img width="916" alt="image" src="https://github.com/user-attachments/assets/df54a10d-7a26-4d85-9b5b-7373fc414c44">

### Reproduction

官方的git上electron-vit分支

### System Info

```shell
mac系统 谷歌浏览器
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
electron 还未支持，不要使用
