### ISSUE TITLE
Bug: 5.2.0在亮色主题下，登录页背景还是黑色

### ISSUE THREAD

**Issue by zxuanhong** [vbenjs/vue-vben-admin#4278]
### Version

Vben Admin V5

### Describe the bug?

5.2.0在亮色主题下，登录页背景还是黑色

### Reproduction

1. 登录页切换到亮色主题
2. 登录页左侧背景还是黑色

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 4.22 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
    pnpm: 9.0.5 - ~/.nvm/versions/node/v20.11.1/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.86
    Safari: 17.6
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
这个是预期的

**Comment by zxuanhong** [comment]
@anncwb 说实话，不理解。亮色主题不应该是白色或者其他吗？？我记得5.0好像是白色(也可能记错了)

**Comment by zxuanhong** [comment]
@anncwb 刚看了master代码，已经正常
