### ISSUE TITLE
Bug: FileUpload组件 上传多个组件时 点击删除图标 所有文件都被删除了

### ISSUE THREAD

**Issue by Deepembrace** [vbenjs/vue-vben-admin#4279]
### Version

Vben Admin V2

### Describe the bug?

FileUpload组件 上传多个组件时 删除其中的某一个会导致所有的文件都被删除
<img width="492" alt="image" src="https://github.com/user-attachments/assets/05a7f6a2-0c82-45ac-9aec-56d78644a247">
{
		label: '项目附件',
		field: 'file',
		component: 'FileUpload',
		labelWidth: 80,
		componentProps: {
			fileType: 'file',
			maxCount: 5,
		},

	},

### Reproduction

1

### System Info

```shell
1
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aonoa** [comment]
Vben Admin V5 有文件上传组件？

**Comment by zqxxjs** [comment]
这确实是一个bug，我自己改好了

**Comment by tuin77** [comment]
> 这确实是一个bug，我自己改好了

你好在form componentMap里面没有找到FileUpload组件，这个组件哪里的自己封装的吗 想试试怎么复现

**Comment by Deepembrace** [comment]
> 这确实是一个bug，我自己改好了

咋改的呀

**Comment by Deepembrace** [comment]
> > 这确实是一个bug，我自己改好了
> 
> 你好在form componentMap里面没有找到FileUpload组件，这个组件哪里的自己封装的吗想试试怎么复现

<img width="1500" alt="image" src="https://github.com/user-attachments/assets/16fd1bf3-fbfd-40b0-82ac-9154dbca56a4">

**Comment by Deepembrace** [comment]
> > 这确实是一个bug，我自己改好了
> 
> 你好在form componentMap里面没有找到FileUpload组件，这个组件哪里的自己封装的吗 想试试怎么复现

<img width="1500" alt="image" src="https://github.com/user-attachments/assets/59cfabbd-7f67-47ba-b1bd-ab6717cf3aef">

**Comment by zqxxjs** [comment]
![image](https://github.com/user-attachments/assets/68ea2359-b8b9-4718-b920-4cf9c1c0a823)

**Comment by Deepembrace** [comment]
> ![图像](https://private-user-images.githubusercontent.com/125987992/365357237-68ea2359-b8b9-4718-b920-4cf9c1c0a823.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDQ0NTAsIm5iZiI6MTcyNTg0NDE1MCwicGF0aCI6Ii8xMjU5ODc5OTIvMzY1MzU3MjM3LTY4ZWEyMzU5LWI4YjktNDcxOC1iOTIwLTRjZjljMWMwYTgyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMTA5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZWU2MzQ3NDYzN2RmNjdlZDdmMTlkNDczYzgyZjZmMDExYjBhZWNjODFmNjg4YzM0NDAxMjNkZjU5NzQ0YzhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SATPqcHeXp3dJasavHryZuESEazvbGdLEEibzF1MLl8)

我们好像不是用的同一个组件，我是在FormSchema 里面用的FileUpload组件，呈现方式是这样的
![Uploading image.png…]()

**Comment by Deepembrace** [comment]
> ![图像](https://private-user-images.githubusercontent.com/125987992/365357237-68ea2359-b8b9-4718-b920-4cf9c1c0a823.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDU4MjksIm5iZiI6MTcyNTg0NTUyOSwicGF0aCI6Ii8xMjU5ODc5OTIvMzY1MzU3MjM3LTY4ZWEyMzU5LWI4YjktNDcxOC1iOTIwLTRjZjljMWMwYTgyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMTMyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmIzMWU4YzcyNmRhZDE2OTViMGRlMmE4NTljMGFhM2RkYjBiZTFkMGY0ODYzZmFhYWYxYzNmZDg1ZWM3MjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IMyjYQguYrkLFenfKkcT1MtmQrOVDgboLQehWWbW6WI)

我们用的好像不是同一个上传组件，我是在Form里面用的FileUpload组件
![Uploading image.png…]()

**Comment by zqxxjs** [comment]
我用的是v4版本
![image](https://github.com/user-attachments/assets/9e212c9d-116c-40f4-8784-e27c07f44d61)

**Comment by Deepembrace** [comment]
> 我用的是v4版本 ![image](https://private-user-images.githubusercontent.com/125987992/365486914-9e212c9d-116c-40f4-8784-e27c07f44d61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDY4NzksIm5iZiI6MTcyNTg0NjU3OSwicGF0aCI6Ii8xMjU5ODc5OTIvMzY1NDg2OTE0LTllMjEyYzlkLTExNmMtNDBmNC04Nzg0LWUyN2MwN2Y0NGQ2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMTQ5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDhlZWI5ZDA1Yjc0ZTU5ZWU2ZDFhMGI4MmNkMzEyNjEwYWZlYmIxODA4ZDcxMjg1MTg5MWI0NDlmY2EwM2NjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cCVUWzMS8Ip9RgpAd8mdi6mAMIsWKvlruhWeR9waBzc)

ni z

**Comment by Deepembrace** [comment]
> 我用的是v4版本 ![image](https://private-user-images.githubusercontent.com/125987992/365486914-9e212c9d-116c-40f4-8784-e27c07f44d61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDcwNDUsIm5iZiI6MTcyNTg0Njc0NSwicGF0aCI6Ii8xMjU5ODc5OTIvMzY1NDg2OTE0LTllMjEyYzlkLTExNmMtNDBmNC04Nzg0LWUyN2MwN2Y0NGQ2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMTUyMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05M2M2ZDBmYzBhZjAyZDkxODdmMDBlNzZkNzU2YjQzODhkMTVhNzA2MjYzOTIyZjlhYTY4MGY4MGQ3MDljMjAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X-yt5nvUdgQIZORDzJNttlmbNJtXPhnGlWxM6KykuIU)

你的删除操作都是在表格里面的，这个v2版本的FileUpload组件删除操作和ui框架的删除操作是一样的 点击文件名后的icon 删除 ，UI框架的删除是正常的
