### ISSUE TITLE
Bug:接口请求错误提示词不正确，始终返回的是框架内置错误

### ISSUE THREAD

**Issue by fluxcky** [vbenjs/vue-vben-admin#4282]
### Version

Vben Admin V5

### Describe the bug?

接口请求错误提示词不正确，始终返回的是框架内置错误，preset-interceptors.ts 文件97行缺少一个判断。

### Reproduction

无

### System Info

```shell
无
```

### Relevant log output

```shell
无
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
client.addResponseInterceptor(
    errorMessageResponseInterceptor((msg: string, error: any) => {
      // 这里可以自行处理了
      const errorMessage = error?.response?.data?.error?.message ?? '';
      const status = error?.response?.status;
      message.error(msg);
    }),
  );
