### ISSUE TITLE
Bug: 后端token失效时，刷新页面不能跳转至登录页

### ISSUE THREAD

**Issue by thanksU** [vbenjs/vue-vben-admin#4284]
### Version

Vben Admin V5

### Describe the bug?

后端设置的token失效时间为2分钟，2分钟后点击浏览器刷新按钮时，页面提示登录过期，进度条便一直在加载，不能跳转至登录页，需要再次点击浏览器刷新按钮，页面才能跳转至登录页。

### Reproduction

![1](https://github.com/user-attachments/assets/bb51320a-33e2-4126-bc38-c064492feb20)
![2](https://github.com/user-attachments/assets/b322e058-86c9-42fb-951a-d54f33292dd4)
![3](https://github.com/user-attachments/assets/ba1a33d3-df07-420e-8a4f-9a126481298a)

### System Info

```shell
...
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
代码是最新的吗

**Comment by likui628** [comment]
![image](https://github.com/user-attachments/assets/582775e1-047b-4f4d-83df-937e607b2d48)

**Comment by likui628** [comment]
有没有/auth/logout接口，
api/core/auth.ts内logoutApi是不是使用的baseRequestClient
```
export async function logoutApi() {
  return baseRequestClient.post('/auth/logout', {
    withCredentials: true,
  });
}
```

你还是要确认下是否为最新代码的
