### ISSUE TITLE
Bug: 样式bug

### ISSUE THREAD

**Issue by zhuizhubf** [vbenjs/vue-vben-admin#4295]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/78f9cbe6-963b-4b2a-9c19-8cd4b28f1e0a)
在弹窗后 位置出现偏差
![image](https://github.com/user-attachments/assets/ee8cb00c-3cde-47ee-ad44-158fe5d42486)

------

在 ele dark 中使用  el-table 样式 hover current-row 会出现
![image](https://github.com/user-attachments/assets/a1f60a84-a673-4701-80ed-f58f1c526d18)
导致不能正常处理

### Reproduction

https://www.vben.pro/#/examples/drawer

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 6.85 GB / 31.91 GB
  Binaries:
    Node: 20.12.2 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.0 - D:\Program Files\nodejs\npm.CMD
    pnpm: 9.5.0 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
滚动条是预期的

**Comment by likui628** [comment]
弹窗时滚动条消失了，看起来是有点偏移

**Comment by likui628** [comment]
@anncwb element-plus的样式有点头疼，你看下

**Comment by Zhao-sj** [comment]
element-plus在暗黑模式下Tag、Tree、Select、Table等这些组件在hover时样式都是亮色模式下的主题
![image](https://github.com/user-attachments/assets/b6cd00a3-2fda-4d1f-9775-760d87006aaf)

**Comment by Zhao-sj** [comment]
弹窗组件默认的footer插槽中按钮文字没有支持i18n；取消和确定按钮必须同时存在，否则就得自己重新定义插槽，可不可以支持单独控制显示
