### ISSUE TITLE
FEATURE: vben框架的table组件中的可编辑列，是否可以通过配置实现实时输入的功能

### ISSUE THREAD

**Issue by alucardxh** [vbenjs/vue-vben-admin#4299]
### Version

Vben Admin V2

### Description

https://procomponents.ant.design/components/editable-table#%E5%AE%9E%E6%97%B6%E4%BF%9D%E5%AD%98%E7%9A%84%E7%BC%96%E8%BE%91%E8%A1%A8%E6%A0%BC
类似antd的pro组件里的实时输入，表格中的所有项都是可以编辑状态，最后总体提交功能。根据demo中列的action获取到的是EditRecordRow对象修改onEdit属性就可以编辑，但是不知道有没有方法可以一次性获取到所有行的EditRecordRow对象，然后批量修改该属性，这种做法是hack的做法吗？

### Proposed Solution

希望可以加入实时编辑的功能或者有实时编辑的demo

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by vince292007** [comment]
v2版本不会在新增功能
