### ISSUE TITLE
Bug: 移动设备下无法点击tab返回到默认标签页

### ISSUE THREAD

**Issue by imdap** [vbenjs/vue-vben-admin#4301]
### Version

Vben Admin V5

### Describe the bug?

移动设备下无法点击tab返回到默认标签页

### Reproduction

1. 开发者工具 & 切换到移动设备
![image](https://github.com/user-attachments/assets/466176f3-1669-4331-9505-bafcb5498407)
2. https://www.vben.pro/#/analytics
3. 随便点击一个页面  此时点击tab的`分析页` 无法切换
![image](https://github.com/user-attachments/assets/980ef36a-fc23-4779-83d3-97687122228d)

包括在真机测试也是同样问题

### System Info

```shell
Binaries:
    Node: 20.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.5.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wangjue666** [comment]
奇怪 我这边手机跟模拟器测试发现没有问题

**Comment by imdap** [comment]
https://github.com/user-attachments/assets/73b8149e-4833-4a6e-933b-bfab5d1dfb9e

**Comment by wangjue666** [comment]
定位到问题了 是tabs的拖拽导致的问题
