### ISSUE TITLE
Docs: 请问如何更新ApiSelect 的值，在开启搜索的情况

### ISSUE THREAD

**Issue by zqxxjs** [vbenjs/vue-vben-admin#4302]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [ ] Confusing
- [X] Not sure?

### Explain in Detail

我稍稍修改了一ApiSelect组件，开启了多选和搜索功能，但是有个难题，比如我用搜索接口搜到的选项，保存后再次打开模态框回显表单的时候如何传递参数？因为ApiSelect 它接收一个api函数参数，默认加载前十条，但搜索的选项不在前十条，回显的时候就只显示value，如图：
![image](https://github.com/user-attachments/assets/658bbdc0-3ce4-4cb5-8b31-7a0e0a55965e)
`{
    field: 'receiver.userList',
    label: '接收人',
    //required: true,
    component: 'ApiSelect',
    componentProps: {
      api: getSysUserList,
      labelField: 'username',
      valueField: 'id',
      resultField: 'data',
      mode: 'multiple',
    },
  },`
ApiSelect 代码如下（改的可能不太好，勿怪，如有建议，虚心接收）： 
`<template>
  <Select
    :show-search="true"
    v-bind="$attrs"
    @change="handleChange"
    @search="handleSearch"
    :options="getOptions"
    :default-active-first-option="false"
    :show-arrow="false"
    :filter-option="false"
    :not-found-content="null"
    v-model:value="state"
    :mode="mode"
  >
    <template #[item]="data" v-for="item in Object.keys($slots)">
      <slot :name="item" v-bind="data || {}"></slot>
    </template>
    <template #suffixIcon v-if="loading">
      <LoadingOutlined spin />
    </template>
    <template #notFoundContent v-if="loading">
      <span>
        <LoadingOutlined spin class="mr-1" />
        {{ t('component.form.apiSelectNotFound') }}
      </span>
    </template>
  </Select>
</template>
<script lang="ts" setup>
  import { PropType, ref, computed, unref, watch } from 'vue';
  import { Select } from 'ant-design-vue';
  import type { SelectValue } from 'ant-design-vue/es/select';
  import { isFunction } from '@/utils/is';
  import { useRuleFormItem } from '@/hooks/component/useFormItem';
  import { get, omit, isEqual } from 'lodash-es';
  import { LoadingOutlined } from '@ant-design/icons-vue';
  import { useI18n } from '@/hooks/web/useI18n';
  import { propTypes } from '@/utils/propTypes';

  type OptionsItem = { label?: string; value?: string; disabled?: boolean; [name: string]: any };

  defineOptions({ name: 'ApiSelect', inheritAttrs: false });
  type ModeType = "multiple" | "tags" | "SECRET_COMBOBOX_MODE_DO_NOT_USE" | undefined;
  const props = defineProps({
    value: { type: [Array, Object, String, Number] as PropType<SelectValue> },
    numberToString: propTypes.bool,
    api: {
      type: Function as PropType<(arg?: any) => Promise<OptionsItem[] | Recordable<any>>>,
      default: null,
    },
    // api params
    params: propTypes.any.def({}),
    // support xxx.xxx.xx
    resultField: propTypes.string.def(''),
    labelField: propTypes.string.def('label'),
    valueField: propTypes.string.def('value'),
    immediate: propTypes.bool.def(true),
    alwaysLoad: propTypes.bool.def(false),
    keyField: propTypes.string.def('key'),
    triggerLength: propTypes.number.def(2), //多少字符触发接口请求
    options: {
      type: Array<OptionsItem>,
      default: [],
    },
    beforeFetch: {
      type: Function as PropType<Fn>,
      default: null,
    },
    afterFetch: {
      type: Function as PropType<Fn>,
      default: null,
    },
    mode: {
      type: String as PropType<ModeType>,
      default: 'tags',
    },
  });

  const emit = defineEmits(['options-change', 'change', 'update:value']);

  const optionsRef = ref<OptionsItem[]>([]);

  const loading = ref(false);
  // 首次是否加载过了
  const isFirstLoaded = ref(false);
  const emitData = ref<OptionsItem[]>([]);
  const { t } = useI18n();

  // Embedded in the form, just use the hook binding to perform form verification
  const [state] = useRuleFormItem(props, 'value', 'change', emitData);

  const getOptions = computed(() => {
    const { labelField, valueField, numberToString } = props;

    let data = unref(optionsRef).reduce((prev, next: any) => {
      if (next) {
        const value = get(next, valueField);
        prev.push({
          ...omit(next, [labelField, valueField]),
          label: get(next, labelField),
          value: numberToString ? `${value}` : value,
        });
      }
      return prev;
    }, [] as OptionsItem[]);

    return data.length > 0 ? data : props.options;
  });

  watch(
    () => state.value,
    (v) => {
      emit('update:value', v);
    },
  );

  watch(
    () => props.params,
    (value, oldValue) => {
      if (isEqual(value, oldValue)) return;
      fetch();
    },
    { deep: true, immediate: props.immediate },
  );

  async function fetch() {
    let { api, beforeFetch, afterFetch, params, resultField } = props;
    if (!api || !isFunction(api) || loading.value) return;
    optionsRef.value = [];
    try {
      loading.value = true;
      if (beforeFetch && isFunction(beforeFetch)) {
        params = (await beforeFetch(params)) || params;
      }
      let res = await api(params);
      if (afterFetch && isFunction(afterFetch)) {
        res = (await afterFetch(res)) || res;
      }
      isFirstLoaded.value = true;
      if (Array.isArray(res)) {
        optionsRef.value = res;
        emitChange();
        return;
      }
      if (resultField) {
        optionsRef.value = get(res, resultField) || [];
      }
      emitChange();
    } catch (error) {
      console.warn(error);
      // reset status
      isFirstLoaded.value = false;
    } finally {
      loading.value = false;
    }
  }

  async function handleFetch(visible: boolean) {
    if (visible) {
      if (props.alwaysLoad) {
        await fetch();
      } else if (!props.immediate && !unref(isFirstLoaded)) {
        await fetch();
      }
    }
  }

  function emitChange() {
    emit('options-change', unref(getOptions));
    handleFetch(false);
  }

  function handleChange(_, ...args) {
    emitData.value = args;
  }

  function handleSearch(kw: string) {
    //大于触发长度时开启接口请求，参数如下：
    if (kw.length >= props.triggerLength) {
      props.params.conditions = [
        { fieldName: 'columnNames', condition: 'In', values: [props.labelField, props.valueField] },
        { fieldName: props.labelField, condition: 'Like', values: [kw] },
        { fieldName: 'pn', condition: 'EqualTo', values: ['1'] },
        { fieldName: 'pz', condition: 'EqualTo', values: ['5'] },
      ];
      fetch();
    }
  }
</script>`

### Your Suggestion for Changes

想知道如何在ApiSelect 加载回显数据的时候可以正确显示那些搜索到的选项。

### Steps to reproduce

步骤没啥，就是参照示例代码写的 model.data.ts Index.vue Modal.vue
然后就发现ApiSelect 无法正确回显搜索项的数据，即搜索项不在api默认加载的前几条数据中

**Comment by mynetfan** [comment]
多选内容不在已加载的options中时就不会被正确渲染。这种情况可以使用tagRender插槽来处理。
https://www.antdv.com/components/select-cn#components-select-demo-option-label-prop

**Comment by zqxxjs** [comment]
非常感谢！
