### ISSUE TITLE
FEATURE: 发布一些公共组件类似于antdesign的pro components

### ISSUE THREAD

**Issue by AnLiBoBo** [vbenjs/vue-vben-admin#4306]
### Version

Vben Admin V5

### Description

我看vben已经把一些公共的组件都抽离出来了,我在想既然公共组件已经抽离出来,为什么不直接发布成一个npm package呢,这样对项目来说,目录结构应该还可以再简洁一些

### Proposed Solution

publish npm package

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by wangjue666** [comment]
发布成npm包的话，微调组件细节的话不方便， 可能是出于这样的顾虑，未来可能会弄成`shadcn`这种组件分发形式

**Comment by yang-xianzhu** [comment]
> 发布成npm包的话，微调组件细节的话不方便， 可能是出于这样的顾虑，未来可能会弄成`shadcn`这种组件分发形式

是直接把源代码download到本地项目里吗

**Comment by wangjue666** [comment]
是呢，不过这个功能还得稍微放放，作者先着手弄 `form `和 `table`组件

**Comment by yang-xianzhu** [comment]
> 是呢，不过这个功能还得稍微放放，作者先着手弄 `form `和 `table`组件

请问一下以后会出一个后端和前端的配套代码吗，就实现登录到菜单、角色管理这些基础模块那种

**Comment by likui628** [comment]
> > 是呢，不过这个功能还得稍微放放，作者先着手弄 `form `和 `table`组件
> 
> 请问一下以后会出一个后端和前端的配套代码吗，就实现登录到菜单、角色管理这些基础模块那种

应该会有社区版本

**Comment by mark0614** [comment]
期待啊
