### ISSUE TITLE
Bug: requestClient.upload上传有问题

### ISSUE THREAD

**Issue by leikui** [vbenjs/vue-vben-admin#4311]
### Version

Vben Admin V5

### Describe the bug?

requestClient.upload上传有问题报错

### Reproduction

const beforeUpload = (file) => {
  console.log(file);

  handleUpload(file)
  fileList.value = [...(fileList.value || []), file];
  return false;
};
function handleDrop(e: DragEvent) {
  console.log(e);
}

const handleUpload = (file) => {

  upLoadFileAPI(file)
    .then(() => {
      fileList.value = [];
      message.success('upload successfully.');
    })
    .catch(() => {
      message.error('upload failed.');
    });
};

/**
 * 上传文件
 */
export async function upLoadFileAPI(param? :any) {
  return requestClient.upload('/file/upload',param);
}

![image](https://github.com/user-attachments/assets/512e43e5-b763-47e1-b118-8782f1e20c04)
![image](https://github.com/user-attachments/assets/c48187dc-c699-44f4-b1e0-788bbae2a3b2)
![image](https://github.com/user-attachments/assets/925b45b5-2fad-4075-8799-2c390d60f45b)

### System Info

```shell
5.1.0
```

### Validations

- [x] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by wangxiaoer5200** [comment]
看你上传连接怎么把请求头参数配置到地址参数去了

**Comment by leikui** [comment]
> 看你上传连接怎么把请求头参数配置到地址参数去了

我用的是框架封装的requestClient.upload，
<img width="1064" alt="image" src="https://github.com/user-attachments/assets/6baea418-2b75-461e-ae6f-27020269e6db">

**Comment by leikui** [comment]
> 看你上传连接怎么把请求头参数配置到地址参数去了
或者就是我用的方法不对

**Comment by leikui** [comment]
> 看你上传连接怎么把请求头参数配置到地址参数去了

是我的问题 ，麻烦关闭下
