### ISSUE TITLE
Bug:  pnpm install 报错

### ISSUE THREAD

**Issue by gitskybo** [vbenjs/vue-vben-admin#4316]
### Version

Vben Admin V5

### Describe the bug?

pnpm install
Scope: all 41 workspace projects
Lockfile is up to date, resolution step is skipped
Packages: +1
+
Progress: resolved 1, reused 1, downloaded 0, added 0, done
. postinstall$ turbo run stub
│ turbo 2.1.1
│ • Packages in scope: @vben-core/composables, @vben-core/design, @vben-core/icons, @vben-core/layout-ui, @vben-core/menu-ui, …
│ • Running stub in 40 packages
│ • Remote caching disabled
│ @vben/turbo-run:stub: cache miss, executing e0c5046494ea38bf
│ @vben/tailwind-config:stub: cache miss, executing d8996e007f0984c9
│ @vben/eslint-config:stub: cache miss, executing 7ad7ca2e3b435dcc
│ @vben/node-utils:stub: cache miss, executing 23faa3cc79e3af77
│ @vben/vsh:stub: cache miss, executing d3988873df419e05
│ @vben/vite-config:stub: cache miss, executing 898e7bc3842c590f
│ @vben/turbo-run:stub:
│ @vben/turbo-run:stub: > @vben/turbo-run@5.2.1 stub D:\Dev\itskybo-open-vue\scripts\turbo-run
│ @vben/turbo-run:stub: > pnpm unbuild --stub
│ @vben/turbo-run:stub:
│ @vben/tailwind-config:stub:
│ @vben/tailwind-config:stub: > @vben/tailwind-config@5.2.1 stub D:\Dev\itskybo-open-vue\internal\tailwind-config
│ @vben/tailwind-config:stub: > pnpm unbuild --stub
│ @vben/tailwind-config:stub:
│ @vben/turbo-run:stub: 'pnpm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
│ @vben/turbo-run:stub: ���������ļ���
│ @vben/tailwind-config:stub: 'pnpm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
│ @vben/tailwind-config:stub: ���������ļ���
│ @vben/turbo-run:stub:  ELIFECYCLE  Command failed with exit code 1.
│ @vben/tailwind-config:stub:  ELIFECYCLE  Command failed with exit code 1.
│ @vben/tailwind-config:stub: node:events:497
│ @vben/tailwind-config:stub:       throw er; // Unhandled 'error' event
│ @vben/tailwind-config:stub:       ^
│ @vben/tailwind-config:stub:
│ @vben/tailwind-config:stub: Error: read ENOTCONN
│ @vben/tailwind-config:stub:     at tryReadStart (node:net:703:20)
│ @vben/tailwind-config:stub:     at Socket._read (node:net:718:5)
│ @vben/tailwind-config:stub:     at Readable.read (node:internal/streams/readable:737:12)
│ @vben/tailwind-config:stub:     at Socket.read (node:net:773:39)
│ @vben/tailwind-config:stub:     at new Socket (node:net:487:12)
│ @vben/tailwind-config:stub:     at Object.Socket (node:net:356:41)
│ @vben/tailwind-config:stub:     at createSocket (node:internal/child_process:336:14)
│ @vben/tailwind-config:stub:     at ChildProcess.spawn (node:internal/child_process:451:23)
│ @vben/tailwind-config:stub:     at spawn (node:child_process:762:9)
│ @vben/tailwind-config:stub:     at run (C:\Users\fuen\AppData\Local\node\corepack\v1\pnpm\9.9.0\dist\pnpm.cjs:3755:16)
│ @vben/tailwind-config:stub: Emitted 'error' event on Socket instance at:
│ @vben/tailwind-config:stub:     at emitErrorNT (node:internal/streams/destroy:169:8)
│ @vben/tailwind-config:stub:     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
│ @vben/tailwind-config:stub:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
│ @vben/tailwind-config:stub:   errno: -4053,
│ @vben/tailwind-config:stub:   code: 'ENOTCONN',
│ @vben/tailwind-config:stub:   syscall: 'read'
│ @vben/tailwind-config:stub: }
│ @vben/tailwind-config:stub:
│ @vben/tailwind-config:stub: Node.js v20.17.0
│ @vben/turbo-run:stub: node:events:497
│ @vben/turbo-run:stub:       throw er; // Unhandled 'error' event
│ @vben/turbo-run:stub:       ^
│ @vben/turbo-run:stub:
│ @vben/turbo-run:stub: Error: read ENOTCONN
│ @vben/turbo-run:stub:     at tryReadStart (node:net:703:20)
│ @vben/turbo-run:stub:     at Socket._read (node:net:718:5)
│ @vben/turbo-run:stub:     at Readable.read (node:internal/streams/readable:737:12)
│ @vben/turbo-run:stub:     at Socket.read (node:net:773:39)
│ @vben/turbo-run:stub:     at new Socket (node:net:487:12)
│ @vben/turbo-run:stub:     at Object.Socket (node:net:356:41)
│ @vben/turbo-run:stub:     at createSocket (node:internal/child_process:336:14)
│ @vben/turbo-run:stub:     at ChildProcess.spawn (node:internal/child_process:451:23)
│ @vben/turbo-run:stub:     at spawn (node:child_process:762:9)
│ @vben/turbo-run:stub:     at run (C:\Users\fuen\AppData\Local\node\corepack\v1\pnpm\9.9.0\dist\pnpm.cjs:3755:16)
│ @vben/turbo-run:stub: Emitted 'error' event on Socket instance at:
│ @vben/turbo-run:stub:     at emitErrorNT (node:internal/streams/destroy:169:8)
│ @vben/turbo-run:stub:     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
│ @vben/turbo-run:stub:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
│ @vben/turbo-run:stub:   errno: -4053,
│ @vben/turbo-run:stub:   code: 'ENOTCONN',
│ @vben/turbo-run:stub:   syscall: 'read'
│ @vben/turbo-run:stub: }
│ @vben/turbo-run:stub:
│ @vben/turbo-run:stub: Node.js v20.17.0
│ @vben/eslint-config:stub:
│ @vben/eslint-config:stub: > @vben/eslint-config@5.0.0 stub D:\Dev\itskybo-open-vue\internal\lint-configs\eslint-config
│ @vben/eslint-config:stub: > pnpm unbuild --stub
│ @vben/eslint-config:stub:
│ @vben/tailwind-config:stub: ERROR: command finished with error: command (D:\Dev\itskybo-open-vue\internal\tailwind-config) D…
│ @vben/node-utils:stub:
│ @vben/node-utils:stub: > @vben/node-utils@5.2.1 stub D:\Dev\itskybo-open-vue\internal\node-utils
│ @vben/node-utils:stub: > pnpm unbuild --stub
│ @vben/node-utils:stub:
│ @vben/vsh:stub:
│ @vben/vsh:stub: > @vben/vsh@5.2.1 stub D:\Dev\itskybo-open-vue\scripts\vsh
│ @vben/vsh:stub: > pnpm unbuild --stub
│ @vben/vsh:stub:
│ @vben/node-utils:stub: 'pnpm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
│ @vben/vsh:stub: 'pnpm' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
│ @vben/node-utils:stub: ���������ļ���
│ @vben/vsh:stub: ���������ļ���
│ @vben/tailwind-config#stub: command (D:\Dev\itskybo-open-vue\internal\tailwind-config) D:\Program Files\nodejs\pnpm.CMD run …
│  Tasks:    0 successful, 6 total
│ Cached:    0 cached, 6 total
│   Time:    1.901s
│ Failed:    @vben/tailwind-config#stub
│  ERROR  run failed: command  exited (1)
└─ Failed in 2.4s at D:\Dev\itskybo-open-vue
 ELIFECYCLE  Command failed with exit code 1.

### Reproduction

开始开始时就遇到了

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i9-13900H
    Memory: 14.33 GB / 31.66 GB
  npmPackages:
    @changesets/changelog-github: ^0.5.0 => 0.5.0
    @changesets/cli: ^2.27.7 => 2.27.7
    @types/jsdom: ^21.1.7 => 21.1.7
    @types/node: ^22.5.1 => 22.5.3
    @vben/commitlint-config: workspace:* => 5.2.1
    @vben/eslint-config: workspace:* => 5.0.0
    @vben/prettier-config: workspace:* => 5.0.0
    @vben/stylelint-config: workspace:* => 5.2.1
    @vben/tailwind-config: workspace:* => 5.2.1
    @vben/tsconfig: workspace:* => 5.2.1
    @vben/turbo-run: workspace:* => 5.2.1
    @vben/vite-config: workspace:* => 5.2.1
    @vben/vsh: workspace:* => 5.2.1
    @vitejs/plugin-vue: ^5.1.3 => 5.1.3
    @vitejs/plugin-vue-jsx: ^4.0.1 => 4.0.1
    @vue/test-utils: ^2.4.6 => 2.4.6
    autoprefixer: ^10.4.20 => 10.4.20
    cross-env: ^7.0.3 => 7.0.3
    cspell: ^8.14.2 => 8.14.2
    husky: ^9.1.5 => 9.1.5
    is-ci: ^3.0.1 => 3.0.1
    jsdom: ^25.0.0 => 25.0.0
    lint-staged: ^15.2.9 => 15.2.10
    rimraf: ^6.0.1 => 6.0.1
    tailwindcss: ^3.4.10 => 3.4.10
    turbo: ^2.1.0 => 2.1.1
    typescript: ^5.5.4 => 5.5.4
    unbuild: ^2.0.0 => 2.0.0
    vite: ^5.4.2 => 5.4.3
    vitest: ^2.0.5 => 2.0.5
    vue: ^3.4.38 => 3.4.38
    vue-tsc: ^2.1.2 => 2.1.4
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Deepembrace** [comment]
建议用pnpm吧

**Comment by likui628** [comment]
怀疑是不是网络问题
Error: read ENOTCONN

**Comment by gitskybo** [comment]
> 建议用pnpm吧

现在用的就是pnpm就行操作的呢

**Comment by gitskybo** [comment]
> 怀疑是不是网络问题 Error: read ENOTCONN

出去和不出去都报错的。

**Comment by likui628** [comment]
https://doc.vben.pro/guide/other/faq.html#%E4%BE%9D%E8%B5%96%E5%AE%89%E8%A3%85%E9%97%AE%E9%A2%98

试一下

**Comment by gitskybo** [comment]
> https://doc.vben.pro/guide/other/faq.html#%E4%BE%9D%E8%B5%96%E5%AE%89%E8%A3%85%E9%97%AE%E9%A2%98
> 
> 试一下

多谢，目前已经尝试过重装node, pnpm, 重新下拉项目，pnpm  reinstall 也不成功。尝试设置了npm和pnpm 镜像切换，国内外镜像都试过了
![image](https://github.com/user-attachments/assets/5152af15-b660-492f-b5a3-017e84e7129e)

**Comment by chenzhenming** [comment]
> > https://doc.vben.pro/guide/other/faq.html#%E4%BE%9D%E8%B5%96%E5%AE%89%E8%A3%85%E9%97%AE%E9%A2%98
> > 试一下
> 
> 多谢，目前已经尝试过重装node, pnpm, 重新下拉项目，pnpm reinstall 也不成功。尝试设置了npm和pnpm 镜像切换，国内外镜像都试过了 ![image](https://private-user-images.githubusercontent.com/57713058/364591204-5152af15-b660-492f-b5a3-017e84e7129e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDUzOTQsIm5iZiI6MTcyNjY0NTA5NCwicGF0aCI6Ii81NzcxMzA1OC8zNjQ1OTEyMDQtNTE1MmFmMTUtYjY2MC00OTJmLWI1YTMtMDE3ZTg0ZTcxMjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA3MzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZjdiYjdhYjBmNGVlOTY0OThjMjZjZWQyYjgyNGFhNGMxMDFjN2M1YzZlYjRhODI0NDdmZjM2MjI0ZWMzYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oVUihwEobWrnxZTtTqoJU0rULhAvCGOyTM7ZRNBsPvk)

你好，这个问题你后面有成功的吗？我也是有这个问题

**Comment by gitskybo** [comment]
> > > https://doc.vben.pro/guide/other/faq.html#%E4%BE%9D%E8%B5%96%E5%AE%89%E8%A3%85%E9%97%AE%E9%A2%98
> > > 试一下
> > 
> > 
> > 多谢，目前已经尝试过重装node, pnpm, 重新下拉项目，pnpm reinstall 也不成功。尝试设置了npm和pnpm 镜像切换，国内外镜像都试过了 ![image](https://private-user-images.githubusercontent.com/57713058/364591204-5152af15-b660-492f-b5a3-017e84e7129e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDUzOTQsIm5iZiI6MTcyNjY0NTA5NCwicGF0aCI6Ii81NzcxMzA1OC8zNjQ1OTEyMDQtNTE1MmFmMTUtYjY2MC00OTJmLWI1YTMtMDE3ZTg0ZTcxMjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA3MzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZjdiYjdhYjBmNGVlOTY0OThjMjZjZWQyYjgyNGFhNGMxMDFjN2M1YzZlYjRhODI0NDdmZjM2MjI0ZWMzYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oVUihwEobWrnxZTtTqoJU0rULhAvCGOyTM7ZRNBsPvk)
> 
> 你好，这个问题你后面有成功的吗？我也是有这个问题

没有实质性的解决方案，靠天处理，目前等table组件出来之后再拉源码试试
