### ISSUE TITLE
FEATURE: 建议不要同时支持多个ui，给用户的选择越少越好

### ISSUE THREAD

**Issue by rain7788** [vbenjs/vue-vben-admin#4323]
### Version

Vben Admin V5

### Description

目前我们项目支持了多个ui，源码里各种重复的文件让有洁癖的人很是头疼。我们并不打算直接拿来某个版本修改，而是想长期订阅最新版本，并合并到我们的项目上。

### Proposed Solution

建议给用户少一些选择，采用ele或ant都可以，我们采用第三方框架就是为了简单些，如果想要兼容多个ui，可以另起文件夹写一些demo来告诉这些有特殊需求的人。

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by likui628** [comment]
你说的有道理，但是又不好办。

**Comment by vince292007** [comment]
少量的代码重复没什么问题，如果你只要某个UI，只要按照文档去精简就好。当你确定了某个UI后，你甚至可以自己写脚本，在每次pull同步的时候，自动做精简删除目录的事，我感觉这个不是问题
