### ISSUE TITLE
Bug: The CJS build of Vite's Node API is deprecated

### ISSUE THREAD

**Issue by ah-kevin** [vbenjs/vue-vben-admin#4325]
### Version

Vben Admin V5

### Describe the bug?

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

### Reproduction

项目拉下来,install, dev会直接有这个warn

### System Info

```shell
无
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
unbuild 依赖的jiti这个包导致的，不影响使用。等后续 jiti 升级即可

**Comment by anncwb** [comment]
dev已经禁用这个提示。
