### ISSUE TITLE
Docs: 中文简介第一句话

### ISSUE THREAD

**Issue by RanGuMo** [vbenjs/vue-vben-admin#4328]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [X] Confusing
- [ ] Not sure?

### Explain in Detail

简介
Vue Vben Admin 是 Vue Vben Admin 的升级版本。

### Your Suggestion for Changes

简介
Vue Vben Admin 是 XXX 的升级版本。

**Comment by wangz-code** [comment]
V5是完全不同的大版本了吧,   基本上属于换了一个框架, 虽然代码就那些  v2 几乎不太可能升级
