### ISSUE TITLE
Bug: FileUpload组件 上传多个文件，点击删除icon，所有文件都被删了

### ISSUE THREAD

**Issue by Natie00** [vbenjs/vue-vben-admin#4329]
### Version

Vben Admin V5

### Describe the bug?

![1725610899142](https://github.com/user-attachments/assets/794acffa-6af5-4888-a8db-69481367caf3)

### Reproduction

![Uploading 1725610899142.jpg…]()

### System Info

```shell
vue3、ant-design-vue 4.0、google
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
v5 版本好像没有 FileUpload 组件吧。如果是旧版本，需要自己解决，或者向组件库提
