### ISSUE TITLE
FEATURE: 更多echarts示例

### ISSUE THREAD

**Issue by 1571312541** [vbenjs/vue-vben-admin#4334]
### Version

Vben Admin V5

### Description

更多echarts示例, 有个数据大屏页面就好了

### Proposed Solution

有个酷炫的数据大屏页面就好了

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by vince292007** [comment]
暂时没有计划
