### ISSUE TITLE
Docs: 能否在文档中增加新建项目的指南？

### ISSUE THREAD

**Issue by qianhao100083** [vbenjs/vue-vben-admin#4336]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [X] Confusing
- [ ] Not sure?

### Explain in Detail

作为vue-vben-admin的初学者，我如果想要新建一个自己的项目，应该怎么做？是在apps目录中新建一个目录，然后根据自己想要使用的组件类型，从web-antd/web-ele/web-naive中拷贝需要的配置和代码，还是在这三个目录上修改。
根据文档的“基础概念”和“本地开发”等章节的描述，我的理解是，基于Monorepo的理念，应该新建一个目录。
那么，带来两个问题：
1、需要拷贝哪些配置文件和代码？
2、需要怎样build这个新项目？
我正在阅读样板应用的代码，摸索与尝试中。

### Your Suggestion for Changes

建议文档中增加相应的章节，描述怎样创建一个新项目，怎样建立项目框架，怎样调试。
最好位于“本地开发”和“路由和菜单”之间。
作为一个初学者，感谢作者的分享精神。
不揣冒昧的提出以上建议，希望能有所助益。

**Comment by M69W** [comment]
https://doc.vben.pro/guide/introduction/thin.html
