### ISSUE TITLE
Docs: 如何定制一个左侧的一级的菜单？

### ISSUE THREAD

**Issue by aaronchen2k** [vbenjs/vue-vben-admin#4342]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [ ] Confusing
- [X] Not sure?

### Explain in Detail

如何定制一个左侧的一级的菜单？依然使用BasicLayout

### Your Suggestion for Changes

给出一个例子

**Comment by vince292007** [comment]
见：https://doc.vben.pro/guide/essentials/route.html#hidechildreninmenu
