### ISSUE TITLE
FEATURE: 请优先开发table，毕竟这个才是用的最多的！感谢

### ISSUE THREAD

**Issue by zhengyuanchao-xinye** [vbenjs/vue-vben-admin#4343]
### Version

Vben Admin V5

### Description

rt,强烈感谢和支持各位

### Proposed Solution

rt,强烈感谢和支持各位

### Alternatives Considered

rt,强烈感谢和支持各位

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by likui628** [comment]
table依赖form，所以先做的form

**Comment by zhangjiayu139** [comment]
> table依赖form，所以先做的form
form也用vxe?
