### ISSUE TITLE
Bug: vben Admin官网示例 顶部菜单混合模式下开启分割菜单。在切换回左侧菜单模式，左侧菜单不能正常显示回之前的状态

### ISSUE THREAD

**Issue by meishaonian123** [vbenjs/vue-vben-admin#4344]
### Version

Vben Admin V2

### Describe the bug?

![image](https://github.com/user-attachments/assets/5d4643cb-0755-46b3-80bc-68bf8d08e9c4)

![image](https://github.com/user-attachments/assets/39b807a0-b9eb-46d8-ad86-f12960e77d9c)

### Reproduction

官网示例：https://v2.vben.pro/#/comp/form/basic

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 113.44 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.1 - ~/.nvm/versions/node/v16.14.1/bin/node
    npm: 6.14.18 - ~/.nvm/versions/node/v16.14.1/bin/npm
  Browsers:
    Chrome: 128.0.6613.120
    Edge: 128.0.2739.67
    Safari: 16.5.2
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by meishaonian123** [comment]
修改部分代码后分割菜单功能正常，但不知道之前的处理逻辑为什么要加上限制
![image](https://github.com/user-attachments/assets/6b0f16d4-5455-4f5a-9f50-c9e327f7eee7)

**Comment by anncwb** [comment]
v2版本这种bug不会去修复了，可以帮忙排查并提PR
