### ISSUE TITLE
FEATURE: 为开发提供更多可选择的版本

### ISSUE THREAD

**Issue by Suomm** [vbenjs/vue-vben-admin#4345]
### Version

Vben Admin V5

### Description

使用发行版时需要根据项目进行大量的更改，可否提供一个精简版 `thin` 去掉演示界面，仅保留框架部分；还有对于 `i18n` 也可以作为一个可选择的项目，而不是必选项。

### Proposed Solution

提供一个精简版，一个无国际化版。

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by likui628** [comment]
目前去掉演示界面只要自己删掉几个目录就行了。
i18n不需要的话，需要自己去处理。

精力有限，应该不会提供
