### ISSUE TITLE
Bug: 登录接口报ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by p-m-q** [vbenjs/vue-vben-admin#4346]
### Version

Vben Admin V5

### Describe the bug?

在官方antd demo中，用户进行登录时，调用登录接口报错：
[Error Handler] Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\workspace\vscode\vue-vben-admin\node_modules\.pnpm\std-env@3.7.0\node_modules\std-env\dist\index.mjs' imported from D:\workspace\vscode\vue-vben-admin\apps\backend-mock\.nitro\dev\index.mjs
    at finalizeResolution (node:internal/modules/esm/resolve:265:11)
    at moduleResolve (node:internal/modules/esm/resolve:933:10)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36)

### Reproduction

无

### System Info

```shell
Windows11, node v20.12.1, pnpm v9.9.0 google浏览器，源码是最新版本vben-admin-pro@5.2.2
```

### Relevant log output

```shell
无
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by likui628** [comment]
你执行什么命令启动的antd demo

**Comment by p-m-q** [comment]
pnpm run dev:antd

**Comment by p-m-q** [comment]
std-env这个模块其实有的，通过pnpm info std-env  可以看到对应的包信息的

**Comment by p-m-q** [comment]
> 你执行什么命令启动的antd demo
pnpm run dev:antd
std-env这个模块其实有的，通过pnpm info std-env 可以看到对应的包信息的

**Comment by likui628** [comment]
要不然你调用下 `pnpm run reinstall` 然后再试一下

**Comment by wangz-code** [comment]
第一次安装完毕之后  貌似需要先在根目录执行 ``` pnpm run build  ```  完毕之后 在运行项目  不然打包的时候回报错

**Comment by p-m-q** [comment]
> 要不然你调用下 `pnpm run reinstall` 然后再试一下

我还是重新搞了个项目再安装，才好使了。reinstall会报错

**Comment by p-m-q** [comment]
> 第一次安装完毕之后 貌似需要先在根目录执行 `pnpm run build ` 完毕之后 在运行项目 不然打包的时候回报错

我还没走到build哪一步，才开始研究这个框架，谢谢你的提醒

**Comment by meishaonian123** [comment]
有没有遇到按照文档步骤启动@vben/web-antd 项目时报错Unable to find an available port (tried 5320 on host "localhost")，但实际5320端口并未被占用
![image](https://github.com/user-attachments/assets/6b4d133d-808f-47b2-a479-e595dc4c6532)
