### ISSUE TITLE
FEATURE: 5.0里面一些基础组件都没有吗

### ISSUE THREAD

**Issue by CurryHan** [vbenjs/vue-vben-admin#4349]
### Version

Vben Admin V5

### Description

5.0里面一些基础组件都没有吗

### Proposed Solution

5.0里面一些基础组件都没有吗

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by anncwb** [comment]
可以看看文档
