### ISSUE TITLE
Bug: 针对 Vben5框架里KeepAlive 未生效的问题

### ISSUE THREAD

**Issue by renyi818** [vbenjs/vue-vben-admin#4350]
### Version

Vben Admin V5

### Describe the bug?

vben5框架中的tab页签,有看到使用keepalive,但是实际上未生效, 请问是需要如何特殊配置吗?

### Reproduction

打开示例项目中的“剪贴板”菜单, 在文本框中输入任何文字,切换tab页签后返回页面, 文本框中的文字会发现清除了.

### System Info

```shell
Mac
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
要启用页面的KeepAlive，需要在路由的meta中配置keepAlive: true。
参考文档：https://doc.vben.pro/guide/essentials/route.html#keepalive
