### ISSUE TITLE
Bug: 苹果电脑上，运行mock项目服务时报错：get-port] Unable to find an available port (tried 5320 on host "localhost").但5320端口实际并未占用

### ISSUE THREAD

**Issue by meishaonian123** [vbenjs/vue-vben-admin#4360]
### Version

Vben Admin V5

### Describe the bug?

Bug: 苹果电脑上，运行mock项目服务时报错：get-port] Unable to find an available port (tried 5320 on host "localhost").
![image](https://github.com/user-attachments/assets/4cc480b7-4794-472a-af6f-e2f982bb7597)

### Reproduction

Bug: 苹果电脑上，运行mock项目服务时报错：get-port] Unable to find an available port (tried 5320 on host "localhost").
![image](https://github.com/user-attachments/assets/4cc480b7-4794-472a-af6f-e2f982bb7597)

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 158.34 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.16.0 - /usr/local/bin/node
    npm: 10.8.1 - /usr/local/bin/npm
    pnpm: 9.7.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.121
    Edge: 128.0.2739.67
    Safari: 16.5.2
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
运行其他web-app会自动运行mock服务，你可能已经运行一个了，或者没彻底关掉导致的
