### ISSUE TITLE
Bug: Form组件显示不全，移动端样式优化

### ISSUE THREAD

**Issue by meimosor** [vbenjs/vue-vben-admin#4366]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/d900d3b1-8997-446e-902d-f0918c8e33d5)
Form组件显示不全，移动端样式优化

### Reproduction

1. 进入https://www.vben.pro/#/examples/form/custom
2. 切换移动端视图调试页面

### System Info

```shell
edge浏览器
win11
vben5.3.3
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aonoa** [comment]
![image](https://github.com/user-attachments/assets/072d17dc-47a5-414f-b8b6-fc19a264c058)

**Comment by anncwb** [comment]
labelClass设置 tailwindcss 响应式能缓解
