### ISSUE TITLE
FEATURE:  建议V5版本国际化文件能支持V2那种多目录、多文件格式的， 这样开发的时候方便管理语言文件

### ISSUE THREAD

**Issue by Ghaitao** [vbenjs/vue-vben-admin#4374]
### Version

Vben Admin V5

### Description

![image](https://github.com/user-attachments/assets/09240b7d-1f1d-42a8-8edc-dc7dae35705c)
![image](https://github.com/user-attachments/assets/91829b53-db21-4fae-bc37-44ebfe8011cc)

### Proposed Solution

**国际化支持多目录，多文件结构，开发时方便管理语言文件**

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by anncwb** [comment]
close 0df8c5c02cbd15a7733f0426af6a9901325aed53
