### ISSUE TITLE
Bug: modal弹窗组件中二级表单控件无法获取焦点

### ISSUE THREAD

**Issue by Zhao-sj** [vbenjs/vue-vben-admin#4376]
### Version

Vben Admin V5

### Describe the bug?

在modal中使用element-plus的DateTimePicker组件弹出的pop中的输入框无法获取焦点进行输入

### Reproduction

![image](https://github.com/user-attachments/assets/bc92ca7e-1d68-4a22-bda2-9e3934c1cd63)

### System Info

```shell
System:
    OS: Windows 11 22631.3880
    CPU: 13th Gen Intel(R) Core(TM) i9-13900H   2.60 GHz
    Memory: 21.3 GB / 32.0 GB
  Binaries:
    Node: 20.16.0 - D:\Application\nodejs\node.exe
    npm: 10.8.1 - D:\Application\nodejs\npm.cmd
    pnpm: 9.6.0 - D:\Application\nodejs\pnpm.cmd
  Browsers:
    Chrome: 127.0.6533.120
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
昨天应该修复了，你有更新最新代码？

**Comment by Zhao-sj** [comment]
是拉取的最新代码，上次修复的是modal中表单组件的pop无法被选中，这次是在pop中的输入控件无法被聚焦输入

**Comment by Zhao-sj** [comment]
问题出现是在更新了useForm之后出现的，之前使用modal都没有这些问题

**Comment by anncwb** [comment]
可以在尝试看看，修复了一个版本
