### ISSUE TITLE
Bug: build构建后的包，在electron中使用loadFile('index.html')引入报ndex-index-DxNHy.mjs路径找不到，求解决，项目已使用5.2.2开发起来了

### ISSUE THREAD

**Issue by fkuepl** [vbenjs/vue-vben-admin#4378]
### Version

Vben Admin V5

### Describe the bug?

Bug: build构建后的包，在electron中使用loadFile('index.html')引入报ndex-index-DxNHy.mjs路径找不到，求解决，项目已使用5.2.2开发起来了

### Reproduction

Bug: build构建后的包，在electron中使用loadFile('index.html')引入报ndex-index-DxNHy.mjs路径找不到，求解决，项目已使用5.2.2开发起来了

### System Info

```shell
Bug: build构建后的包，在electron中使用loadFile('index.html')引入报ndex-index-DxNHy.mjs路径找不到，求解决，项目已使用5.2.2开发起来了
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fkuepl** [comment]
![1](https://github.com/user-attachments/assets/1b4e2526-6f10-4d83-8849-c2b812439aea)
![2](https://github.com/user-attachments/assets/ff1df640-ec38-48bb-bb83-53a6a8f8610f)
![3](https://github.com/user-attachments/assets/351fc52f-d9d0-417d-adb1-4221d937db14)
主要是图片三处的地址有误，需要怎么在vben5中怎么设置

**Comment by fkuepl** [comment]
如果VBEN5中设置不了，是否可以在index.html中接收一个有electron中传输过去的electron的目录地址，自动拼接到上面的JS和CSS文件前？

**Comment by anncwb** [comment]
目前没支持electron，需要自己去改造。

**Comment by lztbwlkj** [comment]
可尝试注释掉internal＞vite-config＞application.ts文件的rollupOptions＞output＞entryFileNames

**Comment by anncwb** [comment]
应该改下base就可以了吧

**Comment by anncwb** [comment]
.env文件内的  `VITE_BASE` 调试下

**Comment by fkuepl** [comment]
> 应该改下base就可以了吧

目前项目构建出来的路径是相对路径，但在electron中好像要用绝对路径才能读的到相应的文件；不同的用户又会将electron的运行包放在不同的目录中，绝对路径就不能写死；base不知道要怎么指定路径才行

**Comment by fkuepl** [comment]
目前我是在electron中获取了用户运行electron的路径，再传输入到index.hml中，在将这个变量的路径拼接到了上面三张图的每个文件前面，项目是可以运行起来了，就是每次打包都要改一下上面的三张图，有点费劲

**Comment by fkuepl** [comment]
> > 目前我是在electron中获取了用户运行electron的路径，再传输入到index.hml中，在将这个变量的路径拼接到了上面三张图的每个文件前面，项目是可以运行起来了，就是每次打包都要改一下上面的三张图，有点费劲
> 
> 请问修改后能完美运行吗？我们也需要集成到Electron，心里有点没底。

只要改路径几个引用文件的路径就能能完美运行的

**Comment by PeiHaigang** [comment]
> > > 目前我是在electron中获取了用户运行electron的路径，再传输入到index.hml中，在将这个变量的路径拼接到了上面三张图的每个文件前面，项目是可以运行起来了，就是每次打包都要改一下上面的三张图，有点费劲
> > 
> > 
> > 请问修改后能完美运行吗？我们也需要集成到Electron，心里有点没底。
> 
> 只要改路径几个引用文件的路径就能能完美运行的

好的，谢谢，那也问题不大，每次打包手动改下。我到时候也研究下配置，看看有没有办法不拼接路径
