### ISSUE TITLE
Bug: 移动端示例-查询表单展开/收起功能失效

### ISSUE THREAD

**Issue by Frosty-Lunar** [vbenjs/vue-vben-admin#4380]
### Version

Vben Admin V5

### Describe the bug?

在手机上浏览 https://www.vben.pro/#/examples/form/query 查看示例（查询表单）
其中展开/收起功能有问题
在PC端则不影响

![微信图片_20240912222948](https://github.com/user-attachments/assets/31f8fbaa-968c-4ab8-bffe-34013846fd94)

### Reproduction

无

### System Info

```shell
6.7英寸手机
```

### Relevant log output

```shell
null
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
这个提交已经修复了 76a879d4d8e86325a933adc00d776070272fe462
