### ISSUE TITLE
FEATURE: 

### ISSUE THREAD

**Issue by ckbabby** [vbenjs/vue-vben-admin#4387]
### Version

Vben Admin V5

### Description

你好，我想类似你那种方式打包自己的组件到packages 目录下，想问下 unbuild 如何打包scss 和less ，目前我升级unbuild 到3.0 版本后 是支持文件复制的，不知道有么有更好的方法可以打包到scss 和less
![图片](https://github.com/user-attachments/assets/ce7ebdec-2cc1-418a-bd0b-66e49ecc50f9)

### Proposed Solution

无法打包scss 和less

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by vince292007** [comment]
loaders改成 `loaders:['sass']`就可以了。

**Comment by ckbabby** [comment]
你好，感谢你的解答，测试过已经可以了，十分感谢了

**Comment by ckbabby** [comment]
这种方式还是不行，因为导出的文件引用的是scss 的，找过unbuild 文档没看到相关说明，估计要自己实现，但是我发现@core/base/design 有类似的功能，参考那个配置文件就可以打包成一个可用的组件库
