### ISSUE TITLE
Bug: 预览网站无法登录

### ISSUE THREAD

**Issue by Simple-Stark** [vbenjs/vue-vben-admin#4397]
### Version

Vben Admin V2

### Describe the bug?

![image](https://github.com/user-attachments/assets/be31bc6b-56a1-4522-b84f-2b3c3526f68a)
![image](https://github.com/user-attachments/assets/b323603f-7b03-4709-b9e5-ba62644fe7c5)

### Reproduction

预览网站无法登录

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-1340P
    Memory: 476.01 MB / 15.73 GB
  Binaries:
    Node: 20.15.0 - D:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - D:\Program Files\nodejs\npm.CMD
    pnpm: 9.7.1 - ~\node_modules\.bin\pnpm.CMD
  Browsers:
    Chrome: bookmarks.html
initial_preferences
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
缓存清理下应该就可以了
