### ISSUE TITLE
Docs: 使用Icon组件加载iconify图标时，有的图标可以离线加载，有的需要进行网络请求，可离线加载的图标有哪些，在哪查找

### ISSUE THREAD

**Issue by liushaofenggithub** [vbenjs/vue-vben-admin#4408]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [ ] Confusing
- [X] Not sure?

### Explain in Detail

使用Icon组件加载iconify图标时，有的图标可以离线加载，有的需要进行网络请求，可离线加载的图标有哪些，在哪查找

### Your Suggestion for Changes

使用Icon组件加载iconify图标时，有的图标可以离线加载，有的需要进行网络请求，可离线加载的图标有哪些，在哪查找

### Steps to reproduce

使用Icon组件加载iconify图标时，有的图标可以离线加载，有的需要进行网络请求，可离线加载的图标有哪些，在哪查找

**Comment by likui628** [comment]
![image](https://github.com/user-attachments/assets/d3ee59d9-22d1-44bb-aa6c-22ac29156e1f)

**Comment by liushaofenggithub** [comment]
![截屏2024-09-18 09 13 13](https://github.com/user-attachments/assets/713b651b-ab33-4793-838a-14fb2176227b)


1、请问你是哪个版本的，我这个版本(2.11.4)不存在上面截图的文件夹
2、举个例子，加载bx:bx-home图标可以离线加载，加载bx图标库的其他图标就需要进行网络请求，当前开发环境是内网

**Comment by likui628** [comment]
我说的是v5
