### ISSUE TITLE
Bug: pnpm build 打包失败

### ISSUE THREAD

**Issue by cng1985** [vbenjs/vue-vben-admin#4424]
### Version

Vben Admin V5

### Describe the bug?

 Tasks:    2 successful, 4 total
Cached:    2 cached, 4 total
  Time:    4.198s
Failed:    @vben-core/design#build

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

### Reproduction

 Tasks:    2 successful, 4 total
Cached:    2 cached, 4 total
  Time:    4.198s
Failed:    @vben-core/design#build

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 17.14 GB / 31.91 GB
  Binaries:
    Node: 21.0.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.10.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: 127.0.6533.89
    Edge: Chromium (113.0.1774.50)
    Internet Explorer: 11.0.19041.4355
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jinmao88** [comment]
怎么build的
