### ISSUE TITLE
Bug: 我使用的是后端路由，但登录进去后发现没有菜单栏

### ISSUE THREAD

**Issue by DB-lost** [vbenjs/vue-vben-admin#4427]
### Version

Vben Admin V5

### Describe the bug?

我选择的是默认的布局，同时页面上也没有看到右边的设置按钮，我是从旧的vben转向5.0版本的，现在发现这个问题，请问有人同我一样么，亦或者是不是我哪里少配置与配置失败了。
![image](https://github.com/user-attachments/assets/9a47259c-132d-4701-96c2-024394ecc6bf)
![image](https://github.com/user-attachments/assets/e4335baf-6e3b-48ac-90cb-eee3ed0cd929)
控制台也没有报错
![image](https://github.com/user-attachments/assets/efebbaae-07f8-4317-a1db-4a40fe84a62e)

### System Info

```


### Relevant log output

_No response_

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DB-lost** [comment]
![image](https://github.com/user-attachments/assets/79861bb0-6bd9-42a4-bcb8-bed7ceb40d4f)
再补充一张浏览器的图片，我是从后端获取路由的，没有发现报错，但菜单栏依旧不显示

**Comment by Ghaitao** [comment]
目录的时候，component应该是 BasicLayout

**Comment by Ghaitao** [comment]
![Uploading image.png…]()
看你配置的layoutMap，我看现在默认的是BasicLayout

**Comment by DB-lost** [comment]
ok，问题解决了，确实是这个原因
