### ISSUE TITLE
FEATURE: 点击目录自动跳转第一项子菜单

### ISSUE THREAD

**Issue by JaneYork** [vbenjs/vue-vben-admin#4430]
### Version

Vben Admin V5

### Description

增加开关：点击目录自动跳转第一项最深层子菜单，直接跳转并激活该菜单，无需一层一层选择

### Proposed Solution

<img width="1468" alt="image" src="https://github.com/user-attachments/assets/f380e37f-fc40-4861-93e9-480b3fc417c3">

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by aitrx** [comment]
+1
