### ISSUE TITLE
Bug: 后端返回401状态无法返回登录

### ISSUE THREAD

**Issue by fatetianchen** [vbenjs/vue-vben-admin#4431]
### Version

Vben Admin V5

### Describe the bug?

1、后端用的同一个方法返回数据以及报错信息，经过测试只有401状态码无法获取response信息，导致前端无法进入指定的代码块进行判断。
2、401报错后因没有response所有无法获取具体报错信息，而且前端必须刷新网页才能跳转登录页，请大佬仔细排查，尽快修复。
<img width="1143" alt="401" src="https://github.com/user-attachments/assets/5802f9a8-21f3-4d94-9e81-780929857a8d">
<img width="834" alt="405" src="https://github.com/user-attachments/assets/53d3e165-8a83-4a98-9fd9-87b32c88acda">

### Reproduction

前端登录后-手动删除线上Redis里的token信息 -返回前端页面刷新

### System Info

```shell
无
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
我尝试了下，未能复现。这里应该是http状态码status=401，不是code=401
