### ISSUE TITLE
Docs: 什么时候可以提供Table组件呢

### ISSUE THREAD

**Issue by lztbwlkj** [vbenjs/vue-vben-admin#4441]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [ ] Confusing
- [X] Not sure?

### Explain in Detail

目前V5的版本没有看到Table组件，Table这个组件几乎每个页面都能使用到，什么时候可以提供呢？坐等～～### ### 

### Your Suggestion for Changes

目前V5的版本没有看到Table组件，Table这个组件几乎每个页面都能使用到，什么时候可以提供呢？坐等～～### ###

**Comment by vince292007** [comment]
应该10月初，国庆期间

**Comment by sunnyboyi** [comment]
+1

**Comment by PeiHaigang** [comment]
+1

**Comment by xingxiuyi** [comment]
The developers worked very hard and the progress was very fast, great.

**Comment by du6688** [comment]
+1

**Comment by anncwb** [comment]
close 417326480579765bbea54d280e95db7250049c18
