### ISSUE TITLE
Bug: V2版本，自动锁屏输入9999999无法解锁

### ISSUE THREAD

**Issue by JaneYork** [vbenjs/vue-vben-admin#4445]
### Version

Vben Admin V2

### Describe the bug?

没点击锁屏，没设置密码，当自动锁屏直接输入999999然后自动就锁住了，且再次登录还是锁住，清理浏览器缓存无效

### Reproduction

<img width="352" alt="image" src="https://github.com/user-attachments/assets/80fbffdc-29de-4772-b66d-d6220d47dd64">

### System Info

```shell
chrome
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Cekun** [comment]
v2版本你是怎么加后端代理的啊
