### ISSUE TITLE
Docs: 表单能否开放一个直接修改某个表单字段的所有属性功能？

### ISSUE THREAD

**Issue by LGX93** [vbenjs/vue-vben-admin#4447]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in Detail

例如根据表单的变化来改变 label的值，还有初始化远程获取列表赋值到Cascader 的options，都不会自动变化，目前只能用formApi.setState()来改变，感觉有些繁琐，如果能直接修改某字段下的其他属性就好了。
![微信截图_20240920124911](https://github.com/user-attachments/assets/4dba3805-a88f-46d3-8a64-c885d6081913)

### Your Suggestion for Changes

希望能开放一个接口，修改字段下的所有属性。

**Comment by finalreturn** [comment]
show是否也考虑增加，初始时希望有表单值，但不显示。目前只能通过dependencies设置

**Comment by anncwb** [comment]
直接 dependencies show设置true就可以了
