### ISSUE TITLE
Bug: 点击面包屑第一个节点或者点击面包屑主页图标会出现标签页的标签消失

### ISSUE THREAD

**Issue by cbombonera** [vbenjs/vue-vben-admin#4462]
### Version

Vben Admin V5

### Describe the bug?

你好，很喜欢vben系统
我发现系统点击**面包屑** 当第一个节点可以跳转的时候，然后再点击**其他菜单节点**可能会出现**标签页上的所有标签消失**
或者偏好=》布局=》面包屑导航 设置显示首页图标，点击面包屑首页图标的情况下，也会导致**标签页上的所有标签消失**

![image](https://github.com/user-attachments/assets/2828a038-872b-426c-858b-7f2f044de43f)

### Reproduction

地址 https://www.vben.pro/#/analytics

### System Info

```shell
window 11  谷歌浏览器 edg浏览器 360浏览器都会出现
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aonoa** [comment]
我试了一下没有复现

**Comment by catalpaUI** [comment]
> 我试了一下没有复现

是的，我今天看确实没有了

**Comment by catalpaUI** [comment]
> 我试了一下没有复现

看了下作者今天提交记录，好像没做处理
但是我觉得这个问题可能是存在的
也许并不是直接按我操作这样就能复现如图所述
因为在发现这个问题前，我在官网这个系统里面点了很多东西，尤其是看滚动条等等

**Comment by catalpaUI** [comment]
> 我试了一下没有复现

点了一会儿，应该是好了，这个可以关闭了。谢谢

**Comment by catalpaUI** [comment]
> 我试了一下没有复现

问题我复现了，用两个浏览器 谷歌和edg
跟主页图标应该没有关系 一下是我复现的过程

 ### 第一种场景复现流程
比如选项卡主题 谷歌风格
1.点击**【菜单】**  演示=》前端权限=》按钮控制
2.**【偏好】** =》选项卡主题 设置成 朴素（或者其他非谷歌风格）
3.点击 ** 面包屑 ** 上的演示节点
4.再点击** 【菜单】**  演示=》前端权限=》按钮控制
 然后就会出现该问题 标签页标签消失


### **第二种场景复现流程**
比如选项卡主题 谷歌风格
1.点击**菜单**  演示=》前端权限=》按钮控制
2.点击 **面包屑** 上的演示节点
3.偏好=》选项卡主题 设置成 朴素（或者其他非谷歌风格）
 然后就会出现该问题 标签页标签消失

* 如果没出现可以继续点两下菜单


### 另外我还注意到一个问题 或者建议

就是比如 我先 点了某某**菜单**， 标签页XX菜单 选中，然后点面包屑 主页图 或者其他节点，页面跳转到主页或者其他页面，但是标签页的选中还是之前的xx菜单选中 也许这不是bug，只是个人觉得有点不合理的建议


![image](https://github.com/user-attachments/assets/d85839f7-495d-4527-be2c-718c75e40a8b)
![image](https://github.com/user-attachments/assets/2680affa-4552-4f34-a65d-888fd431df92)
![image](https://github.com/user-attachments/assets/5c6e632d-e058-4717-b80c-9970bafb6d80)

**Comment by anncwb** [comment]
这个问题应该已经修复了，复现了几次均为出现。
