### ISSUE TITLE
FEATURE: 抽屉能否支持在主体main区域弹出，样式等等

### ISSUE THREAD

**Issue by cbombonera** [vbenjs/vue-vben-admin#4463]
### Version

Vben Admin V5

### Description

vben的系统做的很好
看作者在做演示的功能，只是个人一些小建议
1.底层的的公共组件抽屉 能否支持在main主体内弹出，因为我发现我这边遇到客户不少场景就是喜欢用抽屉，并且提出在主体区域内弹出 并铺满，类似当作了当前页面跳转新的页面差不多的效果！
2.底层的公共组件模态框 能否支持伸缩大小功能
3.看作者最近在写验证码 能否支持 加减乘除 滑块验证
4.对前端样式不熟悉，作者能不能提供一个自适应高度的合理示例，因为我遇到很多场景是 main下面的表格是自适应高度的，作者main用到flex 1 1 % 子级div用高度百分百是做不到 和可视区域高度一致的，我能想到的是用css 是子级div  设置 position: absolute 然后高度百分百，但是感觉不合理，毕竟我的水平不够！也就是想有一个页面示例 比如展示表格屏幕main区域整个高度， body不会显示滚动条的，只有表格有滚动条，自适应高度这种。

### Proposed Solution

没有，如描述，只是个人觉得有的场景可能需要，而且可能在客户面前，这种场景用到的还比较多

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by ArthurDarkstone** [comment]
2.底层的公共组件模态框 能否支持伸缩大小功能 [https://github.com/vbenjs/vue-vben-admin/pull/4862](https://github.com/vbenjs/vue-vben-admin/pull/4862)

**Comment by mynetfan** [comment]
1、抽屉和弹窗已经支持在内容区域挂载；
2、模态窗可使用class支持随浏览器窗口缩放；
3、验证码只是个演示，大概率不会再深入拓展更多的类型；
4、目前已可设置内容区域高度自适应。这个方案可能会在后续继续优化改进
