### ISSUE TITLE
FEATURE: 关于公共组件dropdown能否则支持鼠标滑动

### ISSUE THREAD

**Issue by catalpaUI** [vbenjs/vue-vben-admin#4465]
### Version

Vben Admin V5

### Description

本人对前端不是很熟悉，主要是做后台的
主要用的前端ui 也就bootstrap element plus
看vben新版本用了分层，我觉得特别棒
我这边打算在main区域里面的功能开发用elemnt plus
但是发现头部的公共组件 dropdown 不能滑动弹出 而且强制改成ep ui 或者重写 好像很不合理
但是对shadcn 这种实在是不会，所以看作者这边能否支持滑动 
其实我在开发的场景中 除了main区域内，外部用到鼠标滑动的就是头像 嘿嘿

### Proposed Solution

shadcn  dropdown支持鼠标滑动

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by mynetfan** [comment]
修改这个文件
`packages/effects/layouts/src/widgets/user-dropdown/user-dropdown.vue`
在script段插入一行：``` const menuOpen = ref(false); ```
template段第158行改为``` <DropdownMenu v-model:open="menuOpen"> ```
第160行的div中插入``` @mouseenter="menuOpen = true" ```
大概如下：
```
...
const menuOpen = ref(false);
</script>

<template>
...
  <DropdownMenu v-model:open="menuOpen">
    <DropdownMenuTrigger>
      <div class="hover:bg-accent ml-1 mr-2 cursor-pointer rounded-full p-1.5" @mouseenter="menuOpen = true">
```

**Comment by catalpaUI** [comment]
> 修改这个文件 `packages/effects/layouts/src/widgets/user-dropdown/user-dropdown.vue` 在script段插入一行：`const menuOpen = ref(false);` template段第158行改为`<DropdownMenu v-model:open="menuOpen">` 第160行的div中插入`@mouseenter="menuOpen = true"` 大概如下：
> 
> ```
> ...
> const menuOpen = ref(false);
> </script>
> 
> <template>
> ...
>   <DropdownMenu v-model:open="menuOpen">
>     <DropdownMenuTrigger>
>       <div class="hover:bg-accent ml-1 mr-2 cursor-pointer rounded-full p-1.5" @mouseenter="menuOpen = true">
> ```

谢谢
