### ISSUE TITLE
FEATURE: 偏好能不能后续推出LOGO置于头部的功能等

### ISSUE THREAD

**Issue by cbombonera** [vbenjs/vue-vben-admin#4469]
### Version

Vben Admin V5

### Description

真的非常喜欢vben的偏好也就是以前的主题设置
基本上能想到的都包含了，功能非常齐全
只是个人可能面对客户比较多，看看作者这边后续能不能有几点有关偏好的功能
当然我的建议其实对于开发使用者 使用vben的情况下， 然后自定义改造并不困难，但我觉得这些出自于底层，然后使用者直接做业务可能更优

1.布局设置的时候，LOGO能否置于头部，我看LOGO是跟随侧边栏的宽度，但是现实就是有很多客户要求Logo偏长或者偏短，也就是Logo在头部（主侧边栏模式）
2.侧边栏 头部背景颜色能否自定义颜色或者跟随主色
3.菜单图标使用非彩色图片  icon svg 这类的图标 能否底层自带 彩色属性 或者 自动彩色图标功能（比如第一个图标自动蓝色，第二个黄色 这种随机或者有序的）（主要是侧边栏）
4.支持混合模式并且同时双排
5.支持混合模式或者双排的菜单项 事件 多种类型 路由|click|hover
6.侧栏能否有这样一种模式 主 效果是 （偏好设置的效果）折叠菜单并且显示菜单名称 点击折叠就是折叠菜单只显示图标，不会有自适应等情况出现展开效果的菜单，其实这种模式在我面对的客户用的非常多，类似禅道demo官网的侧栏效果，当然我个人觉得我们vben的 【折叠菜单并且显示菜单名称】 也就是文本在下面 更nice

仅仅是个人建议
——————另外以下可能是疑惑
a.对于定宽 这个我不是很理解，侧边栏设置定宽 好像没有底部滚动条
水平菜单的时候，好像有效果
b.锁屏 是不是暂时未开发或者只是个示例 好像没什么作用，点击遮照 就会关闭dialog

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by anncwb** [comment]
这些功能目前都有，多点点设置就行
