### ISSUE TITLE
FEATURE: 新版本的语言能做成多文件形式吗

### ISSUE THREAD

**Issue by catalpaUI** [vbenjs/vue-vben-admin#4473]
### Version

Vben Admin V5

### Description

项目开发 主要是团队，基本场景应该是分层的
如果一种语言 都写在一个文件里，对于多人 尤其大团队，是否难于管理了

### Proposed Solution

语言设置文件夹，读取多文件

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by vince292007** [comment]
duplicate #4374
