### ISSUE TITLE
FEATURE: 标签页能否支持鼠标滚动

### ISSUE THREAD

**Issue by cbombonera** [vbenjs/vue-vben-admin#4474]
### Version

Vben Admin V5

### Description

仅仅是建议
我没有关心这一块，也没有注意到
是近期我有个同学(非IT)，想给他的小公司搞个录入系统，就是简单的三个增删改查的模块
但是他要求了页面
并给我看了他们行业的一个系统，我进去一看，就是以前很火的框架，用layui搭建的
然后我推荐了用vben 尤其5 画面够好看，技术又新
他研究几天给我反馈说 这确实好
但是标签页不能滚动，然后还是我教他 点旁边的箭头按钮
我一直劝说滚动没什么用，也不知道为什么他说对员工很有用 可能也是强迫症吧

只是建议 我觉得有可能更好，没有也挺好的

### Proposed Solution

标签页触发鼠标滚动事件 滚动分页或者滚动

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by jinmao88** [comment]
是滚轮切换tabs 还是 tabs多了以后滚动？

**Comment by catalpaUI** [comment]
> 是滚轮切换tabs 还是 tabs多了以后滚动？
tabs多了以后，现在是点击前后图标 进行查看
想支持 滚轮 进行下一页查看 或者能滚动tabs类似滚动条效果也行

**Comment by catalpaUI** [comment]
> tabs多了以后，现在是点击前后图标 进行查看
> 想支持 滚轮 进行下一页查看 或者能滚动tabs类似滚动条效果也行

tabs多了以后，现在是点击前后图标 进行查看
想支持 滚轮 进行下一页查看 或者能滚动tabs类似滚动条效果也行

**Comment by yuanhongyu123** [comment]
> > 是滚轮切换tabs 还是 tabs多了以后滚动？
> > tabs多了以后，现在是点击前后图标 进行查看
> > 想支持 滚轮 进行下一页查看 或者能滚动tabs类似滚动条效果也行

https://github.com/zclzone/qs-admin/blob/main/src/components/common/ScrollX.vue
这个库有实现，是不是可以集成进来

**Comment by catalpaUI** [comment]
> > > 是滚轮切换tabs 还是 tabs多了以后滚动？
> > > tabs多了以后，现在是点击前后图标 进行查看
> > > 想支持 滚轮 进行下一页查看 或者能滚动tabs类似滚动条效果也行
> 
> https://github.com/zclzone/qs-admin/blob/main/src/components/common/ScrollX.vue 这个库有实现，是不是可以集成进来

可以啊，实现滚轮很多方法都可以
只是我觉得作者这边如果实现比较优

**Comment by programmer-fly** [comment]
浏览器自带的就是支持滚动的，试试按住shift键再滚动鼠标滚轮~
