### ISSUE TITLE
Bug: 使用auto-import插件导入api后 eslint报错

### ISSUE THREAD

**Issue by linsxw** [vbenjs/vue-vben-admin#4478]
### Version

Vben Admin V5

### Describe the bug?

安装了unplugin-auto-import插件后，在.vue文件中使用ref、computed等 不进行import 就会报错ESLint: 'ref' is not defined.(no-undef)
![image](https://github.com/user-attachments/assets/c292ba6d-8366-4449-9e78-c754dc676417)

这是我的自动导入配置
![image](https://github.com/user-attachments/assets/f75d6844-599c-412b-b796-e8770c7ec269)

### Reproduction

无

### System Info

```shell
v5.3.0-beta.2
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
更新最新代码就行
