### ISSUE TITLE
vben5.3.0是否可以用继承的方式定义一个新组件

### ISSUE THREAD

**Issue by zzfcat** [vbenjs/vue-vben-admin#4479]
准备继承vben5.3里的组件WorkbenchQuickNav，建立一个新的组件，想添加点击事件，点击后进入下一级的页面，这个功能原WorkbenchQuickNav组件好像没有（？）
====================
定义文件 my_custom.vue:
```
<script setup lang="ts">
import { defineComponent } from 'vue';
import {
  WorkbenchQuickNav,
} from '@vben/common-ui';

// 使用 extends 继承 WorkbenchQuickNav
 defineComponent({
  name: 'MyWorkbenchQuickNav',
  extends: WorkbenchQuickNav
});
</script>
```
应用页面 index.vue:
```
<template>
  <div>1
  <MyWorkbenchQuickNav title="我的组件" :items="quickNavItems" class="mt-5 lg:mt-0"></MyWorkbenchQuickNav>
    2
  <WorkbenchQuickNav title="原来的组件" :items="quickNavItems"  class="mt-5 lg:mt-0"></WorkbenchQuickNav>
  3</div>
</template>
```
运行结果：
![image](https://github.com/user-attachments/assets/9664b90e-5eb4-4e91-b7af-0b16c0437f8b)

所以，是不支持组件继承，还是我写得有问题？谢谢。

**Comment by mynetfan** [comment]
vue的文档有说明：```extends 是为选项式 API 设计的，不会处理 setup() 钩子的合并```
https://cn.vuejs.org/api/options-composition.html#extends
如果一定要这么写，参考下面这样：
```
import WorkbenchQuickNav from './workbench-quick-nav.vue';
// 注意，这不是一个vue文件，是一个ts文件
export default {
  extends: WorkbenchQuickNav,
  mounted() {
    console.log('MyWorkbenchQuickNav mounted', this);
    // 在此处获取props、挂载事件监听器等
  },
  name: 'MyWorkbenchQuickNav',
  setup(props, ctx) {
    return { ...WorkbenchQuickNav.setup(props, ctx) };
  },
};
```

**Comment by zzfcat** [comment]
> vue的文档有说明：`extends 是为选项式 API 设计的，不会处理 setup() 钩子的合并` https://cn.vuejs.org/api/options-composition.html#extends 如果一定要这么写，参考下面这样：
> 
> ```
> import WorkbenchQuickNav from './workbench-quick-nav.vue';
> // 注意，这不是一个vue文件，是一个ts文件
> export default {
>   extends: WorkbenchQuickNav,
>   mounted() {
>     console.log('MyWorkbenchQuickNav mounted', this);
>     // 在此处获取props、挂载事件监听器等
>   },
>   name: 'MyWorkbenchQuickNav',
>   setup(props, ctx) {
>     return { ...WorkbenchQuickNav.setup(props, ctx) };
>   },
> };
> ```

果然可以, 非常感谢
