### ISSUE TITLE
Bug: 新下载的项目，打包不了

### ISSUE THREAD

**Issue by haoqing** [vbenjs/vue-vben-admin#4485]
### Version

Vben Admin V5

### Describe the bug?

打包时报错：
 Tasks:    0 successful, 4 total
Cached:    0 cached, 4 total
  Time:    5.347s
Failed:    @vben-core/icons#build

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

### Reproduction

1111

### System Info

```shell
1111
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by M69W** [comment]
1111

**Comment by YouAge** [comment]
这个问题咋解决
