### ISSUE TITLE
FEATURE: useForm配置组件参数响应式支持

### ISSUE THREAD

**Issue by Zhao-sj** [vbenjs/vue-vben-admin#4486]
### Version

Vben Admin V5

### Description

目前配置直接传入对象没有响应式，在组件参数使用computed传入正常运行，但是类型却没有支持
![image](https://github.com/user-attachments/assets/5bab350f-80d0-4ff8-90fc-bdbd06557ba4)

### Proposed Solution

目前配置直接传入对象没有响应式，在组件参数使用computed传入正常运行，但是类型却没有支持

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by Zhao-sj** [comment]
建议submitButtonOptions和resetButtonOptions提供按钮图标配置

**Comment by vince292007** [comment]
这个是预期的，不支持 use内只有schema支持响应式，其他参数从组件传吧

**Comment by Zhao-sj** [comment]
> 这个是预期的，不支持。use内只有schema支持响应式，其他参数从组件传吧

但是schema传入响应式没有类型支持

**Comment by vince292007** [comment]
参考登录界面
