### ISSUE TITLE
Bug: 使用 useVbenForm 时，schema 中的表单项如果不设置 rules 字段，即使输入了值也不会在提交时获取到该值

### ISSUE THREAD

**Issue by ChenWeihua123** [vbenjs/vue-vben-admin#4487]
### Version

Vben Admin V5

### Describe the bug?

使用 useVbenForm 时，schema 中的表单项如果不设置 rules 字段，即使输入了值也不会在提交时获取到该值

### Reproduction

官方仓库注册页随便删除一项中的 rules 即可复现

### System Info

```shell
windows11
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
`FormApi`的 `validate`返回的`values`就是校验成功的字段数据。如果你需要获取无需校验的表单数据，用在`validate`后用`getValues`。
`packages\effects\common-ui\src\ui\authentication\register.vue`第56行左右
```
const [Form, { getValues, validate }] = useVbenForm(
  reactive({
    commonConfig: {
      hideLabel: true,
      hideRequiredMark: true,
    },
    schema: computed(() => props.formSchema),
    showDefaultActions: false,
  }),
);

const router = useRouter();

async function handleSubmit() {
  const { valid } = await validate();
  if (valid) {
    const values = await getValues();
    emit('submit', values as { password: string; username: string });
  }
}
```

**Comment by ChenWeihua123** [comment]
哦哦get了 非常感谢您的回复 ♥️
