### ISSUE TITLE
Bug: Chrome浏览器，表单项的Input，记忆模式填充显示异常

### ISSUE THREAD

**Issue by lztbwlkj** [vbenjs/vue-vben-admin#4492]
### Version

Vben Admin V5

### Describe the bug?

浏览器中Input输入过的数据有记忆，下次输入鼠标标记Input获取焦点会弹出之前输入过的值。
这是官方演示平台截屏
![WeChatf41d554529e4fad3107ecde63dc20841](https://github.com/user-attachments/assets/49025e12-24ee-4ad1-95da-cda3b2d8fd69)

这是自己使用Form表单样式
姓名搜索“王倩倩” 就是通过上面的方式，浏览器对Input记忆模式填充的数据，不是手动输入的。
![image](https://github.com/user-attachments/assets/871a13d0-a20a-4e3e-9e7c-8922295424ff)

### Reproduction

通过浏览器的记忆模式填充的Input，其样式显示很奇怪，没有了输入框的边框，放在界面的搜索栏中异常难看

### System Info

```shell
System:
    OS: macOS 13.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 11.40 GB / 40.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.volta/tools/image/node/20.17.0/bin/node
    npm: 10.8.2 - ~/.volta/tools/image/node/20.17.0/bin/npm
    pnpm: 9.11.0 - ~/.volta/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.138
    Safari: 18.0
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by catalpaUI** [comment]
componentProps autocomplete :'off' 
input 原生属性有效的

**Comment by lztbwlkj** [comment]
这样改太简单粗暴了，我并不想丢失掉这个功能

**Comment by lztbwlkj** [comment]
``` css
input:-webkit-autofill {
  border-style: solid !important;
  border-color: #278df2
} 
```
整个css文件添加了这个样式可以了。不知道  border-color: #278df2 怎么配置动态的主题色
