### ISSUE TITLE
Bug: App Element Plus 组件 Pagination 在background设置true情况下，暗黑没有效果

### ISSUE THREAD

**Issue by catalpaUI** [vbenjs/vue-vben-admin#4496]
### Version

Vben Admin V5

### Describe the bug?

Pagination 组件设置background为true 暗黑情况下
对应的分页器按钮 未选中的 还是白天情况，暗黑没生效

### Reproduction

对应的 li 用到css变量 --el-fill-color
vben useElementPlusDesignTokens 没有注册改变量

### System Info

```shell
各种浏览器
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
能否截图看看。我测试时未发现你所说的问题
![image](https://github.com/user-attachments/assets/0660bfa0-6815-4c9f-9786-3bf00eb556e6)

**Comment by catalpaUI** [comment]
> 能否截图看看。我测试时未发现你所说的问题 ![image](https://private-user-images.githubusercontent.com/17241274/370532752-0660bfa0-6815-4c9f-9786-3bf00eb556e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMzMyNzMsIm5iZiI6MTcyNzIzMjk3MywicGF0aCI6Ii8xNzI0MTI3NC8zNzA1MzI3NTItMDY2MGJmYTAtNjgxNS00YzlmLTk3ODYtM2JmMDBlYjU1NmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDAyNTYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjODRlY2I2NWQ2MzA0MDU4MmRjNTcyOTA4NWEyNjMwMjkwZTBiOTI2ZTBmZTdlZDFjOWZhYzg2MTFmYjY1Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.c0ST0an7n7bmTPrPLM4mzU3e8dYkBR5AqaKCIABVBMM)

晚点吧，我这台电脑 没有vben
刚下载了个最新的包 pnpm也是最新的
只运行了pnpm install
运行页面报错 你知道这个怎么解决吗 之前也遇到过
![image](https://github.com/user-attachments/assets/182decf4-a6d2-4911-b537-1b102c189708)
