### ISSUE TITLE
Bug: App下使用Page组件，在Page组件同级使用其他组件有问题

### ISSUE THREAD

**Issue by catalpaUI** [vbenjs/vue-vben-admin#4497]
### Version

Vben Admin V5

### Describe the bug?

这个不一定是bug

我在app下 elment-plus  demos index.vue 下 加了个 分页做测试
结构大概ElPagination Page  两个组件同级的情况下
这种情况下，点击其他标签页,其他标签页的内容清空了
过程 标签页先点击 这个同级组件的页面 然后再点击 其他标签页，其他标签页都看不到内容

如果单独使用ElPagination 或者 Page不会有问题
或者 Page ElPagination /Pag

### Reproduction

Reproduction

### System Info

```shell
谷歌浏览器
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by catalpaUI** [comment]
![image](https://github.com/user-attachments/assets/06fe316b-e523-410c-bcf2-68d3e2fc48a7)

**这样的页面，进入系统 ，先点击 加载，然后再菜单或者标签页点击，页面都是空的**
![image](https://github.com/user-attachments/assets/2fe58478-ce9a-4986-905f-caaffe1ff0a4)

**Comment by imdap** [comment]
<img width="791" alt="image" src="https://github.com/user-attachments/assets/853a831c-903e-4832-a9d9-70201b3e5180">
https://doc.vben.pro/guide/other/faq.html#%E9%A1%B5%E9%9D%A2%E5%88%87%E6%8D%A2%E5%90%8E%E9%A1%B5%E9%9D%A2%E7%A9%BA%E7%99%BD
控制台是有warning的

**Comment by catalpaUI** [comment]
> <img alt="image" width="791" src="https://private-user-images.githubusercontent.com/28396334/370311350-853a831c-903e-4832-a9d9-70201b3e5180.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODg2MjEsIm5iZiI6MTcyNzE4ODMyMSwicGF0aCI6Ii8yODM5NjMzNC8zNzAzMTEzNTAtODUzYTgzMWMtOTAzZS00ODMyLWE5ZDktNzAyMDFiM2U1MTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDE0MzIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YTFmNDY4OTc4MDIyZmRiNmFiYmM1YWI5YzA0OTM1ZjdiM2ZkNGQ3NDVlZjU1ZjNkMmIzMDJkNmFkOTMwMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-g9kJWuu9ep_8YgGX5Kq3MMtyKUmn5InzSVuhwvvHZQ"> https://doc.vben.pro/guide/other/faq.html#%E9%A1%B5%E9%9D%A2%E5%88%87%E6%8D%A2%E5%90%8E%E9%A1%B5%E9%9D%A2%E7%A9%BA%E7%99%BD 控制台是有warning的

好的，谢谢
