### ISSUE TITLE
Bug: Form组件的展开收起重置窗口后不起作用

### ISSUE THREAD

**Issue by cbombonera** [vbenjs/vue-vben-admin#4498]
### Version

Vben Admin V5

### Describe the bug?

vben官网 queryFrom 示例页面  卡片标题名称【查询表单，默认折叠，折叠时保留2行】 进行测试  0-13的Input 名称字段Index

**A**
1.PC尺寸 转到手机尺寸 原本2行 0-4 Input ，然后将尺寸变化成手机尺寸 显示0-13 Input(这里觉得就有问题，但是这种自适应毕竟场景不多，能做到自适应问题不大)
2.然后将变成PC尺寸，页面显示还是0-13 Input 并没有回到0-4 Input场景
3.展开 收起功能，这个时候就已经没有用了，除了展开 和收起 的文字能切换，起不到任何作用

**B**
1.初始化尺寸是手机尺寸，代码配置的collapsedRows=2  页面显示一行
2.什么都没操作的情况下，手机转PC尺寸 所有Input 0-13 显示 并且展开/收起功能不再起作用

**求教**
1.对css不熟， 关于queryForm， 因为我考虑了分割面板可伸缩，不知道怎么伸缩面板 也就是div的情况下，比如div宽度=pc尺寸，那么也是一行三个div宽度=手机尺寸 那么一行一个，或者vform能配置那就更好了
2.对vue不熟，我看form的 提交点击事件是用的v-bind 这样函数我看在浏览器 审查元素 对应节点，属性上就能看到内容，我在想，如果是业务提交的函数，直接暴露是否不好？没有试验过，用@事件是否就不会暴露，是否更好一些？

![image](https://github.com/user-attachments/assets/d8014c4b-bb4b-45ec-8dd7-e5db5155369f)
![image](https://github.com/user-attachments/assets/1c8d7e05-61cc-40e0-833c-fe5e7d5d8e2b)
![image](https://github.com/user-attachments/assets/aade5bef-9725-4c99-9293-1ea8495541ee)

### Reproduction

同上

### System Info

```shell
谷歌浏览器
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by CHUZHI-L** [comment]
![1](https://github.com/user-attachments/assets/f3c9481c-96c7-483b-9b9c-d12c8c9f545a)

**Comment by coolliyong** [comment]
我也遇到了相同的问题，不过我的vben版本有点低，我修改了 Formaction 的advancedSpanObj 这块逻辑解决了，我代码里不需要显示更多，所以我粗暴的干掉了这些逻辑
