### ISSUE TITLE
Bug: form组件使用element-plus的CheckboxGroup存在选中问题

### ISSUE THREAD

**Issue by CHUZHI-L** [vbenjs/vue-vben-admin#4504]
### Version

Vben Admin V5

### Describe the bug?

form组件使用element-plus库时，CheckboxGroup没有选中效果，但实际的选项值已经选中，且无法取消选中，单独使用elCheckbox时正常，RadioGroup也正常，在checkbox首次点击时，warn:  Invalid prop: type check failed for prop "modelValue". Expected Array, got String with value "XXX".

### Reproduction

`<Form>
       <template #radioGroup="slotProps">
        <el-radio-group v-bind="slotProps">
          <el-radio :value="3">Option A</el-radio>
          <el-radio :value="6">Option B</el-radio>
          <el-radio :value="9">Option C</el-radio>
        </el-radio-group>
      </template>
      <template #checkboxGroup="slotProps">
        <el-checkbox-group v-bind="slotProps">
          <el-checkbox label="Option D" value="Value D" />
          <el-checkbox label="Option E" value="Value E" />
          <el-checkbox label="Option F" value="Value F" />
        </el-checkbox-group>
      </template>
      <template #checkbox="slotProps">
        <el-checkbox label="我已阅读并同意" v-bind="slotProps" />
      </template>
    </Form>
  schema: [
{
      component: 'RadioGroup',
      fieldName: 'radioGroup',
      label: '单选组',
      rules: 'selectRequired',
    },
    {
      component: 'CheckboxGroup',
      fieldName: 'checkboxGroup',
      label: '多选组',
      rules: 'selectRequired',
    },
    {
      component: 'Checkbox',
      fieldName: 'checkbox',
      label: '',
      defaultValue: false,
      renderComponentContent: () => {
        return {
          default: () => ['我已阅读并同意'],
        };
      },
      rules: 'selectRequired',
    },
]
`

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i5-13400
    Memory: 4.87 GB / 15.67 GB
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.7.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
    Chrome: 129.0.6668.71
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by CHUZHI-L** [comment]
![1](https://github.com/user-attachments/assets/0d9b03e2-cfd6-43e3-9b46-025688cae187)

**Comment by zhuizhubf** [comment]
没有设置配置默认值
https://doc.vben.pro/components/common-ui/vben-form.html

element-plus 的值类似
```
  config: {
    // ant design vue组件库默认都是 v-model:value
    baseModelPropName: 'value',

    // 一些组件是 v-model:checked 或者 v-model:fileList
    modelPropNameMap: {
      Checkbox: 'checked',
      Radio: 'checked',
      Switch: 'checked',
      Upload: 'fileList',
    },
  },
```

**Comment by CHUZHI-L** [comment]
已解决，需要设置 `baseModelPropName: 'value',`   谢谢！
