### ISSUE TITLE
Bug: 最新下载的包 安装运行后 系统登陆提示内部异常登录不了

### ISSUE THREAD

**Issue by catalpaUI** [vbenjs/vue-vben-admin#4505]
### Version

Vben Admin V5

### Describe the bug?

**也许不是bug 只是不知道怎么操作**
**以前也遇到过这种问题，求教**

2024/09/25 11点后下载的vben

操作 1.pnpm install

然后pnpm dev 点击登录发现登录不了 报的MOCK_USERS未找到

这个问题以前也遇到过，应该是global 未引用  apps=》backend-mock=》.nitro=》types=》nitro-imports.d.ts

不知道什么情况下 才能引用

然后 pnpm clean 再重新install 也没有
并且 clean 会提示 errno: -4048,code: 'EPERM', syscall: 'unlink',  @ast-grep\napi-win32-x64-msvc\ast-grep-napi.win32-x64-msvc.node 相关，也不知道什么原因，这个问题一直存在，但是确实可以clean 没有管
![image](https://github.com/user-attachments/assets/dbb6bd97-8372-484d-9036-33d4ee72cbe5)
![image](https://github.com/user-attachments/assets/4e5fb40d-d175-45d6-8370-f288994aab5b)

### Reproduction

同上

### System Info

```shell
vscode 最新

pnpm 9.10.0
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
pnpm clean  问题，最新代码应该解决了

**Comment by anncwb** [comment]
最新代码应该可以了，不行的话在重新打开一个issue
