### ISSUE TITLE
Bug: 菜单主题切换为白色的时候，选择菜单的样式有问题

### ISSUE THREAD

**Issue by 6155952** [vbenjs/vue-vben-admin#4507]
### Version

Vben Admin V2

### Describe the bug?

<img width="289" alt="微信图片_20240925120431" src="https://github.com/user-attachments/assets/fb838c98-a423-48b9-822f-1d0a7e896598">
如图所示，菜单主题切换为白色的时候，选择菜单的样式变成黑色，看不到菜单名称

### Reproduction

<img width="289" alt="微信图片_20240925120431" src="https://github.com/user-attachments/assets/a0f4af55-751f-49f5-aeda-426fa957412b">

### System Info

```shell
浏览器：Edge
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
css 颜色值得问题，自己找到颜色变量调整下即可。
