### ISSUE TITLE
在使用vben5时，使用and design vue组件中，<Card>组件可以正常使用，但是<a-button>和<a-modal>组件不能正常使用

### ISSUE THREAD

**Issue by zzfcat** [vbenjs/vue-vben-admin#4509]
**[](url)ant-design-vue中的Card组件可以正常使用，但是a-button只显示文字，没有样式，a-modal直接出现了**
```
<template>
  <Card :body-style="{ backgroundColor: 'rgb(245, 245, 245)', height: '20rem' }" title="实训组列表">
    <template #extra>
      <a-button type="primary" @click="showModal()">新建实训组</a-button>
    </template>
    <a-modal v-model:open="open" title="新建实训组" @ok="submit">
      <BaseForm />
    </a-modal>
  </Card>
</template>

<script setup lang="ts">
import { Card } from 'ant-design-vue';
import { useVbenForm } from '#/adapter';
import { ref } from "vue";

const open = ref<boolean>(false);

const submit = async () => {
   open.value = false; //关闭弹框
};

function showModal() {
  open.value = true;
}
</script>
```
![1](https://github.com/user-attachments/assets/5a12a80a-a103-4335-a944-2ad8b72008f0)

node_modules我删除了，并且通过pnpm install 重新下载了，还是不行

控制台打印信息
![2](https://github.com/user-attachments/assets/53921992-b814-4c58-aa15-e884c3c24b84)

**Comment by mynetfan** [comment]
你没有导入所需要的组件。
`import { Card, Button, Modal } from 'ant-design-vue';`
如果你非要用AButon这样的名字，像下面这样导入：
``import { Card, Button as AButton, Modal as AModal } from 'ant-design-vue';``

**Comment by zzfcat** [comment]
果然可以, 非常感谢
