### ISSUE TITLE
Bug: useVbenForm 自定义组件后，没有任何属性的 <Input /> 输入值以后会修改 defineModel 的值。

### ISSUE THREAD

**Issue by zxj176381** [vbenjs/vue-vben-admin#4515]
### Version

Vben Admin V5

### Describe the bug?

useVbenForm 自定义组件后，没有任何属性的 <Input /> 输入值以后会修改 defineModel 的值。
![93d1548ff53caa68de526cacdf42cc69](https://github.com/user-attachments/assets/9d47a51b-61fb-4d88-b5d8-54fe1c900d82)

### Reproduction

useVbenForm 自定义组件后，没有任何属性的 <Input /> 输入值以后会修改 defineModel 的值。

### System Info

```shell
default
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
描述清楚下吧，根本不知道你在说什么

**Comment by zxj176381** [comment]
上图中 自定义的一个组件。

**Comment by zxj176381** [comment]
vbenForm 返回的值也是 Input 的 value，并不是 我通过 button 设置的 defineModel

**Comment by vince292007** [comment]
ant design vue 绑定值应该是 `v-model:value` 才对

**Comment by zxj176381** [comment]
我并不想让 Input 控制我的 defineModel 啊，我只想通过按钮去修改

https://github.com/user-attachments/assets/6239810d-763e-4dff-8490-51ada9616f6e

![705c08b11a1f5c2accad0ee036e32c34](https://github.com/user-attachments/assets/b6dfd11d-88ab-47ec-9e72-a34362b43948)
![c01b42e9201e116f1cc2021f2cb6f1ac](https://github.com/user-attachments/assets/fd66ba9e-2652-411f-858d-a13df540d354)

**Comment by imdap** [comment]
`defineOptions({ inheritAttrs: false });`

**Comment by zxj176381** [comment]
嗷嗷嗷嗷，可以了
