### ISSUE TITLE
FEATURE: 添加图标选择器组件

### ISSUE THREAD

**Issue by Zhao-sj** [vbenjs/vue-vben-admin#4526]
### Version

Vben Admin V5

### Description

添加图标选择器组件

### Proposed Solution

添加图标选择器组件

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by kkfive** [comment]
mark
