### ISSUE TITLE
Bug: 预览登陆接口404

### ISSUE THREAD

**Issue by qhl123456** [vbenjs/vue-vben-admin#4530]
### Version

Vben Admin V5

### Describe the bug?

https://v2.vben.pro/#/login?redirect=/dashboard
这个预览的地址登陆404 

### Reproduction

https://v2.vben.pro/#/login?redirect=/dashboard
这个预览的地址登陆404 

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 163.69 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 9.4.0 - ~/.nvm/versions/node/v18.16.0/bin/pnpm
  Browsers:
    Chrome: 129.0.6668.70
    Safari: 17.5
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by likui628** [comment]
![image](https://github.com/user-attachments/assets/1b36c43b-347e-4305-b9c0-ec6989f661fc)

**Comment by qhl123456** [comment]
> ![image](https://private-user-images.githubusercontent.com/90845831/371384506-1b36c43b-347e-4305-b9c0-ec6989f661fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjQ1NzAsIm5iZiI6MTcyNzQyNDI3MCwicGF0aCI6Ii85MDg0NTgzMS8zNzEzODQ1MDYtMWIzNmM0M2ItMzQ3ZS00MzA1LWI5YzAtZWM2OTg5ZjY2MWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA4MDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYzZlOGJmNjA5MTdlOTdlYjZhODQ4YWNiNWNmMDU1YzViMzY3MzI4NjMwMzkxMTBkOGE0OWQ2OWYzZTAzNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tTK5cTPdzg8Vw_JT3YhVp0FP9l4y2t_oSeeya3-NQN0)

![image](https://github.com/user-attachments/assets/87ad8153-3938-4138-9b84-89c10016a6a3)

**Comment by aonoa** [comment]
你看看是不是开了梯子被拦了
