### ISSUE TITLE
Bug:  使用element-plus时，el-select、el-alert组件，info样式显示有问题

### ISSUE THREAD

**Issue by Ghaitao** [vbenjs/vue-vben-admin#4532]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/238ba834-7c00-4890-94f9-bb5a1cd1a245)
element-plus官网显示
![image](https://github.com/user-attachments/assets/8645228e-23b9-4c7d-83d4-b9fe6e0b01ae)
![image](https://github.com/user-attachments/assets/c8dc3ed7-53d4-4211-99cc-6b4cc405cd83)

### Reproduction

1

### System Info

```shell
1
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Zhao-sj** [comment]
v-loading指令的默认背景颜色在暗黑模式下也有问题
