### ISSUE TITLE
Bug: 退出登录后第二次登录菜单渲染失败，需要刷新后才能正常渲染 

### ISSUE THREAD

**Issue by smilecode11** [vbenjs/vue-vben-admin#4536]
### Version

Vben Admin V5

### Describe the bug?

我用的是后端获取的role标识然后根据本地菜单配置映射出来的的路由。（可以直接理解为后端获取）
1.刷新浏览器初次登录是没有有问题的
但是在进行退出操作的时候，没有接退出接口，直接走的清除缓存操作。再次登录时菜单不能正常生成了 报错的的地方是normalizeViewPath方法，通过控制台发现了两次进入该方法的 path 不相同
![image](https://github.com/user-attachments/assets/da0748af-cada-4776-a2fe-f24426be186c)
不能正常渲染菜单的 path 打印出来是这样的。
出现这样的状况后重新刷新下菜单又能重新渲染了，就是有点奇怪

### Reproduction

我用的是后端获取的role标识然后根据本地菜单配置映射出来的的路由。（可以直接理解为后端获取）
1.刷新浏览器初次登录是没有有问题的
但是在进行退出操作的时候，没有接退出接口，直接走的清除缓存操作。再次登录时菜单不能正常生成了 报错的的地方是normalizeViewPath方法，通过控制台发现了两次进入该方法的 path 不相同
![image](https://github.com/user-attachments/assets/da0748af-cada-4776-a2fe-f24426be186c)
不能正常渲染菜单的 path 打印出来是这样的。
出现这样的状况后重新刷新下菜单又能重新渲染了，就是有点奇怪

### System Info

```shell
chrome
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
看看能不能在示例环境复现下，目前我这边复现不了
