### ISSUE TITLE
Bug: 引入某些文件或者文件夹下文件，ts-plugin会报错找不到模块

### ISSUE THREAD

**Issue by yc0123450** [vbenjs/vue-vben-admin#4544]
### Version

Vben Admin V5

### Describe the bug?

![2ced384124f83cd2fc9af08d21af08b](https://github.com/user-attachments/assets/e49bfa95-0ed3-461c-9306-95539758acb7)

![849e3a6e216d802af56c2a7928a1403](https://github.com/user-attachments/assets/7ff36563-7224-423d-9059-64c795b7baaa)

如果，无论是组件里引入文件，或者配置路由，都会存在此情况，需要改成别的名字才不报错。具体报错如下：无法找到模块“xxxxxx”的声明文件。“xxxxx隐式拥有 "any" 类型。ts-plugin

### Reproduction

无

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (18) x64 Intel(R) Core(TM) Ultra 5 125H
    Memory: 7.85 GB / 23.47 GB
  Binaries:
    Node: 20.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.11.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
先看看文档的前置条件，你的插件、环境那些是否配置正确

**Comment by anncwb** [comment]
useFileicons.js这个后缀没写，肯定是不行，项目除了ts，其他文件都需要携带后缀名。

**Comment by yc0123450** [comment]
@anncwb 感谢，我尝试把所有插件全部禁用，然后再启用重启下编辑器，报错就没有了。有尝试一个一个重启插件看看具体是哪个引起的，但复现不了，不过先禁用再启用确实不报错了。
