### ISSUE TITLE
Docs: 咨询：V5表单怎么能像V2，每行都可以自定义列宽，还有

### ISSUE THREAD

**Issue by lztbwlkj** [vbenjs/vue-vben-admin#4545]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [ ] Confusing
- [X] Not sure?

### Explain in Detail

![WeChat2de9376abe0b7fd011f266637e0b45e8](https://github.com/user-attachments/assets/f3e2a3fb-f5b5-485f-a3d6-536f0be31285)

```ts
//关键代码
export const formSchema: VbenFormSchema[] = [
  {
    component: 'Textarea',
    componentProps: {
      placeholder: '请输入描述',
    },
    fieldName: 'description',
    label: '描述',
  },
  {
    component: 'Input',
    dependencies: {
      show: false,
      // 随意一个字段改变时，都会触发
      triggerFields: [''],
    },
    fieldName: 'id',
  },
];

 const [BaseForm, baseFormApi] = useVbenForm({
  // 所有表单项共用，可单独在表单内覆盖
  commonConfig: {
    // 所有表单项
    componentProps: {
      class: 'w-full',
    },
  },
  // 提交函数
  handleSubmit: onSubmit,
  schema: formSchema,
  showDefaultActions: false,
  // 大屏一行显示3个，中屏一行显示2个，小屏一行显示1个
  wrapperClass: 'grid-cols-2',
});
```

1、麻烦问一下，我想让备注拉通占满底部，应该怎么配置？
另外，发现配置ID隐藏必须得填“triggerFields：['']”， 只设置show:false是不起作用，这算不算一个BUG
```ts
dependencies: {
      show: false,
      // 随意一个字段改变时，都会触发
      triggerFields: [''],
    },
```
我只是想单纯的隐藏它

### Your Suggestion for Changes

1

**Comment by aonoa** [comment]
![image](https://github.com/user-attachments/assets/936a6c90-0d2f-4fe5-8233-ff58ea15203d)
`formItemClass: 'col-span-12',`配合` class: 'w-1/6',`，效果如下
![image](https://github.com/user-attachments/assets/2875fe37-dba0-47a9-bd3f-45df5e7258f1)

**Comment by anncwb** [comment]
可以参考 https://tailwindcss.com/docs/grid-template-rows
