### ISSUE TITLE
Bug: 关于V5的useVbenForm的componentProps字段BUG

### ISSUE THREAD

**Issue by lztbwlkj** [vbenjs/vue-vben-admin#4552]
### Version

Vben Admin V5

### Describe the bug?

代码如下，useVbenForm的schema中， componentProps直接赋值对象是没问题的， 但是换成Function配置就不起作用了，
```ts
{
    component: 'Select',
    // Function配置失效
    componentProps(values, actions) {
      return {
        fieldNames: {
          label: 'roleName',
          value: 'id',
        },
        mode: 'multiple',
        multiple: true, // 多选
        placeholder: '请选择角色',
      };
    },
  // 直接给对象一切正常
    componentProps: {
      fieldNames: {
        label: 'roleName',
        value: 'id',
      },
      mode: 'multiple',
      multiple: true, // 多选
      placeholder: '请选择角色',
    },
    fieldName: 'roleList',
    label: '角色',
    rules: 'required', // 必填
  },
```

### Reproduction

我看了componentProps的类型是可以给Function，希望这种方式两个都能起作用

### System Info

```shell
System:
    OS: macOS 13.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 7.13 GB / 40.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.volta/tools/image/node/20.17.0/bin/node
    npm: 10.8.2 - ~/.volta/tools/image/node/20.17.0/bin/npm
    pnpm: 9.11.0 - ~/.volta/bin/pnpm
  Browsers:
    Chrome: 129.0.6668.60
    Safari: 18.0
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
试了下，并没有问题，请尝试拉取最新代码。
<img width="623" alt="image" src="https://github.com/user-attachments/assets/3f8c58f9-33d3-4c2c-afe5-8c945cb43c4f">
<img width="459" alt="image" src="https://github.com/user-attachments/assets/a1db9c38-be04-47cd-94bc-ea5738842101">

**Comment by lztbwlkj** [comment]
这个问题存在的。 componentProps写成Function，通过“updateSchema”设置options就出现了。

![WeChat94c5015176ef09d81dbe5908f4417616](https://github.com/user-attachments/assets/ddfa7d4c-fba6-4b71-9caf-1fb4a6c5aef5)
