### ISSUE TITLE
Bug: 当我修改vite配置文件,设置vite.server.open = true时,启动项目后浏览器自动打开后报错

### ISSUE THREAD

**Issue by 1571312541** [vbenjs/vue-vben-admin#4562]
### Version

Vben Admin V5

### Describe the bug?

如下图,启动时,自动打开出现错误, 是因为Nitro Server启动太慢? 之后刷新页面就可以正常访问
![image](https://github.com/user-attachments/assets/c0547ce9-ca26-47e6-85c1-bf1703a73877)
![image](https://github.com/user-attachments/assets/aba82577-e554-4b30-bc97-9afdbeedc814)
![image](https://github.com/user-attachments/assets/9604cf04-c31b-47e3-ac73-e5740d631994)

### Reproduction

设置vite.server.open = true 并启动项目

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 16.58 GB / 31.75 GB
  Binaries:
    Node: 20.17.0 - D:\dev\tools\nvm\activated-nodejs\node.EXE
    npm: 10.8.2 - D:\dev\tools\nvm\activated-nodejs\npm.CMD
    pnpm: 9.12.0 - D:\dev\tools\nvm\activated-nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.65)
    Internet Explorer: 11.0.19041.4355
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
刷新下就好了，自动打开的时间比较早，mock服务还没启动成功。
