### ISSUE TITLE
Bug: vxe-table组件,引入项无法识别 

### ISSUE THREAD

**Issue by 1571312541** [vbenjs/vue-vben-admin#4568]
### Version

Vben Admin V5

### Describe the bug?

在playground/src/views/examples/vxe-table中,所有从#/adapter引入的 VxeGridProps, VxeGridListeners无法识别,但能正常运行
![image](https://github.com/user-attachments/assets/d12bd65b-4eb7-41b3-a457-0030d20a68fc)
![image](https://github.com/user-attachments/assets/ea790b71-cf9f-4cf0-aace-ecebbef360cb)

### Reproduction

-

### System Info

```shell
webstorm
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
没复现，重启IDE，重装依赖试试

**Comment by 1571312541** [comment]
> 没复现，重启IDE，重装依赖试试

已解决, 重装了依赖,重启了几次ide,就好了,ide抽了抽....
