### ISSUE TITLE
FEATURE: 表单组件，查询按钮 收起/展开，能否单独隐藏

### ISSUE THREAD

**Issue by LGX93** [vbenjs/vue-vben-admin#4570]
### Version

Vben Admin V5

### Description

查询按钮 收起/展开，少于收起展开数量时能否关闭，例如我只有两个文本框，一行3个，又想把查询按钮组放到同一行，会显示收起/展开，能否隐藏？
![微信截图_20241005174552](https://github.com/user-attachments/assets/f485afcc-af06-40e0-8abb-2c713d4c970d)
还有table组件，查询表单，小屏幕时，没有下边距
![微信截图_20241005174739](https://github.com/user-attachments/assets/f35fb3e1-3a94-4dfc-b764-32397cb69c00)

### Proposed Solution

如上

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by anncwb** [comment]
可以查看form组件的文档，通过表格的`formOptiosn.showCollapseButton`关闭，其余bug可以拉最新代码。

**Comment by LGX93** [comment]
![image](https://github.com/user-attachments/assets/b2117f37-8470-40fe-9a54-7add451c747d)
单行是正常，两行的边距和其他的不一样

**Comment by LGX93** [comment]
> 可以查看formComponents的文档，通过forms的`formOptiosn.showCollapseButton`关闭，其余bug可以拉最新代码。

![image](https://github.com/user-attachments/assets/2c65b92a-8a49-4cc1-af7e-ecba17170026)
一行2个的边距和其他的不一样
