### ISSUE TITLE
Bug: 菜单栏点击展开一个，其他的菜单也跟着展开了

### ISSUE THREAD

**Issue by Novices666** [vbenjs/vue-vben-admin#4571]
### Version

Vben Admin V5

### Describe the bug?

菜单栏点击展开一个，其他的菜单也跟着展开了
![recording](https://github.com/user-attachments/assets/b49e9576-2c63-420f-8084-ae5f07a23d75)
这里也有这个问题，但是没人回复
https://github.com/vbenjs/vue-vben-admin/discussions/2871

### Reproduction

我的router结构
![image](https://github.com/user-attachments/assets/c50e6eb9-01c4-4404-bee2-32625c63a400)
index.ts文件（router/routes/index.ts）
```ts
import type { RouteRecordRaw } from 'vue-router';

import { mergeRouteModules, traverseTreeValues } from '@vben/utils';

import { coreRoutes, fallbackNotFoundRoute } from './core';

const dynamicRouteFiles = import.meta.glob('./modules/**/*.ts', {
  eager: true,
});

// 有需要可以自行打开注释，并创建文件夹
// const externalRouteFiles = import.meta.glob('./external/**/*.ts', { eager: true });

/** 动态路由 */
const dynamicRoutes: RouteRecordRaw[] = mergeRouteModules(dynamicRouteFiles);

/** 外部路由列表，访问这些页面可以不需要Layout，可能用于内嵌在别的系统 */
// const externalRoutes: RouteRecordRaw[] = mergeRouteModules(externalRouteFiles);
const externalRoutes: RouteRecordRaw[] = [];

/** 路由列表，由基本路由+静态路由组成 */
const routes: RouteRecordRaw[] = [
  ...coreRoutes,
  ...externalRoutes,
  fallbackNotFoundRoute,
];

/** 基本路由列表，这些路由不需要进入权限拦截 */
const coreRouteNames = traverseTreeValues(coreRoutes, (route) => route.name);

export { coreRouteNames, dynamicRoutes, routes };
```

api.ts路由文件（例子，router\routes\modules\api.ts）
```ts
import type { RouteRecordRaw } from 'vue-router';

import { BasicLayout } from '#/layouts';

const routes: RouteRecordRaw[] = [
  {
    path: '/user/api',
    component: BasicLayout,
    meta: {
      title: 'API 中心',
      icon: 'lets-icons:target-fill',
      order: 2,
      hideChildrenInMenu: true,
    },
    children: [
      {
        path: '/user/api',
        name: 'Api',
        component: () => import('#/views/user/api/index.vue'),
        meta: {
          title: 'API 中心',
        },
      },
    ],
  },
];

export default routes;

```

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 3.07 GB / 15.77 GB
  Binaries:
    Node: 20.17.0 - D:\nodeJs\node.EXE
    npm: 10.8.2 - D:\nodeJs\npm.CMD
    pnpm: 9.11.0 - D:\nodeJs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.3570.0)
    Internet Explorer: 11.0.19041.3570
```

### Relevant log output

```shell
控制台没有报错信息
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
你应该需要排查看看你的菜单配置有没有重复的name或者path

**Comment by Novices666** [comment]
之前确实父路由和子路由的path有重复，现在将重复的子路由的path，统一加了/index
问题依然存在。
修改过packages\constants\src\core.ts中的默认路径

![image](https://github.com/user-attachments/assets/db623756-51e7-4dc8-a111-44d312c0c9e3)

**Comment by Novices666** [comment]
重新拉取了项目，将我写好的router，view，拖过去覆盖掉，问题依然存在。不清楚是哪里的问题
这是代码文件，已删除依赖node_modules。
[web-ele.zip](https://github.com/user-attachments/files/17266712/web-ele.zip)

**Comment by Novices666** [comment]
已解决
问题： 所有一级菜单都没有设置name字段
解决方法：给一级菜单设置name且不可重复。
