### ISSUE TITLE
Bug: 切换系统后使用搜索，并点击左侧菜单后，tab页签不显示或者没联动？

### ISSUE THREAD

**Issue by aitrx** [vbenjs/vue-vben-admin#4592]
### Version

Vben Admin V5

### Describe the bug?

1.进入系统后，搜索（目前搜索正常），需要退出系统重新进。(一定要进入系统，搜索一下，并切换一下左侧菜单，然后退出重新进入系统才能复现)
2.再次进入系统后，继续点击搜索，先删除搜索历史>再搜“菜单”并选择第一菜单词条，切换左边其他菜单，tab页签无变化。
3.清除搜索历史，退出系统。再次进入系统，页签没有显示出来，刷新页面后显示。

### Reproduction

https://github.com/user-attachments/assets/76ab3335-3f5c-49c5-a92c-f98bfcea6705

### System Info

```shell
vben5.x
Chrome最新版
Edge最新版
```

### Relevant log output

```shell
突然发现vben更新大版本，线上体验所得结果
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aitrx** [comment]
Uploading 384bf6114a2bbba07c45aefbe10d4fda.mp4…

**Comment by anncwb** [comment]
视频没传成功

**Comment by aitrx** [comment]
初衷是突然发现vben更新大版本了就体验了下，很丝滑。但是搜索的时候tab页签隐约出现2个小情况：退出系统>重新进入系统>清空搜索历史信息>搜索。然后切换左边菜单栏目，会出现tab不显示或者没有跟左边菜单联动的情况，紧急录制了个视频片段：

https://github.com/user-attachments/assets/beb8fa52-ef49-4a2d-82df-89866fc2d477

**Comment by anncwb** [comment]
应该修复了， 可以再试试。

**Comment by aitrx** [comment]
> 应该修复了， 可以再试试。
Perfect，已用上了
