### ISSUE TITLE
componentProps配置失效问题

### ISSUE THREAD

**Issue by lztbwlkj** [vbenjs/vue-vben-admin#4594]
_Originally posted by @anncwb in https://github.com/vbenjs/vue-vben-admin/issues/4552#issuecomment-2390566171_

**Comment by lztbwlkj** [comment]
这个问题存在的。 componentProps写成Function，通过“updateSchema”设置options就出现了。

![WeChat94c5015176ef09d81dbe5908f4417616](https://github.com/user-attachments/assets/ddfa7d4c-fba6-4b71-9caf-1fb4a6c5aef5)

**Comment by mynetfan** [comment]
updateSchema会合并schema配置，你不应该尝试将一个函数与一个对象合并。如果你一开始使用了函数来返回componentProps，而这个函数内又引用了其它的响应式对象，那么componentProps会自动更新无需你手动调用updateSchema

**Comment by anncwb** [comment]
上面说的是正确的，需要自己调整下写法
