### ISSUE TITLE
FEATURE: vxe-table的封装没有删除的相关逻辑

### ISSUE THREAD

**Issue by RanMaoting** [vbenjs/vue-vben-admin#4604]
### Version

Vben Admin V5

### Description

现在的表格封装只有查询的逻辑,希望能在封装组件中加入相关的逻辑,方便进行删除和批量删除
vxe-table的内置删除proxy不好用,必须在复选中选中才能触发删除指令,希望在封装中添加一个新的指令

### Proposed Solution

添加新的删除指令来统一处理删除和批量删除,主要是要处理删除后的分页问题

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by anncwb** [comment]
目前不会去改太多的vxe内部东西，遵循vxe-table的做法就好了
