### ISSUE TITLE
Docs: Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by milletpeak** [vbenjs/vue-vben-admin#4605]
### Documentation is

- [X] Missing
- [X] Outdated
- [X] Confusing
- [X] Not sure?

### Explain in Detail

在使用nginx本地预览的时候，pnpm build:antd 报错

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

<img width="1266" alt="image" src="https://github.com/user-attachments/assets/ebbb0c14-a163-45ca-8a0b-4cd986cad5de">

<img width="1250" alt="image" src="https://github.com/user-attachments/assets/a4078b19-1e2d-4003-8504-c3e1ba60f553">

这是我本地的nginx配置
![image](https://github.com/user-attachments/assets/de2b3a0c-a1d3-4ce6-998c-e04819e554cd)

这是.env.production文件配置
<img width="700" alt="image" src="https://github.com/user-attachments/assets/6804d4a9-3bfa-4f2c-9ac3-a617a7b7cea1">

### Your Suggestion for Changes

按照构建和部署文档配置的，这种错误一般就是vite的base路径不对，但是我已经配置了根路径，还是这个错误

**Comment by anncwb** [comment]
https://doc.vben.pro/guide/other/faq.html#nginx-%E9%83%A8%E7%BD%B2
