### ISSUE TITLE
Bugment-: eleplus form 适配存在问题

### ISSUE THREAD

**Issue by nanzhang237420759** [vbenjs/vue-vben-admin#4611]
### Version

Vben Admin V5

### Describe the bug?

 ElRadioGroup 和  ElCheckboxGroup  都无法显示，希望能提供一个示例。

### Reproduction

   {
    component: 'RadioGroup',
    fieldName: 'menuType',
    label: '菜单类型', 
    renderComponentContent: () => {
      return {
        default: () => {
          return [
            h(
              ElRadioButton,
              {
                props: { value: 'M' },
              },
              () => '菜单',
            ),
            h(
              ElRadioButton,
              {
                props: { value: 'C' },
              },
              () => '按钮',
            ),
          ];
        },
      };
    },
    defaultValue: 'M',
  },
目前使用的是该方式，可以显示，但是无法选择。 控制台输出 :ElementPlusError: [el-radio] [API] label act as value is about to be deprecated in version 3.0.0, please use value instead. 感觉这个props 的 value 就没生效。点击选项都会被选中，控制台报警告：chunk-BYNCQTQY.js?v=6795ff52:122 [Vue warn]: Invalid event arguments: event validation failed for event "update:modelValue".

### System Info

```shell
windows 11
"element-plus": "^2.8.1"
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Zhao-sj** [comment]
![image](https://github.com/user-attachments/assets/3721e87a-c8cb-40e1-830a-30d8206965ad)
woshi我是这样定义了一个组件，模仿antdv的参数，然后在adapter中换成自定义的组件来使用

**Comment by mynetfan** [comment]
你的h函数用法有误。第二个参数传入属性不需要额外的props这一层。
举个例子：
```
h(ElRadioButton, { value: 'M'  }, () => '菜单')
```

**Comment by nanzhang237420759** [comment]
感谢指导，我在form.ts里面重新实现了下：

![image](https://github.com/user-attachments/assets/cec57bc1-84b6-4a3d-a951-a66d606c8039)

 使用：
![image](https://github.com/user-attachments/assets/e813dd2e-1825-45b5-a841-e5ccb2463b76)

这样就不用重开组件了。

还尝试了使用原有的方式:
![image](https://github.com/user-attachments/assets/dadd9f72-c756-47cd-a51e-b9bd662e4c71)

最终效果:
![image](https://github.com/user-attachments/assets/01696bc7-d910-40f2-98c0-1187b5e49053)

仅供大家参考~
