### ISSUE TITLE
Bug: 国际化文件无法使用yaml格式

### ISSUE THREAD

**Issue by RanMaoting** [vbenjs/vue-vben-admin#4612]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/bb1fcd94-ef63-4ca6-95ff-2e1525831e1f)

在加载函数中显示可以使用yaml格式的文件,但是实际上无法使用,会解析错误
![image](https://github.com/user-attachments/assets/937bc92d-d28c-4ea3-895d-260d1a525759)
![image](https://github.com/user-attachments/assets/db79911d-42fa-47c5-812f-f89f447bd890)

### Reproduction

/

### System Info

```shell
/
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
不支持yaml和yml，需要自己加插件调整，yml格式实际拿到对象内存占用偏大，且必须安装插件才能识别，不适合语言文件的一些扩展。截图这里多余的，后续会删除。
