### ISSUE TITLE
FEATURE: VbenForm with FieldArray 

### ISSUE THREAD

**Issue by han2-n** [vbenjs/vue-vben-admin#4616]
### Version

Vben Admin V5

### Description

How can i use VbenForm with nested array?

### Proposed Solution

How can i use VbenForm with nested array?

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by mynetfan** [comment]
Set `fieldName` by separating multiple levels of fields with dots. Just like 'a.b.c' or 'a.0'、'a.0.b'

**Comment by nguyenhan-se** [comment]
> Set `fieldName` by separating multiple levels of fields with dots. Just like 'a.b.c' or 'a.0'、'a.0.b'

can you support me some sample?
