### ISSUE TITLE
Bug: element-plus版本VbenForm Select下拉框设置Option提示“无数据”

### ISSUE THREAD

**Issue by arthuridea** [vbenjs/vue-vben-admin#4619]
### Version

Vben Admin V5

### Describe the bug?

尝试过antd版本能够正常显示选项，playground（antd）中也表现正常。
在element-plus版本中，通过schema配置后不生效。
有没有相关文档或者示例说明一下element-plus组件使用？
![image](https://github.com/user-attachments/assets/56d1a106-0b5c-4c06-8023-8cdd38fed302)

### Reproduction

复制的playground下的例子，将antd相关import改成element-plus的

### System Info

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
    Memory: 11.80 GB / 31.73 GB
  Binaries:
    Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.65)
    Internet Explorer: 11.0.26100.1882
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Whbbit1999** [comment]
element plus不支持在el-select上直接写options，可以自己实现一个select render，可以参考下面的代码把`adapter/form.ts`文件改一下就可以了
```t·
import type {
  BaseFormComponentType,
  VbenFormSchema as FormSchema,
  VbenFormProps,
} from '@vben/common-ui';

import type { Component, SetupContext } from 'vue';
import { h } from 'vue';

import { setupVbenForm, useVbenForm as useForm, z } from '@vben/common-ui';
import { $t } from '@vben/locales';

import {
  ElButton,
  ElCheckbox,
  ElCheckboxGroup,
  ElDivider,
  ElInput,
  ElInputNumber,
  ElOption,
  ElRadioGroup,
  ElSelect,
  ElSpace,
  ElSwitch,
  ElTimePicker,
  ElTreeSelect,
  ElUpload,
} from 'element-plus';
// 业务表单组件适配

export type FormComponentType =
  | 'Checkbox'
  | 'CheckboxGroup'
  | 'DatePicker'
  | 'Divider'
  | 'Input'
  | 'InputNumber'
  | 'RadioGroup'
  | 'Select'
  | 'Space'
  | 'Switch'
  | 'TimePicker'
  | 'TreeSelect'
  | 'Upload'
  | BaseFormComponentType;

const withDefaultPlaceholder = <T extends Component>(
  component: T,
  type: 'input' | 'select',
) => {
  return (props: any, { attrs, slots }: Omit<SetupContext, 'expose'>) => {
    const placeholder = props?.placeholder || $t(`placeholder.${type}`);
    return h(component, { ...props, ...attrs, placeholder }, slots);
  };
};

const customSelectRender = <T extends Component>(component: T) => {
  return (props: any, { attrs }: Omit<SetupContext, 'expose'>) => {
    const placeholder = props?.placeholder || $t(`placeholder.select`);
    const options = props.options;
    return h(component, { ...props, ...attrs, placeholder }, () => {
      // ElOption,
      return options?.map((option: any) =>
        h(ElOption, { label: option.label, value: option.value }),
      );
    });
  };
};

// 初始化表单组件，并注册到form组件内部
setupVbenForm<FormComponentType>({
  components: {
    Checkbox: ElCheckbox,
    CheckboxGroup: ElCheckboxGroup,
    // 自定义默认的重置按钮
    DefaultResetActionButton: (props, { attrs, slots }) => {
      return h(ElButton, { ...props, attrs, type: 'info' }, slots);
    },
    // 自定义默认的提交按钮
    DefaultSubmitActionButton: (props, { attrs, slots }) => {
      return h(ElButton, { ...props, attrs, type: 'primary' }, slots);
    },
    Divider: ElDivider,
    Input: withDefaultPlaceholder(ElInput, 'input'),
    InputNumber: withDefaultPlaceholder(ElInputNumber, 'input'),
    RadioGroup: ElRadioGroup,
    Select: customSelectRender(ElSelect),
    Space: ElSpace,
    Switch: ElSwitch,
    TimePicker: ElTimePicker,
    TreeSelect: withDefaultPlaceholder(ElTreeSelect, 'select'),
    Upload: ElUpload,
  },
  config: {
    modelPropNameMap: {
      Upload: 'fileList',
    },
  },
  defineRules: {
    required: (value, _params, ctx) => {
      if (value === undefined || value === null || value.length === 0) {
        return $t('formRules.required', [ctx.label]);
      }
      return true;
    },
    selectRequired: (value, _params, ctx) => {
      if (value === undefined || value === null) {
        return $t('formRules.selectRequired', [ctx.label]);
      }
      return true;
    },
  },
});

const useVbenForm = useForm<FormComponentType>;

export { useVbenForm, z };

export type VbenFormSchema = FormSchema<FormComponentType>;
export type { VbenFormProps };
```

**Comment by arthuridea** [comment]
> element plus不支持在el-select上直接写options，可以自己实现一个select render，可以参考下面的代码把`adapter/form.ts`文件改一下就可以了
> 
> ```
> import type {
>   BaseFormComponentType,
>   VbenFormSchema as FormSchema,
>   VbenFormProps,
> } from '@vben/common-ui';
> 
> import type { Component, SetupContext } from 'vue';
> import { h } from 'vue';
> 
> import { setupVbenForm, useVbenForm as useForm, z } from '@vben/common-ui';
> import { $t } from '@vben/locales';
> 
> import {
>   ElButton,
>   ElCheckbox,
>   ElCheckboxGroup,
>   ElDivider,
>   ElInput,
>   ElInputNumber,
>   ElOption,
>   ElRadioGroup,
>   ElSelect,
>   ElSpace,
>   ElSwitch,
>   ElTimePicker,
>   ElTreeSelect,
>   ElUpload,
> } from 'element-plus';
> // 业务表单组件适配
> 
> export type FormComponentType =
>   | 'Checkbox'
>   | 'CheckboxGroup'
>   | 'DatePicker'
>   | 'Divider'
>   | 'Input'
>   | 'InputNumber'
>   | 'RadioGroup'
>   | 'Select'
>   | 'Space'
>   | 'Switch'
>   | 'TimePicker'
>   | 'TreeSelect'
>   | 'Upload'
>   | BaseFormComponentType;
> 
> const withDefaultPlaceholder = <T extends Component>(
>   component: T,
>   type: 'input' | 'select',
> ) => {
>   return (props: any, { attrs, slots }: Omit<SetupContext, 'expose'>) => {
>     const placeholder = props?.placeholder || $t(`placeholder.${type}`);
>     return h(component, { ...props, ...attrs, placeholder }, slots);
>   };
> };
> 
> const customSelectRender = <T extends Component>(component: T) => {
>   return (props: any, { attrs }: Omit<SetupContext, 'expose'>) => {
>     const placeholder = props?.placeholder || $t(`placeholder.select`);
>     const options = props.options;
>     return h(component, { ...props, ...attrs, placeholder }, () => {
>       // ElOption,
>       return options?.map((option: any) =>
>         h(ElOption, { label: option.label, value: option.value }),
>       );
>     });
>   };
> };
> 
> // 初始化表单组件，并注册到form组件内部
> setupVbenForm<FormComponentType>({
>   components: {
>     Checkbox: ElCheckbox,
>     CheckboxGroup: ElCheckboxGroup,
>     // 自定义默认的重置按钮
>     DefaultResetActionButton: (props, { attrs, slots }) => {
>       return h(ElButton, { ...props, attrs, type: 'info' }, slots);
>     },
>     // 自定义默认的提交按钮
>     DefaultSubmitActionButton: (props, { attrs, slots }) => {
>       return h(ElButton, { ...props, attrs, type: 'primary' }, slots);
>     },
>     Divider: ElDivider,
>     Input: withDefaultPlaceholder(ElInput, 'input'),
>     InputNumber: withDefaultPlaceholder(ElInputNumber, 'input'),
>     RadioGroup: ElRadioGroup,
>     Select: customSelectRender(ElSelect),
>     Space: ElSpace,
>     Switch: ElSwitch,
>     TimePicker: ElTimePicker,
>     TreeSelect: withDefaultPlaceholder(ElTreeSelect, 'select'),
>     Upload: ElUpload,
>   },
>   config: {
>     modelPropNameMap: {
>       Upload: 'fileList',
>     },
>   },
>   defineRules: {
>     required: (value, _params, ctx) => {
>       if (value === undefined || value === null || value.length === 0) {
>         return $t('formRules.required', [ctx.label]);
>       }
>       return true;
>     },
>     selectRequired: (value, _params, ctx) => {
>       if (value === undefined || value === null) {
>         return $t('formRules.selectRequired', [ctx.label]);
>       }
>       return true;
>     },
>   },
> });
> 
> const useVbenForm = useForm<FormComponentType>;
> 
> export { useVbenForm, z };
> 
> export type VbenFormSchema = FormSchema<FormComponentType>;
> export type { VbenFormProps };
> ```

感谢！试了可以了。

**Comment by Whbbit1999** [comment]
> > element plus不支持在el-select上直接写options，可以自己实现一个select render，可以参考下面的代码把`adapter/form.ts`文件改一下就可以了
> > ```
> > import type {
> >   BaseFormComponentType,
> >   VbenFormSchema as FormSchema,
> >   VbenFormProps,
> > } from '@vben/common-ui';
> > 
> > import type { Component, SetupContext } from 'vue';
> > import { h } from 'vue';
> > 
> > import { setupVbenForm, useVbenForm as useForm, z } from '@vben/common-ui';
> > import { $t } from '@vben/locales';
> > 
> > import {
> >   ElButton,
> >   ElCheckbox,
> >   ElCheckboxGroup,
> >   ElDivider,
> >   ElInput,
> >   ElInputNumber,
> >   ElOption,
> >   ElRadioGroup,
> >   ElSelect,
> >   ElSpace,
> >   ElSwitch,
> >   ElTimePicker,
> >   ElTreeSelect,
> >   ElUpload,
> > } from 'element-plus';
> > // 业务表单组件适配
> > 
> > export type FormComponentType =
> >   | 'Checkbox'
> >   | 'CheckboxGroup'
> >   | 'DatePicker'
> >   | 'Divider'
> >   | 'Input'
> >   | 'InputNumber'
> >   | 'RadioGroup'
> >   | 'Select'
> >   | 'Space'
> >   | 'Switch'
> >   | 'TimePicker'
> >   | 'TreeSelect'
> >   | 'Upload'
> >   | BaseFormComponentType;
> > 
> > const withDefaultPlaceholder = <T extends Component>(
> >   component: T,
> >   type: 'input' | 'select',
> > ) => {
> >   return (props: any, { attrs, slots }: Omit<SetupContext, 'expose'>) => {
> >     const placeholder = props?.placeholder || $t(`placeholder.${type}`);
> >     return h(component, { ...props, ...attrs, placeholder }, slots);
> >   };
> > };
> > 
> > const customSelectRender = <T extends Component>(component: T) => {
> >   return (props: any, { attrs }: Omit<SetupContext, 'expose'>) => {
> >     const placeholder = props?.placeholder || $t(`placeholder.select`);
> >     const options = props.options;
> >     return h(component, { ...props, ...attrs, placeholder }, () => {
> >       // ElOption,
> >       return options?.map((option: any) =>
> >         h(ElOption, { label: option.label, value: option.value }),
> >       );
> >     });
> >   };
> > };
> > 
> > // 初始化表单组件，并注册到form组件内部
> > setupVbenForm<FormComponentType>({
> >   components: {
> >     Checkbox: ElCheckbox,
> >     CheckboxGroup: ElCheckboxGroup,
> >     // 自定义默认的重置按钮
> >     DefaultResetActionButton: (props, { attrs, slots }) => {
> >       return h(ElButton, { ...props, attrs, type: 'info' }, slots);
> >     },
> >     // 自定义默认的提交按钮
> >     DefaultSubmitActionButton: (props, { attrs, slots }) => {
> >       return h(ElButton, { ...props, attrs, type: 'primary' }, slots);
> >     },
> >     Divider: ElDivider,
> >     Input: withDefaultPlaceholder(ElInput, 'input'),
> >     InputNumber: withDefaultPlaceholder(ElInputNumber, 'input'),
> >     RadioGroup: ElRadioGroup,
> >     Select: customSelectRender(ElSelect),
> >     Space: ElSpace,
> >     Switch: ElSwitch,
> >     TimePicker: ElTimePicker,
> >     TreeSelect: withDefaultPlaceholder(ElTreeSelect, 'select'),
> >     Upload: ElUpload,
> >   },
> >   config: {
> >     modelPropNameMap: {
> >       Upload: 'fileList',
> >     },
> >   },
> >   defineRules: {
> >     required: (value, _params, ctx) => {
> >       if (value === undefined || value === null || value.length === 0) {
> >         return $t('formRules.required', [ctx.label]);
> >       }
> >       return true;
> >     },
> >     selectRequired: (value, _params, ctx) => {
> >       if (value === undefined || value === null) {
> >         return $t('formRules.selectRequired', [ctx.label]);
> >       }
> >       return true;
> >     },
> >   },
> > });
> > 
> > const useVbenForm = useForm<FormComponentType>;
> > 
> > export { useVbenForm, z };
> > 
> > export type VbenFormSchema = FormSchema<FormComponentType>;
> > export type { VbenFormProps };
> > ```
> 
> 感谢！试了可以了。

😄这个有些缺陷，根据下面这样改一下可以把disabled props也接收到
<img width="774" alt="image" src="https://github.com/user-attachments/assets/d1cc41d2-6788-4ef1-8b3c-7b6ea050b224">

**Comment by arthuridea** [comment]
> > > element plus不支持在el-select上直接写options，可以自己实现一个select render，可以参考下面的代码把`adapter/form.ts`文件改一下就可以了
> > > ```
> > > import type {
> > >   BaseFormComponentType,
> > >   VbenFormSchema as FormSchema,
> > >   VbenFormProps,
> > > } from '@vben/common-ui';
> > > 
> > > import type { Component, SetupContext } from 'vue';
> > > import { h } from 'vue';
> > > 
> > > import { setupVbenForm, useVbenForm as useForm, z } from '@vben/common-ui';
> > > import { $t } from '@vben/locales';
> > > 
> > > import {
> > >   ElButton,
> > >   ElCheckbox,
> > >   ElCheckboxGroup,
> > >   ElDivider,
> > >   ElInput,
> > >   ElInputNumber,
> > >   ElOption,
> > >   ElRadioGroup,
> > >   ElSelect,
> > >   ElSpace,
> > >   ElSwitch,
> > >   ElTimePicker,
> > >   ElTreeSelect,
> > >   ElUpload,
> > > } from 'element-plus';
> > > // 业务表单组件适配
> > > 
> > > export type FormComponentType =
> > >   | 'Checkbox'
> > >   | 'CheckboxGroup'
> > >   | 'DatePicker'
> > >   | 'Divider'
> > >   | 'Input'
> > >   | 'InputNumber'
> > >   | 'RadioGroup'
> > >   | 'Select'
> > >   | 'Space'
> > >   | 'Switch'
> > >   | 'TimePicker'
> > >   | 'TreeSelect'
> > >   | 'Upload'
> > >   | BaseFormComponentType;
> > > 
> > > const withDefaultPlaceholder = <T extends Component>(
> > >   component: T,
> > >   type: 'input' | 'select',
> > > ) => {
> > >   return (props: any, { attrs, slots }: Omit<SetupContext, 'expose'>) => {
> > >     const placeholder = props?.placeholder || $t(`placeholder.${type}`);
> > >     return h(component, { ...props, ...attrs, placeholder }, slots);
> > >   };
> > > };
> > > 
> > > const customSelectRender = <T extends Component>(component: T) => {
> > >   return (props: any, { attrs }: Omit<SetupContext, 'expose'>) => {
> > >     const placeholder = props?.placeholder || $t(`placeholder.select`);
> > >     const options = props.options;
> > >     return h(component, { ...props, ...attrs, placeholder }, () => {
> > >       // ElOption,
> > >       return options?.map((option: any) =>
> > >         h(ElOption, { label: option.label, value: option.value }),
> > >       );
> > >     });
> > >   };
> > > };
> > > 
> > > // 初始化表单组件，并注册到form组件内部
> > > setupVbenForm<FormComponentType>({
> > >   components: {
> > >     Checkbox: ElCheckbox,
> > >     CheckboxGroup: ElCheckboxGroup,
> > >     // 自定义默认的重置按钮
> > >     DefaultResetActionButton: (props, { attrs, slots }) => {
> > >       return h(ElButton, { ...props, attrs, type: 'info' }, slots);
> > >     },
> > >     // 自定义默认的提交按钮
> > >     DefaultSubmitActionButton: (props, { attrs, slots }) => {
> > >       return h(ElButton, { ...props, attrs, type: 'primary' }, slots);
> > >     },
> > >     Divider: ElDivider,
> > >     Input: withDefaultPlaceholder(ElInput, 'input'),
> > >     InputNumber: withDefaultPlaceholder(ElInputNumber, 'input'),
> > >     RadioGroup: ElRadioGroup,
> > >     Select: customSelectRender(ElSelect),
> > >     Space: ElSpace,
> > >     Switch: ElSwitch,
> > >     TimePicker: ElTimePicker,
> > >     TreeSelect: withDefaultPlaceholder(ElTreeSelect, 'select'),
> > >     Upload: ElUpload,
> > >   },
> > >   config: {
> > >     modelPropNameMap: {
> > >       Upload: 'fileList',
> > >     },
> > >   },
> > >   defineRules: {
> > >     required: (value, _params, ctx) => {
> > >       if (value === undefined || value === null || value.length === 0) {
> > >         return $t('formRules.required', [ctx.label]);
> > >       }
> > >       return true;
> > >     },
> > >     selectRequired: (value, _params, ctx) => {
> > >       if (value === undefined || value === null) {
> > >         return $t('formRules.selectRequired', [ctx.label]);
> > >       }
> > >       return true;
> > >     },
> > >   },
> > > });
> > > 
> > > const useVbenForm = useForm<FormComponentType>;
> > > 
> > > export { useVbenForm, z };
> > > 
> > > export type VbenFormSchema = FormSchema<FormComponentType>;
> > > export type { VbenFormProps };
> > > ```
> > 
> > 
> > 感谢！试了可以了。
> 
> 😄这个有些缺陷，根据下面这样改一下可以把disabled props也接收到 <img alt="image" width="774" src="https://private-user-images.githubusercontent.com/60510247/375941074-d1cc41d2-6788-4ef1-8b3c-7b6ea050b224.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MjI2MzQsIm5iZiI6MTcyODcyMjMzNCwicGF0aCI6Ii82MDUxMDI0Ny8zNzU5NDEwNzQtZDFjYzQxZDItNjc4OC00ZWYxLThiM2MtN2I2ZWEwNTBiMjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA4Mzg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYjhiZDJkOGIzMjgwMzZhMWNmZDRkOWYxY2IxYTZlODNhZGFkNmNiOTc3MGE5N2I4YTAyYjE5YTU5ZmNlNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W3q-9TN-L4fLG7KUzPCy2vPm3POXfjYZje0KLe2TVuo">

我再研究一下，感谢！

**Comment by mynetfan** [comment]
element plus 可以直接用 selectV2 这个组件代替select，它提供类似antd的options属性来自动生成备选项。
https://element-plus.org/zh-CN/component/select-v2.html

**Comment by nanzhang237420759** [comment]
求大神指点默认值怎么才能生效呢？
