### ISSUE TITLE
FEATURE: 是否支持nuxt

### ISSUE THREAD

**Issue by mushu1990** [vbenjs/vue-vben-admin#4629]
### Version

Vben Admin V5

### Description

app中使用nuxt集成项目

### Proposed Solution

app中使用nuxt集成项目

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by aonoa** [comment]
重复 https://github.com/vbenjs/vue-vben-admin/issues/4078
