### ISSUE TITLE
Bug: 子项目preferences文件中配置项无法覆盖默认配置项

### ISSUE THREAD

**Issue by ltbztj** [vbenjs/vue-vben-admin#4632]
### Version

Vben Admin V5

### Describe the bug?

import { defineOverridesPreferences } from '@vben/preferences';

import logo from '#/assets/logo/logo.png';
/**
 * @description 项目配置文件
 * 只需要覆盖项目中的一部分配置，不需要的配置不用覆盖，会自动使用默认配置
 */
export const overridesPreferences = defineOverridesPreferences({
  // overrides
  app: {
    accessMode: 'backend',
    locale: 'zh-CN',
    name: import.meta.env.VITE_APP_TITLE,
  },
  copyright: {
    companyName: 'xxx', // 版权公司名
    companySiteLink: 'javascript:void(0)',
    date: 'xxx', // 版权日期
    icp: 'xxx', // 备案号
    icpLink: 'xxx', // 备案号链接
  },
  widget: {
    languageToggle: false,
  },
});

### Reproduction

.\packages\@core\preferences\src\preferences.ts
该路径文件中 

```ts
 // 加载并合并当前存储的偏好设置
    const mergedPreference = merge(
      {},
      // overrides,
      this.loadCachedPreferences() || {},
      this.initialPreferences,
    );
```

此处代码合并是否存在错误 

```ts
 // 加载并合并当前存储的偏好设置
    const mergedPreference = merge(
      {},
      // overrides,
      this.initialPreferences,
      this.loadCachedPreferences() || {},
    );
```
将代码修改为以上代码后 即可正常覆盖配置项

### System Info

```shell
//
```

### Relevant log output

```shell
//
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
这个文件更改需要清空 localStorage 才能生效。
