### ISSUE TITLE
Bug: Naive Ui项目中从adapter中创建的全局dialog style bug

### ISSUE THREAD

**Issue by RanMaoting** [vbenjs/vue-vben-admin#4633]
### Version

Vben Admin V5

### Describe the bug?

使用从adapter中导出的dialog创建出来的样式主题色没有应用上
![image](https://github.com/user-attachments/assets/3657f689-97a1-43ef-b5cb-bf01646c7d6a)
![image](https://github.com/user-attachments/assets/f034fc7d-8ec6-4ee6-9799-15bda0222913)
可以看到主题相关颜色没有应用上,表现在hover时取消按钮的颜色
下面是正常的样式
![image](https://github.com/user-attachments/assets/c3de1295-a195-4acb-9351-71b9f6f0d770)

### Reproduction

/

### System Info

```shell
最新版本
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
这个看起来是 http://localhost:5888/demos/naive 的默认做法，本身就是这样子。

**Comment by anncwb** [comment]
naive 的问题，https://github.com/tusen-ai/naive-ui/issues/3180
