### ISSUE TITLE
FEATURE: 请问后期会添加系统管理/用户管理/权限管理等模块吗？

### ISSUE THREAD

**Issue by tjwangws** [vbenjs/vue-vben-admin#4638]
### Version

Vben Admin V5

### Description

您好作者，请问后期会添加系统管理/用户管理/权限管理等模块吗？

### Proposed Solution

咱们的系统界面特别漂亮，但是我想在后台添加系统管理/用户管理/权限管理等模块，这样可以更方便的管理。

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by anncwb** [comment]
duplicate #4287
