### ISSUE TITLE
Bug: ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  vue@catalog: isn't supported by any available resolver.

### ISSUE THREAD

**Issue by KuanyaLiao** [vbenjs/vue-vben-admin#4641]
### Version

Vben Admin V5

### Describe the bug?

pnpm install 报错

### Reproduction

D:\vue-vben-admin\docs:
 ERR_PNPM_SPEC_NOT_SUPPORTED_BY_ANY_RESOLVER  vue@catalog: isn't supported by any available resolver.

### System Info

```shell
pnpm -v 9.5.0
node -v v22.4.1
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
尝试用node20版本试试
