### ISSUE TITLE
Bug:  能否告知 packages/locales  在不同的包下怎么共享的多语言 

### ISSUE THREAD

**Issue by wangz-code** [vbenjs/vue-vben-admin#4643]
### Version

Vben Admin V5

### Describe the bug?

例如 packages 下 新建一个包  比如 @my-naive 始终无法使用 @vben/locales  内的多语言数据  (packages/locales 内配置的) 

但是我在 @vben/constants 下就能正常使用 @vben/locales 配置的全局多语言    这个需要在哪里修改吗? 

### Reproduction

希望告知下

### System Info

```shell
希望告知下
```

### Relevant log output

```shell
希望告知下
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by pzzyf** [comment]
@vben/locales不是主仓下的包，你需要把它下到你子仓建的仓库@my-naive下

**Comment by wangz-code** [comment]
> @vben/locales不是主仓下的包，你需要把它下到你子仓建的仓库@my-naive下

感谢答复,  你这样操作相当于又copy了一份语言包, 还要去app立面监听语言切换; 

我看源码 vben 设计就是使用  @vben/locales 全局管理 i18n,   比如 app/A项目 ,  app/B项目 
子项目根本上用的还是 @vben/locales ,   i18n就在这个包初始化的

最终项目的语言包  = 主包+子包,  如果key相同子包可以覆盖主包key          

其实直接用也是能用,就是 dev下显示有问题,  build 之后则一切正常,     我想知道的是  为什么在 @vben/xxx 包内用  @vben/locales 时 dev就能正常,  我自己建@my-naive就不行,

**Comment by pzzyf** [comment]
> > @vben/locales不是主仓下的包，你需要把它下到你子仓建的仓库@my-naive下
> 
> 感谢答复, 你这样操作相当于又copy了一份语言包, 还要去app立面监听语言切换;
> 
> 我看源码 vben 设计就是使用 @vben/locales 全局管理 i18n, 比如 app/A项目 , app/B项目 子项目根本上用的还是 @vben/locales , i18n就在这个包初始化的
> 
> 最终项目的语言包 = 主包+子包, 如果key相同子包可以覆盖主包key
> 
> 其实直接用也是能用,就是 dev下显示有问题, build 之后则一切正常, 我想知道的是 为什么在 @vben/xxx 包内用 @vben/locales 时 dev就能正常, 我自己建@my-naive就不行,

我在@vben/constants是不能直接使用了，主仓下的下的共享的包全是配置类的（internal），子仓使用非主仓下载的过的依赖包本身就是需要去下载的，
还要去app立面监听语言切换，这句话我不知道什么意思

**Comment by pzzyf** [comment]
> 不清楚你的 @my-naive 写法，@vben/locales 主要是给多 apps 复用，或者给 pacakges/ 内的包使用的，你上面说的逻辑没错，所以可能是代码错了。可能需要提供更多的细节来看看才知道

我猜@my-naive是放到根目录下面了

**Comment by wangz-code** [comment]
> 不清楚你的 @my-naive 写法，@vben/locales 主要是给多 apps 复用，或者给 pacakges/ 内的包使用的，你上面说的逻辑没错，所以可能是代码错了。可能需要提供更多的细节来看看才知道

找到原因了, 跟框架没关系,  原因是我的子项目使用了 unplugin-auto-import 自动导入api,  我顺手吧@my-naive  中一些公用的弹窗放进去了,  貌似只要加了 就会导致@vben/locales 中的i18n 就会变成 undefined    ,

**Comment by wangz-code** [comment]
主要是  vite.config.mts   
问题复现仓库   https://github.com/wangz-code/vue-vben-admin-locales/commit/0997b4bdec3e830dc65fa53096f4ab7773f0a5d0

https://github.com/wangz-code/vue-vben-admin-locales

我不确定是不是, 框架不允许这样使用
