### ISSUE TITLE
Bug: safari浏览器下在登陆页点击注册再返回后输入框消失

### ISSUE THREAD

**Issue by AALiujiajun** [vbenjs/vue-vben-admin#4646]
### Version

Vben Admin V2

### Describe the bug?

safari浏览器下在登陆页点击注册再返回后输入框消失
<img width="1284" alt="image" src="https://github.com/user-attachments/assets/5bf14e4c-7b9e-41b2-86f4-73d362298323">

### Reproduction

https://v2.vben.pro/#/login?redirect=/dashboard

### System Info

```shell
macOS 15.0.1
safari版本18.0.1 (20619.1.26.31.7)
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by tuin77** [comment]
奇怪我这边没复现

**Comment by AALiujiajun** [comment]
> 奇怪我这边没复现
你看看有没有把苹果系统和浏览器升级到最新 

https://github.com/user-attachments/assets/522fe71a-544a-4e02-92e7-47485648d871
