### ISSUE TITLE
Bug: build报错

### ISSUE THREAD

**Issue by TNGsimon** [vbenjs/vue-vben-admin#4664]
### Version

Vben Admin V5

### Describe the bug?

**dev可以正常运行，但是run build都不行，在外面和在app里面都不行，turbo日志如下：**
> @vben/web-antd@5.4.0 build E:\qianduan\GIT_公网\vben5\vue-vben-admin\apps\web-antd
> pnpm vite build --mode production

[33mThe CJS build of Vite's Node API is deprecated. See https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.[39m
[36mvite v5.4.9 [32mbuilding for production...[36m[39m
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

[Failed to load PostCSS config: Failed to load PostCSS config (searchPath: E:/qianduan/GIT_公网/vben5/vue-vben-admin/apps/web-antd): [Error] Loading PostCSS Plugin failed: Cannot find module 'cssnano'
Require stack:
- E:\qianduan\GIT_公网\vben5\vue-vben-admin\apps\web-antd\postcss.config.mjs

(@E:\qianduan\GIT_公网\vben5\vue-vben-admin\apps\web-antd\postcss.config.mjs)
Error: Loading PostCSS Plugin failed: Cannot find module 'cssnano'
Require stack:
- E:\qianduan\GIT_公网\vben5\vue-vben-admin\apps\web-antd\postcss.config.mjs

(@E:\qianduan\GIT_公网\vben5\vue-vben-admin\apps\web-antd\postcss.config.mjs)
    at load (file:///E:/qianduan/GIT_%E5%85%AC%E7%BD%91/vben5/vue-vben-admin/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.5_less@4.2.0_sass@1.79.5_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:33631:11)
    at file:///E:/qianduan/GIT_%E5%85%AC%E7%BD%91/vben5/vue-vben-admin/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.5_less@4.2.0_sass@1.79.5_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:33656:16
    at Array.map (<anonymous>)
    at plugins (file:///E:/qianduan/GIT_%E5%85%AC%E7%BD%91/vben5/vue-vben-admin/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.5_less@4.2.0_sass@1.79.5_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:33655:8)
    at processResult (file:///E:/qianduan/GIT_%E5%85%AC%E7%BD%91/vben5/vue-vben-admin/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.5_less@4.2.0_sass@1.79.5_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:33725:14)
    at file:///E:/qianduan/GIT_%E5%85%AC%E7%BD%91/vben5/vue-vben-admin/node_modules/.pnpm/vite@5.4.9_@types+node@22.7.5_less@4.2.0_sass@1.79.5_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:33855:14]

Node.js v20.15.1
 ELIFECYCLE  Command failed with exit code 1.

### Reproduction

无

### System Info

```shell
System:
    OS: windows 10
    Node: 20.15.1
    npm: 10.7.0
    pnpm: 9.12.1
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
请看看文档，路径不要有中文。然后重新reinstall下在执行

**Comment by TNGsimon** [comment]
多谢，可以了，但是run dev就没问题Q_Q
