### ISSUE TITLE
Bug: addResponseInterceptor拦截器抛出error类型错误

### ISSUE THREAD

**Issue by swamp-y** [vbenjs/vue-vben-admin#4667]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/de775644-5032-4891-ab0b-6d0239b410a2)
![image](https://github.com/user-attachments/assets/76027abe-3dd8-406f-9d0e-4e7df44f949c)

addResponseInterceptor 拦截器应通过Promise返回 response对象，否则后面的token过期处理authenticateResponseInterceptor函数，以及通用错误处理errorMessageResponseInterceptor中，回调参数error，将会得到string类型错误信息 =》 `Error ${status}: ${msg}`，无法解构code，message进行自定义判断

### Reproduction

https://github.com/vbenjs/vue-vben-admin

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5700X3D 8-Core Processor
    Memory: 18.40 GB / 31.92 GB
  Binaries:
    Node: 20.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
你可以直接throw 一个对象，而不是error，具体看你业务需求

**Comment by anncwb** [comment]
正常逻辑你接口报错应该不会走 fulfilled 才对，应该会走默认的 rejected，所以你需要看看你的业务逻辑。目前示例代码是接口报错是不会进入 fulfilled逻辑，所以能直接拿到error对象。你的 PR 应该也是。你看看提供你的具体场景，后面我在详细看看吧。

**Comment by swamp-y** [comment]
1. status === 200 但是 code ===500这种，会命中fulfilled ，业务大多数是如此结构，但是直接throw new Error(),后面errorMessageResponseInterceptor处理函数中，error对象也只能拿到string，无法解构里面的code和messge进行自定义处理
2.  status === 200 && code === 401,这种情况，也会导致token过期处理函数无法解构code而命中不了过期处理逻辑
3. 刚从v2换到v5，这块就感觉不一样了 ^_^
