### ISSUE TITLE
FEATURE: form表单的示例能不能搞点稍微复杂点的，css小白

### ISSUE THREAD

**Issue by cbombonera** [vbenjs/vue-vben-admin#4676]
### Version

Vben Admin V5

### Description

看代码都是 外层 用grid 然后grid-cols-n 代表多少列
能不能出个这样的示例

使用useVbenForm 渲染from的时候
不是每行3列  也不是用span-3 合并

而是 有这样的场景
格子
第一行 5列 宽度均分 
第二行 3列 宽度均分
第三行 直接占满
第四行 6列 宽度也是均分

大概是这样的 pc端 我在一定情况下 可以让每行 col-12 col-12 
也可以让另外一行 col-6 col-6 col-6 col-6
因为我想满足一般的表单设计器的功能
不知道作者后续会推出表单设计器吗

类似bootstrap等的布局栅格

小白一个，用组件渲染实在写不出来
谢谢！！！

### Proposed Solution

同上

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by imdap** [comment]
这不是很简单吗  计算一下就行了  wrapperClass设置为grid-cols-30
按你的需求
6 6 6 6 6
10 10 10
30
5 5 5 5 5 5
基础列设置30   剩下的自己按布局分就行了 col-span-x

**Comment by cbombonera** [comment]
> 这不是很简单吗 计算一下就行了 wrapperClass设置为grid-cols-30 按你的需求 6 6 6 6 6 10 10 10 30 5 5 5 5 5 5 基础列设置30 剩下的自己按布局分就行了 col-span-x

你能用代码示例吗
我对tailwindcss 没搞过
    <div class="grid-30 grid">
      <div class="col-span-6"></div>
      <div class="col-span-6"></div>
      <div class="col-span-6"></div>
      <div class="col-span-6"></div>
      <div class="col-span-6"></div>
      <div class="col-span-10"></div>
      <div class="col-span-10"></div>
      <div class="col-span-10"></div>
    </div>
这样写 的话，col-span-10 也不是占33%

**Comment by vince292007** [comment]
看文档就行 https://tailwindcss.com/docs/grid-column

**Comment by mynetfan** [comment]
除了预置的grid-cols-12，你还可以定义更多。比如：
```
grid-cols-30: grid-template-columns: repeat(30, minmax(0, 1fr));
```
参见 https://tailwind.nodejs.cn/docs/grid-template-columns#-6
