### ISSUE TITLE
FEATURE: V5版本 ApiSelect 组件支持

### ISSUE THREAD

**Issue by youtao531** [vbenjs/vue-vben-admin#4682]
### Version

Vben Admin V5

### Description

请问作者 ApiSelect 组件有计划的开发周期吗

### Proposed Solution

期望作者提供 ApiSelect 组件，这个组件业务里还是高频使用的。

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by DesignHhuang** [comment]
是在form 中使用的那个 apiselect 么？

**Comment by youtao531** [comment]
这个目前有在开发吗，或者有没有开发的计划呢

**Comment by DesignHhuang** [comment]
> 这个目前有在开发吗，或者有没有开发的计划呢

目前我的思路是：可以自行将v2的挪过来用，在 packages 中添加一个新的UI库。如果有需要我这几天可以放个 PR 上去，但是不知道能不能被 merge 进去，因为不是用 shadcn 写的通用库。

**Comment by youtao531** [comment]
> > 这个目前有在开发吗，或者有没有开发的计划呢
> 
> 目前我的思路是：可以自行将v2的挪过来用，在 packages 中添加一个新的UI库。如果有需要我这几天可以放个 PR 上去，但是不知道能不能被 merge 进去，因为不是用 shadcn 写的通用库。

方便的话麻烦放个pr🙏🙏🙏，我这边本地集成下
