### ISSUE TITLE
Bug: antd button icon显示错位

### ISSUE THREAD

**Issue by Null404Nil** [vbenjs/vue-vben-admin#4685]
### Version

Vben Admin V5

### Describe the bug?

![微信截图_20241019171908](https://github.com/user-attachments/assets/689f5f33-6c15-4496-9c51-bcb69605c48a)
![微信截图_20241019171959](https://github.com/user-attachments/assets/99f0a86c-5c62-4edb-8a3e-0a1f4e63242c)

### Reproduction

```
import { MdiPlus } from '@vben/icons';

<Button @click="info">
  <template #icon>
    <MdiPlus />
  </template>
  信息
</Button>
```

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 7700 8-Core Processor
    Memory: 8.72 GB / 31.10 GB
  Binaries:
    Node: 22.8.0 - D:\develop\nodejs\node.EXE
    npm: 10.9.0 - D:\develop\nodejs\npm.CMD
    pnpm: 9.12.2 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (128.0.2739.67)
    Internet Explorer: 11.0.22621.3527
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
因为你用的不是ant design的图标，不会被ant deisng默认处理，可以给 icon加个样式，`<MdiPlus  class="anticon"/>` 既可以了
