### ISSUE TITLE
Bug: 表单联动中的校验错误

### ISSUE THREAD

**Issue by sw-Fang** [vbenjs/vue-vben-admin#4686]
### Version

Vben Admin V5

### Describe the bug?

在使用表单联动的校验规则时，如果直接进行formApi的validate()方法，校验规则不是对应列配置的规则。
![Snipaste_2024-10-19_17-28-52](https://github.com/user-attachments/assets/4dbcd3bb-e160-48fb-9f0f-3f693d0b1628)

当在密码输入框输入后，再删除刚才的输入，再点击确认按钮进行校验，此时提示的是表单联动中的校验规则。
![1729330317373](https://github.com/user-attachments/assets/af5dd808-1289-412d-b4cb-ac5ac0c9b4ce)

### Reproduction

下面是表单Schema中密码项：
{
      label: '密码', // 标签
      fieldName: 'password', // 字段名
      component: 'InputPassword', // 组件：需要在 #/adapter.ts内注册，并加上类型
      // 对应组件的参数
      componentProps: {
        placeholder: '请输入密码', // 占位符文本
        allowClear: true, // 	支持清除
        maxlength: 30, // 最大长度
        showCount: true, // 是否展示字数
      },
      // 表单联动
      dependencies: {
        // 只有指定的字段改变时，才会触发
        triggerFields: ['id'],
        if: (values) => !values.id,
        // 校验
        rules: (values) => {
          console.log('val:', values);

          return z
            .string()
            .min(6, '长度必须在 6 - 30 之间')
            .regex(/^\w{6,30}$/, '只能包含字母、数字、_');
        },
      },
    },

下面是模态框表单中，调用表单的校验方法：
const { valid } = await baseFormApi.validate(); // 校验表单
    if (valid) {

    }

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12600KF
    Memory: 36.19 GB / 63.84 GB
  Binaries:
    Node: 20.17.0 - D:\work\nodejs\node.EXE
    npm: 10.8.2 - D:\work\nodejs\npm.CMD
    pnpm: 9.7.0 - D:\work\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by gee1k** [comment]
使用 Zod 自定义校验以后，required 的 message 也应该使用 Zod 来配置，如下所示：
```ts
rules(values) {
    return z
      .string({
        required_error: '请输入密码',
      })
      .min(6, '长度必须在 6 - 30 之间')
      .regex(/^\w{6,30}$/, '只能包含字母、数字、_');
  }
````

**Comment by anncwb** [comment]
@gee1k 的方案是正确的，你也可以额外在外部加一个默认的 rules，不放在dependencies，也能正常。
```ts
dependencies:{rules:xxx}
// 默认
rules:xxx
```

**Comment by gee1k** [comment]
> @gee1k 的方案是正确的，你也可以额外在外部加一个默认的 rules，不放在dependencies，也能正常。
> 
> ```ts
> dependencies:{rules:xxx}
> // 跟dependencies同级，默认
> rules:xxx
> ```


dependencies 同级的 rules 是不生效的

![image](https://github.com/user-attachments/assets/9c1c09ba-03a1-4c23-b20e-99a01248ffd7)


![image](https://github.com/user-attachments/assets/6d416e40-8210-4431-81f5-852f5d830fd7)
