### ISSUE TITLE
Bug: Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

### ISSUE THREAD

**Issue by elkon028** [vbenjs/vue-vben-admin#4690]
### Version

Vben Admin V5

### Describe the bug?

升级 Sass 3.0.0 后, 报错 

Deprecation Warning: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

- internal/vite-config/src/config/application.ts
```js
- return `@import "@vben/styles/global";\n${content}`;
+ return `@use "@vben/styles/global" as *;\n${content}`;
```
- packages/styles/src/global/index.scss
```css
- @import '@vben-core/design/bem';
+ @use '@vben-core/design/bem' as *;
```

### Reproduction

如上

### System Info

```shell
all
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
最新代码应该已经降级sass版本了，等一些库内部的写法改了在同一调整。
