### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by crazyLajiao** [vbenjs/vue-vben-admin#4698]
### Version

Vben Admin V5

### Describe the bug?

执行pnpm dev:antd命令时，同样的版本在mac m1电脑上运行正常，放在centos服务器上就报了如下错误，问了gpt说：可能是 esbuild 版本不兼容或配置问题导致。有人遇到类似的问题吗？

the CJS build of Vite's Node API is deprecated. See https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
                                                                                                                                                                        22:57:08
  VITE v5.4.9  ready in 8767 ms

  ➜  Local:   [http://localhost:80/](http://localhost/)                                                                                                                                      22:57:08
  ➜  Network: [http://172.16.158.9:80/](http://172.16.158.9/)                                                                                                                                   22:57:08
  ➜  Vben Admin Docs: https://doc.vben.pro/                                                                                                                              22:57:08
  ➜  Nitro Mock Server: http://localhost:5320/api                                                                                                                    10:57:08 PM
  ➜  press h + enter to show help                                                                                                                                       22:57:08
                                                                                                                                                                        22:57:11
✔ Nitro Mock Server started.                                                                                                                                        10:57:11 PM
✔ Nitro Server built in 1619 ms                                                                                                                               nitro 10:57:12 PM
/home/howeking/hawk_eye/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:993
                  reject(new Error(error2));
                         ^

Error: The service was stopped
    at /home/howeking/hawk_eye/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:993:26
    at responseCallbacks.<computed> (/home/howeking/hawk_eye/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:622:9)
    at Socket.afterClose (/home/howeking/hawk_eye/node_modules/.pnpm/esbuild@0.21.5/node_modules/esbuild/lib/main.js:613:28)
    at Socket.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v21.7.3
/home/howeking/hawk_eye/apps/web-antd:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  hawk_eye@1.1.0 dev: `pnpm vite --mode development`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.

### Reproduction

https://github.com/vbenjs/vue-vben-admin （main分支）

### System Info

```shell
centos
node v21.7.3
pnpm v9.11.0
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
你应该增加内存看看，参考这个issue：https://github.com/evanw/esbuild/issues/320。这应该不是项目问题。
