### ISSUE TITLE
Docs: 如何在新窗口打开一个路由,而非打开一个外链

### ISSUE THREAD

**Issue by elkon028** [vbenjs/vue-vben-admin#4699]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [X] Confusing
- [ ] Not sure?

### Explain in Detail

如何在新窗口打开一个路由,而非打开一个外链

### Your Suggestion for Changes

建议设计一个菜单参数,可控制是否新窗口打开这个路由

**Comment by aitrx** [comment]
![image](https://github.com/user-attachments/assets/3aa132f9-f7d4-4317-8dce-c10bb0d30f4b)
应该有吧，这个算不

**Comment by mynetfan** [comment]
你将目标路由的完整URL作为外链地址是不是就可以达到你的目的了？

**Comment by elkon028** [comment]
> 你将目标路由的完整URL作为外链地址是不是就可以达到你的目的了？

如果支持选项式的,就不用写死地址不是更优雅吗??你这种就是做不出好产品来
