### ISSUE TITLE
Bug: pnpm install 报错：postinstall:   x missing tasks in project

### ISSUE THREAD

**Issue by mxian** [vbenjs/vue-vben-admin#4701]
### Version

Vben Admin V5

### Describe the bug?

拉的最新版本，5.4.2，本地install后提示：

postinstall$ turbo run stub
. postinstall: turbo 2.2.1
. postinstall:   x missing tasks in project
. postinstall: Error:   x could not find task `stub` in project
. postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1.

### Reproduction

pnpm install

### System Info

```shell
windows, node v20.16.0
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
检查看看你的代码，是不是改了什么。看起来是你动了文件内容
