### ISSUE TITLE
FEATURE: 请问适配麒麟系统吗

### ISSUE THREAD

**Issue by 1571312541** [vbenjs/vue-vben-admin#4703]
### Version

Vben Admin V5

### Description

请问适配麒麟系统吗

### Proposed Solution

请问适配麒麟系统吗

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by anncwb** [comment]
主要看你系统内的浏览器版本，能符合就行。
