### ISSUE TITLE
FEATURE: 可以将版本2.8.0在不重构的基础上直接升级到5.4.2吗？

### ISSUE THREAD

**Issue by kixuan** [vbenjs/vue-vben-admin#4705]
### Version

Vben Admin V2

### Description

因为想实现网站从http1.1升级到http2，必须要vite3.0.0以上才可以使用http2-proxy插件，所以想将整个前端框架升级至最新版

### Proposed Solution

将版本2.8.0在不重构的基础上直接升级到最新版

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [ ] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by anncwb** [comment]
旧项目不行，考虑自己升级vite就好了。

**Comment by kixuan** [comment]
> 旧项目不行，考虑自己升级vite就好了。

好的谢谢😀
