### ISSUE TITLE
Bug: V5.4.2 开发环境正常，生产环境登录报错，不知道是什么问题

### ISSUE THREAD

**Issue by youtao531** [vbenjs/vue-vben-admin#4714]
### Version

Vben Admin V5

### Describe the bug?

<img width="1789" alt="image" src="https://github.com/user-attachments/assets/f6b6f248-0b55-47c5-9517-e81ad3d284c1">

### Reproduction

V5.4.2 开发环境正常，生产环境登录报错，不知道是什么问题

### System Info

```shell
Chrome
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
看起来是你自己业务问题，这个字段应该是业务字段

**Comment by youtao531** [comment]
bootstrap 里面的，业务中没有这个相关的
