### ISSUE TITLE
Bug:  报错”内部服务器错误，请稍后再试“。

### ISSUE THREAD

**Issue by chengchengry** [vbenjs/vue-vben-admin#4718]
### Version

Vben Admin V5

### Describe the bug?

<img width="1213" alt="image" src="https://github.com/user-attachments/assets/e49b3ad6-da32-4810-9ec5-cfaa900f6e1e">

### Reproduction

不知道什么原因 ，起项目就报错了

### System Info

```shell
Chrome
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
mock服务没启动，尝试看看5320端口是否被占用，先kill掉在重新运行就可以了
