### ISSUE TITLE
Bug: 移动端响应式，useVbenModal弹窗可以居中显示

### ISSUE THREAD

**Issue by younland** [vbenjs/vue-vben-admin#4719]
### Version

Vben Admin V5

### Describe the bug?

当前的：
![image](https://github.com/user-attachments/assets/3edf3432-7a50-4e40-aeab-00babbc98136)
期望的：
![image](https://github.com/user-attachments/assets/0164c705-ac54-49b8-b655-b8f7b26cc34c)

### Reproduction

移动端响应式，useVbenModal弹窗可以居中显示

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 6800H with Radeon Graphics
    Memory: 19.71 GB / 39.25 GB
  Binaries:
    Node: 20.17.0 - D:\nvm\nodejs\node.EXE
    npm: 10.8.2 - D:\nvm\nodejs\npm.CMD
    pnpm: 9.11.0 - D:\nvm\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.65)
    Internet Explorer: 11.0.22621.3527
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
这个不是bug，移动端全屏显示效果是预期的
