### ISSUE TITLE
Bug: naive 查询表单渲染异常

### ISSUE THREAD

**Issue by RanMaoting** [vbenjs/vue-vben-admin#4721]
### Version

Vben Admin V5

### Describe the bug?

代码如下
```
import { NRadioButton } from 'naive-ui';
const [QueryForm] = useVbenForm({
  // 默认展开
  collapsed: false,
  layout: 'horizontal',
  commonConfig: {
    controlClass: 'h-full',
  },
  schema: [
    {
      component: 'RadioGroup',
      defaultValue: 1,
      fieldName: 'remark',
      label: 'remark',
      renderComponentContent: () => {
        return {
          default: () =>
            Array.from({ length: 5 }, (_, index) =>
              h(NRadioButton, { value: index, label: String(index) }),
            ),
        };
      },
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: false,
  // 按下回车时是否提交表单
  submitOnEnter: false,
  wrapperClass: 'grid-cols-1 md:grid-cols-4 lg:grid-cols-5',
});
```
![image](https://github.com/user-attachments/assets/61e0fe94-54f6-4545-a20f-39229ed7f5b7)
zheng正常渲染应该是这样的
![image](https://github.com/user-attachments/assets/bc28dcb5-4519-4ca2-aea7-19e2e0313bec)
但是实际上渲染是这样的
![image](https://github.com/user-attachments/assets/370f624f-d771-48d6-ac7e-ee88d819b11d)

### Reproduction

/

### System Info

```shell
/
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by RanMaoting** [comment]
对比了一下naive官网的代码通过表单渲染出来的group组件似乎少了样式,但是不知道怎么修复
![image](https://github.com/user-attachments/assets/372b26e5-2805-482c-98f3-846b1a6c2706)

**Comment by RanMaoting** [comment]
自定义渲染的情况下,默认值不会生效
![image](https://github.com/user-attachments/assets/9051724c-92f0-4e3c-b0ef-30de5306549d)

**Comment by mynetfan** [comment]
RadioGroup如果使用了按钮组样式（RadioButton），需要用Space包裹。具体请查看官方文档的演示代码.
