### ISSUE TITLE
Bug: The date picker component returns a value that differs from the set format.

### ISSUE THREAD

**Issue by Sma11X** [vbenjs/vue-vben-admin#4722]
### Version

Vben Admin V5

### Describe the bug?

https://github.com/vbenjs/vue-vben-admin/blob/862bbd83441fa2bd7d7c933eedba127b95389bdc/playground/src/views/examples/form/basic.vue#L310

When the `datePicker` value is set to `"dayjs('2022-01-01')"`, but returns as `"datePicker":"2021-12-31T16:00:00.000Z"`. It should return the correct date without the time.

The same problem as `timePicker`, it should return the correct time without date.

### Reproduction

https://www.vben.pro/#/examples/form/basic

### System Info

```shell
/
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
这是组件库的问题
