### ISSUE TITLE
Docs: Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

### ISSUE THREAD

**Issue by PeiHaigang** [vbenjs/vue-vben-admin#4723]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [X] Confusing
- [ ] Not sure?

### Explain in Detail

已经按照 #4605 和文档的要求修改了配置，但是还是报这个错误。
错误信息如下：
index-index-ONy1tjT1.mjs:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.

Nginx配置：
`

#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       3001;
        server_name  railway;

        location / {
			# 不缓存html，防止程序更新后缓存继续生效
		    if ($request_filename ~* .*\.(?:htm|html)$) {
			    add_header Cache-Control "private, no-store, no-cache, must-revalidate, proxy-revalidate";
			    access_log on;
		    }
            root   railway;
            index  index.html index.htm;
        }
    }
}
`

mime.types文件中的配置也按要求做了修改如下：
`
application/javascript                           js mjs;
`
但是还是报这个错误，请问是什么问题，谢谢。

### Your Suggestion for Changes

无

**Comment by vince292007** [comment]
最新代码已经调整了，你同步下就可以了。

**Comment by PeiHaigang** [comment]
> 最新代码已经调整了，你同步下就可以了。
确实可以了，拉取了最新代码，重新build后发布成功，非常感谢！

还有个小的问题给碰到的其他人提个醒，在之前的issue里面也有人问过，就是如果直接在web-ele下执行：pnpm build会报错，但是切换到根目录下执行：pnpm build:web-ele可以，而且这次成功后，再到web-ele目录下执行pnpm build 也没有问题了。
