### ISSUE TITLE
Bug: 拉取最新代码后，ts文件中出现错误信息：Parsing error: ESLint was configured to run on `<tsconfigRootDir>/src\store\auth.ts` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.node.json

### ISSUE THREAD

**Issue by PeiHaigang** [vbenjs/vue-vben-admin#4726]
### Version

Vben Admin V5

### Describe the bug?

完整错误信息：
Parsing error: ESLint was configured to run on `<tsconfigRootDir>/src\store\auth.ts` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.node.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/troubleshooting/typed-linting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-fileeslint

### Reproduction

打开/apps/web-ele/src/store/auth.ts 就可以看到错误信息
![image](https://github.com/user-attachments/assets/550afdc4-1778-49ed-8af6-c749c6913f78)

### System Info

```shell
vscode
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
没复现，你重装下依赖，重启vscode就可以了

**Comment by PeiHaigang** [comment]
> 没复现，你重装下依赖，重启vscode就可以了

重装依赖后错误消失，谢谢。

**Comment by PeiHaigang** [comment]
> > 没复现，你重装下依赖，重启vscode就可以了
> 
> 重装依赖后错误消失，谢谢。

重装依赖后还是过了会儿还是出现这个错误，后来我根据copilot提示在tsconfig.node.json中增加了对所有ts文件的包含后错误消失了，新的配置如下：
`
"include": ["vite.config.mts", "src/**/*.ts"]
`

**Comment by Ants24** [comment]
我使用workspace 打开的, 也是会出现这个错误, 重装后也是报一样的错误
