### ISSUE TITLE
FEATURE: 自定义工具栏位置

### ISSUE THREAD

**Issue by pzzyf** [vbenjs/vue-vben-admin#4737]
### Version

Vben Admin V5

### Description

![image](https://github.com/user-attachments/assets/c7911e0e-11f3-4f88-9383-35ecce24163e)
![image](https://github.com/user-attachments/assets/f5ff8aa4-6aad-44b8-a316-c026963fa171)

### Proposed Solution

不应该是和默认的一样限制在右上角吗

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by anncwb** [comment]
这个都自定义了，肯定样式也是需要自己控制
