### ISSUE TITLE
Bug: collapsedShowTitle 设置为true后，pc分辨率变化为手机端的时候，collapsedShowTitle 不生效

### ISSUE THREAD

**Issue by Jing1818** [vbenjs/vue-vben-admin#4744]
### Version

Vben Admin V5

### Describe the bug?

Bug: collapsedShowTitle 设置为true后，pc分辨率变化为手机端的时候，collapsedShowTitle 不生效

### Reproduction

Bug: collapsedShowTitle 设置为true后，pc分辨率变化为手机端的时候，collapsedShowTitle 不生效

### System Info

```shell
Bug: collapsedShowTitle 设置为true后，pc分辨率变化为手机端的时候，collapsedShowTitle 不生效
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [x] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
这个是预期的行为，移动端只会显示图标。
