### ISSUE TITLE
V5版本动态路由和静态路由结合

### ISSUE THREAD

**Issue by xqb0407** [vbenjs/vue-vben-admin#4761]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in Detail

如何把某个静态路由挂在返回的动态路由，例如有一个一级菜单用户管理，然后底下有一个动态的路由参数页面如，/user-detail,不在菜单中显示，如何把他挂载到用户管理下面，通过角色或者授权进行认证

### Your Suggestion for Changes

如何实现，这种

**Comment by xqb0407** [comment]
如果直接写在基本路由里面，相当于单独打开了一个新的BasicLayout布局。

**Comment by wangz-code** [comment]
/demo/user-detail
直接在子路由上配置一下就行了吧

```js
  /**
   * 当前激活的菜单，有时候不想激活现有菜单，需要激活父级菜单时使用
   */
  activePath?: string;
   /**
   * 当前路由的子级在菜单中不展现
   * @default false
   */
  hideChildrenInMenu?: boolean;
  /**
   * 当前路由在面包屑中不展现
   * @default false
   */
  hideInBreadcrumb?: boolean;
  /**
   * 当前路由在菜单中不展现
   * @default false
   */
  hideInMenu?: boolean;
  /**
   * 当前路由在标签页不展现
   * @default false
   */
  hideInTab?: boolean;



```

**Comment by anncwb** [comment]
通过上面的meta配置即可
