### ISSUE TITLE
Bug: typescript.ts 中设置  'perfectionist/sort-interfaces': 'off' 依旧会校验属性顺序

### ISSUE THREAD

**Issue by 1455668754** [vbenjs/vue-vben-admin#4762]
### Version

Vben Admin V5

### Describe the bug?

internal/lint-configs/eslint-config/src/configs/typescript.ts 中设置  'perfectionist/sort-interfaces': 'off' 后 执行pnpm install 
@vben/types中定义interface 依旧校验属性顺序，eslint配置未生效

### Reproduction

![企业微信截图_17301931514689](https://github.com/user-attachments/assets/33e506ab-d6e5-4611-a117-866fffdc31dd)
![image](https://github.com/user-attachments/assets/912427e1-0e6e-45ff-9273-7cb4a39a7ed2)

### System Info

```shell
dev
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
你应该在 perfectionist.ts 更改，而且更改后需要重启IDE

**Comment by 1455668754** [comment]
ok 好的 我试试 感谢大佬

**Comment by 1455668754** [comment]
有效 感谢大佬

**Comment by 1455668754** [comment]
![image](https://github.com/user-attachments/assets/f9e46b2e-a799-4e8e-8c18-60e74f570682)

![image](https://github.com/user-attachments/assets/55880050-f62c-4a04-8603-32d55a0de0b0)
按照您说的方式增加了后 属性排序校验不报了 但是 这个文件的perfectionistPlugin.configs['recommended-natural']报属性问题了 @anncwb
