### ISSUE TITLE
Bug: 后端返回 menu 时，无法使一级菜单作为组件

### ISSUE THREAD

**Issue by kkfive** [vbenjs/vue-vben-admin#4763]
### Version

Vben Admin V5

### Describe the bug?

我期望某个组件作为一级菜单，而不是作为某个菜单的展开现，当接口返回 component:BasicLayout 时，此时菜单是可以显示的，但内容丢失
```json
{
  "code": 0,
  "error": null,
  "message": "ok",
  "data": [
    {
      "meta": {
        "title": "分析",
        "order": 1,
        "icon": "lucide:area-chart"
      },
      "component": "BasicLayout",
      "name": "analytics",
      "path": "/analytics",
      "parentId": 1,
      "id": 17
    }
  ]
}
```
![20241029194517WH9RD7nf001146](https://github.com/user-attachments/assets/8b171e79-a1cd-4f37-be00-675328455e7e)

当我将 component 设置为组件地址时，页面是可以展示的，但 menu 消失了

```json
{
  "code": 0,
  "error": null,
  "message": "ok",
  "data": [
    {
      "meta": {
        "title": "分析",
        "order": 1,
        "icon": "lucide:area-chart"
      },
      "component": "/dashboard/analytics/index",
      "name": "analytics",
      "path": "/analytics",
      "parentId": 1,
      "id": 17
    }
  ]
}
```

![202410291947147wzOxXAT001148](https://github.com/user-attachments/assets/6b38550c-84c1-4b31-85bf-4b9c7c9b66c3)

### Reproduction

将路由模式调整为后端返回，数据使用上述提供的数据

### System Info

```shell
System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 97.61 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.0 - ~/.volta/tools/image/node/20.18.0/bin/node
    Yarn: 4.4.1-git.20240825.hash-b2f315f6 - ~/.volta/tools/image/yarn/4.4.1-git.20240825.hash-b2f315f6/bin/yarn
    npm: 10.8.2 - ~/.volta/tools/image/node/20.18.0/bin/npm
    pnpm: 9.12.1 - ~/.volta/tools/image/pnpm/9.12.1/bin/pnpm
    bun: 1.1.33 - /opt/homebrew/bin/bun
  Browsers:
    Chrome: 130.0.6723.70
    Edge: 113.0.1774.57
    Safari: 18.0.1
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aonoa** [comment]
增加一个children 然后 父路由  hideChildrenInMenu
