### ISSUE TITLE
Bug: 表单组件默认值不正确

### ISSUE THREAD

**Issue by LGX93** [vbenjs/vue-vben-admin#4776]
### Version

Vben Admin V5

### Describe the bug?

例如： fieldName: payment.type 用对象来设置name，defaultValue，设置后不正确，要重新触发才正确。
设置了默认值：payment.type = 1
重新触发后值：payment: {type: 1}
![image](https://github.com/user-attachments/assets/d1d21350-e2c3-4302-87e0-4a1242b6ff71)
![image](https://github.com/user-attachments/assets/0bb3e2ac-092a-469a-a14f-35d692beb1eb)

### Reproduction

如上

### System Info

```shell
win10
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
目前不支持嵌套对象

**Comment by ChenWeihua123** [comment]
> 目前不支持嵌套对象

有计划支持吗
