### ISSUE TITLE
baseRequestClient与requestClient区别

### ISSUE THREAD

**Issue by 1455668754** [vbenjs/vue-vben-admin#4784]
### Documentation is

- [ ] Missing
- [X] Outdated
- [ ] Confusing
- [ ] Not sure?

### Explain in Detail

没有要预览的内容

### Your Suggestion for Changes

想请问大佬 
![image](https://github.com/user-attachments/assets/8aa0ee44-53a1-484e-b871-0ca41e0bd817)
 baseRequestClient与requestClient使用区别是什么

**Comment by anncwb** [comment]
baseRequestClient不会经过那些拦截器，如果这里用requestClient，还是会走一遍原来的错误逻辑。
