### ISSUE TITLE
Bug: 自定义全局Loading，效果不统一

### ISSUE THREAD

**Issue by lztbwlkj** [vbenjs/vue-vben-admin#4800]
### Version

Vben Admin V5

### Describe the bug?

自定义全局Loading，页面初始化渲染确实是生效了，但是点击左边菜单切换还显示的是系统自带的蓝色加载动画，导致效果不统一，这个有办法解决吗？
这是全局的：
![image](https://github.com/user-attachments/assets/01a75e91-802b-4dd6-b71f-a7bb01eb8ee8)
这是菜单切换的
![image](https://github.com/user-attachments/assets/3842c008-1d48-468e-afc9-ad4fdfceef46)

### Reproduction

自定义全局Loading，页面初始化渲染确实是生效了，但是点击左边菜单切换还显示的是系统自带的蓝色加载动画，导致效果不统一，这个有办法解决吗？

### System Info

```shell
System:
    OS: macOS 13.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 6.84 GB / 40.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/.volta/tools/image/node/20.17.0/bin/node
    npm: 10.8.2 - ~/.volta/tools/image/node/20.17.0/bin/npm
    pnpm: 9.11.0 - ~/.volta/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.70
    Safari: 18.0.1
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
里面那个是组件，调整loading组件就可以
