### ISSUE TITLE
Bug: Vs Code 开发时，经常报 “正在加载 IntelliSense 状态” ，同时CPU飚高且失去类型推断和代码提示

### ISSUE THREAD

**Issue by eamd-wq** [vbenjs/vue-vben-admin#4802]
### Version

Vben Admin V5

### Describe the bug?

排查了很久，可能是eslint规则的问题，但是最终还是没有找到具体原因；
打开项目开始写代码，刚开始正常，一段时间后：
![image](https://github.com/user-attachments/assets/5e323c61-b861-4343-9075-434c3f7b5a75)

同时编辑器非常卡顿，Vs Code的进程监视器也只能看到是项目占据了一定的CPU，正在检查我刚刚编辑的文件，并没有其他额外的提示;
此状态大约持续2-5分钟后会恢复正常

### Reproduction

没有改动任何重要配置

### System Info

```shell
Windows 11 ; Vs Code 1.95.1; Eslint插件v3.0.10; Vue - Official v2.1.10
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
这个因素很多，可能是你的插件导致，也可能是配置问题。暂时没法复现，可以帮忙排查看看

**Comment by wangjue666** [comment]
@eamd-wq 可以把vscode的插件都先暂时停用，然后把` .vscode/extensions.json` 这个文件中的插件都启用，试试看

**Comment by eamd-wq** [comment]
> @eamd-wq 可以把vscode的插件都先暂时停用，然后把` .vscode/extensions.json` 这个文件中的插件都启用，试试看

好的，我先照做试一段时间，如果再有复现我再来寻求帮助；感谢
我觉得应该不会只有我遇到这个问题，所以我一定要解决它

**Comment by eamd-wq** [comment]
> @eamd-wq 可以把vscode的插件都先暂时停用，然后把` .vscode/extensions.json` 这个文件中的插件都启用，试试看

只能说有所改善，cpu还是会偶尔高，但是体感上没有之前那么严重；

现在会看到这个提示：ESLint-Validation took 12200ms
所以问题好像依然存在；我打算在空闲时重置我VS Code的云配置和本地配置，然后再使用一段时间再看看；

如有其他道友遇到同样问题，还请赐教

**Comment by eamd-wq** [comment]
备注：我的CPU是 intel i7 11代
