### ISSUE TITLE
Bug: 路由定义之 activePath 只能激活菜单, 但标签栏父标签未高亮(激活)

### ISSUE THREAD

**Issue by elkon028** [vbenjs/vue-vben-admin#4809]
### Version

Vben Admin V5

### Describe the bug?

```js
{
    component: BasicLayout,
    meta: {
      icon: 'fluent:device-meeting-room-remote-24-regular',
      order: 1000,
      title: '视频会议',
      badgeType: 'dot',
      hideInBreadcrumb: true,
      hideChildrenInMenu: true,
    },
    name: 'WebRTC',
    path: '/WebRTC',
    redirect: '/meeting',
    children: [
      {
        meta: {
          icon: 'fluent:device-meeting-room-remote-24-regular',
          title: '视频会议',
        },
        name: 'Meeting',
        path: '/meeting',
        component: () => import('#/views/meeting/index.vue'),
      },
      {
        meta: {
          icon: 'fluent:device-meeting-room-remote-24-regular',
          title: '进入会议',
          hideInTab: true,
          activePath: '/meeting',
        },
        name: 'MeetingRoom',
        path: '/meeting/room',
        component: () => import('#/views/meeting/room.vue'),
      },
    ],
  }
```

<img width="1535" alt="image" src="https://github.com/user-attachments/assets/74f93b98-5d97-47c0-ba5a-aa392fa3b6cf">

<img width="713" alt="image" src="https://github.com/user-attachments/assets/63b345e5-a448-41cd-a9bd-ead59c2a7e52">

### Reproduction

NULL

### System Info

```shell
ALL
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
文档中对于activePath的说明是“用于配置当前激活的菜单，有时候页面没有显示在菜单内，需要激活父级菜单时使用”，从未提及activePath也会对tab有效。
你定义了hideInTab，这个路由就不会出现在tab中

**Comment by elkon028** [comment]
> 文档中对于activePath的说明是“用于配置当前激活的菜单，有时候页面没有显示在菜单内，需要激活父级菜单时使用”，从未提及activePath也会对tab有效。 你定义了hideInTab，这个路由就不会出现在tab中

兄弟,那么按逻辑来讲,是否应该激活标签栏呢,所以你的逻辑是,文档没有提及的功能都不应该有?

**Comment by anncwb** [comment]
这个应该是预期的，路由也会有自己的tab标签，这个应该不会去支持了。
