### ISSUE TITLE
FEATURE: 能否新增配置项->左侧菜单Theme

### ISSUE THREAD

**Issue by elkon028** [vbenjs/vue-vben-admin#4810]
### Version

Vben Admin V5

### Description

能否新增配置项->左侧菜单Theme, 比如
type menuTheme = 'dark' | 'light' | null

menuTheme 为 'dark' | 'light' 时, 则菜单Theme为设定值, 否则跟随全局Theme

**Comment by vince292007** [comment]
配置内的 `theme.semiDarkSidebar`就是了
