### ISSUE TITLE
FEATURE: Iconify在线图标如何在内网中使用，有解决办法吗，可以的话能否提供文档说明

### ISSUE THREAD

**Issue by zwtvip** [vbenjs/vue-vben-admin#4815]
### Version

Vben Admin V5

### Description

内网无法使用Iconify在线图标

### Proposed Solution

内网无法使用Iconify在线图标，期望大佬提供思路

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by mynetfan** [comment]
添加依赖
```
pnpn add @iconify/vue @iconify/json
```
根据自己的需要注册图标集
```
import ep from '@iconify/json/json/ep.json';  // 这里可以引入更多的图标集
import { addCollection } from '@iconify/vue';
addCollection(ep);  // 注册引入的图标集
```
使用离线图标
```
<script setup>
import { Icon } from '@iconify/vue';
</script>

<template>
<!-- 此处icon中的图标集必须已经提前注册过 -->
<Icon icon="ep:apple" />
</template>
```

**Comment by zwtvip** [comment]
@mynetfan 好的，我试下，感谢大佬的解答
