### ISSUE TITLE
Bug: vben的Form、Vxe Table 组件，切换标签页后数据不会被保留。

### ISSUE THREAD

**Issue by MoncyJa** [vbenjs/vue-vben-admin#4816]
### Version

Vben Admin V5

### Describe the bug?

通过useVbenForm和useVbenVxeGrid实例化出来的组件，在切换标签页后表单的数据会被清空，表格的分页也会被重置为第一页。是否可以通过缓存的方式在切换页签后将数据带回来，以达到 vue-router 的 keep-alive 效果。

### Reproduction

https://www.vben.pro/#/examples/vxe-table/form

### System Info

```shell
MacOS,Chromium Engine Version 130.0.6723.92
```

### Validations

- [x] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
你需要开页面keep-alive缓存，跟组件没关系
