### ISSUE TITLE
页面渲染速度很慢

### ISSUE THREAD

**Issue by lq9958** [vbenjs/vue-vben-admin#4818]
当前框架版本： v5.4.3

刚开始以为没有开缓存，后来发现是开了的，关闭动画过渡页面渲染依旧很慢，但是看了官网的例子发现页面加载速度很快啊，我页面加载的数据量也不大，但就是渲染速度特别慢，实在想不到该如何优化了，有大佬可以指点一下吗？

下方展示是开了动画过渡的渲染速度

https://github.com/user-attachments/assets/e331b652-8cdc-4246-b86c-32a04517a2f1

**Comment by mynetfan** [comment]
是生产环境还是开发环境？

**Comment by lq9958** [comment]
> 是生产环境还是开发环境？

开发环境和生产环境下都是这样
