### ISSUE TITLE
Bug: token过期后会死循环

### ISSUE THREAD

**Issue by lovelyJason** [vbenjs/vue-vben-admin#4826]
### Version

Vben Admin V5

### Describe the bug?

#3945 

![image](https://github.com/user-attachments/assets/62bafa03-a98c-4fb3-9a23-cb6a7d957c3c)

跟这个问题一模一样，我后端返回来http状态码为200，data.code为401时会，在响应拦截器中
```js
  client.addResponseInterceptor(
    errorMessageResponseInterceptor((msg: string, error) => {
      // 这里可以根据业务进行定制,你可以拿到 error 内的信息进行定制化处理，根据不同的 code 做不同的提示，而不是直接使用 message.error 提示 msg
      // 当前mock接口返回的错误字段是 error 或者 message
      const responseData = error?.response?.data ?? {};
      const errorMessage = responseData?.error ?? responseData?.message ?? '';
      // 如果没有错误信息，则会根据状态码进行提示
      message.error(errorMessage || msg);
      if (responseData .code === 401) {
         window.location.hash = '/auth/login'
      }
    }),
  );
```

然后会无限死循环，在登录页一直调getinfo接口

我如果不改代码的话，默认这个token过期刷新页面后页面直接空白了，啥也没有。这个bug还在

### Reproduction

暂无

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700
    Memory: 27.26 GB / 63.70 GB
  Binaries:
    Node: 20.15.0 - ~\AppData\Local\fnm_multishells\25468_1729582803829\node.EXE
    npm: 10.7.0 - ~\AppData\Local\fnm_multishells\25468_1729582803829\npm.CMD
    pnpm: 9.12.2 - ~\AppData\Local\fnm_multishells\25468_1729582803829\pnpm.CMD
  Browsers:
    Edge: Chromium (128.0.2739.63)
    Internet Explorer: 11.0.19041.4355
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
你应该参考 status=401时的处理，这个问题已经修复了。

**Comment by lovelyJason** [comment]
> 你应该参考 status=401时的处理，这个问题已经修复了。

![image](https://github.com/user-attachments/assets/960d0411-1eec-43c0-882d-b4889accdfd8)

你说的是这地方吧，也不对哈， 我是5.4.2的版本，看了你github最新代码， 这个东西有一点问题。就是接口请求的http状态码所有全部是200， 当token过期时返回的{code: "401", msg: "token is expired"}是在response.data里面。我即使改了后端把http状态码和data.code都变为401，还是不得行哈，页面会空白，控制台报{code: 401, msg: "token is expired"}路由注册失败。这个问题还是在的哈

**Comment by lovelyJason** [comment]
> > 你应该参考 status=401时的处理，这个问题已经修复了。
> 
> ![image](https://private-user-images.githubusercontent.com/50656459/383784467-960d0411-1eec-43c0-882d-b4889accdfd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NDYwNDEsIm5iZiI6MTczMDk0NTc0MSwicGF0aCI6Ii81MDY1NjQ1OS8zODM3ODQ0NjctOTYwZDA0MTEtMWVlYy00M2MwLTg4MmQtYjQ4ODlhY2NkZmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDAyMTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NDBhMjg3ZGE2MzA2MjE1NjM3ZmY2OTBjYmVjZjZkMDdlNmI1ODZiZTgxYWZlMjcyZTZkYTgxOTI2Yzc1NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ralbu202-E3Lgz48StjKf_Rx56Rrsv2OXuEry5KvAUE)
> 
> 你说的是这地方吧，也不对哈， 我是5.4.2的版本，看了你github最新代码， 这个东西有一点问题。就是接口请求的http状态码所有全部是200， 当token过期时返回的{code: "401", msg: "token is expired"}是在response.data里面。我即使改了后端把http状态码和data.code都变为401，还是不得行哈，页面会空白，控制台报{code: 401, msg: "token is expired"}路由注册失败。这个问题还是在的哈
> 
> 我把
> 
> ```js
>       // 如果不是 401 错误，直接抛出异常
>       if (response?.status !== 401) {
>         throw error;
>       }
> ```
> 
> 改成了
> 
> ```js
>       // 如果不是 401 错误，直接抛出异常
>       if (response?.data.code!== 401) {
>         throw error;
>       }
> ```
> 
> 再页面上点击接口请求的按钮，报401，此时系统无任何回馈，我认为应该是要做两件事：1.清空localstorage里面的vben-web-antd-5.4.2-dev-core-access，这里存储着accessTOken。 2：重定向到/auth/login页面
> 
> 然后紧接着一个问题就是此时刷新页面，刚才还能看到界面，现在全屏空白，进度条一直在转
> 
> ![image](https://private-user-images.githubusercontent.com/50656459/383785967-f2fb4166-1113-46fc-8ad4-e9281d67c587.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NDYwNDEsIm5iZiI6MTczMDk0NTc0MSwicGF0aCI6Ii81MDY1NjQ1OS8zODM3ODU5NjctZjJmYjQxNjYtMTExMy00NmZjLThhZDQtZTkyODFkNjdjNTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDAyMTU0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNWZkYjdjNTg4NmM3MDhiNTU5MWQ3NWNiM2NhZGVlOGJmNDBkOWZiMGE4YjljNDYxNmM5ZGI3MjNiMjhkZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LlLmOat6Xh-EjblZU7CDPoW_qgrVCmWWcWyBPvZbg1M)
> 
> dansh但是我又不敢在这里面直接window.location.href = '/auth/login'，经测试，在login页一直无限循环调getinfo接口，很是头疼

同时也会无限循环调logout接口，然后logout返回http200， {code: 401}， 这里抛错了，又继续无限循环调logout

**Comment by lovelyJason** [comment]
而且另外提一嘴，对于不需要token过期重试的行为时，如图片所示，这段代码要注释掉，另外，在拦截器里得把token清空掉，pinia的插件会连带着把localsrorage里面的token也清掉，这样刷新页面才不会出问题

![image](https://github.com/user-attachments/assets/d3232faa-f24f-416f-be4a-fbffcd077e7f)

**Comment by lovelyJason** [comment]
> 是的，我也遇到了这个情况。 <img alt="Snipaste_2024-11-07_11-55-54" width="1277" src="https://private-user-images.githubusercontent.com/102506714/383808451-b81ca76e-264f-42e9-aca2-02bce224cd91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMzU0NjMsIm5iZiI6MTczMTAzNTE2MywicGF0aCI6Ii8xMDI1MDY3MTQvMzgzODA4NDUxLWI4MWNhNzZlLTI2NGYtNDJlOS1hY2EyLTAyYmNlMjI0Y2Q5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOFQwMzA2MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTNmNzE1MzljMzEwMDAxZTdiZDM4YWE5YTU3ODY4ODMzYTVjYjUzZmVkOGYwNTdhOTJlZDk0ZTk2YWJjZWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HoDyn3pB7EXhFCxV9X3VfP1GHnC3Ytyl0sMjBy8ciBM">

哎，所以就不懂，这个最新代码bug本来就是存在的，作者为啥要关闭这个issue
