### ISSUE TITLE
开发环境 console.log()无法输出日志，不知道怎么开启功能

### ISSUE THREAD

**Issue by zhangzhiyong-ay** [vbenjs/vue-vben-admin#4828]
开发环境 console.log()无法输出日志，不知道怎么开启功能。vite-config/src/config/application.ts文件中esbuild已经注释掉了，还是不行。
![image](https://github.com/user-attachments/assets/27b40214-eb87-4602-ba5d-64e70c91ac16)

**Comment by anncwb** [comment]
这个不可能的，只能是你写错了，或者放错位置了。
