### ISSUE TITLE
Bug: form在弹窗中使用时无法正确触发校验

### ISSUE THREAD

**Issue by RanMaoting** [vbenjs/vue-vben-admin#4837]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/0d0db829-c42a-438a-a48f-ab2adb644f8d)
直接使用表单内部的提交按钮时会先触发校验,校验不通过时不会提交表单,这个表现是符合预期的
![image](https://github.com/user-attachments/assets/b194bda4-dcde-463b-93eb-d04fcb17d3a7)
但是在使用弹窗时,如果使用formApi.submitForm来触发表单的提交行为则不管校验是否通过都会导致提交表单

### Reproduction

/

### System Info

```shell
/
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by youtao531** [comment]
贴代码，应该是写错了。我这边是可以正常校验的。

**Comment by RanMaoting** [comment]
```
<script lang="ts" setup>
import { useVbenModal } from '@vben/common-ui';

import { useVbenForm } from '#/adapter/form';

defineOptions({
  name: 'FormModelDemo',
});

function onSubmit(values: Record<string, any>) {
  console.log(values);
}

const [Form, formApi] = useVbenForm({
  handleSubmit: onSubmit,
  schema: [
    {
      component: 'Input',
      componentProps: {
        placeholder: '请输入',
      },
      fieldName: 'field1',
      label: '字段1',
      rules: 'required',
    },
    {
      component: 'Input',
      componentProps: {
        placeholder: '请输入',
      },
      fieldName: 'field2',
      label: '字段2',
      rules: 'required',
    },
    {
      component: 'Select',
      componentProps: {
        options: [
          { label: '选项1', value: '1' },
          { label: '选项2', value: '2' },
        ],
        placeholder: '请输入',
      },
      fieldName: 'field3',
      label: '字段3',
      rules: 'required',
    },
  ],
  showDefaultActions: false,
});

const [Modal, modalApi] = useVbenModal({
  fullscreenButton: false,
  onCancel() {
    modalApi.close();
  },
  onConfirm: async () => {
    await formApi.submitForm();
  },
  onOpenChange(isOpen: boolean) {
    if (isOpen) {
      const { values } = modalApi.getData<Record<string, any>>();
      if (values) {
        formApi.setValues(values);
      }
    }
  },
  title: '内嵌表单示例',
});
</script>
<template>
  <Modal>
    <Form />
  </Modal>
</template>
```
直接使用演示环境的代码,点击确认按钮,查看log输出,可以看到校验未通过,但是函数被执行了
![image](https://github.com/user-attachments/assets/1b61562b-a200-4929-8945-2ba90e31a973)
![image](https://github.com/user-attachments/assets/e46d4dbb-ecb9-49a4-9d4c-cbd83e6f6a85)

**Comment by youtao531** [comment]
我的方法是在 onSubmit 方法内添加
```ts
 const validateResult = await formApi.validate(values);
  if (!validateResult.valid) {
    return;
  }
```

**Comment by RanMaoting** [comment]
这样做是可以做到,但是行为和直接使用表单里面的按钮就不一致, 而且submitForm在内部也进行了校验, 感觉没必要进行多次校验, 或许在submitForm可以加一个参数来控制是否进行校验,当然 一切以作者为准:)

**Comment by anncwb** [comment]
新增了一个 `validateAndSubmitForm`函数，拉取最新代码即可。
