### ISSUE TITLE
Bug: Vben Drawer 抽屉的header属性无效

### ISSUE THREAD

**Issue by sw-Fang** [vbenjs/vue-vben-admin#4839]
### Version

Vben Admin V5

### Describe the bug?

使用Vben的Drawer时，配置header属性无法生效。
![1](https://github.com/user-attachments/assets/77745e6d-a110-4cf6-be8f-be21e1c7b1df)

### Reproduction

// 抽屉 - 配置
const [Drawer, drawerApi] = useVbenDrawer({
  title: '设置',
  // header: false,
});

### System Info

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
    Memory: 4.57 GB / 23.87 GB
  Binaries:
    Node: 20.18.0 - D:\work\nodejs\node.EXE
    npm: 10.8.2 - D:\work\nodejs\npm.CMD
    pnpm: 9.12.3 - D:\work\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (130.0.2849.56)
```

### Relevant log output

```shell
对象字面量只能指定已知属性，并且“header”不在类型“DrawerApiOptions”中。
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
这个`header`哪里来的，没有说有这个属性吧。

**Comment by anncwb** [comment]
最新代码，`headerClass:'hidden'` ，就可以了。
