### ISSUE TITLE
提问帖：VbenPinInput    button 禁用或者二次快速验证实现方案

### ISSUE THREAD

**Issue by tiandiweizun** [vbenjs/vue-vben-admin#4850]
### Version

Vben Admin V5

### Describe the bug?

手机号登录的时候，当输入的手机号不满足位数或者邮箱输入的格式错误的时候，手机号或者邮箱为VbenInput，而验证码为VbenPinInput，测试发现设置dependencies的disabled无效，而只能在handleSendCode再做一次验证，那么还有更加方便的办法吗，如果再做一次验证的话可以有简单的formapi.validatefield实现吗?能否贴上代码帮忙一下。

### Reproduction

const formSchema = computed((): VbenFormSchema[] => {
  return [
    {
      component: 'VbenInput',
      componentProps: {
        placeholder: 'example@example.com',
      },
      fieldName: 'email',
      label: $t('authentication.email'),
      rules: z
        .string()
        .min(1, { message: $t('authentication.emailTip') })
        .email($t('authentication.emailValidErrorTip')),
    },
    {
      component: 'VbenPinInput',
      componentProps: {
        disabled: true,
        handleSendCode: () => {
          message.success('发送验证码成功!');
        },
        maxTime: 10,
        createText: (countdown: number) => {
          const text =
            countdown > 0
              ? $t('authentication.sendText', [countdown])
              : $t('authentication.sendCode');
          return text;
        },
      },

### System Info

```shell
commitid:9cf0573921b45e71a9e82c70af8c34e7428020d4  ,提交于2024-11-09
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
dependencies 的 disabled 可以支持了。
