### ISSUE TITLE
关于eslint-config的问题请教

### ISSUE THREAD

**Issue by eamd-wq** [vbenjs/vue-vben-admin#4855]
### Version

Vben Admin V5

### Description

在 internal\lint-configs\eslint-config\src\configs\typescript.ts 文件中，languageOptions.project 为什么设置为'./tsconfig.*?.json'，为什么不直接设置为./tsconfig*.json，是会引起什么问题吗;
我在monorepo+git子模块配合使用时，子模块也初始化了husky，使用'./tsconfig.*?.json'提交代码会报错，报错的大致意思是我修改的ts文件没有包含在tsconfig.node.ts中，但我改的时业务文件这里不应该用tsconfig.node.json；后经过gpt和google，我尝试修改为./tsconfig*.json，子模块可以正常提交（这个子模块和从vben-ele复制，未做其他改动）

如果有兴趣协助我，我可以提供一个demo

### Proposed Solution

null

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by vince292007** [comment]
这里应该是eslint7版本的问题，eslint7版本，对monorepo的lint速度非常慢，加上这个就会快很多。可能升级eslint后没有删除。

**Comment by vince292007** [comment]
monorepo 应该需要改成 `./tsconfig.*.json`,否则在仓库内，代码应该会报错。

**Comment by eamd-wq** [comment]
> monorepo 应该需要改成 `./tsconfig.*.json`,否则在仓库内，代码应该会报错。

好的

**Comment by eamd-wq** [comment]
> 这里应该是eslint7版本的问题，eslint7版本，对monorepo的lint速度非常慢，加上这个就会快很多。可能升级eslint后没有删除。

你的意思是加上 `languageOptions.project` 后lint速度回快很多吗；我觉得我现在的lint速度很慢，提交commit需要很久，而且开发时vscode经常卡顿
