### ISSUE TITLE
Bug: element风格下在el-table中预览图片显示错乱

### ISSUE THREAD

**Issue by selectweilin** [vbenjs/vue-vben-admin#4861]
### Version

Vben Admin V5

### Describe the bug?

element风格下在el-table中预览图片显示错乱
![image](https://github.com/user-attachments/assets/2e739a6d-56b1-4c1c-a4a4-69c5b2cc5de8)

### Reproduction

`
 <Page title="房屋管理">
<ElTable :data="tableData" stripe v-loading="loading">
        <ElTable.TableColumn label="房屋图片">
          <template #default="scope">
            <ElImage
              v-if="scope.row.filepath && scope.row.filepath !== ''"
              :preview-src-list="[scope.row.filepath]"
              :src="scope.row.filepath"
              style="height: 40px"
            />
          </template>
        </ElTable.TableColumn>
</ElTable>
</Page>`

### System Info

```shell
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jeff-fe** [comment]
@selectweilin 这个问题是element-plus组件库的bug
