### ISSUE TITLE
提问帖：表单Form如何插入其他元素

### ISSUE THREAD

**Issue by tiandiweizun** [vbenjs/vue-vben-admin#4864]
### Version

Vben Admin V5

### Describe the bug?

在输入手机号发送验证码的进行注册的情况下，表单元素有 手机号、手机验证码、密码和确认密码，当满足某些特定情况下，需要弹出【点击的图像验证码】，其在手机验证码元素之后，在密码之前。 但是这个组件非Form表单组件，即无法在VbenFormSchema完成配置。有2个办法，一个是弹出做出Modal，这样就不需要在表单配置，二个是把这个表单拆成2个，即2个VbenFormSchema，中间再配置【点击的图像验证码】，方法2比较丑陋。有办法让所有 【点击的图像验证码】像表单元素一样展示吗？默认为隐藏，特殊时候显示。换句话说，表单里面可以增加图片等其他各种各样元素支持吗？比如，文生图应用，用户会在表单 Input里面输入话术，然后后端生成图片并展示， 用户再进行图片生成效果 评价（Input）与打分(Input)，最后再提交，或者说这类情况不适合使用表单实现。

### Reproduction

无

### System Info

```shell
无
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
参考自定义组件就行 https://www.vben.pro/#/examples/form/custom
