### ISSUE TITLE
Bug: vbenForm 中使用 editor 无法回车换行问题如何解决？

### ISSUE THREAD

**Issue by zxj176381** [vbenjs/vue-vben-admin#4865]
### Version

Vben Admin V5

### Describe the bug?

Bug: vbenForm 中使用 editor 无法回车换行问题如何解决？

### Reproduction

Bug: vbenForm 中使用 editor 无法回车换行问题如何解决？

### System Info

```shell
System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M2
    Memory: 83.09 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.11.0/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 9.12.3 - ~/.nvm/versions/node/v22.11.0/bin/pnpm
  Browsers:
    Safari: 18.1
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zxj176381** [comment]
我使用的 wangeditor 放在 vbenform 无法换行

**Comment by zxj176381** [comment]
单独拿出来放到网页中就可以回车换上了，这个我应该如何修复呢

**Comment by mynetfan** [comment]
已经提交了一个PR。如果没有被合并，你可以对照这个PR修改你本地的代码看看是否有效
