### ISSUE TITLE
Bug: 深色模式下，偏好复制设置、注销登录按钮无法点击

### ISSUE THREAD

**Issue by T-loml** [vbenjs/vue-vben-admin#4868]
### Version

Vben Admin V5

### Describe the bug?

深色模式下，偏好复制设置、注销登录按钮无法点击

### Reproduction

https://ele.vben.pro/#/workspace

### System Info

```shell
system
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
不是深色模式下无法点击这两个按钮，而是在没有修改偏好设置时才不能点击（默认配置就是深色模式）。
你随意修改一个配置就可以点了
