### ISSUE TITLE
Bug: 配置preferences文件中loginExpiredMode: 'modal',清除缓存之后，还是会出现登录不弹窗，直接跳到登录页

### ISSUE THREAD

**Issue by haioa** [vbenjs/vue-vben-admin#4869]
### Version

Vben Admin V5

### Describe the bug?

配置preferences文件中loginExpiredMode: 'modal',清除缓存之后，还是会出现登录不弹窗，直接跳到登录页

### Reproduction

  app: {
    name: import.meta.env.VITE_APP_TITLE,
    loginExpiredMode: 'modal',
    dynamicTitle: true,
    watermark: true,
  },

### System Info

```shell
win11
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
清除缓存肯定跳转登录页面的，现在只是接口401才会出现弹窗，出现弹窗刷新后，也是会跳转刷新页。
