### ISSUE TITLE
Bug: 怎么把app打包时所有js文件打包到一个js文件，所有css文件打包到一个css文件

### ISSUE THREAD

**Issue by lujiex** [vbenjs/vue-vben-admin#4874]
### Version

Vben Admin V5

### Describe the bug?

我改vite.config.mts文件的build选项不生效。后面改internal/vite-config/src/config/application.ts后虽然打包到一个文件了，但是部署后访问报错。
![5920ebce4d4a14b9171ff36cf6574031](https://github.com/user-attachments/assets/179470e1-d082-4f50-824c-bebe242e043b)
![ce9e377c6938737a919f210f211174e8](https://github.com/user-attachments/assets/661d81f4-aaed-4e2b-b0d4-4456f9234c8e)

### Reproduction

我改vite.config.mts文件的build选项不生效。后面改internal/vite-config/src/config/application.ts后虽然打包到一个文件了，但是部署后访问报错。

### System Info

```shell
System:
    OS: Linux 6.8 Ubuntu 22.04.5 LTS 22.04.5 LTS (Jammy Jellyfish)
    CPU: (16) x64 AMD Ryzen 9 7940HX with Radeon Graphics
    Memory: 5.39 GB / 15.57 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
    pnpm: 9.12.3 - ~/.nvm/versions/node/v20.17.0/bin/pnpm
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lujiex** [comment]
加错地方了，应该加在vite里面，
![image](https://github.com/user-attachments/assets/bf726a03-4b59-4057-8a6e-3716654a08a0)
现在可以打包了，
![image](https://github.com/user-attachments/assets/8f84f5c1-5f79-4247-ab95-56dd282a5ddd)
但是进首页时样式颜色不对。
![image](https://github.com/user-attachments/assets/4189be48-46a3-4602-8d9f-5987087271b9)

切换到暗黑模式再切换回来就正常了。
![image](https://github.com/user-attachments/assets/28bcefd2-aec4-497f-81c4-1ae2c98587d6)

**Comment by vince292007** [comment]
这个只能自己查看vite的配置，项目没有这种需求，所以也不会去调整。
