### ISSUE TITLE
FEATURE: 2.0版本及5.0版本文档界面优化建议

### ISSUE THREAD

**Issue by JACK-ZHANG-coming** [vbenjs/vue-vben-admin#4875]
### Version

Vben Admin V5

### Description

请问这两个文档界面是否可以统一一下，2.0版本官方文档上面顶部有个黄条着实不太好看，因为项目开发需要经常翻阅2.0文档，上面的黄条背景有些影响美观度，后面用新项目会考虑采用5.0版本，请问2.0版本的这个黄条背景是否可以给优化一下？

![image](https://github.com/user-attachments/assets/ff993858-f355-40bf-9a8a-8667dd1a5704)

### Proposed Solution

建议可以参考ant design官方文档，做一个下拉框
![image](https://github.com/user-attachments/assets/8ee0567f-88be-4158-a9bf-5b2651886aec)

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by vince292007** [comment]
目前2版本应该没有计划更新了，包括文档。
