### ISSUE TITLE
FEATURE: 抽离组件的弹框如何在一个页面引入多个抽离组件的弹框

### ISSUE THREAD

**Issue by haioa** [vbenjs/vue-vben-admin#4876]
### Version

Vben Admin V5

### Description

抽离组件的弹框如何在一个页面引入多个抽离组件的弹框

### Proposed Solution

抽离组件的弹框如何在一个页面引入多个抽离组件的弹框

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by vince292007** [comment]
可以查看 https://www.vben.pro/#/examples/modal 这个页面的代码， 就是这种方式。
