### ISSUE TITLE
Bug: 批量添加表单项时设置默认值defaultValue无效

### ISSUE THREAD

**Issue by 18738433131** [vbenjs/vue-vben-admin#4877]
### Version

Vben Admin V5

### Describe the bug?

![Snipaste_2024-11-12_16-35-25](https://github.com/user-attachments/assets/b5095def-6950-495c-9b65-7ab116b2404e)
![Snipaste_2024-11-12_16-36-08](https://github.com/user-attachments/assets/6424eb53-1154-4c38-bb9a-5fa8b0c262f4)

### Reproduction

从后端获取数据然后循环批量添加表单，defaultValue无论是取后端返回的值还是写死固定值都不生效

### System Info

```shell
sec-ch-ua: "Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
defaultValue只有useVbenForm第一次有效。其他情况下，需要动态更新 values 值就可以了
