### ISSUE TITLE
FEATURE: 表单什么时候发布API呢

### ISSUE THREAD

**Issue by lixiaolong117** [vbenjs/vue-vben-admin#4880]
### Version

Vben Admin V5

### Description

表单什么时候发布API呢

### Proposed Solution

表单什么时候发布API呢

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by anncwb** [comment]
duplicate #4682
