### ISSUE TITLE
Bug: table无限滚动有问题

### ISSUE THREAD

**Issue by chengchengry** [vbenjs/vue-vben-admin#4884]
### Version

Vben Admin V5

### Describe the bug?

<img width="1501" alt="image" src="https://github.com/user-attachments/assets/c53ac597-f3f5-444b-b1aa-e08d00dd2093">

没有标签栏的情况下，gridEvents的scroll事件中isBottom显示错误
![image](https://github.com/user-attachments/assets/dc586207-54a7-4c06-92fc-3724f9052773)

### Reproduction

![image](https://github.com/user-attachments/assets/0d65ef97-4b3c-49b1-9daf-0d31a64886f3)

### System Info

```shell
ios，chorme
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
最新版本没能重现。
![image](https://github.com/user-attachments/assets/e256ed43-175e-4f5f-82a6-fc0293746c87)
