### ISSUE TITLE
Bug: 将另外一个工程集logic成到monorepo之后，在运行web-ele调用logic里面定义的接口的时候，会报错在logic工程中找不到用别名定义的import进去的文件，但是我在logic工程中已经在tsconfig和vite文件中正确设置了别名路径，这是咋回事啊

### ISSUE THREAD

**Issue by MRJJRJRS** [vbenjs/vue-vben-admin#4895]
### Version

Vben Admin V5

### Describe the bug?

Bug: 将另外一个工程集logic成到monorepo之后，在运行web-ele调用logic里面定义的接口的时候，会报错在logic工程中找不到用别名定义的import进去的文件，但是我在logic工程中已经在tsconfig和vite文件中正确设置了别名路径，这是咋回事啊

### Reproduction

Bug: 将另外一个工程集logic成到monorepo之后，在运行web-ele调用logic里面定义的接口的时候，会报错在logic工程中找不到用别名定义的import进去的文件，但是我在logic工程中已经在tsconfig和vite文件中正确设置了别名路径，这是咋回事啊

### System Info

```shell
VUE3,CHROME
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chichunyang** [comment]
是不是应该加到workspace啊
