### ISSUE TITLE
Bug: Element-plus Select不显示Options

### ISSUE THREAD

**Issue by 752337625** [vbenjs/vue-vben-admin#4897]
### Version

Vben Admin V5

### Describe the bug?

Element-plus Select不显示Options
![1731648301755](https://github.com/user-attachments/assets/383d11e9-4a6b-4206-91d1-a726762b6755)
![1731648312302](https://github.com/user-attachments/assets/d528f5d3-d51a-4e87-af85-25880d059965)

### Reproduction

 {
      fieldName: 'status',
      component: 'Select',
      componentProps: {
        placeholder: '状态',
        clearable: true,
        options: [
          {
            label: '成功',
            value: '200',
          },
          {
            label: '失败',
            value: '400',
          },
        ],
      },
    },

### System Info

```shell
Browsers
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
ElementPlus 跟 Ant design vue不同，Select 组件根本就没有 options 属性。
https://element-plus.org/zh-CN/component/select.html#select-api

**Comment by 752337625** [comment]
那我该怎么做呢？教我一下。我使用h函数也不行

**Comment by itwenjian** [comment]
我也遇到了这个问题，请问解决了吗

**Comment by itwenjian** [comment]
<img width="807" alt="image" src="https://github.com/user-attachments/assets/135946b5-a11a-45d8-ad90-c318e649ec1c">
@752337625 这样可以
