### ISSUE TITLE
Bug: Drawer表单通过表单接口setState设置rule非必填，界面无红星显示，但依旧需要验证，需要关闭抽屉再次打开才能恢复正常

### ISSUE THREAD

**Issue by firezihai** [vbenjs/vue-vben-admin#4898]
### Version

Vben Admin V5

### Describe the bug?

有一个创建和编辑账号的Drawer表单，当编辑时，密码是非必填的，所以我在onOpenChange事件中进行表单验证规则的重置。
如果首次点开的是编辑，不会提示密码验证信息，如果首次创建，再点编辑，密码虽然显示非必填，但是会提示密码验证信息，关闭再次编辑就不会提示密码验证信息。

### Reproduction

```

  formApi.setState((prev) => {
        return {
          schema: prev.schema?.map((item) => {
            if (item.fieldName === 'password') {
              return {
                ...item,
                rules:
                  user.value?.id > 0
                    ? z.optional(
                        z.string().min(6, { message: '最少输入6个字符' }),
                      )
                    : z
                        .string({ required_error: '请输入密码' })
                        .min(6, { message: '最少输入6个字符' }),
              };
            }
            return item;
          }),
        };
      });
```

创建：
![image](https://github.com/user-attachments/assets/c4b423f7-954f-4517-9c9d-d4c9c8e2c587)
点创建再点编辑：
![image](https://github.com/user-attachments/assets/82e6d6fe-608a-4914-a8df-132c8f585e82)

### System Info

```shell
browsers
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
参考这个：https://www.vben.pro/#/examples/form/dynamic ，使用下面的方式
```ts
{
      component: 'Input',
      dependencies: {
        rules(values) {
          if (values.field1 === '123') {
            return 'required';
          }
          return null;
        },
        triggerFields: ['field1'],
      },
      fieldName: 'field5',
      help: '当字段1的值为`123`时，必填',
      label: '动态rules',
    },
```

**Comment by firezihai** [comment]
@anncwb 同样的验证规则，同样的组件，顺序不一样，结果却不一样，这样有点匪夷所思。
