### ISSUE TITLE
表格使用多级表头的时候，单元格编辑不生效

### ISSUE THREAD

**Issue by Crystal920514** [vbenjs/vue-vben-admin#490]
### Subject of the feature

当表格使用了多级表头的时候，处在多级表头下的元素，无法使用单元格编辑功能

**Comment by IFnGSiYu** [comment]
这个bug解决了吗

**Comment by js123321** [comment]
我也遇到了这个问题，怎么解决

**Comment by mayunlongtx** [comment]
新版本的已经解决了这个问题，你可以看  #2521  但是我自己使用的时候发现二级的表头可以编辑，但是 三级表头的时候不能生效 你可以先看一下这个。

**Comment by mayunlongtx** [comment]
新版本的已经解决了这个问题，你可以看 #2521 ，我是直接把他的  useColumns.ts  替换了我本地的文件。然后我使用的时候发现二级表头可以编辑，但是三级表头的时候编辑不能生效 ，你可以试一下。 @js123321
