### ISSUE TITLE
Bug: 表格搜索框无法取消

### ISSUE THREAD

**Issue by ZustFengBo** [vbenjs/vue-vben-admin#4901]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/d76fcdb7-0327-4de9-bed0-82e5272ee674)
表格头部的搜索框无法去除。把配置删除了会留下按钮和div区域。
配置如下：
![image](https://github.com/user-attachments/assets/1837ed87-5249-4563-b637-1d02248329a4)
试了官方basic 表格的demo，加上搜索配置之后，然后把配置去掉，就会复现

### Reproduction

官网demo即可复现

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Memory: 14.98 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 9.12.3 - ~/.nvm/versions/node/v22.11.0/bin/pnpm
    Watchman: 2024.05.02.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 130.0.6723.119
    Safari: 17.6
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vince292007** [comment]
找个示例参考下就可以：https://www.vben.pro/#/examples/vxe-table/remote

**Comment by ZustFengBo** [comment]
> 找个示例参考下就可以：https://www.vben.pro/#/examples/vxe-table/remote

用的就是basic的示例
