### ISSUE TITLE
FEATURE: 2版本封装的Table组件挺好用的，能否在5版本中加入呢？

### ISSUE THREAD

**Issue by jxgahxs** [vbenjs/vue-vben-admin#4903]
### Version

Vben Admin V5

### Description

2版本封装的Table组件挺好用的，能否在5版本中加入呢？

### Proposed Solution

加入

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by vince292007** [comment]
基本不会考虑了，目前的vxe表格功能也基本可以代替吧
