### ISSUE TITLE
Bug: 内网离线环境中iconify图标全都不显示

### ISSUE THREAD

**Issue by lztbwlkj** [vbenjs/vue-vben-admin#4905]
### Version

Vben Admin V5

### Describe the bug?

```ts
// v2版本中哦诶之图标服务
import { addAPIProvider, disableCache } from '@iconify/vue';

/**
 * @description IconifyAPI相关配置
 * @see {@link https://docs.iconify.design/api/providers.html}
 */
addAPIProvider('', {
  resources: ['http://127.0.0.1:8084'],
});

disableCache('all');

```
在内网离线环境中iconify图标全都不显示了。由于是用户动态配置的，一个个下载到本地不现实，之前在V2版本中可以通过上面方式配置图标服务，但是V5并没有看到具体的配置，请问V5怎么配置iconify图标的服务

![image](https://github.com/user-attachments/assets/a52c5d0a-4a68-4051-92bd-b59d16cf21b5)

### Reproduction

请问V5怎么配置iconify图标的服务

### System Info

```shell
System:
    OS: macOS 13.7.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 904.75 MB / 40.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.0 - ~/.volta/tools/image/node/20.18.0/bin/node
    npm: 10.8.2 - ~/.volta/tools/image/node/20.18.0/bin/npm
    pnpm: 9.12.3 - ~/.volta/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.70
    Safari: 18.1
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zwtvip** [comment]
#4815 这里有大佬解答了
