### ISSUE TITLE
Bug: 创建新页面跳转路由显示空白

### ISSUE THREAD

**Issue by haioa** [vbenjs/vue-vben-admin#4910]
### Version

Vben Admin V5

### Describe the bug?

新页面代码
```vue
<template>user</template>
```
![image](https://github.com/user-attachments/assets/e996beff-60ca-4c28-be5f-37d2c37a08a6)
![image](https://github.com/user-attachments/assets/f1bed69a-2f24-43f5-a7d3-e2dde3552ba7)

### Reproduction

bug

### System Info

```shell
win
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
用div将user包裹起来。
```
<template>
  <div>user</div>
</template>
```
要使用路由切换动画，子页面必须有且仅能有一个根节点。如果不启用路由动画就没有这个限制。

**Comment by aonoa** [comment]
https://doc.vben.pro/guide/other/faq.html#页面切换后页面空白
