### ISSUE TITLE
Bug: 动态路由左侧菜单不显示，并且会出现多个标签

### ISSUE THREAD

**Issue by itwenjian** [vbenjs/vue-vben-admin#4917]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/3c61cf7d-73d2-4e2d-a2a7-9e2c024510ea)
![image](https://github.com/user-attachments/assets/04af7b16-02b3-4455-b93e-86b59ffdce53)

使用动态路由时，左侧菜单无法显示，并且会出现多个标签

### Reproduction

使用动态路由时，左侧菜单无法显示，并且会出现多个标签

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 64.19 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
    pnpm: 9.12.2 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 131.0.6778.69
    Safari: 17.5
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chichunyang** [comment]
你hide In menu左边当然无法显示了啊。。。另外多个标签是正常的，因为每个地址都不一样都带上了你的动态domain。你可以参考示例，把tab title更新一下把domain加上做区分，好好看示例

**Comment by mynetfan** [comment]
看看文档的菜单和路由章节和以及标签操作例子。
