### ISSUE TITLE
Bug: 集成的vxeTable 如何实现刷新列表和获取搜索表单内容呢

### ISSUE THREAD

**Issue by lixinliA** [vbenjs/vue-vben-admin#4918]
### Version

Vben Admin V2

### Describe the bug?

根据ref获取表单内容时报错

### Reproduction

根据ref获取表单内容时报错

### System Info

```shell
2.2
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lztbwlkj** [comment]
gridApi.query() 刷新当前页面。gridApi.reload() 刷新列表并返回第一页
proxyConfig: {
    ajax: {
      query: async (_, formValues) => {
        return await getQueryAllDeptList(formValues);
      },
    },
  },

这里的formValues就是搜索表单项的

**Comment by mynetfan** [comment]
你连提Issue都这么敷衍的吗？
一边标记vben v2，一边又说vxeTable。说报错也不说详细情况，让别人去猜
