### ISSUE TITLE
Bug: 配置多级路由，页面下钻

### ISSUE THREAD

**Issue by zwtgit** [vbenjs/vue-vben-admin#4919]
### Version

Vben Admin V5

### Describe the bug?

多级路由隐藏之菜单， 但是路径与页面不匹配
点击 隐藏子菜单， 期望是跳转到/#/demos/features/hide-menu-children， 然后在parent页面点击下钻到/#/demos/features/hide-menu-children/children

### Reproduction

https://www.vben.pro/#/demos/features/hide-menu-children/children

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-13620H
    Memory: 15.99 GB / 39.70 GB
  Binaries:
    Node: 22.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.8.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.3 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (130.0.2849.56)
    Internet Explorer: 11.0.22621.3527
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by DesignHhuang** [comment]
细节控吧，这么小的问题都被你发现了，哈哈哈
