### ISSUE TITLE
Bug: 安装依赖报错

### ISSUE THREAD

**Issue by MRJJRJRS** [vbenjs/vue-vben-admin#4921]
### Version

Vben Admin V5

### Describe the bug?

│ C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modules\esbuild\install.js:134
│     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
│           ^
│ Error: Expected "0.24.0" but got "0.21.5"
│     at validateBinaryVersion (C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modu…
│     at C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modules\esbuild\install.js:…
│ Node.js v20.18.0
└─ Failed in 3.3s at C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modules\esbuild
 ELIFECYCLE  Command failed with exit code 1.

### Reproduction

│ C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modules\esbuild\install.js:134
│     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
│           ^
│ Error: Expected "0.24.0" but got "0.21.5"
│     at validateBinaryVersion (C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modu…
│     at C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modules\esbuild\install.js:…
│ Node.js v20.18.0
└─ Failed in 3.3s at C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modules\esbuild
 ELIFECYCLE  Command failed with exit code 1.

### System Info

```shell
│ C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modules\esbuild\install.js:134
│     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
│           ^
│ Error: Expected "0.24.0" but got "0.21.5"
│     at validateBinaryVersion (C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modu…
│     at C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modules\esbuild\install.js:…
│ Node.js v20.18.0
└─ Failed in 3.3s at C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modules\esbuild
 ELIFECYCLE  Command failed with exit code 1.
```

### Relevant log output

```shell
│ C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modules\esbuild\install.js:134
│     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
│           ^
│ Error: Expected "0.24.0" but got "0.21.5"
│     at validateBinaryVersion (C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modu…
│     at C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modules\esbuild\install.js:…
│ Node.js v20.18.0
└─ Failed in 3.3s at C:\Users\JRS\Desktop\test8\vue-vben-admin\node_modules\.pnpm\esbuild@0.24.0\node_modules\esbuild
 ELIFECYCLE  Command failed with exit code 1.
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
删除所有依赖重装就行
