### ISSUE TITLE
Bug: 表单配置项componentProps函数中的参数formApi 缺少 setState 和 updateSchema方法

### ISSUE THREAD

**Issue by zwtvip** [vbenjs/vue-vben-admin#4926]
### Version

Vben Admin V5

### Describe the bug?

无法在表单配置项中更新数据

### Reproduction

![image](https://github.com/user-attachments/assets/aa727cdd-3970-44de-a159-45a37112df0c)
![image](https://github.com/user-attachments/assets/e1c67a87-da80-42ae-9b56-8cee67cdccc5)

### System Info

```shell
win11 edge
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
formApi是在 useVbenVxeGrid 提供的，不是这里。
