### ISSUE TITLE
Bug: 固定底栏，表格自适应失效

### ISSUE THREAD

**Issue by finalreturn** [vbenjs/vue-vben-admin#4927]
### Version

Vben Admin V5

### Describe the bug?

开启底栏，并固定。表格height:'auto' 将失效

### Reproduction

![C5AB09B7-F75B-45e7-A967-36CFC090B624](https://github.com/user-attachments/assets/6d11a949-29b4-42a3-ac42-53a945463223)

### System Info

```shell
chorme
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
duplicate #4614
