### ISSUE TITLE
FEATURE: 怎么在自己开发的页面中触发框架的菜单按钮点击事件

### ISSUE THREAD

**Issue by 4396mingkai** [vbenjs/vue-vben-admin#4930]
### Version

Vben Admin V5

### Description

![1732067239445](https://github.com/user-attachments/assets/f31d063a-f389-43a1-aea5-84fbf2a46fde)

### Proposed Solution

如图，左侧菜单栏，头部导航栏等公共框架自带的公共组件按钮的触发事件支不支持在自己的页面中调用呢

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by anncwb** [comment]
自行查看示例代码，有相应的函数
