### ISSUE TITLE
Bug: select默认值有展示但取不到

### ISSUE THREAD

**Issue by remind** [vbenjs/vue-vben-admin#4933]
### Version

Vben Admin V5

### Describe the bug?

设置方式：
<img width="551" alt="image" src="https://github.com/user-attachments/assets/4e9718ef-618a-47d6-915c-1712f059e071">
页面效果：
<img width="506" alt="image" src="https://github.com/user-attachments/assets/393231b5-3073-4c02-ae01-97185c18b52d">
获取方式：
<img width="433" alt="image" src="https://github.com/user-attachments/assets/b39c1359-fc26-4a41-aba3-b9df34ecf2ef">
获取到的值：
<img width="1250" alt="image" src="https://github.com/user-attachments/assets/a7b2d0b7-187c-4c02-9b34-9c0ad3743eeb">

### Reproduction

<script lang="ts" setup>
import { Page } from '@vben/common-ui';

import { Card } from 'ant-design-vue';

import { useVbenForm } from '#/adapter/form';
import { getUnionQuery } from '#/api';

const [QueryForm] = useVbenForm({
  // 所有表单项共用，可单独在表单内覆盖
  commonConfig: {
    // 所有表单项
    componentProps: {
      class: 'w-full',
    },
  },
  // 提交函数
  handleSubmit: onSubmit,
  // 垂直布局，label和input在不同行，值为vertical
  // 水平布局，label和input在同一行
  layout: 'horizontal',
  schema: [
    {
      component: 'Select',
      componentProps: {
        defaultValue:'1',
        options: [
          {
            label: '渠道订单号',
            value: '1',
          },
          {
            label: '业务请求号',
            value: '2',
          },
          {
            label: '机构订单号',
            value: '3',
          },
          {
            label: '机构请求号',
            value: '4',
          },
        ],
      },
      fieldName: 'orderType',
      label: '订单类型',
      formItemClass: 'col-start-1',
    },
    {
      component: 'Input',
      // 对应组件的参数
      componentProps: {
        placeholder: '请输入订单号',
      },
      // 字段名
      fieldName: 'orderId',
      // 界面显示的label
      label: '订单号',
      formItemClass: 'col-start-1',
    },
  ],
  submitButtonOptions: {
    content: '查询',
  },
  actionWrapperClass:'text-center',
  // 大屏一行显示3个，中屏一行显示2个，小屏一行显示1个
  wrapperClass: 'grid-cols-1 md:grid-cols-1 lg:grid-cols-3',
});

function onSubmit(values: Record<string, any>) {
  console.log(values);
  const data =  getUnionQuery(values);
}
</script>

<template>
  <Page>
    <Card title="订单号搜索">
      <QueryForm />
    </Card>
  </Page>
</template>

### System Info

```shell
System:
    OS: macOS 15.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 188.30 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 9.13.0 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.70
    Safari: 18.1
```

### Relevant log output

```shell
No response
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
defaultValue 放在跟componentProps同级就可以

**Comment by remind** [comment]
经测试确实可行，谢谢
