### ISSUE TITLE
FEATURE: 是否可以给ApiSelect等组件增加默认的分页

### ISSUE THREAD

**Issue by gitskybo** [vbenjs/vue-vben-admin#4941]
### Version

Vben Admin V5

### Description

是否可以给ApiSelect等组件增加默认的分页，比方说只查询10条，数据量过大加载起来比较麻烦，使用很忧伤

### Proposed Solution

是否可以给ApiSelect等组件增加默认的分页，比方说只查询10条，数据量过大加载起来比较麻烦，使用很忧伤

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by anncwb** [comment]
现在还没提供 ApiSelect 吧

**Comment by gitskybo** [comment]
> 现在还没提供 ApiSelect 吧

规划里面还做这个组件吗，如果做的话考虑一下加个条件
