### ISSUE TITLE
FEATURE: 短信验证码组件支持前置校验

### ISSUE THREAD

**Issue by 7FreezingPoint** [vbenjs/vue-vben-admin#4951]
### Version

Vben Admin V5

### Description

![1732588738783](https://github.com/user-attachments/assets/0db11299-3033-4a6d-9956-9a7e9cd7db7d)
场景：发送短信验证码之前弹框做其它验证码校验，弹框验证码点完确定无法触发现有倒计时等逻辑

### Proposed Solution

希望可以扩展短信验证码组件，增加回调方法获取组件实例等方式，以支持上述场景

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by mynetfan** [comment]
你去修改`packages/@core/ui-kit/shadcn-ui/src/components/pin-input/input.vue`文件第55行的`handleSend`函数的逻辑就可以了。把 `try` 内部的逻辑替换为你的校验逻辑，校验通过后再执行真正的发送验证码的逻辑
