### ISSUE TITLE
Bug: The behavior of removeSchemaByFields does not match its method name. 

### ISSUE THREAD

**Issue by shixud** [vbenjs/vue-vben-admin#4954]
### Version

Vben Admin V5

### Describe the bug?

packages/@core/ui-kit/form-ui/src/form-api.ts

removeSchemaByFields 这个函数的实际行为是保留这些字段的表单项，而不是移除它们。

### Reproduction

[https://github.com/vbenjs/vue-vben-admin/blob/main/packages/%40core/ui-kit/form-ui/src/form-api.ts#L184C3-L193C4](url)

### System Info

```shell
v5.4.8
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
fixed #4971
