### ISSUE TITLE
Bug: pnpm build报错

### ISSUE THREAD

**Issue by 1982602388** [vbenjs/vue-vben-admin#4960]
### Version

Vben Admin V5

### Describe the bug?

刚下载的v5源码，pnpm i后，测试打包报错（pnpm i）

### Reproduction

。

### System Info

```shell
Cached:    10 cached, 11 total
  Time:    10.423s
Failed:    @vben/web-ele#build

 ERROR  run failed: command  exited (1)
Waiting for the debugger to disconnect...
 ELIFECYCLE  Command failed with exit code 1.
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 1982602388** [comment]
直接pnpm build就报错，什么代码都没改

**Comment by vince292007** [comment]
你的环境、工具版本需要贴出来，还有执行步骤以及在哪个目录执行的。

**Comment by 1982602388** [comment]
> 你的环境、工具版本需要贴出来，还有执行步骤以及在哪个目录执行的。

node@v20.10.0、pnpm@9.14.2在顶层目录执行的
![Uploading Snipaste_2024-11-27_15-11-50.png…]()

**Comment by Ren58888** [comment]
> 直接pnpm build就报错，什么代码都没改

我也遇到了，打包web-antd出现报错，web-ele打包成功

**Comment by anncwb** [comment]
错误日志有详细的错误信息，需要提供更多的日志

**Comment by liwenhua888** [comment]
新下载的代码，pnpm run build:docs时有错，错误如下：
@vben/docs:build: > @vben/docs@5.5.1 build D:\lwhStudy\nodeVue3\vue-vben-admin\docs
@vben/docs:build: > vitepress build
@vben/docs:build:
@vben/docs:build: 
@vben/docs:build:   vitepress v1.5.0
@vben/docs:build:
@vben/docs:build: - building client + server bundles...
@vben/docs:build: i @nolebase/vitepress-plugin-git-changelog: Prepare to gather git logs...
@vben/docs:build: 
@vben/docs:build:  ERROR  x Build failed in 127ms
@vben/docs:build:
@vben/docs:build: ✖ building client + server bundles...
@vben/docs:build:
@vben/docs:build:  ERROR  build error:
@vben/docs:build: [vite-plugin-pwa:build] Command failed with exit code 128: git config --local core.quotepath false
@vben/docs:build:
@vben/docs:build: fatal: --local can only be used inside a git repository
@vben/docs:build: [vite-plugin-pwa:build] Command failed with exit code 128: git config --local core.quotepath false
@vben/docs:build:
@vben/docs:build: fatal: --local can only be used inside a git repository
@vben/docs:build:     at getFinalError (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/execa@9.5.1/node_modules/execa/lib/return/final-error.js:6:9)
@vben/docs:build:     at makeError (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/execa@9.5.1/node_modules/execa/lib/return/result.js:108:16)
@vben/docs:build:     at getAsyncResult (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/execa@9.5.1/node_modules/execa/lib/methods/main-async.js:167:4)
@vben/docs:build:     at handlePromise (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/execa@9.5.1/node_modules/execa/lib/methods/main-async.js:150:17)
@vben/docs:build:     at async Object.buildStart (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/@nolebase+vitepress-plugin-git-changelog@2.11.1_@algolia+client-search@5.15.0_@types+node@22._glwvunpuz6km7icdtwm72ypiq4/node_modules/@nolebase/vitepress-plugin-git-changelog/dist/vite/index.mjs:334:7)
@vben/docs:build:     at async Promise.all (index 6)
@vben/docs:build:     at async PluginDriver.hookParallel (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:20740:9)
@vben/docs:build:     at async file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:21690:13
@vben/docs:build:     at async catchUnfinishedHookActions (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:21158:16)
@vben/docs:build:     at async rollupInternal (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:21687:5)
@vben/docs:build:
@vben/docs:build:  ELIFECYCLE  Command failed with exit code 1.
@vben/docs:build: ERROR: command finished with error: command (D:\lwhStudy\nodeVue3\vue-vben-admin\docs) C:\Users\68817\AppData\Roaming\npm\pnpm.cmd run build exited (1)
@vben/docs#build: command (D:\lwhStudy\nodeVue3\vue-vben-admin\docs) C:\Users\68817\AppData\Roaming\npm\pnpm.cmd run build exited (1)

 Tasks:    7 successful, 8 total
Cached:    7 cached, 8 total
  Time:    4.581s
Failed:    @vben/docs#build

 ERROR  run failed: command  exited (1)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

**Comment by liwenhua888** [comment]
build时错误日志写在哪了？

**Comment by mynetfan** [comment]
> 新下载的代码，pnpm run build:docs时有错，错误如下： @vben/docs:build: > @vben/docs@5.5.1 build D:\lwhStudy\nodeVue3\vue-vben-admin\docs @vben/docs:build: > vitepress build @vben/docs:build: @vben/docs:build: @vben/docs:build: vitepress v1.5.0 @vben/docs:build: @vben/docs:build: - building client + server bundles... @vben/docs:build: i @nolebase/vitepress-plugin-git-changelog: Prepare to gather git logs... @vben/docs:build: @vben/docs:build: ERROR x Build failed in 127ms @vben/docs:build: @vben/docs:build: ✖ building client + server bundles... @vben/docs:build: @vben/docs:build: ERROR build error: @vben/docs:build: [vite-plugin-pwa:build] Command failed with exit code 128: git config --local core.quotepath false @vben/docs:build: @vben/docs:build: fatal: --local can only be used inside a git repository @vben/docs:build: [vite-plugin-pwa:build] Command failed with exit code 128: git config --local core.quotepath false @vben/docs:build: @vben/docs:build: fatal: --local can only be used inside a git repository @vben/docs:build: at getFinalError (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/execa@9.5.1/node_modules/execa/lib/return/final-error.js:6:9) @vben/docs:build: at makeError (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/execa@9.5.1/node_modules/execa/lib/return/result.js:108:16) @vben/docs:build: at getAsyncResult (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/execa@9.5.1/node_modules/execa/lib/methods/main-async.js:167:4) @vben/docs:build: at handlePromise (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/execa@9.5.1/node_modules/execa/lib/methods/main-async.js:150:17) @vben/docs:build: at async Object.buildStart (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/@nolebase+vitepress-plugin-git-changelog@[2.11.1_@algolia](mailto:2.11.1_@algolia)+client-search@[5.15.0_@types](mailto:5.15.0_@types)+node@22._glwvunpuz6km7icdtwm72ypiq4/node_modules/@nolebase/vitepress-plugin-git-changelog/dist/vite/index.mjs:334:7) @vben/docs:build: at async Promise.all (index 6) @vben/docs:build: at async PluginDriver.hookParallel (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:20740:9) @vben/docs:build: at async file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:21690:13 @vben/docs:build: at async catchUnfinishedHookActions (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:21158:16) @vben/docs:build: at async rollupInternal (file:///D:/lwhStudy/nodeVue3/vue-vben-admin/node_modules/.pnpm/rollup@4.28.0/node_modules/rollup/dist/es/shared/node-entry.js:21687:5) @vben/docs:build: @vben/docs:build:  ELIFECYCLE  Command failed with exit code 1. @vben/docs:build: ERROR: command finished with error: command (D:\lwhStudy\nodeVue3\vue-vben-admin\docs) C:\Users\68817\AppData\Roaming\npm\pnpm.cmd run build exited (1) @vben/docs#build: command (D:\lwhStudy\nodeVue3\vue-vben-admin\docs) C:\Users\68817\AppData\Roaming\npm\pnpm.cmd run build exited (1)
> 
> Tasks: 7 successful, 8 total Cached: 7 cached, 8 total Time: 4.581s Failed: @vben/docs#build
> 
> ERROR run failed: command exited (1)  ELIFECYCLE  Command failed with exit code 1.  ELIFECYCLE  Command failed with exit code 1.

构建文档不能使用下载的zip，需要用git clone。你这个报错`--local can only be used inside a git repository`，已经告诉你了只能在一个git存储库中执行
