### ISSUE TITLE
FEATURE: 表单某一行能否增加自定义样式，有时候某个表单字段需要宽度100%，有些是一左一右

### ISSUE THREAD

**Issue by haioa** [vbenjs/vue-vben-admin#4962]
### Version

Vben Admin V5

### Description

![image](https://github.com/user-attachments/assets/fc57505b-b39b-4545-8aaf-e19a93bbff9c)
表单某一行能否增加自定义样式，有时候某个表单字段需要宽度100%，有些是一左一右

### Proposed Solution

![image](https://github.com/user-attachments/assets/fc57505b-b39b-4545-8aaf-e19a93bbff9c)
表单某一行能否增加自定义样式，有时候某个表单字段需要宽度100%，有些是一左一右

### Alternatives Considered

![image](https://github.com/user-attachments/assets/fc57505b-b39b-4545-8aaf-e19a93bbff9c)
表单某一行能否增加自定义样式，有时候某个表单字段需要宽度100%，有些是一左一右

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by mynetfan** [comment]
例子都不看的吗？
https://www.vben.pro/#/examples/form/basic

**Comment by haioa** [comment]
> 例子都不看的吗？ https://www.vben.pro/#/examples/form/basic

非常感谢，先看看例子
