### ISSUE TITLE
Bug: 项目无法导入VbenIcon组件

### ISSUE THREAD

**Issue by haioa** [vbenjs/vue-vben-admin#4964]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/70338ed6-d93f-4120-86b7-414ea3902485)
import { VbenIcon } from '@vben-core/shadcn-ui';
根据演示代码中的\vue-vben-admin\playground\src\views\demos\features\icons\icon-picker.vue文件找到图标显示的组件\vue-vben-admin\packages\@core\ui-kit\shadcn-ui\src\components\icon\icon.vue，但是导入无法识别，想请教是因为什么限制导致的吗

### Reproduction

![image](https://github.com/user-attachments/assets/70338ed6-d93f-4120-86b7-414ea3902485)
import { VbenIcon } from '@vben-core/shadcn-ui';
根据演示代码中的\vue-vben-admin\playground\src\views\demos\features\icons\icon-picker.vue文件找到图标显示的组件\vue-vben-admin\packages\@core\ui-kit\shadcn-ui\src\components\icon\icon.vue，但是导入无法识别，想请教是因为什么限制导致的吗

### System Info

```shell
![image](https://github.com/user-attachments/assets/70338ed6-d93f-4120-86b7-414ea3902485)
import { VbenIcon } from '@vben-core/shadcn-ui';
根据演示代码中的\vue-vben-admin\playground\src\views\demos\features\icons\icon-picker.vue文件找到图标显示的组件\vue-vben-admin\packages\@core\ui-kit\shadcn-ui\src\components\icon\icon.vue，但是导入无法识别，想请教是因为什么限制导致的吗
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by leizhiyou** [comment]
可以使用IconifyIcon 组件

**Comment by leizhiyou** [comment]
import { IconifyIcon } from '@vben/icons';

**Comment by haioa** [comment]
> import { IconifyIcon } from '@vben/icons';

测试了下，不能是使用，我的图标选中之后的值是：ant-design:alipay-circle-outlined

**Comment by haioa** [comment]
> > https://doc.vben.pro/guide/essentials/icons.html
> 
> 使用这个方法显示 第一个不能显示，复制官网文档上的就能显示，这是为什么呢

```
        <span class='icon-[ant-design:alipay-circle-outlined]'></span>
        <span class="icon-[mdi--ab-testing]"></span>
```

**Comment by mynetfan** [comment]
> > > https://doc.vben.pro/guide/essentials/icons.html
> > 
> > 
> > 使用这个方法显示 第一个不能显示，复制官网文档上的就能显示，这是为什么呢
> 
> ```
>         <span class='icon-[ant-design:alipay-circle-outlined]'></span>
>         <span class="icon-[mdi--ab-testing]"></span>
> ```

`<span class="icon-[ant-design--alipay-circle-outlined]"></span>`
图标系列和图标名之间是双横线，不是冒号

**Comment by haioa** [comment]
> > > > https://doc.vben.pro/guide/essentials/icons.html
> > > 
> > > 
> > > 使用这个方法显示 第一个不能显示，复制官网文档上的就能显示，这是为什么呢
> > 
> > 
> > ```
> >         <span class='icon-[ant-design:alipay-circle-outlined]'></span>
> >         <span class="icon-[mdi--ab-testing]"></span>
> > ```
> 
> `<span class="icon-[ant-design--alipay-circle-outlined]"></span>` 图标系列和图标名之间是双横线，不是冒号

非常感谢你的帮助，我已经成功解决问题了

**Comment by haioa** [comment]
抱歉我又出现新问题了
![image](https://github.com/user-attachments/assets/c5c9e31b-d3ab-4dcf-85e8-c0763ac6a3b3)
```vue
      <template #vben_icon="{ row }">
        <span :class="`icon-[${row.vben_icon ? row.vben_icon.replace(':', '--') : ''}]`"></span>{{ row.vben_icon }}
      </template>
```
为什么不能显示另外两个图标
