### ISSUE TITLE
关于icon图标问题，抱歉我又出现新问题了

### ISSUE THREAD

**Issue by haioa** [vbenjs/vue-vben-admin#4968]
抱歉我又出现新问题了
![image](https://github.com/user-attachments/assets/c5c9e31b-d3ab-4dcf-85e8-c0763ac6a3b3)
```vue
      <template #vben_icon="{ row }">
        <span :class="`icon-[${row.vben_icon ? row.vben_icon.replace(':', '--') : ''}]`"></span>{{ row.vben_icon }}
      </template>
```
为什么不能显示另外两个图标

_Originally posted by @haioa in https://github.com/vbenjs/vue-vben-admin/issues/4964#issuecomment-2504155809_

**Comment by axinss** [comment]
你可以使用 VbenIcon 
`import { VbenIcon } from '@vben/common-ui'; `
`<VbenIcon :icon="row.vben_icon "  />`
你使用的这种方式tailwind只给第一个图标做了css设置，所以，1、3因为相同所以能显示。
为什么其他tailwind没有去处理具体原因还不清楚。

**Comment by haioa** [comment]
> <VbenIcon :icon="row.vben_icon " />

![image](https://github.com/user-attachments/assets/b3ab4960-b47e-4f24-9782-883e86afcf3b)
使用这个方式没有这个组件，目前代码是从github拉取最新main分支
```vue
import { VbenIcon } from '@vben/common-ui';
```

**Comment by mynetfan** [comment]
这种方式的图标只有在打包时源码中已经明确使用过的，才会在打包后可用。源代码中没有用过而直接从后台获取或者人工输入的图标名就不行

**Comment by axinss** [comment]
@mynetfan 你说的这种情况是说的提问者，提出的这种情况吗

**Comment by axinss** [comment]
@haioa 在源代码中是有导出该组件的。你可以尝试一下reinstall

**Comment by haioa** [comment]
> @haioa 在源代码中是有导出该组件的。你可以尝试一下reinstall

@axinss 不太明白这个功能操作

**Comment by axinss** [comment]
@haioa 就是 npm run reinstall 或者 pnpm run reinstall  具体看你使用什么包管理器

**Comment by haioa** [comment]
> @haioa 就是 npm run reinstall 或者 pnpm run reinstall 具体看你使用什么包管理器

不太行

**Comment by axinss** [comment]
那你试试使用iconify原生的组件吧。Vben里面也有带。使用下面段。其他参数可以去参考iconify官网
`import {IconifyIcon} from '@vben/icons';`
`<IconifyIcon :icon="row.vben_icon"/>`

**Comment by haioa** [comment]
> @haioa 那你试试使用iconify原生的组件吧。Vben里面也有带。使用下面段。其他参数可以去参考iconify官网 `import {IconifyIcon} from '@vben/icons';` `<IconifyIcon :icon="row.vben_icon"/>`

已成功，非常感谢你的帮助
