### ISSUE TITLE
提问帖：AuthenticationLogin组件点击登录回调

### ISSUE THREAD

**Issue by Lord1910** [vbenjs/vue-vben-admin#4970]
### Version

Vben Admin V5

### Description

AuthenticationLogin组件中怎么在点击的登陆按钮后调用组件中的函数
const formSchema = computed((): VbenFormSchema[] => {
  return [
    {
      component: markRaw(ImgCaptcha),
      fieldName: 'code',
      label: $t('authentication.captcha'),
      rules: z.string().min(1, { message: $t('authentication.captchaTip') }),
    }
  ];
});
其中ImgCaptcha是一个自定义的图片验证码组件，希望点击登陆后调用updateImg实现刷新验证码
const t = ref<string>()
const codeImage = computed(() => {
  return `${apiURL}/captcha?t=${t.value}`
})

const updateImg = () => {
  t.value = String(Date.now())
  sessionStorage.setItem('t', t.value);
};

### Proposed Solution

希望可以点击登录后调用组件中的函数

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by mynetfan** [comment]
#4992 
这个PR里添加了Form插槽使用的说明
