### ISSUE TITLE
Bug: VFormCreate内部返回的表单方法不起作用

### ISSUE THREAD

**Issue by lppoi** [vbenjs/vue-vben-admin#4972]
### Version

Vben Admin V2

### Describe the bug?

![image](https://github.com/user-attachments/assets/30cee3df-6f54-40a4-b72c-0587aee0226d)
useVFormMethods内部好像没有做formItem的update方法绑定，导致此处linkOn内formItem没有update方法更新表单数据，fApi内的表单方法获取的值都是undefined。
![image](https://github.com/user-attachments/assets/f744d4db-07ee-440c-8dfa-34d1a01123a2)
组件使用时 getData获取未undefined

### Reproduction

暂无

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700
    Memory: 12.85 GB / 31.75 GB
  Binaries:
    Node: 18.20.4 - D:\.nvmd\versions\18.20.4\node.EXE
    pnpm: 9.12.2 - D:\npm\node_global\pnpm.CMD
  Browsers:
    Edge: Chromium (130.0.2849.56)
    Internet Explorer: 11.0.19041.4355
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
v2已不在维护，需要自行修复
