### ISSUE TITLE
Bug: 框架性能太差, 页面奔溃

### ISSUE THREAD

**Issue by yuhonyon** [vbenjs/vue-vben-admin#4982]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/9cf83cde-9cd9-4569-99ab-ec728c1b238c)

![image](https://github.com/user-attachments/assets/5480b68e-1518-4aa0-8205-430203943064)

内嵌amis 表格  表头固定后, 表格左右滑动10次左右页面就崩溃, 内嵌V2版本和其他自研框架都没问题

### Reproduction

下载最新版本vben 
将demo页改成amis表格页面
左右滑动页面奔溃
页面有警告 [Violation] Forced reflow while executing JavaScript took 40ms  
页面存在强制回流

### System Info

```shell
mac  m2  chrome  最新版
```

### Validations

- [X] Read the [docs](https://anncwb.github.io/vue-vben-admin-doc/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by anncwb** [comment]
这个不是项目问题，你应该向amis提或者排查自己的写法
