### ISSUE TITLE
Bug: 项目安装依赖启动提示 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'constructor')

### ISSUE THREAD

**Issue by yejing2514** [vbenjs/vue-vben-admin#4998]
### Version

Vben Admin V5

### Describe the bug?

项目安装依赖启动提示 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'constructor')
![微信截图_20241202104427](https://github.com/user-attachments/assets/e320838c-9f1b-493c-9668-0e6c07354e7e)
![微信截图_20241202104433](https://github.com/user-attachments/assets/afd4ed26-25f0-43da-8af0-de6f7b3821dc)

### Reproduction

https://github.com/vbenjs/vue-vben-admin

### System Info

```shell
最新
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
https://github.com/vbenjs/vue-vben-admin/commit/24b9aa44d2c4aedd44323ccad6168b1552a2a05d

**Comment by yejing2514** [comment]
> [24b9aa4](https://github.com/vbenjs/vue-vben-admin/commit/24b9aa44d2c4aedd44323ccad6168b1552a2a05d)

非常感谢

**Comment by LuweeJia** [comment]
我也是报这个错 怎么解决？
