### ISSUE TITLE
Bug: 同一个页面路径不同，来回切换TAB时，表格高度计算出现错误

### ISSUE THREAD

**Issue by mengyix** [vbenjs/vue-vben-admin#5015]
### Version

Vben Admin V5

### Describe the bug?

同一个页面路径不同，来回切换TAB时，表格高度计算出现错误
```vue
const gridOptions: VxeGridProps<RowType> = {
  checkboxConfig: {
    highlight: true,
  },
  exportConfig: {},
  keepSource: true,
  columns: [
    { type: 'checkbox', width: 60 },
    { title: '序号', type: 'seq', width: 50 },
    {
      editRender: {},
      field: 'columnName',
      title: '列名',
      slots: {
        edit: 'edit_columnName',
      },
    },
    {
      field: 'dataType',
      title: '类型',
      slots: {
        edit: 'edit_dataType',
      },
      editRender: {},
    },
    {
      field: 'dataTypeParams',
      title: '类型参数',
      width: '250px',
      slots: {
        edit: 'edit_dataTypeParams',
      },
      editRender: {},
    },
    {
      editRender: {},
      slots: { edit: 'edit_order' },
      field: 'order',
      title: '排序',
      sortable: true,
    },
    {
      editRender: {},
      field: 'comment',
      title: '注释',
      slots: { edit: 'edit_comment' },
    },
    {
      field: 'action',
      fixed: 'right',
      title: '操作',
      width: 300,
      slots: { default: 'action' },
    },
  ],
  editRules: {
    dataTypeParams: [{ required: true, message: '必须填写', type: 'array' }],
  },
  editConfig: {
    mode: 'row',
    trigger: 'click',
  },
  // BUG【来回切换会导致高度计算错误】
  height: 'auto',
  pagerConfig: {
    enabled: false,
  },
  proxyConfig: {
    ajax: {
      query: async ({ page }, formValues) => {
        const result = await pageColumn({
          ...formValues,
          tableId,
        });
        return result;
      },
    },
  },
};
```
https://github.com/user-attachments/assets/f751574f-8807-42e7-93db-5fc4870ebdac

### Reproduction

1

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (22) x64 Intel(R) Core(TM) Ultra 9 185H
    Memory: 5.37 GB / 31.61 GB
  Binaries:
    Node: 20.18.0 - D:\env\nvm\nodejs\node.EXE
    Yarn: 1.22.22 - D:\env\nvm\nodejs\yarn.CMD
    npm: 10.8.2 - D:\env\nvm\nodejs\npm.CMD
    pnpm: 9.13.2 - D:\env\nvm\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (128.0.2739.79)
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zxj176381** [comment]
我也有这样的问题，请问解决了吗？

**Comment by 1982602388** [comment]
自己加个监听重渲染组件看看

**Comment by mynetfan** [comment]
使用了KeepAlive吗？

**Comment by mengyix** [comment]
> 使用了KeepAlive吗？

Vben默认配置，未更改KeepAlive配置

**Comment by zxj176381** [comment]
> 使用了KeepAlive吗？

使用了 KeepAlive

**Comment by zxj176381** [comment]
> https://vxetable.cn/#/component/table/base/autoHeight 看看有关height配置为'auto'时的说明

页面中所有方法都尝试过了，设置 keepAlive 后，切换tab 就会出现这样的问题

**Comment by mynetfan** [comment]
设置了KeepAlive之后，重新激活页面要手动调用表格的高度计算方法。vxeTable文档中说明了只有数据重新加载时才会重新计算高度。

**Comment by zxj176381** [comment]
> > https://vxetable.cn/#/component/table/base/autoHeight 看看有关height配置为'auto'时的说明
> 
> 页面中所有方法都尝试过了，设置 keepAlive 后，切换tab 就会出现这样的问题

尝试下把 minHeight 属性去掉试一下

**Comment by zxj176381** [comment]
> 设置了KeepAlive之后，重新激活页面要手动调用表格的高度计算方法。vxeTable文档中说明了只有数据重新加载时才会重新计算高度。

不设置 keepAlive 也会出现

**Comment by zxj176381** [comment]
> 设置了KeepAlive之后，重新激活页面要手动调用表格的高度计算方法。vxeTable文档中说明了只有数据重新加载时才会重新计算高度。


https://github.com/user-attachments/assets/3d569c65-816f-498f-aa57-d3c6a3e38dfe

这个是没有设置 KeepAlive 的页面

**Comment by zxj176381** [comment]
> > 设置了KeepAlive之后，重新激活页面要手动调用表格的高度计算方法。vxeTable文档中说明了只有数据重新加载时才会重新计算高度。
> 
>  bae1ea1644eb6e66bee70762feeeb055.mp4 
> 这个是没有设置 KeepAlive 的页面

偶先次数挺大的

**Comment by mynetfan** [comment]
是最新版本吗？有没有在playground中能确定重现的方法？

**Comment by zxj176381** [comment]
> 是最新版本吗？有没有在playground中能确定重现的方法？

playground/src/views/examples/vxe-table/remote.vue

playground remte 页面 将调用接口返回时间改为10 即可复现

**Comment by mynetfan** [comment]
已重现。请帮忙看看修改  `packages\effects\common-ui\src\components\page\page.vue`这个文件，在大约77行附近有个setTimeout，将这个时间稍微调长一点（比如100），看这个问题是否有改善

**Comment by zxj176381** [comment]
> 已重现。请帮忙看看修改 `packages\effects\common-ui\src\components\page\page.vue`这个文件，在大约77行附近有个setTimeout，将这个时间稍微调长一点（比如100），看这个问题是否有改善


https://github.com/user-attachments/assets/fbf571e7-7b5a-464a-8886-b5b412778081

有所改善，但是有稍微明显的闪烁问题
