### ISSUE TITLE
Bug: table只有一行数据时有一行空白行

### ISSUE THREAD

**Issue by remind** [vbenjs/vue-vben-admin#5017]
### Version

Vben Admin V5

### Describe the bug?

直接使用基础表格的示例项目，修改数据条数
表格配置：

```
const gridOptions: VxeGridProps<RowType> = {
  columns: [
    { title: '序号', type: 'seq', width: 50 },
    { field: 'name', title: 'Name' },
    { field: 'age', sortable: true, title: 'Age' },
    { field: 'nickname', title: 'Nickname' },
    { field: 'role', title: 'Role' },
    { field: 'address', showOverflow: true, title: 'Address' },
  ],
  data: MOCK_TABLE_DATA,
  pagerConfig: {
    enabled: false,
  },
  sortConfig: {
    multiple: true,
  },
};
```

一行数据效果：
<img width="1105" alt="image" src="https://github.com/user-attachments/assets/8b45eb61-34eb-4eeb-90f8-937a5f521d55">

两行数据效果：
<img width="1051" alt="image" src="https://github.com/user-attachments/assets/121af1ed-5de3-48e6-9a77-43611a921e69">

css中有个最小高度：
<img width="1286" alt="image" src="https://github.com/user-attachments/assets/a929f9eb-1a2d-4e1b-82f3-4342be3eb9f1">

如何不要？

### Reproduction

直接使用基础表格的示例项目，修改数据条数

### System Info

```shell
System:
    OS: macOS 15.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 149.09 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - /usr/local/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.2 - /usr/local/bin/npm
    pnpm: 9.13.0 - /usr/local/bin/pnpm
  Browsers:
    Safari: 18.1
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chichunyang** [comment]
没达到最小高度

**Comment by remind** [comment]
> 没达到最小高度

这个时候能否按实际高度显示

**Comment by mynetfan** [comment]
src\adapter\vxe-table.ts
vxeUI.setConfig中有minHeight
