### ISSUE TITLE
FEATURE: 希望支持在独立窗口打开一个新页面

### ISSUE THREAD

**Issue by wLeeming** [vbenjs/vue-vben-admin#5018]
### Version

Vben Admin V5

### Description

目前的版本, openInNewWindow参数只能实现在新标签页打开页面.     希望支持在独立窗口打开一个新页面 ,并且提供可以控制窗口大小位置的参数

### Proposed Solution

无

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by zwtgit** [comment]
花裤衩大佬的vue-template-admin 有一个open-window.js, [https://github.com/PanJiaChen/vue-element-admin/blob/master/src/utils/open-window.js](url)

**Comment by anncwb** [comment]
@vben/utils内有提供
