### ISSUE TITLE
Bug: 窗口宽度改变 表格宽度会缓慢减小

### ISSUE THREAD

**Issue by imdap** [vbenjs/vue-vben-admin#5027]
### Version

Vben Admin V5

### Describe the bug?

https://github.com/user-attachments/assets/5408409f-8e85-4e02-9021-ab53ac4e3a2e

将https://github.com/vbenjs/vue-vben-admin/commit/17c7ce8f21d79a008ca442c2398c4c8d8883348d#diff-3849673f0d947478f2035cc3b48095d97dd4ba4559113b4df18327ef556dcf0eL506 的hidden加上正常

### Reproduction

改变窗口宽度可复现

### System Info

```shell
最新版本 官网
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by imdap** [comment]
![image](https://github.com/user-attachments/assets/68c9be0a-d999-4e94-8d67-3f8daa48652a)

点这里也能复现

**Comment by simple-ice** [comment]
我也遇到了，vxe的问题，在表格外层套个div设置overflow:hidden
