### ISSUE TITLE
Bug:在使用 Vben Vxe Table 表格 树形结构时是否只支持扁平结构

### ISSUE THREAD

**Issue by BugPcp** [vbenjs/vue-vben-admin#5039]
### Version

Vben Admin V5

### Describe the bug?

在使用 Vben Vxe Table 表格 树形结构时是否只支持扁平结构，如果本身就是处理好的树形结构 我在[vxe-table]官方文档上看是支持的

### Reproduction

<Grid >
      <template #active="{ row }">
        <Tag :color="row.color">{{ row.active === 1 ? '开启' : '关闭'}}</Tag>
      </template>
      <template #title="{ row }">
        <span>{{$t(row.title)}}</span>
      </template>
    </Grid>
    
    treeConfig: {
    transform: true,
    rowField: 'id',
    childrenField: 'children',
  },

### System Info

```shell
无
```

### Relevant log output

```shell
无
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
请查阅VxeTable的文档啊。那个TreeConfig里的transform不能乱配置。当需要从扁平结构转为树形结构时，这个需要为true，就像demo里那样。如果本身就是树形结构，这个必须为false且还需要配置childrenField
