### ISSUE TITLE
Bug: 关闭国际化配置项无效

### ISSUE THREAD

**Issue by LiYuzZ** [vbenjs/vue-vben-admin#5049]
### Version

Vben Admin V2

### Describe the bug?

![image](https://github.com/user-attachments/assets/0356ef6b-6f72-4145-94f2-a21b02fb7524)
如果想在项目中隐藏国际化按钮时，修改localeSetting.ts文件的配置项showPicker:false时无效
![image](https://github.com/user-attachments/assets/4781c211-fae4-4e43-a1c9-d410509a5a77)

这个判断应该语句应该是 && ,我改完可以隐藏掉
![image](https://github.com/user-attachments/assets/d73bf1b9-b907-4c9f-b288-67e9ae7e328a)
不知道是不是BUG

### Reproduction

1

### System Info

```shell
11
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
需要清除本地缓存
