### ISSUE TITLE
Bug: 表格组件（vxe-table）自定义单元格显示异常

### ISSUE THREAD

**Issue by Zhao-sj** [vbenjs/vue-vben-admin#5057]
### Version

Vben Admin V5

### Describe the bug?

使用表格组件[自定义单元格](https://www.vben.pro/#/examples/vxe-table/custom-cell)渲染图片或者多个tag组件会被挤压导致显示不全

### Reproduction

使用表格组件[自定义单元格](https://www.vben.pro/#/examples/vxe-table/custom-cell)渲染图片或者多个tag组件会被挤压导致显示不全

### System Info

```shell
System:
    OS: Windows 11 22631.3880
    CPU: 13th Gen Intel(R) Core(TM) i9-13900H   2.60 GHz
    Memory: 21.3 GB / 32.0 GB
  Binaries:
    Node: 22.11.0 - D:\Application\nodejs\node.exe
    npm: 10.9.0 - D:\Application\nodejs\npm.cmd
    pnpm: 9.14.2 - D:\Application\nodejs\pnpm.cmd
  Browsers:
    Chrome: 131.0.6778.87
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
去看看VxeTable的文档。
 gridOptions.showOverflow = false
