### ISSUE TITLE
Bug: 列表页面底部出现滚动条

### ISSUE THREAD

**Issue by xietongjian** [vbenjs/vue-vben-admin#5065]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/73864940-21b5-419a-9bd3-af723c9b43a3)

### Reproduction

演示环境，列表页面底部出现滚动条

### System Info

```shell
win10 chrome 
Chrome 已是最新版本
版本 131.0.6778.109（正式版本） （64 位）
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by username212-art** [comment]
升级后我的固定列就不生效了
