### ISSUE TITLE
Bug: 昨晚拉了最新的 vben-layout.vue  有样式修改导致vxetable不会自适应宽度 且fixed无效

### ISSUE THREAD

**Issue by huangfe1** [vbenjs/vue-vben-admin#5068]
### Version

Vben Admin V5

### Describe the bug?

   <div
      ref="contentRef"
      class="flex flex-1 flex-col overflow-hidden transition-all duration-300 ease-in"
    >  为啥把overflow-hidden去掉了
<img width="1247" alt="Screenshot 2024-12-07 at 12 47 37" src="https://github.com/user-attachments/assets/49c5eb88-1c62-4975-82fd-4c2ed589855d">

### Reproduction

overflow-hidden

### System Info

```shell
overflow-hidden
```

### Relevant log output

```shell
overflow-hidden
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
拉最近版本测试
