### ISSUE TITLE
Bug: VbenSelect的defaultValue异步设置无效

### ISSUE THREAD

**Issue by mybluecloud** [vbenjs/vue-vben-admin#5070]
### Version

Vben Admin V5

### Describe the bug?

![1](https://github.com/user-attachments/assets/da48de44-aa5d-49a1-bf3a-b6eba8611b74)
![2](https://github.com/user-attachments/assets/98d24a6c-8824-4a03-a079-d756bff19455)
登录页的选择框想要做成动态选项的，但是无论怎么设置都无法修改选择框的默认值，只能是初始化的值

### Reproduction

v5.5.0

### System Info

```shell
Windows 11 专业版
node v22.6.0
npm 10.8.2
pnpm 9.14.2
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mybluecloud** [comment]
![3](https://github.com/user-attachments/assets/21e0ef18-66bd-4a1c-bec1-4ec766f441de)
从后台获取的应该是2，但是一直显示配置文件里面的1，如果不给默认值就一直空着

**Comment by mynetfan** [comment]
修改表单配置的默认值并不能改变表单的当前值，除非重新创建表单或者重置表单。你需要改变的是表单的当前值，而不是默认值

**Comment by mybluecloud** [comment]
> 修改表单配置的默认值并不能改变表单的当前值，除非重新创建表单或者重置表单。你需要改变的是表单的当前值，而不是默认值

我是想着在创建表单的时候从后台获取默认值，你说的思路我明白了，使用FormApi的setValues来实现是吧？只是login.vue里面怎么能拿到FormApi呢？

**Comment by mynetfan** [comment]
你有这种需求，可以修改AuthenticationLogin暴露相关的方法来设置当前表单。

**Comment by mybluecloud** [comment]
> 你有这种需求，可以修改AuthenticationLogin暴露相关的方法来设置当前表单。

好的，我明白了，感谢
