### ISSUE TITLE
Bug: tailwindcss 在 vscode 下没有代码提示，插件已安装

### ISSUE THREAD

**Issue by lamphc** [vbenjs/vue-vben-admin#5080]
### Version

Vben Admin V5

### Describe the bug?

tailwindcss 在 vscode 下没有代码提示，插件已安装，不知道原因？

### Reproduction

tailwindcss 在 vscode 下没有代码提示，插件已安装

### System Info

```shell
tailwindcss 在 vscode 下没有代码提示，插件已安装
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
你打开的是工作区还是文件夹？重启过VSCode没有？

**Comment by frankchen211** [comment]
我是在css文件里有提示，vue文件内没有提示，是vscode直接打开项目文件夹

**Comment by lamphc** [comment]
最新的是哪个版本？

**Comment by lamphc** [comment]
工作区打开就好了
