### ISSUE TITLE
Question: 现在是否有表单提交按钮 loading 的逻辑，如果有的话怎么使用呢

### ISSUE THREAD

**Issue by youtao531** [vbenjs/vue-vben-admin#5084]
### Version

Vben Admin V5

### Describe the bug?

现在是有表单提交按钮 loading 的逻辑，如果有的话怎么使用呢

### Reproduction

现在是有表单提交按钮 loading 的逻辑，如果有的话怎么使用呢

### System Info

```shell
chrome
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
#4985
