### ISSUE TITLE
VbenForm找不到hide或者show  如何隐藏某一字段

### ISSUE THREAD

**Issue by huangfe1** [vbenjs/vue-vben-admin#5087]
### Version

Vben Admin V5

### Describe the bug?

VbenForm找不到hide或者show  如何隐藏某一字段

### Reproduction

VbenForm找不到hide或者show  如何隐藏某一字段

### System Info

```shell
VbenForm找不到hide或者show  如何隐藏某一字段
```

### Relevant log output

```shell
VbenForm找不到hide或者show  如何隐藏某一字段
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
https://doc.vben.pro/components/common-ui/vben-form.html#%E8%A1%A8%E5%8D%95%E8%81%94%E5%8A%A8-1

**Comment by guojia723** [comment]
dependencies: {
        show: false,
        // 随意一个字段改变时，都会触发
        triggerFields: ['field1Switch'],
      }

**Comment by mynetfan** [comment]
https://github.com/vbenjs/vue-vben-admin/issues/5110#issuecomment-2536032776
