### ISSUE TITLE
Bug: Invalid prop: type check failed for prop "modelValue"

### ISSUE THREAD

**Issue by han2-n** [vbenjs/vue-vben-admin#5090]
### Version

Vben Admin V5

### Describe the bug?

[ElementPlus ] When I use the **Select** component, and the **binding value of the Select is an object**, enabling the filterable property causes the input to always reflect the bound value as the search box value (string value).

### Reproduction

1: Code impl
![image](https://github.com/user-attachments/assets/15996e15-b88b-4525-b0b1-a198836704bf)
2: Log result after search on select
![image](https://github.com/user-attachments/assets/0db551e2-d879-42a8-9a67-9994f5ac1d92)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 602.43 MB / 15.85 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.13.2 - ~\AppData\Local\pnpm\pnpm.EXE
    bun: 1.1.18 - ~\AppData\Roaming\npm\bun.CMD
  Browsers:
    Internet Explorer: 11.0.19041.4355
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
Your version?
`ApiSelect` need to set `component` prop value

**Comment by mynetfan** [comment]
More information is needed to infer the problem

**Comment by han2-n** [comment]
I found warn issue: because i **defineModel** must return object 
**But**  i think form data binding is still an issue.

U can see flow and code below 
- Step 1: define value of Select is an object [like element plus guide](https://element-plus.org/en-US/component/select.html#use-value-key-attribute)

```
  {
      // 组件需要在 #/adapter.ts内注册，并加上类型
      component: 'ApiSelect',
      // 对应组件的参数
      componentProps: {
        // 菜单接口转options格式
        afterFetch: (data: { name: string; path: string }[]) => {
          return data.map((item: any) => ({
            label: item.name,
            value: item,  // change here
          }));
        },
        filterable: true, // change here
        valueKey: 'path', // change here
        // 菜单接口
        api: getAllMenusApi,
      },
      // 字段名
      fieldName: 'api',
      // 界面显示的label
      label: 'ApiSelect',
  }
```

- Step 2: Select record then submit data, the data will look like the image below
![image](https://github.com/user-attachments/assets/c3a99a23-77b2-4444-9bb4-3c54e7035aca)
- Step 3: Enter input some text to search then click outside or click submit form
![image](https://github.com/user-attachments/assets/1c8c9e27-df13-4497-a381-dcffc682b2f8)

- So I think the main reason is that it automatically binds the search input data as the value for the form field.

**Expect result**:  must like [Element plust Option filtering](https://element-plus.org/en-US/component/select.html#option-filtering)
- When clicking outside, the search text will automatically clear. And the search text data not be binding for the form field.

**Comment by han2-n** [comment]
This issue occurs in the Select component. I have found that the **onInput** event in **VbenForm** seems to be the cause. 
So i hot fix like: 
```
 componentProps: {
      onInput: undefined,
 },
```
However, it is not sufficient when I am integrating it with VbenApiSelect, as the issue happens again.

> More information is needed to infer the problem

**Comment by han2-n** [comment]
@mynetfan  when I am integrating it with VbenApiSelect, as the issue happens again.
