### ISSUE TITLE
Bug: table使用查询表单 使用select滚动时，滚动到select options的尾部继续滚动会滚动页面

### ISSUE THREAD

**Issue by TengWeiXiang1** [vbenjs/vue-vben-admin#5093]
### Version

Vben Admin V5

### Describe the bug?

table使用查询表单 使用select滚动时，滚动到select options的尾部继续滚动会滚动页面

### Reproduction

table使用查询表单 使用select滚动时，滚动到select options的尾部继续滚动会滚动页面

### System Info

```shell
System:
    OS: macOS 15.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 891.39 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.15.1 - ~/.nvm/versions/node/v20.15.1/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v20.15.1/bin/npm
    pnpm: 9.12.1 - ~/.nvm/versions/node/v20.15.1/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.109
    Edge: 131.0.2903.86
    Safari: 18.1
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
这不算一个BUG。如果确实有这种需求，可以去对应的组件库那边提Issue
