### ISSUE TITLE
Bug: 在 VbenForm 中自定义组件，在自定义组件中用到 VbenTable 无法显示组件，另外 VbenForm 在 adapeter 中异步加载组件，界面中无法正常渲染。

### ISSUE THREAD

**Issue by zxj176381** [vbenjs/vue-vben-admin#5100]
### Version

Vben Admin V5

### Describe the bug?

可能是因为 VbenForm 用到了 VbenTable ，VbenTable 又使用到了 VbenForm, 导致出现该问题

### Reproduction

可能是因为 VbenForm 用到了 VbenTable ，VbenTable 又使用到了 VbenForm, 导致出现该问题

### System Info

```shell
可能是因为 VbenForm 用到了 VbenTable ，VbenTable 又使用到了 VbenForm, 导致出现该问题
```

### Relevant log output

```shell
可能是因为 VbenForm 用到了 VbenTable ，VbenTable 又使用到了 VbenForm, 导致出现该问题
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
什么样的情况下会需要把vbenTable作为vbenForm的子组件？

**Comment by mynetfan** [comment]
异步加载组件需要用defineAsyncComponent包裹import，比如：
```defineAsyncComponent(() =>import('xxxx'))```
```defineAsyncComponent(() =>import('ant-design-vue').then((res) => res.Checkbox))```

**Comment by zxj176381** [comment]
> 什么样的情况下会需要把vbenTable作为vbenForm的子组件？

当编辑一个数据为 Array 时，需要有 新增行，修改row，修改 col, 这个时候需要用到vbenTable
![wechat_2024-12-12_102356_468](https://github.com/user-attachments/assets/2afcb383-a75d-4052-9324-05ac5e03b3f0)

**Comment by zxj176381** [comment]
> 什么样的情况下会需要把vbenTable作为vbenForm的子组件？

如果有其他更好的方式的话，也可以解决该问题的话也可以的

**Comment by zxj176381** [comment]
> 异步加载组件需要用defineAsyncComponent包裹import，比如： `defineAsyncComponent(() =>import('xxxx'))` `defineAsyncComponent(() =>import('ant-design-vue').then((res) => res.Checkbox))`

奥奥，把defineAsyncComponent这个给忘记了

**Comment by zxj176381** [comment]
> 什么样的情况下会需要把vbenTable作为vbenForm的子组件？

无法在 adapter 注册中使用，单独在页面中引入通过 slot 的方式引入是可以使用的。

**Comment by mynetfan** [comment]
> > 什么样的情况下会需要把vbenTable作为vbenForm的子组件？
> 
> 无法在 adapter 注册中使用，单独在页面中引入通过 slot 的方式引入是可以使用的。 感觉像是 table 使用了 form ，form又使用了 table ，好像是因为这样出现了问题

我只是对为什么会有这种需求感到好奇

**Comment by mynetfan** [comment]
> > 什么样的情况下会需要把vbenTable作为vbenForm的子组件？
> 
> 当编辑一个数据为 Array 时，需要有 新增行，修改row，修改 col, 这个时候需要用到vbenTable ![wechat_2024-12-12_102356_468](https://private-user-images.githubusercontent.com/52518826/394984172-2afcb383-a75d-4052-9324-05ac5e03b3f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzUwMDYsIm5iZiI6MTczMzk3NDcwNiwicGF0aCI6Ii81MjUxODgyNi8zOTQ5ODQxNzItMmFmY2IzODMtYTc1ZC00MDUyLTkzMjQtMDVhYzVlMDNiM2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAzMzgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZTY3MDEwMzY5Nzg0NTQ3MDMwOTM1NTgxMmE5ZTdlY2M0NzAzYjc2MGUyODg3OTM2NDBlYjZiNzk4ZDBkMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eGA1yPmtinjIum9BktMuePrPH4IG7Wz-ejSz0XJ6MfM)

这种情况你可以把下面的表格部分和上面的其它部分分开处理，提交之前合并数据就行了。

**Comment by zxj176381** [comment]
> > > 什么样的情况下会需要把vbenTable作为vbenForm的子组件？
> > 
> > 
> > 当编辑一个数据为 Array 时，需要有 新增行，修改row，修改 col, 这个时候需要用到vbenTable ![wechat_2024-12-12_102356_468](https://private-user-images.githubusercontent.com/52518826/394984172-2afcb383-a75d-4052-9324-05ac5e03b3f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzUwMDYsIm5iZiI6MTczMzk3NDcwNiwicGF0aCI6Ii81MjUxODgyNi8zOTQ5ODQxNzItMmFmY2IzODMtYTc1ZC00MDUyLTkzMjQtMDVhYzVlMDNiM2YwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAzMzgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZTY3MDEwMzY5Nzg0NTQ3MDMwOTM1NTgxMmE5ZTdlY2M0NzAzYjc2MGUyODg3OTM2NDBlYjZiNzk4ZDBkMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eGA1yPmtinjIum9BktMuePrPH4IG7Wz-ejSz0XJ6MfM)
> 
> 这种情况你可以把下面的表格部分和上面的其它部分分开处理，提交之前合并数据就行了。

好吧，那我先这么做把
