### ISSUE TITLE
Bug: VbenPinInput组件输入验证码后再删掉，获取到的验证码是未删除之前的

### ISSUE THREAD

**Issue by TengChongChong** [vbenjs/vue-vben-admin#5104]
### Version

Vben Admin V5

### Describe the bug?

# 复现方式
验证码输入123456，然后删除1~5位，获取到的value依然是6位
![image](https://github.com/user-attachments/assets/fce4a579-3aba-4491-a26a-62bdcbe728b4)
# 修复
/vue-vben-admin/packages/@core/ui-kit/shadcn-ui/src/components/pin-input/input.vue
![image](https://github.com/user-attachments/assets/9bb98d4d-55cf-44d0-9d5a-1611602f679c)
![image](https://github.com/user-attachments/assets/9fe15ee5-be85-4e99-a88c-687b92c8d88c)
![image](https://github.com/user-attachments/assets/9641f367-448b-45da-a114-895be81d514a)

### Reproduction

无

### System Info

```shell
mac chrome
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
这个组件应该本来就被设计为完整输入了才算是一次值的变更，删除部分值在下次完整输入之前，都不算值变更了

**Comment by TengChongChong** [comment]
这样设计如果使用在输入6位就自动提交的场景没问题，
如果是不自动提交的场景，输入6位后删除1位，表单验证还是通过的，建议此场景设置为表单验证不通过
