### ISSUE TITLE
FEATURE: Form组件提供手动控制表单项显隐的api

### ISSUE THREAD

**Issue by HadeAs** [vbenjs/vue-vben-admin#5110]
### Version

Vben Admin V5

### Description

目前表单项显隐的方式只能通过表单项其他字段来控制，无法提供调用api的方式手动控制显隐

### Proposed Solution

期望提供api来手动控制表单项显隐

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by mynetfan** [comment]
联动控制：https://doc.vben.pro/components/common-ui/vben-form#%E8%A1%A8%E5%8D%95%E8%81%94%E5%8A%A8

直接控制：` formApi.updateSchema([{fieldName:'xxx', formItemClass: 'hidden' }])`
