### ISSUE TITLE
Bug: Vxe使用插槽的时候，格式化formatter好像不会生效

### ISSUE THREAD

**Issue by aonoa** [vbenjs/vue-vben-admin#5111]
### Version

Vben Admin V5

### Describe the bug?

表格定义
```
{ field: 'group_lock', title: '分组锁定', formatter: 'formatGroupLock', slots: { default: 'open' }, width: '90' },
```
```
    <Grid>
      <template #open="{ row }">
        <Switch v-model:checked="row.group_lock" />
      </template>
    </Grid>
```
数据
![image](https://github.com/user-attachments/assets/5c1df47b-f4b2-45f0-93d5-d82012a8d6e9)
`formatGroupLock`格式化
```
    vxeUI.formats.add('formatGroupLock', {
      cellFormatMethod({ cellValue }) {
        console.log('formatGroupLock')
        return cellValue !== 1;
      },
    });
```
实际效果
![image](https://github.com/user-attachments/assets/b0f50bce-2746-4523-a80a-e0d7e4c6e96a)
![image](https://github.com/user-attachments/assets/d562a755-75c2-4110-8b58-4a05a9b38269)
同时，控制台中也没有打印formatGroupLock

### Reproduction

如果，不使用`slots`，则格式化正常
表格定义
```
{ field: 'group_lock', title: '分组锁定', formatter: 'formatGroupLock', width: '90' },
```
```
    <Grid>
    </Grid>
```
数据
![image](https://github.com/user-attachments/assets/5c1df47b-f4b2-45f0-93d5-d82012a8d6e9)
`formatGroupLock`格式化
```
    vxeUI.formats.add('formatGroupLock', {
      cellFormatMethod({ cellValue }) {
        console.log('formatGroupLock')
        return cellValue !== 1;
      },
    });
```
实际效果
![image](https://github.com/user-attachments/assets/c128442b-53e2-4ead-916d-ba73a7622e52)
![image](https://github.com/user-attachments/assets/d4fdd16c-19f3-4e5e-83cf-4dd9e9ae0338)
控制台中的格式化时的打印也正常

### System Info

```shell
vben 5.5.0
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
这种问题应该在vxeTable那边提。我猜测可能vxeTable本来就是这样定义的：当提供了插槽时，formatter就不再使用

**Comment by aonoa** [comment]
> 这种问题应该在vxeTable那边提。我猜测可能vxeTable本来就是这样定义的：当提供了插槽时，formatter就不再使用

好的，我先去测试下原始vxe会不会出现这个问题

**Comment by aonoa** [comment]
这个确实是vxe table那边的问题
