### ISSUE TITLE
FEATURE: 滚动条位置问题

### ISSUE THREAD

**Issue by markr512** [vbenjs/vue-vben-admin#5115]
### Version

Vben Admin V5

### Description

在个人偏好里设置顶栏固定的之后,右侧的滚动条还是在最顶端
![image](https://github.com/user-attachments/assets/acdfe6dc-80fe-4efa-8c81-541b1272038f)

### Proposed Solution

希望滚动条能改到顶栏的下端开始

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by mynetfan** [comment]
将Page组件的auto-content-height设为true，滚动条就会出现在内容区域

**Comment by mynetfan** [comment]
演示页面：https://www.vben.pro/#/examples/modal

**Comment by markr512** [comment]
好的 了解了 谢谢
