### ISSUE TITLE
Bug: Select 组件 的 options 不支持响应式

### ISSUE THREAD

**Issue by starryknight1231** [vbenjs/vue-vben-admin#5118]
### Version

Vben Admin V5

### Describe the bug?

通常界面会有一个查询表单，一个table，table通常也会需要格式化字典数据，也就意味着也需要字典数据，所以我获取数据的时候用的是：

// 页面加载时
```
onMounted(async () => {
  dicts.apps = await listAppDict();
});
```
要是我查询form使用 ApiSelect 组件的话，那么页面就需要请求后台两次，所以我再想能不能直接使用 select 组件，直接配置options 使用 dict.apps，但 options 不是响应式的  ,所以是不行的，有什么好的建议吗，非常感谢。

### Reproduction
```
const dicts = reactive({
  apps: [] as Dict[],
});


// 查询表单配置
const formOptions: VbenFormProps = {
  schema: [
   	**{
      component: 'ApiSelect',
      componentProps: {
        api: listAppDict,
      },
      fieldName: 'appCode',
      label: '系统',
    },
    {
      component: 'Select',
      componentProps: {
        options: dicts.apps,
      },
      fieldName: 'appCode',
      label: '系统',
    }**
  ],
  showCollapseButton: false,
};
```
// 表格配置
```
const gridOptions: VxeGridProps<Record<string, any>> = {
  columns: [
    { title: '序号', type: 'seq', width: 50 },
    { field: 'title', title: '系统模块' },
    { field: 'businessType', title: '操作类型' },
    { field: 'requestUrl', title: '请求URL' },
    { field: 'requestIp', title: '操作地址' },
    { field: 'operator', title: '操作人员', width: '100' },
    {
      field: 'status',
      formatter: 'formatBoolean',
      title: '操作状态',
      width: '100',
    },
    { field: 'operTime', title: '操作时间' },
    {
      field: 'appCode',
      formatter: ({ cellValue }) => {
        **return formatDictData(dicts.apps, cellValue);**
      },
      title: '系统',
      width: '100',
    },
    { slots: { default: 'action' }, title: '操作' },
  ],
  data: [],
  proxyConfig: {
    ajax: {
      query: async ({ page }, formValues) => {
        const queryParam = { ...page, ...formValues };
        return await listSysOperLog(queryParam);
      },
    },
  },
};
```
... 
// 页面加载时
```
onMounted(async () => {
  dicts.apps = await listAppDict();
});
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz
    Memory: 2.44 GB / 23.83 GB
  Binaries:
    Node: 20.17.0 - D:\devsoft\nodejs\node.EXE
    npm: 10.8.2 - D:\devsoft\nodejs\npm.CMD
    pnpm: 9.13.2 - D:\devsoft\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (130.0.2849.80)
    Internet Explorer: 11.0.19041.4355
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
componentProps 改成函数

**Comment by starryknight1231** [comment]
> componentProps 改成函数

非常感谢，的确好用，没注意这个可以写函数。

  {
    component: 'Select',
    componentProps: () => {
      return {
        options: dicts.apps,
      };
    },
    fieldName: 'appCode',
    label: '系统',
  },
