### ISSUE TITLE
Bug: VbenVxeGrid default sort not working 

### ISSUE THREAD

**Issue by han2-n** [vbenjs/vue-vben-admin#5125]
### Version

Vben Admin V5

### Describe the bug?

When i config default sort like [vxe-table sort](https://vxetable.cn/#/component/grid/proxy/sort)
At the **first time**, sorts param **is empty**

### Reproduction

// Grid configuration
```
const gridOptions: VxeGridProps<RowType> = {
  checkboxConfig: {
    highlight: true,
    labelField: 'name',
  },
  columns: [
    { title: '序号', type: 'seq', width: 50 },
    { align: 'left', title: 'Name', type: 'checkbox', width: 100 },
    { field: 'category', sortable: true, title: 'Category' }, // change here
    { field: 'color', title: 'Color' },
    { field: 'productName', title: 'Product Name' },
    { field: 'price', title: 'Price' },
    { field: 'releaseDate', formatter: 'formatDateTime', title: 'DateTime' },
  ],
  exportConfig: {},
  height: 'auto',
  keepSource: true,
  proxyConfig: {
    ajax: {
      query: async ({ page, sort, sorts }) => {
        console.log('🚀 come here baby ======> ~ query: ~ sort:', sort);
        console.log('🚀 come here baby ======> ~ query: ~ sorts:', sorts);
        return await getExampleTableApi({
          page: page.currentPage,
          pageSize: page.pageSize,
        });
      },
    },
    sort: true, // change here
  },
  sortConfig: { // change here
    defaultSort: {
      field: 'category',
      order: 'desc',
    },
    remote: true,
  },
  toolbarConfig: {
    custom: true,
    export: true,
    // import: true,
    refresh: true,
    zoom: true,
  },
};

```
The first time call method ajax
![image](https://github.com/user-attachments/assets/28bcbc8f-381d-4803-8035-de7f6dbe7132)

**Expect result**:
The default sort must have a value the first time.

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 602.43 MB / 15.85 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.13.2 - ~\AppData\Local\pnpm\pnpm.EXE
    bun: 1.1.18 - ~\AppData\Roaming\npm\bun.CMD
  Browsers:
    Internet Explorer: 11.0.19041.4355
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
This is a `VxeTable` bug.
If `autoLoad` is set to false, the sorting parameters will be missing when the table is refreshed for the first time

**Comment by kexin8** [comment]
版本：5.5.1，将autoLoad设置为true，也不生效

**Comment by mynetfan** [comment]
> 版本：5.5.1，将autoLoad设置为true，也不生效

那是因为useVxeGrid重新包装时，传入VxeGrid的autoLoad永远是false，由useVxeGrid内部管理了自动刷新的逻辑
