### ISSUE TITLE
Bug: ElementPlus's integration VbenApiSelect behaves abnormally in the form after the filtering function is enabled

### ISSUE THREAD

**Issue by han2-n** [vbenjs/vue-vben-admin#5132]
### Version

Vben Admin V5

### Describe the bug?

When using a VbenApiSelect with the filter function enabled in a form, each time you type text to filter, the select value automatically changes to the current search text.

Similar issues: https://github.com/vbenjs/vue-vben-admin/issues/5090

### Reproduction

NA

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700K
    Memory: 14.05 GB / 31.78 GB
  Binaries:
    Node: 20.11.1 - ~\scoop\apps\nodejs-lts\current\node.EXE
    Yarn: 1.22.19 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 10.2.4 - ~\scoop\apps\nodejs-lts\current\npm.CMD
    pnpm: 9.15.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
#5127

**Comment by mynetfan** [comment]
Set form options `disabledOnInputListener` to value `true`.
The `vee-validate` will bind `onInput` on all sub component but conflicts with the filtering function of the `Select`/`SelectV2`... in ElementPlus

**Comment by han2-n** [comment]
> Set form options `disabledOnInputListener` to value `true`. The `vee-validate` will bind `onInput` on all sub components but conflicts with the filtering function of the `Select`/`SelectV2`... in ElementPlus

I set disabledOnInputListener to true, and it only works with Select/SelectV2.
If I use **ApiSelect**, it doesn't work properly.

**Comment by mynetfan** [comment]
```
    {
      component: 'ApiSelect',
      componentProps: {
        afterFetch: (data: { name: string; path: string }[]) => {
          return data.map((item: any) => ({
            label: item.name,
            value: item.path,
          }));
        },
        api: getAllMenusApi,
        filterable: true,
        onBlur: undefined,
      },
      fieldName: 'api',
      label: 'ApiSelect',
      // You need below 2 lines to fix Element plus ApiSelect
      disabledOnChangeListener: true,
      disabledOnInputListener: true,
    },
```
