### ISSUE TITLE
Bug: 组件下拉框Select设置mode：multiple时，在输入框输入文字会出现错误

### ISSUE THREAD

**Issue by tuziyaya** [vbenjs/vue-vben-admin#5136]
### Version

Vben Admin V5

### Describe the bug?

组件下拉框Select设置mode：multiple 时，在输入框输入文字会出现错误，即使options为空，也会自动绑定输入文本的值
![image](https://github.com/user-attachments/assets/91a63c51-d94d-40ce-b154-9f0c07c17f66)

### Reproduction

组件下拉框Select设置mode：multiple时，在输入框输入文字会出现错误

### System Info

```shell
version：5.5.1
error：`value` should be array when `mode` is `multiple` or `tags`
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
是ElementPlus吗？

**Comment by tuziyaya** [comment]
> 是ElementPlus吗？

不是，是antd，并且在上个版本搜索也用不了，这次更新后就直接出现了这个错误

**Comment by mynetfan** [comment]
和ElementPlus的问题一样
等下推一个PR

**Comment by tuziyaya** [comment]
好

**Comment by mynetfan** [comment]
#5127 
#5137 
这两个PR都是为了解决这个问题的。如果你不再合并基础框架的更新了，可以手动同步上述两个PR的改动
