### ISSUE TITLE
Bug:  vxe-table form 收起/展开。。。

### ISSUE THREAD

**Issue by chengang168** [vbenjs/vue-vben-admin#5138]
### Version

Vben Admin V5

### Describe the bug?

设置 collapsed: true， 第二个搜索条件为： Select 组件时， 收起功能失效

const formOptions: VbenFormProps = {
  // 默认展开
  collapsed: true,
  schema: [
    {
      component: 'Input',
      defaultValue: '1',
      fieldName: 'category',
      label: 'Category',
    },
    {
      component: 'Select',
      componentProps: {
        allowClear: true,
        options: [
          {
            label: 'Color1',
            value: '1',
          },
          {
            label: 'Color2',
            value: '2',
          },
        ],
        placeholder: '请选择',
      },
      fieldName: 'color',
      label: 'Color',
    },
    {
      component: 'Input',
      fieldName: 'productName',
      label: 'ProductName',
    },
    {
      component: 'Input',
      fieldName: 'price',
      label: 'Price',
    },
    
    {
      component: 'DatePicker',
      fieldName: 'datePicker',
      label: 'Date',
    },
  ],
  // 控制表单是否显示折叠按钮
  showCollapseButton: true,
  // 是否在字段值改变时提交表单
  submitOnChange: true,
  // 按下回车时是否提交表单
  submitOnEnter: false,
};

### Reproduction

<img width="760" alt="WeChatd101c0769e8d963119f9d8ee45084599" src="https://github.com/user-attachments/assets/e2a6535f-305d-435e-beba-a15d0cc914e0" />

### System Info

```shell
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 218.96 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 14.1.1
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
examples/vxe-table/form.vue  这个页面按照你说的调整Select到第二个时测试了并没有你说的问题。

**Comment by chengang168** [comment]
测试了在24寸屏没有这个问题， 16寸小屏幕有时候出现，有时候不出现

<img width="283" alt="image" src="https://github.com/user-attachments/assets/52ede20b-f46f-4d67-af2e-0953c369081a" />
