### ISSUE TITLE
FEATURE: 菜单badge数字动态修改功能

### ISSUE THREAD

**Issue by xjchen-ysh** [vbenjs/vue-vben-admin#5151]
### Version

Vben Admin V5

### Description

提供一个utils，允许系统通过 http协议|socket 从后台获取到badge，无感刷新到左侧菜单栏上

### Proposed Solution

packages\@core\ui-kit\menu-ui\src\sub-menu.vue
考虑在以上文件中对badge进行computed处理，增加一个全局的store，以route的 name|path 作为key，当store中的值存在时，优先返回store中的badge值，否则以route文件中的配置为准
![image](https://github.com/user-attachments/assets/7d4184d2-1546-468a-98af-65062cc45c43)

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by mynetfan** [comment]
via https://github.com/vbenjs/vue-vben-admin/commit/0f756503ff4cb327eaaf4261b7cb0c7cc26cdcc4
