### ISSUE TITLE
Bug: userInfo.homePath 指定路径时表现异常

### ISSUE THREAD

**Issue by RanMaoting** [vbenjs/vue-vben-admin#5152]
### Version

Vben Admin V5

### Describe the bug?

如图
![image](https://github.com/user-attachments/assets/271cd191-d191-4271-88ff-92daa4dab622)
设置```userInfo.homePath = '/dashboard/more-get';```
同时配置路由
![image](https://github.com/user-attachments/assets/36cc3d01-9c09-445a-bf77-69df3e2fcb4b)
```{
    path: '/dashboard',
    name: 'Dashboard',
    meta: {
      hideChildrenInMenu: true,
      hideInBreadcrumb: true,
      hideInMenu: true,
      hideInTab: true,
      title: $t('page.dashboard.title'),
    },
    children: [
      {
        path: '/dashboard/more-get',
        name: 'DashboardMoreGet',
        component: () => import('#/views/dashboard/more-get/index.vue'),
        meta: {
          title: $t('page.dashboard.moreGet'),
          hideChildrenInMenu: true,
          hideInBreadcrumb: true,
          hideInMenu: true,
          hideInTab: true,
        },
      },
    ],
  },
```

当从登录页面进入时可以跳转到指定的页面,但是当登录后手动修改url地址,配置不会生效,它会直接进入默认的/目录下,如果这时没有配置/analytics,页面就会404

https://github.com/user-attachments/assets/8904e6e4-70ad-4b88-b8d9-999aa75413cc

### Reproduction

/

### System Info

```shell
/
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by axinss** [comment]
那你想要的是什么效果

**Comment by RanMaoting** [comment]
感觉这里应该保持统一,如果指定了homepath路径,那应该不管是通过vuerouter跳转还是在地址栏手动输入都应该进入配置的页面,毕竟默认的/analytics可能是不存在的

**Comment by axinss** [comment]
那你可以配置DEFAULT_HOME_PATH哦

**Comment by RanMaoting** [comment]
不是啊,感觉你没有理解到这里的问题,并不是DEFAULT_HOME_PATH的问题,如果配置DEFAULT_HOME_PATH,但是用户的权限并不能进入这里的地址该怎么办呢,这种情况在实际中开发中应该经常遇到. 比如只有管理员能进入仪表盘查看一些统计信息,而普通用户只有自己的首页并不能进入仪表盘,也进入不了,当用户直接在地址栏输入url时问题就出现了,因为当前用户没有权限进入DEFAULT_HOME_PATH,而现在又不能正确跳转到他自己的首页,会直接进入404,应为DEFAULT_HOME_PATH地址不在当前用户的权限里面

**Comment by axinss** [comment]
确实有这样的问题

**Comment by likui628** [comment]
查了下，vben2有讨论，所以应该是必要的
https://github.com/vbenjs/vue-vben-admin/issues/2069#issuecomment-1294404992
https://github.com/vbenjs/vue-vben-admin/issues/2200#issuecomment-1235167505

**Comment by sosovia** [comment]
框架能不能可以提供一个方法，自动获取到菜单的第一个跳转页面，登录成功之后自动跳转就好了。这样不用配置首页之类的了。因为首页会根据不同的角色path 路径不一样。
