### ISSUE TITLE
Bug: 通过项目中的link访问具体某个组件doc会报错404

### ISSUE THREAD

**Issue by sisterGG** [vbenjs/vue-vben-admin#5155]
### Version

Vben Admin V5

### Describe the bug?

如果没有从https://doc.vben.pro/根路由访问过，直接访问如https://doc.vben.pro/components/common-ui/vben-vxe-table,会报错404(eg.https://doc.vben.pro/xxxxxxxxxxxxx)

### Reproduction

如果没有从https://doc.vben.pro/根路由访问过，直接访问如https://doc.vben.pro/components/common-ui/vben-vxe-table,会报错404(eg.https://doc.vben.pro/xxxxxxxxxxxxx)。可以通过清除浏览器缓存复现

### System Info

```shell
window10,谷歌、火狐浏览器最新版。
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
大概是服务器的rewrite配置问题

**Comment by likui628** [comment]
https://doc.vben.pro/components/common-ui/vben-vxe-table.html
访问这个地址可以的，你试一下

**Comment by mynetfan** [comment]
已复现，稍后修复
