### ISSUE TITLE
Bug: useVbenForm: 操作按钮隐藏导致回车提交失效

### ISSUE THREAD

**Issue by 122531** [vbenjs/vue-vben-admin#5159]
### Version

Vben Admin V5

### Describe the bug?

props.showDefaultActions设置为false后,submitOnEnter设置为true将不起作用,change事件正常

### Reproduction

const [Form, formApi] = useTableForm({
  handleSubmit: () => {
    console.log('onSubmit');
  },
  showDefaultActions: false,
  submitOnEnter: true,
});

### System Info

```shell
window
NODE: '20.14.0'
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by axinss** [comment]
这也不算bug吧。你是想在不使用操作按钮的情况下。也能按回车触发提交？
