### ISSUE TITLE
Bug: modal、drawer 还没有open，就会执行抽离组件的生命周期

### ISSUE THREAD

**Issue by xiaosifeng** [vbenjs/vue-vben-admin#5164]
### Version

Vben Admin V5

### Describe the bug?

modal、drawer 还没有open，就会执行抽离组件的生命周期，
这样就会导致里面声明的变量、生命周期逻辑有问题，
能不能提供一个完全销毁的属性

### Reproduction

无

### System Info

```shell
无
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
connectedComponent传入的是抽离组件定义，不是抽离组件的实例

**Comment by xiaosifeng** [comment]
> connectedComponent传入的是抽离组件定义，不是抽离组件的实例。open和close你可以理解为显示和隐藏，不是创建和销毁

明白，比如说详情页、表单页面要请求接口只能写在打开的回调里？或者说需要 index  -> model -> 再嵌套一个form组件，

**Comment by mynetfan** [comment]
可以写在打开的回调里，也可以打开的时候直接传入数据。弹窗演示页面  https://www.vben.pro/#/examples/modal  有个内外数据共享示例可以参考一下
