### ISSUE TITLE
已解决了

### ISSUE THREAD

**Issue by liuzhiganghaha** [vbenjs/vue-vben-admin#5170]
已解决了

---原始邮件---
发件人: &quot;Li ***@***.***&gt;
发送时间: 2024年12月9日(周一) 下午5:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vbenjs/vue-vben-admin] 新拉的代码启动报错[plugin:vite:css] [sass] An importer must have either canonicalize and load methods, or a findFileUrl method. (Issue #5019)

 
没重现，pnpm install 过程报错了没有
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

_Originally posted by @jiuyi919 in https://github.com/vbenjs/vue-vben-admin/issues/5019#issuecomment-2527391545_

**Comment by liuzhiganghaha** [comment]
麻烦问一下如何解决 的一样mac系统

**Comment by chengazhen** [comment]
你是不是更新项目依赖了

**Comment by chengazhen** [comment]
sass的高版本弃用了 @import 不知道是不是因为这个原因导致的你的问题

**Comment by jiuyi919** [comment]
检查一下全局安装的sass版本是不是太高了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月18日(周三) 下午2:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vbenjs/vue-vben-admin] 已解决了 (Issue #5170)




 
麻烦问一下如何解决 的一样mac系统

**Comment by liuzhiganghaha** [comment]
谢谢 解决了

**Comment by liuzhiganghaha** [comment]
解决了
