### ISSUE TITLE
Bug: pnpm build -- [Error] Loading PostCSS Plugin failed: Cannot find module 'cssnano'

### ISSUE THREAD

**Issue by awsssrD** [vbenjs/vue-vben-admin#5171]
### Version

Vben Admin V5

### Describe the bug?

pnpm build -- [Error] Loading PostCSS Plugin failed: Cannot find module 'cssnano'

### Reproduction

package.json dependencies add line content is "cssnano": "catalog:"

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
    Memory: 14.21 GB / 31.73 GB
  Binaries:
    Node: 20.18.0 - C:\node\node.EXE
    Yarn: 1.22.22 - C:\node\yarn.CMD
    npm: 10.8.2 - C:\node\npm.CMD
    pnpm: 9.15.0 - C:\node\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
```

### Validations

- [x] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
是原版clone之后出现的问题还是你子级修改过的？

**Comment by xisuo67** [comment]
> 是原版clone之后出现的问题还是你修改过的？

![image](https://github.com/user-attachments/assets/6580ceff-db58-4aca-a7a3-2db1de6bd80d)
源代码，执行build:antd

**Comment by mynetfan** [comment]
无此问题。请用不带中文的路径完整clone此项目后再测试

**Comment by awsssrD** [comment]
> 无此问题。请用不带中文的路径完整clone此项目后再测试

已测试,解决问题
