### ISSUE TITLE
Bug: 引用当前文件夹下的图片,但是最终路径变成了public下的路径

### ISSUE THREAD

**Issue by RanMaoting** [vbenjs/vue-vben-admin#5174]
### Version

Vben Admin V5

### Describe the bug?

如图,使用相对路径引用一张图片背景,发现并没有显示,在devtools里面查看,发现路径变成了public下的路径
![image](https://github.com/user-attachments/assets/80fe92b3-60f5-453f-8115-0cdbe65442c1)
![image](https://github.com/user-attachments/assets/5b0a449b-c0b1-42c3-a8f7-1c04531e3ab1)
如果使用img标签就能正常显示,
查询历史issues感觉应该是```vite-plugin-html```造成的问题,但是和以前的问题感觉又不太一样

### Reproduction

/

### System Info

```shell
/
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
https://cn.vitejs.dev/guide/assets.html
