### ISSUE TITLE
Bug: vxe-table分组表头无分割线

### ISSUE THREAD

**Issue by howard1994** [vbenjs/vue-vben-admin#5175]
### Version

Vben Admin V5

### Describe the bug?

分组表头的分割线显示异常

### Reproduction

![image](https://github.com/user-attachments/assets/c0baa777-8529-4c03-baf1-19ebf524ef45)
![image](https://github.com/user-attachments/assets/ec7303c1-1deb-4b4a-a5df-d0355aed399e)

### System Info

```shell
vbenJs：v5.5.1
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
未启用border的时候，这个50%高度的分割线是用来拖拽调整列宽的，不能调整的地方就不会显示这个分割线。
可以配置border属性控制表格显示完整的分割线。

这是vxeTable本身的设计，如果觉得不合理，可以去那边提Issue
