### ISSUE TITLE
十分不理解 为什么取消了自定义tools 这并不会增加额外的维护 且造成了我的项目自定义的tools全部没了

### ISSUE THREAD

**Issue by huangfe1** [vbenjs/vue-vben-admin#5189]
### Version

Vben Admin V5

### Describe the bug?

十分不理解 为什么取消了自定义tools 这并不会增加额外的维护 且造成了我的项目自定义的tools全部没了

### Reproduction

十分不理解 为什么取消了自定义tools 这并不会增加额外的维护 且造成了我的项目自定义的tools全部没了

### System Info

```shell
十分不理解 为什么取消了自定义tools 这并不会增加额外的维护 且造成了我的项目自定义的tools全部没了
```

### Relevant log output

```shell
十分不理解 为什么取消了自定义tools 这并不会增加额外的维护 且造成了我的项目自定义的tools全部没了
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by likui628** [comment]
不知道你说的是什么

**Comment by mynetfan** [comment]
这种连问题都不说清楚的Issue一点作用都没有，直接关闭

**Comment by huangfe1** [comment]
我拉取最新代码看到你们修复这个问题 我下次尽量提问提清楚 辛苦
fix: grid tools in toolbar config not working as expected (https://github.com/vbenjs/vue-vben-admin/pull/5190)
