### ISSUE TITLE
Bug: eslint 多元写法爆红

### ISSUE THREAD

**Issue by zwtvip** [vbenjs/vue-vben-admin#5192]
### Version

Vben Admin V5

### Describe the bug?

![9bb735a95904ac4acb36aa2f1bf2cce](https://github.com/user-attachments/assets/030c4f19-08ca-43ce-9da6-19878e92d4ab)

### Reproduction

![9bb735a95904ac4acb36aa2f1bf2cce](https://github.com/user-attachments/assets/aec19c1f-cc5a-4ec8-8bb9-875f3de854a4)

### System Info

```shell
w11
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by China-tb** [comment]
![image](https://github.com/user-attachments/assets/9de3e005-02de-456c-946a-d2757c25a94e)

**Comment by zwtvip** [comment]
@China-tb 好的，感谢大佬
