### ISSUE TITLE
Bug: 国际化Bug，切换语言时，查询表单的查询按钮语言没变

### ISSUE THREAD

**Issue by Aaron-AnHe** [vbenjs/vue-vben-admin#5196]
### Version

Vben Admin V5

### Describe the bug?

国际化翻译Bug，切换语言时，查询表单的查询按钮语言没变
![1734683760740](https://github.com/user-attachments/assets/80694192-f7ff-4001-b0df-36b1cf22e014)

### Reproduction

const [Form, formApi] = useTableForm({
  handleSubmit: async () => {
    const formValues = formApi.form.values;
    formApi.setLatestSubmissionValues(toRaw(formValues));
    props.api.reload(formValues);
  },
  handleReset: async () => {
    await formApi.resetForm();
    const formValues = formApi.form.values;
    formApi.setLatestSubmissionValues(formValues);
    props.api.reload(formValues);
  },
  commonConfig: {
    componentProps: {
      class: 'w-full',
    },
  },
  showCollapseButton: true,
  submitButtonOptions: {
    content: $t('common.query'),
  },
  // enter提交
  submitOnEnter: true,
  wrapperClass: 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3',
});

### System Info

```shell
Windows
Edge
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by likui628** [comment]
```
<script lang="ts" setup>
import { Page } from '@vben/common-ui';
import { $t } from '@vben/locales';

import { Card, message } from 'ant-design-vue';

import { useVbenForm } from '#/adapter/form';

const [QueryForm] = useVbenForm({
  // 默认展开
  collapsed: false,
  // 所有表单项共用，可单独在表单内覆盖
  commonConfig: {
    // 所有表单项
    componentProps: {
      class: 'w-full',
    },
  },
  // 提交函数
  handleSubmit: onSubmit,
  // 垂直布局，label和input在不同行，值为vertical
  // 水平布局，label和input在同一行
  layout: 'horizontal',
  schema: [
    {
      // 组件需要在 #/adapter.ts内注册，并加上类型
      component: 'Input',
      // 对应组件的参数
      componentProps: {
        placeholder: '请输入用户名',
      },
      // 字段名
      fieldName: 'username',
      // 界面显示的label
      label: '字符串',
    },
    {
      component: 'InputPassword',
      componentProps: {
        placeholder: '请输入密码',
      },
      fieldName: 'password',
      label: '密码',
    },
    {
      component: 'InputNumber',
      componentProps: {
        placeholder: '请输入',
      },
      fieldName: 'number',
      label: '数字(带后缀)',
      suffix: () => '¥',
    },
    {
      component: 'Select',
      componentProps: {
        allowClear: true,
        filterOption: true,
        options: [
          {
            label: '选项1',
            value: '1',
          },
          {
            label: '选项2',
            value: '2',
          },
        ],
        placeholder: '请选择',
        showSearch: true,
      },
      fieldName: 'options',
      label: '下拉选',
    },
    {
      component: 'DatePicker',
      fieldName: 'datePicker',
      label: '日期选择框',
    },
  ],
  // 是否可展开
  showCollapseButton: true,
  submitButtonOptions: {
    content: $t('common.query'),
  },
  // 大屏一行显示3个，中屏一行显示2个，小屏一行显示1个
  wrapperClass: 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3',
});

const [QueryForm1] = useVbenForm({
  // 默认展开
  collapsed: true,
  collapsedRows: 2,
  // 所有表单项共用，可单独在表单内覆盖
  commonConfig: {
    // 所有表单项
    componentProps: {
      class: 'w-full',
    },
  },
  // 提交函数
  handleSubmit: onSubmit,
  // 垂直布局，label和input在不同行，值为vertical
  // 水平布局，label和input在同一行
  layout: 'horizontal',
  schema: (() => {
    const schema = [];
    for (let index = 0; index < 14; index++) {
      schema.push({
        // 组件需要在 #/adapter.ts内注册，并加上类型
        component: 'Input',
        // 字段名
        fieldName: `field${index}`,
        // 界面显示的label
        label: `字段${index}`,
      });
    }
    return schema;
  })(),
  // 是否可展开
  showCollapseButton: true,
  submitButtonOptions: {
    content: $t('common.query'),
  },
  // 大屏一行显示3个，中屏一行显示2个，小屏一行显示1个
  wrapperClass: 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3',
});

function onSubmit(values: Record<string, any>) {
  message.success({
    content: `form values: ${JSON.stringify(values)}`,
  });
}
</script>

<template>
  <Page
    description="查询表单，常用语和表格组合使用，可进行收缩展开。"
    title="表单组件"
  >
    <Card class="mb-5" title="查询表单，默认展开">
      <QueryForm />
    </Card>
    <Card title="查询表单，默认折叠，折叠时保留2行">
      <QueryForm1 />
    </Card>
  </Page>
</template>

```

https://github.com/user-attachments/assets/e0c5fc22-5dce-4065-8b6d-c204ff2cde74

**Comment by mynetfan** [comment]
厉害啊，这都能发现

**Comment by Aaron-AnHe** [comment]
您好，还是有点问题，现在在单独页面翻译没问题了，但是我切换到其他带有搜索表单的Tab菜单时，另一个搜索表单的搜索按钮还是没切换过来，我是后端佬，这个项目对我难度比较大，没有修复的能力

https://github.com/user-attachments/assets/a5fd6075-2650-4f23-a7a8-c85ccb9b5d47
