### ISSUE TITLE
Bug: 国际化切换的时候，表格的列名没有切换成对应的语言

### ISSUE THREAD

**Issue by recharge-top-up** [vbenjs/vue-vben-admin#5197]
### Version

Vben Admin V5

### Describe the bug?

const gridOptions: VxeGridProps = {
  columns,
  height: 'auto',
  keepSource: true,
  pagerConfig: {},
}
export const columns: VxeGridProps['columns'] = [
  {
    field: '发动机',
    title: $t('translate.globle.enegry'),
    minWidth: 120,
  },
]
form表单的label是可以正常切换的，表格的列名还是显示原来的语言，但是刷新整个页面会显示切换后的语言
是否是这种写法不对？

### Reproduction

const gridOptions: VxeGridProps = {
  columns,
  height: 'auto',
  keepSource: true,
  pagerConfig: {},
}
export const columns: VxeGridProps['columns'] = [
  {
    field: '发动机',
    title: $t('translate.globle.enegry'),
    minWidth: 120,
  },
]

### System Info

```shell
chrome 
windows
vben-admin5.x
```

### Relevant log output

```shell
1
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by likui628** [comment]
https://github.com/vbenjs/vue-vben-admin/issues/5196
