### ISSUE TITLE
Bug: 表头后端排序后刷新数据后，排序的图标无法标为排序（就是点击排序排序按钮会变黄，但是刷新数据后就没了，也无法让他变黄，标识为“筛选状态”）

### ISSUE THREAD

**Issue by daipingfa** [vbenjs/vue-vben-admin#5200]
### Version

Vben Admin V5

### Describe the bug?

Bug: 表头后端排序后刷新数据后，排序的图标无法标为排序（就是点击排序排序按钮会变黄，但是刷新数据后就没了，也无法让他变黄，标识为“筛选状态”）

### Reproduction

Bug: 表头后端排序后刷新数据后，排序的图标无法标为排序（就是点击排序排序按钮会变黄，但是刷新数据后就没了，也无法让他变黄，标识为“筛选状态”）

### System Info

```shell
Bug: 表头后端排序后刷新数据后，排序的图标无法标为排序（就是点击排序排序按钮会变黄，但是刷新数据后就没了，也无法让他变黄，标识为“筛选状态”）
```

### Relevant log output

```shell
Bug: 表头后端排序后刷新数据后，排序的图标无法标为排序（就是点击排序排序按钮会变黄，但是刷新数据后就没了，也无法让他变黄，标识为“筛选状态”）
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by daipingfa** [comment]
Bug: 表头后端排序后刷新数据后，排序的图标无法标为排序（就是点击排序排序按钮会变黄，但是刷新数据后就没了，也无法让他变黄，标识为“筛选状态”）

**Comment by likui628** [comment]
这种最好是能提供一个可以复现的代码块

**Comment by mynetfan** [comment]
看VxeTable的文档。那个刷新按钮默认的code为reload，点击之后会重置所有的排序和当前分页等信息。
你得在toolbarConfig中将refresh配置为{code:'query'}，这样才能在点击刷新按钮后重新查询而不是重置表格
