### ISSUE TITLE
Bug: ApiComponent 渲染 Radio Group 点击无法选中

### ISSUE THREAD

**Issue by zwtvip** [vbenjs/vue-vben-admin#5201]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/118453bd-321d-425f-b3b0-d85c4fc32ac9)
![image](https://github.com/user-attachments/assets/71277996-7c26-4575-a04b-e6453f1babdd)

### Reproduction

ApiComponent 渲染 Radio Group 点击无法选中

### System Info

```shell
win11
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
什么版本？更新到最新版再试

**Comment by zwtvip** [comment]
是最新版本，你试下








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年12月21日(周六) 中午1:57写道:

  

 
什么版本？更新到最新版再试

**Comment by mynetfan** [comment]
看文档。
RadioGroup的v-model为value，
ApiComponent的默认modelPropName为modelValue
