### ISSUE TITLE
FEATURE: 路由配置openInNewWindow模式下携带query

### ISSUE THREAD

**Issue by zwtgit** [vbenjs/vue-vben-admin#5206]
### Version

Vben Admin V5

### Description

openInNewWindow新窗口打开模式下，支持跳转携带参数meta.query

### Proposed Solution

useNavigation中，对openInNewWindow 对 path+query  做转换拼接

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by mynetfan** [comment]
你直接写在path里就行了
