### ISSUE TITLE
Bug: router带值跳转设置form表单值，切换页码没有带参数

### ISSUE THREAD

**Issue by LGX93** [vbenjs/vue-vben-admin#5207]
### Version

Vben Admin V5

### Describe the bug?

![image](https://github.com/user-attachments/assets/3bf6fe98-a501-4791-ad8a-378ea86882cc)
![image](https://github.com/user-attachments/assets/82632a24-b503-4b33-a542-064a58088a62)
![image](https://github.com/user-attachments/assets/441a6573-e7c4-468a-b6c7-d364ef2d846e)

### Reproduction

gridApi.formApi.setValues，设置参数第一次加载正常，不点击查询，直接点击页码没有带上设置的参数。

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 6.84 GB / 15.87 GB
  Binaries:
    Node: 20.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.15.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
需要在设置values后调用一次submitForm将数据提交
