### ISSUE TITLE
Bug: tailwind 配置修改不生效

### ISSUE THREAD

**Issue by frankchen211** [vbenjs/vue-vben-admin#5209]
### Version

Vben Admin V5

### Describe the bug?

修改 internal/tailwind-config/src/index.ts 下的tailwind配置不起作用，甚至清空整个文件，也不影响项目样式，即使清空node_modules/.vite并重启服务。

### Reproduction

例如在config的theme中的extend添加如下项覆盖
```
      spacing: {
        '1': '18rem',
      },
```
vscode的代码提示已是新的18rem，但页面依然是默认值。

删除清空index.ts内容，页面样式也依然正常。

### System Info

```shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (16) x64 AMD Ryzen 9 6900HX with Radeon Graphics
    Memory: 18.41 GB / 29.11 GB
    Container: Yes
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 22.11.0 - ~/.nvm/versions/node/v22.11.0/bin/node
    npm: 10.9.0 - ~/.nvm/versions/node/v22.11.0/bin/npm
    pnpm: 9.15.0 - ~/.nvm/versions/node/v22.11.0/bin/pnpm

Vben Version：5.5.1
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
修改之后，运行一次  `pnpm i`

**Comment by frankchen211** [comment]
> 修改之后，运行一次 `pnpm i`

可以了，谢谢！另外请问如果想在指定的app下修改tailwind配置项，配置插件应该如何操作呢？

**Comment by mynetfan** [comment]
每个app下不是都有个tailwind.config.mjs吗？

**Comment by frankchen211** [comment]
不是太会写，尝试了一下不生效……

```javascript
// export { default as config } from '@vben/tailwind-config';

// // /** @type {import('@vben/tailwind-config').Config} */
/** @type {import('tailwindcss').Config} */

export default {
  // ...config,
  theme: {
    extend: {
      spacing: {
        1: '3.25rem',
        15: '3.75rem',
        128: '32rem',
        144: '36rem',
      },
    },
  },
};
```

**Comment by frankchen211** [comment]
每个app下的tailwind配置如何覆盖呢？

**Comment by zzx18023** [comment]
> 每个app下的tailwind配置如何覆盖呢？ @anncwb @mynetfan

你还需要修改app下的postcss.config.mjs
