### ISSUE TITLE
Bug: vxe-table的column title 国际化切换时不生效

### ISSUE THREAD

**Issue by li-yi-hong** [vbenjs/vue-vben-admin#5213]
### Version

Vben Admin V5

### Describe the bug?

在切换国际化语言时，vxe-table的column title 未跟随变化，只有在强制刷新时才会变化。

### Reproduction

1. 在定义columns时，使用 $t 进行翻译
import { $t } from '@vben/locales';
export const columns: VxeGridProps['columns'] = [
  { type: 'checkbox', width: 60 },
  {
    field: 'username',
    title: $t('ui.column.username'),
    minWidth: 80,
  },
  {
    field: 'nickName',
    title: $t('ui.column.nickName'),
    minWidth: 130,
  },
 ...
]

![QQ20241223-114144](https://github.com/user-attachments/assets/baaba14f-8438-4a81-8e95-d7765f186186)

### System Info

```shell
no output
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
测试没有重现。请说明可以稳定重现的具体操作步骤

**Comment by li-yi-hong** [comment]
我重新试了下，当 columns 定义在外部文件，例如 vxe-table 在index.vue, 而columns在data.ts中，会出现这个问题。查了下，估计是 $t 方法的调用时机的原因。我用 computed 包裹 columns 后问题得已解决，如下所示：

export const useColumns = () =>
  computed((): VxeGridProps['columns'] => [
    { type: 'checkbox', width: 60 },
    {
      field: 'username',
      title: $t('ui.column.username'),
      minWidth: 80,
    },
    {
      field: 'nickName',
      title: $t('ui.column.nickName'),
      minWidth: 130,
    },
  ...
]
