### ISSUE TITLE
打包时间过长，是项目框架太重了么，如何优化？

### ISSUE THREAD

**Issue by lzb0111** [vbenjs/vue-vben-admin#5217]
### Version

Vben Admin V2

### Description

打包时间过长，是项目框架太重了么，如何优化？

### Proposed Solution

打包时间过长，是项目框架太重了么，如何优化？

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by likui628** [comment]
第一次打包会比较慢，很多子包都需要依次打包。
下一次打包就会比较快了，有缓存的
