### ISSUE TITLE
FEATURE: VXE Table配置项在Vben中无法配置

### ISSUE THREAD

**Issue by sw-Fang** [vbenjs/vue-vben-admin#5218]
### Version

Vben Admin V5

### Description

Vben中Vxe Table的版本已经进行了更新，但Vxe Table新增的属性无法在Vben中进行配置。如vxe-grid中export-config配置的includeFields、excludeFields等新增属性。

### Proposed Solution

添加相应的新增属性。

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by mynetfan** [comment]
怎么会无法配置？你指的是配置无效还是没有类型提示？

**Comment by sw-Fang** [comment]
> 怎么会无法配置？你指的是配置无效还是没有类型提示？

没有类型提示，相应的配置如includeFields、excludeFields等属性也不会生效。项目中vxe-table的版本是【vxe-table: ^4.9.33】。

**Comment by faruzanCN** [comment]
我import { VxeUI } from 'vxe-table';这段代码，页面上会报错[plugin:vite:import-analysis] Failed to resolve import "vxe-table/es/vxe-ui/style.css" from "src/component/index.ts". Does the file exist?

2  |  import "vxe-table/es/vxe-ui/style.css";

但是我根本没写这段代码

**Comment by faruzanCN** [comment]
![image](https://github.com/user-attachments/assets/5782c0ef-769d-4712-8e20-7cd0c3fa3b76)
![image](https://github.com/user-attachments/assets/14ab4140-e2e7-4d31-af53-ecf2adc61bf5)

**Comment by mynetfan** [comment]
> > 怎么会无法配置？你指的是配置无效还是没有类型提示？
> 
> 没有类型提示，相应的配置如includeFields、excludeFields等属性也不会生效。项目中vxe-table的版本是【vxe-table: ^4.9.33】。

我用VxeTable4.9.33的官方最新的版本测试了一下，你列举的这些属性也不会生效。用devTool查看了一下传递到VxeGrid的属性也是正确的，但是却没有生效。
这个应该是VxeTable的版本BUG

**Comment by mynetfan** [comment]
internal\vite-config\src\plugins\vxe-table.ts


> 我import { VxeUI } from 'vxe-table';这段代码，页面上会报错[plugin:vite:import-analysis] Failed to resolve import "vxe-table/es/vxe-ui/style.css" from "src/component/index.ts". Does the file exist?
> 
> 2 | import "vxe-table/es/vxe-ui/style.css";
> 
> 但是我根本没写这段代码

**Comment by faruzanCN** [comment]
> > > 怎么会无法配置？你指的是配置无效还是没有类型提示？
> > 
> > 
> > 没有类型提示，相应的配置如includeFields、excludeFields等属性也不会生效。项目中vxe-table的版本是【vxe-table: ^4.9.33】。
> 
> 我用VxeTable4.9.33的官方最新的版本测试了一下，你列举的这些属性也不会生效。用devTool查看了一下传递到VxeGrid的属性也是正确的，但是却没有生效。 这个应该是VxeTable的版本BUG

还真是，我换到新版本就没这问题了
