### ISSUE TITLE
FEATURE: ApiSelect 请求增加远程搜索的demo

### ISSUE THREAD

**Issue by chengang168** [vbenjs/vue-vben-admin#5221]
### Version

Vben Admin V5

### Description

 期待增加 关键字远程搜索

### Proposed Solution

期待提供远程 检索demo

demo1
  {
      component: 'ApiSelect',
      componentProps: {
        afterFetch: (data: { name: string; path: string }[]) => {
          return data.map((item: any) => ({
            label: item.name,
            value: item.path,
          }));
        },
        // 菜单接口
        api: getAllMenusApi,
      },
      // 字段名
      fieldName: 'api',
      // 界面显示的label
      label: 'ApiSelect',
}

demo2

<template #name>
        <ApiComponent
          component="ApiSelect"
          :api="getListData"
          showSearch
          :filterOption="false"
          placeholder="请输入名称"
        />
</template>

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by mynetfan** [comment]
不同的组件库略有区别，在筛选事件中去修改ApiSelect的params参数就会触发重新请求数据

**Comment by ChHanBin** [comment]
> 不同的组件库略有区别，在筛选事件中去修改ApiSelect的params参数就会触发重新请求数据

请问如何在筛选事件中去修改ApiSelect的params参数呢
