### ISSUE TITLE
FEATURE: 是否可以实现有赞后台的菜单模式？

### ISSUE THREAD

**Issue by 893949088** [vbenjs/vue-vben-admin#5226]
### Version

Vben Admin V5

### Description

<img width="366" alt="image" src="https://github.com/user-attachments/assets/7cad8fa6-7591-404e-bdda-0aca8a6ddf40" />
<img width="330" alt="image" src="https://github.com/user-attachments/assets/669166f1-3f1a-43e6-807f-3ed5955275c8" />

主要是参考菜单显示模式从下拉展开切换成这种分组显示，可以顶部菜单和侧边菜单相结合，可参考小鹅通菜单模式

### Proposed Solution

<img width="366" alt="image" src="https://github.com/user-attachments/assets/7cad8fa6-7591-404e-bdda-0aca8a6ddf40" />
<img width="330" alt="image" src="https://github.com/user-attachments/assets/669166f1-3f1a-43e6-807f-3ed5955275c8" />

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [x] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by anncwb** [comment]
这个不会支持
