### ISSUE TITLE
Bug: 为什么拉取的v2分支源码，修改代码或者console.log都不生效

### ISSUE THREAD

**Issue by m09663676** [vbenjs/vue-vben-admin#5233]
### Version

Vben Admin V2

### Describe the bug?

从vue-vben-admin仓库中拉取的源码，本地运行后，修改代码或者console.log都不生效

### Reproduction

从vue-vben-admin仓库中拉取的源码，本地运行后，修改代码或者console.log都不生效

### System Info

```shell
从vue-vben-admin仓库中拉取的源码，本地运行后，修改代码或者console.log都不生效
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by aonoa** [comment]
你可以把具体的操作步骤写一下
