### ISSUE TITLE
Docs: 在 useVbenForm 中，我如何通过子组件内部的校验规则来校验该组件是否通过呢，而不是通过 form 自带的 rules，我应该如何去做？

### ISSUE THREAD

**Issue by zxj176381** [vbenjs/vue-vben-admin#5241]
### Documentation is

- [ ] Missing
- [ ] Outdated
- [X] Confusing
- [ ] Not sure?

### Explain in Detail

```
   {
      fieldName: 'aiSceneSessionExpressList',
      component: 'TableItem',
      labelWidth: 0,
      formItemClass: 'lg:col-span-6',
      componentProps: {
        minHeight: 300,
        tableTitle: '课文生词列表',
        tableTitleHelp: '点击表格中某一项即可进入编辑状态',
        columns: [
          {
            field: 'orderNo',
            title: '顺序号',
            width: 120,
            editRender: {
              name: 'input',
              placeholder: '请输入',
            },
          },
        ],
        editRules: {
          orderNo: [{ required: true, message: '必须填写' }],
        },
      },
    },
```
`TableItem` 是一个插槽自定义的组件。

以上代码中，我传入了 `editRules` 到子组件中去判断，可是我怎么告诉 VbenForm 我这个组件是不通过的呢？

### Your Suggestion for Changes

征求意见

**Comment by zwtgit** [comment]
submit的时候 用formApi.setValues或formApi.setFieldValue把数据补上

**Comment by zxj176381** [comment]
> submit的时候 用formApi.setValues或formApi.setFieldValue把数据补上

主要是 规则校验 跟数据没有关系

**Comment by mynetfan** [comment]
你说得太笼统。表单的校验规则可以使用自定义的校验函数。如果表单的自定义校验规则也解决不了，就使用插槽配合模板引用，来调用组件自己暴露的校验方法。

**Comment by zxj176381** [comment]
> 你说得太笼统。表单的校验规则可以使用自定义的校验函数。如果表单的自定义校验规则也解决不了，就使用插槽配合模板引用，来调用组件自己暴露的校验方法。

意思就是，插槽里组件暴露出一个方法，在submit 的时候再去通过 ref 调用组件的校验方法，单独去处理这个组件的校验

**Comment by zxj176381** [comment]
> 你说得太笼统。表单的校验规则可以使用自定义的校验函数。如果表单的自定义校验规则也解决不了，就使用插槽配合模板引用，来调用组件自己暴露的校验方法。

有没有一个办法，是可以统一调用的，submit 也会执行组件里的方法的，有没有这样的功能，或者怎么样能实现

**Comment by zxj176381** [comment]
> 你说得太笼统。表单的校验规则可以使用自定义的校验函数。如果表单的自定义校验规则也解决不了，就使用插槽配合模板引用，来调用组件自己暴露的校验方法。

rules 可不可以接收一个异步函数，成功的话就 return true 有错误就返回一个错误信息
这样的功能呢

**Comment by zxj176381** [comment]
> 你说得太笼统。表单的校验规则可以使用自定义的校验函数。如果表单的自定义校验规则也解决不了，就使用插槽配合模板引用，来调用组件自己暴露的校验方法。

如何通过插槽配合模板调用组件暴露的方法呢
不能直接在 插槽组件中定义 ref 属性，在 rules 中通过 ref 调用 暴露的校验方法 会死循环

**Comment by zxj176381** [comment]
@mynetfan
