### ISSUE TITLE
Bug: 持久化标签页没效果

### ISSUE THREAD

**Issue by CupOfBread** [vbenjs/vue-vben-admin#5244]
### Version

Vben Admin V5

### Describe the bug?

持久化标签页功能默认是打开的，但是在标签之间切换的时候，还是会重新加载整个页面。

### Reproduction

持久化标签页功能默认是打开的，但是在标签之间切换的时候，还是会重新加载整个页面。
 ```
 tabbar: {
    keepAlive: true,
    persist: true,
  },
```
没有效果
![image](https://github.com/user-attachments/assets/9c4731f1-39ea-420f-8249-bfdbae36db72)

### System Info

```shell
windows chrome
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
看文档。
需要配置路由的keepAlive，并且还要求路由name与页面组件的name一致。
如果你仍然觉得是BUG，请重新打开此Issue
