### ISSUE TITLE
FEATURE: 关于布局，希望有两外两种模式

### ISSUE THREAD

**Issue by cbombonera** [vbenjs/vue-vben-admin#5253]
### Version

Vben Admin V5

### Description

之前有提过，不过是混合很多问题提的，作者说点点就出来
实在是点不出来

1.上顶部 
  下左菜单 下右内容
和 混合模式有点相似，但是 头部不需要 顶级菜单，菜单还是在右侧
很多场景会需要，比如客户的logo 标题很长

2. 混合模式 左侧菜单 支持 双排

点不出来，也许布局是有的，望告知

### Proposed Solution

同上

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by likui628** [comment]
@cbombonera 最好是给个效果图

**Comment by cbombonera** [comment]
> @cbombonera 最好是给个效果图

第一种
![image](https://github.com/user-attachments/assets/23a86abe-fb5c-454f-aa84-e84659bc8234)

第二种

![image](https://github.com/user-attachments/assets/38f1ab03-d9df-408d-bcff-1730c6d0ad85)

**Comment by mynetfan** [comment]
第二种我看明白了，有人提过。 #5219
你的第一种我没有看懂。

**Comment by mynetfan** [comment]
#5263

**Comment by cbombonera** [comment]
> 第二种我看明白了，有人提过。 #5219 你的第一种我没有看懂，不就是默认的垂直布局吗？

vben的垂直布局  这样侧边栏logo 比如侧边是200px 那么logo或者其他文字 工具在侧边也是最大200
![image](https://github.com/user-attachments/assets/1f86f096-8d43-4ac9-b6e3-e67b4bd9888a)

而我说的布局是下图 vben的混合模式就是这样的布局啊，但是混合模式 是头部是顶级菜单
想要的需求 就是  混合模式的布局，但是 头部不是 顶级菜单，侧边栏是 菜单即可
![image](https://github.com/user-attachments/assets/1cfc98e3-bf50-4461-b1b5-472075c2758a)
