### ISSUE TITLE
Bug: V2版本启动报错@import 'vxe-table/styles/all';

### ISSUE THREAD

**Issue by 1455668754** [vbenjs/vue-vben-admin#5255]
### Version

Vben Admin V2

### Describe the bug?

![1735372343074](https://github.com/user-attachments/assets/8d054f3f-c8a5-42d1-941c-f3617c5353df)

### Reproduction

![1735372343074](https://github.com/user-attachments/assets/8d054f3f-c8a5-42d1-941c-f3617c5353df)

### System Info

```shell
![1735372343074](https://github.com/user-attachments/assets/8d054f3f-c8a5-42d1-941c-f3617c5353df)
```

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vbenjs/vue-vben-admin/discussions) or join our [Discord Chat Server](https://discord.gg/8GuAdwDhj6).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mynetfan** [comment]
不要随意升级依赖
