### ISSUE TITLE
抽屉功能增强：头部增加左侧关闭按钮，用户体验相对好点，底部可以控制按钮组的居中，右侧，左侧排放位置

### ISSUE THREAD

**Issue by sosovia** [vbenjs/vue-vben-admin#5267]
### Version

Vben Admin V5

### Description

抽屉功能增强：头部增加左侧关闭按钮，用户体验相对好点，底部可以控制按钮组的居中，右侧，左侧排放位置。
![89d93de868502b1a15613e522abaab6](https://github.com/user-attachments/assets/34bc677b-d1f4-45cc-875f-9939655f22d5)

### Proposed Solution

正常实现增加功能。

### Validations

- [X] Read the [docs](https://doc.vben.pro/)
- [X] Ensure the code is up to date. (Some issues have been fixed in the latest version)
- [X] I have searched the [existing issues](https://github.com/vbenjs/vue-vben-admin/issues) and checked that my issue does not duplicate any existing issues.

**Comment by mynetfan** [comment]
底部按钮位置通过footer-class控制。
默认为`justify-end`。
你可以设置`justify-start` 居左，`justify-center` 居中。
还可以使用`gap-n`来设置按钮之间的距离
