### ISSUE TITLE
打包以后和本地展示不一样

### ISSUE THREAD

**Issue by ErnestWangZuNian** [vbenjs/vue-vben-admin#650]
打包后的效果 
![image](https://user-images.githubusercontent.com/11648360/119325678-b4989b00-bcb3-11eb-8ebc-ba9848fbb62b.png)

**Comment by ErnestWangZuNian** [comment]
生产环境 
![image](https://user-images.githubusercontent.com/11648360/119333194-2aa10000-bcbc-11eb-87d5-6e133fe4709a.png) 上传文件会说upload,addeventListenter不是一个函数

**Comment by ErnestWangZuNian** [comment]
第一个问题是打包以后
![image](https://user-images.githubusercontent.com/11648360/119370935-75d10800-bce8-11eb-8950-2cce9255037e.png)这个属性的fixed会被覆盖  第二个是打包的时候配置了mock为true 所以出错

**Comment by Even-Lau** [comment]
我也遇到了同样的问题，打包完之后样式完全乱掉了
![image](https://user-images.githubusercontent.com/23427420/144980905-33928b87-65e4-4b77-99ca-f8fb9ccb0611.png)

**Comment by wangjue666** [comment]
感谢您提出的问题！在我维护这个项目之前，似乎已经有人修复了这个问题并且没有关闭这个issue。由于我无法复现该错误，我相信该问题已经解决。如果您仍然遇到类似的问题，请随时告诉我，我会尽力提供帮助！
