### ISSUE TITLE
可不可以添加一个嵌套路由的写法

### ISSUE THREAD

**Issue by wssnail** [vbenjs/vue-vben-admin#663]
### 页面中嵌套路由

有些需求需要在content页面中实现路由的切换，而不会整个页面切换

### Problem

目前整个路由是被vben接管的，只支持层级路由，测试了一下router-view支持的嵌套路由，没有被支持，当拥有子页面时，顶层页面的不使用component: getParentLayout()，直接指向某个具体的页面，会出现404

### Expected behaviour

期望能支持router-view的嵌套路由，或者相关的可替代写法

### Alternatives

1、使用tab来操作的话有比较多的问题需要考虑，层级菜单也不好实现；
2、把菜单写成公共组件引入到所有页面，会出现菜单也回重新加载，不太友好。

**Comment by qqzhangyanhua** [comment]
来督促一下，看到文档上的大黄字不支持嵌套路由，问下有计划进行了么。

**Comment by spionbo** [comment]
需求+1

**Comment by liujianchao1995** [comment]
需求+1

**Comment by jiejie-color** [comment]
为什么不能支持多级路由嵌套啊，有需求问题还是技术问题

**Comment by mercury-zhang** [comment]
现在支持了吗，还以为代码写的有问题
