### ISSUE TITLE
表格组件中可否增加一个可伸缩列的功能

### ISSUE THREAD

**Issue by Dark15** [vbenjs/vue-vben-admin#667]
### Problem
因为有的时候数据长度不一，容易造成显示上有的列过长，有的列又过短，希望增加一个可伸缩列的功能来弥补这一点🧐

### Expected behaviour
![2021-05-28 02 26 21](https://user-images.githubusercontent.com/30013803/119878309-8ee1ef00-bf5c-11eb-9fe3-3020a3152bf5.gif)

**Comment by xietongjian** [comment]
这个功能很有必要

**Comment by anncwb** [comment]
ant design vue 的table伸缩列不是很好用。可以等待下ant design vue v3版本，看看不会回增强

**Comment by zhangfugui727** [comment]
antdv好像没有看到伸缩列的案例，也没有行排序，坐等大佬
