### ISSUE TITLE
请求封装Cascader就像ApiSelect一样使用！

### ISSUE THREAD

**Issue by lorenzozozo** [vbenjs/vue-vben-admin#712]
请求封装Cascader就像ApiSelect一样使用！

**Comment by zhangfugui727** [comment]
拷贝改下就可以了，很简单，换个组件，数据集换成类似TreeData，工具可以从TreeHelper找，然后参照Cascader调整部分属性

**Comment by zhangfugui727** [comment]
更新一下：我看到最新有`ApiTreeSelect`组件了，你拷贝这个，然后改一下差异化属性就可以用了

**Comment by accpman** [comment]
<template>
    <Cascader v-bind="attrs" v-model:value="state" :options="getOptions" @change="handleChange"/>
</template>
<script lang="ts">
    import {defineComponent, PropType, ref,reactive, watchEffect, computed, unref, watch, onMounted} from 'vue';
    import {Cascader} from 'ant-design-vue';
    import {provinceAndCityData, regionData, provinceAndCityDataPlus, regionDataPlus, CodeToText, TextToCode} from "../utils/areaDataUtil";
    import {useRuleFormItem} from "/@/hooks/component/useFormItem";
    import {propTypes} from "/@/utils/propTypes";
    import {useAttrs} from "/@/hooks/core/useAttrs";
    export default defineComponent({
        name: 'JAreaLinkage',
        components: {
            Cascader
        },
        inheritAttrs: false,
        props: {
            value: propTypes.oneOfType([
                propTypes.object,
                propTypes.array
            ]),
            //是否显示区县
            showArea:propTypes.bool.def(true),
            //是否是全部
            showAll:propTypes.bool.def(false)
        },
        emits: ['options-change', 'change'],
        setup(props, {emit,refs}) {
            const emitData = ref<any[]>([]);
            const attrs = useAttrs();
            const [state] = useRuleFormItem(props, 'value', 'change', emitData);
            const getOptions = computed(() => {
                if(props.showArea&&props.showAll){
                    return regionDataPlus
                }
                if(props.showArea&&!props.showAll){
                    return regionData
                }
                if(!props.showArea&&!props.showAll){
                    return provinceAndCityData
                }
                if(!props.showArea&&props.showAll){
                    return provinceAndCityDataPlus
                }
            });
            function handleChange(_, ...args) {
                emitData.value = args;
                console.info(emitData)
            }
            return {
                state,
                attrs,
                regionData,
                getOptions,
                handleChange
            };
        },
    });
</script>

**Comment by accpman** [comment]
[新建文本文档 (4).txt](https://github.com/anncwb/vue-vben-admin/files/7089958/4.txt)
