### ISSUE TITLE
a标签在开发环境中初次加载时可以跟随系统主题颜色，正式环境会失去颜色渲染

### ISSUE THREAD

**Issue by wllgh** [vbenjs/vue-vben-admin#960]
![image](https://user-images.githubusercontent.com/56148263/126629925-962e0ab5-2ed0-4307-8fe0-05b52150cbdf.png)
本地开发环境第一次加载的时候可以看到a标签是跟随系统主题色的，打包正式环境以后会失去a标签会失去颜色渲染，需要手动点击的时候才会跟随系统主题色（开发环境都是没有问题的， 打包发布正式环境有这个问题）
![image](https://user-images.githubusercontent.com/56148263/126634929-9dcc7c51-68c7-4956-93b5-fe2f5c20cddd.png)

**Comment by LestreZhao** [comment]
兄弟  有解不 我也遇到同样问题
