### ISSUE TITLE
Jwt（accessToken + refreshToken） 认证方式的支持

### ISSUE THREAD

**Issue by jiangyimin** [vbenjs/vue-vben-admin#964]
vben中封装了axios的requestInterceptors, responseInterceptors。
但这样的封装缺少了灵活性，使得无法在拦截器中做到 Jwt（accessToken + refreshToken）
的无感刷新。
     比如accessToken 5分钟有效期，refreshToken7天有效期，当返回401后需要拿到refreshToken再
多发一个请求，成功后重新设置accessToken. 
    希望在axios 的包装设计时考虑到这种情况，留下一个扩展点。

目前要解决这个问题，好像只能用定时刷新的方法。

**Comment by r70kg** [comment]
这种情况确实很普遍，用promise缓存请求能解决吗？

**Comment by someGenki** [comment]
还有类似aws cognito的认证方案。即后端返回accessToken + refreshToken +token有效时间。希望可以请求前判断token是否在有效期内，如果不在则先请求新的token再继续请求接口。

**Comment by someGenki** [comment]
提供下自己实现的，位于请求前拦截检查刷新的方式，侵入性感觉挺小的，可以参考下哈
````js
 // src/utils/http/axios/Axios.ts VAxios class中的方法
  // 用于排除不需要token的接口，避免死循环请求
  isNeedTokenURL(url, arr = ['/login', '/refresh', '/getUserInfo']) {
    return !arr.some((val) => url.indexOf(val) > -1);
  }
  // 返回一个promise对象，用于阻塞调用者继续执行。这里面发送刷新请求，成功后清空请求队列
  private refreshTokenBeforeReq(doRefreshTokenApi: () => Promise): Promise<unknown> {
    // 创建一个未完成的promise，把改变状态的resolve方法交给请求token结束后执行
    const promise = new Promise((resolve) => {
      console.log('等待新token');
      // 等待队列放的是一个回调函数，来延迟resolve的执行，以此控制promise状态的改变
      this.waitingQueue.push(() => resolve(null));
    });
    if (!this.refreshing) {
      this.refreshing = true;
      // 模拟请求刷新Token接口，当接口返回数据时执行then方法 TODO 添加catch捕获异常
      new Promise((res) => {
        console.log('刷新token中，正在发起刷新请求');
        setTimeout(() => res(null), 3000);
      }) // 上面使用setTimeout用于体现刷新token的延时，下面才是真实的请求方法
        .then(doRefreshTokenApi())
        .then(() => {
          console.log('刷新token成功，放行所有请求');
          this.refreshing = false;
          this.waitingQueue.length = 0;
          this.waitingQueue.forEach((cb) => cb());
        });
    }
    return promise;
  }
````

````diff
- this.axiosInstance.interceptors.request.use((config: AxiosRequestConfig) => {
+ this.axiosInstance.interceptors.request.use(async (config: AxiosRequestConfig) => {
+      // 无感刷新Token控制开关，可以从createAxios的配置项对象中获取
+      const noSenseSwitchOn = true;
+      // 如果打开无感刷新设置而且是需要Token的请求路径则刷新Token
+      if (noSenseSwitchOn) {
+        // 从store中获取 token过期时间 刷新token的请求方法
+        const { expireTime, doRefreshToken } = useUserStore();
+        if (
+          expireTime !== 0 &&
+          expireTime <= new Date().getTime() &&
+          this.isNeedTokenURL(config.url)
+        ) {
+          // 等待刷新token成功，清空请求队列，改变promise，才得以继续
+          await this.refreshTokenBeforeReq(doRefreshToken);
+        }
+      }
 // If cancel repeat request is turned on, then cancel repeat request is prohibited
      const {
        headers: { ignoreCancelToken },
      } = config;
      
    ......
    
     return config;
   }, undefined);
````

**Comment by someGenki** [comment]
提供下自己实现的，位于请求前检查过期时间拦截刷新的方式，侵入性感觉挺小的，可以参考下

````js
  /* src/utils/http/axios/Axios.ts VAxios class中，多了2个方法 */
  // 用于排除不需要token的接口，避免死循环请求
  private isNeedTokenURL(url, arr = ['/login', '/refresh', '/getUserInfo']) {
    return !arr.some((val) => url.indexOf(val) > -1);
  }
  // 返回一个promise对象，用于阻塞调用者继续执行。这里面发送刷新请求，成功后清空请求队列
  private refreshTokenBeforeReq(doRefreshTokenApi: () => Promise): Promise<unknown> {
    // 创建一个未完成的promise，把改变状态的resolve方法交给请求token结束后执行
    const promise = new Promise((resolve) => {
      console.log('等待新token');
      // 等待队列放的是一个回调函数，来延迟resolve的执行，以此控制promise状态的改变
      this.waitingQueue.push(() => resolve(null));
    });
    if (!this.refreshing) {
      this.refreshing = true;
      // 模拟请求刷新Token接口，当接口返回数据时执行then方法 TODO 添加catch捕获异常
      doRefreshTokenApi().then(() => {
        console.log('刷新token成功，放行队列中的请求');
        this.refreshing = false;
        this.waitingQueue.forEach((cb) => cb());
        this.waitingQueue.length = 0;
      });
    }
    return promise;
  }
````

````diff
- this.axiosInstance.interceptors.request.use((config: AxiosRequestConfig) => {
+ this.axiosInstance.interceptors.request.use(async (config: AxiosRequestConfig) => {
+      // 无感刷新Token控制开关，可以从createAxios的配置项对象中获取
+      const noSenseSwitchOn = true;
+      // 如果打开无感刷新设置而且是需要Token的请求路径则刷新Token
+      if (noSenseSwitchOn) {
+        // 从store中获取 token过期时间 刷新token的请求方法
+        const { expireTime, doRefreshToken } = useUserStore();
+        if (
+          expireTime !== 0 &&
+          expireTime <= new Date().getTime() &&
+          this.isNeedTokenURL(config.url)
+        ) {
+          // 等待刷新token成功，清空请求队列，改变promise，才得以继续
+          await this.refreshTokenBeforeReq(doRefreshToken);
+        }
+      }
 // If cancel repeat request is turned on, then cancel repeat request is prohibited
      const {
        headers: { ignoreCancelToken },
      } = config;
      
    ......
    
     return config;
   }, undefined);
````

**Comment by qingmang** [comment]
> 提供下自己实现的，位于请求前检查过期时间拦截刷新的方式，侵入性感觉挺小的，可以参考下
> 
> ```js
>   /* src/utils/http/axios/Axios.ts VAxios class中，多了2个方法 */
>   // 用于排除不需要token的接口，避免死循环请求
>   private isNeedTokenURL(url, arr = ['/login', '/refresh', '/getUserInfo']) {
>     return !arr.some((val) => url.indexOf(val) > -1);
>   }
>   // 返回一个promise对象，用于阻塞调用者继续执行。这里面发送刷新请求，成功后清空请求队列
>   private refreshTokenBeforeReq(doRefreshTokenApi: () => Promise): Promise<unknown> {
>     // 创建一个未完成的promise，把改变状态的resolve方法交给请求token结束后执行
>     const promise = new Promise((resolve) => {
>       console.log('等待新token');
>       // 等待队列放的是一个回调函数，来延迟resolve的执行，以此控制promise状态的改变
>       this.waitingQueue.push(() => resolve(null));
>     });
>     if (!this.refreshing) {
>       this.refreshing = true;
>       // 模拟请求刷新Token接口，当接口返回数据时执行then方法 TODO 添加catch捕获异常
>       doRefreshTokenApi().then(() => {
>         console.log('刷新token成功，放行队列中的请求');
>         this.refreshing = false;
>         this.waitingQueue.forEach((cb) => cb());
>         this.waitingQueue.length = 0;
>       });
>     }
>     return promise;
>   }
> ```
> 
> ```diff
> - this.axiosInstance.interceptors.request.use((config: AxiosRequestConfig) => {
> + this.axiosInstance.interceptors.request.use(async (config: AxiosRequestConfig) => {
> +      // 无感刷新Token控制开关，可以从createAxios的配置项对象中获取
> +      const noSenseSwitchOn = true;
> +      // 如果打开无感刷新设置而且是需要Token的请求路径则刷新Token
> +      if (noSenseSwitchOn) {
> +        // 从store中获取 token过期时间 刷新token的请求方法
> +        const { expireTime, doRefreshToken } = useUserStore();
> +        if (
> +          expireTime !== 0 &&
> +          expireTime <= new Date().getTime() &&
> +          this.isNeedTokenURL(config.url)
> +        ) {
> +          // 等待刷新token成功，清空请求队列，改变promise，才得以继续
> +          await this.refreshTokenBeforeReq(doRefreshToken);
> +        }
> +      }
>  // If cancel repeat request is turned on, then cancel repeat request is prohibited
>       const {
>         headers: { ignoreCancelToken },
>       } = config;
>       
>     ......
>     
>      return config;
>    }, undefined);
> ```

能不能贴一下完整的

**Comment by someGenki** [comment]
> 能不能贴一下完整的

之前的项目删了，不好意思

**Comment by coderwyd** [comment]
> 提供下自己实现的，位于请求前检查过期时间拦截刷新的方式，侵入性感觉挺小的，可以参考下
> 
> ```js
>   /* src/utils/http/axios/Axios.ts VAxios class中，多了2个方法 */
>   // 用于排除不需要token的接口，避免死循环请求
>   private isNeedTokenURL(url, arr = ['/login', '/refresh', '/getUserInfo']) {
>     return !arr.some((val) => url.indexOf(val) > -1);
>   }
>   // 返回一个promise对象，用于阻塞调用者继续执行。这里面发送刷新请求，成功后清空请求队列
>   private refreshTokenBeforeReq(doRefreshTokenApi: () => Promise): Promise<unknown> {
>     // 创建一个未完成的promise，把改变状态的resolve方法交给请求token结束后执行
>     const promise = new Promise((resolve) => {
>       console.log('等待新token');
>       // 等待队列放的是一个回调函数，来延迟resolve的执行，以此控制promise状态的改变
>       this.waitingQueue.push(() => resolve(null));
>     });
>     if (!this.refreshing) {
>       this.refreshing = true;
>       // 模拟请求刷新Token接口，当接口返回数据时执行then方法 TODO 添加catch捕获异常
>       doRefreshTokenApi().then(() => {
>         console.log('刷新token成功，放行队列中的请求');
>         this.refreshing = false;
>         this.waitingQueue.forEach((cb) => cb());
>         this.waitingQueue.length = 0;
>       });
>     }
>     return promise;
>   }
> ```
> 
> ```diff
> - this.axiosInstance.interceptors.request.use((config: AxiosRequestConfig) => {
> + this.axiosInstance.interceptors.request.use(async (config: AxiosRequestConfig) => {
> +      // 无感刷新Token控制开关，可以从createAxios的配置项对象中获取
> +      const noSenseSwitchOn = true;
> +      // 如果打开无感刷新设置而且是需要Token的请求路径则刷新Token
> +      if (noSenseSwitchOn) {
> +        // 从store中获取 token过期时间 刷新token的请求方法
> +        const { expireTime, doRefreshToken } = useUserStore();
> +        if (
> +          expireTime !== 0 &&
> +          expireTime <= new Date().getTime() &&
> +          this.isNeedTokenURL(config.url)
> +        ) {
> +          // 等待刷新token成功，清空请求队列，改变promise，才得以继续
> +          await this.refreshTokenBeforeReq(doRefreshToken);
> +        }
> +      }
>  // If cancel repeat request is turned on, then cancel repeat request is prohibited
>       const {
>         headers: { ignoreCancelToken },
>       } = config;
>       
>     ......
>     
>      return config;
>    }, undefined);
> ```

请求前判断会出现问题吧？比如修改本地时间之类的

**Comment by wuzhican** [comment]
> 提供下自己实现的，位于请求前检查过期时间拦截刷新的方式，侵入性感觉挺小的，可以参考下
> 
> ```js
>   /* src/utils/http/axios/Axios.ts VAxios class中，多了2个方法 */
>   // 用于排除不需要token的接口，避免死循环请求
>   private isNeedTokenURL(url, arr = ['/login', '/refresh', '/getUserInfo']) {
>     return !arr.some((val) => url.indexOf(val) > -1);
>   }
>   // 返回一个promise对象，用于阻塞调用者继续执行。这里面发送刷新请求，成功后清空请求队列
>   private refreshTokenBeforeReq(doRefreshTokenApi: () => Promise): Promise<unknown> {
>     // 创建一个未完成的promise，把改变状态的resolve方法交给请求token结束后执行
>     const promise = new Promise((resolve) => {
>       console.log('等待新token');
>       // 等待队列放的是一个回调函数，来延迟resolve的执行，以此控制promise状态的改变
>       this.waitingQueue.push(() => resolve(null));
>     });
>     if (!this.refreshing) {
>       this.refreshing = true;
>       // 模拟请求刷新Token接口，当接口返回数据时执行then方法 TODO 添加catch捕获异常
>       doRefreshTokenApi().then(() => {
>         console.log('刷新token成功，放行队列中的请求');
>         this.refreshing = false;
>         this.waitingQueue.forEach((cb) => cb());
>         this.waitingQueue.length = 0;
>       });
>     }
>     return promise;
>   }
> ```
> 
> ```diff
> - this.axiosInstance.interceptors.request.use((config: AxiosRequestConfig) => {
> + this.axiosInstance.interceptors.request.use(async (config: AxiosRequestConfig) => {
> +      // 无感刷新Token控制开关，可以从createAxios的配置项对象中获取
> +      const noSenseSwitchOn = true;
> +      // 如果打开无感刷新设置而且是需要Token的请求路径则刷新Token
> +      if (noSenseSwitchOn) {
> +        // 从store中获取 token过期时间 刷新token的请求方法
> +        const { expireTime, doRefreshToken } = useUserStore();
> +        if (
> +          expireTime !== 0 &&
> +          expireTime <= new Date().getTime() &&
> +          this.isNeedTokenURL(config.url)
> +        ) {
> +          // 等待刷新token成功，清空请求队列，改变promise，才得以继续
> +          await this.refreshTokenBeforeReq(doRefreshToken);
> +        }
> +      }
>  // If cancel repeat request is turned on, then cancel repeat request is prohibited
>       const {
>         headers: { ignoreCancelToken },
>       } = config;
>       
>     ......
>     
>      return config;
>    }, undefined);
> ```

老哥，打个pr呗，直接贴不知道代码的位置啊。

**Comment by codingzZh** [comment]
``` js
responseInterceptorsCatch &&
      isFunction(responseInterceptorsCatch) &&
      this.axiosInstance.interceptors.response.use(undefined, async (error) => {
        if(error?.response?.status === 401) {
          if(!this.isNeedTokenURL(error?.config?.url)) return;
          const { doRefreshToken } = useUserStoreWithOut;
          await this.refreshTokenBeforeReq(doRefreshToken, error?.config);
        } else {
          return responseInterceptorsCatch(axiosInstance, error);
        }
      });
```
我在响应中去监听401，然后按照上述方法，可以成功刷新token，但是在请求队列重新请求后，接口调用成功，但页面数据不刷新，我通过打印看到transformResponseHook触发了2次，第一次拿到数据，但第二次是undefind.
请求队列push方法：
```js
this.waitingQueue.push(this.requsest(config, { apiUrl: '' }));
```

**Comment by likui628** [comment]
https://github.com/vbenjs/vue-vben-admin/pull/4157 参考下这个PR，可以自行去实现

**Comment by codingzZh** [comment]
按照v5版本去修改v2的实现了，但是对于代码的修改量来说有点大。于是在高强度冲浪时，发现了一个基于vben2.x版本的项目`(yudao-ui-vben-admin)`中，添加了刷新token的功能，在此记录一下。

utils/auth.ts

``` javascript
export function getAccessToken(): string {
  return getAuthCache(ACCESS_TOKEN_KEY)
}

export function setAccessToken(value: string) {
  return setAuthCache(ACCESS_TOKEN_KEY, value)
}
```

Axios.ts

``` javascript
...
import { useGlobSetting } from '@/hooks/setting'
// 这里的方法可以自己copy一下
import {getAccessToken, getRefreshToken, setAccessToken} from '@/utils/auth'

const globSetting = useGlobSetting()
// 请求队列
let requestList: any[] = []
// 是否正在刷新中
let isRefreshToken = false

/**
 * @description:  axios 模块
 */

export class VAxios {
  // ...
  refreshToken() {
    const refreshToken = getRefreshToken()
    return axios.post(`${globSetting.apiUrl}/system/auth/refresh-token?refreshToken=${refreshToken}`)
  }
    // 这里根据自己项目后端，处理401可以在异常捕获中写
    // 响应结果拦截器处理
    this.axiosInstance.interceptors.response.use(async (res: AxiosResponse<any>) => {
      const config = res.config
      // 处理 accessToken 过期的情况
      if (res.data.code === 401) {
        // 如果未认证，并且未进行刷新令牌，说明可能是访问令牌过期了
        if (!isRefreshToken) {
          isRefreshToken = true
          // 1. 获取到刷新token
          if (getRefreshToken()) {
            // 2. 进行刷新访问令牌
            try {
              const refreshTokenRes = await this.refreshToken()
              // 2.1 刷新成功，则回放队列的请求 + 当前请求
              setAccessToken(refreshTokenRes.data.data.accessToken)
              ;(config as Recordable).headers.Authorization = `Bearer ${getAccessToken()}`
              requestList.forEach((cb: any) => {
                cb()
              })
              requestList = []
              return new Promise((resolve) => {
                resolve(this.axiosInstance.request(config))
              })
              // res = await Promise.all([this.axiosInstance(config)])[0]
            }
            catch (e) {
              requestList.forEach((cb: any) => {
                cb()
              })
            }
            finally {
              requestList = []
              isRefreshToken = false
            }
          }
        }
        else {
          // 添加到队列，等待刷新获取到新的令牌
          return new Promise((resolve) => {
            requestList.push(() => {
              ;(config as Recordable).headers.Authorization = `Bearer ${getAccessToken()}` // 让每个请求携带自定义token 请根据实际情况自行修改
              resolve(this.axiosInstance(config))
            })
          })
        }
      }
      res && axiosCanceler.removePending(res.config)
      if (responseInterceptors && isFunction(responseInterceptors))
        res = responseInterceptors(res)

      return res
    }, undefined)

    // 响应结果拦截器错误捕获
    responseInterceptorsCatch
      && isFunction(responseInterceptorsCatch)
      && this.axiosInstance.interceptors.response.use(undefined, (error) => {
        return responseInterceptorsCatch(axiosInstance, error)
      })

// ...
}
```
